### ISSUE TITLE
Erreur during import - table with ' character

### ISSUE THREAD

**Issue by lbartoletti** [pgmodeler/pgmodeler#1001]
Hi,

Yes, it's ugly... I have a table named like: "my_schema.ma_table_with_l'accent"

PgModeler can't import this table
```
Could not execute the SQL command.
Message returned: `ERREUR:  erreur de syntaxe sur ou près de « entretien »
LINE 1: ...E cl.attisdropped IS FALSE AND relname='fp_zone_d'entretien'...
```

For information, PgAdmin use double quote to avoid this problem.

Regards.

**Comment by rkhaotix** [comment]
Hi @lbartoletti 

This is an issue relatively easy to solve. I'll add the ability to use ' in the object's name and pgModeler will do the automatic double quotation on it. 

Thanks for reporting!

**Comment by lbartoletti** [comment]
same error for a table  with this character '>'

**Comment by lbartoletti** [comment]
Globally, I think that all non "ascii" character can be return an error.
