### ISSUE TITLE
Fade in/out for found objects

### ISSUE THREAD

**Issue by Mike0007** [pgmodeler/pgmodeler#1004]
I have a quaet bug DB model (~200 tables)  and I think that is not so handy to use "Highlight" function in "Find Object". 
Is it possible to Fade in/out for all found objects? In some cases it will be very usefull.

Regards

**Comment by rkhaotix** [comment]
Hi @Mike0007 

Yes, its possible and seems a great idea. I'll add it to 0.9.1 milestone.

Thanks

**Comment by Mike0007** [comment]
Greait! Will wait for next release.

Thanks

**Comment by Mike0007** [comment]
Hi @rkhaotix ,  
Thank you for so fast implementarion. Only one question: When will be possible to download compeled version 0.9.1-alpha1?

**Comment by rkhaotix** [comment]
Hi @Mike0007 

I'm planning to release alpha1 in a month or less. Initially, I was planning to do that in december but I'll need to be away from pgModeler a bit because my son will born! :)

**Comment by Mike0007** [comment]
Hi @rkhaotix 

Thanks for info and my congratulations!
