### ISSUE TITLE
Easier way to create Relationships

### ISSUE THREAD

**Issue by Zynde** [pgmodeler/pgmodeler#1006]
Hi, 

This is an enhancement request really. Unless I'm missing a shortcut somewhere I find it quite annoying to add relationships. My Schema box takes up all of the screen so to add a relationship I have to scroll to an area where I can right click the background and select New -> Relationship -> ?

It would be nice to have the ability to add a relationship from right clicking a table or schema. Anything else other than having to find the background to click on.

Thanks

**Comment by rkhaotix** [comment]
Hi!

Well, you have two options:

1) If your model has only one schema disable the schema's rectangle so you can click in the gaps between tables.

2) If you want to keep using the schema rectangle, you can select the desired tables so you can link them, hit N. The object creation overlay will be displayed with the relationship types you can create for the table pair. Select the desired one and the relationship form will be opened. 

In future releases I'll improve the way relationships are created, don't worry! ;)

**Comment by Zynde** [comment]
Thanks I didn't know about option 2. A right click off the table would be great.
