### ISSUE TITLE
Payment does not function. Can not download binaries.

### ISSUE THREAD

**Issue by duaneking** [pgmodeler/pgmodeler#1010]
I attempted to buy a copy of the binaries as a way to support you and show my erlier defect filed was in good faith, and apparently, your system thinks either I have too many ad blockers installed, or your payment system doesn't work with my antivirus.  Either way, filing this because you have effectively made it impossible to download or use this project by asking for payment for open source/free software.

EDIT: I ended up buying a copy of not exactly cheap valentina instead because I didn't even have the option of trying out an open source option that could have met my work and personal needs for much cheaper.  Saddened that this project isn't viable, but I'm in a hurry and trying to get work done.

**Comment by rkhaotix** [comment]
Well, I really sorry that pgModeler can't help you. Anyways, I can't let to tell you that you have the source code and the instruction on the official website and can compile it for yourself!
