### ISSUE TITLE
After export, I need to quote table name in SQL.

### ISSUE THREAD

**Issue by Pweilnau** [pgmodeler/pgmodeler#1012]
I successfully exported the model to PostgreSQL 10.  When I use it, it always requires double quotes on table and field names.

SELECT * FROM public."DimPlatform"
ORDER BY "PlatformKey" ASC 

I don't see anyway to control that from pgModeler.  What have I done wrong?

**Comment by rkhaotix** [comment]
You're doing nothing wrong. The name double quoting is an automatic feature and can't be deactivated.

Objects' names are case sensitive. So, DimPlatform is different from dimplatform. In that case, the first one will be always quoted. Even in PostgreSQL, if you name a table DimPlatform you should use double quotes to reference it. This is the default behaviour of both, pgModeler and PostgreSQL.
