### ISSUE TITLE
database import crashed

### ISSUE THREAD

**Issue by NicoBotha** [pgmodeler/pgmodeler#1014]
Hi
Tried to import my first schema without success. 
How do I go about solving this?

![image](https://user-images.githubusercontent.com/11308883/32738031-5db2f102-c8a4-11e7-82ae-f50de6fbbecc.png)

**Comment by rkhaotix** [comment]
Which PostgreSQL?

**Comment by NicoBotha** [comment]
PostgreSQL 10.0 compiled by Visual C++ build 1800, 64 bit

**Comment by rkhaotix** [comment]
I found the problem... Seems the "start_value" is not recognized anymore PostgreSQL 10.1. I'm already providing a patch.

**Comment by NicoBotha** [comment]
Hi

How do I get the patch?

 

Regards

 

Nico Botha

Senior Systems Architect

 

Every great achievement was once considered impossible

 

Cell:     +27 (0)82 579 0578

Fax:     +27 (0)86 593 2632

 

Superitum (Pty) Ltd

Office No A99, Elarduspark Shopping Centre, 

c/n Delmas Road & Barnard street, Elarduspark, Pretoria

PO Box 2004, Newlands, 0049, South Africa

**Comment by rkhaotix** [comment]
If you're using the compiled version (available in the project's site) I'll upload the patched version in the end of this month. If you're able to compile it, you can test right now. Just clone the branch 0.9.1-alpha1 and build it.

Lastly, you can try to do a hack with your current installation. Just copy this file https://github.com/pgmodeler/pgmodeler/blob/0.9.1-alpha1/schemas/catalog/sequence.sch and replace the same file in your installation. For instance, suppose that you've installed pgModeler in ```C:\pgmodeler```, you should replace the file  ```C:\pgmodeler\schemas\catalog\sequence.sch```

**Comment by rkhaotix** [comment]
Hi @NicoBotha 

Unfortunately, I can't antecipate the binary packages release because I still have some fixes being developed.

About the log file... it seems that the sequences were imported. What is causing the errors in the log file is that you are running the demo version and this one is capable of handle only 9 objects of each kind. So, if your database is bigger than that probably you'll not get the full model.

**Comment by NicoBotha** [comment]
I took the step and paid. 
Now I need to know where to capture the code to change from demo version to paid-up version.

**Comment by rkhaotix** [comment]
Uninstall the demo and get the full version using your key.

**Comment by NicoBotha** [comment]
The question is where to get full version. 
There's jst demo links that work. 



![i2](https://user-images.githubusercontent.com/11308883/32796422-647ec8ac-c977-11e7-957b-d9684da66193.PNG)

**Comment by rkhaotix** [comment]
Click the box "Download" to expand the form where you can inform the key. 
![dl_bin](https://user-images.githubusercontent.com/2205476/32796750-758f01bc-c94e-11e7-93e9-0704b69d31da.png)

**Comment by NicoBotha** [comment]
100% runs  perfectly now. 
Thank you very much
