### ISSUE TITLE
Project Compiles but Won't Run on LMC 18.2

### ISSUE THREAD

**Issue by eengnerd** [pgmodeler/pgmodeler#1015]
I'm using the latest version of LinuxMint Cinnamon (18.2) 64 bit, QT Creator 4.4.1, Qt 5.9.2, git 2.7.4, and followed the directions for using git to clone the project.  I opened the pgmodeler.pro file with QTCreator GUI and compiled just fine, but the program exits with code 127 when it tries to run.  When I open a terminal and try to run the compiled program directly, it seems like it does not know where to find all the .so files for the Qt system.  How can it compile successfully and NOT know this?  Makes no sense.

Sincerely,
Arthur Baldwin

**Comment by rkhaotix** [comment]
First, DO NOT compile pgModeler in QtCreator, unless you know what you're doing and want to code/debug it. Follow all the steps in the tutorial from the console. If you compile the software under QtCreator it'll link against the IDE libraries and if they are not mapped into $PATH or $LD_LIBRARY_PATH  the compiled application will not be able to find them. There're other problems like shadow builds that can cause the compilation to go wrong. This is why I strongly recommend that users compile pgModeler in CLI.
