### ISSUE TITLE
crash dump when importing hstore/ghstore/etc

### ISSUE THREAD

**Issue by cbueche** [pgmodeler/pgmodeler#1017]
The situation: Postgres 9.4 with some extensions, including hstore/ghstore
I cannot import anything related to it, pgmodeler just segfault. I can provide more details if needed. I tried to exclude all extensions, functions, etc, but as soon as a table contains such data, the import crashes.

```
-- Raw attributes: ghstore (OID: 1903129) --
alignment: integer
analyze: 0
by-value: 
category: U
collatable: 
collation: 0
comment: 
configuration: base
default-value: 
delimiter: ,
element: 0
enumerations: 
input: 1903130
internal-length: -1
name: ghstore
object-id: 0
object-type: 17
oid: 1903129
output: 1903131
owner:  <role name="postgres"/>

permission: 
preferred: 
range-attribs: 
receive: 0
schema:         <schema name="public"/>

send: 0
sql-disabled: 
storage: plain
tpmodin: 0
tpmodout: 0
type-class: 
typeattrib: 
```

**Comment by rkhaotix** [comment]
Hi @cbueche 

If possible, please, send the dump of your database (without data) so the import process can be debbuged.

**Comment by cbueche** [comment]
The database is classified so I can't provide more information. I know it will be hard to debug this way. I will talk to a few people.

**Comment by rkhaotix** [comment]
No problem. I understand.
If you can produce a small sample that reproduces the bug/crash it'll help
too.

Em 16 de nov de 2017 11:49 AM, "Charles Bueche" <notifications@github.com>
escreveu:

**Comment by cbueche** [comment]
Hello again. Here the steps to reproduce the problem.

- Run the SQL code below into you local Postgres database
- start pgModeler
- Import
- select your connection
- select the `demohstore` database
- select `Import extension objects`
- click `Import`
- segfault

```sql
psql
CREATE DATABASE demohstore;
postgres=# \connect demohstore

CREATE EXTENSION hstore;

CREATE TABLE demo (
 id serial primary key,
 field1 VARCHAR (255),
 field2 hstore
);

INSERT INTO demo (field1, field2)
VALUES
 (
 'f1val1',
 '"f2k1" => "f2v1",
  "f2k2" => "f2v2",
  "f2k3" => "f2v3"'
 );

INSERT INTO demo (field1, field2)
VALUES
 (
 'f1val11',
 '"f2k11" => "f2v11",
  "f2k22" => "f2v22",
  "f2k33" => "f2v33"'
 );

SELECT * FROM demo;
```
