### ISSUE TITLE
Failed exporting data base

### ISSUE THREAD

**Issue by Pulsar2011** [pgmodeler/pgmodeler#1018]
Recently, while exporting database from PGmodeler to PostgreSQL 9.5 server, I got the following error:

"Could not execute the SQL command.
Message returned: ERROR: CREATE DATABASE cannot be executed from a function or multi-command string"

Before, I do not have such an issue when exporting database.

I am using v0.9.0-beta1 build number 20170418.

**Comment by lewinmadrid** [comment]
I still get this error when exporting to 9.6.
Works fine with 9.4.
I'm using the binary 0.9.1-beta.
