### ISSUE TITLE
PostgreSQL 10 support

### ISSUE THREAD

**Issue by anayrat** [pgmodeler/pgmodeler#1019]
Hello,

It would be great if 0.9.1 include PostgreSQL 10 support 😄 

Regards,

**Comment by jadbox** [comment]
To be clear, pgmodeler does have issues working with PG10... particularly importing/exporting sequences.

**Comment by rkhaotix** [comment]
Hi @anayrat.
pgModeler already has support to PostgreSQL. You can connect to. a db server in version 10 normally, import, export and diff databases. What we have not yet implemented are specific features introduced by PostgreSQL 10. They will be gradually added in future releases of the tool.

@jadbox This issue was quickly solved and is already available in 0.9.1-alpha1. If you are able to compile pgModeler, you can try to code of the branch ```0.9.1-alpha1` ``. The binary packages will be released in November, 30.

**Comment by Titum** [comment]
I have the same issue even with 0.9.1-alpha downloaded today.
Version of PostgreSql is 10.1-2 windows 64 on Windows 7.
I bougth the app yesterday for an urgent project and the first thing I want to do (import) is bugged :(

Complete bug report is joined.
[pgmodeler-import-error.txt](https://github.com/pgmodeler/pgmodeler/files/1517988/pgmodeler-import-error.txt)

**Comment by rkhaotix** [comment]
Hi @Titum. Don't worry, the patched version (0.9.1-alpha1) is ready and will be released later today. ;)

**Comment by ombak** [comment]
Hello...
I have question mybe someone in this forum can help me...

I use fedora 27 and postgresql-10 to install pgmodeler v0.9.0-alpha1. 
My problem is, I cannot connect to my postgresql-10, the pgmodeler show popup like this:

![screenshot from 2018-04-23 18-48-12](https://user-images.githubusercontent.com/2133726/39124844-23cc6426-4727-11e8-8fa1-73d8e5a84099.png)

But when I test connection it's work like this image:

![screenshot from 2018-04-23 18-48-39](https://user-images.githubusercontent.com/2133726/39124873-39bb2650-4727-11e8-9741-cc2e8274417d.png)

Mybe somebody can solve my problem. thank you...

**Comment by rkhaotix** [comment]
The unsupported version message is related to the reverse engineering/code generation feature. It can't read PostgreSQL 10 catalogs and generate compatible code. You have to update your pgModeler installation.
