### ISSUE TITLE
Fedora 27 install fails

### ISSUE THREAD

**Issue by william20111** [pgmodeler/pgmodeler#1020]
Purchased a license and install fails for latest 0.9.1 release

This pops up during install.

> Error during installation process (br.com.pgmodeler):
Execution failed(Unexpected exit code: 134): "/opt/pgmodeler/dbm-mime-type.sh uninstall"

Then errors displayed to stdout on the terminal.

> $ ./pgmodeler-0.9.1-alpha-linux64.run
QSslSocket: cannot resolve CRYPTO_num_locks
QSslSocket: cannot resolve CRYPTO_set_id_callback
QSslSocket: cannot resolve CRYPTO_set_locking_callback
QSslSocket: cannot resolve sk_free
QSslSocket: cannot resolve sk_num
QSslSocket: cannot resolve sk_pop_free
QSslSocket: cannot resolve sk_value
QSslSocket: cannot resolve SSL_library_init
QSslSocket: cannot resolve SSL_load_error_strings
QSslSocket: cannot resolve SSLv23_client_method
QSslSocket: cannot resolve SSLv23_server_method
QSslSocket: cannot resolve X509_STORE_CTX_get_chain
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
QSslSocket: cannot resolve SSLeay
QSslSocket: cannot call unresolved function CRYPTO_num_locks
QSslSocket: cannot call unresolved function CRYPTO_set_id_callback
QSslSocket: cannot call unresolved function CRYPTO_set_locking_callback
QSslSocket: cannot call unresolved function SSL_library_init
Could not register file downloader for https protocol: QSslSocket::supportsSsl() returns false
Warning: No protocol specified
QXcbConnection: Could not connect to display :0
/opt/pgmodeler/dbm-mime-type.sh: line 9: 14915 Aborted                 (core dumped) $PGMODELER_CLI_PATH "--dbm-mime-type" "$@"

**Comment by rkhaotix** [comment]
Hi @william20111 

Did you tried to use the tarball?

**Comment by william20111** [comment]
Yes tried both, its launches but then crashes seconds after.

**Comment by william20111** [comment]
[pgmodeler_20171122_1803.zip](https://github.com/pgmodeler/pgmodeler/files/1497076/pgmodeler_20171122_1803.zip)

zipped and attached the dump it creates

**Comment by rkhaotix** [comment]
Hmm... I suspect that there is some incompatibilities between the SSL installation in your machine and pgModeler. My suspections comes mainly due to the error log generated by the installer. There are some symbols that aren't located and it seems that some libs are outdated or even missing.

**Comment by rkhaotix** [comment]
Found this issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

Seems that wkhtmltopdf suffers the same issue. They suggest not to use the related symbols but I don't have control over it. Qt is trying to use them. Maybe we can try some hacks:

1) Disable the update checking in general setting. If you can't do that due the crash edit the file pgmodeler.conf (~/.config/pgmodeler/pgmodeler.conf) and look for the ```check-update```. Set it to ```false``` and start pgmodeler again.

2) If step 1 does not work, we can try to use the Qt installation of your machine. It may be a bit tricky but it can work. Let's test this one only if the #1 fails.

**Comment by william20111** [comment]
Thats managed to start it! But its still a bit borked looking..

For example i cant change the window size or maximise the window like normal application. The text in the menus are tiny and some of menu items don't work.

There is a fedora pkg'ed version in the repos that works well it just doesn't do postgres 10 as it checks the version of server install. Is there a flag to ignore the server version check? Logged this bug in the hope to get updated to latest version.

https://bugzilla.redhat.com/show_bug.cgi?id=1516460

**Comment by rkhaotix** [comment]
Okay. Could you please attach a screenshot? Are you running it on a 2k or 4k screen?

**Comment by william20111** [comment]
Just a laptop 1080p screen. I cant change the window size half of the application is cut off as you can see. Thanks for this help btw!

![screenshot from 2017-11-22 18-49-27](https://user-images.githubusercontent.com/3274971/33144784-10f648be-cfb6-11e7-849e-e6d53049e2f9.png)

**Comment by rkhaotix** [comment]
Hmmm... I think I know what's going on. There even an issue related:
https://github.com/pgmodeler/pgmodeler/issues/989

In short, try to run pgModeler from console like this:

```QT_AUTO_SCREEN_SCALE_FACTOR=0 QT_SCALE_FACTOR=1 pgmodeler```

**Comment by william20111** [comment]
you my friend a true hero. Its looking good now, thanks!

**Comment by rkhaotix** [comment]
No problem! ;)
