### ISSUE TITLE
Switch between commit/autocommit for SQL Execution

### ISSUE THREAD

**Issue by mmonty01** [pgmodeler/pgmodeler#1021]
I am wondering where I can switch between commit and autocommit. At the moment it seems autocommit is enabled for any SQL execution. However in a production environment this can be risky. I would like to do the commit seperately in such cases. How can I configure this?

**Comment by rkhaotix** [comment]
Currently, there's no such feature. I can add this to the set of features for the next release.

**Comment by mmonty01** [comment]
Yes, I think this would be a very good feature and for us a reason to migrate to this release.
