### ISSUE TITLE
Issue Purchasing

### ISSUE THREAD

**Issue by mattgiles** [pgmodeler/pgmodeler#1022]
Hi there! I just purchased the pre-built binary (twice) on your site, but the redirect from paypal failed both times.

<img width="883" alt="screen shot 2017-12-03 at 12 20 48 pm" src="https://user-images.githubusercontent.com/4960227/33528026-a0c7ae36-d828-11e7-9f80-06af8a3b2643.png">

And attempts to leave feedback also failed:

<img width="615" alt="screen shot 2017-12-03 at 12 33 48 pm" src="https://user-images.githubusercontent.com/4960227/33528041-f221bdbc-d828-11e7-8840-72b8ee80da3f.png">

How can I get the prebuilt binary? I would love avoiding dealing with the build environment myself!

Thanks.

**Comment by rkhaotix** [comment]
Hi @mattgiles 

Sorry for that. I send you an email so we can take care of your issues. I'll close this ticket, right?

Anything you need you can contact me directly via: raphael [at] pgmodeler [dot] com [dot] br
