### ISSUE TITLE
export data model (the type geometry doesn't exist)

### ISSUE THREAD

**Issue by Framattoaerei** [pgmodeler/pgmodeler#1023]
Hi,

I have got an issue with the export of a data model generated with pgModeler.
When I'm doing the export operation an error message always appears that states :" ERROR: the type "geometry does not exist".
How can I solve this problem in roder to export my datamodel from pgModeler to postgreSQL?

Thanks.

**Comment by yjacolin** [comment]
You should probably run this SLQ command: `CREATE EXTENSION postgis;`

In regards of pgModeler, probably needs to activate this extension when the user adds a geometry column.
