### ISSUE TITLE
Can't add GROUP BY in view with no WHERE clause

### ISSUE THREAD

**Issue by dfego** [pgmodeler/pgmodeler#1025]
In the current view editor there's nowhere to put a GROUP BY clause if there is no WHERE clause. Using FROM-WHERE puts it after the last WHERE with a comma. Using After WHERE puts it directly after WHERE, which is a syntax error.

I can work around this by putting in a dummy true After WHERE or entering my own view definition, but it would be desirable not to have to do this.

An example of a view I'd like to create:
```sql
CREATE VIEW device_category_counts AS
SELECT devices.category_id, COUNT(devices.category_id) AS num_devices
FROM devices
GROUP BY devices.category_id;
```

**Comment by rkhaotix** [comment]
Thanks for that. I'll fix it as soon as possible!
