### ISSUE TITLE
Can't reference view column in view

### ISSUE THREAD

**Issue by dfego** [pgmodeler/pgmodeler#1026]
In the current view editor there's support for adding columns to refer to in different parts of the query. However, this field can't be modified directly and the pop-up window only shows proper tables, and not views. My understanding is that views referring to views are valid (and it seems to work on some testing I'm doing), so adding the ability to select view columns here would be helpful!

**Comment by rkhaotix** [comment]
This is an old request and a problem complex to solve due to the internal design of the tool. But still in 0.9.x series I intend to add such feature.
