### ISSUE TITLE
export to SVG doesn't crop to diagram

### ISSUE THREAD

**Issue by garretwilson** [pgmodeler/pgmodeler#1027]
I just created a schema with four tables to include in a document. I exported the model to an SVG file. But the generated image had huge sections of whitespace to the left and to the right of the model. Apparently the export algorithm doesn't crop the image to the bounding rectangle of the outsides of all the graphics.

I finally figured out how to move the entities, but that merely shifted the whitespace to the other side. How do I get an SVG no larger than necessary to include the given diagram (i.e. without added whitespace padding)?

**Comment by rkhaotix** [comment]
It seems a bug to me. The resulting image should be automatically cropped. I'll check that. Thanks

**Comment by garretwilson** [comment]
Do you have any sort of estimate on getting this fixed, or at least a workaround? I have a lot of lessons to write, and every diagram is filling up have the page. As you know from our private discussions, I chose PGModeler to use in these lessons, and one of the main selling points were the SVG diagrams.

**Comment by rkhaotix** [comment]
Unfortunately there's no workaround because I had to fix the algorithm that was calculating the area to be drawn from the canvas. 

I would suggest you to move your objects in the design view as close as possible to the origin point but this "solution" would still create a blank area at the right of the resulting graphics file.

About the estimated date for a official patch, well, I'm planning to release the 0.9.1-beta in January, but I'll try to shorten this time... if the newborn here in my home allow me! :)

**Comment by garretwilson** [comment]
Happy New Year, and I hope all is going well with the child!

I wanted to check to see if there is any news on getting a new version out with this bug fixed.

**Comment by rkhaotix** [comment]
Hi @garretwilson 

I'm a bit late but yes there'll be a new version soon. I know you need this fix for your lessons.. This way, maybe, I can do a custom build for you just to help you and when the new version comes out you can get the rest of the patches. Please, contact me on my personal email so we can discuss this better! :)

**Comment by garretwilson** [comment]
I already did the first round with my lesson, so I can wait until you put out the next official release. I just wanted to check back and make sure this didn't get forgotten. Thanks.

**Comment by rkhaotix** [comment]
Don't worry! The fix is already merged into the next version's codebase! ;)

**Comment by Maxzor** [comment]
Hello, what about now, is the cropping already working?
I exported a model to svg and there is only one small (A4?) page, while I would need a custom one larger than A0.
Could the svg export feature take into account the page size in the print setting?
