### ISSUE TITLE
Multi-line comments

### ISSUE THREAD

**Issue by afonso360** [pgmodeler/pgmodeler#1028]
Hi, it appears that we can only have one line of comments on objects.

I've been using multi line comments by editing the XML file directly, and it works! it even exports the SQL correctly so I believe this to be only a UI change.

**Comment by rkhaotix** [comment]
I don't get it. Could you give an example?

**Comment by afonso360** [comment]
When editing, say a table, pressing enter or shift+enter on the comment box applies the changes instead of creating a new line
