### ISSUE TITLE
how to resize objects, including schema

### ISSUE THREAD

**Issue by JohnColeman** [pgmodeler/pgmodeler#1029]
Re pgmodeler-091-alpha1
great design tool but how to resize objects in the design view, including the enclosing schema rectangle?
If this can be done I don't know how - except via Configuration/Appearance/Global: Font Style, which i sub-optimal.

**Comment by rkhaotix** [comment]
Hi @JohnColeman 

The objects in the design view can't be resized freely. Their sizes are calculated automatically.

About the schema's rectangle it will be resized everytime you move a table over the screen which means that the rectangle dimensions are the same as the sum of all tables (of that schema) bounding rectangles.
