### ISSUE TITLE
cardinality of fk relationships

### ISSUE THREAD

**Issue by JohnColeman** [pgmodeler/pgmodeler#1030]
Re pgmodeler-091-alpha1
fk relationships have cardinlity too.
I would like to show all my fk relationships correctly in crow's foot notation, including a o indicator for optional cardinality as in 0..1 to 0..* .

**Comment by rkhaotix** [comment]
Currently, there is no way to determine the fk relationship cardinality. I'm planning to add that in next releases.

**Comment by orthoxerox** [comment]
In 0.9.4-beta the relationship is inferred only partially: 

```sql
create table a (id bigint primary key);
create table b (id bigint primary key references a (id));
```

The foot on the side of A is correctly inferred to be `||` instead of `OI` (because b.id is a PK and thus non-nullable), but the foot on the B side is `O∈` instead of `OI` (again, because b.id is a PK and can't be duplicated).
