### ISSUE TITLE
how to hide column attribute decorations on table symbols?

### ISSUE THREAD

**Issue by JohnColeman** [pgmodeler/pgmodeler#1031]
Re pgmodeler-091-alpha1
column decorations showing type on the left and constraint/nullability on the right are good but sometimes I want to hide them to reduce the symbol size to fit the whole diagram on a single page - showing only column names and datatypes.
If this can be done, I don't know how.
Keep up the good work :-)

**Comment by rkhaotix** [comment]
This feature is unsupported, but I can consider to add it in future releases.
