### ISSUE TITLE
SCRAM Authentication not supported - PG 10

### ISSUE THREAD

**Issue by jafri** [pgmodeler/pgmodeler#1034]
Connection to a SCRAM enabled database throws "authentication method 10 not supported"

**Comment by rkhaotix** [comment]
Are you compiling it or using binaries from site?

**Comment by nmsz97** [comment]
Compiling it, it seems that the new scram mode introduced in PG10 does not seem to work. Password and MD5 work fine.

**Comment by rkhaotix** [comment]
If you're compiling it can be a missing dependency or the libpq on your machine has no support to scram.

**Comment by crystal-wb** [comment]
I am encountering this message. I am a Rails developer but I wanted to share a visualization of the database schema of an app I work on.

I have Postgresql 13 and I installed pgModeler 0.9.1. When I try to setup a connection to the database I wish to model, I get this message "authentication method 10 not supported". I haven't done anything to the settings in pgModeler and the setup of Postgresql is the default. I installed pgModeler from the website, same for Postgresql.

All I want is to be able to import the tables so I can arrange them in a easily understandable way and save an image of it.

**Comment by Adil-Kumashev** [comment]
I also could not connect to my database on local machine. Every time I try to connect the "message 10 is not supported" error raises.

**Comment by jokay** [comment]
Using the binary **0.9.3** *(AppImage)* and get the same error.

![image](https://user-images.githubusercontent.com/18613935/154421538-9a156061-6d32-4ecc-92c3-0be360653b9b.png)

**Comment by ruckc** [comment]
Really need this today...

**Comment by jokay** [comment]
Confirmed working with pgModeler **1.0.2** and PostgreSQL **15.2** *(default scram-sha-256)*.
