### ISSUE TITLE
Multiple CHECK constraints for a domain is not allowed

### ISSUE THREAD

**Issue by datafoo** [pgmodeler/pgmodeler#1036]
pgModeler does not allow the creation of multiple CHECK constraints for a domain while it is possible in PostgreSQL:

> When a domain has multiple CHECK constraints, they will be tested in alphabetical order by name.
[source](https://www.postgresql.org/docs/current/static/sql-createdomain.html)

Reverse engineering a database containing a domain with multiple CHECK constraints ended up with a model with only one of the CHECK constraints.

**Comment by rkhaotix** [comment]
Thanks! I'll fix that as soon as possible!
