### ISSUE TITLE
How can I create a many to many relationship with self

### ISSUE THREAD

**Issue by anrolmarSoprasteria** [pgmodeler/pgmodeler#1037]
Hi. I've installed the version 0.9.1-alpha1 and I've tried to create a many to many relationship with self in a table. But I can't do it.

Can you help me?

**Comment by rkhaotix** [comment]
Hold Shift while clicking the desired table.

In future releases I will improve the creation of this kind of relationship.

**Comment by anrolmarSoprasteria** [comment]
Thank you.

I've done it
