### ISSUE TITLE
Missing constraint names for tables.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#1039]
It seems like in the current 0.9.0-alpha1 constraint names are not shown anymore in the table GUI "things". Triggers, indexes etc. are still visible and the names are available in the properties, not lost or something. It looks like they are really only not visible.

![table](https://user-images.githubusercontent.com/6223655/34514396-9144fbfa-f06d-11e7-8bfc-3e3bd0c33d93.png)

![table properties](https://user-images.githubusercontent.com/6223655/34514401-949374e4-f06d-11e7-9412-514923dbe761.png)

**Comment by rkhaotix** [comment]
Hi @tschoening 

Go to Settings > Appearence and restore the default settings. This can happen if you're coming from 0.8.2 to 0.9.0 or 0.9.1-alpha1

**Comment by tschoening** [comment]
Thanks, that fixed it for me. I have chosen restoring default settings already on app start and didn't realize that your mentioned settings are not part of that main configuration file.
