### ISSUE TITLE
Default attribute length="1" breaks usages of varchar.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1040]
I've upgraded from 0.8.2 to 0.9.0-alpha1 to get support for Postgres 10 and it seems that during saving of my old imported file a lot of objects get a default attribute of `length="1"`. That's the case for types with a different defined length as well, like `integer`, `boolean` etc. In the GUI of those types wherever they are used the length attribute is specified as 1, but disabled, so not used in the end I guess.

But I get a problem with types like `varchar`, which seemed to have a default length of 0 in older versions, because they didn't have the `length` attribute in the XML file and the exported SQL only contained `varchar` as well. Now the same SQL file contains `varchar(1)` instead. If I manually change the length of 1 back to 0, SQL keeps its `varchar` without length specifier.

So in my opinion, a default value of 1 for `varchar` is a bad decision and should be 0 instead. Whoever needed a restricted `varchar` in the past, would already had defined a length other than 0 manually, so no default value would need to be applied anyway.

**Comment by rkhaotix** [comment]
Thanks for suggesting that. I'll improve the usage of length for varchar.
