### ISSUE TITLE
Individual custom SQL for export and modeling?

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1041]
I'm using pgModeler in combination with DbVisualizer, while the former is for modeling and the latter for support, maintenance, updating things etc. Therefore I always export SQL files from the pgModeler XML files and load them into DbVisualizer to e.g. publish new databases for customers. Simply because I need the connections for those new customers in DbVisualizer most likely anyway.

The problem is that statements like `CREATE FUNCTION` as generated by pgModeler don't work OOB in DbVisualizer, instead one needs to tell DbVisualizer about those complex SQL blocks using `--/` to start and `/` such a block. While the start is a perfectly fine SQL comment, the latter isn't, which is the reason I can't use custom SQL in pgModeler to prepend/append those. During validation of a model using pgModeler Postgres errors on the `/` end of the SQL block for DbVisualizer.

http://confluence.dbvis.com/display/UG100/Executing+Complex+Statements#ExecutingComplexStatements-UsinganSQLBlock

One possible solution would be to configure DbVisualizer to e.g. use `----/` and `--/` as SQL block identifiers, which are both perfectly valid SQL comments now and work as custom SQL in pgModeler as well. The downside of such an approach is that everyone using my SQL files need to reconfigure DbVisualizer as well and in general I would like to keep default settings as much as possible.

Therefore I would like to discuss/suggest if it makes sense to add another layer of custom SQL? One which is applied during modeling for validation, creation of database etc. in pgModeler only and another one which is only taken into account during exporting to a SQL file. Like one can now disable custom SQL, a user could either choose for the already available dialogues if they are applied always/never or only at export time or it might even make sense to provide two custom SQL dialogues, the one already available and another one for exports only. Each could be enabled/disabled individually.

What do you think?

**Comment by rkhaotix** [comment]
I get it, but Instead of adding an "uneeded" complexity to pgModeler objects and XML files, why not simply ignore those lines starting with certain tokens (configured via settings) during validation/export? This way it is possible to achieve that interoperability that you need between the tools involved.

**Comment by tschoening** [comment]
If that is easier and somewhat secure to implement... The problem in my opinion is that `--/` and especially `/` are very common strings, might be difficult to safely recognize only those by regular expressions.

**Comment by rkhaotix** [comment]
You got a point here. In fact, these strings are quite common and can generate lots of false-positive matches. This is why, in my opinion, the use of comments is the safest choice. For example, pgModeler generates SQL code and appends a special token ```-- ddl-end --``` so the export helper can deduce that a whole SQL statement ends in the line prior that token. This doesn't impact in the code semantics and the user can run the code as-is in any db related software.

Well, I need to make some tests to determine the best approach to solve this issue, specifically.

**Comment by tschoening** [comment]
> This is why, in my opinion, the use of comments is the safest choice.

Or a tristate as mentioned, because you already have a boolean to enable/disable custom SQL. Adding a third state "export only" doesn't need to deal with the contents of the custom SQL in any special way and you don't need to change the schema of your XML and such too much.
