### ISSUE TITLE
Don't limit connection port number

### ISSUE THREAD

**Issue by Jean-Roc** [pgmodeler/pgmodeler#1042]
Hi,

I'm trying the 0.9.1 alpha demo but I can't get very far as the connection window is enforcing a port number >= 5421 but the db I would like to try pgmodeler with is only reachable using port 80.

I perfectly know this port is wrong but that's the only one opened in the corporate proxy and there is no way to change it.

Could you please drop this constraint ?

**Comment by rkhaotix** [comment]
Hi! 

Yes, I can. But it will be available only in the next release (0.9.1-beta).

**Comment by Jean-Roc** [comment]
thanks a lot !
