### ISSUE TITLE
Omit schema identifier for SQL export

### ISSUE THREAD

**Issue by FxKu** [pgmodeler/pgmodeler#1044]
Hi
afaik, there is no way to export a model to SQL without the schema identifier, am I right? For our project we offer an option to create the database model additionally inside different Postgres schemas. If there would be no schema addressed with the tables (and sequences etc.), we could simply rerun the exported SQL file from pgModeler (after adjusting the database search path). Right now we have remove the schema identifier from the export file.
Do you think this use case is reasonable enough to add an extra option along with the SQL export? I know, that such an option would be a bit silly if one got more schemas inside a pgModeler file. My there is already an existing workaround I'm not aware of.

Keep up the great work!
Best
Felix

**Comment by WalterFred** [comment]
This is very useful! I also need to run the same DDL SQL's on different schemas!
