### ISSUE TITLE
Can't not build on windows

### ISSUE THREAD

**Issue by wl1711** [pgmodeler/pgmodeler#1050]
I am trying to follow the "Build and install pgModeler" instructions to build it on my windows 64 bit machine.

1: $QTBIN/qmake.exe pgmodeler.pro -- no output?
2: $QTBIN/mingw32-make.exe -- failed with the following msg

**Comment by wl1711** [comment]
$ c:/Qt/Tools/mingw492_32/bin/mingw32-make.exe
cd libutils/ && ( test -e Makefile || C:/Qt/5.6.3/mingw49_32/bin/qmake.exe C:/Users/123456/Downloads/pgmodeler-develop/libutils/libutils.pro -o Makefile ) && C:/Q                                                t/Tools/mingw492_32/bin/mingw32-make -f Makefile
mingw32-make[1]: Entering directory 'C:/Users/123456/Downloads/pgmodeler-develop/libutils'
C:/Qt/Tools/mingw492_32/bin/mingw32-make -f Makefile.Release
mingw32-make[2]: Entering directory 'C:/Users/123456/Downloads/pgmodeler-develop/libutils'
g++ -c -pipe -fno-keep-inline-dllexport -DHAVE_STRUCT_TIMESPEC -O2 -std=gnu++0x -Wall -Wextra -fexceptions -mthreads -frtti -DUNICODE -DBUILDNUM=\"20180124\" -DBI                                                NDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build\" -DPLUGINSDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build/plugins\" -DPRIVATEBINDIR=\"C:/Users/5                                                75963/Downloads/pgmodeler-develop/build\" -DCONFDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build/conf\" -DDOCDIR=\"C:/Users/123456/Downloads/pgmodeler-deve                                                lop/build\" -DLANGDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build/lang\" -DSAMPLESDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build/samples\" -DSCHE                                                MASDIR=\"C:/Users/123456/Downloads/pgmodeler-develop/build/schemas\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_L                                                IB -DQT_CORE_LIB -I. -I"C:/Program Files/PostgreSQL/9.4/include" -I"C:/Program Files/PostgreSQL/9.4/include" -IC:/Qt/5.6.3/mingw49_32/include -IC:/Qt/5.6.3/mingw4                                                9_32/include/QtPrintSupport -IC:/Qt/5.6.3/mingw49_32/include/QtSvg -IC:/Qt/5.6.3/mingw49_32/include/QtWidgets -IC:/Qt/5.6.3/mingw49_32/include/QtGui -IC:/Qt/5.6.3                                                /mingw49_32/include/QtANGLE -IC:/Qt/5.6.3/mingw49_32/include/QtNetwork -IC:/Qt/5.6.3/mingw49_32/include/QtCore -Imoc -IC:/Qt/5.6.3/mingw49_32/mkspecs/win32-g++  -                                                o obj/exception.o src/exception.cpp
/usr/bin/sh: g++: command not found
Makefile.Release:229: recipe for target 'obj/exception.o' failed
mingw32-make[2]: *** [obj/exception.o] Error 127
mingw32-make[2]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libutils'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libutils'
makefile:46: recipe for target 'sub-libutils-make_first-ordered' failed
mingw32-make: *** [sub-libutils-make_first-ordered] Error 2

**Comment by rkhaotix** [comment]
```/usr/bin/sh: g++: command not found```

The compiler g++ can't be located. This isn't needed by default but try to put the path to that command (```C:/Q t/Tools/mingw492_32/bin/```) in PATH environment variable.

**Comment by wl1711** [comment]
That fixed the g++ command not found issue.

Getting the following error:
g++: error: C:/Program: No such file or directory
g++: error: Files/PostgreSQL/9.4/bin/libxml2.dll: No such file or directory
Makefile.Release:70: recipe for target 'parsers.dll' failed
mingw32-make[2]: *** [parsers.dll] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libparsers'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libparsers'
makefile:89: recipe for target 'sub-libparsers-make_first-ordered' failed
mingw32-make: *** [sub-libparsers-make_first-ordered] Error 2
------
after I modified pgmodeler.pri
  !defined(PGSQL_LIB, var): PGSQL_LIB = C:/Program Files/PostgreSQL/9.4/lib/libpq.dll
  !defined(PGSQL_INC, var): PGSQL_INC = C:/Program Files/PostgreSQL/9.4/include
  !defined(XML_INC, var): XML_INC = C:/Program Files/PostgreSQL/9.4/include
  !defined(XML_LIB, var): XML_LIB = C:/"Program Files"/PostgreSQL/9.4/bin/libxml2.dll -- added double quote
----
I am getting this:
mingw32-make[2]: Entering directory 'C:/Users/123456/Downloads/pgmodeler-develop/libparsers'
g++ -Wl,-s -shared -Wl,-subsystem,windows -mthreads -Wl,--out-implib,C:/Users/123456/Downloads/pgmodeler-develop/libparsers/libparsers.a -o parsers.dll obj/schemaparser.o obj/xmlparser.o obj/parsersattributes.o  -LC:/Users/123456/Downloads/pgmodeler-develop/libutils -lutils "C:/Program Files/PostgreSQL/9.4/bin/libxml2.dll" -LC:/Qt/5.6.3/mingw49_32/lib C:/Qt/5.6.3/mingw49_32/lib/libQt5PrintSupport.a C:/Qt/5.6.3/mingw49_32/lib/libQt5Svg.a C:/Qt/5.6.3/mingw49_32/lib/libQt5Widgets.a C:/Qt/5.6.3/mingw49_32/lib/libQt5Gui.a C:/Qt/5.6.3/mingw49_32/lib/libQt5Network.a C:/Qt/5.6.3/mingw49_32/lib/libQt5Core.a
C:/Program Files/PostgreSQL/9.4/bin/libxml2.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Makefile.Release:70: recipe for target 'parsers.dll' failed
mingw32-make[2]: *** [parsers.dll] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libparsers'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/123456/Downloads/pgmodeler-develop/libparsers'
makefile:89: recipe for target 'sub-libparsers-make_first-ordered' failed
mingw32-make: *** [sub-libparsers-make_first-ordered] Error 2

----
I do have this file - C:/Program Files/PostgreSQL/9.4/bin/libxml2.dll

**Comment by rkhaotix** [comment]
Seems that the 'Program Files' (with the space) is failing to be recognized as part of a single path. Try to move PostgreSQL installation to C:/PostgreSQL

**Comment by wl1711** [comment]
I am using postgres 9.4 and 64 it, any issue with that?

**Comment by rkhaotix** [comment]
If you are compiling pgModeler with Qt 32 bits I do not recommend mixing 32 and 64 bit libraries. The code may compile fine but when running the application you'll get unexpected results.

**Comment by wl1711** [comment]
I installed postgres with 32 bit, and I am at step 5
1: $QTBIN/qmake.exe pgmodeler.pro
2: $QTBIN/mingw32-make.exe
3: $QTBIN/mingw32-make.exe install
4: cd build
5: $QTBIN/windeployqt pgmodeler.exe

I am getting the following error:

$ /c/Qt/5.6.3/mingw49_32/bin/windeployqt pgmodeler.exe
C:\Users\xxxxxx\Downloads\pgmodeler-develop\build\pgmodeler.exe 32 bit, release executable
Direct dependencies: Qt5Core Qt5Gui Qt5Widgets
All dependencies   : Qt5Core Qt5Gui Qt5Widgets
To be deployed     : Qt5Core Qt5Gui Qt5Widgets
Unable to find the platform plugin.

**Comment by wl1711** [comment]
Can someone provide some input?
