### ISSUE TITLE
specify a schema when doing diffs on postgresql

### ISSUE THREAD

**Issue by matt-wirtz** [pgmodeler/pgmodeler#1051]
Hi!

This is a feature request for postgresql:

it would be great if one could specify the schema when determining the differences between model and database.

Right now, all schemas of the specified db are incorporated in the diff. So if you are comparing one schema only and activate that missing objects should be dropped then all objects of other schemas are dropped. If you deactivate that missing objects should be dropped then deleted columns e.g. are nor removed from database.

Thx for the great work on this program.

**Comment by cepete** [comment]
Yes, I second this.  We are constantly doing diffs between our dev and production databases which have the same tables, but in different schemas (devsi vs prdsi for example).
Thanks!
