### ISSUE TITLE
Can not create integer array columns

### ISSUE THREAD

**Issue by pematt** [pgmodeler/pgmodeler#1052]
Version: 0.9.0

Problem: Can not create integer array columns.

How to reproduce the problem: Add a column to any table and enter `integer[]` in the 'Type:' field. When pressing apply the column will be added to the table as `integer`. When the table is created in the database the column is created as an `integer` column, not `integer[]`.

**Comment by pematt** [comment]
Hi, could you please let me know if this is a bug or expected behaviour? Thanks!

**Comment by IsaakGroepT** [comment]
Did you find an answer to this question?
