### ISSUE TITLE
Why are duplicate relationship names not allowed when they do not even occur in the exported sql?

### ISSUE THREAD

**Issue by christiaanwesterbeek** [pgmodeler/pgmodeler#1053]
Consider this simple data model.
![image](https://user-images.githubusercontent.com/465989/35503635-fec3c58a-04e0-11e8-9dd9-f8e72d3f9715.png)

Here's the exported sql (some comments removed from it).

```sql
-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.9.1-alpha1
-- PostgreSQL version: 10.0
-- CREATE DATABASE new_database;
-- ;

-- object: public.company | type: TABLE --
-- DROP TABLE IF EXISTS public.company CASCADE;
CREATE TABLE public.company(
	company_id serial NOT NULL,
	name varchar(50),
	CONSTRAINT company_pk PRIMARY KEY (company_id)

);
ALTER TABLE public.company OWNER TO postgres;

-- object: public.contact | type: TABLE --
-- DROP TABLE IF EXISTS public.contact CASCADE;
CREATE TABLE public.contact(
	contact_id serial,
	name varchar(50),
	company_id_company integer
);
ALTER TABLE public.contact OWNER TO postgres;

-- object: company_fk | type: CONSTRAINT --
-- ALTER TABLE public.contact DROP CONSTRAINT IF EXISTS company_fk CASCADE;
ALTER TABLE public.contact ADD CONSTRAINT company_fk FOREIGN KEY (company_id_company)
REFERENCES public.company (company_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;

-- object: public.asset | type: TABLE --
-- DROP TABLE IF EXISTS public.asset CASCADE;
CREATE TABLE public.asset(
	asset_id serial NOT NULL,
	name varchar(50),
	company_id_company integer,
	CONSTRAINT asset_pk PRIMARY KEY (asset_id)

);
ALTER TABLE public.asset OWNER TO postgres;

-- object: company_fk | type: CONSTRAINT --
-- ALTER TABLE public.asset DROP CONSTRAINT IF EXISTS company_fk CASCADE;
ALTER TABLE public.asset ADD CONSTRAINT company_fk FOREIGN KEY (company_id_company)
REFERENCES public.company (company_id) MATCH FULL
ON DELETE SET NULL ON UPDATE CASCADE;
```

As you can see the relationship names `has` and `company_has_many_asset` do not occur in the exported sql.

Why is it that I cannot rename the second relationship name to `has`? When I do the following error occurs: "The object has (Relationship) already exists on new_database (Database)!"

![image](https://user-images.githubusercontent.com/465989/35503797-759b2770-04e1-11e8-9396-d2896cc18ea2.png)

I'm trying to [keep to conventions naming tables and relationships](https://stackoverflow.com/a/4703155/1385429). A few names of those relationships are **comprises**, **occupies** and **classifies**. When the number of tables in the model increases, the chance of duplicate relationship names increases.

How can I stick to these conventions and circumvent duplicity in relationship names?

**Comment by rkhaotix** [comment]
Currently, there's no workaround for the name duplicity. For now, in pgModeler all objects should have unique names in their subgroup (kind) even if they don't have SQL code generate (the case of some relationships).

I'll study the possibility to change this behavior in future releseas since it will demand an important change in the tool's core.
