### ISSUE TITLE
How to create a recursive relationship?

### ISSUE THREAD

**Issue by christiaanwesterbeek** [pgmodeler/pgmodeler#1054]
I'm trying to create a recursive relationship. A table with a relationship to itself. I tried this by right-clicking a table -> New -> Relationship -> 1 to Many. Then when dragging, I cannot select the same table. I tried selecting a different table and in the dialog change the name in receiver table, but that doesn't have any effect.

In short, my question is how to create a recursive relationship.

**Comment by rkhaotix** [comment]
Hi Christiaan.

This is not so intuitive as I wanted to... But hold Shift while clicking the table to create a self relationship.

**Comment by christiaanwesterbeek** [comment]
I already tried that, but nothing happens. So I go, right-click a table -> New -> Relationship -> 1 to Many, move arrow while holding the Shift and click on the same table while still holding the Shift key. I also tried that with Ctrl, Alt en Command. Nothing happens. I have to click on another table or the canvas for anything to happen. I'm on an iMac.

**Comment by christiaanwesterbeek** [comment]
However I just discovered that I can create one manually by going to the table properties -> add a column to become the foreign key, go to tab Constraints and add a foreign key that takes that column and let it refer to the primary of the same table. I'm pretty much ok now. I don't mind that I'm unable to do that by dragging.
