### ISSUE TITLE
Printing function cannot scale?

### ISSUE THREAD

**Issue by snhirsch** [pgmodeler/pgmodeler#1057]
Why is it not possible to have the printing operation be a bit smarter?  It tries to spread a relatively small schema (5 tables) across four sheets of paper.  I can find no way to either select a limited region or ask it to scale to a single page.  This is a real show stopper and greatly limits the usefulness of the tool.

**Comment by rkhaotix** [comment]
First.. pgModeler uses a built-in printing system provided by Qt... so if it is not so smart at a certain level we need to have it changed in the framework.

About spreading the model across four sheets... see the highlighted dashed lines in the image below? They are the page delimiters or margins or limits... and they serve to help you to position your objects on the paper and not exceed its dimensions... By default, pgModeler works with A4 in Landscape but these settings can be changed in Settings > General > Printing & Code

![page delimiters](https://user-images.githubusercontent.com/2205476/35704291-c3ef1e1a-077d-11e8-8054-e61e0490160f.png)

**Comment by snhirsch** [comment]
Blast, I didn't realize Qt printing was so restrictive.  Do I have control over the size that objects are rendered?  The table graphics are large to start with and I cannot fit very many into one of the page areas.

As a workaround, I can export as SVG and re-render that to PDF.  It will then fit on one page, but even in that case it picks up way too much of the surrounding blank area.  Is there any way you can add a feature to mark a rectangular region for SVG or PNG export so I can restrict to only the actual objects?

**Comment by snhirsch** [comment]
I was looking at this wrong way.  Answer seems to be to "lie" about the paper size and choose an option that fits the entire drawing on one page.  Then, print to PDF and use, e.g. Acroread to scale back to letter size for printing drafts.

Thanks for nudging me in the right direction!

**Comment by rkhaotix** [comment]
No problem! :)
Just answering your previous message... The Qt printing interface depends on the OS. I found the Linux the most restricted one, and I agree with you. It should be improved.

The only task pgModeler does before send the objects to the printer is to determine the amount of pages to be printed and where the objects will be placed on the sheet. Basic calculations only. The rest is for Qt.

About the tables' size, you can reduce a bit their size by hiding the extended attributes of the tables. By extended attributes we call the constraints, triggers, indexes and rules that are displayed at the bottom of each table. You can toggle that section by click the gray triangle at the very bottom of any table (if they have one of the mentioned objects attached). See  **_Toggling extended attributes_** at this blog post https://www.pgmodeler.com.br/blog/2017/4/4/pgmodeler-090-beta-is-out
