### ISSUE TITLE
Create trigger with sql expression as a body instead of a trigger function

### ISSUE THREAD

**Issue by christiaanwesterbeek** [pgmodeler/pgmodeler#1058]
I'd like to create a trigger on a table with a definition like this.

```sql
create trigger user_encrypt_pass_trigger
before insert or update on "user"
for each row
execute procedure auth.encrypt_pass();
```

So on my user table I did this:
![image](https://user-images.githubusercontent.com/465989/35703379-1b0d9212-079c-11e8-96e5-b5d776636c7e.png)
Though the function is required, and I can't save the changes, or I get this error
> Assignment of a not allocated function to object user_encrypt_pass_trigger (Trigger)!
![image](https://user-images.githubusercontent.com/465989/35703459-5f187224-079c-11e8-85c9-a6356433b5d5.png)

I found issue https://github.com/pgmodeler/pgmodeler/issues/961 with a hint towards Custom SQL. I tried it:
![image](https://user-images.githubusercontent.com/465989/35703469-6d463318-079c-11e8-9039-e4d9a57cdd72.png)

But I still couldn't save the new trigger (same error).

How can I create a trigger with a sql expression instead of needing to refer to a function? It seems overkill to do that when that function is only executing a stored procedure.

**Comment by rkhaotix** [comment]
It's not possible, and it's not overkill... pgModeler needs to know the link/dependency between the objects in order to correctly generate the SQL/XML code.

You can create the whole trigger manually. Just use the "Generic SQL" object an put there the trigger definition.

**Comment by christiaanwesterbeek** [comment]
Thanks for the tip.
