### ISSUE TITLE
The Primary Key can not be seen in diagram 0.9.1-beta

### ISSUE THREAD

**Issue by juusechec** [pgmodeler/pgmodeler#1066]
I'm opening a .dbm in pgmodeler 0.9.1-beta, but the name of primary key constraints can't be seen.
![image](https://user-images.githubusercontent.com/4140058/36112731-97001ba6-0ff8-11e8-9c94-a45971f11602.png)

**Comment by juusechec** [comment]
![image](https://user-images.githubusercontent.com/4140058/36112995-5ba6ea16-0ff9-11e8-96f7-badde667c7fa.png)

**Comment by juusechec** [comment]
![image](https://user-images.githubusercontent.com/4140058/36113018-67b3c644-0ff9-11e8-9cfe-fa2f87ab0b77.png)

**Comment by rkhaotix** [comment]
Go to Settings > Appearance and restore the default settings of that section. Restart the application and the problem should be resolved.

**Comment by juusechec** [comment]
thanks, this solve the problem!
