### ISSUE TITLE
0.9.1-beta fails to build on Fedora 28 / gcc 8 / qt 5.10

### ISSUE THREAD

**Issue by rosset** [pgmodeler/pgmodeler#1068]
gcc version 8.0.1 20180131 (Red Hat 8.0.1-0.9) (GCC) 
Name        : qt5-qtbase Version     : 5.10.0

g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILDNUM=\"20180213\" -DBINDIR=\"/usr/bin\" -DPLUGINSDIR=\"/usr/lib64/pgmodeler/plugins\" -DPRIVATEBINDIR=\"/usr/libexec\" -DCONFDIR=\"/usr/share/pgmodeler/conf\" -DDOCDIR=\"/usr/share/doc/pgmodeler\" -DLANGDIR=\"/usr/share/pgmodeler/lang\" -DSAMPLESDIR=\"/usr/share/pgmodeler/samples\" -DSCHEMASDIR=\"/usr/share/pgmodeler/schemas\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../libobjrenderer/src -I../libpgconnector/src -I../libpgmodeler/src -I../libparsers/src -I../libutils/src -isystem /usr/include/libxml2 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Imoc -isystem /usr/include/libdrm -Isrc -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/collationwidget.o src/collationwidget.cpp
make[1]: Leaving directory '/home/filiperosset/rpmbuild/my/failed/pgmodeler/pgmodeler-0.9.1-beta/libpgmodeler_ui'
In file included from src/sqlexecutionwidget.h:28,
                 from src/generalconfigwidget.cpp:27:
src/ui_sqlexecutionwidget.h: In member function 'void Ui_SQLExecutionWidget::setupUi(QWidget*)':
src/ui_sqlexecutionwidget.h:186:56: error: no matching function for call to 'QToolButton::setShortcut(QLatin1String)'
         snippets_tb->setShortcut(QLatin1String("Alt+X"));
                                                        ^
In file included from /usr/include/qt5/QtWidgets/qcheckbox.h:44,
                 from /usr/include/qt5/QtWidgets/QCheckBox:1,
                 from src/ui_generalconfigwidget.h:16,
                 from src/generalconfigwidget.h:28,
                 from src/generalconfigwidget.cpp:19:
/usr/include/qt5/QtWidgets/qabstractbutton.h:87:10: note: candidate: 'void QAbstractButton::setShortcut(const QKeySequence&)'
     void setShortcut(const QKeySequence &key);
          ^~~~~~~~~~~
/usr/include/qt5/QtWidgets/qabstractbutton.h:87:10: note:   no known conversion for argument 1 from 'QLatin1String' to 'const QKeySequence&'
In file included from src/sqlexecutionwidget.h:28,
                 from src/generalconfigwidget.cpp:27:
src/ui_sqlexecutionwidget.h:204:54: error: no matching function for call to 'QToolButton::setShortcut(QLatin1String)'
         export_tb->setShortcut(QLatin1String("Alt+X"));
                                                      ^
In file included from /usr/include/qt5/QtWidgets/qcheckbox.h:44,
                 from /usr/include/qt5/QtWidgets/QCheckBox:1,
                 from src/ui_generalconfigwidget.h:16,
                 from src/generalconfigwidget.h:28,
                 from src/generalconfigwidget.cpp:19:
/usr/include/qt5/QtWidgets/qabstractbutton.h:87:10: note: candidate: 'void QAbstractButton::setShortcut(const QKeySequence&)'
     void setShortcut(const QKeySequence &key);
          ^~~~~~~~~~~
/usr/include/qt5/QtWidgets/qabstractbutton.h:87:10: note:   no known conversion for argument 1 from 'QLatin1String' to 'const QKeySequence&'
{standard input}: Assembler messages:
{standard input}: Error: .size expression for generalconfigwidget.cpp does not evaluate to a constant
make[1]: *** [Makefile:11984: obj/generalconfigwidget.o] Error 1
make[1]: Entering directory '/home/filiperosset/rpmbuild/my/failed/pgmodeler/pgmodeler-0.9.1-beta/libpgmodeler_ui'
g++ -c -pipe -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILDNUM=\"20180213\" -DBINDIR=\"/usr/bin\" -DPLUGINSDIR=\"/usr/lib64/pgmodeler/plugins\" -DPRIVATEBINDIR=\"/usr/libexec\" -DCONFDIR=\"/usr/share/pgmodeler/conf\" -DDOCDIR=\"/usr/share/doc/pgmodeler\" -DLANGDIR=\"/usr/share/pgmodeler/lang\" -DSAMPLESDIR=\"/usr/share/pgmodeler/samples\" -DSCHEMASDIR=\"/usr/share/pgmodeler/schemas\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../libobjrenderer/src -I../libpgconnector/src -I../libpgmodeler/src -I../libparsers/src -I../libutils/src -isystem /usr/include/libxml2 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -Imoc -isystem /usr/include/libdrm -Isrc -I/usr/lib64/qt5/mkspecs/linux-g++ -o obj/generalconfigwidget.o src/generalconfigwidget.cpp
make[1]: *** Waiting for unfinished jobs....

**Comment by rosset** [comment]
0.9.0-alpha1 also fails, full logs here https://kojipkgs.fedoraproject.org//work/tasks/1490/24861490/build.log

**Comment by joaof** [comment]
Workaround here:  https://bugreports.qt.io/browse/QTBUG-65251
