### ISSUE TITLE
Unable to change object creation order

### ISSUE THREAD

**Issue by snhirsch** [pgmodeler/pgmodeler#1072]
I added a function to my data model, then added a check constraint to an existing table that references the function.  Validation fails because the function is created after the table in the DDL.  I opened the swap ids dialog, told it to create the function before the table, then pushed OK.  It does nothing.  The DDL source still tries to define the function after it is referenced.  The "Apply Fix" button is grayed out, so no luck there.  I can manually edit the DDL source, but this seems like it shouldn't be necessary.

Am I missing something?

**Comment by rkhaotix** [comment]
In theory you're doing it right. It seems that we have a bug here. Could you check what are the ids of the table, the constraint and function?

**Comment by snhirsch** [comment]
The table is 5213.  The function is 5770.  The constraint is being declared in the table creation statement and does not have an id.  Even after I check "Use Alter for columns and constraints" the constraint still ends up in the table DDL.  I can _swap_ the function and table using those options, but of course this creates dozens of other problems.  At this point, I'm hand-editing the SQL as a workaround.

**Comment by rkhaotix** [comment]
You can revalidate your model every time you swap ids. This will fix any remaining problem related to the creation order.

**Comment by snhirsch** [comment]
Ok, that does work.  Thanks!  But, the function to "do exactly what I say" and shuffle the source item in front of the target seems simple enough conceptually. Why does it simply take no action?
