### ISSUE TITLE
garbled/overlapping text in table (constraints section)

### ISSUE THREAD

**Issue by yogesch** [pgmodeler/pgmodeler#1075]
When a table has a few different constraints, rules and indices, the second half of the table that shows this information sometimes has overlapping lines. 

It is a bit hard to describe in words, so here are some screenshots - notice that in the bottom section of the tables, after the third lines, the next ones are almost entirely overlapping with each other, leading to serious readability problems. I've seen it happen in more than one case. (Not sure it matters, but I'm using pgmodeler on the Mac.) 

![screen shot 2018-03-01 at 08 46 36](https://user-images.githubusercontent.com/18548961/36825424-5ff19832-1d2d-11e8-8517-e1221db31f2b.png)
![screen shot 2018-03-01 at 08 47 47](https://user-images.githubusercontent.com/18548961/36825425-603f25fc-1d2d-11e8-9017-467cdaa1eea9.png)
![screen shot 2018-03-01 at 08 48 12](https://user-images.githubusercontent.com/18548961/36825426-60b5e75a-1d2d-11e8-8752-09d7d6966783.png)

**Comment by rkhaotix** [comment]
See here: https://github.com/pgmodeler/pgmodeler/issues/1066

**Comment by yogesch** [comment]
Muito obrigado senhor..
