### ISSUE TITLE
Partitioned tables - doesn't import main table (Postgres 10)

### ISSUE THREAD

**Issue by gmoeller** [pgmodeler/pgmodeler#1079]
We have implemented partitioning on two of our main working tables.  pgModeler does not recognize the main table, so we can not work with it in the application. It will import the individual partitions, but no relationships exist between the partitions and the other tables in the database.

**Comment by rkhaotix** [comment]
Table partitioning is not supported yet. I'm planning to start to work on it during the development of 0.9.1 stable or 0.9.2-alpha1 (not decided yet)
