### ISSUE TITLE
Validation fails on imported table with user defined function

### ISSUE THREAD

**Issue by yogesch** [pgmodeler/pgmodeler#1080]
In postgres, I first create a table and then I create a user defined function (which takes the table itself as the input argument type). Everything works nicely in postgres, but after importing the model to pgmodeler, it fails to validate with the error:

>  Could not execute the SQL command.
>  Message returned: `ERROR:  type "person" already exists

It seems that pgmodeler is trying to create a custom type "person" in this case (in the model objects sidebar, there is an entry "person" under type). So obviously it will fail because the type/table "person" already exists. It is possible to fix the validation problem by simply deleting the entry under type. But then exporting fails because it is not possible to drop type "person" when the table "person" exists. Oddly enough, if one creates the same function definition within pgmodeler, there is no such problem, but after exporting and reimporting the model the problem is back. 

So this creates a usability issue where it is not possible to do export/import operations on models which have user defined functions. So any way to work around this would be most appreciated. I remain available for any followup queries. 

To reproduce:
In postgres, create the following table and function. Then import the model into pgmodeler and validate. 
 
```
CREATE TABLE person 
  ( 
    id int PRIMARY KEY, 
    first_name text, 
    last_name text NOT NULL 
  ); 

INSERT INTO person 
  VALUES 
    (1, 'John', 'Smith'), 
    (2, 'Jane', 'Doe'), 
    (3, NULL, 'Prince'); 

CREATE FUNCTION display_name(rec person) 
  RETURNS text 
  STABLE 
  LANGUAGE SQL 
  COST 5 
AS $$ 
  SELECT 
    CASE 
      WHEN $1.first_name IS NULL THEN '' 
      ELSE $1.first_name || ' ' 
    END || $1.last_name; 
$$; 

SELECT p.id, p.display_name FROM person p;

```

**Comment by rkhaotix** [comment]
I have a suspect on what is causing this... I'll investigate and provide the needed patch.
For now, the only workaround is to drop the type wrongly generated in the model.

**Comment by yogesch** [comment]
Thank you, after dropping the type I can now validate the model. 

But after dropping the type in the model, if I try to do a diff with the server db, the diff has a command that looks like "drop type ...". So when I try to apply that diff, the server throws an error saying that the type cannot be dropped when the table still exists. 

So the workaround I use now is to simply delete the function from pgmodeler, and recreate (easy enough to copy paste) it.

**Comment by yogesch** [comment]
Impressive that you already fixed it...

Cheers!

**Comment by rkhaotix** [comment]
I really work hard to make pgModeler a better tool. It is of my interest to exterminate all the bugs discovered so my users can rely on the tool! ;)
