### ISSUE TITLE
Search - request

### ISSUE THREAD

**Issue by MatthsTrier** [pgmodeler/pgmodeler#1085]
A simple possibility to search for String/Text in the Name-fields would be very usefull, esspecially in bigger models. (with a "Set focus" on found objects).

**Comment by rkhaotix** [comment]
Such feature alread exists. Click the "Find objects" button at the very bottom (left corner) of the "Design" view.

**Comment by MatthsTrier** [comment]
Thank you very much!
"Sometimes I don't see the tree in the forest".

Sunny regards
Matths
