### ISSUE TITLE
Unamble to write file <file_addres> due to one or more erros in the definition generation process!

### ISSUE THREAD

**Issue by kylefelipe** [pgmodeler/pgmodeler#1087]
Hi, im having issue when i try to save the .dbm file...
Version: 0.9.1
S.O>: Ubuntu 17.10

[7] src/schemaparser.cpp (1148)
  QString SchemaParser::getCodeDefinition(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `cast-type' with an undefined value in file `/usr/local/share/pgmodeler/schemas/xml/cast.sch', line 4, column 32!

[6] src/schemaparser.cpp (1436)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `cast-type' with an undefined value in file `/usr/local/share/pgmodeler/schemas/xml/cast.sch', line 4, column 32!

[5] src/schemaparser.cpp (910)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&, unsigned int)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `cast-type' with an undefined value in file `/usr/local/share/pgmodeler/schemas/xml/cast.sch', line 4, column 32!

[4] src/baseobject.cpp (844)
  virtual QString BaseObject::getCodeDefinition(unsigned int, bool)
    [ERR_ASG_OBJ_INV_DEFINITION] The object `cast(public.geometry,point)' (Cast) has inconsistent SQL or XML definition!

[3] src/databasemodel.cpp (6613)
  virtual QString DatabaseModel::getCodeDefinition(unsigned int, bool)
    [ERR_ASG_OBJ_INV_DEFINITION] The object `cast(public.geometry,point)' (Cast) has inconsistent SQL or XML definition!

[2] src/databasemodel.cpp (7108)
  void DatabaseModel::saveModel(const QString&, unsigned int)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/x12239181/Dropbox/cadastro_plantio_Inicio/modelagem/cadastro_plantio.dbm' due to one or more errors in the definition generation process!

[1] src/modelwidget.cpp (1584)
  void ModelWidget::saveModel(const QString&)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/x12239181/Dropbox/cadastro_plantio_Inicio/modelagem/cadastro_plantio.dbm' due to one or more errors in the definition generation process!

[0] src/mainwindow.cpp (1359)
  void MainWindow::saveModel(ModelWidget*)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/x12239181/Dropbox/cadastro_plantio_Inicio/modelagem/cadastro_plantio.dbm' due to one or more errors in the definition generation process!

**Comment by rkhaotix** [comment]
Hi! Could you please share the model file?

**Comment by kylefelipe** [comment]
[files.zip](https://github.com/pgmodeler/pgmodeler/files/1842921/files.zip)

**Comment by rkhaotix** [comment]
Send them again... seems the zip file is corrupted. Empty files.

**Comment by kylefelipe** [comment]
Funny! for me works, here is a dropbox link to the file
https://www.dropbox.com/s/7848jtawgw5gor9/files.zip?dl=0

**Comment by kylefelipe** [comment]
Here is a file that was working well... 
[modelo_cad_plantio.zip](https://github.com/pgmodeler/pgmodeler/files/1843216/modelo_cad_plantio.zip)

Now, with the 0.9, even if i start a new model... when i try to save it shows that i can do it....

There is some log that i can paste here to help this fix???

**Comment by kylefelipe** [comment]
Hi, now im using debian, and i just imported a database to PgModeler and it prompts the same error...
