### ISSUE TITLE
DEFAULT on columns does not reflect changes on DIFF

### ISSUE THREAD

**Issue by dtiziani** [pgmodeler/pgmodeler#1088]
When I change some default columns and make a diff on a database on AWS, it changes on database, but it always appears as a PENDING CHANGE in DIFF operation.

Here's the script pgmodeler generates:

ALTER TABLE company.company ALTER COLUMN equity_type SET DEFAULT NULL;
-- ddl-end --
ALTER TABLE customer.customer_contract ALTER COLUMN dt_entry SET DEFAULT NOW();

Column type:
company.equity_type -> character(5) DEFAULT NULL
customer_contract.dt_entry timestamp DEFAULT now()

pgmodeler version 0.9.1-alpha

**Comment by dbtech** [comment]
I have the same issue when using a Sequence as Default Value for a Table Column in the model and comparing it against a database. BTW, this is my generic approach for generating primary keys, so it occurs once for each table. Example:
Database:
= = = = =
CREATE TABLE public.event (
    event_id bigint NOT NULL DEFAULT nextval('event_seq'::regclass),
    CONSTRAINT event_pkey PRIMARY KEY (event_id)
)
= = = = =
Diff does not recognize the database column default and keeps reporting a difference:
= = = = =
ALTER TABLE public.event ALTER COLUMN event_id SET DEFAULT nextval('public.event_seq'::regclass);
= = = = =

**Comment by FGRibreau** [comment]
Did you tried last beta1? 
I dont have the issue anymore, you can close this @rkhaotix :)
