### ISSUE TITLE
Multiple foreign keys to the same table

### ISSUE THREAD

**Issue by abiuan** [pgmodeler/pgmodeler#1090]
I'm unable to create multiple foreign keys in a table to the same table. For example:
`create table a (id integer primary key);`
`create table b (id integer primary key
, code1 integer constraint code1_fk references a(id)
, code2 integer constraint code2_fk references a(id)
);
`
is perfectly legal in postgresql.
Is there any particular reason why pgmodeler prohibits to create more than one foreign key to the same table?

> There is already a relationship between tableB (Table) and tableA (Table) in the model!

Regards

**Comment by drseu55** [comment]
I'm also unable to create multiple foreign keys to the same table. v0.9.4 on Fedora 37

**Comment by rkhaotix** [comment]
> I'm also unable to create multiple foreign keys to the same table. v0.9.4 on Fedora 37

In that case, don't use the relationship tool... Just create the foreign key constraints by hand on the desired table.
