### ISSUE TITLE
Can not save model to disk 

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#1094]
I have database model with size about 1.6MB and when I try save it on disk, pgmodeler is cyclic
![2018-04-07 10 35 32](https://user-images.githubusercontent.com/3863428/38452572-83317f30-3a4f-11e8-8581-be3632bde6f9.png)

In addition, generation xml for large models takes a very long time (about 5min for my case), so pgmodeler can not be used for large serious projects, it is necessary to divide them into several separate parts, which is very uncomfortable

**Comment by fte1965** [comment]
Check mail

**Comment by rkhaotix** [comment]
It seems the problem is that the saving process is entering in a loop and never exists it. The issue happens only in macOs. I'll investigate it better and provide the needed fixes.

**Comment by fte1965** [comment]
if this helps, on small models the CPU usage is 99% after saving
![2018-04-18 12 48 15](https://user-images.githubusercontent.com/3863428/38925099-4a09154a-4307-11e8-8234-25d2628f0aeb.png)
