### ISSUE TITLE
Hide several Tables

### ISSUE THREAD

**Issue by MatthsTrier** [pgmodeler/pgmodeler#1095]
For better overview it would be nice, to hide a (bigger) group of tables "by one click".
Found the possibility to change colours of tables by the Tag-Option, 
but no possibility to select them all at once - to hide them and their relations at once.

**Comment by rkhaotix** [comment]
You can do that in two ways:

1) Select the desired objects, right click them and use "Fade in/out > Fade out"
2) Open the object finder (bottom left of the design view) and search the desired objects. Click the button "Fade out" to fade out all objects listed in the search result.

**Comment by MatthsTrier** [comment]
Thanks for your quick answer.
Ok, yes, I know these Options.
But I am looking for a possibility to fade in/out a big number of tables at a time, and a way, to do this several times, without reselecting them manually each time.
Filtering would be a good possibility, but for this, a common "element" in all these tables is necessary. 
And without changing the names of the tables (for example adding a prefix like "FadeIO_") I don't see a possibility: unfortunately a filter on "comment"- or "tag"-fields of the tables is not possible. 
And due to compatibility a name-changing is not possible also....
Hoping for a more comfortable solution....
