### ISSUE TITLE
I cannot save my tables in a different schema

### ISSUE THREAD

**Issue by Framattoaerei** [pgmodeler/pgmodeler#1096]
Hallo,

I have the following problem. I create a E-R schema in pgModeler and i set a new dedicated schema, different from public,  where I would like that all the tables create will be saved once the export process finished.

When the export process is finisched everything is copied in in the public schema. Where do I make the mistake?

Thanks in advance

Francesco

**Comment by rkhaotix** [comment]
Hi!

I didn't get it. Do you want to move the tables to a new schema? Could you, please, elaborate it?

Thanks

**Comment by Framattoaerei** [comment]
Yes exactly! But unfortunately they are always copyed within the '*public*'
schema.

Could you help me?



2018-04-10 15:37 GMT+02:00 Raphael Araújo e Silva <notifications@github.com>
:
