### ISSUE TITLE
Type dep relationship with tables containing sequence column

### ISSUE THREAD

**Issue by cletellier61** [pgmodeler/pgmodeler#1098]
Hi Raphaël,

In the model, the dep relationship propagates also the default sequence object column of the source table to the target table (and not only the NULL or NOT NULL attribute). I tried, without success, the include/excluding options of the Relation properties DialogBox.

The target table is generated correctly in PG database as expected for the LIKE(<table>) statement without options. An immediate diff (model/database comparison) suggests to alter the column with default sequence object.

Did i miss something ?

Thank you,

Cyrille Letellier

After a diff,

**Comment by cletellier61** [comment]
Hi Raphaël,

I just wanted to clarify what happens, my original title is badly choosen:

I have a source table core.session wich contains columns with default values sequence for serial  and now() for timestamps (default values in the 4th column):
![source-table-properties](https://user-images.githubusercontent.com/38252677/38856687-67377f16-4227-11e8-9639-ea59ddf9cc66.png)

In the log scheme, i create my log_session table (2 columns) and i add a dep relationship (with Excluding All):
![dep_relationship_with_excludingall](https://user-images.githubusercontent.com/38252677/38856828-d85f79a0-4227-11e8-9b71-42b1bce5362d.png)

Finally my target table has the following properties (4th column). The default values of the target table are also propagated in the target table:
![target-table-properties](https://user-images.githubusercontent.com/38252677/38856874-f965e882-4227-11e8-8179-902f5ab3f834.png)

It is not a problem when i export the model to the database (part of the generated script for the target table):
CREATE TABLE param.log_session(
	LIKE core.session EXCLUDING ALL,
	log_date timestamp(0) NOT NULL,
	log_op text NOT NULL
);
no default values are generated in postgresql (v10.1).

But when i make a diff between the database and the model, all the "unexpected" default values of the target table in the model raise differences.

Would it be possible to have the target table in the model to reflect the including/excluding options that are setup for the dep relationship ?

Thank you,

Cyrille Letellier
pgmodeler 0.9.1 Beta 1
postgresql V10.1

**Comment by rkhaotix** [comment]
Hi Cyrille!

I understand the problem. Could you please send me a small model that causes the issue?
It's important to note that for copy relationships (LIKE) PostgreSQL will completely detach the source table from the destination, which means that they have no relationship anymore once they are exported. Also, the diff can't determine that the destination table was generated from a copy relationship this can explain in parts the false-positive diffs.. But I'll investigate it better. Just send me a sample model and I'll work on the fix if needed.

**Comment by cletellier61** [comment]
Hi Raphaël,

I have in the enclosed zip file:

*the small relationshipdep.dbm with the source core.session table, the target log.session table and the relationship type dep with "excluding all" option. 
*the pg_dump sql file once the export is made from pgmodeler to postgresql
*the psql \d core.session and \d log.session showing the 2 tables structures and default values
*the diff sql script generated by pgmodeler

[relationshipdep.zip](https://github.com/pgmodeler/pgmodeler/files/1920570/relationshipdep.zip)

Thank you,

Cyrille
