### ISSUE TITLE
Cannot see row listing in Index properties

### ISSUE THREAD

**Issue by heisian** [pgmodeler/pgmodeler#1101]
<img width="706" alt="screen shot 2018-04-13 at 5 30 07 pm" src="https://user-images.githubusercontent.com/4141828/38762407-7c687776-3f40-11e8-903f-4305010da2e3.png">

Unable to scroll or resize window to be able to see the Indexed columns...

**Comment by heisian** [comment]
I'm running Sierra 10.12.6, this release was built off of the 0.9.1-beta1 branch:
<img width="1138" alt="screen shot 2018-04-13 at 6 42 24 pm" src="https://user-images.githubusercontent.com/4141828/38763163-809525e2-3f4a-11e8-8841-27cf4e9d8c3f.png">

**Comment by heisian** [comment]
i'll try pulling the latest commit, I last pulled the branch about a week ago

**Comment by heisian** [comment]
With the latest commit, there are now scrollbars, but one is still unable to see anything:
<img width="706" alt="screen shot 2018-04-13 at 11 48 14 pm" src="https://user-images.githubusercontent.com/4141828/38765389-34b6e1ee-3f75-11e8-9811-43dcbafbb9c9.png">

How hard would it be to make these modals resizable? If you can give any pointers, I'd love to help. This program is wonderful and has helped me come up with some great schema designs:

![screen shot 2018-04-13 at 11 50 13 pm](https://user-images.githubusercontent.com/4141828/38765406-8340ad90-3f75-11e8-95f6-5c9a7bc95317.png)

**Comment by rkhaotix** [comment]
Actually, it's a bit complicated to solve this kind of problem,  related to resolution and dialogs. The fact is that the dialogs are resized according to the resolution of the user's screen. A similar issue was present on Windows 10 but I've solved it, I applied the same approach for macOS but seems is not working as expected. I'm running the latest High Sierra on a Mac mini attached to a 2K monitor and the dialogs are ok. I'm gonna review the patch then.

What's is the resolution of your screen?

**Comment by heisian** [comment]
It is a Retina display on a MacBookPro, so the resolution is 2880x1800.
On my desktop, I use a 4K monitor, so there it is 3840x2160

**Comment by heisian** [comment]
I set my display scale to "look like" 1024x640, and now the scrollbar shows up, and I can scroll all the way down to see. So it seems that the dialog model calculates the screen height wrong b/c of HiDPI/Retina, and doesn't show the scrollbar in higher resolutions.

<img width="706" alt="screen shot 2018-04-14 at 12 10 30 pm" src="https://user-images.githubusercontent.com/4141828/38771725-050d9b28-3fdd-11e8-89bd-61b063ccf511.png">
