### ISSUE TITLE
Cancel undoes last action on function when nothing changed

### ISSUE THREAD

**Issue by rcurr** [pgmodeler/pgmodeler#1106]
Using pgmodeler compiled at 9c615c0 (tag: v0.9.1-beta1) on Ubuntu 16.04.

The "Cancel" button on "Function properties" seems to undo the last action even if I have not changed anything. My steps are:

If I create a simple function, then click "Apply". Add a comment through "Function properties", click "Apply". Open "Function properties" again, it looks like:

![test-fn](https://user-images.githubusercontent.com/14201936/38926981-43323c52-42fc-11e8-9ea1-50f26fba2556.png)

Clicking "Cancel" and opening "Function properties" again - the comment is now removed, even though I haven't added the comment in the last "Function properties" session. I would expect that if I hadn't changed anything, "Cancel" would not do anything.

Happy to clarify or add more info.

**Comment by rkhaotix** [comment]
This is a regression and I discovered it days ago. Already fixed it. You can try the fix using the "cli-improvements" branch

Anyways, thanks for reporting.

**Comment by rcurr** [comment]
Thanks for the quick reply. I've compiled pgmodeler at fa195f4 on the cli-improvements branch and it looks to be fixed.

**Comment by pupitetris** [comment]
Hi. We have just discovered this issue. A reference to the change that fixed the regression would be nice. Thanks.

**Comment by pupitetris** [comment]
OK, thanks a lot.
