### ISSUE TITLE
failed check for updates

### ISSUE THREAD

**Issue by prtome** [pgmodeler/pgmodeler#1107]
Hello
when I run Check for updates I get 
The update notifier failed to check for new versions! Please, verify your internet connectivity and try again! Connection error returned: 0 - SSL handshake failed.

I have currently V0.9.1-beta Build 20180122, paid version

thanks

**Comment by jkirkpatrick** [comment]
See #1069

**Comment by christiaanwesterbeek** [comment]
You may close this issue since it's a duplicate of: https://github.com/pgmodeler/pgmodeler/issues/949
