### ISSUE TITLE
hide relations

### ISSUE THREAD

**Issue by prtome** [pgmodeler/pgmodeler#1108]
I would like to hide some relations in the model. I have tried giving custom color "white". the relations disappear, but the losanges that are on the relations lines are still there, as well as the littles squares next to the table (these are less annoying). It is mostly to be able to print some cleaner model, for relations that are less "present in all tables and as such not need to print"

Is that possible ? thanks

**Comment by rkhaotix** [comment]
Right click the desired relatinship (or any graphical object) and use Fade > Fade in

Or right click the blank area on the canvas and use the same menu but now choosing the kind of object to be faded. The fade factor can be adjusted in the settings.

**Comment by prtome** [comment]
Thanks a lot, I missed that. perfect
