### ISSUE TITLE
why doesn't it support postgres-10?

### ISSUE THREAD

**Issue by pzzrudlf** [pgmodeler/pgmodeler#1113]
![screenshot from 2018-04-25 18-37-53](https://user-images.githubusercontent.com/3185502/39241112-639eab80-48b8-11e8-9a8d-f65dd4ff66dd.png)

**Comment by heisian** [comment]
Works on 10.1 and 10.3 for me.. looks like it's reporting the version incorrectly (1.0) there?

**Comment by rkhaotix** [comment]
Update your release to at least 0.9.0-beta2
