### ISSUE TITLE
How to update model with changes in database?

### ISSUE THREAD

**Issue by mjmeyer** [pgmodeler/pgmodeler#1115]
Diff seems to work well in applying changes from model to db but I'm also in need of a way to update the model from any changes in db.

Diff doesnt seem to support this. I can select a db as the source for diff but dont see any way to select the model as the "compare to" target.

Import works fine to ingest the entire db schema into a NEW model but doesnt seem to have any way to import into an existing model.

Is there any way to update an existing model with diff from database?

**Comment by rkhaotix** [comment]
Unfortunately, this isn't supported by the tool yet.
There are some workarounds but they aren't the optimal solution.

You can reverse engineering the updated database to a new model and then use the metadata handling dialog to copy the objects metadata (position, textboxes, relationships colors and points, etc) to the new model generated from the reverse engineering.

**Comment by rkhaotix** [comment]
@zoranembroker see here:
https://pgmodeler.io/support/docs/612-objects-metadata-handling

**Comment by bradleygore** [comment]
@rkhaotix - was this "metadata handling" functionality removed in v0.9.3-beta1? I'm unable to find this dialog and would very much like to bring in new tables/etc... from my server w/o losing formatting of placement, colors, etc...

**Comment by bradleygore** [comment]
> @rkhaotix - was this "metadata handling" functionality removed in v0.9.3-beta1? I'm unable to find this dialog and would very much like to bring in new tables/etc... from my server w/o losing formatting of placement, colors, etc...

In case others come here w/ same question: Found the answer - It's in "Fix" menu -> "Objects Metadata".

**Comment by rkhaotix** [comment]
Hi @bradleygore 

Sorry the delay. I see that you found it.
The action that triggers the feature was moved to the new place in 0.9.3-alpha

https://pgmodeler.io/blog/2020/3/26/the-first-alpha-release-of-093-is-ready
