### ISSUE TITLE
Curious, why the dependency on XML2 when Qt has XML built in?

### ISSUE THREAD

**Issue by ShamanTcler** [pgmodeler/pgmodeler#1125]
As a Qt developer I have become quite fond of Qt's XML implementation ... after leaving Xerces.

Is XML2 is for a technical reason? Or is it a legacy issue. Removing a dependency is always good.

Regards
Carl

**Comment by rkhaotix** [comment]
Just because when I started this project (in 2006) XML2 was more complete than Qt's XML implementation. I know these days Qt's XML is good enough too. But I have no plans to move to it (at least in a near future). :)
