### ISSUE TITLE
The mac demo dmg fails to even open

### ISSUE THREAD

**Issue by chriszrc** [pgmodeler/pgmodeler#1127]
**Bug description**
The mac demo dmg fails to even open

**How to reproduce**
Download and try to open dmg on macos 10.12.5

**Expected behavior**
The installer should open

**Screenshots**

**Info about your desktop**
 - OS: Mac
 - Version: 10.12.5
 - Window manager:
 - pgModeler version: 0.9.1
 - Qt version:

**Stacktrace / Debug info**

**Additional info**

**Comment by rkhaotix** [comment]
Hi @chriszrc 

I've tested the binary and everything is okay! I was able to install and run the demo.
Could your provide more details? Screenshots?

**Comment by chriszrc** [comment]
Hi, 
Thanks for responding, ok, I took another look, and I discovered that actually the disk image was getting mounting, but unlike most dmgs that I've downloaded, opening/doubling clicking the dmg didn't open a new window, so I never noticed that it was actually getting mounted. Weird. Anyways, I can close this, thanks for responding!
