### ISSUE TITLE
Problem with buyed dmg file for macOS

### ISSUE THREAD

**Issue by ray-delossantos** [pgmodeler/pgmodeler#1128]
**Bug description**
pgmodeler-0.9.1-macos.dmg doesn't open in 3 macs tested.

**How to reproduce**
Download from the website in the payed part for the binary pgmodeler-0.9.1-macos.dmg.

**Expected behavior**
When you try to unpack the dmg it finish without any additional prompt. This takes less than a a second.

**Info about your desktop**
 - OS: macOS Sierra
 - Version: 10.12.6 (16G1314)
 - Window manager: default
 - pgModeler version: 0.9.1
 - Qt version: N/A

**Additional info**

**Comment by matthewblott** [comment]
I have the same issue - my details are the same as those above.

**Comment by raydf** [comment]
I solved it, after running the dmg, look for a pgmodeler shortcut in the desktop of the mac. Anyways the installer should be more user friendly if it's possible.

**Comment by matthewblott** [comment]
Okay there's definitely an issue with the dmg file.  I got it to work with the following.

1. From the terminal.

```
hdiutil attach -noverify -nomount pgmodeler-0.9.1-macos.dmg

open /Volumes/pgmodeler
```

2. Drag pgModeler.app to the Applications folder

**Comment by rkhaotix** [comment]
I'm gonna to check that but there was not changes in the DMG construction from 0.9.0 to 0.9.1... If any error is being raised please attach some screenshots.

**Comment by matthewblott** [comment]
There's no error. It just doesn't work when you double-click the dmg file - nothing happens.

**Comment by keshavkuruva** [comment]
Looks like the issue exists with pgmodeler-0.9.2-alpha-macos.dmg too. I tried mounting the dmg directly by double clicking it but it failed to open. I am on High Sierra 10.13.3 BTW. 

Tried hdiutil as mentioned by @matthewblott and was able to move the app to Applications folder.
