### ISSUE TITLE
Could not generate source code due to one or more errors! 

### ISSUE THREAD

**Issue by abrahambruck** [pgmodeler/pgmodeler#1129]
I see that this was resolved (fixed) for hirsch, but where to I get the "fix" or version where it is "fixed"

**I am on Version v0.9.1-Beta Build: 20180122**

I have an "Instance" of Postgres in which I have 7 "Databases";
I changed the Master password for the owner of the Instance.

After that, I am not able to use the "Source Code";
/* Could not generate source code due to one or more errors! 
 [2] src/databaseimporthelper.cpp (2106)
  void DatabaseImportHelper::createPermission(attribs_map&)
    [ERR_CUSTOM] The object `permission_dba=arwdDxt/roottest' (Permission) is referencing the object `dba' (Role) which was not found in the model!
[1] src/databaseimporthelper.cpp (503)
  void DatabaseImportHelper::createPermissions()
    [ERR_CUSTOM] The object `permission_dba=arwdDxt/roottest' (Permission) is referencing the object `dba' (Role) which was not found in the model!
[0] src/databaseimporthelper.cpp (645)
  void DatabaseImportHelper::importDatabase()
    [ERR_CUSTOM] The object `permission_dba=arwdDxt/roottest' (Permission) is referencing the object `dba' (Role) which was not found in the model!
 */
This is only happening in the "roottest" database that is highlighted above. The others are working as expected.

abraham.bruck@gmail.com

**Comment by rkhaotix** [comment]
You can get the patched version (**0.9.1**) from:

https://github.com/pgmodeler/pgmodeler/releases (source code)
https://pgmodeler.io/download (compiled version)

**Comment by abrahambruck** [comment]
​What is my Access Key?​


All the Best!

Abraham Bruck
(845) 300-7970
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
We are a Soul having an Inner Body Experience ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
