### ISSUE TITLE
New Sort order button

### ISSUE THREAD

**Issue by abrahambruck** [pgmodeler/pgmodeler#1130]
**Bug description**
The new sort order button orders the columns in the tables as expected, but also sorts the table names in "random" order, not alphabetically. The tables, etc should be in alpha order

**How to reproduce**
click on the new sort button

**Expected behavior**
The tables, etc should be in alpha order

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager:
 - pgModeler version: 9.1 latest
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
The sort button affects all the object's tree. If you let it unchecked all the objects are sorted by the OID (object identification number) if checking the button the all the objects in the tree are sorted alphabetically.
