### ISSUE TITLE
Modal windows too compact, window proportions not saved.

### ISSUE THREAD

**Issue by ovidiucs** [pgmodeler/pgmodeler#1133]
Using pgmodeler v0.9.1 build 20180526 / qt 5.10.1 on arch linux / xfce / 1920 x 1200 24" screen

There seems to be an issue with some windows (adding a table, adding a view, edit a table, etc) 
When adding a table for instance you see at most 2 columns in the window and in order to see all of them (or more content) for each individual table you have to resize vertically the window (or maximize it) as the windows width and height is not remembered across elements ( tables in this instance but can also be others like views for instance)

![screenshot_20180528_202336](https://user-images.githubusercontent.com/2406691/40624585-20302302-62b6-11e8-9381-40f4d0185d88.png)
 
Additionally when editing table data text that should appear is now hidden

![screenshot_20180528_202402](https://user-images.githubusercontent.com/2406691/40624654-7de97714-62b6-11e8-946d-fde740c91fe7.png)

Similarly with views as I said earlier.
![screenshot_20180528_202522](https://user-images.githubusercontent.com/2406691/40624705-d877b9c0-62b6-11e8-83e2-cf1fda48b618.png)

This would probably be not such a big deal if window proportions would be kept when you'd resize them.

**Comment by MrCheeze96** [comment]
I have this problem too. It seems to be the info/warning texts that appear in the windows, that doesn't make the window resize correctly?

**Comment by MrCheeze96** [comment]
It just happened when I were adding a foreign key constraint manually through constraints on a table. So it seems to be connected to every time a resize of a window should happen.
