### ISSUE TITLE
Modify names of foreign keys

### ISSUE THREAD

**Issue by Daniel-Brosnan-Blazquez** [pgmodeler/pgmodeler#1134]
**Modify names of foreign keys**
When creating foreign keys, pgmodeler automatically creates a name using the foreing key name and the table name. This is resulting in large names without any reason (collision could be resolved this way, but when there is no collision is a bad thing having names too large).

In my project I have, for example, these two tables:
 dim_signature_id | dim_signature | dim_exec_name 
------------------+---------------+---------------
                1 | TEST          | TEST
 gauge_id | system | name | description | dim_signature_id_dim_signature_tb 
----------+--------+------+-------------+-----------------------------------
        1 |        | TEST |             |                                 1

where you can see the foreign key name 'dim_signature_id_dim_signature_tb'.

Could you please tell me if this feature is already available or if it could be added?

Thanks a lot in advance.

**Comment by MrCheeze96** [comment]
You can change what the name of the FK should be set to in the global settings (accessed by pressing F12 of by using the drop down menu > Edit > Settings and then go to Relationships > FK Settings & Patterns [Tab] > Name patterns), or by changing it for each FK by double clicking the relation and in the bottom of the window (Naming patterns) the name can be set.

**Comment by Daniel-Brosnan-Blazquez** [comment]
Sorry, I was looking for that and didn't realize it was just there.

Thanks a lot.
Cheers.

**Comment by Daniel-Brosnan-Blazquez** [comment]
Solved.
