### ISSUE TITLE
Não consigo fazer engenharia reversa

### ISSUE THREAD

**Issue by defo-git** [pgmodeler/pgmodeler#1135]
The object sanepredial.atd_preco (Tabela), oid 22495148, could not be imported due to one or more errors! Check the exception stack for more details. HINT: if the object somehow references objects in pg_catalog or information_schema consider enable the importing of system objects.

**Comment by rkhaotix** [comment]
É preciso mais detalhes. Só com essa informação não consigo te ajudar. Poderia anexar o dump do seu banco de dados aqui ou enviar por email?
