### ISSUE TITLE
Generate diff from model crashes trying a SELECT SQL 

### ISSUE THREAD

**Issue by Daniel-Brosnan-Blazquez** [pgmodeler/pgmodeler#1142]
[gsdm.zip](https://github.com/pgmodeler/pgmodeler/files/2075687/gsdm.zip)

**Bug description**
When trying to generate a diff from model, the GUI reports the following issue:
[5] src/connection.cpp (400)
  void Connection::executeDMLCommand(const QString &, ResultSet &)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'

I have tried all the different possible options but nothing works.

**How to reproduce**
Create the database:
$ createdb gsdmdb
FIll the database with the code generated by pgmodeller:
$ psql gsdmdb -f gsdm_data_model.sql

Then run the Generate diff from model function from pgmodeler using the model gsdm_data_model.dbm 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
Generate no errors and no differences.

**Info about your desktop**
 - OS:
Ubuntu
 - Version:
14.04 LTS
 - Window manager:
G-nome
 - pgModeler version:
0.9.0
 - Qt version:
3.0.4
**Stacktrace / Debug info**
[5] src/connection.cpp (400)
  void Connection::executeDMLCommand(const QString &, ResultSet &)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'
       ** 42703

[4] src/catalog.cpp (227)
  void Catalog::executeCatalogQuery(const QString &, ObjectType, ResultSet &, bool, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'
       ** catalog: sequence

[3] src/catalog.cpp (443)
  vector<attribs_map> Catalog::getMultipleAttributes(ObjectType, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'

[2] src/catalog.cpp (545)
  vector<attribs_map> Catalog::getObjectsAttributes(ObjectType, const QString &, const QString &, const vector<unsigned int> &, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'
       ** Object type: sequence

[1] src/databaseimporthelper.cpp (642)
  void DatabaseImportHelper::importDatabase()
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'
       ** Object type: sequence

[0] src/modeldatabasediffform.cpp (595)
  void ModelDatabaseDiffForm::captureThreadError(Exception)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  no existe la columna «start_value»
LINE 1: SELECT start_value, min_value, max_value, increment_by, cach...
               ^
HINT:  Probablemente quiera hacer referencia a la columna «explicit_ref_cnf_tb_expl_ref_cnf_id_seq.last_value».
QUERY:  SELECT start_value, min_value, max_value, increment_by, cache_value,  CASE WHEN is_cycled IS FALSE THEN NULL  ELSE is_cycled END FROM "gsdm"."explicit_ref_cnf_tb_expl_ref_cnf_id_seq" LIMIT 1;
CONTEXT:  función PL/pgSQL pg_temp_6.get_seq_attribs(text,text) en la línea 1 en EXECUTE
'

**Additional info**

**Comment by rkhaotix** [comment]
Hi @Daniel-Brosnan-Blazquez 

This issue seems to be related to the sequence importing which was fixed in 0.9.1-alpha1. Did you tried this release or the stable 0.9.1?

**Comment by Daniel-Brosnan-Blazquez** [comment]
Hi @rkhaotix 

I will give it a try to see if this is solved. I will report here the output of the analysis.
I also see 0.9.1 supports PostGIS extensions! That's great!
Very good job with this tool. Very powerful.

Thanks a lot for your quick answer.
