### ISSUE TITLE
Erro ao iniciar o pgModeler

### ISSUE THREAD

**Issue by pescador98** [pgmodeler/pgmodeler#1145]
Toda vez que abro aparece um erro que diz assim:
Um ou mais plugins não foram ativados devido a erros durante o processo de carregamento!  
Verifique a pilha de exceções para mais detalhes.

**Detalhes**: 
[2] src/pluginsconfigwidget.cpp (140)
  virtual void PluginsConfigWidget::loadConfiguration()
    [ERR_PLUGIN_NOT_LOADED] Could not load the plugin `dummy' from the library `C:/Program Files (x86)/pgmodeler/plugins/dummy/dummy.dll'! Message returned by plugin manager: `The shared library was not found.'

[1] src/pluginsconfigwidget.cpp (140)
  virtual void PluginsConfigWidget::loadConfiguration()
    [ERR_PLUGIN_NOT_LOADED] Could not load the plugin `xml2object' from the library `C:/Program Files (x86)/pgmodeler/plugins/xml2object/xml2object.dll'! Message returned by plugin manager: `The shared library was not found.'

[0] src/pluginsconfigwidget.cpp (147)
  virtual void PluginsConfigWidget::loadConfiguration()
    [ERR_PLUGINS_NOT_LOADED] Um ou mais plugins não foram ativados devido a erros no processo de carregamento! Verifique a pilha de exceções para mais detalhes.

Eu estou usando a versão 0.9.1 do pgModeler para windows 10.

**Comment by equinton** [comment]
I have the same problem with the same version.

**Comment by paulito-bandito** [comment]
9I have the same problem with compiling version v.0.9.2 compiling on a MacOS (Catalina 0.15.3 )

The files are all where they need to be (I manually copied them), but the instructions don't cover how to add these files to the application path. 

Perhaps something is missing from the README.md?
