### ISSUE TITLE
Object creation order (sequences before tables)

### ISSUE THREAD

**Issue by lktg** [pgmodeler/pgmodeler#1146]
I've created a set of tables with IDENTITY columns. however, the target db version is 9.6 and therefore IDENTITY columns are not supported. So I've created a set of sequences (about 15 of them) to replace IDENTITY with SEQUENCE column. when validation is running it complain about the fact that the sequence not exists and in fact, in the script i see it but at the bottom!

Two questions/ideas:
1. Is it possible to move all the sequences to the top of the script?
2. ER - I think the tool should be smart enough to put all required objects dependencies ahead of the objects need them.

Thoughts?

**Comment by rkhaotix** [comment]
Did you try to apply fixes? The "smartness" of the tool lies in the semi-automatic fixes it provides to solve this kind of issue.

**Comment by lktg** [comment]
Thanks! looks like problem solved
