### ISSUE TITLE
syntax error at or near "-" with uuid-ossp extension

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1147]
**Bug description**
When adding the uuid-ossp extension, pgModeler neglects to escape the extension name, breaking the command.

**How to reproduce**
Add the uuid-ossp extension and validate your model.

**Expected behavior**
Model passes validation.

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager:
 - pgModeler version: 0.9.1
 - Qt version:

**Comment by stlbucket** [comment]
+1 - same behavior on mac

**Comment by rkhaotix** [comment]
This is fixed on 0.9.2-alpha
