### ISSUE TITLE
Style of the bounding schema

### ISSUE THREAD

**Issue by nghtstr** [pgmodeler/pgmodeler#1158]
**Feature description**
This should be relatively simple to describe. My team and I love your tool. However when exporting the image, the transparency of the schema backgrounds takes too much from the colors we are using. As such, it looks like we are fans of pastels. (LOL)

I think there should be a way to adjust the following of the schema boxes:
The overall background transparency (as to allow for darker colors)
The font/size/color of the individual schema name
The border color and width of the schema box.

I understand that this is a minor issue, but these would be very welcome additions to our tool set.

**Comment by Maxzor** [comment]
As for now you, can already choose a custom color (with the "continuous-color-picker panel") as close as white as possible.
