### ISSUE TITLE
src/view.cpp:359: bad erase ?

### ISSUE THREAD

**Issue by dcb314** [pgmodeler/pgmodeler#1161]
src/view.cpp:359] -> [src/view.cpp:357]: (error) Iterator 'itr' used after element has been erased.

Source code is

     if(references[*itr]==references[ref_id])
                                vect_idref[i]->erase(itr);
      itr++;

Maybe better code

     if(references[*itr]==references[ref_id])
                                itr = vect_idref[i]->erase(itr);
      else 
                               itr++;

**Comment by rkhaotix** [comment]
Yes, there's a bad erase here but I'll check if this method is still used over the application if not the better option is to remove it (less code to keep).

Thanks anyway.
