### ISSUE TITLE
Remove protected objects and disable protected mode

### ISSUE THREAD

**Issue by Cycloone** [pgmodeler/pgmodeler#1162]
Hello, how can i delete protected objects and how to disable auto protected mode?
When i try to remove constraint i catch this error:

[1] src/tablewidget.cpp (607)
  void TableWidget::removeObject(int)
    [ERR_REM_PROTECTED_OBJECT] The object `fact_aggregate_uq1' (Constraint) can not be deleted because it is protected!

**Comment by heri16** [comment]
I need to add comments to items in the advanced tab of relationships. Can this be done?

**Comment by rkhaotix** [comment]
@heri16 No, for now this isn't supported.

As a workaround, if you need to edit attributes that are locked by the relationships you can manually make the link between the tables by creating the columns and foreign keys. This way you're free to edit any of their attributes.

**Comment by marcotcal** [comment]
Hello, 

can I change the owner of a table generated by a many to many relation ? as the table object is protected I could not do it.
I know I can change directly on the database but I want to generate completely using pg_modeler.
for some objects I use custom sql feature but I don't lknow if it is the case

**Comment by rkhaotix** [comment]
@marcotcal See here:

https://www.pgmodeler.io/support/docs/718-managing-relationship-generated-objects?v=1.2.0
