### ISSUE TITLE
Ability to set foreign key relationships as 1:1?

### ISSUE THREAD

**Issue by ghost** [pgmodeler/pgmodeler#1163]
I have relations in my database that use foreign keys but that do not have a 1:n relationship. Those tables use a separate UNIQUE constraint to enforce each foreign key appearing at most once; I'd like to be able to illustrate that a foreign key isn't a 1:n relationship in the database schema map. Would it be possible to allow this?

Thanks so much for such a great application!

**Comment by Maxzor** [comment]
Hello, isn't it what the ?:**1** ?:**1** at both ends of the relationship object illustrates?
