### ISSUE TITLE
Dep relation (copy/like) and SQL order generation sequence of the LIKE order problem

### ISSUE THREAD

**Issue by cletellier61** [pgmodeler/pgmodeler#1164]
Hi Raphael,
I have log tables in a log schema that have dep relation (copy/like) with other tables i want to track in.

In the modeler i get : 
*displayed first, my 2 extra-columns (log_date, log_op)
*then the copied fields (green color) of the dep relation from my tracked original table.

But SQL generation gives:
CREATE TABLE log.agent(
	LIKE core.agent,
	log_date timestamp(0) NOT NULL DEFAULT now(),
	log_op text NOT NULL
);
instead of :
CREATE TABLE log.agent(
	log_date timestamp(0) NOT NULL DEFAULT now(),
	log_op text NOT NULL,
	LIKE core.agent,
); as the modeler displays the fields.

The like generation sequence is important for me (a trigger that expects the 2nd order). Is there a way to achieve this ?

Thank you,

Cyrille

2 screens copies: the original tracked table and the log table. Using the 9.1 pgmodeler release (x64 linux).
![original_tracked_table](https://user-images.githubusercontent.com/38252677/44781748-7fec6900-ab85-11e8-9345-671b6ac5bdf4.png)

![log_table_from_dep_relationship](https://user-images.githubusercontent.com/38252677/44781747-7fec6900-ab85-11e8-9b24-073cf0f3ff3a.png)

**Comment by rkhaotix** [comment]
Hi!

Did you try to validate the model? This kind of issue is easily solved by the validation/fix process.

**Comment by rkhaotix** [comment]
I understand it partially... Could you provide the model you're working on?
