### ISSUE TITLE
cannot install on mac

### ISSUE THREAD

**Issue by stlbucket** [pgmodeler/pgmodeler#1166]
i paid for and downloaded pg modeler

i am unable to install

![image](https://user-images.githubusercontent.com/2467892/44866837-1d55a480-ac3b-11e8-9789-09b03cc84957.png)

**Comment by stlbucket** [comment]
![image](https://user-images.githubusercontent.com/2467892/44867181-f8adfc80-ac3b-11e8-82b0-3990aeb5c6d1.png)

**Comment by rkhaotix** [comment]
Hi!
Maybe a corrupted file? Do you tried to download it again?

**Comment by stlbucket** [comment]
same problem

i tried downloading the 9.1 version, when i run it, it creates a new drive?   it doesn't install to my applications.

then

![image](https://user-images.githubusercontent.com/2467892/44871998-4715c800-ac49-11e8-99ff-951bd7b66a0b.png)

i have to go into settings to allow this to execute.

i had this same issue trying to demo the software.  then i paid for it, hoping it was just a problem with the demo.

i have permissions to all directories - i am the only user and have all admin privs on this machine.

**Comment by stlbucket** [comment]
![image](https://user-images.githubusercontent.com/2467892/44872128-90661780-ac49-11e8-8192-cbaabaf85981.png)


this is the app i attempted to execute

**Comment by stlbucket** [comment]
![image](https://user-images.githubusercontent.com/2467892/44872150-9c51d980-ac49-11e8-94b8-38dc0199d4e1.png)

the 'external drive' that is created

**Comment by rkhaotix** [comment]
Click the green arrow on the error message and post a screenshot here please. Maybe there's something wrong with the conf files.

**Comment by stlbucket** [comment]
![image](https://user-images.githubusercontent.com/2467892/44873376-ea1c1100-ac4c-11e8-8da8-e8bd47d0e028.png)

**Comment by rkhaotix** [comment]
Do you moved the pgmodeler.app to /Applications ? I'm not able to test the mac package right now but later today I'll do that.

**Comment by stlbucket** [comment]
ok - that does the trick - manually copying to applications

**Comment by stlbucket** [comment]
to be clear - i still cannot install alpha.  i've tried downloading it again to no avail.

**Comment by inieves** [comment]
I am on Mac OSX 10.15.2

I have a paid license and I am unable to install pgmodeler (from the binary installer) versions:
0.9.1
0.9.2-beta2
0.9.2_snapshot20191127

Are there any log files I can check?
What could be causing this?
