### ISSUE TITLE
Clob data type import Error

### ISSUE THREAD

**Issue by chaospuppy** [pgmodeler/pgmodeler#1167]
**Bug description**
Importing tables with fields of the "Clob" data type (PostgreSQL/EDB) causes import error 

**How to reproduce**
Import PostgresSQL table to pgModeler that includes a field of type "Clob"

**Expected behavior**
Error appears in produced error log and table fails to be imported

 - OS: Ubuntu
 - Version: 18.04 (also occurred for Ubuntu 16.04)
 - pgModeler version: v0.9.1-beta1
 - Qt version: 5.9.5

**Stacktrace / Debug info**

src/databaseimporthelper.cpp (743)
  void DatabaseImportHelper::createObject(attribs_map&)
    [ERR_OBJECT_NOT_IMPORTED] The object `schmeaname.tablename' (Table), oid `*****', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.

Note: 
Removal or change of Clob data type to something else allows import.

**Comment by rkhaotix** [comment]
Need more details about the error. The fill stack trace can help. Also, if you can add a sample database so I can test/debug the import on my side.
