### ISSUE TITLE
Hide schemas and tables for generate an image file

### ISSUE THREAD

**Issue by equinton** [pgmodeler/pgmodeler#1170]
It will be very interesting to generate a PNG only for one schema, but it's no possible, even with fade all tables of the others schemas.

Thanks,

**Comment by rkhaotix** [comment]
Here's an example... All tables hidden and an image generated via export process.

You've to change the opacity factor to zero which causes all objects with opacity = 0 to be completely hidden.

![demodb](https://user-images.githubusercontent.com/2205476/44985933-82b9d600-af58-11e8-8dee-0c70aca30624.png)

Check this link to see where do you find the opacity settings:
https://pgmodeler.io/support/docs/41-general-settings?preview=true

**Comment by equinton** [comment]
Ok, thanks. Sorry for this stupid question, I'm just beginning to use your software after a lot of years with Sql Power Architect.

best regards,
Eric Quinton.
