### ISSUE TITLE
100% CPU in use

### ISSUE THREAD

**Issue by equinton** [pgmodeler/pgmodeler#1171]
**Bug description**
Sometimes, but frequently, pgmodeler use 100 % of one CPU (version 0.9.1 on Ubuntu 18.04 LTS). I must stop and restart pgmodeler.

I do not know exactly which process triggers this behavior, perhaps the generation of the xml file after a change ?

**How to reproduce**

**Expected behavior**

**Screenshots**

**Info about your desktop**
 - OS: Ubuntu 18.04
 - Version: 4.15.0-33-generic
 - Window manager: /usr/lib/xorg/Xorg vt1 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3

 - pgModeler version: 0.9.1
 - Qt version: Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by fte1965** [comment]
I have same problem after each saving model to disk...
OS: macOS High Sierra 10.13.6
Qt: 5.9.3

**Comment by rkhaotix** [comment]
@fte1965 I remember you've reported this issue #1094 and I've fixed it. The problem still persists even in 0.9.1 or 0.9.2-alpha?

@equinton Could you detail a bit more? What are the action you were taking after the software started to use the entire CPU?

**Comment by equinton** [comment]
The problem is triggered when I change the position of an object: after pgmodeler generate automatically the xml file, the cpu usage increase to 100%

**Comment by rkhaotix** [comment]
@equinton Hm... it seems to be the thread responsible to save the temporary model (for recover purposes). It'll consume 100% of the cpu depending o the size of your model but right after finish the saving the cpu should back to normal.

**Comment by equinton** [comment]
It never release the CPU. The dbmodel has a size of 88 Ko, only 40 tables: it's a small database.

I have a ssd disk, and it's crypted.

**Comment by fte1965** [comment]
More, run the pgmodeler, then click on the "new model", create the table and save it, then we get a 100% CPU load..., close pgmodeler, run pgmodeler, reopen dbmodel saved in step 1,  click "Validate", after validation we get a 100% CPU load

**Comment by equinton** [comment]
It seems to be resolved with version 0.9.2alpha1.

thanks.
