### ISSUE TITLE
Cannot Reduce The Height of the Dialog Box

### ISSUE THREAD

**Issue by mikail-khan** [pgmodeler/pgmodeler#1175]
Hi

I run PGModeller on my Arch Linux system. However, I am not sure if this due to my recent system upgrade but now I am not able to reduce the size of the dialog box to create a table or any other dialog box. Because of this I cannot see the buttons at the bottom of the dialog box (see screenshot). Scrolling up and down does not reveal them.

 - OS: Manjaro Arch Linux 
 - Version: 17.1.12
 - Window manager: XFCE4
 - pgModeler version:2.0.9.2_alpha
 - Qt version:5.11.1-2

**Comment by co-category** [comment]
I'm going to have to open this again. The dialog boxes take up all the screen real estate and beyond and so you can not access the buttons or see them. It is not possible to reduce them in size. I would like to post a screenshot but not sure how to do that here.
