### ISSUE TITLE
Create view error

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#1176]
**Bug description**
 void View::addReference(Reference &, unsigned int, int)
    [ERR_MIX_VIEW_DEF_EXPR_REFS] It is not possible mix ordinary references (SELECT-FROM, FROM-WHERE, After WHERE) with references used as view SQL definition!

**How to reproduce**
create new view in model with reference properties: ref.type = Expression & Used in = View Definition  

**Info about your desktop**
 - OS: Mac OS X
 - Version: Sierra 10.13
 - Window manager:
 - pgModeler version: 0.9.2-alpha1
 - Qt version: 5.9.3

**Comment by rkhaotix** [comment]
Fixed it! Thanks!
