### ISSUE TITLE
Support for ENUM type in 0.9.1 

### ISSUE THREAD

**Issue by ghost** [pgmodeler/pgmodeler#1181]
Is there an issue with ENUM types for the version in subject?
I can't find it in selectable Data types?

Thanks.

**Comment by rkhaotix** [comment]
Do you mean this?
https://pgmodeler.io/support/docs/328-user-defined-types

**Comment by j1e8WTb1A1nReiUc** [comment]
Yes. Thanks for clearing that up.

**Comment by GitStorageOne** [comment]
I added enum and referenced to it from some table.
Validation says, that enum is being referenced by 1 object(s) before its creation.
Can PGmodeler automatically recreate id's with proper creation order?

**Comment by rkhaotix** [comment]
@GitStorageOne see this: https://pgmodeler.io/support/docs/67-model-validation

**Comment by rkhaotix** [comment]
The ids swapping feature is the last resort when the automatic fixes don't work.

**Comment by thesteve0** [comment]
None of the links on this page work anymore but this page is the #1 google result for enums in pgmodeler. Any chance you could update the links

**Comment by thesteve0** [comment]
Here is the page that talks about userdefined types which covers enums.
https://pgmodeler.io/support/docs/331-user-defined-types?v=0.9.2
You get to it by
new -> schema object -> type

**Comment by mkocztorz** [comment]
How can I edit the user defined type (enum)?
