### ISSUE TITLE
Can't use citext as datatype.

### ISSUE THREAD

**Issue by rokkie** [pgmodeler/pgmodeler#1182]
**Bug description**
Can't use `citext` as datatype.

**How to reproduce**
 - install `postgres-contrib`
   `sudo apt-get install postgresql-contrib`
 - create new model / open existing model
 - create new extension
   `CREATE EXTENSION citext WITH SCHEMA public;`
 - create table / edit existing table
 - create column / edit existing column
 - type `citext` in `Type` field.

**Expected behavior**
The field should get the `citext` type.

**Actual behavior**
The format says `invalid_type`.
If you click 'Apply' anyway, a dialog appears with the message:
'Assignment of invalid type to the object!'.

**Screenshots**
![screenshot from 2018-09-25 10-53-03](https://user-images.githubusercontent.com/1914675/46004267-bc42b480-c0b2-11e8-9e19-4058a94388fc.png)
![screenshot from 2018-09-25 10-57-32](https://user-images.githubusercontent.com/1914675/46004281-c369c280-c0b2-11e8-8bd2-8f648f5c5446.png)

**Info about your desktop**
 - OS: Ubuntu
 - Version: 16.04.5
 - Window manager: Compiz
 - pgModeler version: 0.9.2-alpha (ae32fbb90b0a86d92065bf8b2fe8d986078d6f98)
 - Qt version: 5.5.1
 - Postgres: 10

**Stacktrace / Debug info**
```
[1] src/pgsqltypewidget.cpp (216)
  PgSQLType PgSQLTypeWidget::getPgSQLType()
    [ERR_ASG_INV_TYPE_OBJECT] Assignment of invalid type to the object!

[0] src/columnwidget.cpp (206)
  virtual void ColumnWidget::applyConfiguration()
    [ERR_ASG_INV_TYPE_OBJECT] Assignment of invalid type to the object!

```

**Additional info**
I've tried installing the extension in `public` and `pg_catalog`, both to no avail.

Output of `\dx`:
```
postgres=# \dx
                            List of installed extensions
   Name    | Version |   Schema   |                   Description                    
-----------+---------+------------+--------------------------------------------------
 adminpack | 1.0     | pg_catalog | administrative functions for PostgreSQL
 citext    | 1.4     | pg_catalog | data type for case-insensitive character strings
 pgcrypto  | 1.3     | public     | cryptographic functions
 plpgsql   | 1.0     | pg_catalog | PL/pgSQL procedural language
 uuid-ossp | 1.1     | public     | generate universally unique identifiers (UUIDs)
(5 rows)
```

**Comment by rkhaotix** [comment]
https://pgmodeler.io/support/docs/317-extensions

You need to check ```Handles data type``` while creating the extension.

**Comment by rokkie** [comment]
@rkhaotix Ah! I dodn't know that! Solved the problem!
Tnx!
