### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by aidanw** [pgmodeler/pgmodeler#1184]
**Bug description**
When validating my model in the latest alpha version I get the following error

> Could not execute the SQL command.
>  Message returned: `ERROR:  permission denied to create "pg_catalog.geometry_dump"
> DETAIL:  System catalog modifications are currently disallowed.
> '

In 0.9 it was validating fine.

**Expected behavior**
my model to validate

**Info about your desktop**

 - OS: win10 64bit
 - Version: 0.92-alpha (licensed)
 - Window manager: ?
 - pgModeler version: ?
 - Qt version: ?

**Additional info**
This was fine before I upgraded to the paid for alpha version.
The only additional thing that changed was I had "CREATE EXTENSION Postgis" prepended in my model (properties -> custom sql -> prepend sql) And that failed validation, but removing that sql and hitting the 'fix' button seemed to fix that problem.

**Comment by aidanw** [comment]
urgh I downgraded to 0.9.1 and I see the same issue...

Can you give me a download for 0.9.0 that was working, but does not seem available from the downloads page.

**Comment by aidanw** [comment]
Additionally when I do an export I get the same error, with maybe a bit more detail
(this is 0.9.1)
![2018-09-27 14_48_30-export model](https://user-images.githubusercontent.com/1986524/46150527-aaa10e80-c264-11e8-8bf7-bdf03a44d5a6.png)

**Comment by aidanw** [comment]
If I export to sql and run the sql in postgres I get the same error.

If I comment out the following line

`SET search_path TO pg_catalog,public,mongoose;`

then it just works...

How can I do the equivalent of commenting out that line during an export?

**Comment by rkhaotix** [comment]
See here: https://github.com/pgmodeler/pgmodeler/issues/1183

**Comment by rkhaotix** [comment]
The ```search_path``` can't be removed from there since the export process can fail in certain operations.

**Comment by aidanw** [comment]
Sorry to be stupid... from that linked issue, can you tell me how I "force the schema for the extension"?

**Comment by rkhaotix** [comment]
No problem @aidanw 

If you're writing the extension code use the keyword `SCHEMA`. If you're creating the extension from the editing dialog use the object picker "Schema".

See the docs here:
https://pgmodeler.io/support/docs/317-extensions
https://www.postgresql.org/docs/current/static/sql-createextension.html

**Comment by aidanw** [comment]
I cannot work out how to do this in the pgModeler interface... 

The auto fixer put this in the code of my model

```
<extension name="postgis">
</extension>
```

I changed it to

```
<extension name="postgis">
    <schema name="public"/>
</extension>
```

and we are happy again!

**Comment by rkhaotix** [comment]
Hm. I think I will improve the auto fix. Thanks for pointing out this!
