### ISSUE TITLE
Double call on tableview::configureobject() : tables painted twice.

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1198]
As I was trying to implement a new feature, I came along this bug.
I have setup QtCreator debugging and the stack trace for calls 1 & 2 is as follows :
https://framabin.org/p/?1eb3198e5d6a07d2#52U7lIDdY5ZvG+jSmWX0nE5PLB8GEelEK7i88Vm5O/Q=

Best regards,
Maxime

**Comment by Maxzor** [comment]
I believe it might come from BaseObjectWidget::finishConfiguration, it calls both :
- DatabaseModel::addObject, which triggers tableview constructor
- BaseGraphicObject::setModified, which triggers a signal s_objectModified requesting another configureobject().

**Comment by rkhaotix** [comment]
Hey @Maxzor !

Thanks for reporting that. It'll help me eliminate bottlenecks over the application. I'm focused in improving the drawing of the objects and this issue has some indirect impacts on performance but I'll look into it.
