### ISSUE TITLE
Cant import form existing database

### ISSUE THREAD

**Issue by tonykaralis** [pgmodeler/pgmodeler#1203]
**Bug description**
Cant import an existing database Postgres 10.5. I am not building from source. I have payed for a 6 month license. It is a simple database, nothing fancy. Only has a few tables. 

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
![image](https://user-images.githubusercontent.com/18276387/48333469-71bfcc00-e64f-11e8-8742-0a667b556164.png)

**Info about your desktop**
 - OS: Windows 10 Pro
 - Version: 1803 OS Build 17134.376
 - pgModeler version: 0.9.2
 - Qt version: Cant find qt version

**Stacktrace / Debug info**

```5] src/connection.cpp (415)
  void Connection::executeDMLCommand(const QString&, ResultSet&)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'
       ** 42703

[4] src/catalog.cpp (416)
  std::vector<std::map<QString, QString> > Catalog::getObjectsNames(std::vector<ObjectType>, const QString&, const QString&, attribs_map, bool)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[3] src/databaseimporthelper.cpp (149)
  std::vector<std::map<QString, QString> > DatabaseImportHelper::getObjects(std::vector<ObjectType>, const QString&, const QString&, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[2] src/databaseimportform.cpp (892)
  static std::vector<QTreeWidgetItem*> DatabaseImportForm::updateObjectsTree(DatabaseImportHelper&, QTreeWidget*, std::vector<ObjectType>, bool, bool, QTreeWidgetItem*, const QString&, const QString&, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[1] src/databaseimportform.cpp (738)
  static void DatabaseImportForm::listObjects(DatabaseImportHelper&, QTreeWidget*, bool, bool, bool, bool, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[0] src/databaseimportform.cpp (332)
  void DatabaseImportForm::listObjects()
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

**Comment by rkhaotix** [comment]
There's a bug on 0.9.2-alpha that prevents databases from PostgreSQL 10+ to be imported.

This is already fixed on 0.9.2-alpha1 to be released on December. You can download the files below and replace them on the ```schemas\catalog``` folder on pgmodeler's installation path 


https://raw.githubusercontent.com/pgmodeler/pgmodeler/0.9.2-alpha1/schemas/catalog/function.sch

https://github.com/pgmodeler/pgmodeler/blob/0.9.2-alpha1/schemas/catalog/aggregate.sch

**Comment by tonykaralis** [comment]
I have replaced the files, however is there an additional step that I need to do in order for it to take effect?

Its i still giving the same error

**Comment by tonykaralis** [comment]
@rkhaotix any help would be appreciated.

**Comment by robtsai** [comment]
I have the exact same problem.  I'm running Postgres 11.1.
I just bought the 12 month license.  Thanks!

**Comment by panamacheng** [comment]
What did you do?

**Comment by jannwe** [comment]
We're unfortunately having the same problem here.

**Comment by panamacheng** [comment]
When I update my database to 11.4, it was fixed as well, I am using  Linux with OS and was used like to used Postgresqladmin4

**Comment by brijmcq** [comment]
I'm having the same issue  with Postgres 11.4

**Comment by rkhaotix** [comment]
For those still running into this issue... Just upgrade your pgModeler installation to the latest one  .

**Comment by ogayte** [comment]
I have upgraded to 0.9.2-beta1 to solve that problem but now the error message is:

Could not access the file or directory C:/serveurs/pgmodeler/schemas/catalog/foreigndatawrapper.sch! Make sure that it exists or if the user has access permissions on it!
Indeed this file doesn't exist.

Other problem, the upgrade process changed my 12 months version to demo !

**Comment by ogayte** [comment]
I completely uninstalled pgModeller and then installed the version 0.9.2_snapshot_20190921 and it works now. Thank you.
