### ISSUE TITLE
I am getting warning for using demo version even when I purchased access key

### ISSUE THREAD

**Issue by manojb23** [pgmodeler/pgmodeler#1208]
I have downloaded pgModeler 0.9.1 using a purchased access key. However when I run, I see the message 'you are using a demo version. You cannot use more than 9 instances of an object' ?? 
Please help

**Comment by rkhaotix** [comment]
You have to download the complete version using the access key sent to your email. See here: pgmodeler.io/download

**Comment by manojb23** [comment]
Thank you. I uninstalled and reinstalled with the correct version using access key in the mail.

**Comment by manojb23** [comment]
It works now.
