### ISSUE TITLE
Can't open public schema anymore 

### ISSUE THREAD

**Issue by IsaakGroepT** [pgmodeler/pgmodeler#1210]
**Bug description**
As soon as I open the public schema (there's only one), the program crashes

**How to reproduce**
See above

**Expected behavior**
Open the schema and see the tables

**Screenshots**

**Info about your desktop**
 - OS: antergos
 - Version: latest (rolling release)
 - Window manager: kwin
 - pgModeler version: 0.9.2-alpha
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```
[3] src/connection.cpp (415)
  void Connection::executeDMLCommand(const QString&, ResultSet&)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'
       ** 42703

[2] src/catalog.cpp (416)
  std::vector<std::map<QString, QString> > Catalog::getObjectsNames(std::vector<ObjectType>, const QString&, const QString&, attribs_map, bool)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[1] src/databaseimporthelper.cpp (149)
  std::vector<std::map<QString, QString> > DatabaseImportHelper::getObjects(std::vector<ObjectType>, const QString&, const QString&, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[0] src/databaseimportform.cpp (892)
  static std::vector<QTreeWidgetItem*> DatabaseImportForm::updateObjectsTree(DatabaseImportHelper&, QTreeWidget*, std::vector<ObjectType>, bool, bool, QTreeWidgetItem*, const QString&, const QString&, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'
```

**Additional info**
I bought two licenses of your software, one for Win and one for Lin

**Comment by rkhaotix** [comment]
Please see this:
https://github.com/pgmodeler/pgmodeler/issues/1199

There's a bug on current releases that causes databases in PostgreSQL 11 not to bem imported. The solution is already done but the official launch only in December.

**Comment by rkhaotix** [comment]
Sorry, wrong issue...
Please, see this one:
https://github.com/pgmodeler/pgmodeler/issues/1203#issuecomment-441230352

**Comment by IsaakGroepT** [comment]
Thanks for the link but replacing the schemas doesn't solve my issue

**Comment by IsaakGroepT** [comment]
Seems to have been solved with the new alpha1 version. Thanks for all the work!

**Comment by panamacheng** [comment]
An error has occurred:

08:33:59 PM: Error: ERROR:  column "proisagg" does not exist
LINE 9:  WHERE proisagg = FALSE AND pronamespace = 2200::oid
               ^
HINT:  Perhaps you meant to reference the column "pr.prolang".

**Comment by panamacheng** [comment]
I had got this kinds of error from PostgresAdmin III when I refresh the database to check the seed.
What can I do for checking and fixing this error, Actrually, when I test the server on Ubuntu, I had got database connection error, what can I do?
I look forward to your reply soon.
Thanks.
