### ISSUE TITLE
ERR_REF_TUPLE_INEXISTENT

### ISSUE THREAD

**Issue by fpbarthel** [pgmodeler/pgmodeler#1212]
I have recently started getting the following "warnings" (suppressed when checking ignore import errors) when importing my database, but I have no idea what causes them.

```
[3] src/resultset.cpp (131)
  int ResultSet::validateColumnName(const QString &)
    [ERR_REF_TUPLE_INEXISTENT] Reference to a tuple with an invalid index or the result is empty (no tuples)!

[2] src/resultset.cpp (141)
  int ResultSet::validateColumnName(const QString &)
    [ERR_REF_TUPLE_INEXISTENT] Reference to a tuple with an invalid index or the result is empty (no tuples)!

[1] src/catalog.cpp (623)
  QString Catalog::getObjectOID(const QString &, ObjectType, const QString &, const QString &)
    [ERR_REF_TUPLE_INEXISTENT] Reference to a tuple with an invalid index or the result is empty (no tuples)!
       ** Object type: role

[0] src/databaseimporthelper.cpp (501)
  void DatabaseImportHelper::createPermissions()
    [ERR_REF_TUPLE_INEXISTENT] Reference to a tuple with an invalid index or the result is empty (no tuples)!
       ** -- Raw attributes: xxxx (OID: 17413) --
allow-conns: true
comment: 
connlimit: -1
encoding: UTF8
is-template: 
lc-collate: en_US.UTF-8
lc-ctype: en_US.UTF-8
name: xxxx
object-type: 21
oid: 17413
owner: 17412
permission: xxxx
tablespace: 1663
template: 
---
```

I have no issues with the database in any way that I know of. What could be the reason for this error? Unfortunately I could not find anything in the postgres or pgmodeler documentation that might help clear this up.

**Comment by sailfish009** [comment]
latest beta version(v0.9.4, msys2 self-build) still have this bug(no tuple),  
even if i checked ignore import error that doesn't worked.

**Comment by rkhaotix** [comment]
@sailfish009 could you provide a dump of your database so I can try to investigate?

**Comment by sailfish009** [comment]
@rkhaotix I'd like to give you a dump too, but unfortunately the database is not mine, and I can't give it to you for security reasons. I work for that company as a freelancer.

**Comment by jeabraham** [comment]
I have the same bug! My database has terrabytes of data, though, so I can also not send you a dump.
