### ISSUE TITLE
Import Databaseobjects postgres 11 failed

### ISSUE THREAD

**Issue by ingoschult** [pgmodeler/pgmodeler#1217]
**Bug description**
The import of database objects is aborted with the following error message

**How to reproduce**
Import database objects from postgres 11

**Expected behavior**
Could not execute the SQL command.
Message returned: Fehler. Spalte pr.proisagg existiert nicht
LINE 1: ... namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag ..

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: Windows 10 
 - Version: 1803 (Build 17134.441)
 - Window manager:
 - pgModeler version: v0.9.2-alpha build: 20180818
 - Qt version: Qt 5.9.3

**Stacktrace / Debug info**
[5] src/connection.cpp (415)
  void Connection::executeDMLCommand(const QString&, ResultSet&)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.
'
       ** 42703

[4] src/catalog.cpp (416)
  std::vector<std::map<QString, QString> > Catalog::getObjectsNames(std::vector<ObjectType>, const QString&, const QString&, attribs_map, bool)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.
'

[3] src/databaseimporthelper.cpp (149)
  std::vector<std::map<QString, QString> > DatabaseImportHelper::getObjects(std::vector<ObjectType>, const QString&, const QString&, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.
'

[2] src/databaseimportform.cpp (892)
  static std::vector<QTreeWidgetItem*> DatabaseImportForm::updateObjectsTree(DatabaseImportHelper&, QTreeWidget*, std::vector<ObjectType>, bool, bool, QTreeWidgetItem*, const QString&, const QString&, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.
'

[1] src/databaseimportform.cpp (738)
  static void DatabaseImportForm::listObjects(DatabaseImportHelper&, QTreeWidget*, bool, bool, bool, bool, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.
'

[0] src/databaseimportform.cpp (332)
  void DatabaseImportForm::listObjects()
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `FEHLER:  Spalte pr.proisagg existiert nicht
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Vielleicht wurde beabsichtigt, auf die Spalte »pr.prolang« zu verweisen.

**Comment by edbizarro** [comment]
I have the same problem with pg 11

**Comment by MarcusRiemer** [comment]
Related: https://github.com/jOOQ/jOOQ/issues/7785

This was also mentioned on the mailing list: https://www.postgresql.org/message-id/153486142520.1370.12035528830969343708%40wrigleys.postgresql.org
