### ISSUE TITLE
Behavior bug on canvas layers : tagging unhides

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1222]
Hello,
Setting a tag on an object unhides all layers.
BR, Maxime

**Comment by Maxzor** [comment]
I believe there is also a bug, which ill try to reproduce, where tagging moves objects between layers (default layers was empty).

**Comment by Maxzor** [comment]
It is actually maybe even worse than that. After an unkown manipulation related to tags and layers, all model objects went fade out oO

**Comment by rkhaotix** [comment]
Couldn't reproduce the bug. Please, detail the steps so I can see it happening. On my test everything was ok.

**Comment by Maxzor** [comment]
The layer unhiding happens to me systematically, when I click on quick - set tag.
For the other bug I will try to reproduce it.

**Comment by Maxzor** [comment]
I understand this garbage issue will not help you much but to me some strange things are happening :)
Just discovered the metadata handle and restore feature and its great I recovered it all.

**Comment by Maxzor** [comment]
Ah also relationships loose their color at some point.
