### ISSUE TITLE
Scripts for extensions are generated at the end

### ISSUE THREAD

**Issue by robregonm** [pgmodeler/pgmodeler#1223]
**Bug description**
Extensions script is generated at the end of SQL source, but it should be added at the beginning to avoid errors like #560 and #1023 

**How to reproduce**
- Create a model
- Add one or more tables to model
- Add a extension using right click -> New -> Extension
- Save changes
- Right click and select source

**Expected behavior**
It should generate a `CREATE EXTENSION IF NOT EXISTS xyz;`

**Info about your desktop**
 - OS: Ubuntu
 - Version: 18.04
 - pgModeler version:0.9.2-alpha1

**Comment by technorior** [comment]
And extension name shoud be with quotes

**Comment by rkhaotix** [comment]
pgModeler already quotes the names if needed. Can you give an example of what name should be quoted? Maybe there's a bug.
