### ISSUE TITLE
"Fix a model" do not support new "Layers" feature

### ISSUE THREAD

**Issue by Mike0007** [pgmodeler/pgmodeler#1225]
**Bug description**
New Feature "Layers" will be deleted by model Fix.

**How to reproduce**
Create a model with Layers and then try to use "Fix a model" option.

**Expected behavior**
"Layers" should be not deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/3176797/50521321-67557680-0ac5-11e9-88b2-2f0e8d78e7bd.png)

**Info about your desktop**
 - OS: Windows 
 - Version: 7 Pro
 - Window manager: 
 - pgModeler version: v0.9.2-alpha 1
 - Qt version: 5.9.3

**Comment by Maxzor** [comment]
I second this, some bugs need treatment on layers + fixing.
Very often a model with tags and layers, while saved with model validation, appears broken and then, after fixing, some layers, tags and even tagged objects disappear :(
