### ISSUE TITLE
can not start on ubuntu 18.04.1

### ISSUE THREAD

**Issue by andy-igoshin** [pgmodeler/pgmodeler#1228]
**Bug description**
pgModeler can not start on ubuntu 18.04.1.

**How to reproduce**
attempt to start pgModeler.

**Expected behavior**
pgModeler should start.

**Info about your desktop**
 - OS: ubuntu
 - Version: 18.04.1
 - Window manager: KDE
 - pgModeler version: 0.9.1, 0.9.2alpha1
 - Qt version: 5.9.5

**Stacktrace / Debug info**

0.9.1
------
cd /opt/pgmodeler
$ ./pgmodeler
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

0.9.2alpha1
----------------
cd /opt/pgmodeler
$ ./pgmodeler
./pgmodeler
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ai'
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50906)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ai'
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50906)
Aborted (core dumped)
QThread::wait: Thread tried to wait on itself
QMutex: destroying locked mutex
QMutex: destroying locked mutex
QThread: Destroyed while thread is still running
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ai'
Cannot mix incompatible Qt library (version 0x50905) with this library (version 0x50906)
Aborted (core dumped)
QObject::~QObject: Timers cannot be stopped from another thread

**Comment by andy-igoshin** [comment]
start-pgmodeler.sh helps.

**Comment by arnab4892** [comment]
If I use start-pgmodeler.sh it starts but then gives the following errors:
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_num_locks
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_id_callback
qt.network.ssl: QSslSocket: cannot resolve CRYPTO_set_locking_callback
qt.network.ssl: QSslSocket: cannot resolve ERR_free_strings
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_cleanup
qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_init
qt.network.ssl: QSslSocket: cannot resolve sk_new_null
qt.network.ssl: QSslSocket: cannot resolve sk_push
qt.network.ssl: QSslSocket: cannot resolve sk_free
qt.network.ssl: QSslSocket: cannot resolve sk_num
qt.network.ssl: QSslSocket: cannot resolve sk_pop_free
qt.network.ssl: QSslSocket: cannot resolve sk_value
qt.network.ssl: QSslSocket: cannot resolve SSL_library_init
qt.network.ssl: QSslSocket: cannot resolve SSL_load_error_strings
qt.network.ssl: QSslSocket: cannot resolve SSL_get_ex_new_index
qt.network.ssl: QSslSocket: cannot resolve SSLv3_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv3_server_method
qt.network.ssl: QSslSocket: cannot resolve SSLv23_server_method
qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get_chain
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_noconf
qt.network.ssl: QSslSocket: cannot resolve OPENSSL_add_all_algorithms_conf
qt.network.ssl: QSslSocket: cannot resolve SSLeay
qt.network.ssl: QSslSocket: cannot resolve SSLeay_version
qt.network.ssl: QSslSocket: cannot call unresolved function SSLeay
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_client_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
Any idea as to how to resolve this.

**Comment by Skealz** [comment]
I had the same issue with the same setup.

I edited pgmodeler.vars to fit my QT5 installation, manually verifying that each path is correct.
Particularly, i changed the lib line to : 
`# Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/"`

Full config : 
`#!/bin/bash

# If you have root access you can rename this file to pgmodeler.sh and put it on
# /etc/profile.d (if you system supports this technique).
#
# If you do not have root access you can change this file and install it
# as a .bashrc or .bash_profile.
#
# In both cases above you will need to set the PGMODELER_ROOT variable with
# the full path to pgModeler root directory.


# ---[ Custom Qt configuration ]---
#
# This section specifies some environment vars responsible to find Qt framework installation in your system.
# Make sure to have the command "qtpaths" correctly mapped into your PATH environment variable or use the
# QT_PATHS_BIN variable below to specify the mentioned command.
#
# If you have a custom Qt installation at /opt/qt-5.9.6 for example, the path to the command above should be
# /opt/qt-5.9.6/5.9.6/gcc_64
#
# NOTE: Use the configuration below only if you have a custom Qt installation other than as defined by 
# your system or if Qt isn't included/installed by default on your distro.


# Replace the value of this variable by the full path to "qtpaths" if you have a custom Qt installation
 export QT_PATHS_BIN="/usr/bin/qtpaths"

# Qt's main environment variables
 export QT_ROOT="$($QT_PATHS_BIN --install-prefix)"
 export QT_BIN="$($QT_PATHS_BIN --binaries-dir)"
 export QT_PLUGIN_PATH="$($QT_PATHS_BIN --plugin-dir)"

# Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/"                       

 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$QT_LIBS"
 export PATH=$PATH:"$QT_BIN"
# --- [ End custom configuration ] ---

# Specify here the full path to the pgmodeler's root directory
export PGMODELER_ROOT="$(dirname "$(readlink -f "$0")")"
echo $PGMODELER_ROOT

export PGMODELER_TMPL_CONF_DIR="$PGMODELER_ROOT/conf"
export PGMODELER_SCHEMAS_DIR="$PGMODELER_ROOT/schemas"
export PGMODELER_LANG_DIR="$PGMODELER_ROOT/lang"
export PGMODELER_PLUGINS_DIR="$PGMODELER_ROOT/plugins"
export PGMODELER_SAMPLES_DIR="$PGMODELER_ROOT/samples"
export PGMODELER_CHANDLER_PATH="$PGMODELER_ROOT/pgmodeler-ch"
export PGMODELER_CLI_PATH="$PGMODELER_ROOT/pgmodeler-cli"
export PGMODELER_APP_PATH="$PGMODELER_ROOT/pgmodeler"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PGMODELER_ROOT/lib"
export PATH=$PATH:"$PGMODELER_ROOT"`

**Comment by Skealz** [comment]
I had the same issue with the same setup.

I edited pgmodeler.vars to fit my QT5 installation, manually verifying that each path is correct.
Particularly, i changed the lib line to : 
` # Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/" `

Full config : 
` #!/bin/bash

# If you have root access you can rename this file to pgmodeler.sh and put it on
# /etc/profile.d (if you system supports this technique).
#
# If you do not have root access you can change this file and install it
# as a .bashrc or .bash_profile.
#
# In both cases above you will need to set the PGMODELER_ROOT variable with
# the full path to pgModeler root directory.


# ---[ Custom Qt configuration ]---
#
# This section specifies some environment vars responsible to find Qt framework installation in your system.
# Make sure to have the command "qtpaths" correctly mapped into your PATH environment variable or use the
# QT_PATHS_BIN variable below to specify the mentioned command.
#
# If you have a custom Qt installation at /opt/qt-5.9.6 for example, the path to the command above should be
# /opt/qt-5.9.6/5.9.6/gcc_64
#
# NOTE: Use the configuration below only if you have a custom Qt installation other than as defined by 
# your system or if Qt isn't included/installed by default on your distro.


# Replace the value of this variable by the full path to "qtpaths" if you have a custom Qt installation
 export QT_PATHS_BIN="/usr/bin/qtpaths"

# Qt's main environment variables
 export QT_ROOT="$($QT_PATHS_BIN --install-prefix)"
 export QT_BIN="$($QT_PATHS_BIN --binaries-dir)"
 export QT_PLUGIN_PATH="$($QT_PATHS_BIN --plugin-dir)"

# Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/"                       

 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$QT_LIBS"
 export PATH=$PATH:"$QT_BIN"
# --- [ End custom configuration ] ---

# Specify here the full path to the pgmodeler's root directory
export PGMODELER_ROOT="$(dirname "$(readlink -f "$0")")"
echo $PGMODELER_ROOT

export PGMODELER_TMPL_CONF_DIR="$PGMODELER_ROOT/conf"
export PGMODELER_SCHEMAS_DIR="$PGMODELER_ROOT/schemas"
export PGMODELER_LANG_DIR="$PGMODELER_ROOT/lang"
export PGMODELER_PLUGINS_DIR="$PGMODELER_ROOT/plugins"
export PGMODELER_SAMPLES_DIR="$PGMODELER_ROOT/samples"
export PGMODELER_CHANDLER_PATH="$PGMODELER_ROOT/pgmodeler-ch"
export PGMODELER_CLI_PATH="$PGMODELER_ROOT/pgmodeler-cli"
export PGMODELER_APP_PATH="$PGMODELER_ROOT/pgmodeler"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PGMODELER_ROOT/lib"
export PATH=$PATH:"$PGMODELER_ROOT" `

**Comment by Skealz** [comment]
I had the same issue with the same setup.

I edited pgmodeler.vars to fit my QT5 installation, manually verifying that each path is correct.
Particularly, i changed the lib line to : 
`# Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/"`

Full config : 
``` #!/bin/bash

# If you have root access you can rename this file to pgmodeler.sh and put it on
# /etc/profile.d (if you system supports this technique).
#
# If you do not have root access you can change this file and install it
# as a .bashrc or .bash_profile.
#
# In both cases above you will need to set the PGMODELER_ROOT variable with
# the full path to pgModeler root directory.


# ---[ Custom Qt configuration ]---
#
# This section specifies some environment vars responsible to find Qt framework installation in your system.
# Make sure to have the command "qtpaths" correctly mapped into your PATH environment variable or use the
# QT_PATHS_BIN variable below to specify the mentioned command.
#
# If you have a custom Qt installation at /opt/qt-5.9.6 for example, the path to the command above should be
# /opt/qt-5.9.6/5.9.6/gcc_64
#
# NOTE: Use the configuration below only if you have a custom Qt installation other than as defined by 
# your system or if Qt isn't included/installed by default on your distro.


# Replace the value of this variable by the full path to "qtpaths" if you have a custom Qt installation
 export QT_PATHS_BIN="/usr/bin/qtpaths"

# Qt's main environment variables
 export QT_ROOT="$($QT_PATHS_BIN --install-prefix)"
 export QT_BIN="$($QT_PATHS_BIN --binaries-dir)"
 export QT_PLUGIN_PATH="$($QT_PATHS_BIN --plugin-dir)"

# Change the "lib64" by "lib" if you're running a 32 bit system
 export QT_LIBS="$QT_ROOT/lib/x86_64-linux-gnu/"                       

 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$QT_LIBS"
 export PATH=$PATH:"$QT_BIN"
# --- [ End custom configuration ] ---

# Specify here the full path to the pgmodeler's root directory
export PGMODELER_ROOT="$(dirname "$(readlink -f "$0")")"
echo $PGMODELER_ROOT

export PGMODELER_TMPL_CONF_DIR="$PGMODELER_ROOT/conf"
export PGMODELER_SCHEMAS_DIR="$PGMODELER_ROOT/schemas"
export PGMODELER_LANG_DIR="$PGMODELER_ROOT/lang"
export PGMODELER_PLUGINS_DIR="$PGMODELER_ROOT/plugins"
export PGMODELER_SAMPLES_DIR="$PGMODELER_ROOT/samples"
export PGMODELER_CHANDLER_PATH="$PGMODELER_ROOT/pgmodeler-ch"
export PGMODELER_CLI_PATH="$PGMODELER_ROOT/pgmodeler-cli"
export PGMODELER_APP_PATH="$PGMODELER_ROOT/pgmodeler"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$PGMODELER_ROOT/lib"
export PATH=$PATH:"$PGMODELER_ROOT" ```
