### ISSUE TITLE
Dark schema Mac OS X mohave

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#1229]
![2019-01-11 13 29 41](https://user-images.githubusercontent.com/3863428/51028770-7815ea00-15a5-11e9-88db-27baff329d99.png)

![2019-01-11 13 30 24](https://user-images.githubusercontent.com/3863428/51028779-7ea46180-15a5-11e9-85e2-f6031292fc98.png)

**Comment by fte1965** [comment]
And one more...
![2019-01-11 14 53 38](https://user-images.githubusercontent.com/3863428/51032371-d09eb480-15b0-11e9-99bf-fe42557dbd65.png)

**Comment by tzachshabtay** [comment]
Until there's a fix for this, you can run from terminal:
`defaults write br.com.pgmodeler.pgModeler NSRequiresAquaSystemAppearance -bool yes` and restart pgmodeler.

This will make the GUI usable again.
