### ISSUE TITLE
Add comment column in table editor

### ISSUE THREAD

**Issue by equinton** [pgmodeler/pgmodeler#1230]
**Feature description**
Is it possible to add a comment column in the table editor to show alls comments assigned ? 

Thanks,

Eric Quinton.

**Sample image**
![pgmodeler](https://user-images.githubusercontent.com/6715861/51468389-23c1f580-1d6f-11e9-9c2c-d2c51a34b7c3.png)

**Additional info**
_Add any other context or screenshots about the feature request here._

**Comment by rkhaotix** [comment]
Yes. It is! :)
I'll provide it.

**Comment by Rwing** [comment]
And is it possible to add a comment column in the design view?
![image](https://user-images.githubusercontent.com/497333/54173815-688c2200-44be-11e9-89ea-0d553302c773.png)
