### ISSUE TITLE
SVG unknown module

### ISSUE THREAD

**Issue by ocket8888** [pgmodeler/pgmodeler#1239]
## Bug description
Compilation on Linux failing due to: `Project ERROR: Unknown module(s) in QT: svg`

## How to reproduce
Download the source and dependencies, try to build with `qmake` as per instructions.

## Expected behavior
Compilation succeeds

## Screenshots
Sanitized command and output:

```
 user@host > ~/src/pgmodeler $ /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -r PREFIX=/opt/pgmodeler BINDIR=/opt/pgmodeler PRIVATEBINDIR=/opt/pgmodeler PRIVATELIBDIR=/opt/pgmodeler/lib pgmodeler.pro
Reading /home/user/src/pgmodeler/libutils/libutils.pro
Project ERROR: Unknown module(s) in QT: svg
```

## Info about your desktop
 - OS: Linux Mint 18.3 (64-bit)
 - Version: 4.15.0-43-generic
 - Window manager: Cinnamon
 - pgModeler version: both `master` and `develop`
 - Qt version: 5.5.1

## Stacktrace / Debug info
N/A

## Additional info
¯\\\_(ツ)\_/¯

**Comment by jimmykirk** [comment]
Try:

`sudo apt-get install libqt5svg5*`

**Comment by cfgobel** [comment]
Same issue in Linux Mint 20.1 (64-bit).

Installing libqt5svg5 solved.

**Comment by GileuNeto** [comment]
mesmo instalando =>  sudo apt-get install libqt5svg5*
nao consigo resolver 

o comando:
/usr/bin/qmake6 -r CONFIG+=release PREFIX= BINDIR= \ PRIVATEBINDIR= PRIVATELIBDIR=/lib pgmodeler/pgmodeler.pro

resultado:
Reading /home/mirgus01/pgmodeler/libs/libutils/libutils.pro [/home/mirgus01/libs/libutils]
Project ERROR: Unknown module(s) in QT: svg

**Comment by jimmykirk** [comment]
> mesmo instalando => sudo apt-get install libqt5svg5* nao consigo resolver
> 
> o comando: /usr/bin/qmake6 -r CONFIG+=release PREFIX= BINDIR= \ PRIVATEBINDIR= PRIVATELIBDIR=/lib pgmodeler/pgmodeler.pro
> 
> resultado: Reading /home/mirgus01/pgmodeler/libs/libutils/libutils.pro [/home/mirgus01/libs/libutils] Project ERROR: Unknown module(s) in QT: svg

Which distribution?

**Comment by GileuNeto** [comment]
I managed to solve it, but I don't remember what I did
