### ISSUE TITLE
Unknown attribute partitioning in relationship.sch

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1243]
**Bug description**
The following error is produced while generating a diff:

> Unknown attribute partitioning in file C:/Program Files (x86)/pgmodeler/schemas/alter/relationship.sch, line 14, column 38!

**How to reproduce**
Create a diff of a database model.

**Expected behavior**
You get the diff.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/1658949/52954568-d5fad600-338a-11e9-9bcb-3753038cfae1.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager:
 - pgModeler version: 0.9.2-alpha1
 - Qt version:

**Comment by oliversalzburg** [comment]
I'm currently suspecting that this is triggered because I removed an inheritance relationship from two tables. The error itself seems to be generic enough not to be triggered by something specific to our model.

**Comment by oliversalzburg** [comment]
Yeah, when I comment out all the parts relating to `partioning`, then I get my `ALTER TABLE NO INHERIT` line and the diff completes as expected.

However, I noticed a related bug. I previously had 2 tables where one inherited from the other and added 2 more columns. I dropped the inheritance and added the previously inherited columns to the table manually. In the diff, these newly added columns are not added to the table. Probably because they are assumed to already exist.

**Comment by rkhaotix** [comment]
Hi @oliversalzburg 

Do you have an small sample so I can test the bug?

**Comment by oliversalzburg** [comment]
Import this, then remove the inheritance and try to generate a diff.
[new_database.zip](https://github.com/pgmodeler/pgmodeler/files/2877334/new_database.zip)

**Comment by rkhaotix** [comment]
Thanks @oliversalzburg 

Found the problem and already fixed it! ;)

**Comment by oliversalzburg** [comment]
Awesome. Thanks for the quick work :)
