### ISSUE TITLE
Why copied column is removed from clipboard after first paste ?

### ISSUE THREAD

**Issue by cvgaviao** [pgmodeler/pgmodeler#1245]
Hello, 
I just started with pgModeler this week in my ubuntu (0.9.1-beta). Reaaly amazing tool !

But I'm facing a little problem and don't know if it is a problem from my side.

I'm trying to copy a column from one table to all others. But after the first paste I can't paste it to others anymore. I had to re-copy the column and do the paste again...

am I missing something ?

**Comment by rkhaotix** [comment]
Actually, this is a limititation of the tool. I'll improve the column copy process in such you to allow the user to paste the copied column on a set of selected tables.

**Comment by cvgaviao** [comment]
ok, thanks for the feedback ! 
btw-> "Parabéns pelo excelente produto !" ;)

**Comment by Maxzor** [comment]
(Hello, there is the same issue with full tables, please generalize this :) )
