### ISSUE TITLE
Validation error due to table being created below view requiring it

### ISSUE THREAD

**Issue by shemgp** [pgmodeler/pgmodeler#1253]
**Bug description**
_Validation error due to TABLE being CREATEd below VIEW requiring it._

**How to reproduce**
_I don't think I'm allowed to send our whole database schema, but it does occur in it consistently._
1. import public schema
2. validate
3. see error

**Expected behavior**
_I expect VIEWs to be CREATEd below tables to avoid this problem._

**Screenshots**
* Here's the error when validating:
  ![2019-03-12 pgmodeler precedence 1](https://user-images.githubusercontent.com/1734126/54172329-ac7c2880-44b8-11e9-8138-754ca9e3c039.png)
* Here's the view on top: 
  ![2019-03-12 pgmodeler precedence 2](https://user-images.githubusercontent.com/1734126/54172337-b2720980-44b8-11e9-8ed7-4c7cc186eaa2.png)
* Here's the table below: 
  ![2019-03-12 pgmodeler precedence 3](https://user-images.githubusercontent.com/1734126/54172340-b4d46380-44b8-11e9-9931-70ee86ec3853.png)

**Info about your desktop**
 - OS: Ubuntu
 - Version: 18.04.2
 - Window manager: gnome-shell
 - pgModeler version: 0.9.2~alpha1
 - Qt version: 5.9.5+dfsg-0ubuntu1

Thanks for looking at this.

**Comment by shemgp** [comment]
Looking more at the code: I guess the reason why some views go up into where the tables is because in `getCreationOrder` it uses `object->getObjectId()` as the map index.  Therefore when `getCodeDefinition` calls it, the *order* is based on `getObjectId` (since it's a map) instead of by functions, tables, then views, etc. 

Is this by design? Shouldn't it just use an incremental index map to retain the order?

**Comment by rkhaotix** [comment]
This is a classic case in which the table is being referenced from within a source code, in that case, the view's definition. Currently, pgModeler isn't able to detect this kind of reference and the user need to use the "Swap ids" feature to fix this kind of problem

Reference:
https://pgmodeler.io/support/docs/67-model-validation
https://pgmodeler.io/support/docs/68-swap-objects-ids

**Comment by shemgp** [comment]
Yes, but I think that `CREATE VIEW`s should always be after `CREATE TABLE` declarations, since you can't create a TABLE that references a VIEW in PostgreSQL anyway (https://stackoverflow.com/questions/34499323/is-it-possible-to-refer-a-column-in-a-view-as-foreign-key-postgresql-9-4).  

It's even in the code, where there's a loop for processing views. But it doesn't do anything since the views are scooped up by another loop on top of it.  That's why my PR (#1254) had to exclude the VIEW from the top loop so it'll go to the views loop.

The PR helps me have my workflow quicker since I don't have to swap ids since it forces all `VIEW`s to be after `TABLE` declarations.
