### ISSUE TITLE
Run diff but ignore a specific schema? Or run only on specific schema?

### ISSUE THREAD

**Issue by GollyJer** [pgmodeler/pgmodeler#1256]
I have a simple chat database that looks like this.

![image](https://user-images.githubusercontent.com/689204/54483346-cbf3b800-480e-11e9-921c-2d9c947998be.png)

I then run a GraphQL tool called Hasura on the database. Hasura creates it's own schema which makes the database look like this.
![image](https://user-images.githubusercontent.com/689204/54483355-e463d280-480e-11e9-9c65-835408a1931a.png)

_To get see this in pgModeler I have to run "Import" with "Ignore errors" turned on._

**My goal is to continue to update my Public scheme inside pgModeler even after Hasura has done it's thing.**

But, when I run the diff I get errors.
`The object hdb_catalog.hdb_primary_key (View), oid 17158, could not be imported due to one or more errors! Check the exception stack for more details. HINT: if the object somehow references objects in pg_catalog or information_schema consider enable the importing of system objects.`

Is there a way to only look a Public when running a diff? Or maybe say "Ignore this schema" when running a diff?

Any other help in troubleshooting this issue is helpful.

Thanks! 👍
Jeremy

**Comment by rkhaotix** [comment]
Hi @GollyJer 

Okay, we have two problems here:

1) pgModeler is having problems importing a view called ```hdb_primary_key``` on schema ```hdb_catalog.hdb_primary_key". Since this can denote a bug I'll need the entire stack trace generated when the import process is aborted. Running the importing in debug mode helps too because you can attach here the generated log file. If you can share your database dump (without data) I can test it here on my side.

2) Currently, there's no way to diff just a set of objects in the database. The process for now needs to read the entire database in order to check the changes. I'm already planning some approaches to solve this issue.

Now the workarounds... You can try one of the following things:

1) In the database import dialog check only the objects you want to see in the resulting model. When you do the diff using the generated model (from the previous step) don't forget to check ```Don't drop missing objects``` , this can help you to achieve what you need. 

2) Import the whole database as is. After that disable the SQL code of the schema ```hdb_catalog```. pgModeler will ask you to deactivate the SQL code for the children of that schema, you can confirm. Now, run the diff normally and see the results. In this approach pgModeler doesn't include in the comparison the objects with SQL code disabled. This is a way to tell the tool "don't compare these objects to anything, ignore it!". Basically, if you won't compare an object on the model against the database just disable its SQL code.

See more info about SQL disabling and diff process here:
https://pgmodeler.io/support/docs/53-compare-a-model-and-a-database
https://pgmodeler.io/support/docs/21-basic-fields

**Comment by btroia** [comment]
Hi, I just ran in to the same issue and found this thread via google. Will this make it into v0.9.2? Thanks!

**Comment by GollyJer** [comment]
Hi @rkhaotix.  Can we donate more to prioritize this issue?

**Comment by GollyJer** [comment]
This works for us now in the postgres 12 and the newest pgmodeler. 🎉

**Comment by Maxzor** [comment]
How?

**Comment by rkhaotix** [comment]
@GollyJer I was about the ask that too... I didn't implemented that yet! Were the workaround enough for you case? :)

**Comment by GollyJer** [comment]
@Maxzor @rkhaotix I take it back. We are just working around the issue. 
We just bought a lifetime license so this will ultimately be an awesome feature to have some day. Thanks!

**Comment by rkhaotix** [comment]
@GollyJer thanks for the lifetime access key! :)
I already flagged  to implementation the issue related to partial diff. I hope that still in 0.9.3-alpha1 we have some preview of the feature. ;)

**Comment by Maxzor** [comment]
A [poorly-sketched idea](#1220) but wouldn't it be nice to fusion 4 existing features into one :

1. export
2. import
3. diff
4. obj-metadata
?

**Comment by rkhaotix** [comment]
@Maxzor This will demand some deep UI redesign. This kind of task/discussion I prefer to let to pgModeler 1.0. For now I think refine things that are ready is the best approach.

**Comment by GollyJer** [comment]
@rkhaotix Now we're using supabase. A really cool postgres service.
But, I'm running into even more diff issues because they have a ton of other schemas by default. 
Did the ability to do a partial diff ever get implemented? I'm not seeing it.

Ideally I could tell pgModeler to only diff a specific schema, `public`, in this case.

**Comment by rkhaotix** [comment]
@GollyJer The partial diff is implemented since 0.9.3-beta :)

https://www.pgmodeler.io/support/docs/53-compare-model-and-database?v=1.0.0

**Comment by GollyJer** [comment]
😀
