### ISSUE TITLE
Updater error at start

### ISSUE THREAD

**Issue by madtyn** [pgmodeler/pgmodeler#1258]
Hello,

pgModeler is giving me the error attached in the screenshot about the updater failing. Not a big deal, but it's a little annoying.

I'm using kubuntu 18.10 with 64bits architecture and my internet connection is fine and working..

![pgmodeler_updater_error](https://user-images.githubusercontent.com/2944906/54994707-32be6180-4fc5-11e9-9cf7-837e5cb85377.png)

**Comment by rkhaotix** [comment]
Hi! This is an incompatibility with openssl libs on you machine... See here (the warning box at the start of the text):
https://pgmodeler.io/blog/2018/8/20/pgmodeler-092-alpha-is-out

**Comment by Maxzor** [comment]
You can also compile with the no_update macro.

**Comment by madtyn** [comment]
I'm reading just now.

I didn't compile, I bought the binary 64bits package

**Comment by rkhaotix** [comment]
@madtyn you can try to deactivate periodic updates checking on pgModeler's settings.
