### ISSUE TITLE
Failure to access system32 folder on startup

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1260]
**Bug description**
When I open a `.dbm` file with `pgmodeler.exe`, it attempts to access content in `C:\Windows\system32\`.

**How to reproduce**
Install pgModeler, open a `.dbm` file with `pgmodeler.exe`.

**Expected behavior**
Model is opened.

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/55943437-e3c02f80-5c46-11e9-9d1d-425648c447d9.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager:
 - pgModeler version: 0.9.2-alpha1
 - Qt version:

When I attempted this for the first time after installation, I got a different error. Looked like #964. On the second and successive attempts, I got the error above.

**Comment by oliversalzburg** [comment]
Just FYI, I only attempted this because `.dbm` files were not associated with PgModeler after installation, even though the option was set. The file type was still associated with Winamp.

**Comment by rkhaotix** [comment]
@oliversalzburg I know this issue happened long ago but do you still have this problem? I made a lot of improvements on the file association and the config files loading.

**Comment by oliversalzburg** [comment]
This doesn't appear to be a problem anymore. I can open `.dbm` directly without any issue with 0.9.4-alpha1 👍
