### ISSUE TITLE
macos install

### ISSUE THREAD

**Issue by viclew** [pgmodeler/pgmodeler#1262]
**Bug description**
_A clear and concise description of what the bug is._

**How to reproduce**
_Please, if the bug can be reproduceable describe the steps in full details. If possible provide a sample model and/or a SQL dump for test purposes._

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by viclew** [comment]
Hi, I could not install Pgmodeler on my Mac - MacOS Mojave 10.14.4

Pgmodeler version: 0.9.1 or 0.9.2-alpha1 

**PGmodeler Error Message:**

Failed to create initial configuration in /Users/viclew/Library/Preferences/io.pgmodeler! Check if the current user has write permission over that path and at least read permission over /Applications/pgmodeler.app/Contents/MacOS/conf.

**Comment by rkhaotix** [comment]
Try to create ```/Users/viclew/Library/Preferences/io.pgmodeler``` manually and start the application. Also, check if ```/Applications/pgmodeler.app/Contents/MacOS/conf``` is not empty or if you don't have permissions on both paths

**Comment by viclew** [comment]
Thanks, resolved.
