### ISSUE TITLE
Tables are offset during dragging operation, drop in unexpected location

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1273]
**Bug description**
When you drag a table, it is almost impossible to figure out how it will be placed on the grid when you drop it.

**How to reproduce**
1. Enable "Align object position to grid".
2. Drag a table.
3. Drop the table.

**Expected behavior**
It should be clear where the table will be dropped, but because it is misaligned with the grid during the drag operation, it is almost impossible to determine where it will be dropped. This results in having to repeat the operation multiple times, which is extremely frustrating.

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![image](https://user-images.githubusercontent.com/1658949/57682413-14bec600-7632-11e9-86e1-a7793e44c4eb.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager: Explorer
 - pgModeler version: 0.9.2-alpha1
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by Maxzor** [comment]
Hello,
It is really not a problem to me
When align-to-grid is toggled, graphical objects are aligned with the top left corner of the item matching a grid node. Actually when I drag and drop slowly I can see the object moving "from node to node".
To me only thing slightly bothering is the position infobox (the cartesian coordinates) that masks this particular top left area.

And you can always disable drag and drop. _And_ if u still want perfectly aligned tables you can then cherry-pick
https://github.com/pgmodeler/pgmodeler/pull/1207/commits/602e9dcd24c400dfaa96ab33cec958e76459861c
(will repull soon)
BR, Maxime

**Comment by oliversalzburg** [comment]
Well, I _do_ want items to be aligned to the grid, but I feel like the place they are dropped in is unpredictable. You pick up a table, move it only horizontally and it is then dropped one row higher or lower  than where you picked it up, just because it was offset during the drag operation.

It appears to me like the offset of the entire canvas plays a role in this. So the behavior is constantly different, depending on the current position of the work area. This is extremely confusing.

**Comment by rkhaotix** [comment]
@oliversalzburg Yeah, you're right. The current position of the canvas (defined by the scrollbars at the bottom and right ) is causing some noise in the calculation of the snapping point. I'm working on it right now.

**Comment by Maxzor** [comment]
I get your concern and was at one point in time also midly infuriated by this I recall.
The thing is by magic today, I don't have parasite offsets, the table moves one cell by one cell, and I can clearly and predictably see where it is going.
https://youtu.be/ZfouvFHsM-g
Actually... it looks like there is an offset at start, which clears totally after a few drops. ?

**Comment by oliversalzburg** [comment]
@Maxzor That video looks just like it is for me. At first I thought, while dragging, the table is moved relative to the center of grid cells and tried to adjust my movement and drop location assumptions accordingly. But then I move the canvas a bit and it behaves differently. It was driving me crazy. Every time I thought I understood what was going on, it was slightly different the next time.

I only realized that the canvas offset plays a role when I tried to gather more useful information earlier.

I'm happy to see that @rkhaotix was able to reproduce it. A fix would be greatly appreciated.

**Comment by rkhaotix** [comment]
Don't worry @oliversalzburg , I'll provide the fix ASAP. :)

**Comment by rkhaotix** [comment]
@oliversalzburg ... and voilà c33943f1dfdc70b7c4f8d6d7ee1e39b897764c9f :)

**Comment by oliversalzburg** [comment]
Awesome :D I'll have to wait for the next release though. I've never built pgModeler.

And, wow, that's a lot larger change than I would have assumed. I would not have thought the float vs double precision would make such a difference.

**Comment by rkhaotix** [comment]
@oliversalzburg Don't mind the float replacement... I was just eliminating some warnings due to the loss of precision when assigning double values to float variables. I forgot to make this change on a separated commit! :p

The fix for the bug you have reported was done here https://github.com/pgmodeler/pgmodeler/commit/c33943f1dfdc70b7c4f8d6d7ee1e39b897764c9f#diff-281b265952ea2479c8dad9ebf1e96168R361 
and
https://github.com/pgmodeler/pgmodeler/commit/c33943f1dfdc70b7c4f8d6d7ee1e39b897764c9f#diff-5adb8f75eb537fc1b23a821d98b1e854R392

**Comment by oliversalzburg** [comment]
Oh, I see. I was confused because I didn't see it mentioned in the commit message, so I thought it just came down to precision 😄 This makes more sense.

**Comment by oliversalzburg** [comment]
This is working great in the 0.9.2-beta! Awesome!
