### ISSUE TITLE
Hide changelist while generating diff

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1276]
**Feature description**
When the diff is being generated, the process is needlessly slowed down by updating the UI.

When you generate a diff, and the diff tool window is maximized to use the full screen, the process takes considerably longer than if you make the window as small as possible.

I don't consider it important to watch the changes being populated live, as I mostly care about the result. Having the changes updated live during the processing only slows down the process.

My suggestion would be to not populate the list while the changes are being generated.

**Sample image**
![image](https://user-images.githubusercontent.com/1658949/57844098-aa438c80-77cf-11e9-8799-7fc4ca23f552.png)

**Comment by Maxzor** [comment]
A much broader, much harder, and I think much more appropriate solution is to multithread the app :)

**Comment by oliversalzburg** [comment]
If it's harder, why not start with something simple?

It seems like massive overengineering to rewrite entire parts of your application to preserve live updating a UI that probably has little relevance, compared to the functionality it visualizes.

Personally, I don't need to see those changes at all and I especially don't need to see the list updated on every action taken. I also don't need someone to invest a huge amount of time to multithread their application so that I can then get a fluent display of an information that is redundant and serves no real purpose.

**Comment by Maxzor** [comment]
I totally get your point of view^ It is just that it seems to me that  a lot of other parts of the application would benefit from multithreading aswell : model loading, validation, diffing as in here, maybe saving...

**Comment by rkhaotix** [comment]
@Maxzor all that you cited is already running on a separated thread to increase performance.

@oliversalzburg if you need less information, for now, you can use the CLI version of the diff:
https://pgmodeler.io/support/docs/613-command-line-interface

Also, many users like to see all that is happening in the process (me included). Anyway, It's not hard to tweak the diff output to hide such information, but I see this task having a minor importance compared to other I have to do. But your request has its relevance and I'll provide some improvements in the future.

FYI, I've made a quick benchmark here by disabling almost all code that performs the output population. Diff'ing a model with almost 2000 objects against its counterpart on a database server was "only" 2.5 seconds quickier than the original process (that outputs everything).

**Comment by oliversalzburg** [comment]
Maybe it's specific to Windows (10), but in my case the difference is far more significant. I have sent you a bug report via email earlier with my current DB model.

When I have the diff window maximized to full screen, the process takes 1:41.07, when I have the window at the smallest size, it takes 0:35.55.

**Comment by rkhaotix** [comment]
Hmm... That's a lot of difference. I use Linux as my main OS and I can usure that the process has a satisfactory performance. 

In fact, pgModeler is slower on Windows. I really don't know why... but I suspect that Qt does things behind the scenes that causes these slow downs. This is the trade off of using a multplatform C++ framework. :(

I'll try release a test feature that optionally disables part of the output of the diff process to see if it can improve the speed on Windows

**Comment by oliversalzburg** [comment]
It's really not critical at all for me. I know how to handle it and just restore the window to smallest size and it's fine. I just wanted to make you aware that there is likely potential for optimization here. 😁

Maybe I'll even give the CLI a closer look. I was not aware of that previously. So this could become even less of an issue for me personally.

**Comment by rkhaotix** [comment]
@oliversalzburg You can download a preview of 0.9.2-beta using your access key (I did enable early access for you). Test the feature you've requested and put your feedback here, please. Just take care to use your "production" models in this new version since there were some changes. (I'll report everything on a dedicated post on the project's blog soon) :)

**Comment by oliversalzburg** [comment]
Will do! Thanks a lot 😊

I also noticed a couple more minor issues (although one crashes pgModeler) with the Diff dialog, which I'll report later.

**Comment by oliversalzburg** [comment]
It's weird that the default folder is `C:\pgmodeler`. And then there are these:

![image](https://user-images.githubusercontent.com/1658949/58245749-c73f0900-7d55-11e9-9a2f-1a159c4f3da3.png)

![image](https://user-images.githubusercontent.com/1658949/58245844-02413c80-7d56-11e9-8292-0646be25bc17.png)

![image](https://user-images.githubusercontent.com/1658949/58245852-08371d80-7d56-11e9-815f-0a71602f96d6.png)

**Comment by oliversalzburg** [comment]
When I run the installer "as Administrator" and use the default installation path, then I still get the first two warning dialogs (I click "Ignore"), but the installation completes.

**Comment by oliversalzburg** [comment]
I can't see any changes relating to the population of the Diff tool view. What am I missing?

**Comment by rkhaotix** [comment]
@oliversalzburg  about the issues on the installation... I've changed the installer builder. Now I'm using Qt installer framework on both Windows and Linux to make easier the maintainance. I'll check what's going on.

About the diff output... Sorry, my mistake, I forgot to mention how to enable the reduced output: go to settings and check ```Low verbosity for the export, import and diff process``` and run the diff again.

**Comment by oliversalzburg** [comment]
Awesome! I'll give it another try. If you need any input regarding the installation issues, let me know.

**Comment by oliversalzburg** [comment]
![image](https://user-images.githubusercontent.com/1658949/58249844-3588c900-7d60-11e9-9586-cf59b573d84a.png)
Info bubble won't hide when switching tabs.

Diff now completes in 0:14! 👌
