### ISSUE TITLE
Improvement : copy from everywhere?

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1277]
Encountering small itching-corners using the software professionally recently...
Currently on the design view copy/pastes is only useful to copy graphical objects (being able to copy them cross-model is great!).
It would be nice to be able to copy from everywhere, not only from the objectsScene.
For example copy the selection in a dockwidget, not doing anything more than copying raw text into clipboard.
It would be especially useful with the object finder : you could extract a list of items from pgmodeler, to, say, a spreadsheet.
It requires an eventfilter pretty high I guess, like on the mainwindow/modelwidget, to intercept ctrl+c hits and not redirect them to the objectScene selection.

**Comment by rkhaotix** [comment]
Thanks for your observations @Maxzor 

Just a small correction... You can copy any kind of objects from a model to another one. Just use the context menu when select an object in model objects widget (right side of the screen) . Currently only single selection is possible but I have plans to allow multiple selection on that widget.
