### ISSUE TITLE
FK name pattern is {st}_{sc} but pgmodeler generates {sc}_{st}

### ISSUE THREAD

**Issue by simasch** [pgmodeler/pgmodeler#1279]
**Bug description**
I configured the FK name pattern to be {st}_{sc} but pgmodeler generates {sc}_{st}

**How to reproduce**
Set the name pattern to {st}_{sc} and create a new relationship

**Expected behavior**
The name of the FK column should be {st}_{sc} 

**Info about your desktop**
 - OS: Windows 10
 - pgModeler version: 0.9.2

**Comment by rkhaotix** [comment]
Hi @simasch 

For now, pgModeler ignores the `{sc}` placeholder when defining the name of the generated contraints, if that's the case. I'll mark this as a feature request so I can implement it in the future.

**Comment by simasch** [comment]
@rkhaotix IMHO the current naming is wrong.

It generates column_table like id_employee but normally it's the other way around: employee_id

**Comment by rkhaotix** [comment]
Actually, this is a matter of taste. There's no convention for this, AFAIK.
Also, note that you can change the name pattern globally so you can define `{st}_{sc}` for all relationship you create on your model.

**Comment by simasch** [comment]
You misunderstood my bug report. Changing the name pattern globally, as you call it, doesn't work! That's the bug I'm complaining about.

**Comment by rkhaotix** [comment]
Okay... maybe I misunderstood you. Let's see, based on the image what field you are using the pattern `{st}{sc}`?

![name_pattern](https://user-images.githubusercontent.com/2205476/58327096-1728d900-7e05-11e9-8530-e6db3e18bb60.png)

I'm asking that because on my tests the result was the expected.

**Comment by simasch** [comment]
I'm setting Column (Source)

**Comment by rkhaotix** [comment]
Pattern: `{st}_{sc}` where `{st}` = `table_a` and `{sc}` = `id`
Result: `table_a_id`

![name_pattern_2](https://user-images.githubusercontent.com/2205476/58327703-9ff44480-7e06-11e9-8079-b2113f23f417.png)

**Comment by rkhaotix** [comment]
Maybe it's a bug that your model raised, could you share it?

**Comment by simasch** [comment]
I'm setting it as global configuration.

![configuration](https://user-images.githubusercontent.com/593352/58328266-f9be3400-7e31-11e9-91a5-f95ad0f2b5da.png)
![model](https://user-images.githubusercontent.com/593352/58328267-fa56ca80-7e31-11e9-9373-aa23dcbfb60d.png)

**Comment by rkhaotix** [comment]
Ok. I have some questions:

1) Are you setting the global pattern __after__ creating the relationship?
2) Creating another relationship after configuring the global pattern has the same unexpected result?

**Comment by simasch** [comment]
I tried both after and before with the same result

**Comment by mattdavenport** [comment]
Any update here? I just bought a copy of pgmodeler and it becomes a bit tedious making relationships due to this bug. I am on v0.9.2-beta1_snapshot201906... build 20190629 macOS Mojave.

The workaround I've found that works is every time the relationship modal pops up, go to Settings -> Name Patterns, uncheck then re-check `Use global settings for these fields`. This seems to make it work, but it's a bit of a hassle.

Thanks!

**Comment by rkhaotix** [comment]
I still can't reproduce that bug. On my side all is working correctly for all relationships that works with name pattern. 🤔

**Comment by rkhaotix** [comment]
@mattdavenport  what's the pattern and relationship type you're using? Can you share an small example?

**Comment by mattdavenport** [comment]
@rkhaotix Sure thing. [Here](https://www.dropbox.com/s/8p7mewma2uzkrx9/Screenshot%202019-07-22%2012.16.41.png?dl=0) is a screenshot of a simple example I created. Here are the steps I took:

1. Add `order` table with a serial `id` field
2. Add `item` table with a serial `id` field
3. Add `One-To-Many` relationship from `order` to `item` table.

These steps generated the output shown in the screenshot (configuration included for reference).

Thanks!

**Comment by ibot3** [comment]
AFAICS, the problem still persists. It is working fine if you uncheck the `Use global setings for these fields` box and insert it manually. But if you change the default value to `{st_sc}` and create a new relationship without touching the name pattern settings (because it is correctly set in the default settings), the new column is still named `{sc_st}`.

@rkhaotix You may misunderstood that the problem is that the default value is not used, even if it should be used.

**Comment by rkhaotix** [comment]
@ibot3 are you able to create a video in which you reproduce this behavior? Once again, I've tested all the ways to create the relationships, changed global patterns, used them and not used them too (by using custom patterns per relationship) and everything was ok. Maybe I missing something... a video showing the problem can help a lot.

**Comment by ibot3** [comment]
I think I figured out when the problem ocurs. If I create a (one-to-many) relationship without even visiting the `settings` tab, the wrong format is used. If I at least open the `setings` tab once, the correct default value is used.

[Video](https://i.imgur.com/sgCdjvV.gif)

**Comment by rkhaotix** [comment]
@ibot3 Thank you very much!!! Now, I can confirm that this is a bug. I'll provide the proper fix to it.
