### ISSUE TITLE
Generating and modifying diagrams from existing tables [Question]

### ISSUE THREAD

**Issue by hubitor** [pgmodeler/pgmodeler#1286]
In phpMyAdmin  I'm able to edit the diagrams of tables and their relationships for a given database within the "Designer". In pgModeler I couldn't find such a feature. Is it also possible with pgModeler? If not, please consider to add this feature to it.

**Comment by Maxzor** [comment]
In pgmodeler, you can edit **directly** items in a database, ony from the "manage" section.
But this is not "graphically", like in the design section.
In the design section, you work on models, that are not directly tied to a database. You can model a database without ever implementing your model.
The dual-way bond with the database is achieved via the diff/import/export feature.

**Comment by hubitor** [comment]
Thanks!
