### ISSUE TITLE
Include DML (ie table data) in the Diff process

### ISSUE THREAD

**Issue by pbryant-phew** [pgmodeler/pgmodeler#1289]
**Feature description**
The `Edit data` feature allows us to include sample/test/bootstrap data within a table object definition, which is great.  However this data is not included in the Diff process, and hence isn't written to, or updated in, the DB as part of Diff process.  The table data *is* included in the Export process, but this is a heavier process with different options and controllability compared to Diff.

**Additional info**
A support conversation with @rkhaotix confirmed there is no known reason why this could not be possible - it was just a matter of getting it on the list.

**Comment by rkhaotix** [comment]
Thanks @xagtech !
I'll think on the best way to implementate this.
