### ISSUE TITLE
Draging an area on the modeler, auto selecting all objects, including tables,views,textboxes,etc,  for moving. 

### ISSUE THREAD

**Issue by RuiBaiXYZ** [pgmodeler/pgmodeler#1291]
**Feature description**
Draging an area on the modeler, auto selecting all objects, including tables,views,textboxes,etc,  for moving. 
Or moving a schema, also moving textboxes inside schema rectangles.

**Sample image**
N/A

**Additional info**
N/A

**Comment by rkhaotix** [comment]
I couldn't reproduce the bug. Could you provide more details?

**Comment by RuiBaiXYZ** [comment]
Sorry, this is not a bug, just a demand. 
Each table I have a near-by textbox to describe the business logic of the table, now the number of the table is upto 130+.
With the business logic changing, the modeler should be changed as the same.
When moving numerous tables , I have to click the destination tables and textboxes one-by-one, and then can drag to move.
Is possible to add a function that dragging the mouse on the modeler to select an area, all objects (including tables, textboxes, etc) in the area can be selected to drag to move.

**Comment by rkhaotix** [comment]
Are you talking about this?
https://pgmodeler.io/support/docs/77-select-several-objects-at-once

**Comment by RuiBaiXYZ** [comment]
Great!
Thank you @rkhaotix
