### ISSUE TITLE
Adding a view make the project impossible to save

### ISSUE THREAD

**Issue by arno974** [pgmodeler/pgmodeler#1292]
**Bug description**
After adding a view object (tried with just the name and the schema), if I want to save my project pgModeler raise this error "Unable to write the file /path_to/project.dbm due to one or more errors in the definition generation process!". After that the dbm file weitgh is 0Ko. If I delete the view I can validate and save my project as usual.

**How to reproduce**
Add a view and try to save your project

**Info about your desktop**
    OS: WUbuntu 18.04.2 LTS
    pgModeler version: 0.9.2-beta

**Comment by rkhaotix** [comment]
Confirmed. There's a bug that isn't validating the view prior adding it to the model. Thanks for reporting.
