### ISSUE TITLE
Add support to text search configuration, dictionary

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#1293]
**Feature description**
Add support for text search configurations/dictionaries on pgModeler

https://www.postgresql.org/docs/11/textsearch.html
https://www.postgresql.org/docs/11/sql-createtsconfig.html
https://www.postgresql.org/docs/11/sql-createtsdictionary.html

**Comment by Maxzor** [comment]
That is a super feature,
I would be glad to offer some help here.
