### ISSUE TITLE
foreigndatawrapper.sch not accessible

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1296]
**Bug description**
When trying to produce a diff, the following error is shown:

> Could not access the file or directory C:/Program Files (x86)/pgmodeler/schemas/catalog/foreigndatawrapper.sch! Make sure that it exists or if the user has access permissions on it!

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/60170577-ff2fe500-9808-11e9-8655-88e613c8d746.png)

**Info about your desktop**
 - OS: Windows 
 - Version: 10
 - Window manager:
 - pgModeler version:0.9.2-beta
 - Qt version:

I actually have that file at `C:\Program Files\pgmodeler\schemas\catalog\foreigndatawrapper.sch`. Which is also the application directory of pgModeler. No idea why it's looking in the `(x86)` path.

**Comment by rkhaotix** [comment]
Hi @oliversalzburg 

I suspect that you have one of the pgModeler's environment variables set. Older versions of the installer had the need to set them so the executable could work properly. Check if you have one or more vars named ```PGMODELER_*``, remove them and restart the application.

**Comment by oliversalzburg** [comment]
Right on!
![image](https://user-images.githubusercontent.com/1658949/60178245-50e16b00-981b-11e9-9440-c7b2c7b5f3ec.png)

Now everything is working as expected. Thanks for the quick solution!
