### ISSUE TITLE
Close button is not effective in Diff Preview

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1297]
**Feature description**
When you generate a diff against a local server, you are able to preview the diff before applying it. When you chose to do so, you get send to the **Diff Preview** tab in the **Diff tool** dialog.

I frequently just copy bits from here to build my own migrations in dedicated files. The statements shown here are very valuable for that process.

When I'm done, I just want to exit out of the process, but the **Close** button does nothing. You have to switch back to the **Output** tab, click **Cancel** here, then close the dialog.

I think it would be nice if that extra step could be eliminated.

**Sample image**
![image](https://user-images.githubusercontent.com/1658949/60178511-feed1500-981b-11e9-8208-cc896f096e29.png)

**Comment by rkhaotix** [comment]
Thanks, I'll add that! :)
