### ISSUE TITLE
Tooltip is too large

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1300]
**Bug description**
Hovering with the mouse over the buttons in the **Table properties** dialog, shows very large tooltips.

**How to reproduce**
Open the dialog and place the mouse over the **Add item** button.

**Expected behavior**
![image](https://user-images.githubusercontent.com/1658949/60331702-8ca04000-9995-11e9-8a31-2ba447d72ffb.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/60331688-84480500-9995-11e9-8806-14c94aaab0d8.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager:
 - pgModeler version: 0.9.2-beta
 - Qt version:

**Additional info**
This behavior is dependent on which display the dialog is on. On my primary (left) display, I get the large tooltip. On my secondary (right) display, I get the small one.

**Comment by Maxzor** [comment]
Hello, I have the same problem on windows.
It does not look deterministic, but this obese tooltip problem seems present for me on ALL tooltips.

**Comment by rkhaotix** [comment]
I'm scratching my head why this is happening. I suspect that it must be some bug on Qt. Because untill 5.11 the tooltips were fine. After switching to 5.12 this appeared, and happens only on Windows. 🤔

**Comment by Maxzor** [comment]
I thought that too and searched a bit on the web and found nothing :<

**Comment by rkhaotix** [comment]
I'll do some investigations on pgModeler's code... Maybe I can workaround this.

**Comment by oliversalzburg** [comment]
![LnnRErMZEg](https://user-images.githubusercontent.com/1658949/60339373-e1998180-99a8-11e9-9b57-90dfd928ec5a.gif)

I noticed there is a slide-down animation when a tooltip first appears. Maybe that's where the issue is coming from.

**Comment by Maxzor** [comment]
Spot on, and when you enter the hover zone in a strange way, but which... :)

**Comment by ams-tschoening** [comment]
Happens for me as well with the release of 0.9.2:

![pgModeler too large tooltips](https://user-images.githubusercontent.com/6223655/71544275-704d8200-297d-11ea-8973-6d25f081747f.png)

**Comment by rkhaotix** [comment]
Guys I finally could figure out what was causing this strange behavior. The problem is the attribute "opacity" on Tooltip's stylesheet that seems to make Qt not handle it correctly (maybe a bug on the framework?). The solution is open the file ```ui-style.conf``` find the entry ```QToolTip {``` and remove the ```opacity``` attribute. This should solve the bug.
