### ISSUE TITLE
Model export of table column generates database column with wrong precision

### ISSUE THREAD

**Issue by dbtech** [pgmodeler/pgmodeler#1302]
Export of a table column with decimal(15,2) generates a database column with decimal(152). In the specific case the table has 3 columns with the same type definition but the error occurs only for the last database column.

**Comment by rbrdevs** [comment]
Same problem here with precision values of decimal or numeric field types.
When "Export" schema to db server connection, field of type numeric(10,2) is exported as numeric(102,0)
But if you open SQL source code visualization (Alt+S) everything seems correct.

Using pgModeler 0.9.2-beta1 and PostgreSQL 11.2

**Comment by rkhaotix** [comment]
@rbrdevs this issue isn't related to the original one but I will investigate as well.

**Comment by rkhaotix** [comment]
@rbrdevs can you elaborate an small sample model where the problem occur?

**Comment by rbrdevs** [comment]
> @rbrdevs can you elaborate an small sample model where the problem occur?

Sorry, didn't see your reply.
Thanks for fixing it!
Regards
