### ISSUE TITLE
save object tree collapse state

### ISSUE THREAD

**Issue by GitStorageOne** [pgmodeler/pgmodeler#1303]
**Feature description**
Object tree in `Manage` tab should not reset collapse state of each group  
when we press `Update the object tree` -> `Quick refresh` or `Full refresh` buttons.

![изображение](https://user-images.githubusercontent.com/3978064/61123687-ab322b00-a4ad-11e9-80aa-6b0ce843662d.png)

**Comment by GitStorageOne** [comment]
2 Years behind.  
This feature can improve user experience, especially for developers.  
For example, when debugging app that change DB structure.  
Each refresh collapse entire tree and lead to requirement to open many objects over and over.
Please consider including this feature in the next version.

**Comment by rkhaotix** [comment]
Sure, let's see what I can do to minimize this issue.

**Comment by rkhaotix** [comment]
@GitStorageOne it's done. I'm just trying to figure out how to restore the scrollbar position after restoring the tree's state. But the restoration itself, expanding the items as they were after refreshing the widget us working. :)

**Comment by GitStorageOne** [comment]
Can't suggest exact solution, i'm not C++ developer.  
Here is what i found:  
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getscrollinfo 
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setscrollinfo

**Comment by rkhaotix** [comment]
I have some ideas in mind, should test them later today. Anyway, thanks for the links.
