### ISSUE TITLE
Provide subdiagrams for complex models

### ISSUE THREAD

**Issue by leftbit** [pgmodeler/pgmodeler#1305]
**Feature description**
Trying to reverse engineer a database with several thousand objects (tables, views, procedures). 

Having everything in one large diagram is not practical. I'd like to have small subdiagrams to effectively model the functional clusters (usually 10-20 objects per functionality). Some objects need to be contained in several diagrams.

This would give me a tool to 
a) work more effectively
b) clearly communicate the design of a functional group of objects to the user base

**Comment by Maxzor** [comment]
that's pretty much what multidimensional layers do, you can give a try at this :
https://github.com/pgmodeler/pgmodeler/commit/d567e7177c04a59cb01e1dad4c230d46936b35df

**Comment by rkhaotix** [comment]
You can workaround it by using 2 forms:

1) The layers feature (as @Maxzor said) but officially, pgModeler supports only single layers. Multidimensional layers will be merged to the official codebase in the future.

2) You can import a small set of your database and save in separated file. But this option cases the creation of detached diagrams. For instance, let's say you have a database with 20 schemas in which you have 100 tables. You can import the database schema by schema saving them on different files. The only problem (actually a feature lacking) the models generated doesn't know about their "sibling", so if you modify a table on a model the others will not be aware of that change. This is one feature I may be adding on the future.
