### ISSUE TITLE
Edit Data, Load from CSV, Text Delimiter Fails

### ISSUE THREAD

**Issue by pbryant-xag** [pgmodeler/pgmodeler#1308]
Any time I have Text Delimiter enabled (any type of delimiter that I have tried), only the first line gets imported and it behaves like it doesn’t escape what is inside the delimiters, or understand line feed characters.  I don’t have a perfect demonstration of the problem.  The table I am working with is 17 columns and ~720 rows. However I am able to demonstrate part of the problem as follows:

Create a table object:
{col-1, varchar}, {col-2, varchar}

Then try to import a CSV that looks like this, selecting Text Delimiter="
col-1,col-2
"a,",b
"c",d

Note that there is a comma in col-1, record-1 that we need to escape.

What happens is that the delimiter is correctly removed from the data, but it doesn’t actually escape/ignore the first comma, so you end up with three columns in the first record.

Again, this isn't the only or even main problem I've seen.  In the case of my actual table, I also only get the first row imported (as tho it thinks the rest of the file is part of the first row, which suggests an issue with line feed characters as well perhaps?).

@rkhaotix Has confirmed separately that this is a known issue, and asked that it be recorded here.

**Comment by rkhaotix** [comment]
@xagtech looking into this issue I could solve it by manually escaping the text delimiter and columns separators. For example:

Say my CSV file is:
`"col1";"co2";"col3" `
`"data \"\" teste\;";"\"\" \; teste1 \; ";"data teste 3"`

Now pgModeler understands it as:
`"col1";"co2";"col3" `
`"data "" teste;";""" ; teste1 ; ";"data teste 3"`

But, we still have two problems here:
1) Line feed character still can't be correctly parsed if they appear in the middle of columns.
2) Despite the solution above is working perfectly the user still need to escape the special characters manually so pgModeler can parse the file correctly. This can be a pain depending on the size of the file :(
