### ISSUE TITLE
Primary key from relationship's attribute

### ISSUE THREAD

**Issue by mariec7** [pgmodeler/pgmodeler#1309]
Hello. I found a problem with saving primary key checked in window for relationship. When I check  "log_time" (attribute) as primary key ("id_maintenace" is primary key from related table), it is correct only for current relation. After saving and reopen, primary key is not checked.
Version: 0.9.1 0180513 Qt 5.9.3 is older. Maybe it was solved in newer version, but I don't know.
Thank you.

![image](https://user-images.githubusercontent.com/35764895/63849449-68131500-c992-11e9-969d-5e507cc5cfa5.png)

**Comment by ivibe** [comment]
The issue still persists in 0.9.3 version

**Comment by rkhaotix** [comment]
@ivibe do you have a small test case to confirm the problem?

**Comment by ivibe** [comment]
Hope the next schema will be ok for a test case

```xml

<?xml version="1.0" encoding="UTF-8"?>
<!--
CAUTION: Do not modify this file unless you know what you are doing.
         Unexpected results may occur if the code is changed deliberately.
-->
<dbmodel pgmodeler-ver="0.9.3" use-changelog="false" last-position="0,0" last-zoom="1" max-obj-count="4"
	 default-schema="public" default-owner="postgres">
<database name="new_database" is-template="false" allow-conns="true">
</database>

<schema name="public" layer="0" fill-color="#e1e1e1" sql-disabled="true">
</schema>

<table name="country" layer="0" collapse-mode="2" max-obj-count="2" z-value="0">
	<schema name="public"/>
	<role name="postgres"/>
	<position x="217" y="184"/>
	<column name="id" not-null="true">
		<type name="smallint" length="0"/>
	</column>
	<column name="name">
		<type name="varchar" length="0"/>
	</column>
	<constraint name="country_pk" type="pk-constr" table="public.country">
		<columns names="id" ref-type="src-columns"/>
	</constraint>
</table>

<table name="city" layer="0" collapse-mode="2" max-obj-count="3" z-value="0">
	<schema name="public"/>
	<role name="postgres"/>
	<position x="223" y="506"/>
	<column name="name">
		<type name="smallint" length="0"/>
	</column>

	<customidxs object-type="column">
		<object name="id" index="1"/>
		<object name="id_country" index="0"/>
	</customidxs>

	<customidxs object-type="constraint">
		<object name="city_pk" index="0"/>
		<object name="country_fk" index="1"/>
	</customidxs>
</table>

<relationship name="country_has_many_city" type="rel1n" layer="0"
	 src-col-pattern="{sc}_{st}"
	 pk-pattern="{dt}_pk" uq-pattern="{dt}_uq"
	 src-fk-pattern="{st}_fk"
	 custom-color="#2cca01"
	 src-table="public.country"
	 dst-table="public.city"
	 src-required="false" dst-required="false">
	<label ref-type="name-label">
		<position x="0" y="0"/>
	</label>
	<column name="id" not-null="true">
		<type name="smallint" length="0"/>
	</column>
	<special-pk-cols indexes="0,"/>
</relationship>

</dbmodel>
```

So in order to have a composite primary key the attribute 'id' is created in Attributes tab of Relationship properties. Then in Primary Key tab both fields 'id' and 'id_country' are selected.

After saving and reopening PgModeler the field 'id' is no more a part of primary key.

**Comment by rkhaotix** [comment]
@ivibe Thanks! The sample model helped me to confirm the bug. The problem happens when using an attribute of the relationship and a generated column as PK. I'll investigate what's wrong and provide the proper fix. :)

**Comment by ivibe** [comment]
Thank you for your work!

**Comment by rkhaotix** [comment]
Done! Just a small comparison problem... It's fixed now.

**Comment by ivibe** [comment]
Is there gonna be a minor release or this fix will be available only with next version 0.9.4?

**Comment by rkhaotix** [comment]
@ivibe I can release a snapshot build in the next days. :)

**Comment by ivibe** [comment]
@rkhaotix that would be cool
