### ISSUE TITLE
Default Diff settings seem to DROP policies, then ALTER then, causing exception

### ISSUE THREAD

**Issue by pbryant-xag** [pgmodeler/pgmodeler#1314]
The default Diff settings, including 'Force Recreation of Objects'=TRUE, seem to DROP policies and then try to issue ALTER statements on those policies.  The DROP statements are not visible in the Diff Preview commands, but a query to the DB confirms they have indeed been dropped some time before attempting to 'Apply Diff'.  Therefore the ALTER statements fail during 'Apply Diff'.  I know it seems like I should turn off 'Force Recreation of Objects', but that causes other problems and I have never otherwise needed or wanted to change that setting.

![image](https://user-images.githubusercontent.com/30482025/64103688-adf12400-cd6a-11e9-96a4-369517636eac.png)

![image](https://user-images.githubusercontent.com/30482025/64103669-a5005280-cd6a-11e9-848f-1015940c6e26.png)

**Comment by rkhaotix** [comment]
Couldn't reproduce that problem. Can you provide more details?

**Comment by rkhaotix** [comment]
After the fix I've made in the last commit the procedures you've described in the email pgModeler imported correctly the database and made the diff without issues.
