### ISSUE TITLE
Can I create database object model using sql ?

### ISSUE THREAD

**Issue by hong-duc** [pgmodeler/pgmodeler#1315]
When design model, I want to create table quick with all column using sql, then custom it using GUI.
It just that click and click is tiresome. Is there a way to do it ?

Thank you

**Comment by rkhaotix** [comment]
No. It's not possible.

**Comment by hong-duc** [comment]
If I make a feature request, is it possible to implement ?

**Comment by rkhaotix** [comment]
It depends on the complexity as well my available time.

**Comment by hong-duc** [comment]
I have no more question, I will close it now, thank you :smile:

**Comment by Maxzor** [comment]
@hong-duc If you look at [xml2object plugin](https://github.com/pgmodeler/plugins/tree/master/xml2object), you can get the idea and work-out a sql2object plugin :)
