### ISSUE TITLE
Allow manual object creation sequencing in Swap IDs dialog

### ISSUE THREAD

**Issue by pbryant-xag** [pgmodeler/pgmodeler#1316]
As far as I can tell, whereas it is possible to swap two objects' IDs in the 'Change objects creation order' (aka Swap IDs) dialog, it is *only* possible to swap two IDs.  Ie it is not possible to place an object say from the bottom of the list somewhere higher in the list, without also being forced to move an object from higher in the list to that location lower in the list (ie you can only 'swap').

The problematic use-case is when you decide 'late' in a project that you want to add eg some sequence definitions.  Those sequences get created at the bottom of the object creation order list (apparently because they are new, and I am not commenting here on whether you might be able to leverage some existing smarter logic for that).  They of course have to be created before they can be used by the relevant table.  Assume this is an existing table (eg we are replacing a `bigserial` columm with a bigint that uses a manually-created sequence object).  So I need to move the sequence creation to be above that table's creation.  I don't think this is currently possible without moving the object which currently sits above that table in the list, to be at the bottom of the list (not desirable for other reasons of course <-- it was already in the right place).

(The work-around is to open the dbm file in a text editor and move the relevant XML element manually.  This works fine in Sublime for example, as long as you don't eg create invalid XML by accident)

**Comment by OndrejValenta** [comment]
To add to this, what if I've decided to add uuid-ossp extension after I created multiple tables and relations. I cannot find a way to move this extension upward because swapping really works only as swapping of the same objects and not order rearrangement tool with simple Ctrl-Up and Ctrl-Down key binds.

There must be some other way to change the order of the elements creation that I'm missing, right? Don't tell me I have to start all over and think of everything before I start modeling.

**Comment by rkhaotix** [comment]
You can double click ```hubDocumentsPermissions``` and then double click ```uuid-ossp``` . Once both objects are selected, swap their IDs. You will notice that the table will be move to the end of the listing. Now, close the dialog and validate your model. The validator will probably point out some references breaking, apply the fixes and validate again. Repeat the process until no errors are returned by the validator.

**Comment by rkhaotix** [comment]
I'll will on this soon. I have some ideas on how to improve the objects swapping.

**Comment by OndrejValenta** [comment]
I'll try to fiddle with the order, I'm pretty close already :-) 

Btw. one more and very IMPORTANT thing. Could the swap id window remember it's position and size everytime it's closed. Now it's always opened in a Microsoft manner :-) Small and condensed, and I have to resize it every time. Thank you.

**Comment by OndrejValenta** [comment]
![2019-09-21_18-26-14](https://user-images.githubusercontent.com/6738956/65376195-6db40000-dc9d-11e9-80a2-b34ca13361b0.gif)

Because of my high screen resolution the mouse cursor is tilted.

**Comment by rkhaotix** [comment]
@OndrejValenta about the postion and size restoration is already available for almost all dialogs. Maybe it is not working properly on your case. Check if you have accidentally disabled it on general settings.

**Comment by rkhaotix** [comment]
@OndrejValenta I found the problem... You're right. I see that you are activating the dialog from the popup menu and seems that the position/size restoration is not begin applied. :)

For now, use the "Swap ids" button on the validator widget to see size restoration in action.
