### ISSUE TITLE
SHARING VIOLATION on Windows using external source code editor.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1319]
**Bug description**
The bug refers to the ability of pgModeler to use external source code editors, like described in [the docs](https://pgmodeler.io/support/docs/25-source-code-input-fields). I've configured the editor [TextPad](https://www.textpad.com/products/textpad/index.html) and it opens with the expected content just fine. The problem is when I save the changes made within TextPad, the following error message is shown:

![Clipboard01](https://user-images.githubusercontent.com/6223655/65057569-18ad7c80-d973-11e9-980b-b63246066045.png)

That essentially says that a sharing violation happened during writing the mentioned file. That sharing violation can be documented with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) as well:

    16:29:49,4029321	TextPad.exe	2520	CreateFile	C:\Users\tschoening\AppData\Local\pgmodeler\tmp\source_Tn1160.sql	SHARING VIOLATION	Desired Access: Generic Read/Write, Disposition: OverwriteIf, Options: Sequential Access, Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, AllocationSize: 0

The problem is that pgModeler holds the file still open with sharing modes read and write, while TextPad wants to open the file with sharing mode read only, which conflicts in the end. That pgModeler holds a handle can be seen in Process Monitor again as well:

	16:28:42,6191104	pgmodeler.exe	1160	CreateFile	C:\[...]\source_Tn1160.sql	SUCCESS	Desired Access: Generic Read/Write, Disposition: Create, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Created
	16:28:42,6195209	pgmodeler.exe	1160	CreateFile	C:\[...]\source_Tn1160.sql	SUCCESS	Desired Access: Generic Write, Read Attributes, Disposition: OpenIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: 0, OpenResult: Opened
	16:28:42,6196099	pgmodeler.exe	1160	SetEndOfFileInformationFile	C:\[...]\source_Tn1160.sql	SUCCESS	EndOfFile: 0
	16:28:42,6196974	pgmodeler.exe	1160	SetAllocationInformationFile	C:\[...]\source_Tn1160.sql	SUCCESS	AllocationSize: 0
	16:28:42,6197998	pgmodeler.exe	1160	WriteFile	C:\[...]\source_Tn1160.sql	SUCCESS	Offset: 0, Length: 1.093, Priority: Normal
	16:28:42,6199709	pgmodeler.exe	1160	CloseFile	C:\[...]\source_Tn1160.sql	SUCCESS	

There are two calls to `CreateFile`, but only one `CloseFile`, so one handle is still open and responsible for the sharing violation. I had a look at the source of pgModeler and found that it thinks to close the file properly:

	tmp_src_file.setFileTemplate(GlobalAttributes::TemporaryDir + GlobalAttributes::DirSeparator + QString("source_XXXXXX") + QString(".sql"));
	tmp_src_file.open();
	tmp_src_file.close();
	input.setFileName(tmp_src_file.fileName());

	if(!input.open(QFile::WriteOnly | QFile::Truncate))
		throw Exception(Exception::getErrorMessage(ErrorCode::FileDirectoryNotAccessed)
										.arg(tmp_src_file.fileName()),
										ErrorCode::FileDirectoryNotAccessed ,__PRETTY_FUNCTION__,__FILE__,__LINE__);

	buffer.append(this->toPlainText());
	input.write(buffer);
	input.close();

https://github.com/pgmodeler/pgmodeler/blob/develop/libpgmodeler_ui/src/numberedtexteditor.cpp#L363

But sadly that is not the case, `QTemporaryFile` doesn't close files on calling `close`:

	bool QTemporaryFileEngine::close()
	{
		// Don't close the file, just seek to the front.
		seek(0);
		setError(QFile::UnspecifiedError, QString());
		return true;
	}

https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qtemporaryfile.cpp?h=dev#n436

    // Since the QTemporaryFileEngine::close() does not really close the file,
    // we must explicitly call QFSFileEngine::close() before we remove it.
    d->unmapAll();
    QFSFileEngine::close();

https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/io/qtemporaryfile.cpp?h=dev#n395

Others ran into similar problems and changed their implementation to only use `QFile` itself:

    const QString tmpBaseName("XXXXXX-test.cpp");
    QString templatePath = QDir::temp().absoluteFilePath(tmpBaseName);
    QFile tmpQSourceFile(templatePath);

https://fami.codefreak.ru/gitlab/peter/qt4/commit/ea181f7fa681815f27b633ba0b3b0c2754c1a753

**How to reproduce**
Configure TextPad as external source code editor, click "Edit" button in the source code-views and save changes in the newly opened window of TextPad.

**Expected behavior**
pgModeler should properly close the generated temporary files before starting external editors to avoid any chance of sharing violations.

**Screenshots**
![Clipboard01](https://user-images.githubusercontent.com/6223655/65058592-cec59600-d974-11e9-876d-e18d176e8a28.png)

![Clipboard02](https://user-images.githubusercontent.com/6223655/65058670-f4529f80-d974-11e9-9012-5c43fa2dcbb2.png)

**Info about your desktop**
 - OS: Windows 10 1903
 - Version: Build 18362.356
 - Window manager:
 - pgModeler version: 0.9.1, but happens in master as well.
 - Qt version: QT5 bundled with pgModeler.

**Stacktrace / Debug info**
It doesn't crash, things simply don't work as expected/intended.

**Comment by rkhaotix** [comment]
Hmm... Thanks for that. I'll think on an alternative solution.

Did you test using other text editors?

**Comment by ams-tschoening** [comment]
I suggest simply doing what the linked GitLab-code does. No, I didn't test with other editors and depending on the sharing mode those text editors use things might work. But one can't really know beforehand and without changing things on your side you would actually end up discussing why some text editors are compatible with that feature while others aren't.

TextPad for e.g. uses sharing mode READ only because it wants to write the file in that moment and during that operation it actually makes a lot of sense to not allow others to write the file at the same time as well. Of course you don't write the file actually, but TextPad or other editors can't know that. They can only force others to stay out using sharing mode READ.

Anyway, the only problem is that your attempt to close the file is not properly honoured by QT and looking at the GitLab-changes it doesn't seem too difficult to change that.
