### ISSUE TITLE
Create a reusable "file selector" widget

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#1321]
**Feature description**
There's a lot of file selector like controls used to select output/input files for some processes. These controls causes the repetition of code because they basically do the same thing (with few differences): open a file dialog, allow the user to select a file, fill an input box with the selected file path. 

This kind of operation can be isolated to an dedicated widget and all instances of that controls can be replaced. This new widget should allow the above operations and other like set read only mode (the user can't change manually the input box), send signals for the actions take by the user (changed the input text, selected the file, etc).

**Sample image**
![file_selector](https://user-images.githubusercontent.com/2205476/65264918-0ef85600-dae6-11e9-977f-b351b6ffda2e.png)

**Comment by Maxzor** [comment]
Are Qt custom widgets desirable or do you aim at a lower-level modularization?
https://doc.qt.io/qt-5/designer-creating-custom-widgets.html

**Comment by rkhaotix** [comment]
In that case, I prefer low-level modularization because I'm a bit worried about the deployment of a custom widget made for designer. Being a pgModeler control the deployment won't change.

**Comment by Maxzor** [comment]
Some nitty-gritty :

- QFileDialog constructed in the FileSelectorWidget class constructor and waiting for exec, or class attributes waiting to be passed as arguments ?
- Some factorization that is already done, i.e. in modelfixform, will be lost factorizing this way.
- Red text like in QLineEdit as in QtCreator if file does not exist, with 3s perpetual-timer polling possible on-disk changes?
- Global QSettings across all(/ ?)per FileSelectors, or keep the current default way?

**Comment by Maxzor** [comment]
Will try with placeholder label, class attributes, red+timer, global qsettings.

**Comment by Maxzor** [comment]
Btw, I don't see any case where line edit should be read only.

**Comment by Maxzor** [comment]
Depending on your plans for a big UI rework, you might want to either abandon the idea of HintTextWidget in favor of regular tooltips, or make them into custom QtCreator widgets. Relatively big upside of a high-level custom widget is that they do not break tab order (which is a poor feature in Qt) as the empty_widget_hint + hinttextwidget do.

**Comment by rkhaotix** [comment]
I don't see any problem with HintTextWidget. Using regular tooltips instead can be a bit hard because tooltips don't accept formatted texts (unless some derivations are done). So, I still prefer to use it in 1.0+

About the tab order... The problem is not Qt's or even HintTextWidget.. I need to reorder the tab sequencing of all widgets again because they have changed a lot over the years and haven't had the tab order reviewed.

**Comment by Maxzor** [comment]
> I don't see any problem with HintTextWidget. Using regular tooltips instead can be a bit hard because tooltips don't accept formatted texts (unless some derivations are done). So, I still prefer to use it in 1.0+

I get this point
 
> About the tab order... The problem is not Qt's or even HintTextWidget.. I need to reorder the tab sequencing of all widgets again because they have changed a lot over the years and haven't had the tab order reviewed.

A pesky thing : tab order is easy to do from qtcreator and its dedicated feature. It is harder once uic is passed, since you have to programmatically remake those with QWidget::setTabOrder() ...

**Comment by Maxzor** [comment]
WIP, you can check don't feel like PR yet, not enough tested, but the implementation got quite ready IMO.
https://github.com/Maxzor/pgmodeler/commit/a5d90b5dcd7ef01c367b05397109b5fc2cd4409a

**Comment by Maxzor** [comment]
Guess this can be mergeable and ironed out in place :)

**Comment by Maxzor** [comment]
> I don't see any problem with HintTextWidget. Using regular tooltips instead can be a bit hard because tooltips don't accept formatted texts (unless some derivations are done). So, I still prefer to use it in 1.0+

Just discovered you can do html tooltips now.
I vote to remove hinttextwidget.
![html_tootip](https://user-images.githubusercontent.com/16599683/72663277-ed09d400-39f0-11ea-8d72-b763693e000f.png)

**Comment by rkhaotix** [comment]
I will try it.
