### ISSUE TITLE
Failure on database/schema naviagation (database explorer)

### ISSUE THREAD

**Issue by wagner-serrano** [pgmodeler/pgmodeler#1322]
Navigation on database/schema (database explorer) was interrupted with this error message (from PostgreSQL) and connection with PostgreSQL was aborted.
-------------------------------------
# Server side:
$ psql -V 
   psql (PostgreSQL) 11.5 (Debian 11.5-1.pgdg100+1)
$ uname -a
   Linux (...) 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

 
# Client side:
$ uname -a
  Darwin (...) 17.7.0 Darwin Kernel Version 17.7.0: Sun Jun  2 20:31:42 PDT 2019; root:xnu-4570.71.46~1/RELEASE_X86_64 x86_64

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G8030

$ xcodebuild -version
Xcode 9.4
Build version 9F1027a

$ qmake --version
QMake version 3.1
Using Qt version 5.13.1 in /usr/local/Cellar/qt/5.13.1/lib

REMARK: Build v0.9.1 with qt 5.1.13.1 (successfully)

# My Diagnosis: wrong query on PostgreSQL dictionary, incompatible with PostgreSQL version 11.5 

-------------------------------------
# ERROR MESSAGE:
[3] src/connection.cpp (415)
  void Connection::executeDMLCommand(const QString &, ResultSet &)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'
       ** 42703

[2] src/catalog.cpp (416)
  vector<attribs_map> Catalog::getObjectsNames(vector<ObjectType>, const QString &, const QString &, attribs_map, bool)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[1] src/databaseimporthelper.cpp (149)
  vector<attribs_map> DatabaseImportHelper::getObjects(vector<ObjectType>, const QString &, const QString &, attribs_map)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

[0] src/databaseimportform.cpp (892)
  static vector<QTreeWidgetItem *> DatabaseImportForm::updateObjectsTree(DatabaseImportHelper &, QTreeWidget *, vector<ObjectType>, bool, bool, QTreeWidgetItem *, const QString &, const QString &, unsigned int)
    [ERR_CMD_SQL_NOT_EXECUTED] Could not execute the SQL command.
 Message returned: `ERROR:  column pr.proisagg does not exist
LINE 1: ...namespace AS ns ON pr.pronamespace = ns.oid WHERE pr.proisag...
                                                             ^
HINT:  Perhaps you meant to reference the column "pr.prolang".
'

**Comment by rkhaotix** [comment]
Already fixed on 0.9.2-alpha1
