### ISSUE TITLE
When a sequence is created during the creation of a table, the model crash during the reopen

### ISSUE THREAD

**Issue by equinton** [pgmodeler/pgmodeler#1323]
**Bug description**
I create a new table, with a column id associated with a sequence. The sequence is created during the creation of the column.
When the model is reopen, an error is generated: the sequence is recorder after the table creation. I must modify manually the file to reorder the xml file.

**How to reproduce**
Systematic

**Expected behavior**

**Screenshots**

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version: 0.9.2-beta1
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```
The object `station_type_id' (Column) is referencing the object `tracking.station_type_station_type_id_seq' (Sequence) which was not found in the model!

XML file: 
<table name="station_type" layer="2" collapse-mode="2" max-obj-count="2">
	<schema name="tracking"/>
	<role name="filo"/>
	<position x="40" y="460"/>
	<column name="station_type_id" not-null="true" sequence="tracking.station_type_station_type_id_seq">
		<type name="integer" length="0"/>
	</column>
	<column name="station_type_name" not-null="true">
		<type name="varchar" length="0"/>
	</column>
	<constraint name="station_type_pk" type="pk-constr" table="tracking.station_type">
		<columns names="station_type_id" ref-type="src-columns"/>
	</constraint>
</table>

<sequence name="station_type_station_type_id_seq" cycle="false" start="1" increment="1" min-value="0" max-value="2147483647" cache="1">
	<schema name="tracking"/>
	<role name="filo"/>
</sequence>
```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Did you validate your model before save it?
https://pgmodeler.io/support/docs/67-model-validation

**Comment by equinton** [comment]
It's ok after the validation procedure. Thanks.
