### ISSUE TITLE
Set comment for column generated by relationship

### ISSUE THREAD

**Issue by molexx** [pgmodeler/pgmodeler#1325]
**Feature description**
When a column is created by a relationship its properties are protected so you can't edit it. This includes its comment, so there is no way to set the comment.

Perhaps some properties could be non-protected?
Or perhaps column comment could be a new relationship property?

**Comment by rkhaotix** [comment]
This is similar to #1388
The commit https://github.com/pgmodeler/pgmodeler/commit/1b8be41aeef9e58c2e60b54c0c863e93f1513b82 adds a workaround that allows the detachment of objects generated by relationships making possible the changing on any attribute of these objects.

**Comment by molexx** [comment]
Thanks! :-)
