### ISSUE TITLE
Make textual outputs of validation copyable.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1327]
**Feature description**
During #1326 I wanted to copy the output of the validation and found it to be pretty difficult. I needed to copy each line on it's own and some lines even needed to get right clicked and get all text marked using the context menu before being able to copy them and stuff. As this log provides useful output during debugging errors, I guess it's pretty likely that someone wants to copy it, so there should be some text-only representation of the contents as well.

Thanks!

**Sample image**
![Clipboard01](https://user-images.githubusercontent.com/6223655/65708097-1b545400-e08e-11e9-9230-66279c5e81ac.png)

**Comment by Maxzor** [comment]
https://github.com/pgmodeler/pgmodeler/issues/1277

**Comment by rkhaotix** [comment]
Okay guys, just to give some feedback for you... I've made a first implementation of this feature which basically allowed one to copy the entire validation output as text as well open it on a dedicated widget so text searches could be performed, as well the browsed text could be saved to an external file. 

![model_validation_output](https://user-images.githubusercontent.com/2205476/79259758-9e3ecf80-7e63-11ea-83bc-e1ca74aab7a5.png)

![model_validation_output1](https://user-images.githubusercontent.com/2205476/79259771-a3038380-7e63-11ea-8f5f-aa2cd88c084c.png)

But I thought once more and find a bit overkill to have a "text editor" inside pgModeler just to browse the generated text output. So I decided to remove the "View as text" from the menu on "Output" button at model validation widget. If you think this can be useful I can return it... for now, only "Copy as text" is available. Once activated, it'll put the text representation of the validation to the clipboard and the user is free to paste it wherever he/she wants! 

What do you think?

**Comment by ams-tschoening** [comment]
Things look pretty good to me, thanks! We all have some sort of Text Editor available already anyway. :-) This is in line with editing SQL in an external editor as well, only if you change that to an internal one in future, your now removed view would make some sense to come back. But the most important thing is that one is able to copy the output somehow and that seems to be the case now.

**Comment by rkhaotix** [comment]
Okay then :)
I'll close this issue since the provided solution is enough!

Thanks @ams-tschoening
