### ISSUE TITLE
Materialized view Index with to_tsvector() not working

### ISSUE THREAD

**Issue by BrendanMartin** [pgmodeler/pgmodeler#1328]
Trying to create a materialized view with an index using gin like the following:

```
--Create the materialized view
CREATE materialized view <schema_name>.mv_prompts AS
SELECT id, ngram, freq
FROM <schema_name>.prompts
WHERE add_conditions_here
ORDER BY freq DESC;

--Create a search index using GIN
CREATE INDEX prompts_ngram_idx 
ON <schema_name>.mv_prompts 
USING GIN (to_tsvector('english', ngram));
```

But when doing all this and trying to export, I receive the following error:
```
Could not execute the SQL command.
Message returned: ERROR: function to_tsvector(unknown, integer) does not exist
LINE 4: (to_tsvector(english', ngram))
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
```

Steps I used:
1. Created view
2. Created gin index inside view
2.1 Added an Expression element to the index where the expression was `to_tsvector('english', ngram)`

I'm not sure what I'm doing wrong, but the code generated looks very close, just has extra parentheses:

```
-- object: prompts_ngram_idx | type: INDEX --
-- DROP INDEX IF EXISTS public.prompts_ngram_idx CASCADE;
CREATE INDEX prompts_ngram_idx ON public.mv_prompts 
	USING gin
	(
	  (to_tsvector('english', ngram))
	);
-- ddl-end --
```

**Comment by rkhaotix** [comment]
Running manually the code generated by pgModeler returns the error? Maybe the syntax is incorrect.

Also, Does your view depend on some extension?

**Comment by BrendanMartin** [comment]
The error occurs when I'm exporting it to a local database. There are no extensions being used.

**Comment by BrendanMartin** [comment]
Never mind. It turns out the syntax was incorrect. Thank you for your reply.
