### ISSUE TITLE
Support PG version 12 without oids

### ISSUE THREAD

**Issue by shemgp** [pgmodeler/pgmodeler#1329]
**Feature description**
Please allow pgmodeler to work with PostgreSQL 12 without oids, since according to [this](https://www.postgresql.org/docs/12/release-12.html#id-1.11.6.5.4) the hidden column `oid` in tables are removed in version 12.

**Additional info**
I get this on pgmodeler 0.9.2-beta1 while importing a database from PostgreSQL 12:
![Screenshot from 2019-10-02 11-25-03](https://user-images.githubusercontent.com/1734126/66015974-57147100-e507-11e9-9d7a-afba09ef58d4.png)

Thanks for the future hard work on this.

**Comment by rkhaotix** [comment]
That changes A LOT of things. The entire reverse engineering and diff processes make use of oid fields. It'll not be an easy fix. :(

**Comment by rkhaotix** [comment]
Nevermind, I've found the problem. The query catalog for table listing is referencing an oid field which is ambigous in PG12. I'll mark this issue for fix until the final 0.9.2 :)
