### ISSUE TITLE
I/O error : failed to load external entity

### ISSUE THREAD

**Issue by BrendanMartin** [pgmodeler/pgmodeler#1330]
I'm on Windows and have pgModeler installed through the purchased pre-compiled latest version.

When trying to use `pgmodeler-cli` I get this message:

```
I/O error : failed to load external entity "<random_directory>/conf/dtd/source-code-highlight.dtd"
``` 

Were `random_directory` is whatever directory I'm currently in. 

I have `C:\Program Files\pgmodeler` in my Path but it doesn't seem to see the conf folder there.

**Comment by rkhaotix** [comment]
Could you provide the complete command line used to call the CLI?

**Comment by BrendanMartin** [comment]
All I did was call `pgmodeler-cli` without any args to see if it was in my Path correctly.

**Comment by rkhaotix** [comment]
Okay. I'll invastigate. Thanks!
