### ISSUE TITLE
Foreign Keys when exporting to SQL files

### ISSUE THREAD

**Issue by BrendanMartin** [pgmodeler/pgmodeler#1331]
I'm trying to have a Postgres server backend and SQLite on the frontend for a mobile app and would like to be able to use the same SQL export for building both databases.

The problem is that SQLite doesn't allow constraints in their alter table functions. Is there a way for pgModeler to export to a SQL file like:
```
CREATE TABLE so_items (   
    item_id INTEGER NOT NULL,   
    so_id INTEGER,   
    product_id INTEGER,   
    qty INTEGER,   
    net_price NUMERIC,   
    PRIMARY KEY (item_id, so_id),   
    FOREIGN KEY (so_id) REFERENCES so_headers (id));
);
```
Instead of doing ALTER TABLE statements at the end of the file?

**Comment by rkhaotix** [comment]
Unfortunately no.
pgModeler needs to create foreign keys the way it does in order to solve referencing problems.

**Comment by BrendanMartin** [comment]
Okay, thanks.
