### ISSUE TITLE
Just noticed a peculiar behavior with touch screen

### ISSUE THREAD

**Issue by quaxquax** [pgmodeler/pgmodeler#1332]
**Bug description**
I usually have not much use for my touchscreen, but it is a delight to work with when moving around tables in an ERM diagram. But these actions don't seem to be captured by the undo history. So after moving a table via touchsreen and then via mouse, I observe the peculiar behavior that the table I moved via screen stays put, while all the mouse actions are retraced.

**How to reproduce**
This may be specific to the Linux Gnome desktop otherwise it may be reproducible with any touchscreen.

This was on a HP Spectre with touchscreen.

**Expected behavior**
I would expect touch events to be handled by the history undo in the same manner as mouse events.

**Screenshots**
N/A

**Info about your desktop**
 - OS: Ubuntu
 - Version: 18.04
 - Window manager: Gnome
 - pgModeler version: v0.9.2-beta1
 - Qt version: 5.9.7

**Stacktrace / Debug info**
N/A
```

**Comment by Maxzor** [comment]
Dell inspiron touchscreen, gnome desktop, pgm0.9.2, qt5.12 here. Have no problem ¯\o/¯
I'd suggest moving to a more recent version of Qt.
