### ISSUE TITLE
Relationship column pattern not exporting correctly

### ISSUE THREAD

**Issue by BrendanMartin** [pgmodeler/pgmodeler#1335]
I have the pre-compiled binary installed on Windows.

I'm trying to set the pattern for the many-to-many relationships to be `tablename_id` so I have set the patterns to `{st}_{sc}` and `{dt}_{sc}`. 

![image](https://user-images.githubusercontent.com/8090350/66571259-f4415c00-eb3c-11e9-81ca-82500d12c45c.png)

When exporting to .sql the pattern is still set to the default, but when inspecting the .dbm XML it looks like it is set correctly to my new pattern.

Furthermore, I had a many-to-many relationship already set when I changed the pattern. After changing the pattern and re-creating the relationship, it's still showing as the old pattern. But every new relationship I make shows the new pattern in the .dbm.

**Comment by rkhaotix** [comment]
Hi @BrendanMartin 

> Furthermore, I had a many-to-many relationship already set when I changed the pattern. After changing the pattern and re-creating the relationship, it's still showing as the old pattern. But every new relationship I make shows the new pattern in the .dbm.

That's the main point. It seems not clear but changing global pattern only affects new relationships. Existing relationships are not changed to the new pattern. I can add an option to apply the pattern changing to all relationships.

**Comment by BrendanMartin** [comment]
Oh okay. Even when I make new relationships the new pattern doesn't export to SQL.

**Comment by BrendanMartin** [comment]
Yeah, I've tried deleting the relationship, saving, remaking a new many-to-many with a different name, but when I export it still uses the default `id_tablename` pattern instead of `tablename_id`.

**Comment by rkhaotix** [comment]
Which version you're working on? If it's 0.9.1 try to use the latest snapshot, please.

**Comment by rkhaotix** [comment]
@BrendanMartin See this small video I've made in order to demonstrate that the pattern feature is working as expected on 0.9.2-beta2 (under development): https://youtu.be/SWNlyDmFb-s

**Comment by BrendanMartin** [comment]
I'm on v0.9.2_snapshot20190921. Here's a screencap of my side: https://youtu.be/FogPQfuPi9U

**Comment by BrendanMartin** [comment]
I forgot to show the XML, but it looks like this:
```
<relationship name="user_interest" type="relnn" layer="0"
	 src-col-pattern="{sc}_{st}" dst-col-pattern="{sc}_{dt}"
	 pk-pattern="{gt}_pk" uq-pattern="{gt}_uq"
	 src-fk-pattern="{st}_fk" dst-fk-pattern="{dt}_fk"
	 pk-col-pattern="id"
	 custom-color="#83af1f"
	 src-table="public.users"
	 dst-table="public.interest"
	 src-required="false" dst-required="false"
	 single-pk-col="true"
	 table-name="user_interest"/>
```

**Comment by rkhaotix** [comment]
I think I got it... The problem seems to happen when you click "Single pk column". If you create the relationship without using that feature what happens? It behaves correctly?

**Comment by BrendanMartin** [comment]
Unfortunately, even if I don't check "Single pk column" it still happens.

**Comment by rkhaotix** [comment]
That's really odd. :(

**Comment by rkhaotix** [comment]
@BrendanMartin could you sent me a copy of your database model? Maybe the bug happens due to the arrangement of the objects in it.

**Comment by kkursor** [comment]
I don't feel any effect from these settings on 0.9.2-2 beta in Ubuntu.
As I understand, these options should automatically fill object names and reference types when I create new relationship.
But they do not.

**Comment by BrendanMartin** [comment]
Here's the flow that I went through for it to happen:
1. Start a new schema and define relationships without using relationship tool
2. Change global settings for the relationship pattern
3. Try deleting and existing relationship and recreating using the relationship tool (N) --> doesn't use global pattern settings for column names
4. Uncheck "Use global settings for these fields" when making a new relationship and change the patterns there. --> this works

**Comment by kkursor** [comment]
I tried to create new FK waiting pgModeler to generate default name and update/delete actions as specified at Settings window. But the name was empty and actions were default (NO ACTION)

**Comment by rkhaotix** [comment]
@kkursor the name pattern feature works only with relationships created from the relationship tool. If you manually create an FK (and consequently a FK relationship) the patterns will not be applied.

https://pgmodeler.io/support/docs/310-relationships

**Comment by kkursor** [comment]
Ah, I see. Ok

**Comment by BrendanMartin** [comment]
@rkhaotix I just noticed something today. It turns out that when creating a relationship if I simply just click on the settings tab and click "apply" my globals work. If I just hit apply without clicking the settings tab then my globals don't work.

**Comment by dtrehas** [comment]
+1 :(

**Comment by rkhaotix** [comment]
I still can't reproduce this... I'm scratching my head trying to figure out how to make this "bug"(?) happer. @BrendanMartin do you have any extra info that may help? I'm working on branch 0.9.3 and the patterns are working fine.
