### ISSUE TITLE
Not possible to set RLS policy to RESTRICTIVE

### ISSUE THREAD

**Issue by OFRBG** [pgmodeler/pgmodeler#1338]
**Bug description**
RLS can't set RESTRICTIVE.

**How to reproduce**
Set RLS for any table. Add a policy. Postgres policies are PERMISSIVE by default. Checking or unchecking the permissive checkbox makes no difference.

**Expected behavior**
Add a RESTRICTIVE checkbox instead.

**Info about your desktop**
 - OS: macOS
 - Version: 10.13
 - pgModeler version: v0.9.2-beta1 build 20190902
 - Qt 5.12.3

**Additional info**
https://www.postgresql.org/docs/11/sql-createpolicy.html

**Comment by rkhaotix** [comment]
Are you sure about that? See below. The first example is a restrictive policy while the second is a permissive policy. Note the PERMISSIVE/RESTICTIVE policies were introduced in PostgreSQL 10 so if you're using a version below that you'll not see these keywords in action.

![policy](https://user-images.githubusercontent.com/2205476/67200996-a00b6700-f3db-11e9-97a0-63c776f11dae.png)
