### ISSUE TITLE
Can't save a model????

### ISSUE THREAD

**Issue by ElixirMike** [pgmodeler/pgmodeler#1341]
I just purchased this tool. I started with a blank canvas and setup a few tables. I am now trying to save the model. First, it kept complaining about validation and "no connection". At this point, I just want to save the model, not execute it against a DB...how do I do that???

Then, I setup a connection to my local db, just so I can save, it validates, but now doesn't let me save the file??? It keeps complaining with this error
"unable to write the file 'c:////blah/blah//test_model.dbm" due to one or more errors in the definition generation process!"

How can I save this model?

**Comment by ElixirMike** [comment]
I just started brand new model, created 1 table/1 field and tried to save. I get this error
"unknown attribute "hide-ext-attribs" in file `C:/Program Files (x86)/pgmodeler/schemas/xml/table.sch', line 10, column 25!.

**Comment by rkhaotix** [comment]
Which version? Have you installed the demo version before purchase the full version?

**Comment by ElixirMike** [comment]
Yes, I had the demo version...then installed new package. FYI, I went back and uninstalled both demo version and full version, restarted my computer, and now it allows me to correctly save my model. Yea!

Now, however, I cannot get the "export" or "diff" feature to work. I have created a single table and just want to see it export/update my local DB. If I precreate the DB on the server, and then try to export to this db, the app throws the error "Database Test already exists!".  The export feature requires you select an existing defined connection, which has the DB specified, so how do I get export to run and run script on server???

I then figured, I'll try the "diff" feature, I choose my model as input, the empty db for the "compare to" and run this. Now I get an error:

"Error: column reference "oid" is ambigious line 1: Select rf.oid, rl.rulename as name from (SELECT r.oid, rw... ) . 

I can't see the rest of the error as it's truncated. What am I missing here? Just trying to get a basic table to sync against my local server.

**Comment by ElixirMike** [comment]
Here is the full raw error:

"[4] src/connection.cpp (415)
  void Connection::executeDMLCommand(const QString&, ResultSet&)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 1: SELECT rl.oid, rl.rulename AS name FROM ( SELECT rw.oid, rw....
               ^
'
       ** 42702

[3] src/catalog.cpp (259)
  void Catalog::executeCatalogQuery(const QString&, ObjectType, ResultSet&, bool, attribs_map)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 1: SELECT rl.oid, rl.rulename AS name FROM ( SELECT rw.oid, rw....
               ^
'
       ** catalog: rule

[2] src/catalog.cpp (355)
  attribs_map Catalog::getObjectsNames(ObjectType, const QString&, const QString&, attribs_map)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 1: SELECT rl.oid, rl.rulename AS name FROM ( SELECT rw.oid, rw....
               ^
'

[1] src/catalog.cpp (327)
  void Catalog::getObjectsOIDs(std::map<ObjectType, std::vector<unsigned int, std::allocator<unsigned int> > >&, std::map<unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > >&, attribs_map)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 1: SELECT rl.oid, rl.rulename AS name FROM ( SELECT rw.oid, rw....
               ^
'

[0] src/modeldatabasediffform.cpp (564)
  void ModelDatabaseDiffForm::importDatabase(unsigned int)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 1: SELECT rl.oid, rl.rulename AS name FROM ( SELECT rw.oid, rw...."

**Comment by rkhaotix** [comment]
About this error:

```Error: column reference "oid" is ambigious line 1: Select rf.oid, rl.rulename as name from (SELECT r.oid, rw... ) .```

Use the latest snapshot build that fixes this problem. You're running PostgreSQL 12 right? If so, use the latest snapshot. At the end of this week I'm gonna release the new version of pgModeler which fixes this issue.

About the other errors, please see the links below:
https://pgmodeler.io/support/docs/44-connections-settings
https://pgmodeler.io/support/docs/51-export-a-model
https://pgmodeler.io/support/docs/53-compare-a-model-and-a-database

**Comment by ElixirMike** [comment]
Do I need to uninstall the current version and then install latest snapshot?
Can you provide link to version to download? I'm running windows 64

**Comment by ElixirMike** [comment]
FYI, yes, I'm running PostgreSQL 12. Also I'm running version.
v0.9.2_snapshot20190921 build 20190921 qt:5.12.3

IS there a new version?

**Comment by rkhaotix** [comment]
Yes. You need to uninstall the old one to use the newer version...
You download the snapshot here: pgmodeler.io/download 
On that link use your access key. After validating the access key, in the payament details form, on the "Release" field choose the snapshot build and download it.

**Comment by ElixirMike** [comment]
I did that, but for the snapshot version, I'm already running the version
it shows in the drop down menu:
0.9.2_snapshot20190921

I can't wait until you release the official version...right now it's more
important I can create/save/load my models. But I will obviously want the
features to execute/update the model on my server db... When do you think
the new version will be release?


[image: image.png]
