### ISSUE TITLE
pgModeler 0.9.2 beta2 for Windows not available in "Programs and Features" in system control.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1349]
**Bug description**
After installing pgModeler 0.9.2 beta2 on Windows 10 1903, it doesn't seem to be registered properly for "Programs and Features" in control panel. It was with earlier versions like 0.9.1.

**How to reproduce**
Just execute the installer and look at the control panel, no new entry.

**Expected behavior**
pgModeler should be available in "Programs and Features" like in the past.

**Screenshots**
![pgModeler Systemsteuerung](https://user-images.githubusercontent.com/6223655/69526954-9ab9b300-0f6b-11ea-91d4-e6605cffd4f1.png)

![pgModeler Windows Explorer](https://user-images.githubusercontent.com/6223655/69526961-9beae000-0f6b-11ea-84ff-03662460751b.png)

![pgModeler Programs and Features](https://user-images.githubusercontent.com/6223655/69527200-19aeeb80-0f6c-11ea-8355-cdddc40dc706.png)

Don't get confused about the wrong version number in the last screenshot, I really used the installer of 0.9.1.

**Info about your desktop**
 - OS: Windows 10
 - Version: 1903
 - Window manager:
 - pgModeler version: 0.9.2 beta2
 - Qt version: Whatever is bundled with pgModeler only.

**Stacktrace / Debug info**
No crash.

**Additional info**
None.

**Comment by ams-tschoening** [comment]
This problem still exists in the released version of 0.9.2 and it's most likely that it has been introduced in the following commit:

https://github.com/pgmodeler/pgmodeler/commit/ec2b7e79e6d1297569fa820bfbf8b8bf15cffef2

While the following setting makes somewhat sense for an installer, double-clicking the installer DOES NOT call UAC-elevation automatically. Instead I need to manually choose "Execute as Administrator" in the context menu of the installer. That makes me wonder if that setting is really applied or what it's purpose is at all.

    <RequiresAdminRights>true</RequiresAdminRights>

https://github.com/pgmodeler/pgmodeler/commit/ec2b7e79e6d1297569fa820bfbf8b8bf15cffef2#diff-aacc7034d32c2ff5d652580fa01e2d36R16

Looking at `Inno Setup Help`, they distinguish administrative from non-administrative mode and the setting above might trigger a non-administrative installation even if the installer is executed as an admin. If it's not the setting above, it might be the changed handling of the start menu entry as well:

		component.addOperation("CreateShortcut", "@TargetDir@/pgmodeler.exe", "@StartMenuDir@/pgModeler.lnk",
            "workingDirectory=@TargetDir@", "iconPath=@TargetDir@/pgmodeler.exe",
            "iconId=0", "description=PostgreSQL Database Modeler");

https://github.com/pgmodeler/pgmodeler/commit/ec2b7e79e6d1297569fa820bfbf8b8bf15cffef2#diff-c4b4d4044929f6f5059f18d10982ac4fR27

The following screenshot make clear that even if the installer is executed as admin, it's not using the default system wide start menu anymore, but that locally to the admin-user instead. The system wide one contains far more entries.

![pgModeler select start menu](https://user-images.githubusercontent.com/6223655/71542655-307c9f80-2969-11ea-94a6-e1ed32c4b5c8.png)

That is totally in-line with what is documented [non-administrativer vs. administrative mode](http://www.jrsoftware.org/ishelp/index.php?topic=admininstallmode):

> In administrative install mode:

> The {group} folder is created in the All Users profile.
> The "auto" form of the directory and Shell Folder constants is mapped to the "common" form.
> The HKA and uninstall info root keys will be HKEY_LOCAL_MACHINE.

> In non administrative install mode:

> The {group} folder is created in the current user's profile.
> The "auto" form of the directory and Shell Folder constants is mapped to the "user" form.
> The HKA and uninstall info root keys will be HKEY_CURRENT_USER.

There's an [overview](http://www.jrsoftware.org/ishelp/index.php?topic=commonparams) of how behaviour of some constants is changes as well:


  | Administrative | Non administrative
-- | -- | --
autoappdata | commonappdata | userappdata
autocf | commoncf | usercf
autocf32 | commoncf32 | usercf
autocf64 | commoncf64 | usercf
autodesktop | commondesktop | userdesktop
autodocs | commondocs | userdocs
autopf | commonpf | userpf
autopf32 | commonpf32 | userpf
autopf64 | commonpf64 | userpf
autoprograms | commonprograms | userprograms
autostartmenu | commonstartmenu | userstartmenu
autostartup | commonstartup | userstartup
autotemplates | commontemplates | usertemplates

So it seems pretty clear to me that you are triggering a user-specific installation somehow, regardless if the installer is executed as admin or not. In the past, executing it as admin switched between administrative and non-administrative installation mode instead.

**Comment by ams-tschoening** [comment]
This problem still exists in the released version of 0.9.2 and most of the following comment applies here as well:

https://github.com/pgmodeler/pgmodeler/issues/1350#issuecomment-569409144

Didn't find something to distinguish between user- and system-wide app-registration yet.

**Comment by ams-tschoening** [comment]
https://stackoverflow.com/questions/59510656/how-to-distinguish-per-user-vs-system-wide-installation-in-qt-installer-framewo

**Comment by jmevel** [comment]
Version 0.9.2 has LOTS of bugs. 
This is really a deteriorated user experience compare to version 0.9.1

**Comment by ams-tschoening** [comment]
The project needs more manpower. ;-)

**Comment by rkhaotix** [comment]
@jmevel And what could be these bugs?

**Comment by jmevel** [comment]
I really don't have time to open a ticket for each of them I must move on my work now.
These bugs are like super obvious (many random error messages at startup, table names and column names don't show anymore in the design view...etc)

I think Raphael forgot to remove a reference to his **C:\Users\Raphael\Desktop\pgmodeler\build\conf** directory because many error messages are related to that folder. Even if I copy the **conf** folder to that path it still breaks in many ways

**Comment by jmevel** [comment]
For example try to open a .dbm file directly by clicking on it. 
Also the design view not showing column names and table names is quite bothering

Sorry for not opening tickets

**Comment by rkhaotix** [comment]
@jmevel Okay, that's a shame because this kind of attitude don't help. I will see what I can do.

Those problems you mentioned are all things that can be easily solved (or are in the way to be fixed). pgModeler isn't perfect and I know that but based upon you said those aren't "LOT OF BUGS" and if you look to the development log I try to fix critical bugs as soon as they are reported (of course if I can reproduce them!)

**Comment by ams-tschoening** [comment]
> For example try to open a .dbm file directly by clicking on it.

This sounds like the problems with the installer I ran into as well. Have a look at #1350 and especially the following comment mentioning `AllUsers=true`.

https://github.com/pgmodeler/pgmodeler/issues/1350#issuecomment-570944740

**Comment by rkhaotix** [comment]
@ams-tschoening This one I'll work carefully in order to solve once for all. Thanks for clarifying.
