### ISSUE TITLE
No building on Fedora 18

### ISSUE THREAD

**Issue by sergiovl** [pgmodeler/pgmodeler#135]
I install this packages:
- qt3-devel-3.3.8b-43.fc18.x86_64
- postgresql-devel-9.2.3-1.fc18.x86_64
- libxml2-devel-2.9.0-3.fc18.x86_64

I create libpg.pc:
$ cat /usr/lib64/pkgconfig/libpq.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib64/pgsql
includedir=${prefix}/include/pgsql

Name: LibPQ
Version: 5.0.0
Description: Library PQ
Requires:
Libs: -L${libdir} -lpq
Cflags: -I${includedir}

Commands:
$ pkg-config libpq --cflags --libs
-I/usr/include/pgsql  -L/usr/lib64/pgsql -lpq

$ pkg-config libxml-2.0 --cflags --libs
-I/usr/include/libxml2  -lxml2  

$ qmake pgmodeler.pro 

$ make
cd libutil && make -f Makefile
make[1]: Entering directory `/home/sergiovl/workspace/pgmodeler/libutil'
g++ -c -pipe -Wall -W -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -fPIC  -DQT_NO_DEBUG -DQT_SHARED -DQT_TABLET_SUPPORT -DQT_THREAD_SUPPORT -I/usr/lib64/qt-3.3/mkspecs/default -I. -Isrc -I../libdbconnect/src -I../libparsers/src -I../libpgmodeler/src -I../libobjrenderer/src -I../libpgmodeler_ui/src -I/usr/lib64/qt-3.3/include -Isrc/ -Imoc/ -o obj/exception.o src/exception.cpp
In file included from src/exception.cpp:1:0:
src/exception.h:29:19: fatal error: QObject: File or directory not found
compilation terminated.
make[1]: ** [obj/exception.o] Erro 1
make[1]: Leaving directory`/home/sergiovl/workspace/pgmodeler/libutil'
make: *\* [sub-libutil] Erro 2

**Comment by darwindave** [comment]
thanks @sergiovl 
These instructions seemed to work for 0.8.1-beta1 on fedora 22. i just changed 

    qmake-qt4 pgmodeler.pro 

to 

    qmake-qt5 pgmodeler.pro

**Comment by Hubbitus** [comment]
Who want may use my builds: http://rpm.hubbitus.info/Fedora21/pgmodeler/
