### ISSUE TITLE
Validation failed: no DTD found

### ISSUE THREAD

**Issue by KeidyU** [pgmodeler/pgmodeler#1351]
Getting the error **Validation failed: no DTD found,** on Windows

i have this bash that works fine in Linux, but when i try to execute on Windows i get the error.

set -e
SQLMODEL="./database/model.sql"
pgmodeler-cli  -if ./database/model.dbm -ef -of $SQLMODEL && \
    sed -i '1s/^/CREATE DATABASE db_name;\n\\c db_name;\n/' $SQLMODEL

The error is: 

[0] src/syntaxhighlighter.cpp (580)
  void SyntaxHighlighter::loadConfiguration(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[1] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[2] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[3] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

** pgmodeler-cli aborted due to critical error(s). **

I/O error : failed to load external entity "E:/PROYECTO-Drillit/server/conf/dtd/source-code-highlight.dtd"
highlight SYSTEM "E:/PROYECTO-Drillit/server/conf/dtd/source-code-highlight.dtd"
                                                                               ^
validity error : Validation failed: no DTD found !
<source-code-highlight>
                      ^

I want to ask if there is a way to set up the path where pgmodeler go to find conf folder. That i 
think will solve the issue.

Thanks

Working environment :
 - OS:   Windows
 - Version: 10
 - pgModeler version: 0.92
 - Qt version:

**Comment by rkhaotix** [comment]
@KeidyU Did you try to use the latest 0.9.3-beta1? Issues related to path resolving were fixed during the 0.9.3 development.
I'll close this issue since I think it's solve, anyway, if you still find problem running pgModeler as you need feel free to reopen this ticket.
