### ISSUE TITLE
can't save with postgis

### ISSUE THREAD

**Issue by pasqal** [pgmodeler/pgmodeler#1352]
I use 
postgresql 11
postgis 2.8
linux Mx-linux 19 patito
pgmodeler v0.9.1 QT 5.11.13 (install from distro)

I import from my DB with all my extension (to preserve postgis), import fail with no extensions.
But i can't save the model

[7] src/schemaparser.cpp (1319)
  QString SchemaParser::getCodeDefinition(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `storage' with an undefined value in file `/usr/share/pgmodeler/schemas/xml/usertype.sch', line 46, column 5!

[6] src/schemaparser.cpp (1436)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `storage' with an undefined value in file `/usr/share/pgmodeler/schemas/xml/usertype.sch', line 46, column 5!

[5] src/schemaparser.cpp (910)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&, unsigned int)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `storage' with an undefined value in file `/usr/share/pgmodeler/schemas/xml/usertype.sch', line 46, column 5!

[4] src/baseobject.cpp (836)
  virtual QString BaseObject::getCodeDefinition(unsigned int, bool)
    [ERR_ASG_OBJ_INV_DEFINITION] The object `public.box2df' (Type) has inconsistent SQL or XML definition!

[3] src/databasemodel.cpp (6742)
  virtual QString DatabaseModel::getCodeDefinition(unsigned int, bool)
    [ERR_ASG_OBJ_INV_DEFINITION] The object `public.box2df' (Type) has inconsistent SQL or XML definition!

[2] src/databasemodel.cpp (7198)
  void DatabaseModel::saveModel(const QString&, unsigned int)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/pasqal/Documents/basr_edp_fixed.dbm' due to one or more errors in the definition generation process!

[1] src/modelwidget.cpp (1592)
  void ModelWidget::saveModel(const QString&)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/pasqal/Documents/basr_edp_fixed.dbm' due to one or more errors in the definition generation process!

[0] src/mainwindow.cpp (1371)
  void MainWindow::saveModel(ModelWidget*)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `/home/pasqal/Documents/basr_edp_fixed.dbm' due to one or more errors in the definition generation process!

Thank for your help

**Comment by rkhaotix** [comment]
Could you please share your model or database dump?

**Comment by pasqal** [comment]
I share my fle by MP.
I make my file with import from DB, I make modifications and i can save in pgmodeler 0.9.1-beta. After I change my OS and install pgmodeler 0.9.1.
I can open my old file but not save (see error).
