### ISSUE TITLE
PostGres 8.x not supported

### ISSUE THREAD

**Issue by manojb23** [pgmodeler/pgmodeler#1354]
**Bug description**
I was using this on PostGres 8.4 ( Greenplum 5.x). I am now getting an error that PostGres8.x is not supported. Can we reenable the product to work on PostGres8.4 even though it is not supported? 
There are open source products like Greenplum that rely on PostGres 8.x

**How to reproduce**
As soon as you connect to a database of PG 8.x version, it throws the error

**Expected behavior**
Support PG 8.x

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
The support to PostgreSQL 8.x was dropped long ago still in 0.7.x due to eol announcement of that db series. Unfortunately, bringing back this support is an almost impossible task due to the amount of effort needed. So, it's not in my plans to work on this. Sorry.

**Comment by denis-mrd** [comment]
Sorry for necroposting... Is it possible to add GreenPlum support by developing a some plugin?

**Comment by rkhaotix** [comment]
I doubt it, sorry. PostgreSQL 9.x is also too old for the current state of pgModeler's code base.
