### ISSUE TITLE
Cannot use cli in a docker

### ISSUE THREAD

**Issue by LinqLover** [pgmodeler/pgmodeler#1357]
**Bug description**
Cannot start `pgmodeler-cli` from a docker image.
```
$ pgmodeler-cli
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

**How to reproduce**
```
$ sudo apt-get update -y
$ sudo apt-get install -y pgmodeler
$ pgmodeler-cli
```
**Expected behavior**
Something happens, and then the database has been imported.

**Info about your desktop**
 - OS: Ubuntu in a docker
 - Version: Ubuntu 18.04.3 LTS
 - pgModeler version: ?

**Comment by xmsk** [comment]
I ran into a similar problem. I think this is related to the fact that you do not have a display server (or whatever it is called) within a Docker container.
Apparently there is a QT switch to make applications run without a screen. Try running
```
pgmodeler-cli -platform offscreen
```
followed by any arguments you would like to pass to `pgmodeler-cli`, e.g.
```
pgmodeler-cli -platform offscreen --input /path/to/example.dbm --export-to-dbms --host <db_host> --port <db_port> --user postgres --passwd <password> --initial-db postgres
```
This worked for me anyway.
