### ISSUE TITLE
CASTs get removed during migration to 0.9.2.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1361]
**Bug description**
When opening a formerly working model with 0.9.2, an error is shown about being unable to load the model:

> Could not load the database model file C:\[...]\schema.dbm. Check the error stack to see details. You can try to fix it in order to make it loadable again.

The stack trace contains error messages like the following:

> The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!

After choosing to fix the model, all CASTs seem to have simply been removed. The following is one example for such pair of function and CAST:

	<function name="fn_cast_inet_from_varchar"
			window-func="false"
			returns-setof="false"
			behavior-type="CALLED ON NULL INPUT"
			function-type="IMMUTABLE"
			security-type="SECURITY INVOKER"
			execution-cost="1"
			row-amount="0">
		<schema name="public"/>
		<language name="plpgsql" sql-disabled="true"/>
		<return-type>
		<type name="inet" length="1"/>
		</return-type>
		<parameter name="value" in="true">
			<type name="varchar" length="0"/>
		</parameter>
		<parameter name="modifier" in="true">
			<type name="integer" length="1"/>
		</parameter>
		<parameter name="is_explicit" in="true">
			<type name="boolean" length="1"/>
		</parameter>
		<definition><![CDATA[/**
	 * Cast {@code varchar} to {@code inet}.
	 * <p>
	 * The following casts {@code varchar} to {@code clt_inet_addr_src}, to make inserts e.g. using
	 * DbVisualizer easier. Using its GUI it doesn't seem possible to provide an explicit {@code CAST}
	 * like is possible in SQL. Without such a {@code CAST} Postgres throws errors, because just like
	 * jOOQ, DbVisualizer lacks the type {@code inet} and uses {@code varchar} instead, wich doesn't
	 * cast implicitly.
	 * </p>
	 * @see http://stackoverflow.com/questions/21285414/macaddr-inet-type-of-postgres-in-slick
	 */
	DECLARE
		ret_val inet;

	BEGIN
		SELECT inet_in(CAST(value AS cstring)) INTO ret_val;

		RETURN ret_val;
	END;]]></definition>
	</function>

	<cast  cast-type="assignment">
		<type name="varchar" length="0"/>
		<type name="inet" length="1"/>
		<function signature="public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)"/>
	</cast>

This seems to only happen with CASTs and their functions, the model contains lots of other functions and e.g. triggers and those seem to be resolved properly.

**How to reproduce**
The bug is reproducible with the mentioned schema, but I can't provide the full one.

**Expected behavior**
The CASTs should not have been removed, because the referenced functions should have been found.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: Windows 10
 - Version: 1909
 - Window manager:
 - pgModeler version: 0.9.2
 - Qt version: bundled with pgModeler

**Stacktrace / Debug info**
```
	[0] src/mainwindow.cpp (1685)
	  void MainWindow::showFixMessage(Exception&, const QString&)
	    [ModelFileNotLoaded] Could not load the database model file `C:\Users\tschoening\Documents\Eclipse\Java Sm-Mtg\de.am_soft.sm_mtg.backend\src\main\resources\de\am_soft\sm_mtg\backend\daos\db\schema.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

	[1] src/mainwindow.cpp (977)
	  void MainWindow::addModel(const QString&)
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!

	[2] src/mainwindow.cpp (952)
	  void MainWindow::addModel(const QString&)
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!

	[3] src/modelwidget.cpp (1427)
	  void ModelWidget::loadModel(const QString&)
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!

	[4] src/databasemodel.cpp (3358)
	  void DatabaseModel::loadModel(const QString&)
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!
	       ** C:\Users\tschoening\Documents\Eclipse\Java Sm-Mtg\de.am_soft.sm_mtg.backend\src\main\resources\de\am_soft\sm_mtg\backend\daos\db\schema.dbm (line: 774)

	[5] src/databasemodel.cpp (3288)
	  void DatabaseModel::loadModel(const QString&)
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!
	       ** C:\Users\tschoening\Documents\Eclipse\Java Sm-Mtg\de.am_soft.sm_mtg.backend\src\main\resources\de\am_soft\sm_mtg\backend\daos\db\schema.dbm (line: 774)

	[6] src/databasemodel.cpp (4516)
	  Cast* DatabaseModel::createCast()
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!
	       ** C:\Users\tschoening\Documents\Eclipse\Java Sm-Mtg\de.am_soft.sm_mtg.backend\src\main\resources\de\am_soft\sm_mtg\backend\daos\db\schema.dbm (line: 774)

	[7] src/databasemodel.cpp (4504)
	  Cast* DatabaseModel::createCast()
	    [RefObjectInexistsModel] The object `cast(varchar,inet)' (Cast) is referencing the object `public.fn_cast_inet_from_varchar(IN varchar,IN integer,IN boolean)' (Function) which was not found in the model!
```

**Comment by ams-tschoening** [comment]
I might have found the problem: After fixing the model, I simply created a new CAST and looked at how it references functions now:

	<cast  cast-type="assignment">
		<type name="varchar" length="0"/>
		<type name="inet" length="0"/>
		<function signature="public.fn_cast_inet_from_varchar(varchar,integer,boolean)"/>
	</cast>

The difference is that `IN` is not used anymore, so I deleted that from the old model and opening it succeeded. Would be great if pgModeler would simply handle that on its own.

**Comment by rkhaotix** [comment]
The CLI is intended to do that... but in that case specifically the proper code somehow was not merged into the final version.. I might forgot to upload it since I was working on three different machines while coding this last version. I'll look for this fix on the history and if I can't find I'll do it again it's not complicated. Sorry for that.

**Comment by rkhaotix** [comment]
Done. I'll upload a new build of 0.9.2 in a few hours.

**Comment by ams-tschoening** [comment]
Thanks for the fast fix!

**Comment by ams-tschoening** [comment]
Reopening, because I'm still running into problems: I've downloaded your updated build and re-tested my file with it, got the warning about that the model needs to be fixed, clicked to fix it and `pdmodeler-cli.exe` is running at 100 % CPU-load for minutes already and doesn't seem to finish ever.

	pgModeler 0.9.2 command line interface.
	Starting model fixing...
	Loading input file: C:/Users/tschoening/Documents/Eclipse/Java Sm-Mtg/de.am_soft.sm_mtg.backend/src/main/resources/de/am_soft/sm_mtg/backend/daos/db/schema.dbm
	Fixed model file: C:/Users/tschoening/Documents/Eclipse/Java Sm-Mtg/de.am_soft.sm_mtg.backend/src/main/resources/de/am_soft/sm_mtg/backend/daos/db/schema_fixed.dbm
	Extracting objects' XML...
	Recreating objects...

Opening the file in older versions took only seconds. Looking at the [code](https://github.com/pgmodeler/pgmodeler/commit/3c82ccb0343471c9ca40f7b3c43183f9e4864063), you might have implemented and endless loop:

	while(sig_idx >= 0)
	{
		signature = obj_xml.mid(sig_idx, regexp.matchedLength());

		if(!signature.contains(in_keyw))
			continue;
	[...]
	}

In case of the first `if`, `sig_idx` is never advanced, resulting in checking the same string over and over again. Seems like you need to `break` instead of `continue` or advance `sig_idx`, like is done otherwise:

    sig_idx = regexp.indexIn(obj_xml, sig_idx + len);

**Comment by rkhaotix** [comment]
That's why I need the original file that was causing the problem. I used the small test you posted. With that the fix works fine. I'll see what's happening.

**Comment by rkhaotix** [comment]
Sorry, my bad. I've found the error... :|

**Comment by ams-tschoening** [comment]
Just tested with your changes and my model gets fixed now, thanks.

**Comment by ams-tschoening** [comment]
Must have done something wrong in the former test, with my custom build version of pgModeler my schema file can't be fixed anymore. While pgModeler tells me that the model has been fixed, when it tries to open the fixed version, the same error like before is shown that the model needs to be fixed an all happens again. I already made sure that your formerly committed fixes are available in by branch.

I'm sending you my schema file by private mail, would be great if you could have a look at that. Thanks!

**Comment by ams-tschoening** [comment]
Closing again, the issue seems to be related to my custom version of pgModeler in my setup somehow. @rkhaotix thankfully tested my file and fixing worked with pgModeler containing the commits mentioned here.
