### ISSUE TITLE
Minor improvements to the build and/or its instructions on Windows.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1363]
# "msys_64" vs. "msys64"

The following files contain directory names like `msys_64`:

* pgmodeler.pri
* windeploy.sh

I suggest to change those to `msys64` instead, because that was the default name used when I set the environment up. This prevents users from unnecessary changes, especially because some of those places are not yet documented at all, like `windeploy.sh`.

# Exporting "bin"-path

The following was [additionally necessary](https://github.com/pgmodeler/pgmodeler/issues/1346#issuecomment-569510102) and is not yet documented:

    export PATH=$PATH:/C/msys64/mingw64/bin

# Package for QT installer framework

The docs contain the following statement for Windows currently:

    pacman -S base-devel mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-postgresql mingw-w64-x86_64-qt5

But that is not enough to build the installer, the [following package](https://packages.msys2.org/package/mingw-w64-x86_64-qt-installer-framework?repo=mingw64) needs to be added as well:

    mingw-w64-x86_64-qt-installer-framework

# "QT_IFW_ROOT" unnecessary/wrong

`windeploy.sh` contains the following statement:

    QT_IFW_ROOT=/c/qt-ifw

But with the above installed package, that path is not available and `binarycreator` instead is simply available using `PATH`. So that variable would not be needed at all anymore, which makes building easier because of less manual changes.

# "DIST_ROOT" isn't created automatically

`windeploy.sh` contains some `DIST_ROOT`, which doesn't seem to be created automatically, but let the final installer-step fail if missing. Creating would be easy:

    mkdir -p "${DIST_ROOT}"
    if [ $BUILD_ALL -eq 1 ]; then
      rm -r "${DIST_ROOT}/*" > $LOG 2>&1
    fi

Is there a reason for cleaning `DIST_ROOT` only sometimes? Sounds easier and safer to simply do it always, as users can switch different versions even without building all.

# Patches

[pgmodeler.pri.diff.txt](https://github.com/pgmodeler/pgmodeler/files/4010598/pgmodeler.pri.diff.txt)
[windeploy.sh.diff.txt](https://github.com/pgmodeler/pgmodeler/files/4010599/windeploy.sh.diff.txt)

**Comment by rkhaotix** [comment]
> # "msys_64" vs. "msys64"
> The following files contain directory names like `msys_64`:
> 
> * pgmodeler.pri
> * windeploy.sh
> 
> I suggest to change those to `msys64` instead, because that was the default name used when I set the environment up. This prevents users from unnecessary changes, especially because some of those places are not yet documented at all, like `windeploy.sh`.
> 

Instead of hardcoding `msys64` as you suggest it's better to create an variable which receives the full path to msys installation because it is completely dependent on the user's env. One may install it at `/c/msys_64` (my case), others at `/c/msys64` or even another completely different path. So, a variable may solve this.

> # Exporting "bin"-path
> The following was [additionally necessary](https://github.com/pgmodeler/pgmodeler/issues/1346#issuecomment-569510102) and is not yet documented:
> 
> ```
> export PATH=$PATH:/C/msys64/mingw64/bin
> ```
> 

I still can't see this issue being reproduced in my environment variable. If the script is being running from mingw64 console it is not needed to export it's bin folder to PATH. I'll test the deployment script again to see if the vulkan related error happens.

> # Package for QT installer framework
> The docs contain the following statement for Windows currently:
> 
> ```
> pacman -S base-devel mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-postgresql mingw-w64-x86_64-qt5
> ```
> 
> But that is not enough to build the installer, the [following package](https://packages.msys2.org/package/mingw-w64-x86_64-qt-installer-framework?repo=mingw64) needs to be added as well:
> 
> ```
> mingw-w64-x86_64-qt-installer-framework
> ```
> 
> # "QT_IFW_ROOT" unnecessary/wrong
> `windeploy.sh` contains the following statement:
> 
> ```
> QT_IFW_ROOT=/c/qt-ifw
> ```
> 
> But with the above installed package, that path is not available and `binarycreator` instead is simply available using `PATH`. So that variable would not be needed at all anymore, which makes building easier because of less manual changes.
> 

The installation instructions doesn't contemplate the generation of installers. This is on purpose to make that step-by-step as simple as possible. Also, the current reference to IFW on the deployment script is that way because the version of IFW available at msys repository was kinda buggy and the installer wasn't being generated correctly so I decided to use the official Qt IFW from https://qt.io this explains why that path `/c/qt-ifw`. But I'm gonna review this and do the proper changes.

> # "DIST_ROOT" isn't created automatically
> `windeploy.sh` contains some `DIST_ROOT`, which doesn't seem to be created automatically, but let the final installer-step fail if missing. Creating would be easy:
> 
> ```
> mkdir -p "${DIST_ROO.T}"
> if [ $BUILD_ALL -eq 1 ]; then
>   rm -r "${DIST_ROOT}/*" > $LOG 2>&1
> fi
> ```
> 
> Is there a reason for cleaning `DIST_ROOT` only sometimes? Sounds easier and safer to simply do it always, as users can switch different versions even without building all.
> 

Actually, there's no need for these instructions anymore. The correct procedure should be:

```
mkdir -p "${DIST_ROOT}" > $LOG 2>&1 
rm -r "${DIST_ROOT}/*" > $LOG 2>&1
```

I'll change the script during 0.9.3.

Thanks

**Comment by ams-tschoening** [comment]
Guten Tag Raphael Araújo e Silva,
am Montag, 30. Dezember 2019 um 21:55 schrieben Sie:

>> ```
>> export PATH=$PATH:/C/msys64/mingw64/bin
>> ```

> I still can't see this issue being reproduced in my environment
> variable. If the script is being running from mingw64 console it is
> not needed to export it's bin folder to PATH. I'll test the
> deployment script again to see if the vulkan related error happens.

The following is what I get when manually executing "msys2_shell.cmd"
after setting my environment up using official deployment archives
instead of using the installer. Maybe things are a bit different with
the installer?

> Administrator@tschoening-nb MSYS ~
> # echo $PATH
> /usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

> tschoening@tschoening-nb MSYS ~
> $ echo $PATH
> /usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

Shouldn't harm too much adding a note to the PATH in the docs, though.
As can be seen by the linked issue, I wasn't the only/first one for
whom PATH was incomplete.

> got the same error, it wont make in the next step

https://github.com/pgmodeler/pgmodeler/issues/1346#issuecomment-559913460

Mit freundlichen Grüßen,

Thorsten Schöning

-- 
Thorsten Schöning       E-Mail: Thorsten.Schoening@AM-SoFT.de
AM-SoFT IT-Systeme      http://www.AM-SoFT.de/

Telefon...........05151-  9468- 55
Fax...............05151-  9468- 88
Mobil..............0178-8 9468- 04

AM-SoFT GmbH IT-Systeme, Brandenburger Str. 7c, 31789 Hameln
AG Hannover HRB 207 694 - Geschäftsführer: Andreas Muchow

**Comment by ams-tschoening** [comment]
Another thing I just noticed: After checking out the current master, it warns about missing plugins and informs to add its corresponding repo. Why not add that as submodule automatically? Did so right now and seemed to work perfectly.

**Comment by ams-tschoening** [comment]
I found a lot more files worth ignoring, while only `release` in the last line is the output folder I choose during build Everything else comes from the project. Not sure if this is worth an individual PR or I should combine things with the other suggested changes...

[dummy.gitignore.txt](https://github.com/pgmodeler/pgmodeler/files/4023427/dummy.gitignore.txt)
[dummy.gitignore.diff.txt](https://github.com/pgmodeler/pgmodeler/files/4023425/dummy.gitignore.diff.txt)

**Comment by ams-tschoening** [comment]
After building the installer on Windows I got error message about the following missing DLLs:

* libdouble-conversion.dll
* libzstd.dll

This needs to be added to the copy-instructions in the docs AND in `windeploy.sh`:

[windeploy.sh.diff.txt](https://github.com/pgmodeler/pgmodeler/files/4024026/windeploy.sh.diff.txt)

**Comment by rkhaotix** [comment]
> After building the installer on Windows I got error message about the following missing DLLs:
> 
> * libdouble-conversion.dll
> * libzstd.dll
> 
> This needs to be added to the copy-instructions in the docs AND in `windeploy.sh`:
> 
> [windeploy.sh.diff.txt](https://github.com/pgmodeler/pgmodeler/files/4024026/windeploy.sh.diff.txt)

These dll are from Qt 5.14 no? Because building with 5.12 (LTS) , the official version adopted for binaries , it's everything ok.

**Comment by ams-tschoening** [comment]
This happens when I follow your instruction by installing [mingw-w64-x86_64-qt5](https://packages.msys2.org/package/mingw-w64-x86_64-qt5), which seems to `5.13.2-1` currently. The only thing I did on my own was additionally installing [mingw-w64-x86_64-qt-installer-framework](https://packages.msys2.org/package/mingw-w64-x86_64-qt-installer-framework?repo=mingw64) in version `3.2.0-1` using the package manager, which you said you did differently.

Don't know where the requirements for the new DLLs actually come from. If it's QT itself, this could happen to everyone following your instructions, if it's because of QTIF, you should decide if you prefer providing that manually or using the package manager as well. The latter is easier, at least if things work.

If the DLLs are available in your version of QT/QTIF, you might as well decide to simply add them for future releases already.

**Comment by rkhaotix** [comment]
That's a dependency of 5.13+. Find out yesterday while testing your PRs. Soon I will update the installation procedures
