### ISSUE TITLE
I bought the program and could not install

### ISSUE THREAD

**Issue by SerhiiYAroshenko** [pgmodeler/pgmodeler#1364]
Good afternoon.
![2019-12-31](https://user-images.githubusercontent.com/46189920/71621776-ff56d600-2bd9-11ea-9ab7-6ec44b21819c.png)
I bought the program and could not install.
The installer downloaded, but it does not start under any version of the operating system (10.8.1.7, XP).

P.S. Great gift for the new year, thanks.

**Comment by rkhaotix** [comment]
Well, it cannot work for certain machines. This is why this support channel exists. Could you provide more details so I can help you?

**Comment by SerhiiYAroshenko** [comment]
You did not specify what specific information you are interested in,
therefore I will provide information about the operating system. If
additional information is needed, indicate which.

вт, 31 дек. 2019 г. в 15:00, Raphael Araújo e Silva <
notifications@github.com>:

**Comment by rkhaotix** [comment]
What OS? What errors? What version of the tool?

**Comment by SerhiiYAroshenko** [comment]
What OS?
*Windows 10 Pro*
*1903*
*18362.535*
What errors?
*The installer just does not start.*
What version of the tool?
*pgmodeler-0.9.2-windows32.exe*

вт, 31 дек. 2019 г. в 16:36, Raphael Araújo e Silva <
notifications@github.com>:

**Comment by Maxzor** [comment]
When you run pgmodeler-0.9.2-windows32.exe from cmd/powershell, is there any output?

**Comment by rkhaotix** [comment]
@Maxzor I was about to ask that! 😅

That's strange the installer generally outputs errors not just doesn't start. 

@SerhiiYAroshenko could you try to run the installer as administrator and/or from console? 

if you prefer I can refund you without problem. It's up to you. :)

**Comment by SerhiiYAroshenko** [comment]
Unfortunately, there is no reaction when starting from the administrator
and in the console. No error occurs, but no action is taken by the
installer program.

That is, the program will not work?

вт, 31 дек. 2019 г. в 17:18, Raphael Araújo e Silva <
notifications@github.com>:

**Comment by SerhiiYAroshenko** [comment]
Lord!
New Year's miracle. I just downloaded the installer from the site and
launched it in the console from under the administrator and the installer
started and the licensed version works with full functionality.
Thanks!
Happy New Year, everyone!

P.S. The question is closed.

вт, 31 дек. 2019 г. в 17:18, Raphael Araújo e Silva <
notifications@github.com>:

**Comment by Maxzor** [comment]
Btw when fiddling with windows had pgmodeler not outputting anything by default.
Tried CONFIG+=console without success.
I got it working with : https://stackoverflow.com/a/41701133/7359123
First thing in main() :
```
#ifdef _WIN32
if (AttachConsole(ATTACH_PARENT_PROCESS)) {
    freopen("CONOUT$", "w", stdout);
    freopen("CONOUT$", "w", stderr);
}
#endif
```
