### ISSUE TITLE
Platform not recognized - Ubuntu 19.10

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1365]
**Bug description**

maxzor@it:~/pgm$ $QT_ROOT/bin/qmake -r CONFIG=+release PREFIX=$INSTALLATION_ROOT BINDIR=$INSTALLATION_ROOT PRIVATEBINDIR=$INSTALLATION_ROOT PRIVATELIBDIR=$INSTALLATION_ROOT/lib PLUGINSDIR=$INSTALLATION_ROOT/plugins pgmodeler.pro
sh: 1: wingetdate.bat: not found
Reading /home/maxzor/pgm/libutils/libutils.pro

 Altough I should be in the pgmodeler.pri unix scope ... oO

Project WARNING: CONFIG-=import_qpa_plugin is deprecated. Use QTPLUGIN.platforms=- instead.

Qt 5.14.0 from qt.io

**Comment by rkhaotix** [comment]
Whaaat?  :/
Did you try to force the spec? 
Try this: ```qmake -spec linux-g++ [rest of the parents]```

**Comment by Maxzor** [comment]
same problem
lol my ubutunu is broken
