### ISSUE TITLE
pgModeler opens the restoration dialog on Windows always when double-clicking a *.dbm-file.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#1370]
**Bug description**
When double-clicking a *.dbm-file on Windows, pgModeler always comes up with the following dialog:

![pgModeler restore-dialog](https://user-images.githubusercontent.com/6223655/71787161-b907d980-3014-11ea-9645-a8ff545c31a5.png)

No matter if I restore or cancel, the dialog always comes again, but only if I double-click the file. If I instead open pgModeler manually and open the file manually, the dialog does not appear. I guess it doesn't have to do with the file itself, but the problems with the new installer (#1349, #1350) or stuff like that.

How does pgModeler recognize if there has been a problem before and decided to show that dialog?

**How to reproduce**
I can reproduce that simply by double-clicking any *.dbm-file.

**Expected behavior**
The restore-dialog should not be shown.

**Screenshots**
![pgModeler restore-dialog](https://user-images.githubusercontent.com/6223655/71787161-b907d980-3014-11ea-9645-a8ff545c31a5.png)

**Info about your desktop**
 - OS: Windows 10
 - Version: 1909
 - Window manager: -
 - pgModeler version: 0.9.2 and current master
 - Qt version: bundled with pgModeler

**Stacktrace / Debug info**
There are now error messages or stacktraces shown by pgModeler during exit.

**Comment by Maxzor** [comment]
I cannot manage to build a debug version with mingw qtcreator for now.
But you should look IMO at libpgmodeler_ui/modelrestorationform.cpp  line 35 :
```
QStringList ModelRestorationForm::getTemporaryModels(void)
{
	//Returns if there is some .dbm file on the tmp dir
	return(QDir(GlobalAttributes::TemporaryDir, QString("*.dbm"), QDir::Name, QDir::Files | QDir::NoDotAndDotDot).entryList());
}

```

**Comment by rkhaotix** [comment]
The problem @Maxzor is that when pgModeler starts after double -clicking the dbm file it'll create a temporary copy of it (which is normal and expected) but this operation is being performed before the model restoration form do its checking in order to appear or not. A small tweak may solve the issue.
