### ISSUE TITLE
No text on tables

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1375]
**Bug description**
There's no text.

**How to reproduce**
Worked fine in all pre-released of 0.9.2, now the final is broken.

**Expected behavior**
Text in the boxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/71971539-1cf3f300-320b-11ea-8c2b-12224e4b503c.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager: Explorer
 - pgModeler version: 0.9.2
 - Qt version:

**Additional info**
pgModeler should really try to break this tradition of having major breaking issues in the final release after months of stable pre-releases. I don't understand why this has been happening for years 😥 Is the problem using the pre-releases in the first place and messing up the local configurations? I keep running into this and it's super frustrating to have to roll back, because the Windows installer also refuses to operate if the previous version isn't uninstalled manually yet.

**Comment by rkhaotix** [comment]
Hi @oliversalzburg !

I really sorry for that. Unfortunately, some improvements done lead to the change of configurations structure causing this kind of problem. You can try to restore the default settings in Settings > Appearance . I really try not to break things but it's a bit complex when you're introducing new things. :(

About the installer, there's a long discussion rolling here on GitHub. After 0.9.1 the installer was unified and the one used on Linux is on also used on Windows. But on the latter platform things are a bit complicated and I will try to rewrite the installer scripts in the next week's. 

Sorry again ! :(

**Comment by oliversalzburg** [comment]
I had already tried to reset the appearance settings, but it didn't have any effect. Losing settings is also always a bit disappointing, but I try to keep close to the defaults anyway.

I completely get that there's always a risk of breaking things with last minute changes, but why not just add a Release Candidate after the Beta, at which stage only critical fixes will be added. That way people can be sure that the final is the way to go.

For the past 2 or 3 versions, the final was always broken after I've been successfully using a preview version before that for months. At some points it was even necessary to use the preview, because the final didn't support the new pg server version yet (which I fully understand). So then you're finally happy to get a stable version, it's disappointing when it doesn't work.

I'm sure you can relate and I don't want to complain too much, but, given the long preview periods, it seems like (release) quality control is generally very important to you. So the finals could maybe be paced slightly slower to really iron everything out. Then maybe the real final should just be a fresh label on the last stable RC 😊

**Comment by titoshadow** [comment]
Had the same issue on Windows, went Linux Mint and works seamless, just to add some hint

**Comment by AndeVandenberg** [comment]
I know this is a couple months late, but I had the same issue and if zoom is set to 100%, the text comes back!

**Comment by rkhaotix** [comment]
This happens only on Windows as other people reported. Unfortunately, it doesn't happen on my development environment on that system. 

@AndeVandenberg Which pgModeler version are you using?

**Comment by AndeVandenberg** [comment]
Hi @rkhaotix,

I'm using 0.9.3-alpha. It seems only the text in the tables dissappears at varying zooms - the relation text resizes properly.

Still very user-friendly at 100% zoom :)

Cheers,
Andre

**Comment by Andrevdb** [comment]
Just to follow up, this issue has stopped seemingly randomly. I haven't changed any settings or anything. Text is now visible in the tables regardless of zoom.

Cheers,
Andre
