### ISSUE TITLE
Diff tool consistently crashes when tries to create an RLS policy

### ISSUE THREAD

**Issue by AntonioAngelino** [pgmodeler/pgmodeler#1383]
**Bug description**
pgModeler consistently crashes when diff tool tries to generate a migration for a table that has an RLS policy applied.

Note: If the remote database doesn't have any policy applied, the diff tool is able to generate the migration and then apply it.

**How to reproduce**
1. Download [bug.zip](https://github.com/pgmodeler/pgmodeler/files/4053120/bug.zip)
 and then extract bug.dbm.
2. Open the model file, import the model in Postgres using the Export tool.
3. Run diff tool (even w/o changing the schema). It will consistently crash.

**Expected behavior**
Diff tool generates the migration script and applies it.

**Screenshots**

<img width="695" alt="pgModeler-diff-crash" src="https://user-images.githubusercontent.com/1618005/72246714-a5033f80-35f3-11ea-9c8f-dc79d08e68a6.png">

The screenshot has been taken before pgModeler quits unexpectedly (no error codes).

**Info about your desktop**
 - OS: Windows
 - Version: 10.0.18363 Build 18363
 - pgModeler version: 0.9.2 (build 20200106)
 - Qt version: Qt 5.13.2

**Comment by rkhaotix** [comment]
Hi @AntonioAngelino thanks for reporting that.

Just trying to get more details... It also crashes if you try just to import the database? Or the policy does not exist at the database?

**Comment by AntonioAngelino** [comment]
Hi @rkhaotix,

from my prev. post:

> Note: If the remote database doesn't have any policy applied, the diff tool is able to generate the migration and then apply it.

So:
- It works if you create the model from scratch.
- It works if you remove the policy from the remote database and then run the diff tool.
- it *doesn't work* if the policy already exists and you try to run the diff tool.

**Comment by rkhaotix** [comment]
@AntonioAngelino thank you very much! I'm really happy to receive such support from users!!!

I know that pgModeler isn't perfect and I'm constantly doing my best to make it reliable. I'm gonna work on this issue and release an snapshot build soon. Thanks for helping !

**Comment by rkhaotix** [comment]
@AntonioAngelino testing the model you provided I wasn't able to see a crash happening... :/
I'm on a openSuse 15.1, Qt 5.14. I'll try the same on Windows machine, but the software hangs or closes unexpectedly?

**Comment by AntonioAngelino** [comment]
> Closes unexpectedly.

Did you import the database before trying to run the diff tool?

The problem arises when the RLS policy already is in the database.

**Comment by rkhaotix** [comment]
Yes. I tried two ways:

1) Exported the model + Diff the model against the newly created db
2) Exported the model + Imported the database + Diff the imported model against the existing db

I'm on the 0.9.3-alpha codebase. Tried on Linux and Windows and nothing happens

**Comment by AntonioAngelino** [comment]
Quick video: https://www.youtube.com/watch?v=0xCbKe75JKc

> I'm on the 0.9.3-alpha codebase. Tried on Linux and Windows and nothing happens

I'm currently using the stable version. Where can I download the 0.9.3-alpha version?

**Comment by rkhaotix** [comment]
That's strange... I really can't get that bug.
I'll release a snapshot build soon so you can test the 0.9.3-alpha.

**Comment by AntonioAngelino** [comment]
@rkhaotix any news? :)

**Comment by rkhaotix** [comment]
No because no crash happens for me! :(
Could you send me a dump of your database where the problem raises?

**Comment by AntonioAngelino** [comment]
@rkhaotix 
I'm able to reproduce the bug by simply using the export tool, and then the diff tool.
The exporter successfully creates all the required DB objects (including the policy).

![Db Import](https://i.imgur.com/oK7WF6P.png)

If I run the diff tool to apply any change to the DB, it crashes.

FYI: I'm using PostgreSQL 11.5 in a docker container.

DB Dump: https://gist.github.com/AntonioAngelino/98d55be8fd4df7a0746ee6248ad5a20d

Let me know when you compile the 0.9.3-alpha for Win, so I can try to reproduce the bug w/ the new version, thank you.

**Comment by rkhaotix** [comment]
@AntonioAngelino thanks! Tried once more and nothing happens on both Linux and windows.

Let's wait until I release 0.9.3-alpha so you can do new tests. I'm finishing the last details of it and until the end of the next week the binaries will be available.

**Comment by AntonioAngelino** [comment]
@rkhaotix I downloaded the latest alpha version and the diff tool doesn't crash anymore! 🎉
