### ISSUE TITLE
Owner is no longer set in export

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1385]
**Bug description**
When creating an export of the model, all `ALTER X OWNER TO Y` calls are now comments and uneffective in setting the owner of the entity.

**How to reproduce**
Export a model.

**Expected behavior**
The owner is still set as with 0.9.2-beta2 and earlier versions.

**Comment by rkhaotix** [comment]
Hi @oliversalzburg I'm aware if that problem and I will release a snapshot build with the fix for this problem soon

**Comment by oliversalzburg** [comment]
@rkhaotix Awesome. We purchased a new license though recently and we no longer have access to snapshots.

**Comment by oliversalzburg** [comment]
@rkhaotix Just FYI, I've been enjoying these recent changes a lot today. The workflow is very smooth. Well done

**Comment by rkhaotix** [comment]
Thanks 😁
