### ISSUE TITLE
Diff Tool: cannot add new indexed column to an existing table

### ISSUE THREAD

**Issue by AntonioAngelino** [pgmodeler/pgmodeler#1396]
**Bug description**
Diff Tool generates wrong migration SQL when a new column + index is added to a table.

**How to reproduce**
1. Create a new table on pgModeler.
2. Export the table to Pgsql.
3. Add a new column.
4. Add an index on the new column.
5. Run the diff tool to update your database.

**Expected behavior**
The Diff tool must Alter tables before trying to create the indexes.

**Generated DDL**

```sql
-- [ Created objects ] --
-- object: comment_body_full_text_idx | type: INDEX --
-- DROP INDEX IF EXISTS test.comment_body_full_text_idx CASCADE;
CREATE INDEX comment_body_full_text_idx ON test.comment
	USING gin
	(
	  body_full_text
	);
-- ddl-end --

-- object: body_full_text | type: COLUMN --
-- ALTER TABLE test.content DROP COLUMN IF EXISTS body_full_text CASCADE;
ALTER TABLE test.content ADD COLUMN body_full_text tsvector;
-- ddl-end --


-- object: content_body_full_text_idx | type: INDEX --
-- DROP INDEX IF EXISTS test.content_body_full_text_idx CASCADE;
CREATE INDEX content_body_full_text_idx ON test.content
	USING gin
	(
	  body_full_text
	);
-- ddl-end --

-- object: body_full_text | type: COLUMN --
-- ALTER TABLE test.comment DROP COLUMN IF EXISTS body_full_text CASCADE;
ALTER TABLE test.comment ADD COLUMN body_full_text tsvector;
-- ddl-end --
```

**Info about your desktop**
 - OS: Windows 10
 - pgModeler version: v0.9.3-alpha_snapshot20200131
 - Qt version: 20200131 Qt 5.13.2

**Comment by rkhaotix** [comment]
@AntonioAngelino I'm 99% sure that the index was created before the column. :)

Try to swap the ids of the table owning the columns and the index then validate the model and apply the fixes if needed. Finally, try to diff again.

**Comment by AntonioAngelino** [comment]
@rkhaotix yes, you're right. :)
So the diff tool follows the OIDs just like the export tool. Nice to know!
