### ISSUE TITLE
Add support for PL/Python and plv8 languages

### ISSUE THREAD

**Issue by AntonioAngelino** [pgmodeler/pgmodeler#1397]
PgModeler supports c, plpgsql, and sql for defining Stored Procedures.

I'd like to write SPs in PL/Python and/or plv8. 

[PL/Python](https://www.postgresql.org/docs/9.5/plpython.html) is part of PostgreSQL since v. 9.5. 

[PLV8](https://plv8.github.io/) is a trusted Javascript language extension for PostgreSQL. It can easily installed as a pg extension, and it's also already installed by default in AWS RDS and Azure Database instances.

**Comment by rkhaotix** [comment]
I can add ```plpythonu```. But for now you can easily create dummy languages with the names ```plpythonu``` and ```plv8``` and use them in your functions.

https://pgmodeler.io/support/docs/714-creating-dummy-objects?v=0.9.2

**Comment by AntonioAngelino** [comment]
Man, you thought about anything! 😄 
I didn't think that it could be so easy.
