### ISSUE TITLE
Geometry type mismatch

### ISSUE THREAD

**Issue by MistrBurns** [pgmodeler/pgmodeler#1398]
**Bug description**

I have two tables containing geometry columns. Both columns appear every time a diff is made against the database, although there were no changes made in the model or in the database. This is the output from the diff preview:

-- [ Changed objects ] --
ALTER TABLE [tablename] ALTER COLUMN geom TYPE geometry;
-- ddl-end --
ALTER TABLE [tablename] ALTER COLUMN geom TYPE geometry;

Please note, that this error is only ocurring when using the geometry type in pg-modeler. Importing the table into the working model populates the table with data-type public.geometry and the diff works as expected.

**Info about your desktop**
 - OS: Windows 10
 - Version: 10.0.18363 Build 18363
 - Window manager: 
 - pgModeler version: 0.9.2 stable/0.9.3 alpha
 - Qt version:

-Database: PostgreSQL 12.2 (Debian 12.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
-PostGIS: version 3.0.0

**Comment by rkhaotix** [comment]
Thanks @MistrBurns !
I'll investigate this.
