### ISSUE TITLE
Crash after some seconds

### ISSUE THREAD

**Issue by bencz** [pgmodeler/pgmodeler#1399]
**Bug description**
I followed the Windows build instructions, presented on this site, [](https://pgmodeler.io/support/installation)
PgModeler compiles successfully, when I run the program, after a few seconds an error occurs and the program closes, even though I didn't do anything, just open the program

One detail, When I execute the qmake, I got this warning:
`C:/msys32/mingw32/share/qt5/mkspecs/common/windows-vulkan.conf:1: Cannot find feature windows_vulkan_sdk`

**How to reproduce**
clone the PgModeler
clone the Plugins
Download the Msys2 for x64, install the packages ( the same of the installation instructions ), change the variables on *.pri file and build the program...

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager: Explorer
 - pgModeler version: 0.9.2
 - Qt version: 5.14.1

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```
** pgModeler crashed after receive signal: 11 **

Date/Time: 2020-02-19 11:20:43 
Version: 0.9.2 
Build: 20200219 
Compilation Qt version: 5.14.1
Running Qt version: 5.14.1
```

**Comment by bencz** [comment]
This warning too, when execute the qmake:

`WARNING: Failure to find: obj/windows_ico.qrc
`

**Comment by bencz** [comment]
On console, I got this error:

```
$ ./pgmodeler.exe
Exception code=0xc0000005 flags=0x0 at 0x000000006D2169FC. Access violation - attempting to read data at address 0x0000000000000018

```

**Comment by rkhaotix** [comment]
This is a bug that only happens when compiling pgModeler 0.9.2 and below using Qt 5.14. 

There's a workaround that is open the pgmodeler.conf file and set to false the option ```check-updates```. I'll provide a quick fix for the code so it can compile without problem.

**Comment by rkhaotix** [comment]
Update your source with the yesterday's commit which fixes the problem.

**Comment by Bluebottle-new** [comment]
I already used the new sources (verified that by looking at the file libpgmodeler_ui/src/updatenotifierwidget.cpp).

The workaround of setting check-updates to false doesn't work as well.
