### ISSUE TITLE
How to disable the alternating gray stripes on object tree and data grids?

### ISSUE THREAD

**Issue by gwideman** [pgmodeler/pgmodeler#1402]
pgModeler looks pretty promising, but I can't use it for the frustratingly trivial reason that the object tree, the property grid, and all data grids are covered in zebra stripes -- that is every other row has a gray background. (aka "graybar").  And worse, when scrolled, these UI areas turn into flashing monstrosities as the grey and white areas rapidly trade places, liable to prompt an epileptic seizure. (And I'm not exaggerating here.)

How do I turn the gray bars off and just get normal white (or any other color than stripes) background on the object tree and data grids?

Thanks.

**Comment by rkhaotix** [comment]
Hi @gwideman 

Your concern is valid, I don't think you're exaggerating. For now, there's no way to change the rendering of grid/trees in pgModeler. But we can make it optional in the settings in future releases.

Have you tried to change you system's color scheme to a darker one to see if the effect diminishes?

**Comment by gwideman** [comment]
Hi Raphael -- thanks for your speedy reply. I am glad to hear you are open to providing an option for a more-standard style for these UI element. I am not very inclined to start fiddling with my Windows color-scheme, because I use many software packages and don't want to discover problems in on others.  But sadly, this is no longer an issue. Despite pgModeler seeming to have many interesting  features, I note that the diff and sync area (which I most need at the moment) is at experimental stage, and indeed pgModeler just crashed and disappeared without warning while trying to reverse engineer a database. So I think it is not yet ready for intensive use, unfortunately. But I am interested to see where it goes in the future!
