### ISSUE TITLE
Add "bulk replace" feature

### ISSUE THREAD

**Issue by titoshadow** [pgmodeler/pgmodeler#1403]
**Feature description**
It's currently impossible to do a replacement of some strings (table names, field names, relations ...), although its possible to "Find" them.
Would be helpful to have a "Replace" function attached to the "Find" panel, allowing users to make bulk replacement -thus being able to rename items massively-.

**Sample image**
![imagen](https://user-images.githubusercontent.com/8121774/75451880-92f61a00-5971-11ea-8571-f2de4df61d98.png)

**Additional info**
This would imply some improvement like the one proposed on #508, but more extensive for each thing able to being located through "Find" panel

**Comment by rkhaotix** [comment]
The current implementation only allows bulk renaming. Other bulk replacements may be added in the future.
