### ISSUE TITLE
Recent Models -> Clear Menu does not remove items

### ISSUE THREAD

**Issue by btroia** [pgmodeler/pgmodeler#1408]
**Bug description**
Recent Projects history list in menu always persists. Unable to permanently clear.

**How to reproduce**
After clearing the Recent Projects history via `Recent Models`->`Clear Menu` menu, then quitting and restarting pgModeler, the menu history still persists

**Expected behavior**
Selecting `Clear Menu` should permanently clear the menu history.

**Screenshots**
<img width="578" alt="screnshot" src="https://user-images.githubusercontent.com/368747/76126561-65dae480-5fcd-11ea-8f38-64bb7d63e527.png">

**Info about your desktop**
 - OS: MacOS
 - Version: 10.15.1
 - Window manager:
 - pgModeler version: v0.9.2 build 20200106 Qt 5.12.3
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by DickBoffin** [comment]
I have this behavior on the current 1.1.5 on Windows 11.
I compiled myself, have the app in c:\pgmodeler and the dir has "modify" for "users".
I see the same on my laptop with Windows 10.
