### ISSUE TITLE
Long foreign key names with appended number change on apply

### ISSUE THREAD

**Issue by molexx** [pgmodeler/pgmodeler#1412]
**Bug description**
When a relationship generates a foreign key with a really long name (longer than 62 chars?) the generated fk's name ends with a number. When you open the relationship and hit 'apply' without making any changes that number can change.

This causes generated diffs to keep dropping/creating the same foreign key unnecessarily.

**How to reproduce**
See example model with two tables with long names and a one-to-many relationship between them. Open the master table and look at the constraints, note the number at the end of the constraint name.
Close the master table. Double-click the relationship, do nothing but click 'apply'. Open the master table again and check the constraint name - the number at the end will have changed.

[test_long_fk_name.dbm.zip](https://github.com/pgmodeler/pgmodeler/files/4320160/test_long_fk_name.dbm.zip)

**Expected behavior**
A foreign key's name does not change unless the user specifically changes it or anything in the pattern that autogenerates it.

**Info about your desktop**
 - OS: Linux
 - Version: Ubuntu
 - Window manager:KWin
 - pgModeler version: 0.9.2
 - Qt version: 5.7.1

**Comment by rkhaotix** [comment]
Hi! My question for you is: do really need such long names? You can workaround this naming issues by using fixed name patterns for generated fks.

Another option is uncheck "Recreate only unmodifiable objects" in diff options. This way pgModeler will stop trying recreate the same fks over and over everytime you run a diff.

**Comment by molexx** [comment]
No, I don't need such long names, but it happens automatically when a relationship is created with two tables with long names. In this case I can workaround by editing the pattern.

But it is unexpected behaviour and confused me somewhat.
I expect in 3 months time I will create a similar scenario and have completely forgotten about this behaviour and confuse myself again! 
Worse, I might not notice in the diff or in the test environment and apply it to production causing a delay whilst it rebuilds the FK.
If I enable "Recreate only unmodifiable objects" (I hadn't noticed this, thanks, I'll test it out) then it'll still rename the FK randomly which is unnecessary. We prefer to keep the diffs as small and clean as possible.

I guess there is some code that determines that the name is going to be truncated and so puts in a number for uniqueness - that's great please could it not update that number? :-)

**Comment by rkhaotix** [comment]
> I guess there is some code that determines that the name is going to be truncated and so puts in a number for uniqueness - that's great, but please could it not update that number?

Yes, I can adjust the algorithm to avoid changing the number when there's the need to truncate the object's name. I was just curious about your scenario.
