### ISSUE TITLE
I am getting this error, creating mac electron App from ubuntu

### ISSUE THREAD

**Issue by sagarbest1** [pgmodeler/pgmodeler#1414]
Process: webhook-electron [5638]
Path: /Volumes/VOLUME/*/webhook-electron.app/Contents/MacOS/webhook-electron
Identifier: com.electron.webhook-electron
Version: 1.0.0 (1.0.0)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: webhook-electron [5638]
User ID: 501

Date/Time: 2020-03-17 12:04:27.614 +0530
OS Version: Mac OS X 10.15.3 (19D76)
Report Version: 12
Anonymous UUID: E8D57AC3-5578-30EC-649C-CB398CA00349

Sleep/Wake UUID: 185536B7-2C54-4957-9D65-86D53955D359

Time Awake Since Boot: 90000 seconds
Time Since Wake: 870 seconds

System Integrity Protection: enabled

Notes: Translocated Process

Crashed Thread: 0

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Reason: DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: /Volumes/VOLUME/*/webhook-electron.app/Contents/MacOS/webhook-electron
Reason: image not found

Binary Images:
0x10712a000 - 0x10712aff3 +com.electron.webhook-electron (1.0.0 - 1.0.0) /var/folders/*/webhook-electron.app/Contents/MacOS/webhook-electron
0x10dfbc000 - 0x10e04ccb7 dyld (733.8) /usr/lib/dyld

Model: MacBookPro9,2, BootROM 230.0.0.0.0, 2 processors, Dual-Core Intel Core i5, 2.5 GHz, 6 GB, SMC 2.2f44
Graphics: kHW_IntelHD4000Item, Intel HD Graphics 4000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x0198, 0x393930343334322D3031382E413030472020

**Comment by rkhaotix** [comment]
Sorry, but what this has to do with pgModeler project?
