### ISSUE TITLE
How do I update an existing install?

### ISSUE THREAD

**Issue by GollyJer** [pgmodeler/pgmodeler#1416]
### ?

<img src="https://user-images.githubusercontent.com/689204/77832285-27c77100-70f2-11ea-8a9d-007b96109a15.png" width=600>

**Comment by rkhaotix** [comment]
Qt Installer Framework doesn't accept installation overwrites. You have to uninstall the older version before install the newer pgModeler. You'll not lose pgModeler settings because they are stored in a different path.

**Comment by rkhaotix** [comment]
This limitation is something quite discussed and a fix requested in Qt forums.

**Comment by GollyJer** [comment]
@rkhaotix Excellent. Thanks. Losing settings was the main issue. I know I could save them and then overwrite them back myself but knowing they aren't deleted in an uninstall is reassuring. 👍
