### ISSUE TITLE
Auto-update existing installations

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1419]
**Feature description**
Auto-update existing installations without requiring manual deinstallation. On Windows.

**Sample image**
![image](https://user-images.githubusercontent.com/1658949/78249710-17970380-74ef-11ea-8d72-fff7553b01ae.png)

**Comment by rkhaotix** [comment]
Hi @oliversalzburg 

This is a limitation of the Qt installer framework. This is heavily discussed and a fix being frequently asked to Qt development team.

**Comment by oliversalzburg** [comment]
Oh I see. I'll surely forget it and ask again in a year :D
