### ISSUE TITLE
Crash on osx

### ISSUE THREAD

**Issue by phate82** [pgmodeler/pgmodeler#1420]
Hi,

I have used pgmodeler for months. I downloaded the source code, compiled it and installed the application in osx successfully. Unfortunately, after updating osx to the 10.14.6 version, pgmodeler stopped working. If I launch the app, it crashes with the error "Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib". Can you help me for fixing the problem?
Thanks in advance

pgmodeler version: 0.9.2

**Comment by rkhaotix** [comment]
I need more details. But I suspect that libssl was moved to another place in your system or the library is corrupted.

Anyway, if you post more details here can help.

**Comment by phate82** [comment]
thanks for your quick answer!
I don't know how I can give you more details. The only thing I can post is the system report about the crash.
Anyway, I visited the /usr/local/opt/openssl/lib/ directory and I found the libssl.1.1.dylib lib file. So  I think the problem is the lib version. Is there a solution in your opinion? Thanks

**Comment by phate82** [comment]
no ideas? :(

**Comment by phate82** [comment]
ok..I brutally solved the problem. I found the old versions of the required libraries and copied them manually in the target directory.
For who is interested in, I found the libraries at this link:

https://github.com/zoom/zoom-sdk-macos/tree/master/ZoomSDK
