### ISSUE TITLE
Failure to find: obj/windows_ico.qrc -- pgmodeler.exe does not exist

### ISSUE THREAD

**Issue by AndeVandenberg** [pgmodeler/pgmodeler#1424]
Noobie here,

Building pgmodeler keeps getting stuck here:
`
$ qmake -r CONFIG+=release PREFIX=C:/pgmodeler pgmodeler.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libutils/libutils.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libparsers/libparsers.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libpgmodeler/libpgmodeler.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libpgconnector/libpgconnector.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libobjrenderer/libobjrenderer.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui/libpgmodeler_ui.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/crashhandler/crashhandler.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/main-cli/main-cli.pro
Reading C:/msys64/home/Andre/pgmodeler-0.9.2/main/main.pro
C:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf:1: Cannot find feature windows_vulkan_sdk
Project WARNING: Plugins subproject C:/msys64/home/Andre/pgmodeler-0.9.2/plugins/plugins.pro wasn't found! pgModeler will be build without plugins.
Project WARNING: Make sure to clone https://github.com/pgmodeler/plugins inside pgModeler's root folder and rerun qmake.
WARNING: Failure to find: obj/windows_ico.qrc
`

and then when running _windeployqt_
`
Andre@Andre MINGW64 /c/pgmodeler
$ windeployqt pgmodeler.exe pgmodeler_ui.dll
"pgmodeler.exe" does not exist.
`

Any suggestions are much appreciated.

Cheers,
Andre

**Comment by rkhaotix** [comment]
You have to run ```mingw32-make``` and ```mimgw32-make install``` before running ```windeployqt```

Are you following the official building instructions?

**Comment by AndeVandenberg** [comment]
Hi Raphael,

Yes, I am following the [official building instructions](https://pgmodeler.io/support/installation) for windows.

**Platform specific requirements:** everything looks correct
**Tweaking the building script:** everything look correct
**Building the software:** from the root directory of the source code through MSYS2 minGW x64...

1. `qmake -r CONFIG+=release PREFIX=$INSTALLATION_ROOT pgmodeler.pro` with the $INSTALLATION_ROOT set to the desired location. A warning `Failure to find: obj/windows_ico.qrc`
2. `make`  seems to complete, results in these at completion:
```
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:693: pgmodeler_ui.dll] Error 1
make[2]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make[1]: *** [Makefile:45: release] Error 2
make[1]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make: *** [Makefile:273: sub-libpgmodeler_ui-make_first-ordered] Error 2
```
3. `make install` also seems to complete, results in:
```
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:693: pgmodeler_ui.dll] Error 1
make[2]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make[1]: *** [Makefile:55: release-install] Error 2
make[1]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make: *** [Makefile:297: sub-libpgmodeler_ui-install_subtargets-ordered] Error 2
```
4. from the install folder, I am having trouble running windeployqt
```
$ windeployqt pgmodeler.exe pgmodeler_ui.dll
"pgmodeler.exe" does not exist.
```
This is what is in the install folder:
```
Andre@Andre MINGW64 /c/pgmodeler
$ ls
libobjrenderer.dll.a  libparsers.dll.a  libpgconnector.dll.a  libpgmodeler.dll.a  libutils.dll.a  objrenderer.dll  parsers.dll  pgconnector.dll  pgmodeler.dll  utils.dll

```
 
Thanks for your time,
Andre

**Comment by rkhaotix** [comment]
Can you post the entire build log? That warning about windows_ico.qrc would not break the build process

**Comment by AndeVandenberg** [comment]
Absolutely; here's the entire build log, attached.

[pgmodelerbuildlog.txt](https://github.com/pgmodeler/pgmodeler/files/4489090/pgmodelerbuildlog.txt)

Andre

**Comment by rkhaotix** [comment]
Here's your first error (which probably broke the entire process):

```C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: obj/modelsdiffhelper.o:modelsdiffhelper.cpp:(.rdata$.refptr._ZN10Attributes10SearchPathE[.refptr._ZN10Attributes10SearchPathE]+0x0): undefined reference to `Attributes::SearchPath'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile.Release:693: pgmodeler_ui.dll] Error 1
make[2]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make[1]: *** [Makefile:45: release] Error 2
make[1]: Leaving directory '/home/Andre/pgmodeler-0.9.2/libpgmodeler_ui'
make: *** [Makefile:273: sub-libpgmodeler_ui-make_first-ordered] Error 2```

Specially this:

```mingw32/bin/ld.exe: obj/modelsdiffhelper.o:modelsdiffhelper.cpp:(.rdata$.refptr._ZN10Attributes10SearchPathE[.refptr._ZN10Attributes10SearchPathE]+0x0): undefined reference to `Attributes::SearchPath'```

What is strange to me is that this attribute is not used anymore in the 0.9.2 code. Did you cloned the repository before compile? Which branch are you using? Tested the compilation here on Windows and it runs pretty fine. 🤔

**Comment by AndeVandenberg** [comment]
Hi again Raphael,

0.9.3-alpha worked! 

Thank you so much for your time and instructions. 
Andre

**Comment by rkhaotix** [comment]
Great! You're welcome. 😁

**Comment by Maylle** [comment]
Hi,
I have the same problem. Please could you help me?

$ qmake -r CONFIG+=release PREFIX=c:pgmodeler pgmodeler.pro
Reading C:/pgmodeler-0.9.3-alpha/libutils/libutils.pro
Reading C:/pgmodeler-0.9.3-alpha/libparsers/libparsers.pro
Reading C:/pgmodeler-0.9.3-alpha/libpgmodeler/libpgmodeler.pro
Reading C:/pgmodeler-0.9.3-alpha/libpgconnector/libpgconnector.pro
Reading C:/pgmodeler-0.9.3-alpha/libobjrenderer/libobjrenderer.pro
Reading C:/pgmodeler-0.9.3-alpha/libpgmodeler_ui/libpgmodeler_ui.pro
Reading C:/pgmodeler-0.9.3-alpha/plugins/plugins.pro
 Reading C:/pgmodeler-0.9.3-alpha/plugins/dummy/dummy.pro
 Reading C:/pgmodeler-0.9.3-alpha/plugins/xml2object/xml2object.pro
Reading C:/pgmodeler-0.9.3-alpha/crashhandler/crashhandler.pro
Reading C:/pgmodeler-0.9.3-alpha/main-cli/main-cli.pro
Reading C:/pgmodeler-0.9.3-alpha/main/main.pro
WARNING: Failure to find: obj/windows_ico.qrc
WARNING: Failure to find: obj/windows_ico.qrc
WARNING: Failure to find: obj/windows_ico.qrc
WARNING: Failure to find: obj/windows_ico.qrc

** pgModeler build details **

  PREFIX        = c:pgmodeler
  BINDIR        = c:pgmodeler
  PRIVATEBINDIR = c:pgmodeler
  PRIVATELIBDIR = c:pgmodeler
  PLUGINSDIR    = c:pgmodeler/plugins
  SHAREDIR      = c:pgmodeler
  CONFDIR       = c:pgmodeler/conf
  DOCDIR        = c:pgmodeler
  LANGDIR       = c:pgmodeler/lang
  SAMPLESDIR    = c:pgmodeler/samples
  SCHEMASDIR    = c:pgmodeler/schemas

* To change a variable value run qmake again setting the desired value e.g.:
  > qmake PREFIX+=/usr/local -r pgmodeler.pro

* Proceed with build process by running:
  >  make && make install

**Comment by PowerUser1234** [comment]
-I am following the official Windows build instructions, and am getting the same build errors as the first person here.
-I have posted at [https://github.com/pgmodeler/pgmodeler/issues/1599](https://github.com/pgmodeler/pgmodeler/issues/1599)
-I have tried the latest stable version, 0.9.3, and an even later version, 0.9.4-beta.  I have also downloaded
the contents of the plugins folder from github, just as the msys2 error message told me.
-I have been unable to make any more progress, although the person here claims success via source code version 
0.9.3-alpha.  However I can't locate on the internet, anywhere, where to download a .zip or .tar file containing
this particular version.

Can someone in the know please reply to me, and point me in the correct direction, please?

**Comment by MauricioPG** [comment]
Copy windows_ico.* from

 C:\msys64\home\pgmodeler\main\res to C:\msys64\home\pgmodeler\main\obj

and from

C:\msys64\home\pgmodeler\crashhandler\res to C:\msys64\home\pgmodeler\crashhandler\obj
