### ISSUE TITLE
Support for postgres 12 generated columns

### ISSUE THREAD

**Issue by nbsoftware** [pgmodeler/pgmodeler#1425]
It would be great to add support for new generate columns available in postgres 12. (cf https://www.postgresql.org/docs/12/ddl-generated-columns.html)

For now, in the importing process, pgModeler imports the generated expression as a default value expression and, should the expression be a bit lengthy, is not displaying it entirely.

Moreover, if I save the model and close it, even though it has passed validation, it won't reopen and the fix process fails.

**Comment by nbsoftware** [comment]
Thank you very much for this.

FYI, in my use case the expression is quite long and doesn't display nicely in the one line entry field, as shown in the screen copies.

<img width="359" alt="Screenshot 2020-04-25 at 19 17 37" src="https://user-images.githubusercontent.com/1502008/80314866-77ce4c00-87f4-11ea-9b39-e9a82d817e82.png">

<img width="505" alt="Screenshot 2020-04-25 at 19 17 46" src="https://user-images.githubusercontent.com/1502008/80314871-7c930000-87f4-11ea-8ddc-57ad561d7026.png">

**Comment by rkhaotix** [comment]
No problem, I can adjust the size of the field to fit long expressions.
