### ISSUE TITLE
not able to update the comment field for a FK

### ISSUE THREAD

**Issue by wirshad00** [pgmodeler/pgmodeler#1427]
Hi,

I am trying to update the comment field for all the columns in a table in order to generate a data dictionary, however I am unable to update the comment fields for the columns that are foreign key in the table. Is there a way to add comments for foreign keys? 

Appreciate your support.

Regards,

wirshad

**Comment by rkhaotix** [comment]
If the Fk was generated by a relationship there's no way to edit it directly. 

I'm working on a experimental feature where one is able to convert that relationship generated objects in such way that they can be edited. See this demonstration video:

https://youtu.be/Ldx1iCx74BA

**Comment by wirshad00** [comment]
Thank you for the quick response Raphael. I will wait for the new feature
in next release.
