### ISSUE TITLE
Crash, In Design mode

### ISSUE THREAD

**Issue by XIYO** [pgmodeler/pgmodeler#1430]
![image](https://user-images.githubusercontent.com/27078637/81496136-4d01ee80-92f0-11ea-9c3a-850a1b44a6e9.png)

**Bug description**
Im just import my EC2 postgresql 10, Create by spring boot.

**pgModeler version 9.2

Windwos 10 1903, (OS 18362.778), Korean

**Comment by XIYO** [comment]
Oh! fix it!.
Settings - Appearance - Font - Consolas

gulim (korean font) -> Consolas

**Comment by rkhaotix** [comment]
This seems to be a bug in Qt framework. This is the second issue regarding Korean fonts. Anyway, I will see what I can do for pgModeler
