### ISSUE TITLE
Can't import schema from pg 12 

### ISSUE THREAD

**Issue by bvthomsen** [pgmodeler/pgmodeler#1431]
When trying to import a existing schema I get the following error:

**Could not execute the SQL command.
 Message returned: `ERROR:  column reference "oid" is ambiguous
LINE 3: ) UNION (SELECT 5 AS object_type,  rl.oid, rl.rulename AS na...**
                                           ^
the error originates in : src/databaseimporthelper.cpp (149) 

The only difference from a standard installation is that the database server runs on port 5436, not 5432.

**Version info: OS: Windows 8.1 64 bit, DB: Postgres 12 64 bit, PG Modeler ver. 9.2))**

If I transfer the schema to a Postgres ver. 11 server, the import function works as expected.

![Udklip](https://user-images.githubusercontent.com/1866520/81920491-8e88e700-95d9-11ea-852b-967aacf47e43.PNG)

**Comment by rkhaotix** [comment]
Is it possible to share the database dump ? I need to investigate that.

**Comment by bvthomsen** [comment]
[pg12bck.zip](https://github.com/pgmodeler/pgmodeler/files/4628311/pg12bck.zip)
I've sendt you a mail with the same dump (Before I found the method of zipping before uploading a file to a GitHub issue)

**Comment by rkhaotix** [comment]
Thanks! I'll work on it.

**Comment by rkhaotix** [comment]
Do you have a minimal test case? I'm getting errors trying to restore this dump.

**Comment by bvthomsen** [comment]
I have a sql script that will create the schema in an otherwise empty database.
You'll have to have the postgis extension installed as some of the tables are using a field type "geometry" that depends on the postgis extension. You migth simply delete the "geometry" field definition from the tables. But then it might be the presence of the extension that causes the problem....
[plotcut_temlate.zip](https://github.com/pgmodeler/pgmodeler/files/4632661/plotcut_temlate.zip)

**Comment by rkhaotix** [comment]
I finally got the dump restored to a PostgreSQL 12.2 and imported it correctly in pgModeler 0.9.2, 0.9.3-alpha and 0.9.3-alpha1 (under development). The attached model is the one generated in the lastest version.

[pg12bck_model.zip](https://github.com/pgmodeler/pgmodeler/files/4634951/pg12bck_model.zip)

**Comment by bvthomsen** [comment]
Sorry for being late answering the comment.
However: Updating from 9.2 alpha1 to 9.2 final solved the problem. Sorry for the noise !
Regards Bo Victor Thomsen

**Comment by amro17** [comment]
> Updating from 9.2 alpha1 to 9.2 final solved

How can I update to the latest version please on a window is there a command I run?

thank you

**Comment by bvthomsen** [comment]
[https://pgmodeler.io/download](url)
