### ISSUE TITLE
Cannot create aggregation with `double precision` argument as a parameter of transition function

### ISSUE THREAD

**Issue by cloud-rocket** [pgmodeler/pgmodeler#1442]
The following example is generated by pgModeler and it is not supported by PostgreSQL 

```
CREATE AGGREGATE agg_lag (double precision,integer,anyelement) (
	SFUNC = agg_lag_trans(anyarray,double precision,integer,anyelement),
	STYPE = anyarray
	,FINALFUNC = agg_lag_final(anyarray)
);

```
The error is:

```
ERROR:  syntax error at or near ","
LINE 2: ... = agg_lag_trans(anyarray,double precision,integer,a...
```

Because for some reason PostgreSQL is not supporting `double precision` as a specified argument to transition function (maybe PostgreSQL bug).

There should be an option pgModeler to prevent specifying arguments of transition/final functions. I.e. like the following:

```
CREATE AGGREGATE agg_lag (double precision,integer,anyelement) (
	SFUNC = agg_lag_trans,
	STYPE = anyarray
	,FINALFUNC = agg_lag_final
);

```

**Comment by rkhaotix** [comment]
No, that's a pgModeler bug. Instead of informing only the name of the function the "signature" (combination of name plus the parameters types) is being provided which, of course, is invalid. I'll flag this as bug and provide the fix. Thanks for that.

**Comment by cloud-rocket** [comment]
@rkhaotix, I am not entirely sure it's a bug (since it looks like PostgreSQL does support providing full signature (maybe for the case when polymorphic functions are used). But indeed something weird is happening with "double precision" type......

**Comment by rkhaotix** [comment]
Yeah, you're right... I've made a simple replacement ```double precision``` -> ```numeric``` and the syntax was validated. Of course, the object itself wasn't created due to missing objects. Additionally, if I double quote the double precision like this ```"double precision"```  it also works. It seems that PostgreSQL obligates this.

**Comment by penguin86** [comment]
I'm not sure if this is the same issue: pgmodeler (v0.9.3) translates the following XML code:
```
<aggregate name="first_agg">
	<schema name="public"/>
	<role name="postgres"/>
	<comment><![CDATA[Returns the first non-NULL item]]></comment>
	<type name="anyelement" length="0" ref-type="state-type"/>
	<function ref-type="transition" signature="public.first_fun(anyelement,anyelement)"/>
</aggregate>
```
into the following SQL code:
```
-- object: public.first_agg | type: AGGREGATE --
-- DROP AGGREGATE IF EXISTS public.first_agg(*) CASCADE;
CREATE AGGREGATE public.first_agg (*) (
	SFUNC = public.first_fun(anyelement,anyelement),
	STYPE = anyelement
);
-- ddl-end --
ALTER AGGREGATE public.first_agg(*) OWNER TO postgres;
-- ddl-end --
COMMENT ON AGGREGATE public.first_agg(*) IS E'Returns the first non-NULL item';
-- ddl-end --
```
that doesn't appear to be a valid PostgreSQL code, leading to an "An aggregate using a polymorphic transition type must have at least one polymorphic argument." error.
I'd expect to obtain something like this following working code:
```
CREATE AGGREGATE public.first_agg (
	SFUNC = public.first_fun,
	BASETYPE = anyelement,
	STYPE = anyelement
);
```
Does it belong here or should I open another issue?
Thanks

**Comment by rkhaotix** [comment]
@penguin86 I think that they are similar problems... which is the malformed SQL code for aggregations. I'll check that.

**Comment by penguin86** [comment]
@rkhaotix Thank you very much!
Here you find the bare minimum dbm to reproduce the issue and the sql file it produces when exported.
ATM I'm using Pgmodeler 0.9.3 and exporting for PostgreSQL 13.
[issue-1442-example.zip](https://github.com/pgmodeler/pgmodeler/files/6276919/issue-1442-example.zip)

**Comment by rkhaotix** [comment]
@penguin86  Thanks! I'll try to solve this issue still before the launching of the next snapshot of 0.9.4-alpha.

**Comment by rkhaotix** [comment]
@penguin86 After testing the database model that you provided, I found that the problem is that you forgot to add ```anyelement``` as the input data type of the aggregate. I was reading the PostgreSQL docs again, at the [aggregate example section](https://www.postgresql.org/docs/current/xaggr.html), and found the following:

> the aggregate function itself can be specified with polymorphic **input type(s)** and **state type**, allowing a single aggregate definition to serve for multiple input data types. Here is an example of a polymorphic aggregate:

```sql
CREATE AGGREGATE array_accum (anyelement)
(
    sfunc = array_append,
    stype = anyarray,
    initcond = '{}'
);
```

After adding ```anyelement``` as input type for the aggregate I could successfully create that object.

**Comment by penguin86** [comment]
@rkhaotix Thank you very much, I'm sorry I didn't find the error before posting here!
Have a nice day!

**Comment by rkhaotix** [comment]
@penguin86 No problem! :)

Feel free to ask anything when needed.

A nice day for you too.

**Comment by rkhaotix** [comment]
@cloud-rocket first of all, sorry for the delay in working on this problem.... Well, I think that the problem is now solved. After studying a lot the problem I decided to remove the arguments from the functions attached to the aggregate instead of working on a fix to make the functions be used in signature format... it would break other portions of the software so I opted by the simplest solution, and let PostgreSQL decide which function to use. :)
