### ISSUE TITLE
Any tips for this error?

### ISSUE THREAD

**Issue by sygecom** [pgmodeler/pgmodeler#1446]
Any tips to avoid this error when compiling PLUGIN together on windows?

mingw32-make[2]: Leaving directory 'D:/devel/projetos_git/pgmodeler/libpgmodeler_ui'
mingw32-make[1]: Leaving directory 'D:/devel/projetos_git/pgmodeler/libpgmodeler_ui'
cd plugins\ && ( if not exist Makefile D:\devel\qt5xhb\qt\bin\qmake.exe -o Makefile D:\devel\projetos_git\pgmodeler\plugins\plugins.pro "PREFIX+=D:/pgModeler" -spec win32-g++ "CONFIG+=release" ) && mingw32-make -f Makefile
mingw32-make[1]: Entering directory 'D:/devel/projetos_git/pgmodeler/plugins'
cd dummy\ && ( if not exist Makefile D:\devel\qt5xhb\qt\bin\qmake.exe -o Makefile D:\devel\projetos_git\pgmodeler\plugins\dummy\dummy.pro "PREFIX+=D:/pgModeler" -spec win32-g++ "CONFIG+=release" ) && mingw32-make -f Makefile
mingw32-make[2]: Entering directory 'D:/devel/projetos_git/pgmodeler/plugins/dummy'
mingw32-make -f Makefile.Release
mingw32-make[3]: Entering directory 'D:/devel/projetos_git/pgmodeler/plugins/dummy'
g++ -c -fno-keep-inline-dllexport -DHAVE_STRUCT_TIMESPEC -O2 -std=gnu++1y -Wextra -Wall -W -fexceptions -mthreads -frtti 
-DUNICODE -D_UNICODE -DBUILDNUM=\"20200611\" -DBINDIR=\"D:/pgModeler\" -DPLUGINSDIR=\"D:/pgModeler/plugins\" -DPRIVATEBINDIR=\"D:/pgModeler\" -DCONFDIR=\"D:/pgModeler/conf\" 
-DDOCDIR=\"D:/pgModeler\" -DLANGDIR=\"D:/pgModeler/lang\" -DSAMPLESDIR=\"D:/pgModeler/samples\" -DSCHEMASDIR=\"D:/pgModeler/schemas\" -DQT_NO_DEBUG -DQT_PLUGIN 
-DQT_PRINTSUPPORT_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. 
-ID:\pgsql10_32bits\include -I..\..\..\..\libxml2-2.9.1-win32-x86\include\libxml2\libxml -I..\..\libpgmodeler_ui 
-I..\..\libpgmodeler_ui\src -I..\..\libobjrenderer\src -I..\..\libpgconnector\src -I..\..\libpgmodeler\src 
-I..\..\libparsers\src -I..\..\libutils\src -I..\..\..\..\qt5xhb\qt\include -I..\..\..\..\qt5xhb\qt\include\QtPrintSupport -I..\..\..\..\qt5xhb\qt\include\QtSvg 
-I..\..\..\..\qt5xhb\qt\include\QtUiTools -I..\..\..\..\qt5xhb\qt\include\QtWidgets -I..\..\..\..\qt5xhb\qt\include\QtGui -I..\..\..\..\qt5xhb\qt\include\QtANGLE 
-I..\..\..\..\qt5xhb\qt\include\QtNetwork -I..\..\..\..\qt5xhb\qt\include\QtCore -Imoc -I..\..\..\..\qt5xhb\qt\mkspecs\win32-g++  -o obj\dummy.o src\dummy.cpp
In file included from ..\..\libparsers\src/schemaparser.h:28:0,
                 from ..\..\libpgmodeler\src/baseobject.h:30,
                 from ..\..\libpgmodeler\src/databasemodel.h:33,
                 from ..\..\libpgmodeler_ui\src/modelwidget.h:29,
                 from ..\..\libpgmodeler_ui\src/pgmodelerplugin.h:28,
                 from src\dummy.h:28,
                 from src\dummy.cpp:19:
..\..\libutils\src/globalattributes.h: In constructor 'Dummy::Dummy()':
..\..\libutils\src/globalattributes.h:61:3: error: 'QString GlobalAttributes::PluginsDir' is private
   PluginsDir,
   ^
src\dummy.cpp:31:25: error: within this context
       GlobalAttributes::PluginsDir +
                         ^
Makefile.Release:1457: recipe for target 'obj/dummy.o' failed
mingw32-make[3]: *** [obj/dummy.o] Error 1
mingw32-make[3]: Leaving directory 'D:/devel/projetos_git/pgmodeler/plugins/dummy'
Makefile:36: recipe for target 'release' failed
mingw32-make[2]: *** [release] Error 2
mingw32-make[2]: Leaving directory 'D:/devel/projetos_git/pgmodeler/plugins/dummy'
Makefile:41: recipe for target 'sub-dummy-make_first-ordered' failed
mingw32-make[1]: *** [sub-dummy-make_first-ordered] Error 2
mingw32-make[1]: Leaving directory 'D:/devel/projetos_git/pgmodeler/plugins'
Makefile:307: recipe for target 'sub-plugins-make_first-ordered' failed
mingw32-make: *** [sub-plugins-make_first-ordered] Error 2

D:\devel\projetos_git\pgmodeler>

**Comment by thomascjohnson** [comment]
In ```plugins/dummy/src/dummy.cpp``` change ```GlobalAttributes::PluginsDir``` to ```GlobalAttributes::getPluginsDir()```

:)

**Comment by sygecom** [comment]
thanks ️
