### ISSUE TITLE
[Question] Does pgModeler support Wayland ?

### ISSUE THREAD

**Issue by RuiBaiXYZ** [pgmodeler/pgmodeler#1448]
Upgraded to CentOS 8.2.2004 , default display server protocol was Wayland.

According to [Wayland and Qt](https://doc.qt.io/qt-5/wayland-and-qt.html), does pgModeler support this display server rpotocol?

**Comment by rkhaotix** [comment]
I never tested it, to be honest.

**Comment by RuiBaiXYZ** [comment]
Thanks for your reply.
