### ISSUE TITLE
Relationship appearance : connect pk-fk + pagination causes bug

### ISSUE THREAD

**Issue by Maxzor** [pgmodeler/pgmodeler#1450]
![Capture d’écran de 2020-06-20 20-27-46](https://user-images.githubusercontent.com/16599683/85208955-876d9b00-b334-11ea-8154-7a39b1cd9ba0.png)
Often happens, when displaying pk-fk relation and toggling pagination.

**Comment by rkhaotix** [comment]
It happens to me when I use "FK to PK" connection mode and disabling curved lines. After collapsing all sections of a table the relationship "loses" the reference point where it was connected. The possible solution is to connect to the table's center point when the table is full collapsed.

**Comment by Maxzor** [comment]
I remember having code a snippet for the line to connect at the bottom of the column group if collapsed and col not in pagination.

**Comment by Maxzor** [comment]
Cannot confirm,
model changelog seems to need a bit more work, cannot move a table.

**Comment by rkhaotix** [comment]
Model changelog is not ready.

**Comment by Maxzor** [comment]
Right, nevermind, was a problem with a previous build.
On model changelog, rearranging objects over the canvas is now truly irreversible :< / :)
