### ISSUE TITLE
No properties are seen

### ISSUE THREAD

**Issue by AlexisK99** [pgmodeler/pgmodeler#1451]
Zooming the screen does not display the properties of the tables, but when you return to another size, they are displayed again.

pgModeler Version: 0.9.3-alpha1
QT Version: 5.15.0
Windows 10

![Captura de pantalla (700)](https://user-images.githubusercontent.com/55039048/85248131-f2df6780-b41d-11ea-8ac7-1b16b606cb12.png)
![Captura de pantalla (701)](https://user-images.githubusercontent.com/55039048/85248386-a5afc580-b41e-11ea-879b-505c766d742c.png)

**Comment by rkhaotix** [comment]
Please, see this discussion:
https://github.com/pgmodeler/pgmodeler/issues/1436

Closing this one since it's a duplicated subject.
