### ISSUE TITLE
Possible to track schema changes and create update scripts

### ISSUE THREAD

**Issue by hg2581** [pgmodeler/pgmodeler#1452]
Is it possible to keep track of schema changes and automatically create update scripts from one schema version to the next one? The application would be to allow automatic update of eg customer installations of databases.

**Comment by rkhaotix** [comment]
Are you talking about a diff tool? If so, pgModeler already does it. 

https://pgmodeler.io/support/docs/53-generate-differences-scripts?v=0.9.2

**Comment by hg2581** [comment]
Does it generate a SQL script that someone can use to update a database from one schema version to the next and so on, one step at a time?

**Comment by Maxzor** [comment]
exactly!
