### ISSUE TITLE
SQL export no longer creates schema.

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#1460]
**Bug description**
In previous versions, an SQL export would also create the necessary schema. This appears to have been broken in 0.9.3-beta.

It seems like the SQL code block that previous handled this is now commented out.

**How to reproduce**
Export a SQL file for a model that doesn't use the `public` schema.

**Expected behavior**
The schema is created.

**Screenshots**
![image](https://user-images.githubusercontent.com/1658949/87934425-4ed5f400-ca8f-11ea-9673-061f8acd73eb.png)

**Info about your desktop**
 - OS: Windows 10
 - Version: 2004
 - Window manager:
 - pgModeler version: 0.9.3-beta
 - Qt version:

**Comment by rkhaotix** [comment]
Nothing has changed from 0.9.3-alpha1 to 0.9.3-beta regarding schemas (see the image).... Maybe you disabled the SQL code for schema ```fm```? Can you provide more details?

<img width="550" alt="Screenshot_20200720_095104" src="https://user-images.githubusercontent.com/2205476/87939485-8e401880-ca6e-11ea-97f5-802f6d713efa.png">

**Comment by oliversalzburg** [comment]
I haven't made any intentional changes in that area. The SQL code is actually disabled, but I'm not allowed to make any changes to the schema properties:

![image](https://user-images.githubusercontent.com/1658949/87941610-aed29780-ca9b-11ea-8fd7-efec71cc7d4a.png)

**Comment by oliversalzburg** [comment]
Hmm, seems like the schema was actually created as `<schema name="fm" layer="0" protected="true" fill-color="#e1e1e1" sql-disabled="true">`. After unprotecting it, I could enable the SQL code and everything is working as expected.

Not sure how this apparently worked previously, but our author probably had different intentions. Not a bug anyway. Feel free to close.
