### ISSUE TITLE
last double quote in default value for json column is not converted to &quote; in .dbm file

### ISSUE THREAD

**Issue by pnhgithub** [pgmodeler/pgmodeler#1465]
Using the 0.9.3-beta version of pgmodeler.

The issue occurs when saving a model containing json columns with default values. The error is in the XML formatting of the default-value attribute of the column elements in the output .dbm file.

If the column's default value string contains double quotes (as used when specifying a json object), the expectation is that all double quote characters in the json string are replaced with &quote; in the output XML format.

The current behavior is that if there are multiple values in the json string, then all but the last of the double quotes in the json string are replaced with &quote;. If only a single json value then the output is correct.

Following is a sample:

Note1: the columns in question are named current_aspect (second column) and current_brightness (seventh column). Look for an embedded " near the end of the default-value attribute.

Note2: column current_fault (sixth column) also uses json type, but the default string contains only one json value and is formatted correctly in the XML.

```XML
<table name="sign_state" layer="2" collapse-mode="1" max-obj-count="8" z-value="0">
        <schema name="&quot;JSS&quot;"/>
        <role name="jss"/>
        <position x="1760" y="620"/>
        <column name="sign_state_pk" not-null="true">
                <type name="integer" length="0"/>
        </column>
        <column name="current_aspect" not-null="true" default-value="'{&quot;sign_aspect&quot;: { &quot;message_no&quot;: 0, &quot;message_multi&quot;: &quot;" }}'::json">
                <type name="json" length="0"/>
        </column>
        <column name="aspect_source">
                <type name="text" length="0"/>
        </column>
        <column name="aspect_control_mode" not-null="true" default-value="0">
                <type name="integer" length="0"/>
        </column>
        <column name="out_of_service" not-null="true" default-value="False">
                <type name="bool" length="0"/>
        </column>
        <column name="current_fault" not-null="true" default-value="'{&quot;sign_fault&quot;: { }}'::json">
                <type name="json" length="0"/>
        </column>
        <column name="current_brightness" not-null="true" default-value="'{&quot;sign_brightness&quot;: { &quot;brightness_level&quot;: 0, &quot;brightness_mode&quot;: &quot;automatic" }}'::json">
                <type name="json" length="0"/>
        </column>
        <constraint name="sign_state_pkey" type="pk-constr" table="&quot;JSS&quot;.sign_state">
                <columns names="sign_state_pk" ref-type="src-columns"/>
        </constraint>
</table>
```

**Comment by rkhaotix** [comment]
Thanks @pnhgithub 

This is an important issue and I think I will change how default values are saved into the dbm file.
