### ISSUE TITLE
[0.9.2-alpha] Parsing error on string

### ISSUE THREAD

**Issue by Uthmordar** [pgmodeler/pgmodeler#1467]
Using the pgModeler cli 0.9.3-alpha.

The issue occurs when diffing two databases. A parsing error occurs on string containing some json-like formatted custom template.

Some samples:

### Case 1 (parsing failure):

`
create trigger custom_trigger
  after insert on custom_schema.custom_table
  for each row
  execute procedure custom_schema.create('{"id": "{{&new.user__id}}", "country": "{{&new.country__id}}", "email": "{{&new.email}}"}', '{{&new.created_at}}');
`
Produces the trace:
`
Entity: line 3: parser error : error parsing attribute name
{&amp;new.country__id}}\&quot;,\&quot;email\&quot;: \&quot;{{&amp;new.email}}\"

Entity: line 3: parser error : attributes construct error
{&amp;new.country__id}}\&quot;,\&quot;email\&quot;: \&quot;{{&amp;new.email}}\"

Entity: line 3: parser error : Couldn't find end of Start Tag trigger line 2
{&amp;new.country__id}}\&quot;,\&quot;email\&quot;: \&quot;{{&amp;new.email}}\" 

Entity: line 3: parser error : Extra content at the end of the document
{&amp;new.country__id}}\&quot;,\&quot;email\&quot;: \&quot;{{&amp;new.email}}\" 
`

In this case, the expectation is to have the string properly parsed.

### Case 2 (unexpected behavior):

`
create trigger custom_trigger
  after insert on custom_schema.custom_table
  for each row
  execute procedure custom_schema.create('{}', '{{&new.created_at}}');
`
In diff output, some unexpected double quote appears:
`
CREATE TRIGGER custom_trigger
	AFTER INSERT 
	ON custom_schema.custom_table
	FOR EACH ROW
	EXECUTE PROCEDURE custom_schema."create"('"{}"','"{{&new.created_at}}"');
`

In this case, the expectation is to have output without the double quotes added.

**Comment by rkhaotix** [comment]
For **case 1** it seems that this bug #1465 is also happening.

For **case 2** maybe it's a problem parsing the values coming from the system catalogs.

In both cases I need to make some inspections... Is it possible to create a small model which denotes the problems above? Thanks

**Comment by Uthmordar** [comment]
I composed a small model with the error cases, hope it suits you.

`
create schema iam;

create table iam.profile
(
  profile__id uuid primary key not null,
  email text not null unique,
  country__id varchar(2) default null,
  created_at timestamptz default now(),
  updated_at timestamptz,
  deleted_at timestamptz
);

create or replace function iam.create_event() returns trigger as $$
begin
  if tg_nargs != 2 then
    raise exception 'event_manager.create(payload_template jsonb|text, occurred_at text|timestamptz) requires a `payload_template` and an occured_at reference';
  end if;

  return new;
end;
$$ language plpgsql;

create trigger event__iam_profile_created
  after insert on iam.profile
  for each row
  execute procedure iam.create_event('{"id": "{{&new.profile__id}}", "country": "{{&new.country__id}}", "email": "{{&new.email}}"}', '{{&new.created_at}}');

create trigger event__iam_profile_updated
  after insert on iam.profile
  for each row
  execute procedure iam.create_event('{}', '{{&new.created_at}}');
`
