### ISSUE TITLE
Qt required components

### ISSUE THREAD

**Issue by Akioma9** [pgmodeler/pgmodeler#1468]
Hi, everyone ! 
The QT framework (+5.9.x) is a requirement to install Pgmodeler. The lighter version is Qt 5.9.9, with all the components, its about 12GB, as you can see on the image below:

![image](https://user-images.githubusercontent.com/62565551/89805184-a48c4200-db0b-11ea-8c1f-a66788451b8b.png)

Perhaps not all of these components are required for installation ? Can anyone tell me which components are these ?

**Comment by Maxzor** [comment]
Windows is a different beast with msys2 packages but you probably need only one : the compiler-specific. And sources if you want.

**Comment by rkhaotix** [comment]
@Maxzor actually he doesn't need to use that Qt installer. I'm supposing that you have used the one provided by qt.io. if you follow the installation instructions you'll see that is enough to use the package provided by msys2

**Comment by Akioma9** [comment]
When I readed for the first time the instructions, I thought the link to QT Framework in the requirements overview section was there to download it.
After a while, I did notice it doesn't needs to download the QT installer. The third command line of the section plataform requirements includes the package **mingw-w64-x86_64-qt5**. 

`pacman -S base-devel mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-postgresql mingw-w64-x86_64-qt5`
