### ISSUE TITLE
The object public.MyType (Type) [id: 4435] is being referenced by 2 object(s) before its creation.

### ISSUE THREAD

**Issue by HughMacdonald** [pgmodeler/pgmodeler#1470]
I created a table, and then later created a new type before adding the type as a field to the previously created table.

Can I force the type to be defined before the table? I'm relatively new to pgmodeler.

Thanks

**Comment by rkhaotix** [comment]
Use the model validation process...
https://pgmodeler.io/support/docs/67-model-validation?v=0.9.2

**Comment by HughMacdonald** [comment]
Thanks for the pointer, and the quick response 👍
