### ISSUE TITLE
pgmodeler and postgresql 13

### ISSUE THREAD

**Issue by hg2581** [pgmodeler/pgmodeler#1485]
I am currently running pgmodeler 0.9.0-alpha1 on CentOS but would like to upgrade my installation to postgresql 13. Which version of pgmodeler is compatible with this version of the database software? The one I am running is only compatible with version 9 up through 9.6.

**Comment by rkhaotix** [comment]
pgModeler 0.9.3-beta1 is where the support to PostgreSQL 13 started. But prior versions (0.9.3-alpha1 and above) can connect normally to that specific DB version with minor issues.

**Comment by crystal-wb** [comment]
I only have a license for pgModeler 0.9.1. Is it at all possible to use it with PostgreSQL 13?
