### ISSUE TITLE
How to define columns order in a primary key definition

### ISSUE THREAD

**Issue by gfgs58** [pgmodeler/pgmodeler#1489]
When I define a relationship from tableA to tableB (i.e. 1-to-many), the tableA pk is copied to the tableB pk, which already has another PK defined. So, tableB has a compound PK, let's call them id1 and id2.

If id1 is the PK of tableA, and id2 is the PK of tableB, the primary key in tableB is defined as (id2, id1). 
But I want it to be defined as PRIMARY KEY (id1, id2).

I could no find a way to change the order of the columns in the primary key definition.

pgModeler v0.9.2, in Arch Linux

Best regards,

**Comment by rkhaotix** [comment]
Unfortunately, you can't. If you want to change the columns' order in the pk you have to create manually the connection between the tables using foreign key constraint and on tableB create the PK with the columns you need.

**Comment by gfgs58** [comment]
OK. Thanks for the reply.
