### ISSUE TITLE
Why isn't it in Brew?

### ISSUE THREAD

**Issue by XIYO** [pgmodeler/pgmodeler#1490]
I used Google Translator.

I purchased a license from the official site.
So I would like to conveniently install and manage packages through Brew.

But brew doesn't have pgmodeler.
Is this not in "brew" because it is paid for and sold? Or is there another reason?

Thanks in advance to those who responded.

**Comment by rkhaotix** [comment]
First, thank you for your support!

I'm sorry, but paying for pgModeler doesn't mean that you'll have it in brew. I have created my own way to provide ready to use packages for those who pay for the tool.

**Comment by XIYO** [comment]
I used Google Translator.

@rkhaotix Thank you very much for replying.

I wasn't proficient in English, so I couldn't properly convey the meaning of the question. But I could see that there weren't enough conditions to add to "Brew" yet.
