### ISSUE TITLE
PG Modeler not opening on Mac OS Big Sur

### ISSUE THREAD

**Issue by charisra** [pgmodeler/pgmodeler#1494]
**Bug description**
PG Modeler is not opening/running since updating on MAC OS Big Sur

**How to reproduce**
Update a Mac machine on Big Sur

**Expected behavior**
PG Modeler to open

**Screenshots**
N/A

**Info about your desktop**
 - OS: Mac OS
 - Version: Big Sur (11.0.1 (20B29))
 - Window manager:
 - pgModeler version:  0.9.2
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
You did not provide enough info about the problem. Please, what is going on in details?

**Comment by charisra** [comment]
I had to delete the current installation and checked out the develop branch. That fixed it
