### ISSUE TITLE
New versions of libssl and libcrypto for the Dependencies?

### ISSUE THREAD

**Issue by dpellegrini** [pgmodeler/pgmodeler#1495]
I went through the build and install document and got down to the "Dependencies" section, where I ran into an issue: `can't open file: /Applications/pgmodeler.app/Contents/Frameworks/libssl.1.0.0.dylib (No such file or directory)`
Sure 'nuff, that file doesn't exist, and neither does `libcrypto.1.0.0.dylib`. However, I DO see `libssl.1.1.dylib` and `libcrypto.1.1.dylib`.
Should I proceed using the newer versions, or does it have to be the 1.0.0 versions? If the former, does that warrant an update to the documentation?

Thanks!
David

MacOS 10.15.7
pgModeler master branch
qt: stable 5.15.1
PostgreSQL 13.1

**Comment by rkhaotix** [comment]
@dpellegrini Yes, I have to update the docs.

It's safe to use the newer version of libssl and libcrypto.

The docs were written when the latest LTS version of Qt  was 5.12. I'm waiting the finishing of 0.9.3 (scheduled to December) the I will update the docs completely. :)

**Comment by dpellegrini** [comment]
OK, great. I made the changes and it ran, though I did get a couple warning like: 
`warning: changes being made to the file will invalidate the code signature in: /Applications/pgmodeler.app/Contents/Frameworks/libssl.1.1.dylib`
I assume that's harmless. :-D

David

**Comment by rkhaotix** [comment]
That's ok. pgModeler binaries aren't signed anyway :D
