### ISSUE TITLE
Mac OS preview model is dark shaded

### ISSUE THREAD

**Issue by M-Thirumal** [pgmodeler/pgmodeler#1496]
**Feature description**
Mac OS  model preview is dark shaded

**Sample image**
![Screenshot 2020-11-24 at 12 30 08 PM](https://user-images.githubusercontent.com/6417222/100059282-cd350f00-2e50-11eb-851c-d916d8193f5c.png)

Build from source.

**Comment by rkhaotix** [comment]
Which pgModeler version? 
Did you try to restore default settings in the appearances tab at pgModeler settings?

**Comment by M-Thirumal** [comment]
Yes, It's working. Thanks a lot
