### ISSUE TITLE
PgModeler is not opening on macOS Catalina

### ISSUE THREAD

**Issue by timkofu** [pgmodeler/pgmodeler#1502]
I downloaded 0.9.3 release demo a few minutes ago and when I try to open it i get this error:
<img width="424" alt="pgm_error" src="https://user-images.githubusercontent.com/509078/103356041-e91b7880-4ac0-11eb-9573-f55cc3863074.png">

**Comment by rkhaotix** [comment]
https://support.apple.com/en-us/HT202491

**Comment by cryptedx** [comment]
Really? Hold ctrl while opening and then click open.

**Comment by rkhaotix** [comment]
@cryptedx thanks! 😁 
I didn't know about that shortcut. 👍

**Comment by timkofu** [comment]
> Really? Hold ctrl while opening and then click open.

Worked. Thanks!
