### ISSUE TITLE
Release 0.9.3: color problem on table attributes toggler if a tag is associated with the table

### ISSUE THREAD

**Issue by equinton** [pgmodeler/pgmodeler#1503]
**Bug description**
Color for the table attribute toggler buttons is only black if a tag is associated with it. I tried to parameter the appearance, with no result.

**How to reproduce**

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
![image](https://user-images.githubusercontent.com/6715861/103548053-81d93c00-4ea5-11eb-84ae-bfca0a58ae4e.png)

Tables Request, dbversion or dbparam don't have any associated tags, others tables have tags.

**Info about your desktop**
 - OS: Linux
 - Version: 20.04
 - Window manager:
 - pgModeler version: 0.9.3
 - Qt version: 5.12.5

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
You have to update your tags with the colors of the togglers. This was a new addition related to 0.9.3.

**Comment by equinton** [comment]
Ok, thanks.
