### ISSUE TITLE
Error using extensions

### ISSUE THREAD

**Issue by AlexisK99** [pgmodeler/pgmodeler#1506]
**Error using extensions**

The extensions are generated after creating the tables,
 therefore if I want to use a function inside my table, it gives me an error.

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - pgModeler version: 0.9.3
 - Qt version: 5.15.2

**Stacktrace / Debug info**
```
[0] src/modelexportform.cpp (292)
  void ModelExportForm::captureThreadError(Exception)
    [SQLCommandNotExecuted] No se pudo ejecutar el comando SQL.
 Mensage retornada: ERROR:  no existe la función uuid_generate_v4()
LINE 3:  uuid_test uuid DEFAULT uuid_generate_v4(),
                                ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.


[1] src/modelexporthelper.cpp (568)
  void ModelExportHelper::exportToDBMS(DatabaseModel*, Connection, const QString&, bool, bool, bool, bool, bool)
    [SQLCommandNotExecuted] No se pudo ejecutar el comando SQL.
 Mensage retornada: ERROR:  no existe la función uuid_generate_v4()
LINE 3:  uuid_test uuid DEFAULT uuid_generate_v4(),
                                ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.


[2] src/modelexporthelper.cpp (42)
  void ModelExportHelper::handleSQLError(Exception&, const QString&, bool)
    [SQLCommandNotExecuted] No se pudo ejecutar el comando SQL.
 Mensage retornada: ERROR:  no existe la función uuid_generate_v4()
LINE 3:  uuid_test uuid DEFAULT uuid_generate_v4(),
                                ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.

       ** CREATE TABLE public.test (
	id_test serial NOT NULL,
	uuid_test uuid DEFAULT uuid_generate_v4(),
	test_name varchar(50),
	CONSTRAINT test_pk PRIMARY KEY (id_test)
);


[3] src/connection.cpp (478)
  void Connection::executeDDLCommand(const QString&)
    [SQLCommandNotExecuted] No se pudo ejecutar el comando SQL.
 Mensage retornada: ERROR:  no existe la función uuid_generate_v4()
LINE 3:  uuid_test uuid DEFAULT uuid_generate_v4(),
                                ^
HINT:  Ninguna función coincide en el nombre y tipos de argumentos. Puede ser necesario agregar conversión explícita de tipos.

       ** 42883

```

**Screenshots**

![Captura de pantalla (877)](https://user-images.githubusercontent.com/55039048/104239935-08f45a00-543a-11eb-8aab-0bd868dc6a27.png)
![Captura de pantalla (878)](https://user-images.githubusercontent.com/55039048/104239936-0a258700-543a-11eb-80eb-dc983188b8be.png)
![Captura de pantalla (879)](https://user-images.githubusercontent.com/55039048/104239938-0b56b400-543a-11eb-9e96-c2156c6217b6.png)
![Captura de pantalla (880)](https://user-images.githubusercontent.com/55039048/104239943-0c87e100-543a-11eb-8615-2ebc2b34a976.png)
![Captura de pantalla (881)](https://user-images.githubusercontent.com/55039048/104239946-0d207780-543a-11eb-8983-2efd5149f12a.png)
![Captura de pantalla (883)](https://user-images.githubusercontent.com/55039048/104239951-0db90e00-543a-11eb-9781-f54c8f141b59.png)
![Captura de pantalla (884)](https://user-images.githubusercontent.com/55039048/104239953-0e51a480-543a-11eb-96bc-f8889412128d.png)

**Comment by rkhaotix** [comment]
Validate your model.

**Comment by AlexisK99** [comment]
![Captura de pantalla (886)](https://user-images.githubusercontent.com/55039048/104240943-a56b2c00-543b-11eb-9d4b-c9ccf8bbeb5c.png)

I don't know if I'm wrong about something, but it tells me correctly validated

**Comment by rkhaotix** [comment]
Could you provide your database model so I can investigate?

**Comment by AlexisK99** [comment]
[test_uuid_error.zip](https://github.com/pgmodeler/pgmodeler/files/5798461/test_uuid_error.zip)

**Comment by rkhaotix** [comment]
@AlexisK99 This is one of the cases that pgModeler can't solve for itself. I asked you to validate the model because I tought uuid data type was created by the extension uuid-ossp but that extension creates only supporting functions. So, to solve this issue you have to use the object swapping tool to move the extension to a position before to that in the creation order. See here:
https://pgmodeler.io/support/docs/68-swap-objects-ids?v=0.9.3

**Comment by AlexisK99** [comment]
Ohh, right now I will see the documentation, thank you very much for answering my question

**Comment by AlexisK99** [comment]
![Captura de pantalla (887)](https://user-images.githubusercontent.com/55039048/104247109-e405e400-5445-11eb-90b1-631fde9cfaff.png)

It worked perfectly, thank you very much !!
