### ISSUE TITLE
Create a simple feature to group tables by visual rectangle layer using colors

### ISSUE THREAD

**Issue by Diackne** [pgmodeler/pgmodeler#1510]

**Comment by rkhaotix** [comment]
Please, provide a detailed description of what do you need. Thanks.

**Comment by jacodavel** [comment]
Given a design with say 100 or more tables, is there anyway one can group tables together on a page to only view what is relevant from a certain perspective?

**Comment by rkhaotix** [comment]
Yes. You have some options to separate tables in a certain context:

1) You can use tags to setup custom colors for tables
https://pgmodeler.io/support/docs/329-tags?v=0.9.3

2) You can use layers to separate the tables. With layers you can hide objects quickly and focus only on the portion you want to work.
https://pgmodeler.io/support/docs/124-layers-management?v=0.9.3

3) If your database is a multi schema one you can enable schemas rectangles so you can quickly arrange/move tables just my moving the schema's rectangle.
https://pgmodeler.io/support/docs/32-schemas?v=0.9.3

4) Using the auto arrange feature. This one is a more generic solution but for some cases can be enough.
https://pgmodeler.io/support/docs/715-autoarrange-objects-over-the-canvas?v=0.9.3

4)

**Comment by Diackne** [comment]
I understood, but these solutions are all structural, and not visual notations, it is important for those who are creating a model, to put more contextual notations. Notes, are perfect although they could also have background color.
But there is nothing example (a square where these tables are grouped (visual) in different contexts in a Schema, example Schema X have tables A1 A2 A3 A4 -  WIP[A1 A2]  or Schema Y - Y1[A1 A2] , Y2[A3 A4])
- Tags: the overview gets very confusing
- Autoarrange: it is not a solution because tables are in positions that we do not want.
- layers - to see your context, I lose others hidden, and you can't distinguish visible ones.
- Schemas - it is not a visual it is structural

**Comment by rkhaotix** [comment]
Ok @Diackne 

I'll think on something else that fits your needs. Thanks.
