### ISSUE TITLE
purchased Mac version, DMG appears to do nothing!

### ISSUE THREAD

**Issue by Rafeski** [pgmodeler/pgmodeler#1513]
**Bug description**
I paid for a lifetime licence, and bought for Mac and Win 64. I downloaded the mac dmg install file, try and run it and it does nothing. Not even a flash screen. Nothing appears to be created in Applications etc.

**How to reproduce**
click on the dmg file.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
Nothing to screenshot.

**Info about your desktop**
 - OS: MacOS Catalina
 - Version: 10.15.7
 - Window manager:
 - pgModeler version:0.9.3
 - Qt version: ?

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Hi @Rafeski 

The dmg is mounted at your desktop. The application itself is inside the dmg. You have to move it to /Applications in order to work properly.

**Comment by Rafeski** [comment]
Hi Raphael!

 

Thanks for the simple answer! A bit new to Macbook so I don’t really understand their install structures!

 

Thanks once again, have a great weekend! :)

**Comment by rkhaotix** [comment]
Hey @Rafeski 

No problem! :)
You can contact me anytime. 

Have a great weekend too.

**Comment by Rafeski** [comment]
Hi Raphael,

 

Just a suggestion…

 

I am adding loads of columns, and perhaps you could have another button that adds the column to the table and then resets the column properties form as a default button, so you don’t have to keep clicking on the add new column…..

 

Just a thought…

 

:)

**Comment by rkhaotix** [comment]
Hi.

I didn't understand... Could you please detail this suggestion? :)

Em sex, 29 de jan de 2021 13:25, Rafe Saunders <notifications@github.com>
escreveu:

**Comment by Rafeski** [comment]
Hi,

When you add a single column, from the table form, you click the add column
button, enter details then the apply button and the add column form closes.

If you need to add several columns, you need to keep clicking the add
column button every time.

If instead, when the add column form was open, it did not close when the
apply button was pressed, but added the column as the default button but
stayed open to add the next column, instead of closing. This way, users
with a 30 column table would save clicking the add column button 29
times.....

Does that make sense..

Cheers.
