### ISSUE TITLE
pgModeler and Desktop menu item

### ISSUE THREAD

**Issue by demetriuzz** [pgmodeler/pgmodeler#1522]
**Feature description**

pgModeler is **GUI**.
When installing it, you **need** to provide for the creation of `*.desktop` files in the _menu_ and on the _desktop_. 

**Additional info**

For now, this has to be done _manually_.

**Comment by rkhaotix** [comment]
Run ```pgmodeler-cli -mt install```

**Comment by demetriuzz** [comment]
> Run `pgmodeler-cli -mt install`

It works.
But .. this **hand** made.

The task is _specifically_ for the package **installation** process.

**Comment by rkhaotix** [comment]
Ok. I will see what I can do.

**Comment by demetriuzz** [comment]
> Ok. I will see what I can do.

Thank you for your feedback!

**Comment by demetriuzz** [comment]
**Good day!**
There is a _suggestion_ on how to do this.
Experience in other programs:
 add a menu item that creates * .desktop on the menu and (or) desktop.
Example - IntelliJIDEA

![IntelliJIDEA_menu](https://user-images.githubusercontent.com/61899867/109650573-37abc880-7b7f-11eb-877b-44868cd45d23.png)
