### ISSUE TITLE
Synchronize model with database

### ISSUE THREAD

**Issue by develogo** [pgmodeler/pgmodeler#1527]
I have a database and I used reverse engineering to create a model, all right, it worked perfectly. I transferred this file to another computer and made some changes to the model, then connected with the original bank and tried to use the diff by checking the option "Generate filters from changelog", because I made many changes and I don't remember to insert one by one using the button "Add". But when selecting the most recent date I see that nothing happens. Is there any way to synchronize my model with the current bank and see what differences between them to use diff?

**Comment by rkhaotix** [comment]
The partial diff based on the changelog will work only if the changes you've made were in the current session or you've opted to store the changelog in the database model file (the default is not to save it into the file).

In any case, you can always perform the full diff that the result will be the same, it'll only take more time to finish depending on the size of your database.

**Comment by develogo** [comment]
I will redo the diagram and check the option "Store in file model". So if you transfer the file to another computer, will the data persist?

**Comment by rkhaotix** [comment]
Yes. Exactly.

**Comment by develogo** [comment]
Thanks for the clarification. You do an excellent job on pgmodeler.
