### ISSUE TITLE
"Store in model file" corrupting file

### ISSUE THREAD

**Issue by develogo** [pgmodeler/pgmodeler#1528]
Well, I found the function to save changes next to the file to be applied in the future incredible. But I'm having problems, every time I check the option to save the changelog and when closing the pgmodeler the file is corrupted. First I want to let you know that the validations are done before the rescue, as informed in the documentation.

Operating system: Windows 10 Pro
Version: 2004
OS Build: 19041.804

PgModeler
Version: 0.9.3

Qt version: 5.15.2

[0] src/mainwindow.cpp (1721)
  void MainWindow::showFixMessage(Exception&, const QString&)
    [ModelFileNotLoaded] Could not load the database model file `C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

[1] src/mainwindow.cpp (992)
  void MainWindow::addModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[2] src/mainwindow.cpp (967)
  void MainWindow::addModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[3] src/modelwidget.cpp (1634)
  void ModelWidget::loadModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[4] src/databasemodel.cpp (3419)
  void DatabaseModel::loadModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!
       ** C:/Users/lippe/Documents/CidadeMelhor/diagram/diagram.dbm (line: 1225)

[5] src/databasemodel.cpp (11280)
  void DatabaseModel::addChangelogEntry(const QString&, const QString&, const QString&, const QString&)
    [InvChangelogEntryValues] Trying to register a changelog entry with invalid values(s)!

**Comment by rkhaotix** [comment]
@develogo Could you send me a copy of your database model?

**Comment by develogo** [comment]
@rkhaotix yes. Can you tell me an email?

**Comment by rkhaotix** [comment]
you can send it to bug (at) pgmodeler.io

**Comment by develogo** [comment]
Sent to bug@pgmodeler.io. 
I didn't find the option on the website, sorry, so I used the software option and this email was informed.

**Comment by rkhaotix** [comment]
I got it. I'll test to see what is happening.

**Comment by develogo** [comment]
I don't know if this is useful information, but I'm using postgis.

**Comment by rkhaotix** [comment]
The postgis itself is not the problem. I've found the problem. I'll flag this ticket as bug.

**Comment by develogo** [comment]
Thank you very much.

**Comment by develogo** [comment]
I tested it on version 0.9.4-alpha and it was fixed. Even the file that was giving error returned to work with all changelogs intact.
