### ISSUE TITLE
The main window can't get small enough to fit on a small display.

### ISSUE THREAD

**Issue by fcolecumberri** [pgmodeler/pgmodeler#1531]
**Bug description**
When running the program on a small display (1366x768) the main window can't get small enough, the lower buttons and the lower toolbar become unaccessible

**How to reproduce**
Run the program on a small display (1366x768)

**Expected behavior**
The main window should be able to be small. 

**Screenshots**

![pgmodeler_cropped](https://user-images.githubusercontent.com/12193875/111497922-c99bff80-8741-11eb-90fc-8bce67b60f20.png)

**Info about your desktop**
 - OS: Linux Ubuntu-Mate
 - Version: 20.04
 - Window manager: Mate
 - pgModeler version: 0.9.3-alpha1
 - Qt version:  5.12.8

**Comment by LuckyDenis** [comment]
Good afternoon. I also encountered this behavior. And now the program can not be expanded to full screen.

**Info about your desktop**

- OS: Linux Mint 20.1 Cinnamon
- Version: 20.01
- Window manager: Cinnamon 4.8.6
- pgModeler version: 0.9.3
- Qt version: Debian 5.12.8

**Comment by fcolecumberri** [comment]
I have just tried tested the 0.9.4-alpha branch, it works, thanks
