### ISSUE TITLE
[feature-request] how to grant role to other role? I already double check but still not found

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1542]
Hi @rkhaotix, have a good day,

I can see, I have role `public_read` and role `anonymous`, I want to do this:
`grant public_read to anonymous`, but I cannot find it in anywhere, is that missing feature? because I see we can grant "role to table" but cannot grant "role to role"?
do I missing something? 

Best wishes,
Hiep

**Comment by rkhaotix** [comment]
Hi @hiepxanh 

Yeah, pgModeler does not support this yet. But I will flag this issue as feature request and try to implement it during development of 0.9.4.

**Comment by hiepxanh** [comment]
hi @rkhaotix, 
Thank you for your support, please check your email, I cannot find this email sir aphael@pgmodeler.io

![image](https://user-images.githubusercontent.com/16970990/118383477-350e2a80-b628-11eb-8a6f-ead67c516901.png)

**Comment by hiepxanh** [comment]
nice to meet you, 
I see that your project is very good, I already bought a full paid version of your application. I would like to make more donate on a safe and secure channel, I would like to suggest you using github sponsor. I'm already convince Dokku platform using it and he have a good subscription from github sponsor. 
I suggest you to read this topic on here: https://github.com/dokku/dokku/discussions/4258#discussioncomment-268269
as I said in this topic: 
1) I help other project very much, you should try this: https://aeplay.org/citybound-devblog/why-im-moving-from-patreon-to-github-sponsors#:~:text=At%20the%20same%20time%2C%20the,for%20creators%20are%20really%20lacklustre.&text=GitHub%20Sponsors%20is%20like%20a,that%20already%20are%20on%20GitHub

 image.png
2) create a readme https://github.com/dokku/dokku/discussions/4258#discussioncomment-268746
like this man: https://github.com/readme/benjie-gillam

After you create a github sponsor, I'm happy to become your first donator

Thank you,
Hiep

**Comment by rkhaotix** [comment]
@hiepxanh GitHub sponsor does not support Brazilian banks until the day I was reading about it... But I'll check it again.

About the issue itself, the sample command you posted ```GRANT public_read TO anonymous``` is the same as creating the role ```anonymous``` this way ```CREATE anonymous ... IN ROLE public_read```

Anyway, I'll make the diff between two roles to generate GRANT/REVOKE commands.

**Comment by hiepxanh** [comment]
thank you for your support, if i have good condition, I would like to make some donate directly for you, can you give me a working email address? or discord or slack? I will chat more for you, BTW, it take me few month to finish, but once it lauch successful, I will transfer for you through USDT https://academy.binance.com/vi/articles/what-is-tether-usdt (by TRC-20 network, it only cost 1$ for any kind of transaction in 1 minute on any account global)
@rkhaotix
