### ISSUE TITLE
libpq

### ISSUE THREAD

**Issue by yogesch** [pgmodeler/pgmodeler#1547]
So I am trying to install this from source. I am using Ubuntu Linux 20.04 and I have Postgresql 12 and Qt installed. libpq-dev and libpq5 are already installed via apt. 

While checking the platform specific requirements, the first two (for Qmake and libxml2) pass, but the third (libpq), I get a different result. 
```
1: pkg-config libpq --cflags --libs
``` 
Instead of 
```
 -I/usr/include -L/usr/lib64/libpq.so 
```
I get

```
-I/usr/include/postgresql -lpq
``` 
What does it mean if the -L part is missing? How should I get it, or can I continue with the installation?

**Comment by rkhaotix** [comment]
There's no problem. Having -L[path] or -lpq is the same thing. You can continue the building.

**Comment by yogesch** [comment]
Thank you!
