### ISSUE TITLE
Problems using layers

### ISSUE THREAD

**Issue by sebmay** [pgmodeler/pgmodeler#1551]
Layers is a very good idea to me.
My project is big, and the representation in pgmodeler is unreadable. Not because of pgmodeler. Would be the same in a non-layered dataset representation.
I recompiled pgmodeler 0.9.4-alpha in my debian buster

I see some bugs :
1) renaming layer does not change the name. That one should be easy :) **EDIT** double-click or F2 for direct renaming works **
2) After moving the views in a separate layer, i see that works. I can redispose the view in the new layer.  I can show/hide the layers. But if i save, exit pgmodeler, then come back, the views are back in the original layer. At the place defined earlier in the new layer. You save the new place of the object, but the layer no.
In fact, the views are now in both layers...
view name="battle_participant" layers="0,1" collapse-mode="1" max-obj-count="1" z-value="0"

![image](https://user-images.githubusercontent.com/10236091/120486850-b64e1700-c3b5-11eb-82e1-6e5a0a0cf1d1.png)
But thanks to you for this great job...

**Comment by rkhaotix** [comment]
Hi @sebmay  

Are you not mixing layers with schema rectangles? They are two completely different things...

Anyway, I've tested renaming both schemas and layers (0.9.4-alpha1, under development) and everything worked as expected.

Could you please provide more details?

**Comment by sebmay** [comment]
I maybe made a mistake with renaming layers...
But the second point seems to be a trouble....

**Comment by sebmay** [comment]
I can give a method to exhibit the problem.
Suppose you have "things" on screen.
Create a new layer.
right click on a viewX, set layers, unselect the main one, select the newly created layer.
If you hide the new layer, the viewX disappear. Show that new one layer, hide the main : Only the "moved" viewX appears. That is what is expected.
Save the schema, exit pgmodeler.
Look in the xml file : the viewX : 
view name="battle_participant" layers="0,1" collapse-mode="1" max-obj-count="1" z-value="0"
should be layers="1".
Restart pgmodeler : the viewX appears in both layers.
The bug is in the xml generation. Only.

**Comment by sebmay** [comment]
I made a test with a third layer. It looks like after save/exit/restart, the default layer ALWAYS show everything.With an objX moved to the third layer, i see after reload of the dbm, that the second and third layer hold the "moved" object as expected. Only the default, number 0 still show everything.

**Comment by rkhaotix** [comment]
Can confirm that the bug is still there after the comment on #1579 .

**Comment by sebmay** [comment]
YESSSS !

Looks like it's working....

Thanks, man.
