### ISSUE TITLE
Problem while importing DB (public.tmp_sequence_table)

### ISSUE THREAD

**Issue by altnetto** [pgmodeler/pgmodeler#1553]
Hello, 

I am new to PGModeler and I apologize if this error was solved in another related issue. Furthermore, before creating a trigger function that works exactly the same way as another trigger (in different tables and with different fields), all the imports gone well, without any errors. However, after creating this new trigger function, PGModeler is raising this error:

`[0] src/databaseimportform.cpp (591)
  void DatabaseImportForm::captureThreadError(Exception)
    [ObjectNotImported] The object `public.tmp_sequence_table' (Table), oid `53321', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.

[1] src/databaseimporthelper.cpp (662)
  void DatabaseImportHelper::importDatabase()
    [ObjectNotImported] The object `public.tmp_sequence_table' (Table), oid `53321', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.

[2] src/databaseimporthelper.cpp (410)
  void DatabaseImportHelper::createObjects()
    [ObjectNotImported] The object `public.tmp_sequence_table' (Table), oid `53321', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.

[3] src/databaseimporthelper.cpp (391)
  void DatabaseImportHelper::createObjects()
    [ObjectNotImported] The object `public.tmp_sequence_table' (Table), oid `53321', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.
       ** -- Raw attributes: tmp_sequence_table (OID: 53321) --
columns: 
comment: 
dead-rows-amount: 0
is-partitioned: 
last-analyze: 
last-autovacuum: 
last-vacuum: 
max-obj-count: 2
name: tmp_sequence_table
object-type: 6
oid: 53321
oids: 
owner: 	<role name="master"/>

parents: 
part-key-colls: 
part-key-cols: 
part-key-exprs: 
part-key-opcls: 
partition-bound-expr: 
partitioned-table: 
partitioning: HASH
permission: 
position: 	<position x="0" y="0"/>

rls-enabled: 
rls-forced: 
row-amount: 48
schema: 	<schema name="public"/>

schema-oid: 2200
sql-disabled: 
tablespace: 
tuples-del: 0
tuples-ins: 48
tuples-upd: 0
unlogged: 
---

[4] src/databaseimporthelper.cpp (788)
  void DatabaseImportHelper::createObject(attribs_map&)
    [ObjectNotImported] The object `public.tmp_sequence_table' (Table), oid `53321', could not be imported due to one or more errors! Check the exception stack for more details. `HINT:' if the object somehow references objects in `pg_catalog' or `information_schema' consider enable the importing of system objects.
       ** -- Raw attributes: tmp_sequence_table (OID: 53321) --
columns: 
comment: 
dead-rows-amount: 0
is-partitioned: 
last-analyze: 
last-autovacuum: 
last-vacuum: 
max-obj-count: 2
name: tmp_sequence_table
object-type: 6
oid: 53321
oids: 
owner: 	<role name="master"/>

parents: 
part-key-colls: 
part-key-cols: 
part-key-exprs: 
part-key-opcls: 
partition-bound-expr: 
partitioned-table: 
partitioning: HASH
permission: 
position: 	<position x="0" y="0"/>

rls-enabled: 
rls-forced: 
row-amount: 48
schema: 	<schema name="public"/>

schema-oid: 2200
sql-disabled: 
tablespace: 
tuples-del: 0
tuples-ins: 48
tuples-upd: 0
unlogged: 
---

[5] src/databaseimporthelper.cpp (1837)
  void DatabaseImportHelper::createTable(attribs_map&)
    [AsgInvalidTypeObject] Assignment of invalid type to the object!
       ** <function name="generate_code_name"
		window-func="false"
		returns-setof="false"
		behavior-type="CALLED ON NULL INPUT"
		function-type="VOLATILE"
		security-type="SECURITY INVOKER"
		execution-cost="100"
		row-amount="0">
	<schema name="public"/>
	<role name="master"/>
	<language name="plpgsql"/>
	<return-type>
	<type name="text"/>
	</return-type>
	<parameter name="description">
		<type name="text" length="0"/>
	</parameter>
	<definition><![CDATA[
BEGIN
	description = UPPER(TRIM(description));
    description = UNACCENT(description);

	description = regexp_replace(description, '[^A-Z0-9_\s]','','g');
    
    description = regexp_replace(description, '\s+', '_', 'g');
    
    description = TRIM(description);
    
    description = TRIM(description, '_');
    
	RETURN description::text;

END;]]></definition>
</function>

[6] src/pgsqltypes/pgsqltype.cpp (249)
  static PgSqlType PgSqlType::parseString(const QString&)
    [AsgInvalidTypeObject] Assignment of invalid type to the object!
       ** information_schema.sql_identifier

[7] src/pgsqltypes/pgsqltype.cpp (288)
  unsigned int PgSqlType::setType(const QString&)
    [AsgInvalidTypeObject] Assignment of invalid type to the object!

`

If I follow the hint that PGModeler gives me (to check the "import system objects" when importing), it runs well again. But, I would like to undestand where are this error occuring (the closer I've got was that it is an error in the oid 209, which would be a plpgsql function called float4larger), since I am using two similar trigger functions.

**Comment by rkhaotix** [comment]
You didn't provide more details, but I suppose that it is trying to assign the type ```information_schema.sql_identifier``` to an object that I can't identify due to the lack of information. Anyway, objects that reside on ``` pg_catalog``` or ```information_schema``` are considered built-in system objects and aren't imported automatically.

 You have to force their importing by checking "Import system objects". That's the reason pgModeler hints you to check the mentioned option.

About the function ```float4larger``` the idea is the same here. This function probably is allocated in ```pg_catalog```  and is failing to be imported because that option is not checked.

**Comment by altnetto** [comment]
Oh, I got it, so we do have to check the option to import, due to the location of the content on Postgre libs. Thank you so much! We were thinking that could be an error due to some function bad usage.

My best regards, 
Altieres
