### ISSUE TITLE
Running pgmodeler-0.9.3-demo-macos.dmg doesn't do anything

### ISSUE THREAD

**Issue by RedTailedHawk** [pgmodeler/pgmodeler#1558]
I just downloaded `pgmodeler-0.9.3-demo-macos.dmg` and ran it, but it doesn't do anything.  It looks like the process just dies.

Running on a Mac with Big Sur 11.2.3.

Thanks for any help.

**Comment by rkhaotix** [comment]
Hi @RedTailedHawk 

The dmg image is mounted to your desktop once you double click it. After mounting it you have to move the application inside the image to the /Applications folder on your system. After this procedure, you can run pgModeler.

**Comment by RedTailedHawk** [comment]
I see, ok that worked fine thanks!
