### ISSUE TITLE
Cannot Connect and Db Connection Info not Saved

### ISSUE THREAD

**Issue by RedTailedHawk** [pgmodeler/pgmodeler#1559]
I cannot seem to connect to my database, and the connection parameters do not seem to be getting saved.

![image](https://user-images.githubusercontent.com/8505928/122643523-40002300-d0de-11eb-9bde-c0ad5a6cd3ab.png)

When I go back into the db connection, everything I just entered is blank.

![image](https://user-images.githubusercontent.com/8505928/122643561-7178ee80-d0de-11eb-9e67-0f1207f3cf11.png)

I'm seeing this behavior on both `0.9.3` and `0.9.4-alpha`.

**Comment by rkhaotix** [comment]
See here how to create connections properly.

https://pgmodeler.io/support/docs/44-connections-settings?v=0.9.3

**Comment by RedTailedHawk** [comment]
All good now, thanks.  Sorry for the newbie questions.  :-)

**Comment by rkhaotix** [comment]
No problem, feel free to ask anything :)
