### ISSUE TITLE
I cannot find "import foregn schema" feature, is that we not have this?

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1567]
Hi @rkhaotix, hope you have good day in Brazil
I'm following the tutorial to get work with FDW with clickhouse: https://github.com/adjust/clickhouse_fdw
there is the line IMPORT FOREIGN SCHEMA which I not found pgmodeller, I guess we not support this yet :D or I just not found on the document 
```
IMPORT FOREIGN SCHEMA "test_database" FROM SERVER clickhouse_svr INTO public;
```

I guess I should use custom sql

**Comment by rkhaotix** [comment]
Hi @hiepxanh 

There's no native support for ```IMPORT FOREIGN SCHEMA``` so you can use custom SQL or generic SQL objects. I prefer the latter  because they are more flexible.

**Comment by hiepxanh** [comment]
thank you so much :D
