### ISSUE TITLE
Foreign key on delete actions not checked in diff tool

### ISSUE THREAD

**Issue by aruhn1** [pgmodeler/pgmodeler#1570]
**Bug description**
After changing the on delete/update actions on a foreign key, (e.g. change from no action on delete to cascade on delete) and then doing a diff, this change is not reflected. 

**How to reproduce**
Just create two tables, one containing foreign keys to the other. First let it be no action on delete for the foreign key. Sync to a database. Check that there is no diff. Then change the FK so that it is now cascade on delete. Do a diff again, it will not show any changes. 

**Expected behavior**
The on delete action of the foreign key should be checked in the diff tool.

**Info about your desktop**
 - OS: Ubuntu and FreeBSD
 - Version: 20.04 and 11
 - Window manager: Gnome and terminal/ssh
 - pgModeler version: .94 alpha
 - Qt version:

**Comment by rkhaotix** [comment]
The diff tool works only with objects that can be fully modified by ALTER command. Foreign keys (and any other constraint) can't. The only possible change for constraint is:

```ALTER CONSTRAINT constraint_name [ DEFERRABLE | NOT DEFERRABLE ] [ INITIALLY DEFERRED | INITIALLY IMMEDIATE ]```

So, if you need to change the delete/update action or any other constraint attribute you have to force the recreation of the object itself by checking the ```Force recreation of objects``` and ```Recreate only unmodifiable objects```

https://pgmodeler.io/support/docs/53-compare-model-and-database?v=0.9.3

**Comment by aruhn1** [comment]
In the docs page, it says 

> Instead of using an ALTER command to modify certain kinds of objects a DROP and CREATE will be used in order to do a full modification. This option does not affect the database object.

So does this mean the data in the column will be unaffected?

**Comment by aruhn1** [comment]
Yes it will make it smoother to integrate pgmodeler into a production workflow, more efficient than individual commands. On second thought, is a good ambition for the project than being just a good modeling tool, IMO.
