### ISSUE TITLE
pgmodeler.appdata.xml removed

### ISSUE THREAD

**Issue by marco44** [pgmodeler/pgmodeler#1574]
**Bug description**
pgmodeler.appdata.xml has been removed by 2a222e5e8eacdb797e1c87061334b3c5524e9ca1. Is this normal ? I used to package it in the arch's package.

**Comment by rkhaotix** [comment]
Yes, it was removed. 

Since it was quite outdated and the original creator of the file never requested updates on it I supposed that it wasn't needed anymore. But feel free to add an updated version and send me a pull request. I'll be glad to merge it!

**Comment by marco44** [comment]
Yes, I can either do a PR to put it back, or put it in archlinux's packaging directly. I see the file anyway has a reference to pgmodeler.desktop, which isn't in the repository either. Tell me what you prefer.

**Comment by rkhaotix** [comment]
@marco44 pgModeler.desktop is created by the CLI using the parameter ```-mt install``` so you can run a post install action to create the mentioned file.

**Comment by marco44** [comment]
BTW I've been trying to use `pgmodeler-cli -mt install` (`-sw`, as I want to install it at package deployment time), and I think I've hit a bug: the deployed pgModeler.desktop file has `Path=/root` set, which is of course bad, as it makes startup impossible

I think the problem is here:
```
      if(!uninstall)                                                              
          attribs[Attributes::WorkingDir]=QStandardPaths::writableLocation(QStandardPaths::HomeLocation);
```, maybe this should be ignored in the case we are doing a system-wide install ?

**Comment by marco44** [comment]
Or maybe this Path entry could be totally ignored, it's not required, and I think it defaults to the user's home

**Comment by marco44** [comment]
BTW do you want me to open another issue for this ?

**Comment by marco44** [comment]
Ok, so closing this one :)
