### ISSUE TITLE
Add an option to turn off alpha/beta versions updates

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#1577]
**Feature description**
Many users don't like to use alpha/beta releases in their environments, and development version updates notifications displayed by pgModeler can be annoying for these users. So,  it would be great if they could disable only this kind of notification and having only stable versions update notifications active. Maybe another checkbox under "Check for updates at startup" in general settings can do the trick.

**Comment by GitStorageOne** [comment]
Just add drop down list after checkbox with options `stable`, `beta`, `alpha`.
