### ISSUE TITLE
Issue #1551 is not fixed !

### ISSUE THREAD

**Issue by sebmay** [pgmodeler/pgmodeler#1579]
When you put an object ( for example a view) on a dedicated layer (called "Views", By ex.) and untick the "default" layer, the object is "moved" to layer "Views".
That's correct.
Then you save the project, and exit pgmodeler.
In the dbm : objects are on the default layer, as before 

\<table name="delegating_voter" **layers="0"** collapse-mode="1" max-obj-count="4" z-value="0">

and the views are on layer 2 for ex. :

\<view name="sujet_delegation" **layers="2"** collapse-mode="1" max-obj-count="1" z-value="0">

Until then, all is correct, **you fixed the bug... partially**.

Then you reopen the project with pgmodeler.
 And you get the views on the 'Views' layer  AND on the default layer !!

As i said before : you fixed the bug in the dbm-write routine,

but there is the mirrored bug in the dbm-read routine !!

**Comment by rkhaotix** [comment]
Ok. I'll check. You could just reopen the original issue. :)

**Comment by sebmay** [comment]
Sorry, i just thought a closed issues was definitely in the past. I'll do that from now on. Thanks.

**Comment by rkhaotix** [comment]
I'll close this one since it's duplicated. Let's keep discussing on #1551
