### ISSUE TITLE
Foreign Key Match Type Default

### ISSUE THREAD

**Issue by dpomerantz-jci** [pgmodeler/pgmodeler#1581]
**Feature description**
When creating a foreign key in pgModeler, the default match type is MATCH FULL.  The default for PostgresSQL is MATCH SIMPLE.  Please make the default in pgModeler match the default in PostgresSQL.

**Additional info**
https://www.postgresql.org/docs/9.0/sql-createtable.html#:~:text=MATCH%20FULL%20will%20not%20allow,foreign%20key%20are%20not%20null

**Comment by rkhaotix** [comment]
Hey @dpomerantz-jci 

The funny thing is that reading the previous sentence it gives the idea that MATCH SIMPLE is the default :)
But I can adjust that easily.

> There are three match types: MATCH FULL, MATCH PARTIAL, and MATCH SIMPLE, which is also the default

**Comment by dpomerantz-jci** [comment]
Thank you for agreeing to make the adjustment.  To be clear....

pgModeler default:  MATCH FULL
PostgresSQL default:  MATCH SIMPLE

Requested change:  Make pgModeler Default MATCH SIMPLE.

Thanks!

**Comment by rkhaotix** [comment]
Ow, you're right. My mistake! :)
