### ISSUE TITLE
Refactor dbm format to be consistant.

### ISSUE THREAD

**Issue by dpomerantz-jci** [pgmodeler/pgmodeler#1585]
**Feature description**
When writing a DBM file it should be in a repeatable format.  e.g. All tables should be written in alphabetical order, or some other order that is consistent.

**Sample image**
FIle - Save

**Additional info**
This helps with merge conflicts and "fixed" schema files.  Having them be out of order makes it harder to reconcile differences.

**Comment by pematt** [comment]
Suggestion: You could have two properties on each object for ordering: one for the order of saving in the xml file, and one for the order of the exported SQL statements.
