### ISSUE TITLE
Commas unsupported in enum values

### ISSUE THREAD

**Issue by MunyuShizumi** [pgmodeler/pgmodeler#1588]
**Bug description**
Using a comma in an enum value throws the following error:
_The enumeration ${value} can't be assigned to the type ${type} because contains invalid characters!_

This is not a PostgreSQL limitation, and commas aren't too uncommon in enum values (in this particular use case, it's an industry categorization, ex. "Leisure, Travel & Tourism" - mapping these labels elsewhere kinda defeats the point of using enums, and we're using this extensively in PSQL already).

**How to reproduce**
Create new enum type, add enum value such as `foo, bar` and the error will be thrown when trying to save the enum type.

**Info about your desktop**
 - OS: Arch Linux
 - Version: Linux 5.14.2-arch1-2
 - Window manager: Xfce 4.16.1-2
 - pgModeler version: 0.9.3-1
 - Qt version: 5.15.2+kde+r222-2

**Comment by rkhaotix** [comment]
Okay. I'll not work on this right now because 0.9.4-beta is ready to be released. So, I'm going to schedule this issue for 0.9.4-beta1 :)

**Comment by MunyuShizumi** [comment]
@rkhaotix (**tl;dr:** Please revert the `,` -> `•` enum delimiter commit, it creates way more problems than it solves in the current implementation (0.9.4b1 burnt me hard). Details and suggested solutions below.)

I'm assuming the new `•` separator introduced in the 0.9.4b1 merge is intended to fix this issue. Just to let you know that importing old DB models with 0.9.4b1 now results in enum values being parsed as one value, which typically throws an AsgEnumLongName and then relationally cascade-drops everything referencing the now-removed enums (in my case, about 90% of the DB model).

In short, 0.9.4b1 is essentially unusable for existing 0.9.3 models using enums, unless one feels like editing all of the XML by hand before opening the model. Even worse, if the enums have very few values (total encoded length < 64), 0.9.4 will "successfully" parse the old model, except now it turned all enum values into a single value and _it won't even inform the user_.

### Example

To illustrate... (XML only, haven't looked at the source)

Old format:
```
<enumeration values="foo,bar,baz"/>
```

New format:
```
<enumeration values="foo•bar•baz"/>
```

After parsing (JSON syntax):
0.9.3 opening 0.9.3 format: `['foo', 'bar', 'baz']`
0.9.4 opening 0.9.4 format: `['foo', 'bar', 'baz']`
0.9.4 opening 0.9.3 format: `['foo,bar,baz']`
0.9.3 opening 0.9.4 format: `['foo•bar•baz']`

If all the delimited values together exceed 63 bytes (which isn't a strict PSQL limit but depends on NAMEDATELEN when compiling, i.e. may in non-standard builds be greater than 63), pgModeler drops the enum (and everything referencing it) while "fixing" the model. If not, it just concatenates all values into one value, silently causing a bunch of issues and requiring manual intervention.

### Suggested solution

Also, I feel this solution just exchanges one problem (people using `,` in enums) for a less common one (people using `•` in enums) while also introducing a major breaking change for essentially all existing models using enums, so doesn't feel very useful. CSV-like encoding (in a nutshell: replace `"` with `""`, enclose value in double-quotes if it contains comma(s)) would result in better compatibility and only introduce an infinitesimal breaking change. E.g.:

_(I'll skip the XML encoding cause there would be a lot of `&quot;`s)_
Enum values: `foo,foo`, `bar•bar`, `baz"baz`
Encoded with quotes around every element: `"foo,foo","bar•bar","baz""baz"`
Encoded with quotes around select elements: `"foo,foo",bar•bar,baz""baz`

As much as I like brevity, I'd personally go with quotes around _all_ elements, it makes old vs. new format checks via regex a lot more robust and avoids the most issues with existing models. This way 0.9.4 could parse 0.9.3 models without issues, only adversely affecting models where _all_ of an enum's values have quotes around them.

Furthermore, the CSV format is very well standardized and documented, supports any Unicode character (essentially same as PostgreSQL enums), and one can easily find a small library to handle encoding/decoding without reinventing the wheel.
Or you can easily write the required transformations yourself, e.g. here's a quick JavaScript version (pardon the language, regex should be reusable at least):
```javascript
function encodeEnumValues(valueArray) {
	return valueArray
		.map(e => '"' + e.replace(/"/g, '""') + '"')
		.join(',');
}

function decodeEnumValues(str) {
	switch (true) {
		// If string matches new format, use new decoder
		case /^"([^"]|""){1,63}"(,"([^"]|""){1,63}"){0,65534}$/.test(str):
			return [... str.matchAll(/(?<=,|^)"((?:[^"]|"")+)"(?=,|$)/g) ]
				.map(m => m[1].replace(/""/g,'"'));
		case /^[^,]{1,63}(,[^,]{1,63}){0,65534}$/.test(str):
			return str.split(',');
		default:
			throw 'Malformed enum values';
	}
}

// Tests, each has exactly 3 elements
[
	// old
	'foo,bar,baz',
	'foo,"bar",baz',
	'fo"o,"bar,baz"',
	// new
	'"foo","bar","baz"',            // foo      bar     baz
	'"f""o""o","""bar","baz"""',    // f"o"o    "bar    baz"
	'"f,o,o",",bar","baz,"',        // f,o,o    ,bar    baz,
].forEach((s, i) => {
	console.log(`TEST #${i+1}`);
	console.log('Encoded:', s);
	let d = decodeEnumValues(s);
	console.log('Decoded:', d);
	let e = encodeEnumValues(d);
	console.log('Reencoded:', e);
});
```

Even if you don't agree with this solution, please revert the delimiter change, the current parser is somewhere between useless and dangerous for existing models using enums. Not being able to use commas is less of an issue than not being able to load old models. _\*runs back to 0.9.3\*_

**Comment by rkhaotix** [comment]
Calm down, there's no need to revert the commit. For now keep using 0.9.3 :)

I'll add a fix step in pgModeler CLI that does the conversion from commas to the new delimiter :)

I was expecting such problem to happen, and I will explain everything in details when releasing 0.9.4.

Anyway, could you send me a copy of your database model created in 0.9.3 so I can test the fix process?

**Comment by rkhaotix** [comment]
Had another idea that will solve the problem:

Instead of writting the enum type like this:

```xml
<usertype name="mytype" configuration="enumeration">
    <enumerations values="foo•bar•baz"/>
</usertype>
```

Enums will be written like this:

```xml
<usertype name="mytype" configuration="enumeration">
    <enumeration label="foo"/>
    <enumeration label="bar"/>
    <enumeration label="baz"/>
</usertype>
```

This way we can write virtually any char accepted by pgModeler in the enum labels. The only downside of this change is that it automatically breaks models constructed in 0.9.3, and such files *must* be fixed using ```pgmodeler-cli --fix-model```. I think it's a better solution than the original one.

**Comment by MunyuShizumi** [comment]
Latest suggestion seems best so far. At least it makes the XML more readable, standard CSVification would introduce a lot of XML-escaped characters.

My main work model is kinda too complex for testing purposes (and I'm sure upper management would start screaming if I shared it), but I went and created a sample model to test this further. Works in 0.9.4-beta and exports valid SQL (at least as far as PSQL 13.4 is concerned).
[test_enum.zip](https://github.com/pgmodeler/pgmodeler/files/7579743/test_enum.zip)

Creates an enum using:
- all printable CP-1252 characters
  - excluding `'` cause pgModeler doesn't escape it when generating SQL (results in SQL injection essentially)
  - excluding `,` cause pgModeler throws an error
  - excluding `•` (which does work in enums!) cause it breaks table data somehow? (removes all characters inputted after `•` including itself)
  - (`\` has to be escaped as `\\` in table data, but not in enums)
  - (some relatively obscure characters got replaced with regular spaces in the process, but I'm calling it good enough for v0.1a)
- 5 random UTF-8 strings
- 20 random xkcd-936 strings

... then creates a table using the enum and inserts table data for each enum value. If any enum value is removed/modified, it should throw an error during the insert. Outside of that, only `'` and `,` need to be tested manually.

Not an ideal test model, but should work for now. I'm guessing that CP-1252 is most likely to throw any errors related to parsing/validation/encoding/SQL generation/etc., and if it supports anything UTF-8 outside of that, it should support it in its entirety without issues?

**Comment by rkhaotix** [comment]
Nice. Thank you.

> Creates an enum using:
> 
> * all printable CP-1252 characters
>   
>   * excluding `'` cause pgModeler doesn't escape it when generating SQL (results in SQL injection essentially)
>   * (`\` has to be escaped as `\\` in table data, but not in enums)

I think an SQL Injection will not happen just a broken SQL code. The auto escape is something I plan for future releases.

>   * excluding `,` cause pgModeler throws an error

I think that CLI in 0.9.4 now covers this, fixing the model properly.

>   * excluding `•` (which does work in enums!) cause it breaks table data somehow? (removes all characters inputted after `•` including itself)

Yeah, the character `•` was originally used as the data separator for table data, but I tried to extend its use to enums but didn't work. I expect similar problems to happen with table data but I'll not worry about it for now.

>   * (some relatively obscure characters got replaced with regular spaces in the process, but I'm calling it good enough for v0.1a)
> * 5 random UTF-8 strings
> * 20 random xkcd-936 strings

These ones were completely ignored by the fix process and the whole data type and table which depends on it were discarded. Anyway, your example was a bit overkill but I think that the CLI "failed successfully" on trying to fix the model, which generated a model without those two objects, which is good in my opinion. :)

I think real-world examples like you posted initially can be covered now. But I'll let you give me some feedback before I merge the code into the develop branch.

**Comment by MunyuShizumi** [comment]
> I think an SQL Injection will not happen just a broken SQL code.

Essentially. What I meant is that it works similar to SQL injection by not escaping characters. On rare occasions, it could actually produce syntactically valid SQL.
Since single quotes/apostrophes are also very commonly used (e.g. `'s` possessives, "Côte d'Ivoire" in a country enum, etc.), I'd classify this as more-or-less the same caliber of issue as commas.

>I think that the CLI "failed successfully" on trying to fix the model, which generated a model without those two objects, which is good in my opinion. :)

Depends on why it failed. 0.9.4-beta1 also "fails successfully" by dropping simple enums where all values conform to `^[A-Za-z0-9_]+$` and then cascade-drops the vast majority of an existing 0.9.3 model. I haven't checked the codebase & fix diffs, but I imagine it's not just tied to some random UTF-8 character and is instead a greater/more common problem.

Generally, I'd say that any solution that breaks 0.9.3 compatibility without at least providing full PSQL-like character support (i.e. is very robust in the long term) is not worth it, but I don't know how badly the latest fix breaks existing models (only that it breaks 0.9.3 in _some_ way), so give me a day or two to test the branch and I'll let you know how it fares.

**Comment by rkhaotix** [comment]
> 0.9.4-beta1 also "fails successfully" by dropping simple enums where all values conform to ^[A-Za-z0-9_]+$ and then cascade-drops the vast majority of an existing 0.9.3 model.

That's why I always ask for the original model or dump of database that raised the bug. It's easier to find and fix the problem. Working with sample/isolated cases may not be enough to discover what's is wrong.

I can confirm that 0.9.4-beta1 does not drop enums (and dependant objects) that have labels based on that simple regexp. But if you say so, I can investigate a bit more with a proper example.

> Generally, I'd say that any solution that breaks 0.9.3 compatibility without at least providing full PSQL-like character support (i.e. is very robust in the long term) is not worth it,

Inevitably, in any step of pgModeler's development, a fix or a new feature will break the compatibility with older versions. That's why I created a model fix feature that tries to solve all that compatibility problems. It covers a lot of problems but in a very few cases we need to fix the model manually, which is not that hard.

But saying that any "solution that breaks 0.9.3 compatibility without at least providing full PSQL-like character support" is complicated, because, pgModeler *doesn't* support the full set of characters as PostgreSQL does (and maybe never supports). 

So, what I try to do is to solve the specific problem and the possible collateral effects of the patch (if possible). If I can't, I just move on and try to live with it, eventually coming back to the problem and trying a different solution. :/

**Comment by MunyuShizumi** [comment]
> I can confirm that 0.9.4-beta1 does not drop enums (and dependant objects) that have labels based on that simple regexp.

I can confirm (and already provided evidence) that it does. But here you go, two copy-pasted real-world enums with test tables. No, I won't share the company's entire backend publicly to illustrate the point.
[test_enum.zip](https://github.com/pgmodeler/pgmodeler/files/7587500/test_enum.zip)

All regex values conform to `^[A-Za-z0-9_]{1,63}$`. Model works and exports correct SQL in 0.9.3 and 0.9.4-beta.
Two things will happen with 0.9.4-beta1:
1. `enum_industry` will get dropped, and the table using it will get cascade-dropped.
2. `enum_job_type` will be preserved, but with malformed values (or rather, one concatenated value instead of 6). Exported SQL will throw an error if enum literals are used anywhere.

The only enums that survive 0.9.4-beta1 are those that have a single value. Enums whose encoded value exceeds 63 get dropped, and others' values get concatenated into a single value (or rather, the old delimiter gets ignored and isn't replaced).

> pgModeler _doesn't_ support the full set of characters as PostgreSQL does

0.9.3 already supports the entirety of CP-1252 (without `,` and `'`) and every exotic UTF-8 character I throw at it in enum labels. It's much harder to find characters that _don't_ work than those that work, which is why I went the extra mile to test the entirety of CP-1252 ahead of time, in case it stealthily introduces a new issue somewhere (but the first sample model will break regardless of characters used, e.g. only with the provided `^[a-z]+( [a-z]+){3}$` values).
So far, commas are the only issue in enums (and single quotes, but only in SQL generation), I can't see why dropping support for non-ASCII characters would be considered good or necessary in this case if it already works.

**Comment by rkhaotix** [comment]
> No, I won't share the company's entire backend publicly to illustrate the point.

Sorry but I was not trying to ask for your model again. :)

> All regex values conform to `^[A-Za-z0-9_]{1,63}$`. Model works and exports correct SQL in 0.9.3 and 0.9.4-beta. Two things will happen with 0.9.4-beta1:
> 
> 1. `enum_industry` will get dropped, and the table using it will get cascade-dropped.

Okay, I could confirm that, but now it works correctly in the latest commit of the branch `0.9.4`.

> 2. `enum_job_type` will be preserved, but with malformed values (or rather, one concatenated value instead of 6). Exported SQL will throw an error if enum literals are used anywhere (i.e. SQL will fail during data inserts).

There's no such enum in the sample model. Just the `enum_industry` and `tbl_enum_industry`.

> Enums whose encoded value exceeds 63 get dropped.

This will certainly happen, and the solution is to either hardcode an upper char limit or using a configuration entry or even a mix between the two.

**Comment by MunyuShizumi** [comment]
Sorry, at work, probably forgot to reupload modified zip.. >.<
[test_enum.zip](https://github.com/pgmodeler/pgmodeler/files/7588467/test_enum.zip)
(with `enum_job_type`)

If these work with the new branch, but the first sample fails, I'll have to check the fix branch today or tomorrow to see what's up.
I'd honestly like to look at at the codebase and throw a PR here and there for small fixes at least, but kinda short on time currently.

**Comment by rkhaotix** [comment]
> Sorry, at work, probably forgot to reupload modified zip.. >.<

No problem! :)

Anyway, this sample with `enum_job_type` worked as expected! :D
 
> If these work with the new branch, but the first sample fails, I'll have to check the fix branch today or tomorrow to see what's up. I'd honestly like to look at at the codebase and throw a PR here and there for small fixes at least, but kinda short on time currently.

Don't worry, take the needed time to test everything. But, the good news is that all the sample models worked in the latest commit. But I'll wait your considerations.

Thanks.

**Comment by MunyuShizumi** [comment]
Finally found some time to run the tests, sorry for the wait.

_**Small build instructions correction:** Under "Resolving dependencies", command no. 10 only copies `libqxcb.so`, but `libqoffscreen.so` is also needed (for the model fixer at least)._

So, I may have misunderstood that branch fix-issue-1588 still fails somewhere with the CP-1252 + random Unicode test model, but all seems to work perfectly on my end. Enums are entirely preserved, table data is inserted normally. Same with all real-world models I have.
The only character not entirely supported is `'` when exporting SQL, though that's an entirely different module so outside the scope of this issue/fix (and one could simply enter it as `''` as a workaround).

So far, seems to work perfectly with everything I throw at it. I'll run a few extra tests with less common characters/code pages just as an FYI report, but I'd label this merge-ready as is.

**Comment by rkhaotix** [comment]
>

> Finally found some time to run the tests, sorry for the wait.

No worries! :)



> **Small build instructions correction:** Under "Resolving dependencies", command no. 10 only copies `libqxcb.so`, but `libqoffscreen.so` is also needed (for the model fixer at least).

Thanks for this, I will fix this ASAP.

> So far, seems to work perfectly with everything I throw at it. I'll run a few extra tests with less common characters/code pages just as an FYI report, but I'd label this merge-ready as is.

That's great. Thanks for your help!
