### ISSUE TITLE
master failed to build

### ISSUE THREAD

**Issue by CaptainBloodz** [pgmodeler/pgmodeler#1594]
building from master
20210924.20b5186ac Qt 5.15.2
failed.

I had to patch to succeed as:
cat /etc/portage/patches/dev-db/pgmodeler-9999/001-check_update_chk.patch 
--- pgmodeler-9999/libs/libgui/src/settings/generalconfigwidget.old.cpp	2021-09-24 21:53:55.609326260 +0300
+++ pgmodeler-9999/libs/libgui/src/settings/generalconfigwidget.cpp	2021-09-24 21:57:31.726211093 +0300
@@ -221,8 +221,8 @@
 	});
 
 #ifdef NO_UPDATE_CHECK
-	check_upd_chk->setChecked(false);
-	check_upd_chk->setVisible(false);
+	check_update_chk->setChecked(false);
+	check_update_chk->setVisible(false);
 #endif
 
 	//Retrieving the available UI dictionaries

**Comment by rkhaotix** [comment]
This issue is fixed. Will be available officially on 0.9.4-beta1

See #1590

**Comment by CaptainBloodz** [comment]
My apologizes, as I was focused on git master integration to gentoo.
So I didn't do the appropriate checks before posting.

Thks

**Comment by rkhaotix** [comment]
No problem :)

I just found it strange that you mentioned master branch since the fix was applied to branch 0.9.4-beta1.
