### ISSUE TITLE
Trouble Building pgModeler from source.

### ISSUE THREAD

**Issue by PowerUser1234** [pgmodeler/pgmodeler#1599]
I am running Windows 10 64 bit, and I am having trouble following the build instructions for pgModeler 0.9.3 as per the website [https://pgmodeler.io/support/installation](https://pgmodeler.io/support/installation).

I have done everything accurately and successfully, up to the point that states:

**qmake -r CONFIG+=release PREFIX=$INSTALLATION_ROOT pgmodeler.pro**

-Inside MSYS2 MinGW 64bit, how exactly do I set $QT_ROOT and $INSTALLATION_ROOT ?

I know that I have installed Qt 5.99 in C:\Qt.  I have installed PostgreSQL in 
C:\Program Files\PostgreSQL\14. I have MSYS2 in C:\msys64.

How am I to specify a build directory for
pgmodeler, and whereabouts do I do this?

-How should I set $PGSQL_ROOT ? $PGMODELER_SOURCE ? $MSYS2_ROOT ?

**Comment by rkhaotix** [comment]
From docs:

> In the following procedures, to shorten the commands, we are assuming that $QT_ROOT is the full path to the Qt installation which varies from system to system, so remember to replace the variable with the real path according to your system. The variable $INSTALLATION_ROOT is the path where pgModeler should be installed after the building process is complete. Again, don't forget to replace the variables by the respective full path according to the running operating system.

So, `$QT_ROOT ` must be replaced by the path where Qt framework is installed. By the same logic, `$INSTALLATION_ROOT` is the path to where the file must be placed after building and deployment. Remember that these aren't environment variables, they are just placeholders in the commands on the docs just to make them shorter. 

For example, if Qt was installed via MSY2 at `/usr` and you want to install pgModeler at `C:\pgmodeler` the command above need to be written like this:

`/usr/bin/qmake -r CONFIG+=release PREFIX=/c/pgmodeler pgmodeler.pro`

**Comment by PowerUser1234** [comment]
I have tried running the command

**qmake -r CONFIG+=release PREFIX=/c/Users/User/Desktop/build/ pgmodeler.pro**
_Cannot find file: pgmodeler.pro._

and I get the message that the command does not know where the .pro file is.
Is the destination build directory the same as the unzipped pgmodeler, or not?
What should I do to properly correct this small looking error?

**Comment by PowerUser1234** [comment]
-Can someone knowledgeable about compiling and building pgModeler kindly tell me where I can get the missing
files and directories I need in order to build the open source, stable version of pgModeler?  I am
I required to do this with the alpha, open source, available version?

**Comment by rkhaotix** [comment]
Okay...

First, you can ignore the plugins.pro part. Anyway, to get them working, you have to clone their source inside the pgModeler's source code root:

```git clone https://github.com/pgmodeler/plugins.git```

And about  ```WARNING: Failure to find: obj/windows_ico.qrc```, you can ignore it completely since it doesn't prevent you to build pgModeler.

Did you even tried to run ```make && make install``` ?

**Comment by PowerUser1234** [comment]
I didn't try to go any further, since when compiling or building software, errors that occur earlier tend to mean there will be errors later on.

Anyway, I have succeeded.  The only problem was that two .dll files, named
**libmd4c.dll** and **libzstd.dll**, where not put in the designated build directory.  They
were elsewhere on the drive, within MSYS2, so I copied them into the root build
directory, and everything is running fine.

By the way, pgmodeler itself is giving me notification messages for a higher version
than what I built, a beta version.  I have decided to opt for the highest stable only
version, 0.9.3.  Is there place is pgmodeler that I can turn off the update available
messages?  What do I do to stop them?

Otherwise, thankyou more than very much, I am now running some free and open source software, that I have built myself!  Thanks for helping me!

**Comment by rkhaotix** [comment]
> I didn't try to go any further, since when compiling or building software, errors that occur earlier tend to mean there will be errors later on.

It wasn't error... just warning! ;)

> Anyway, I have succeeded. The only problem was that two .dll files, named
libmd4c.dll and libzstd.dll, where not put in the designated build directory. They
were elsewhere on the drive, within MSYS2, so I copied them into the root build
directory, and everything is running fine.

You did the correct procedure, it is even in the installation instructions.

> By the way, pgmodeler itself is giving me notification messages for a higher version
than what I built, a beta version. I have decided to opt for the highest stable only
version, 0.9.3. Is there place is pgmodeler that I can turn off the update available
messages? What do I do to stop them?

Yes, I've released a new version yesterday. You can disable update notifications in the general settings.

> Otherwise, thankyou more than very much, I am now running some free and open source software, that I have built myself! Thanks for helping me!

I'm glad that you made it! I'm closing this issue now, but feel free to reopen it in case of any problem, ok?
