### ISSUE TITLE
Export DB takes postgres instead of the specified owner

### ISSUE THREAD

**Issue by boucaron** [pgmodeler/pgmodeler#1600]
**Bug description**
Minor issue, I specified a specific owner for each table, when exporting it takes "postgres" instead
Export to 13 Dialect to be more specific

**Expected behavior**
Expecting to take the specified owner when generating the SQL

**Screenshots**
![image](https://user-images.githubusercontent.com/6444359/139685435-dc071a99-7e55-4183-adbd-8e4bfd04cb2c.png)

SQL Output:
-- ddl-end --
ALTER TABLE public."BOOKMARK" OWNER TO postgres;
-- ddl-end --

**Info about your desktop**
 - OS: Fedora  
 - Version: 34
 - Window manager: Default Gnome
 - pgModeler version: v0.9.4-beta compiled from git tag (without plugins)
 - Qt version: **20211029.20b5186ac Qt 5.15.2**

**Stacktrace / Debug info**
No crash

**Additional info**
None

**Comment by rkhaotix** [comment]
Can't reproduce the problem. Is there any step-by-step that can help me to identify it? Thanks

**Comment by boucaron** [comment]
Yes, I managed to reproduce a variant of the issue:
1) Create a new model
2) Create a new table with a column
3) Inside the table dialog, search for new owner, create a new role and named it "joe" for instance + validation
4) Export the schema -> it is fine at this step
5) Go back in the table and change the owner to "postgres" + validation
6) Export the schema -> it is still exporting with "joe"

**Comment by rkhaotix** [comment]
Hi @boucaron 

Well, I tried your step-by-step but had no success in reproducing the bug. Could you make a small video that demonstrates it?

**Comment by boucaron** [comment]
Sorry @rkhaotix the bug was me ^^
I rechecked and most likely I forgot to click on the export...

Not used to the pattern implemented:
1. Click first to select the file/directory
2. Validate 
3. Finally click export
I am so used to the regular save pattern in 2 steps, that I missed to click on the export after the selection...
