### ISSUE TITLE
pgmodeler-cli segfaults if no display

### ISSUE THREAD

**Issue by marco44** [pgmodeler/pgmodeler#1604]
**Bug description**
When pgmodeler-cli is run without a correct DISPLAY value (or I suppose a valid wayland environment), it segfaults

**How to reproduce**
```
unset DISPLAY
pgmodeler-cli 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```
**Info about your desktop**
 - OS: ArchLinux
 - Version: current
 - Window manager: kde
 - pgModeler version: 0.9.4_beta1
 - Qt version: 5.15.2

**Stacktrace / Debug info**
I don't have a backtrace yet (no debug symbols). If needed, I'll recompile for this.

**Additional info**
I managed to make it run by setting 
```
QT_QPA_PLATFORM=offscreen
```
maybe pgmodeler-cli should be a QCoreApplication ?

**Comment by rkhaotix** [comment]
This is a known issue, and the workaround is to use the parameter ```-platform offscreen```

For now pgModeler CLI can't be based on QCoreAppplication because it uses pure GUI components. The solution is to move some code to classes that can be used in either in CLI and GUI. Since I consider this a minor issue, I will work on this during development of 1.0. :)

**Comment by marco44** [comment]
Ok, sorry, I didn't find a bugreport. Should I close this one ?

**Comment by pinaraf** [comment]
Hum, couldn't you just add in the pgmodeler cli `main`, before the instanciation of the `Application` object, a simple call to
```c++
qputenv("QP_QPA_PLATFORM", "offscreen");
```

This will workaround the issue for everyone without requiring people to know about it.

**Comment by rkhaotix** [comment]
I didn't tried this way. Other workaround I tried have failed. Thanks for this advice, I will test it later today. 😁

**Comment by rkhaotix** [comment]
Hey @marco44 , that tip worked! I'll let it until I provide the correct fix for the problem, which is a lot more complex! :)

**Comment by marco44** [comment]
That's @pinaraf that proposed this fix, but good news.
