### ISSUE TITLE
Export model to SQL File using Split mode

### ISSUE THREAD

**Issue by TNTworks** [pgmodeler/pgmodeler#1614]
**Bug description**
Export model window to SQL File in mode Split does not allow to select a directory on Windows, as it opens the dialog to select a file.

**How to reproduce**
By wanting to choose any directory it just walks into them because it is probably a "open a file" dialog.

**Expected behavior**
Choosing a directory to which pgM splits the SQL.

**Screenshots**
![image](https://user-images.githubusercontent.com/3856730/146700095-24a513d6-257e-4991-a888-40689a636c5c.png)

**Info about your desktop**
 - OS: Windows
 - Version: 10
 - Window manager: Windows
 - pgModeler version: v0.9.4
 - Qt version: 20211220.20211220 Qt 5.15.2

**Stacktrace / Debug info**
Did not crash

**Additional info**
Workaround is to create a file e.g. "file.sql", select it in the Export Model dialog, then removing the file and creating a directory with the same name. Then the exporter works as expected and creates the splitted files.
Not a blocker but annoying :(

**Comment by rkhaotix** [comment]
@TNTworks thanks for reporting that. Actually, I found it annoying AND a blocker since it completely breaks the user's interaction on Windows. I'll fix it ASAP.
