### ISSUE TITLE
SVG export boundaries issue when open it in web-browser

### ISSUE THREAD

**Issue by bcag2** [pgmodeler/pgmodeler#1627]
**Bug description**
I export my model as SVG, and it is truncated in web-browser as we can see in screenshot. It is ok with PNG export to compare.
If I open it under Inkscape, I see all tables, so I think it is only a boundaries management issue.
EDIT: after inkscape edit, remove some unused schema and resize page in document properties, it shows correctly in web-browser !

**How to reproduce**
Just open a model which have enough tables (> 8-10 tables) or multiple schemas, export it as SVG, then open SVG file in web-browser like Firefox, Chromium/Chrome.

**Expected behavior**
Show all tables (and views) when open it in web browser

**Screenshots**
![20220106_pgmodeler_truncated-svg-issue](https://user-images.githubusercontent.com/5690299/148393814-cb445e14-ae73-4200-be09-6a6edb7423bd.png)

**Info about your desktop**
 - OS: Ubuntu 18.04
 - pgModeler version: 0.9.4
 - Qt version: ?

**Comment by rkhaotix** [comment]
@bcag2 Thanks for reporting that! You nailed it! It was a problem when determining the SVG boundaries.

I've taken the opportunity to fix other bugs that I found on the SVG export. Now it seems it's working as expected. In the attached file there's a PNG and an SVG of the same sample model... they are exactly the same, in dimensions, font size, and some other aspects.

[demo_png_svg.zip](https://github.com/pgmodeler/pgmodeler/files/7825023/demo_png_svg.zip)
