### ISSUE TITLE
Changing a pk from integer to serial does not update default expression

### ISSUE THREAD

**Issue by btownshend** [pgmodeler/pgmodeler#1629]
**Bug description**
Changing a pk from integer to serial does not update default expression

**How to reproduce**
Create a table with an integer pk, apply, change to serial, apply.   PK does not default to using sequence for pk.   Changing to another type first (e.g. smallint), apply, then to serial does work.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS:Mac
 - Version:
 - Window manager:
 - pgModeler version: 0.9.4
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Hi @btownshend 

I think I didn't understand correctly, but the `serial` data type is converted to `integer` + `sequence` when running the SQL code in the server. pgModeler doesn't provide this association automatically. You can convert from integer to serial and the inverse too but you have to follow some rules:

https://www.pgmodeler.io/support/docs/711-creating-a-sequence-from-serial-type?v=0.9.4
https://www.pgmodeler.io/support/docs/712-creating-a-serial-from-integer-type?v=0.9.4

Could you provide a small example for both cases (when it does work and when it doesn't)? Thanks.

**Comment by btownshend** [comment]
Hi,  the problem I think is with the diff process.    If the only change to a table is that the pk was changed from int to serial, then it seems that the diff doesn't pick up that it needs to update the default to use nextseq and the database is not consistent with the model after applying (since the underlying type of the field is unchanged).   If I change it to smallint, diff and apply, then change it to serial, the subsequent diff and apply work and the database is then consistent.

**Comment by btownshend** [comment]
By the way, I'm not talking about using the menu option to convert to serial.   I just changed the field from integer to serial within the table editing dialogs.

**Comment by btownshend** [comment]
And, if it makes any difference, this model is not based on any reverse engineering -- it was build from scratch in pgmodeler and only forward engineered to database.   So there's no sequences or settings in the database that should affect this (other than diffing against prior forward-engineering of the same model).

**Comment by rkhaotix** [comment]
Hi @btownshend 

Now I understood. :)

I'll try to reproduce the problem in my development environment and provide the proper fixes. 

Thanks

**Comment by btownshend** [comment]
Thanks for the quick fix!
