### ISSUE TITLE
Altering identity column type causes not working diff

### ISSUE THREAD

**Issue by LKajan** [pgmodeler/pgmodeler#1633]
**Bug description**
PgModeler produces a malformed diff sql after altering a identity column to other type (e.g. uuid).
"DROP IDENTITY" and "ALTER TYPE" DDLs are in wrong order in a diff sql. It first tries to alter the type before dropping the identity. Type cannot be changed to uuid if there is still a identity constraint.

**How to reproduce**
1. Create a table with IDENTITY type primary key
2. Run to database
3. Alter primary key type to uuid
4. Generate a diff
5. Try to run the diff to the database
6. Now DROP IDENTITY comes after ALTER TYPE in the diff sql

**Expected behavior**
Running a diff sql works

**Info about your desktop**
 - OS: Windows 11
 - pgModeler version: 0.9.4

**Comment by LKajan** [comment]
No I see that after fixing that manually there rises also other issues that are not related to PgModeler.
Naturally, integers cannot be casted to uuids automatically. And if there are any foreign key constraints those must be handled manually anyways. So maybe one should not expect a diff sql to be correct without manually tweaking it in case of altering primary key types.

The issue is still valid but I'm not sure if there are real use cases.

**Comment by rkhaotix** [comment]
Interesting issue, this one.  Maybe moving the `ALTER ... DROP IDENTITY` to the beginning may solve this.

Thanks for reporting.
