### ISSUE TITLE
Build instructions invalid/small issue on windows + here is the fix

### ISSUE THREAD

**Issue by GiGurra** [pgmodeler/pgmodeler#1636]
Just some quick fix info regarding the install/build-from-source instructions here: https://pgmodeler.io/support/installation. 

The last step for building pgmodeler on windows (cp <lotsOfFiles.dll>, isnt sufficient to make it work). It is missing two msys/mingw dlls.

To fix this, add the following two to the copy command at the end of the install/build-from-source instructions.

libzstd.dll libmd4c.dll

After adding those two, the built binary launches.

**Comment by rkhaotix** [comment]
Unfortunately, this always happens when MSYS2 upgrades its version. I've updated the instructions twice or more just to include new dlls :)

Anyway, thanks for reporting that.
