### ISSUE TITLE
Fade Out/In Issue

### ISSUE THREAD

**Issue by sggreener** [pgmodeler/pgmodeler#1645]
I have a situation where I Fade Out foreign key references to domain (list of values) tables.

I note that certain actions undo the fade out. Since I have a lot of domain/LOV tables it is tiresome to select and fade them out again.

Attached is a video that shows just such a situation. I select 4 FKs to domain tables, fade them out, edit one of the domain tables, all four fade back in

https://user-images.githubusercontent.com/4132977/150242448-d20d8fcc-7676-46aa-9494-f6195d7422e4.mp4

.

**Comment by villekah** [comment]
I would like to note that the Find objects -> Pattern -> Find is capable of wiping out all of the fade in/out settings in the model, and it does it every time, rendering the Find objects function unusable in many cases. As a result every object in the model is faded in.

Find objects also contains a Fade out drop down menu which let's you fade in/out objects in or not in the result list. If I have any by-hand faded out objects in my schema, I would simply not use it. In any case, if you happen to fade in/out the correct result list, there will be a time when you have to hit the Find button again...
