### ISSUE TITLE
App crashes: "Could not access sch-highlight.conf" error after fresh install

### ISSUE THREAD

**Issue by mareeo** [pgmodeler/pgmodeler#1647]
**Bug description**
Compiled executable myself and get a "Could not access the file or directory C:/Users/MYUSERNAME/AppData/Local/pgmodeler/sch-highlight.confg! Make sure that it exists or if the user has access permissions on it!" Program crashes after that. 

Tested with the demo binary downloaded from the website and had the same issue. Tried deleting that directory and the directoy was remade, but no sch-highlight.conf file.

**How to reproduce**
Install pgmodeler 0.9.4 demo binary from website and run it.

**Expected behavior**
App to start

**Screenshots**
N/A

**Info about your desktop**
 - OS: Windows 10 21H2
 - Version: 21H2
 - Window manager: N/A
 - pgModeler version: 0.9.4
 - Qt version: 5.15.2

**Stacktrace / Debug info**

```
** pgModeler crashed after receive signal: 11 **

Date/Time: 2022-02-08 12:19:19 
Version: 0.9.4 
Build: 20211220.20211220 
Compilation Qt version: 5.15.2
Running Qt version: 5.15.2

** Stack trace unavailable on Windows system **

```

**Additional info**
N/A

**Comment by rkhaotix** [comment]
Did you run ```make install```? Is the folder ```conf``` exists in the installation path?

**Comment by mareeo** [comment]
Yes I ran make install. The `conf` folder does exists in the installation path (it is in the `build` directory in the self compiled version and also in the demo version which installed to `C:\Program Files\pgModeler`). Attached is its contents.

![image](https://user-images.githubusercontent.com/9520224/153054075-d864867c-978f-4ca4-acf9-8ae7c96f5f6c.png)

Here are the contents of `AppData\Local\pgmodeler`

![image](https://user-images.githubusercontent.com/9520224/153054240-b5b89d25-51d4-4f89-8995-78e9baf7d063.png)

**Comment by mareeo** [comment]
Disregard. Uninstalling a previous version of pgmodeler seems to have fixed the problem.
