### ISSUE TITLE
pgmodeler-0.9.4-macos.dmg does nothing

### ISSUE THREAD

**Issue by egana-hmh** [pgmodeler/pgmodeler#1650]
**Bug description**
pgmodeler-0.9.4-macos.dmg does nothing

**How to reproduce**
- Downloaded pgmodeler-0.9.4-macos.dmg from the offical sites download section.
- Click on the download dmg and nothing happens.

**Expected behavior**
- Clicking on the dmg starts and installer or installs pgmodeler.

**Screenshots**

**Info about your desktop**
 - OS: macOS 
 - Version: Big Sur 11.6.1
 - Window manager:
 - pgModeler version: 0.9.4
 - Qt version:

**Stacktrace / Debug info**

**Additional info**

**Comment by rkhaotix** [comment]
Hi @egana-hmh 

When you double click the dmg an icon is created in your desktop. Double click it so you can have access to the bundle.

**Comment by egana-hmh** [comment]
I was told by another user it creates a desktop icon in the background...

**Comment by wsierakowski** [comment]
Just a note for anyone else that runs into the same issue. The installer wasn't actually creating any shortcut on the desktop for me. What I did was to mount the contest of the dmg file in the following way: `hdiutil attach pgmodeler-0.9.4-macos.dmg` then went to the volume `/Volumes/pgmodeler` and manually dragged the pgmodeler app to my applications directory. Then right-clicked on it and selected open to bypass the security restriction as the app developers can't be verified.
