### ISSUE TITLE
Views Referencing Other Views

### ISSUE THREAD

**Issue by nissane** [pgmodeler/pgmodeler#1657]
**Feature description**
I have a number of views that reference each other. I am unable to select references in the child view, because that only allows references to tables.

So I think I need to create an expression.  The issue I have is the order that the views are being created when I export the database.  

**So my question is**
is there a way to specify that a view depends on another view?
Or can I some control the export order of views?

Many Thanks!

**Comment by rkhaotix** [comment]
Hi @nissane 

For now, views are not allowed to reference each other. 

You can control the order of creation of the objects in the database model. Take a look here:

https://www.pgmodeler.io/support/docs/68-swap-objects-ids?v=0.9.4

**Comment by nissane** [comment]
ok, that totally worked, and fixed another issue I had.  Many thanks for the quick reply!
