### ISSUE TITLE
Support create partition on key which is created by a relationship

### ISSUE THREAD

**Issue by bachden** [pgmodeler/pgmodeler#1671]
I'm trying to create 2 table as follow
<img width="424" alt="image" src="https://user-images.githubusercontent.com/1224571/161708140-2d1b55f0-56ce-420b-836e-ed76a0324228.png">
Now on table issue I want to create partition key by `org_id` column, but there is error: 
<img width="878" alt="image" src="https://user-images.githubusercontent.com/1224571/161708411-a6f68793-4591-4569-98f0-1c477805f103.png">
Plz help!

**Comment by rkhaotix** [comment]
You can't create partition keys from relationship added columns like the error message shows for you. 

You need to create the columns and pk manually on "issue" table so you can use the column "org_id" as partition key. Also, you need to create a foreign key on table "org" that references "issue". Using a one-to-many relationship in your case will not be possible.

**Comment by bachden** [comment]
> 

thank for your reply @rkhaotix , but is this the limit of pgModeler? do you plan to support it?

**Comment by rkhaotix** [comment]
Yes, this is a limitation of the tool. In future releases I plan to work on this issue .

**Comment by bachden** [comment]
> 

I’m lôking forward. Thanks
