### ISSUE TITLE
PRECISO DE AJUDA COM ESTE ERRO!!!

### ISSUE THREAD

**Issue by XAUK33** [pgmodeler/pgmodeler#1677]
![image](https://user-images.githubusercontent.com/104914127/166703755-0bb3e5d2-8b36-473c-8e09-932a4ec25a87.png)

ESTE ERRO SEMPRE ACONTECE, QUERO APENAS EXIBIR 3 TABELAS MAS ISSO ACONTECE SEMPRE, SEMPRE DA ESSE ERRO FATAL MAS NÃO SEI O QUE POSSA SER.

**Comment by rkhaotix** [comment]
A senha fornecida para o usuário postgres não está correta. Cheque a senha como também o método de autenticação no pg_hba.conf

https://www.postgresql.org/docs/current/client-authentication-problems.html

**Comment by XAUK33** [comment]
> A senha fornecida para o usuário postgres não está correta. Verifique uma senha como também o método de autenticação no pg_hba.conf
> 
> https://www.postgresql.org/docs/current/client-authentication-problems.html

**Comment by XAUK33** [comment]
Então eu devo refazer um novo banco de dados com uma senha nova? pois eu ja estou com a ultima versão do pgadmin.

**Comment by rkhaotix** [comment]
pgAdmin != PostgreSQL. Você precisa olhar as configurações do seu banco de dados. Talvez da rolê que voce usa para acessar o mesmo. Nos links acima tem um norte pra você.
