### ISSUE TITLE
Error while connecting PostgreSQL 15 beta 1

### ISSUE THREAD

**Issue by ranquetat** [pgmodeler/pgmodeler#1689]
**Bug description**
_A clear and concise description of what the bug is._

[0] src/tools/databaseimportform.cpp (551)
  void DatabaseImportForm::listDatabases()
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  column "datlastsysoid" does not exist
LINE 1: SELECT oid, datname AS name, datlastsysoid AS last_sys_oid F...
                                     ^
'
![Captura de Tela 2022-06-16 às 09 47 04](https://user-images.githubusercontent.com/38974841/174073050-b863a25c-5f70-4c3e-9164-0ffbd350eb2b.png)

**How to reproduce**
_Please, if the bug can be reproduceable describe the steps in full details. If possible provide a sample model and/or a SQL dump for test purposes._
Import -> Settings -> choose connection (an existing connection to some PostgreSQL 15 beta1

**Expected behavior**
_A clear and concise description of what you expected to happen._
Connection sucessfu using PostgreSQL 15 beta 1

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: MacOS Monterey
 - Version: 12.4
 - Window manager:
 - pgModeler version: 1.0.0-alpha
 - Qt version: 5.15.3

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by jokay** [comment]
> switch
> 
> ```
>  image: postgres:14
> ```

Did I miss something, does pgModeler support even Postgres **14**?

An issue for Postgres **14** support is still open, see [here](https://github.com/pgmodeler/pgmodeler/issues/1658).
