### ISSUE TITLE
Alpha1 not starting up on linux

### ISSUE THREAD

**Issue by nissane** [pgmodeler/pgmodeler#1692]
**Bug description**
I am trying to start pgmodeler on ubuntu.  I get the following error when starting it.
This is the latest alpha1 version. the prior alpha version starts just fine.

[0] src/settings/snippetsconfigwidget.cpp (65)
  SnippetsConfigWidget::SnippetsConfigWidget(QWidget*)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[1] src/utils/syntaxhighlighter.cpp (647)
  void SyntaxHighlighter::loadConfiguration(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[2] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[3] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[4] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group .

**Comment by rkhaotix** [comment]
This error and the solution for it are documented in the blog post:
https://www.pgmodeler.io/blog/2022/6/21/pgmodeler-100-alpha1-is-ready-and-waiting-for-you

> **Before you start using 1.0.0-alpha1!**

> If you installed pgModeler 1.0.0-alpha before using 1.0.0-alpha1 you should get the error Error while interpreting XML buffer at line 0 column 0. Message generated by the parser: No declaration for attribute ```partial-match``` of element group.

> This error occur due to an attribute of the syntax highlight files was dropped. The solution is to manually erase the files xml-highlight.conf and sql-highlight.conf in your local storage where pgModeler settings are saved ```/home/(user)/. config/pgmodeler-1.0``` (Linux), ```C:\Users\(user)\AppData\Local\pgmodeler-1.0``` (Windows), ```/Users/(user)/Preferences/pgmodeler-1.0``` (macOS).

> After erasing the files, from the console, access the installation directory and run the command ```pgmodeler-cli -cc -mo``` to recreate the configuration files of the current version. You can now restart pgModeler.

**Comment by nissane** [comment]
thank you.  that fixed it
