### ISSUE TITLE
Table Load CSV Fails to Process Text Delimiter Correctly

### ISSUE THREAD

**Issue by pbryant-phew** [pgmodeler/pgmodeler#1702]
**Bug description**
The issue relates to importing data from text files into tables, through Table properties > Edit data > Load CSV.  When you select Separator=(anything I've tried), and Text delimiter=ON, with any character as the delimiter (tried " ' `), the source file produces something like one single record in the preview frame (typically the very last record from the source file, mashed up and perhaps with 1+ mashed records after it).  When you set Text delimiter=OFF, you get all of the expected source records, but the import preview data includes the text delimiter characters around the imported text (which is the first thing one is trying to avoid when specifying a text delimiter).  Furthermore, the text delimiters are essential for escaping column/field separator characters found within the quoted/delimited text (otherwise those are treated as separator values and they screw up the table field alignment).

It is normal for RDBMS tools (and Excel, LibreOffice, etc) to export data in eg CSV format, with text columns delimited say by double-quotes, specifically to deal with cases where the separator value (eg a comma) is found within a column's text value.  Currently, with the behaviour as it is, the only work-around we have found is to search for and delete cases where a separator value is found within quoted text.  That is a particularly cumbersome work-around since, by definition of the problem, we are looking for the separator character, which, by definition of the problem, appears in billions of legitimate places in the source text file (and I haven't come up with a regex that reliably finds only the cases of a separator between two text separator characters and doesn't find the comma between these two delimited strings `"blah","blah"`).

**How to reproduce**
Create a table:

```
column-1, varchar
column-2, varchar
```

Use Table properties > Edit Data > Load CSV, with Separator=Comma and Text delimiter=ON, with double-quote as the delimiter.
Then try to load a CSV containing the following data:

```
column-1,column-2
"a,",b
"y",z
```

**Expected behavior**
This should result in data being loaded correctly into the Load CSV preview pane as follows:

```
column-1,column-2
a,b
y,z
```

However, with the settings as above you instead get something like this:

```
column-1,column-2
y,z
```
(actually, it is more of a mess than that, but you basically get the last line from the CSV, mashed up in various ways)

And if you don't specify the text delimiter (") you get this (ie extra columns due to the comma in record-1, column1):

```
column-1,column-2,column-3
"a,",b
"y",z,
```

And if you don't specify the text delimiter ("), and you manually remove the comma within the text delimiters around record-1, column-1, you get this (which includes the " characters, which you don't want):

```
column-1,column-2
"a",b
"y",z
```

**Info about your desktop**
 - OS: macOS
 - Version: (all versions to 12.5)
 - pgModeler version: all tested versions up to and including 0.9.4

**Additional info**
This issue was been acknowledged by @rkhaotix via email in Aug 2019, but still seems to be present in 0.9.4.

**Comment by rkhaotix** [comment]
Hi @pbryant-phew 

Sorry my silence in this issue lately. I was focused on finishing 1.0.0-beta. After releasing it, this problem was the first one I started to work on a fix.

Well, I decide to make a deep change on how pgModeler handles CSV files and ended up implementing a CSV parser which obeys strictly the [RFC4180](https://www.rfc-editor.org/rfc/rfc4180). I tested several data models and the results were quite exciting! pgModeler could handle all CSV presented producing the expected results. It's still a work in progress and it demands some polishing but I would like to ask you a copy of the file that caused the bug described in this issue. Could you please send me a copy privately?

**Comment by pbryant-phew** [comment]
Great to hear, @rkhaotix, and thanks for the update.  I don't have a specific example to share with you, and it was just compliance with RFC4180 that I was keen to see in pgModeler, so if you have that covered then great.  A simple test is as follows (and it was lack of support for the first line, as well as strange behaviour when trying to work around that, that we were bumping into):

```
column_1, column_2
"a,",b
"c,d",e
"f,""g""",h
```

(ie all records should produce just two columns)

**Comment by rkhaotix** [comment]
Hey @pbryant-phew 

No problem. I tested several examples of CSV documents compliant with RFC4180 and pgModeler produced the desired results. Even malformed documents were rejected by it. So I think we're on the right path. I even addressed the problem in #1703 without even working directly on it :)

I'll push some more complex tests and see how to tool behaves.

**Comment by pbryant-phew** [comment]
OK great @rkhaotix.  Looking forward to putting it through its paces!

**Comment by rkhaotix** [comment]
@pbryant-phew  You can try this fix now. I've uploaded a snapshot build that includes the fix for this issue!

**Comment by pbryant-phew** [comment]
Thanks vm @rkhaotix.  I'll do some testing and report back here.
