### ISSUE TITLE
[Feature-request] Ctrl + P to have a search box to search and enter to function

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1707]
**Feature description**
As a user of Pgmodeler, I would like Ctrl + P to have a search box, allowing me to access something quickly.

- version 1: simple search box list all function and filter their name
- version 2: more like table name
- version 3: anything you want

I usually work with function

**Sample image**
this is Tableplus application example:

![image](https://user-images.githubusercontent.com/16970990/183604306-a91f054b-e577-43c8-b0ac-67a48ba76c3f.png)

**Comment by hiepxanh** [comment]
is that feature completed sir? I'm using 1.0.1 version but I cannot see this?

**Comment by rkhaotix** [comment]
Yes. It was created in the form of a plugin. If you're using the official packages from the project's site, hit Ctrl+1 to open the search box.

**Comment by hiepxanh** [comment]
oh I see, sir. Have a good day <3 I love this feature so much
