### ISSUE TITLE
1.0.0 Beta Crashes on Windows 11 on startup

### ISSUE THREAD

**Issue by StevenMRobinson** [pgmodeler/pgmodeler#1712]
**Bug description**
After downloading and  installing the Windows installer package from the website, the pgModeler.exe crashes  when double clicking it to start the program.

**How to reproduce**
Run the .exe file on Windows 11 after installing the Beta.

**Expected behavior**
That pgModeler will start up and allow me to use it.

**Screenshots**
![pgModelerBetaStartupError](https://user-images.githubusercontent.com/113693160/190638400-de5b1c2f-5050-4a15-b014-1176ba940b07.png)
![pgModelerBetaStartupError2](https://user-images.githubusercontent.com/113693160/190638476-e8854a9d-5c41-4365-b488-5803ab8b4933.png)
![pgModelerBetaStartupError3](https://user-images.githubusercontent.com/113693160/190638527-e974d27a-3715-403b-8100-4129893229c6.png)

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Hi @StevenMRobinson 

This error occur due to an attribute of the syntax highlight files which was dropped. The solution is to manually erase the files ```*-highlight.conf``` in your *user's local storage* where pgModeler settings are saved: ```/home/(user)/. config/pgmodeler-1.0``` (Linux),```C:\Users\(user)\AppData\Local\pgmodeler-1.0``` (Windows), ```/Users/(user)/Preferences/pgmodeler-1.0``` (macOS).  After erasing the files, start pgModeler again so the erased files can be created again by the tool.
