### ISSUE TITLE
Error while pgModeler is starting

### ISSUE THREAD

**Issue by mariec7** [pgmodeler/pgmodeler#1719]
**Bug description**
During starting pgModeler 1.0.0-beta raise error

**How to reproduce**
Run pgModeler

**Info about your desktop**
 - OS: Windows 11
 - pgModeler version: 1.0.0-beta
 - Qt version: ?

**Stacktrace / Debug info**
[0] src/settings/snippetsconfigwidget.cpp (65)
  SnippetsConfigWidget::SnippetsConfigWidget(QWidget*)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[1] src/utils/syntaxhighlighter.cpp (648)
  void SyntaxHighlighter::loadConfiguration(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 
       ** C:/Users/.../AppData/Local/pgmodeler-1.0/sch-highlight.conf

[2] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 
       ** C:/Users/.../AppData/Local/pgmodeler-1.0/sch-highlight.conf

[3] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group . 

[4] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute partial-match of element group .

**Comment by rkhaotix** [comment]
See here: https://github.com/pgmodeler/pgmodeler/issues/1712

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/193172469-87b84dad-2b5c-422e-b68c-05231b3d61aa.png)
https://pgmodeler.io/blog/2022/9/10/pgmodeler-100-beta-is-finally-here-delivering-important-enhancements
you should do this

**Comment by mariec7** [comment]
Thanks, it helped.
