### ISSUE TITLE
[installation] some depedencies are not found (windows)

### ISSUE THREAD

**Issue by CDecoster** [pgmodeler/pgmodeler#1722]
**Bug description**
when i tried to launch the .exe i have an error who ask me to dl libpcre2-8-0.dll
when i followed the tutorial for the installation i have some dependies that are not found.
is it because i tried for QT5 or QT 6 (i'm using MSYS2 Mingw64 terminal)

https://pgmodeler.io/support/installation at the "Resolving dependencies" chapter

1. echo -e "[Paths]\nPrefix=.\nPlugins=qtplugins\nLibraries=." > /g/pgmodelerOS/qt.conf ==> it does nothing
3. cp libbrotlicommon.dll libbrotlidec.dll libbz2-1.dll libcrypto-1_1-x64.dll libdouble-conversion.dll \
      libfreetype-6.dll libgcc_s_seh-1.dll libglib-2.0-0.dll libgraphite2.dll libharfbuzz-0.dll libiconv-2.dll \
      libicudtd*.dll libicudt*.dll libicuind*.dll libicuin*.dll libicuucd*.dll libicuuc*.dll libintl-8.dll \
      liblzma-5.dll libpcre-1.dll libpcre2-16-0.dll libpng16-16.dll libpq.dll libssl-1_1-x64.dll libstdc++-6.dll \
      libwinpthread-1.dl libxml2-2.dll libzstd.dll zlib1.dll /g/pgmodelerOS ==> 

output : cp: cannot stat 'libicudtd*.dll': No such file or directory
cp: cannot stat 'libicuind*.dll': No such file or directory
cp: cannot stat 'libicuucd*.dll': No such file or directory
cp: cannot stat 'libpcre-1.dll': No such file or directory
cp: cannot stat 'libwinpthread-1.dl': No such file or directory

so i tried with the 6.2

4.   cp D3Dcompiler_47.dll libb2-1.dll libbrotlicommon.dll libbrotlidec.dll libbz2-1.dll libcrypto-1_1-x64.dll \
      libdouble-conversion.dll libfreetype-6.dll libgcc_s_seh-1.dll libglib-2.0-0.dll libgraphite2.dll \
      libharfbuzz-0.dll libiconv-2.dll libicudt*.dl libicuin*.dll libicuuc*.dll libintl-8.dll liblzma-5.dll \
      libmd4c.dll libpcre-1.dll libpcre2-16-0.dll libpng16-16.dll libpq.dll libssl-1_1-x64.dll libstdc++-6.dll \
      libwinpthread-1.dll libxml2-2.dll zlib1.dll $INSTALLATION_ROOT

output : 

cp: cannot stat 'D3Dcompiler_47.dll': No such file or directory
cp: cannot stat 'libicudt*.dl': No such file or directory
cp: cannot stat 'libpcre-1.dll': No such file or directory

for the 4 mkdir /g/pgmodelerOS/qtplugins/tls

output : 
mkdir: cannot create directory ‘/g/pgmodelerOS/qtplugins/tls’: No such file or directory

and finally the last step : cp -r /c/msys64/mingw64/share/qt6/plugins/platforms/tls/* /g/pgmodelerOS/qtplugins/tls

output : cp: cannot stat '/c/msys64/mingw64/share/qt6/plugins/platforms/tls/*': No such file or directory

**Info about your desktop**
 - OS:windows
 - Version:10
 - Window manager:
 - pgModeler version:[Merge branch '1.0.0-beta' into develop](https://github.com/pgmodeler/pgmodeler/commit/2b12a86165c8dc163eb21f5a4c9b7813fd666d10)
 - Qt version:qt5(open source)

thanks a lot for the help

**Comment by CDecoster** [comment]
i just had to cp the file directly from the file and it work

**Comment by zengtengcq** [comment]
> i just had to cp the file directly from the file and it work

where did you cp the missing files from? i have the same issue, and in my folder x:\xx\msys64\mingw64\bin there are no such files.
