### ISSUE TITLE
Warning on reserved keywords

### ISSUE THREAD

**Issue by GeertJohan** [pgmodeler/pgmodeler#1725]
**Feature description**
I was creating a new table in my design and the resulting SQL (generated by pgmodeler) didn't apply well. I got an SQLSTATE 42601 message. I couldn't find the syntax error. I thought it had to do with inheritance, which I used for the first time through pgmodeler. After a while I found out it was because I named by table `usage`, which is a reserved keyword in postgres.

The errors from postgres can be very obscure, this is an issue by itself. But meanwhile it would be nice if pgmodeler would show warnings when reserved keywords are used as identifiers for objects like tables, columns, functions, etc.

**Comment by rkhaotix** [comment]
Actually, pgModeler treats reserved words when naming objects and in the presence of such keywords the object's name is automatically double-quoted. Maybe I need to update the reserved keywords list.

Could you please attach here the entire SQL code of the failing object?

**Comment by GeertJohan** [comment]
My apologies @rkhaotix , I seem to have misdiagnosed the problem here.
The issue was not the `usage` keyword at all. I should've done a clean reproduction before reporting, sorry.

The issue was a missing comma in the creating of a table that uses inheritance:
```sql
CREATE TABLE foo.bar (
	a integer NOT NULL,
	b smallint NOT NULL,
	c smallint NOT NULL -- << Missing comma here
-- 	id bigint NOT NULL DEFAULT nextval('finance.quux_id_seq'::regclass),
-- 	y smallint NOT NULL,
-- 	z integer,
	CONSTRAINT bar_uq_a_b_c UNIQUE (a,b,c)
)
 INHERITS(finance.quux);
 ```

However, I just compiled tag v1.0.0-beta and found that the issue is fixed there.

**Comment by rkhaotix** [comment]
No problem, thanks! :)
