### ISSUE TITLE
Running diff throws owner error on Mac but not Windows.

### ISSUE THREAD

**Issue by GollyJer** [pgmodeler/pgmodeler#1727]
I don't fully understand this so I'll do my best to describe what I'm seeing.
I'm using pgmodeler-1.0.0-beta1_snapshot20221018 on both platforms.

I created a local database using the Export function of pgModeler on both platforms. Works great.

I have a cloud based database with no tables, just the database name.

If I use the Diff function in pgModeler from a Windows computer, it works great and creates the same schema in the cloud as the local database.

If I follow the same procedure from a MacOS computer, running the Diff function in pgModeler results in this error.
```The object `ingredient_db' (Database) is referencing the object `jeremy' (Role) which was not found in the model!```

I'm not sure where the `jeremy` role is coming from. I haven't specified it in pgModeler or the cloud database.
It is my macOS username.

Here's the Extra Info tab if it helps.

```
-- Raw attributes: ingredient_db (OID: 24576) --
active-layers: 
allow-conns: true
append-at-eod: 
comment: 
connlimit: -1
encoding: UTF8
is-template: 
layers: 
lc-collate: C
lc-ctype: C
name: ingredient_db
object-type: 21
oid: 24576
owner: 	<role name="jeremy"/>

permission: {=Tc/admin,admin=CTc/admin,web_access=C/admin}
pgsql-ver: 15.0
prepend-at-bod: 
sql-disabled: 
tablespace: 	<tablespace name="pg_default"/>

template: 
---
```

Let me know what else I can provide.
Thanks!

**Comment by rkhaotix** [comment]
Hey @GollyJer 

Did the diff works locally on both platforms?

For example, if you have an empty database on the local server when you runs the diff it raises the error?

**Comment by GollyJer** [comment]
Hey @rkhaotix. Thanks for the response.

Yeah, creating an empty database and then applying diff works on both platforms. (just checked).

But, after creating an empty local database on Windows and Mac, when I run `SELECT * FROM pg_roles` I see `jeremy` in the list of roles.
I guess postgres creates new databases by creating a role named after the logged in user?

And that role doesn't exist in the cloud database, hence the error?

It doesn't explain why Diff to the cloud database works on Windows, though. 🤔
Head scratcher...

Here's the macOS log.
<img width="433" alt="Screenshot 2022-11-21 at 1 29 05 PM" src="https://user-images.githubusercontent.com/689204/203161823-b91d1ec0-756e-4e50-9066-0551cd3ae8e9.png">

**Comment by rkhaotix** [comment]
Really strange. I'll investigate.

What are the PostgreSQL versions involved?

**Comment by GollyJer** [comment]
PostgreSQL 15.0 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by GollyJer** [comment]
I think this might have to do with the Default "Owner" field being set to `postgres` since the cloud db doesn't have that role/user.

In pgModeler I'm not specifying the owner in the tables so it's using the `postgres` default. I'd like to change the default to `admin` but don't see how to add an owner in pgModeler. It only let's me pick from a list and only includes `postgres`.

(sorry I'm over my skis a bit in this area)

**Comment by GollyJer** [comment]
OK, more digging. 

When using Windows and doing pgModeler DIFF on the remote database, all the tables are owned by `admin` (the user connected to the database). Remote database has an `admin` user and not a `postgres` user. (we don't control this)

Doing the DIFF to localhost the databases are all owned by `postgres`. There is no `admin` user.

I feel like I need synchronise the Owner field by making sure each database has the same logged in user when creating the tables.

**Comment by rkhaotix** [comment]
Are you making a diff between two databases or between a model and a database? If you have a model, could you please share it (privately)?

**Comment by GollyJer** [comment]
It is from a .dbm model to each of the databases.

I was actually able to create a `postgres` user on the cloud database. At that point everything started working on both platforms in the same way. 💪

Another oddity while testing is that I have to run DIFF twice when initially creating the tables because a foreign key isn't created the first time.

I'll send you the model. Where should I send it? Thanks.

**Comment by rkhaotix** [comment]
> It is from a .dbm model to each of the databases.
> 
> I was actually able to create a `postgres` user on the cloud database. At that point everything started working on both platforms in the same way. 

That's great!

> Ideally I'd like to understand how to set the table owner in pgModeler to something other than postgres, but for now I can keep moving forward.

You can set owners to database objects in 2 different ways:

1) Directly from the object's editing form, field "Owner".
2) From the context menu in the designing area, by selecting the desired objects, then right-click over the selection and activate the menu item Quick > Change owner 

> Another oddity while testing is that I have to run DIFF twice when initially creating the tables because a foreign key isn't created the first time.

There some very few cases that this can happen, I'll check that too.

**Comment by GollyJer** [comment]
Thanks for the awesome suport @rkhaotix. 💪

> You can set owners to database objects in 2 different ways:
> 
>     1. Directly from the object's editing form, field "Owner".
> 
>     2. From the context menu in the designing area, by selecting the desired objects, then right-click over the selection and activate the menu item Quick > Change owner
> 

Sorry, I'm being dense. 
How do you get other options besides `postgres` to choose from? In the dialogs and in the context I can only ever choose none or postgres. You can't enter anything freeform into the text field and using the magnifying glass UI only allows picking postres also.


<img width="518" alt="Screenshot 2022-11-22 at 11 28 35 AM" src="https://user-images.githubusercontent.com/689204/203404581-93cc7c0a-b9ce-4543-b7fa-f37415cc9632.png">

**Comment by rkhaotix** [comment]
Oh, I forgot to mention that the list of owners is filled with the roles you have created in the model. So, you need to create the roles first before using the steps I provided.

You can create a role by right click the design area and choose New > Database object> Role

**Comment by rkhaotix** [comment]
@GollyJer just to give you a return...

I've tested the model that you sent me, everything runs fine without a single error. The only "problem" I found is that two unique constraints were created after running the diff twice as you mentioned before. I've patched the diff and it seems that is working ok.

**Comment by GollyJer** [comment]
Sounds good! 
Thanks for the support @rkhaotix.
