### ISSUE TITLE
PostgreSQL Version8.4

### ISSUE THREAD

**Issue by Zineda-yoshi** [pgmodeler/pgmodeler#1729]
Is there a way to import postgre SQL Version8.4?

When I try to import I get the following error:
 Unsupported PostgreSQL version (8.4) detected Valid versions are between 9.0 and 13.0.

Is it possible to get an installer for an older version?

**Comment by rkhaotix** [comment]
Well, PostgreSQL 8.x support was dropped nine years ago and the support for PostgreSQL 9.x removed in 1.0.0-alpha1. 

The best you can do is to dump the 8.4 database and restore it in a 9.x database server, and then import it using the current version you're using.
