### ISSUE TITLE
ON UPDATE label missing in Relationship properties  (v1.0.0-beta1)

### ISSUE THREAD

**Issue by mperezfra** [pgmodeler/pgmodeler#1735]
**Bug description**
In the spanish translation of the relationship properties, in the tab "Settings" the ON UPDATE label is written as ON DELETE, i.e. ON DELETE appears twice

**How to reproduce**
Execute pgmodeler in spanish.
In a pgmodeler model, double click on a relationship and select "Settings" tab

**Screenshots**
![imagen](https://user-images.githubusercontent.com/6173579/213992041-98ff4084-18b8-48f0-81f6-7a08ac1ac750.png)

**Info about your desktop**
 - OS: Linux 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2
 - Window manager: Cinnamon
 - pgModeler version:v1.0.0-beta1

**Comment by rkhaotix** [comment]
This is a problem with the Spanish translation file. I've dropped the outdated translation files and now it should the correct label (in English).
