### ISSUE TITLE
Erro ao inicializar o aplicativo

### ISSUE THREAD

**Issue by pedrostefanogv** [pgmodeler/pgmodeler#1739]
**Bug description**
plugin ssh tunel não carrega, diretório não existe 

**How to reproduce**
Ao abrir o aplicativo usando o ZorinOS ocorre o erro.

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**
https://i.imgur.com/CS3Lfio.png

**Info about your desktop**
 - OS: ZorinOS (ubuntu)
 - Version: Pro 16,2
 - Window manager: Gnome
 - pgModeler version: 1.0.0
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

[0] src/settings/pluginsconfigwidget.cpp (142)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginsNotLoaded] One or more plugins were not activated due to errors during the loading process! Check the exception stack for more details.

[1] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `sshtunnel' from the library `/tmp/.mount_pgmodeyDxHJD/plugins/sshtunnel/libsshtunnel.so'! Message returned by plugin manager: `Cannot load library /tmp/.mount_pgmodeyDxHJD/plugins/sshtunnel/libsshtunnel.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'

[2] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `splitmodel' from the library `/tmp/.mount_pgmodeyDxHJD/plugins/splitmodel/libsplitmodel.so'! Message returned by plugin manager: `Cannot load library /tmp/.mount_pgmodeyDxHJD/plugins/splitmodel/libsplitmodel.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'

[3] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `quickedit' from the library `/tmp/.mount_pgmodeyDxHJD/plugins/quickedit/libquickedit.so'! Message returned by plugin manager: `Cannot load library /tmp/.mount_pgmodeyDxHJD/plugins/quickedit/libquickedit.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'



**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Rapaz, muito estranho. A ```libQt6UiTools.so.6```está em ```/tmp/.mount_pgmodeXXXXX/lib```.

Acredito que pode estar acontecendo algum conflito de libs no seu sistema. Tente fazer o seguinte pelo console:

```
$> ./pgmodeler-1.0.0-linux64.appimage --appimage-mount
$> cd /tmp/.mount_pgmodeXXXXX [troque o XXXXX pelos caracteres da pasta temporaria gerada no comando anterior]
$> LD_LIBRARY_PATH=/tmp/.mount_pgmodeXXXXX/lib ./pgmodeler
````

E veja se o pgModeler executa normalmente.

**Comment by pedrostefanogv** [comment]
Com os comandos abriu sem erro e carregou os plugins
https://i.imgur.com/ILWwBgn.png

Eu fiz a instalação. E ao executar dá o mesmo erro parecido também
Talvez durante o processo de execução/instalação algum arquivo/pasta não esta sendo copiado para a pasta de plugin 


Pilha de erro ao executar o pg instalado no ZorinOs

[0] src/settings/pluginsconfigwidget.cpp (142)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginsNotLoaded] One or more plugins were not activated due to errors during the loading process! Check the exception stack for more details.

[1] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `sshtunnel' from the library `/opt/pgModeler/plugins/sshtunnel/libsshtunnel.so'! Message returned by plugin manager: `Cannot load library /opt/pgModeler/plugins/sshtunnel/libsshtunnel.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'

[2] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `splitmodel' from the library `/opt/pgModeler/plugins/splitmodel/libsplitmodel.so'! Message returned by plugin manager: `Cannot load library /opt/pgModeler/plugins/splitmodel/libsplitmodel.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'

[3] src/settings/pluginsconfigwidget.cpp (133)
  virtual void PluginsConfigWidget::loadConfiguration()
    [PluginNotLoaded] Could not load the plugin `quickedit' from the library `/opt/pgModeler/plugins/quickedit/libquickedit.so'! Message returned by plugin manager: `Cannot load library /opt/pgModeler/plugins/quickedit/libquickedit.so: (libQt6UiTools.so.6: não é possível abrir arquivo compartilhado: Arquivo ou diretório inexistente)'

**Comment by rkhaotix** [comment]
Eu já detectei o problema. Vai ser corrigido na 1.0.1 :)
Na próxima semana já subo os binários corrigidos
