### ISSUE TITLE
Infinite Canvas

### ISSUE THREAD

**Issue by Swivelgames** [pgmodeler/pgmodeler#1741]
**Feature description**
Many diagramming applications available now have implemented the concept of an "Infinite Canvas". More often than not, this is useful for centering your viewport on what you're trying to focus on at that particular moment.

**Sample image**
![image](https://user-images.githubusercontent.com/1456302/217474949-407b24a8-d10b-43ad-8efc-d3e9d53575f8.png)
![image](https://user-images.githubusercontent.com/1456302/217477369-b9a003d0-8a9e-4d60-87d5-973ea882735f.png)

**Additional info**
This is possible with pgModeler unless the item you're trying to center is at the west-most or north-most portions of the diagram. At which point, they're always at the edge of the screen. The only way to alleviate that is to either deal with it, or shift your entire diagram to the south-east, which is less than desirable. It would be useful if the canvas was "infinite".

**Implementation Considerations**
Not to doom my own proposal, but since there is tooling in place that is based on the premise of having a `0,0` in the top left position, there may be some things to consider when undertaking this. In most implementations, determining `0,0` is often only necessary in the case of printing or displaying page delimiters. Outside of that, negative X and Y coordinates are acceptable and shouldn't be an issue (outside of potentially having to use signed types instead of unsigned, if that's the case here). (_Although, compatibility with older versions of pgModeler after this feature is implemented might be a consideration._)

When printing or displaying page delimiters, the X-Origin and Y-Origin can be offset by using the X coordinate of the west-most object, and the Y coordinate of the north-most object. Hopefully that alleviates some of the fears or concerns with a major refactor to introduce this type of functionality.

The potentially heavier implementation might be to recalculate the origin, given that you would need to update the position of every object in the diagram. This wouldn't be terribly difficult (iterate and `obj.x += -1 * westMostObj.x`, `obj.y += -1 * northMostObj.y`), but definitely tedious and potentially expensive depending on the size of the graph.

Another option would be to allow Infinite Canvas to be a toggleable as a feature as a "Free Form Canvas" of sorts. At which point, it would disable Page Delimiters or other features that require non-negative coordinates. I'm not entirely sure that would be desirable to users though, and it may actually be less easy to maintain from a development perspective since you would have branching-logic-dependent features at that point.

**Comment by rkhaotix** [comment]
Hi @Swivelgames 

I think your point is really valid. But the main problem is that pgModeler works with positive coordinates. So,  Changing it to accept negative ones will break A LOT of things at a first glance. I don't discard your suggestion but I need to study it carefully before deciding to implement it. 

I will try some tests and see how pgModeler behaves.

**Comment by Swivelgames** [comment]
Sounds good! Very interested in what you'll find :slightly_smiling_face:

**Comment by Swivelgames** [comment]
@rkhaotix I just thought of a bit of a compromise, which would be to make it pseudo-infinite. Effectively, the view for new diagrams could _start_ at `x = (4 * page_width); y = (4 * page_height)` or something similar, and then omit empty pages when printing. That would give designers a 4 page buffer to play with.

If you really wanted to go the extra mile with a pseudo-infinite canvas, you could also start out new diagrams are something crazy like 1000 * page_width/height, and then only include pages with objects in them when printing.

I don't want to scope creep this one issue too much, but there could even be a Phase 2 of the feature that could be worked on after the feature is launched that has "Smart Page Delimiters" that adjust themselves by aligning page delimiters to the Y of the north-most object, and the X of the west-most object. But that might be quite the undertaking.

I know I'm already asking quite a bit here :sweat_smile:

**Comment by rkhaotix** [comment]
Hi @Swivelgames 

Sorry the delay on response.

Don't worry, you're not bothering me or asking too much.. actually your ideas are promising and may not affect the core code or at least will demand less changes than implementing a real infinite canvas .

I'll try some tests on 1.1.0-alpha and see how it behaves. :)

**Comment by rkhaotix** [comment]
@Swivelgames sorry for the huge delay in taking care of this issue... 

It turns out that implementing the "real" infinite canvas was pretty much easier than creating a faking one. The basics of the infinite canvas are working now. You can move objects in any direction and objects now can lay on negative coordinates without problem, since pgModeler will not lock them on the origin point (0,0) anymore. :)

I'm testing other features tied to the canvas like printing and exporting to PNG. So far, everything is ok! I'm closing the issue since the base request is covered.

**Comment by Swivelgames** [comment]
@rkhaotix That's awesome to hear! Thanks so much for putting in the time for this enhancement! I'll have to try it out once I get back to my machine 🎉
