### ISSUE TITLE
Diff Issues - Process Freezes with 1.0.0

### ISSUE THREAD

**Issue by tmollitor-ttec** [pgmodeler/pgmodeler#1742]
**Bug description**
When trying to use the Diff Tool, the process freezes with the new 1.0.0 code.  I am not having any issues doing a diff with the 1.0.0-beta version using the same model against the same Postgres 15 database.  Process freezes when "Creating columns permissions..." during "Step 1/3 Importing Database".  This happens both when doing a full database diff or a partial diff (Generating filters from changelog for the past hour).

**How to reproduce**
Open Diff Tool
Input-> Select Current model
Compare to-> Select local-db connection and Postgres 15 database
Store in SQL File

**Expected behavior**
Create difference script.  This works successfully using a 1.0.0-beta version compiled in December

**Screenshots**
Full Diff:
![image](https://user-images.githubusercontent.com/110556199/217892516-b1923d4e-7fb4-4a90-bd84-2ca5c0a7ef1b.png)

Partial Diff:
![image](https://user-images.githubusercontent.com/110556199/217892571-aca7d1c0-708b-47ce-bc61-a12605ec24ea.png)

**Info about your desktop**
 - OS:  Windows 10
 - Version: 10
 - Window manager:
 - pgModeler version: 1.0.0 (Main branch)
 - Qt version: 6.3.2

**Stacktrace / Debug info**
pgModeler freezes, but I do not see a stack trace

**Additional info**
Same behavior against a DB version hosted in the cloud.  And again, difference scripts can still be generated using 1.0.0 beta version

**Comment by rkhaotix** [comment]
Hi @tmollitor-ttec 

Is it possible for you to share the database model so I can see what's going on? I've tested the diff with several sample models I have and they work perfectly fine on PG15. Maybe is something with your model/database.

**Comment by tmollitor-ttec** [comment]
Hi @rkhaotix

Thanks for your quick reply.

I've simplified my model down to one table, and created a new PG15 database using the script generated from the model.  I then attempted to run the diff, with the same results.

I'm attaching the model, a generated DB script, and a screenshot with the new diff results.

[Example.zip](https://github.com/pgmodeler/pgmodeler/files/10700701/Example.zip)

![image](https://user-images.githubusercontent.com/110556199/217914591-83155165-612c-4646-aa44-071caef41bbb.png)

Thanks,
Tom

**Comment by rkhaotix** [comment]
Surprisingly, your sample model worked on my environments, Linux and Windows 10. That's kinda strange 🤔

**Comment by tmollitor-ttec** [comment]
I just tried an Import of my 1 table example PG15 database into a brand new model, with similar results.  Maybe something to do with the database import rather than the model itself?  

![image](https://user-images.githubusercontent.com/110556199/217946482-88c28ff1-a883-4dd5-95ce-e29dc20fa384.png)

**Comment by rkhaotix** [comment]
I tried with import and diff as well... Both worked fine. Very strange. I'll keep investigating.

Do you run pgModeler only on Windows? If not, could you try on Linux but importing from the same database server? Maybe it's something with the database server...

**Comment by tmollitor-ttec** [comment]
Yes, only running on Windows.  I don't currently use Linux.  However, I have tried importing from both my localhost, and a PG15 database hosted in Google Cloud.  Same results for both.

Are there possibly some local cached settings that I need to delete?

**Comment by rkhaotix** [comment]
No, there are no cached settings.

Did you compile pgModeler? Try with Qt 6.4 and the latest commit on branch 1.0.1. I'm testing your model with that codebase.

**Comment by tmollitor-ttec** [comment]
Yes, I did compile.  I was having the issue with a 1.0.0 branch I had grabbed in January, and I saw you had an official release of 1.0.0 since then, so I grabbed the Main branch and recompiled yesterday, but had the same result.

I will upgrade to Qt 6.4 and get 1.0.1, and let you know how it goes.

Thanks for your help!

**Comment by tmollitor-ttec** [comment]
Unfortunately no luck.  I upgraded to Qt 6.4 and build with 1.0.1, but still stuck in the same place :(

![image](https://user-images.githubusercontent.com/110556199/218176631-b0e1ded7-4a12-464e-a8c0-8cec35f2987b.png)

**Comment by rkhaotix** [comment]
That's weird, really! Are you able to run pgModeler against another database server? Different from both you tested?

Also, could you provide me a full dump (without data) of your database?

**Comment by tmollitor-ttec** [comment]
I currently only have my localhost and the cloud instance.  However, the database is empty, with the 1 empty table, which was generated from the script pulled from pgModeler.

In fact, the issue happens if I uncheck the entire schema and just try to import 1 role ( I have to select something or the Import button is not activated).

![image](https://user-images.githubusercontent.com/110556199/218180485-1dde50d9-ad10-40e6-b83b-90e663d05bfe.png)

![image](https://user-images.githubusercontent.com/110556199/218180526-7cb66b14-3bc5-414e-9748-f7c2f1d3ee6b.png)

I attached the DB script yesterday, but here it is again:
[example.txt](https://github.com/pgmodeler/pgmodeler/files/10710563/example.txt)

**Comment by rkhaotix** [comment]
> In fact, the issue happens if I uncheck the entire schema and just try to import 1 role ( I have to select something or the Import button is not activated).

Oh, that gives me some clue. I'll try that.

**Comment by tmollitor-ttec** [comment]
And just as a test, I moved the App to a completely different Windows machine, and am getting the same result.

**Comment by tmollitor-ttec** [comment]
Not sure if it is something with my build.  I don't know if this helps, but this is the contents of my app folder:

[app_folder_contents.txt](https://github.com/pgmodeler/pgmodeler/files/10711681/app_folder_contents.txt)

I followed the instructions here (https://pgmodeler.io/support/installation), and it was mostly straight forward, though I had to find a couple of additional missing dependencies from C:\msys64\mingw64\bin.  Also, this command failed because the platforms and tls folders were both straight under plugins, so I don't know if my qtplugins folder is correct:  cp -r $MSYS2_ROOT/mingw64/share/qt6/plugins/platforms/tls/* $INSTALLATION_ROOT/qtplugins/tls

**Comment by terrycain** [comment]
So just to add my experiences here. I encountered this exact issue on Ubuntu 22.04 when building pgModeler with qt5. After installing the required qt6 packages and convincing qmake to use qmake6 and not 5, said issue went away.

**Comment by tmollitor-ttec** [comment]
@terrycain Thanks!  I'm still dealing with the issue.  I thought I had uninstalled qt5, but it looks like qmake may have used qt5 packages instead of 6:

#############################################################################
# Makefile for building: pgmodeler
# Generated by qmake (3.1) (Qt 5.15.8)
# Project:  pgmodeler.pro
# Template: subdirs
# Command: C:/msys64/mingw64/bin/qmake.exe -o Makefile pgmodeler.pro CONFIG+=release PREFIX=C:/pgModeler/app
#############################################################################

How did you convince qmake to use qt6?

**Comment by rkhaotix** [comment]
@tmollitor-ttec instead of q make.exe try using qmake-qt6 or qmake6

**Comment by tmollitor-ttec** [comment]
Thank you!  The import and diff operations are now both working for me on initial testing!

Just for reference, I also ran windeployqt-qt6 rather than windeployqt as the later was giving me an error.

Thanks again for your help!

**Comment by terrycain** [comment]
@rkhaotix is there a way you can have the makefile complain if its linked to qt5? That might avoid others making these errors in future?

**Comment by rkhaotix** [comment]
I'll make some researches and see if it's possible to abort the building when building with Qt 5 also I can update the installation procedures to indicate the use of Qt 6 only
