### ISSUE TITLE
update policy not work because work syntax (version 1.0.1)

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1745]
**Bug description**
alter policy seem not work because:
 ` ALTER POLICY public.books.update_books` should be 
 ` ALTER POLICY  update_books on  public.books`

**How to reproduce**
just run normal file

**Expected behavior**
should work, look like this one not work because wrong generate syntax

![image](https://user-images.githubusercontent.com/16970990/219938532-6987d0d8-1d4b-4165-8568-558003983d94.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/16970990/219938484-f08061bb-b0dc-40a1-bc50-6e4d9cd59846.png)

![image](https://user-images.githubusercontent.com/16970990/219938490-2a97bbdd-45cc-46d7-806f-141f6866144b.png)

![image](https://user-images.githubusercontent.com/16970990/219938500-1affc982-ab6c-42e6-918b-6e5a5e65ed7b.png)

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

[0] src/tools/modeldatabasediffform.cpp (880)
  void ModelDatabaseDiffForm::captureThreadError(Exception)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "."
LINE 1: ALTER POLICY public.books.update_books
                           ^
'

[1] src/tools/modelexporthelper.cpp (31)
  void ModelExportHelper::abortExport(Exception&)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "."
LINE 1: ALTER POLICY public.books.update_books
                           ^
'

[2] src/tools/modelexporthelper.cpp (44)
  void ModelExportHelper::handleSQLError(Exception&, const QString&, bool)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "."
LINE 1: ALTER POLICY public.books.update_books
                           ^
'
       ** ALTER POLICY public.books.update_books
	USING ("userId" = nullif(current_setting('jwt.claims.userId', true), '')::uuid);


[3] src/connection.cpp (500)
  void Connection::executeDDLCommand(const QString&)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "."
LINE 1: ALTER POLICY public.books.update_books
                           ^
'
       ** 42601



**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Thanks @hiepxanh 

I know what's going on.

I'll provide a fix ASAP.

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/221391187-556495a8-f7ab-4413-a828-e1e6b54f7c66.png)

drop policy have the same issue, I have to modify it manually @rkhaotix
