### ISSUE TITLE
Model import fails 

### ISSUE THREAD

**Issue by clairvoyant** [pgmodeler/pgmodeler#1749]
**Bug description**
PgModeler fails to import any model. (tested with 4 diferent SQL models)

**How to reproduce**
It's always reproducible in every model. I have old models that were imported without problems in the past (versions prior to 1.0.0) but now they are always stuck in the middle of the import process. 

if can fail in diferent points. 
* If only user model is imported, then it fails in the "creating user permision". 
*  If the table & secquences are also imported, it fails when importing "sequences".

**Expected behavior**
I expect the import process to finish and show the model. 

**Screenshots**
_If applicable, add screenshots to help explain your problem._
![pgmodeler](https://user-images.githubusercontent.com/4071497/221377919-720d09a2-34d7-4132-8bd0-37017189f33e.png)

**Info about your desktop**
 - OS: openSUSE
 - Version: 15.4
 - Window manager: Tested on xfce, windowmaker and KDE Plasma
 - pgModeler version: 1.0.1
 - Qt version: 5-5.15

**Stacktrace / Debug info**
_If pgModeler doesnt crash but following exception shows up in the xterm. 

```
QObject::connect: Cannot queue arguments of type 'Exception'
(Make sure 'Exception' is registered using qRegisterMetaType().)

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Try to build it using Qt 6. There's a similar problem that happens only when building with Qt 5 (#1742 )

**Comment by clairvoyant** [comment]
> Try to build it using Qt 6. There's a similar problem that happens only when building with Qt 5 (#1742 )

Thanks, for the quick answer. 
I will try to build with Qt 6. 

In case it helps, the bisect by version is:

v0.9.4:             Ok. 
v1.0.0-alpha:  Ok
v1.0.0-alpha:  Ok
v1.0.0-alpha1: Ok
v1.0.0-beta:    Fails
v1.0.0:             Fails
v1.0.1:             Fails

**Comment by clairvoyant** [comment]
Closing as duplicate of (https://github.com/pgmodeler/pgmodeler/issues/1742 )

**Comment by rkhaotix** [comment]
> QObject::connect: Cannot queue arguments of type 'Exception'
(Make sure 'Exception' is registered using qRegisterMetaType().)

This message explains a lot. I've changed the way qmetatypes are declared and seems Qt5 doesn't work well with it. Since I have no intention to keep supporting Qt 5 I recommend that all users build pgModeler with Qt 6 I even updated the installation instructions to reflect that situation.
