### ISSUE TITLE
How can the shadows be removed.

### ISSUE THREAD

**Issue by DcPublished** [pgmodeler/pgmodeler#1750]
**Feature description**
_A clear and concise description of what the problem is._
Shadows on table object look nice, waste space.  How can they be removed?

**Sample image**
_If the feature requested is a visual improvement, please, attach some images to make it clear._

**Additional info**
_Add any other context or screenshots about the feature request here._

**Comment by rkhaotix** [comment]
For now they can't be removed. But I can add an option in future releases to hide them.

**Comment by DcPublished** [comment]
Thank you.  That would be good.

Best,

Dan.

**Comment by DcPublished** [comment]
Cool.  Thanks.

Dan.
