### ISSUE TITLE
 'object already exists' errors 

### ISSUE THREAD

**Issue by jmollerhoj** [pgmodeler/pgmodeler#1755]
**Bug description**
I get a lot of 'already exists' errors. For instance when I look at the properties for a schema/user and then click apply. If I delete the object and I try to recreate it, I get the same error. 

**How to reproduce**
Not sure. Something seems out of sync. 

**Expected behavior**
Being able to change the properties for an object like role and schema.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: Arch Linux / appimage
 - Version: 6.2
 - pgModeler version: 1.0.1
 - Qt version: 6.4.1

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

[0] src/dbobjects/rolewidget.cpp (275)
  virtual void RoleWidget::applyConfiguration()
    [AsgDuplicatedObject] The object `users' (Role) already exists on `test' (Database)!

[1] src/dbobjects/baseobjectwidget.cpp (778)
  virtual void BaseObjectWidget::applyConfiguration()
    [AsgDuplicatedObject] The object `users' (Role) already exists on `test' (Database)!

[2] src/dbobjects/baseobjectwidget.cpp (734)
  virtual void BaseObjectWidget::applyConfiguration()
    [AsgDuplicatedObject] The object `users' (Role) already exists on `test' (Database)!


```

**Additional info**
Seems like pgmodeler is keeping ghost objects somewhere which makes the app complain about 'already exists'.

**Comment by rkhaotix** [comment]
Do you have a sample model that this issue happens?
