### ISSUE TITLE
Please don't trigger code completion when I type a period inside of a comment or text field.

### ISSUE THREAD

**Issue by StevenMRobinson** [pgmodeler/pgmodeler#1769]
As the title says.  I'm on the latest test version.  It's a bit annoying when the code completion dialog pops up every time I type a period inside of a text field or a comment.  Should restrict the code completion to those elements that it makes sense for.

**Comment by rkhaotix** [comment]
The latest version (1.1.0-alpha) is still under development and bugs are expected... Anyway, about the completion to be triggered in the middle of comments it was already planned to be patched. Now, could you be more specific about what text fields are triggering the completion? Thanks

**Comment by StevenMRobinson** [comment]
Hi Raphael,

Sounds good.  I only filed this to make sure you were aware of it, it's only a minor irritation.  When I create text in a query is where it was happening, any generic text, from the looks of it.  So if I do something like:

UPDATE my_table SET my_value = 'Text. field. with. periods.'  

Every time I type a period inside the quoted area, the code completion dialog box pops up with no suggestions.  Happens with in the scenario where I only have a single quote to the left of the text and in the scenario where I'm inside a completed quote with both single quotes there.   

Also happens when I have a -- for a comment in the query.  If I type:

 -- Some text with a period.  

The code completion dialog pops up in this scenario as well.  Hope this helps!  Great product, I use it daily!

**Comment by rkhaotix** [comment]
Hey @StevenMRobinson 

Thanks for the detailed report!  Now I have a clear vision of how to work to fix the problem!

Glad to hear that you like pgModeler! :)
