### ISSUE TITLE
Malfunction in getCatalogQuery method of Catalog class

### ISSUE THREAD

**Issue by enjoy12e** [pgmodeler/pgmodeler#1772]
**Bug description**
Method Catalog::getCatalogQuery build bad SQL query without space before WHERE clause. It happens during import and diff processes. 

**How to reproduce**
Start regular import or diff action cause error with bad SQL request to database
SELECT ... FROM pg_rolesWHERE ...

**Info about your desktop**
 - OS: Linux
 - Version: CentOS 7
 - Window manager: mate
 - pgModeler version: 1.0.4
 - Qt version: 6.5.0

**Additional info**
lines 459 and 469 of 
[pgmodeler](https://github.com/pgmodeler/pgmodeler)/[libs](https://github.com/pgmodeler/pgmodeler/tree/develop/libs)/[libconnector](https://github.com/pgmodeler/pgmodeler/tree/develop/libs/libconnector)/[src](https://github.com/pgmodeler/pgmodeler/tree/develop/libs/libconnector/src)/catalog.cpp
```
pos = sql.length();
```
retrieve last position of query string, but after in line 475 appends WHERE clause exact in the end of string:
```
sql.insert(pos, custom_filter);
```
but it make SQL (in my case) ...FROM pg_rolesWHERE... without space character.

Change both lines to 
```
pos = sql.length()+1;
```
solve the problem for me.
Maybe, you can change string in 451 to " WHERE..." also solve problem. But its no tested yet.

I can provide more info, if you need.

**Comment by enjoy12e** [comment]
**Screenshot of error**
![issue_1_1](https://user-images.githubusercontent.com/45516205/235198798-72a37c5f-43db-453a-93ae-bd7114ebfe47.png)

**Stack trace**
[0] src/tools/databaseimportform.cpp (584)
  void DatabaseImportForm::captureThreadError(Exception)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'

[1] src/tools/databaseimporthelper.cpp (665)
  void DatabaseImportHelper::importDatabase()
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'

[2] src/tools/databaseimporthelper.cpp (523)
  void DatabaseImportHelper::createPermissions()
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'

[3] src/catalog.cpp (935)
  QString Catalog::getObjectOID(const QString&, ObjectType, const QString&, const QString&)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'
       ** Object type: role

[4] src/catalog.cpp (501)
  void Catalog::executeCatalogQuery(const QString&, ObjectType, ResultSet&, bool, attribs_map)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'
       ** catalog: role

[5] src/connection.cpp (457)
  void Connection::executeDMLCommand(const QString&, ResultSet&)
    [SQLCommandNotExecuted] Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near "="
LINE 1: ...tabase' AS parent_type FROM pg_rolesWHERE rolname = E'app_te...
                                                               ^
'
       ** 42601

**Dump of postgresql cluster**
[db.zip](https://github.com/pgmodeler/pgmodeler/files/11355397/db.zip)

**Comment by rkhaotix** [comment]
Thanks for the sample, but I still can't get the errors in both 1.0.4 and 1.1.0-alpha.

Could you please run the database import in debug model and attach here the log file?

**Comment by enjoy12e** [comment]
OK. I do that. Are you run import from db sample in attachment? I'm add tablespace for test_table, then add user for tablespace. See cluster dump more detailed, please. I can attach exported docker container export with db, if you need. Are you sure, you code enter line 459? Can you run debug or add qDebug() into that branch?

**Comment by enjoy12e** [comment]
Sorry 😞.  I forget to say, you must run partitional import. For example, check only dm_test schema or test_table only.

**Comment by enjoy12e** [comment]
![issue_1_p2](https://user-images.githubusercontent.com/45516205/235606908-77b033ec-966c-44af-81e6-c3ff28bc477b.png)
![issue_1_p3](https://user-images.githubusercontent.com/45516205/235606911-f0953b25-403e-43e7-be94-8a5b36a275ff.png)
![issue_1_p1](https://user-images.githubusercontent.com/45516205/235606914-8a77a498-f75e-4b83-8fe0-746f4e3b6780.png)

***Debug log***
[debug_log.zip](https://github.com/pgmodeler/pgmodeler/files/11370800/debug_log.zip)

**Comment by enjoy12e** [comment]
It's not working due line 443 of catalog.cpp
sql=schparser.getSourceCode(attribs).**simplified**();
trim trailing whitespace.

**Comment by rkhaotix** [comment]
> It's not working due line 443 of catalog.cpp sql=schparser.getSourceCode(attribs).**simplified**(); trim trailing whitespace.

Try removing the ```.simplified()``` call and see if it solves.

> What OS and version of qt and postgres did u use? I want to reproduce positive result toothinking

openSuse Linux Leap 15.3, PostgreSQL 15, Qt 6.4.1.

![image](https://user-images.githubusercontent.com/2205476/235715957-3bacfc8a-0922-447b-9940-12077323bdf8.png)

![image](https://user-images.githubusercontent.com/2205476/235716090-1d6cf67b-c527-4ca1-9cc2-9bf66136bc0b.png)

**Comment by enjoy12e** [comment]
1. Removing using file role.sch with whitespace and remove .**simplified**() solve the problem. But removing simplified may occurs later in some side effects.
2. On screen above i can see only one tablespace. Maybe you have error during import sample db. 

![issue_1_c1](https://user-images.githubusercontent.com/45516205/235858521-fdd0e0b6-ec49-4242-8845-fa59d7cc2082.png)

3. Make sure that tablespace created and right granted on it. Table test_table also must be in that tablespace.

Below you can see sql script for creation problem situation.

**Preparation SQL-script**
```
-- Create roles with !comments
CREATE ROLE app_test;
ALTER ROLE app_test WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
COMMENT ON ROLE app_test IS 'Application technical user';

CREATE ROLE dm_test;
ALTER ROLE dm_test WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
COMMENT ON ROLE dm_test IS 'Test schema';

-- Create tablespace
-- !Make sure that path is correct and target directory exists before do
CREATE TABLESPACE test_tablespace OWNER postgres LOCATION '/var/lib/postgresql/data/test_tablespace';

GRANT ALL ON TABLESPACE test_tablespace TO dm_test;
GRANT ALL ON TABLESPACE test_tablespace TO app_test;

-- Create DB
CREATE DATABASE test WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'en_US.utf8';

ALTER DATABASE test OWNER TO postgres;
ALTER DATABASE test SET default_tablespace TO 'test_tablespace';

-- Switch to test DB
\connect test

-- Create schema
CREATE SCHEMA dm_test;
ALTER SCHEMA dm_test OWNER TO dm_test;
SET default_tablespace = test_tablespace;

-- Create table
CREATE TABLE dm_test.test_table (
	id numeric(16),
	text character varying(100)
);
ALTER TABLE dm_test.test_table OWNER TO dm_test;
```

4. That branch of code in catalog.cpp used rarely. In my databases error appears in 10% of cases. Did you add debug output or attach debugger to check if program goes into that line 459? For example, just add qDebug():

![issue_1_c2](https://user-images.githubusercontent.com/45516205/235858385-b8f0d9b8-f158-498c-beb6-79170dbc5bea.png)

**Comment by rkhaotix** [comment]
Okay. I've managed to get the error. I'll investigate it and provide a proper fix.

**Comment by enjoy12e** [comment]
https://github.com/pgmodeler/pgmodeler/commit/d5706da6c99781d89083db60a4d55405783d48a6
solves the problem. Error doesn't appear on my db, when it was origin.
