### ISSUE TITLE
Drag&drop feature to open model files

### ISSUE THREAD

**Issue by enjoy12e** [pgmodeler/pgmodeler#1780]
**Feature description**
Please consider the possibility to add drag&drop feature to open model files.

**Sample video**
https://github.com/pgmodeler/pgmodeler/assets/45516205/df59774d-0e42-4dab-b310-d016bffdb9b2

**Additional info**
It's handy to open model by simple drop files onto main window.

**Comment by rkhaotix** [comment]
If you already made it like in the sample video just send me a PR that I'll analyze and eventually merge into the code base :)
