### ISSUE TITLE
Unable to import/diff table with constrain made with gist extension

### ISSUE THREAD

**Issue by vavroch2010** [pgmodeler/pgmodeler#1791]
**Bug description**
Import/diff of existing table in DB fails with error: 'The object public.bug_test.overlapping_times_test_ix (Constraint), oid 18296, could not be imported due to one or more errors! Check the exception stack for more details. HINT: if the object somehow references objects in pg_catalog or information_schema consider enable the importing of system/extension objects.'

**How to reproduce**
Use Postgresql 14 and run this 
```
create extension btree_gist schema public version '1.6';
create table bug_test
(
	id bigint not null
		primary key,
	id_test bigint not null,
	name varchar,
	valid_from timestamp with time zone,
	valid_to timestamp with time zone,
	constraint overlapping_times_test_ix
		exclude using gist (id_test with =, tstzrange(valid_from, valid_to) with &&),
	constraint to_bigger_from_program_check
		check (valid_from < valid_to)
);
```
and try import it to pgmodeler.

**Expected behavior**
Import should be successful 

**Screenshots**
![image](https://github.com/pgmodeler/pgmodeler/assets/30267257/c5784e01-8cf2-4db4-b4cf-bb7005ca2a2a)

**Info about your desktop**
 - OS: MacOS
 - Version: Ventura 13.4
 - Window manager: default
 - pgModeler version: 20230613.dc6ab5cc8 
 - Qt version: Qt 6.5.1

**Stacktrace / Debug info**
Doesn't crash but shows:
```
The object public.bug_test.overlapping_times_test_ix (Constraint), oid 18296, could not be imported due to one or more errors! Check the exception stack for more details. HINT: if the object somehow references objects in pg_catalog or information_schema consider enable the importing of system/extension objects.
```

**Additional info**
No info

**Comment by rkhaotix** [comment]
Thanks for reporting. 

Found out that pgModeler is missing the multirange types which are required for the example. I've added them and I could import the table:

![image](https://github.com/pgmodeler/pgmodeler/assets/2205476/c4cd1310-e424-4588-9eb1-e7f3b6236a6d)
