### ISSUE TITLE
Black and White "InkSaver" -Theme

### ISSUE THREAD

**Issue by apotkonen** [pgmodeler/pgmodeler#1798]
**Feature description**

"InkSaver" -theme with black fonts, black lines, borders and no fill at all.
At least should hold using "InkSaver"-theme exported svg, png, or black and white printed pdf -file.

Peoples who still do printable documents may like printer ink saving theme.
This could increase tool use for academic papers etc.

**Comment by apotkonen** [comment]
Tested "IncSaver"-theme, it does better "black and white" -exports and printing now. There is still colors and fillings at grouping schema and relationship connectors, maybe other elements too not included to test model now. Black and white, or one foreground color and none for fill, is need. It's enough to get exported graphics, prints to that state.

**Comment by rkhaotix** [comment]
> There is still colors and fillings at grouping schema and relationship connectors, maybe other elements too not included to test model now.

Yes, these elements (with custom colors defined by the users) need an extra patch to disable/change their colors when the InkSaver theme is active. I'll provide this feature soon.
