### ISSUE TITLE
something to modify existing domain

### ISSUE THREAD

**Issue by brigadier** [pgmodeler/pgmodeler#1800]
**Feature description**
Seems like there's no way to modify an existing domain, so if a user of pgmodeller makes an error in domain definition, then references it from tables, it becomes not possible to sync with diff. It is possible to create correct domain in the console, but model still does not sync properly and the diff process tries to alter domain with invalid parameters.

I'd suggest to display domains in model just as tables are and to add a form to modify existing domains.

**Comment by rkhaotix** [comment]
Did you try this?
https://www.pgmodeler.io/support/docs/65-model-objects?v=1.1.0

**Comment by brigadier** [comment]
I use 0.9.4 as it is the latest version in my distro and seems like there's no such thing. As you say it is implemented in the latest version I'm closing the issue.
