### ISSUE TITLE
Please improve "Table properties" window

### ISSUE THREAD

**Issue by ravsii** [pgmodeler/pgmodeler#1808]
**Feature description**
I've been using pgModeler for about a year now and I hoped this would change at some point, but unfortunately it's still the way it is.

When designing a database (which is the main usecase for me, and many other I believe) we need to see columns and their info (green rect), which is problematic considering that even on 1080p monitor you could see up to about 4-5 columns max, assuming you're not resizing this window to fullscreen.

Suggested fix: Move fields in red squares to a new separate tab ("General" or something) and columns(and others) be a full-height tabs

**Sample image**
Red - wasted space
Green - Actual info I need to see
![image](https://github.com/pgmodeler/pgmodeler/assets/5007271/15d7e925-215e-4d0a-a34c-ea2be57fe797)

Suggested fix (please forgive me my photoshop skills lmao)
![image](https://github.com/pgmodeler/pgmodeler/assets/5007271/2b0c1760-8e36-4f8c-8cd9-cedc997ff854)

**Comment by rkhaotix** [comment]
This is already planned to be implemented until the end of the development of 1.1.0.

**Comment by ravsii** [comment]
Thanks!
