### ISSUE TITLE
pgModeler crushes when trying to drag a table with the mouse

### ISSUE THREAD

**Issue by IngaTomasevic** [pgmodeler/pgmodeler#1813]
**Bug description**
I created 2 simple tables with minimal data. When trying to drag it to further modification - the program crushes. It happens each time I do it. I have just install pgModeler on my computer for the first time today. And I have this problem.

**How to reproduce**
_Please, if the bug can be reproduceable describe the steps in full details. If possible provide a sample model and/or a SQL dump for test purposes._

**Expected behavior**
_A clear and concise description of what you expected to happen._

**Screenshots**

**Info about your desktop**
 - OS: Windows 10 
 - Version: '10.0.19045'
 - Window manager:
 - pgModeler version: pgmodeler-1.0
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Hi @IngaTomasevic 

Are you using pgModeler 1.0.5 or the recently launched 1.1.0-alpha1?

Are the binaries the ones purchased from the site or you are compiling pgModeler?

**Comment by IngaTomasevic** [comment]
I just followed instruction provided in email after the purchase and installed by the key . It seems to be the version pgmodeler-1.1.0-alpha1-windows64



Отправлено из мобильной Почты Mail.ru


вторник, 3 октября 2023 г., 22:57 +03:00 от ***@***.***  ***@***.***>:

**Comment by rkhaotix** [comment]
Yeah, I can confirm the problem. But it seems to happen only on Windows 10. On 11 pgModeler runs ok. I'll investigate this crash.

**Comment by IngaTomasevic** [comment]
How can I get debugged version?

**Comment by rkhaotix** [comment]
Just download the package again and reinstall it on your machine. I've uploaded a new build yesterday.
