### ISSUE TITLE
Support for PostgreSQL 16

### ISSUE THREAD

**Issue by jokay** [pgmodeler/pgmodeler#1817]
**Feature description**

PostgreSQL 16 was released on 14th september 2023, see [here](https://www.postgresql.org/about/news/postgresql-16-released-2715/).

Would be good to have support for this new version as well.

**Sample image**

![image](https://github.com/pgmodeler/pgmodeler/assets/18613935/cc429b9e-f034-46cb-b391-9fcb24f86753)

**Additional info**

None.

**Comment by rkhaotix** [comment]
Already supported on pgModeler 1.0.6 and 1.1.0-alpha1

**Comment by rkhaotix** [comment]
Released 5 days ago
