### ISSUE TITLE
1.0.6 (No declaration for attribute width of element textbox) cause error have to fix database accident delete schema 

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1819]
**Bug description**
Hi @rkhaotix, 
Hope you have a good day sir! Long time no see.
After go from 1.0.5 alpha which is very good to 1.0.6 I have a dialog ask me fix broken database and after that it remove few schema

**How to reproduce**
- upgrade 1.0.6
- open old file
- fix old file
- have database_fixed which is broken

**Expected behavior**
should not broken

**Screenshots**
![image](https://github.com/pgmodeler/pgmodeler/assets/16970990/55788511-e233-4ba3-ae8f-511480d600f4)

**Info about your desktop**
 - OS: windows
 - Version: 11
 - Window manager:
 - pgModeler version: 1.0.6
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```


[0] src/mainwindow.cpp (1971)
  void MainWindow::showFixMessage(Exception&, const QString&)
    [ModelFileNotLoaded] Could not load the database model file `C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

[1] src/mainwindow.cpp (1185)
  void MainWindow::addModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[2] src/mainwindow.cpp (1160)
  void MainWindow::addModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[3] src/widgets/modelwidget.cpp (1721)
  void ModelWidget::loadModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[4] src/databasemodel.cpp (3405)
  void DatabaseModel::loadModel(const QString&)
    [InvModelFileNotLoaded] Could not load file `C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm'. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[5] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute width of element textbox . 
       ** C:/Users/cthuo/Documents/small-cosmos/awread/resources/database/awread_database.dbm

[6] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString&)
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute width of element textbox . 

[7] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute width of element textbox . 


```

**Additional info**
attach file here, I will delete once you can detect the error

**Comment by rkhaotix** [comment]
Actually, you're trying to open a model designed in 1.1.0-alpha1 in 1.0.6. This will not work because pgModeler doesn't guarantee backward compatibility between two major versions where the original model version is greater than the currently running application. If the model was designed in 1.0.6 and you tried to open it in 1.1.0-alpha1 it was more likely to work or, at least, the fix process would capture the problems and adjust the model's structure to version 1.1.0-alpha1. My advice for you is to stick with 1.1.0-alpha1 or upgrade to 1.1.0-beta. Or, if you prefer to keep using 1.0.6, remove the attribute "width" from <textboxes> and "name-color" from <schema> so the model can be loadable again.

**Comment by hiepxanh** [comment]
Aw my bad, I thought it is an upgrade, sorry I will close issue now

**Comment by rkhaotix** [comment]
No worries :)
