### ISSUE TITLE
Allow "shifting" IDs instead of swapping

### ISSUE THREAD

**Issue by chrispytoes** [pgmodeler/pgmodeler#1822]
**Feature description**
I would like to have the ability to simply "shift" object IDs up and down in the creation list, rather than swapping them entirely. 99% of the time this simply creates more problems by moving the object you swapped with into the wrong place, creating a cascading problem that takes hours of swapping to resolve. This could all be fixed if I could simply move an item in the list, and shift all the objects below it down.

**Comment by rkhaotix** [comment]
Which version?

You can already shift them by using arrow keys. Just select the object you want to move and press up or down to move it in the creation list.

**Comment by chrispytoes** [comment]
> Which version?
> 
> You can already shift them by using arrow keys. Just select the object you want to move and press up or down to move it in the creation list.

1.0.5. I'm opening the Objects list in the bottom-right, and the arrow keys do nothing there, or on the "Swap Ids" dialog from the context menu.

What "creation list" are you referring to?

**Comment by rkhaotix** [comment]
Sorry, you have to hold Control key while pressing up or down. The steps I mentioned are done in the swap IDs dialog.

https://www.pgmodeler.io/support/docs/68-swap-objects-ids?v=1.1.0

**Comment by chrispytoes** [comment]
> Sorry, you have to hold Control key while pressing up or down. The steps I mentioned are done in the swap IDs dialog.
> 
> https://www.pgmodeler.io/support/docs/68-swap-objects-ids?v=1.1.0

Thank you! That's what I was looking for.
