### ISSUE TITLE
invalid conversion from 'const xmlError*'

### ISSUE THREAD

**Issue by marco44** [pgmodeler/pgmodeler#1824]
**Bug description**
Since libxml 2.12, it seems xmlGetLastError() returns a `const xmlError*`. So when compiling, you get
```
src/xmlparser.cpp:182:42: error: invalid conversion from ‘const xmlError*’ {aka ‘const _xmlError*’} to ‘xmlError*’ {aka ‘_xmlError*’} [-fpermissive]
  182 |                 xml_error=xmlGetLastError();
      |                           ~~~~~~~~~~~~~~~^~
      |                                          |
      |                                          const xmlError* {aka const _xmlError*}
```
Just replacing the declaration of xml_error with the correct const type seems to solve the issue, but my C++ is a bit rusty.

Do you want me to do a PR ?

**Info about your desktop**
 - OS: archlinux
 - Window manager: plasma
 - pgModeler version: 1.0.6
 - Qt version: 5.15.10

**Comment by rkhaotix** [comment]
Hi! I already fixed that on branch ```1.1.0-beta1 ``` 😁

**Comment by marco44** [comment]
Ok…
Have a nice day :)

**Comment by neeweesomu** [comment]
![Uploading pgmodeler-1.0.6-error.png…]()

Facing same issue in windows10.
