### ISSUE TITLE
[1.1.0 beta] seem missing pgmodeler-cli.exe but actually it still there

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1827]
Hi @rkhaotix, nice to see you,

I just download 1.1.0 beta and I think this is bug. The image is clear so I not follow the guideline, feel free to close if it is a misstake.
1) app think file is broken and try to fix
2) cli is missing
3) search and it still there

![image](https://github.com/pgmodeler/pgmodeler/assets/16970990/1d2582b9-bea4-4854-af30-846237890466)

**Comment by hiepxanh** [comment]
p/s: I'm using avast antivirus but I dont think it relevant since it still working at previous version

**Comment by IvanDrag0** [comment]
I'm having the same issue and it looks like it's not recognizing the file even when it's selected manually.

![image](https://github.com/pgmodeler/pgmodeler/assets/24702285/987ecc4b-6902-4a1d-814b-155afa58ac99)

**Comment by rkhaotix** [comment]
@hiepxanh @IvanDrag0 Issue confirmed. Seems to happen only on Windows. I'll investigate!
