### ISSUE TITLE
Moving tables to a new layer does not move relationships

### ISSUE THREAD

**Issue by hg2581** [pgmodeler/pgmodeler#1837]
**Bug description**
When moving tables to a newly created layer, the lines showing relationships remain in the original layer. if this is a bug, unfortunately I am not able to update to a newer version of pgmodeler at this time.

**How to reproduce**
Create a new layer in the model and move all tables in a schema to the new layer and you'll find the relatinship lines remain in the original layer.

**Expected behavior**
Both tables and relationships between these tables should be moved together

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Info about your desktop**
 - OS: CentOS
 - Version: 7
 - Window manager:
 - pgModeler version: 0.9.3
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Related to #1690
