### ISSUE TITLE
Can't open model.sdbm after saving model.dbm as split model

### ISSUE THREAD

**Issue by dekiesel** [pgmodeler/pgmodeler#1847]
**Bug description**
I have a file called `model.dbm` which I saved as a split model, `model.sdbm`. When I close pgmodeler, reopen it and try to load `model.sdbm` it fails and gives me a stacktrace (see below). 

Opening and closing `model.dbm` works without a problem.

**How to reproduce**
I can't upload the model publicly, unfortunately, but line 68 of `model.sdbm` doesn't have a character 93:
![image](https://github.com/pgmodeler/pgmodeler/assets/17333827/1604ebb2-c45e-4e29-a4aa-57bfbe96fe01)

**Expected behavior**
pgmodeler loads the split file without errors

**Screenshots**
![image](https://github.com/pgmodeler/pgmodeler/assets/17333827/2b8c2fa6-5db2-4aa7-bb07-f00ed63920c7)

**Info about your desktop**
 - OS: Ubuntu
 - Version: 22.04.3
 - Window manager: KDE
 - pgModeler version: 1.0.6
 - Qt version: 5.15.3

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

[0] src/mainwindow.cpp (1962)
  void MainWindow::loadModels(const QStringList &)
    [Custom] Failed to load the split database model `/home/david/pgmodeler/pgmodels/retool_acm/model.sdbm'! Please, check the error stack for more details.

[1] src/splitmodelplugin.cpp (584)
  void SplitModelPlugin::loadSplitModel(const QString &)
    [Custom] Failed to load the split database model `/home/david/pgmodeler/pgmodels/retool_acm/model.sdbm'! Please, check the error stack for more details.

[2] src/xmlparser.cpp (92)
  void XmlParser::loadXMLFile(const QString &)
    [LibXMLError] Error while interpreting XML buffer at line 68 column 93.
Message generated by the parser: EntityRef: expecting ';' . 
       ** /home/david/pgmodeler/pgmodels/retool_acm/model.sdbm

[3] src/xmlparser.cpp (123)
  void XmlParser::loadXMLBuffer(const QString &)
    [LibXMLError] Error while interpreting XML buffer at line 68 column 93.
Message generated by the parser: EntityRef: expecting ';' . 

[4] src/xmlparser.cpp (199)
  void XmlParser::readBuffer()
    [LibXMLError] Error while interpreting XML buffer at line 68 column 93.
Message generated by the parser: EntityRef: expecting ';' . 
       ** /home/david/pgmodeler/pgmodels/retool_acm/model.sdbm



```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Hey @dekiesel 

Could you please send me a copy of your model? I would like to debug the split model saving and loading processes.

**Comment by rkhaotix** [comment]
@dekiesel I suspect that there's a problem in one of the schema files used by the plugin in 1.0.6.

Try one thing, please...

Search for the file ```object.sch``` in the plugin ```splitmodel``` folder and change the line:

```$tb [<object type=] "{type}" [ signature=] "&{signature}" [ file=] "&{file}" /> $br```

To

```$tb [<object type=] "{type}" [ signature=] "{signature}" [ file=] "{file}" /> $br```

Note that only "&" was removed from ```{signature}``` and ```{file}```. This syntax is not supported by 1.0.6 only by 1.1.0. 

In 1.1.0 (to be released in a few days) your model saved and loaded in split mode without issues!

**Comment by dekiesel** [comment]
That worked, thank you!
