### ISSUE TITLE
"Import objects to the working model" should not reset table positions

### ISSUE THREAD

**Issue by GitStorageOne** [pgmodeler/pgmodeler#1862]
**Feature description**
I'm developing a DB model programmatically, using some ORM framework.  
I implement changes to the code then the framework updates the DB structure.  
So I need to overview the results, and pgModeler is a great tool for that (I use full paid version).  
But, unfortunately, after each import, pgModeler resets the positions of all tables and other model elements.  
I strongly believe that with option `Import objects to the working model` pgModeler should restore the positions of every item that was in the model before.  

Also, import dialog (import existing database) should respect `auto browse` option from selected connection.  
So when connection with auto browse database is selected, import dialog should auto select database to import data from.

**Comment by rkhaotix** [comment]
Thanks for your suggestion @GitStorageOne 

I'll consider it on the next patch (1.1.1) or if it takes too much time to implement I'll move it to 1.2.0, but I believe this is something quite easy to add.

**Comment by rkhaotix** [comment]
@GitStorageOne I added some improvements related to this issue on 1.1.1 (released today) and I would like your feedback if possible! :)

pgModeler 1.1.1 now does not touch the current position of the original object when importing new objects to the working model. There is also an extra option to put the imported objects in random positions. The "Auto browse" feature has been fixed and now it is considered in both database import form and model/db diff form.

**Comment by GitStorageOne** [comment]
Well, for me it doesn't work, unfortunately.  
Steps:
1. Create database model programmatically.
2. Import model in pgModeler, place tables where I would like.
3. Add new column to the some table within model programmatically.
4. Import model in pgModeler, with option `import objects to the working model`.
5. I don't see the new column in the table within pgModeler model.
    Can't check import log, because pgModeler closes window right after import.
6. If I delete table from model programmatically and re-import model to pgModeler with option `import objects to the working model` - it still stays.

So, 5 is just a bug as I understand.  
But 6, i suppose it is by design, in that way, would be great if you could add option `drop existing objects before import` under `Import objects to the working model`.  
Should be the way to reload entirely model from database and restore table positions, so continuous development become possible.

**Comment by rkhaotix** [comment]
Hmmm ... Now I understand what you want. 

1) Apply changes made in the database to the model. This is the inverse of how diff tool works today, applying to the database the changes made in the model.

2) Avoid changing the object positions in the model when importing new objects. 

3) Make the import form obey the " auto browse" option of the connections used in the process.

The items 2 and 3 are implemented on pgModeler 1.1.1. The item 1, it's not fully supported, that's why you're no seeing the new column on the model. pgModeler will not import new columns alone due to the way the reverse engineering works. 

I have plans to create a plug-in that will implement a full featured database -> model sync tool. For now, I will review the import process and try to improve it in the way you need.

**Comment by GitStorageOne** [comment]
Thanks, 2 and 3 are definitely works great.  
As you are going to develop a whole new plugin for "database -> model sync",  
`drop existing model objects` under `Import objects to the working model` could be an option.  
What that option could do:  
- Cache position and size data of the database related objects;
- Remove database related objects and not touch UI elements like Textbox.  
  All changes that was made to any database related objects (within pgModel) will be lost, f.e. additional columns or new tables. 
- Reload database related objects and re-apply position and size data.
- At the end we get updated database model view, and even visual remarks will be still there.  
  Also please add option somewhere to leave import form opened so users who interested to debug would be able to review the log.

Full featured plugin, that you announced, is absolutely awesome, will do it's own complicated job.  
I'm pretty excited to get it in the future, luckily I recently decided to support project and opted in to lifetime updates :)  
I can additionally help with polishing UI, by reporting some bugs and thoughts.  
I have few for new backup tool form.

**Comment by rkhaotix** [comment]
> As you are going to develop a whole new plugin for "database -> model sync",
drop existing database objects under Import objects to the working model could be an option for now.
What that option could do:

> * Cache position and size data of the database related objects;
> * Remove database related objects and not touch UI elements like Textboxes, e.t.c.
> * All changes that was made to any database related objects (within pgModel) will be lost, f.e. additional columns or new tables.
> * Reload database related objects and re-apply position and size data.
> * At the end we get updated database model view, and even visual remarks will be still there.
> Also please add option somewhere to leave import form opened so users who interested to debug would be able to review the log.

Now that you mentioned these steps, did you know the objects' metadata handling feature? I think it can help you while the plugin isn't developed: https://pgmodeler.io/support/docs/612-objects-metadata-handling?v=1.1.0

> Full featured plugin, that you announced, is absolutely awesome, will do it's own complicated job.
I'm pretty excited to get it in the future, luckily I recently decided to support project again and opted in to lifetime updates :)

And I'm grateful for the financial support! :D

> I can additionally help with polishing UI, by reporting some bugs and thoughts.
I have few for new backup tool form.

I'll be waiting for that! ;)

**Comment by GitStorageOne** [comment]
> Now that you mentioned these steps, did you know the objects' metadata handling feature? I think it can help you while the plugin isn't developed: https://pgmodeler.io/support/docs/612-objects-metadata-handling?v=1.1.0

Wow, this is what I need and it works, I can organize my workflow.
I am closing this topic, additional temporary features are not needed,  
Will use what is implemented and wait for the synchronization plugin, thanks.
