### ISSUE TITLE
Table and attribute display bug

### ISSUE THREAD

**Issue by Medialo** [pgmodeler/pgmodeler#1870]
**Bug description**
Tables are not displayed correctly and columns are overlapped when there are several rows  

**How to reproduce**
Create table with many columns with some NOTNULL attributes

**Expected behavior**
Display correctly

**Screenshots**
![image](https://github.com/pgmodeler/pgmodeler/assets/33297991/17cf65b5-38e2-459d-8334-5da4d98fa1d4)
![image](https://github.com/pgmodeler/pgmodeler/assets/33297991/69f39b96-65e9-4713-be1f-756a2a4fb57a)

**Info about your desktop**
 - OS: Windows
 - Version: 11 23H2
 - Window manager: 
 - pgModeler version: 1.1.1
 - Qt version: 6.6.2

**Comment by rkhaotix** [comment]
This problem sometimes is related to the font being used in the appearance settings. I had similar problems on MacOs. Try to change the default font and see if the issue persists. Anyway, I will investigate.

**Comment by Medialo** [comment]
The default font (tahoma) seem to solve the problem, thank you very much.
