### ISSUE TITLE
current position of the mouse in the canvas is distracting

### ISSUE THREAD

**Issue by cowsonindustries** [pgmodeler/pgmodeler#1877]
**Feature description**
Option to switch off the display of the 'current position of the mouse in the canvas'. 

As the mouse moves and the values change, the neighbouring elements wobble as they accomodate the space needed for the new values, which is distracting.

**Sample image**
n/a

**Additional info**
n/a

**Comment by rkhaotix** [comment]
Hi! Could you provide some pics or videos demonstrating the issue? Thanks

**Comment by cowsonindustries** [comment]
Video attached.

https://github.com/pgmodeler/pgmodeler/assets/162904426/a820bfe5-a7f3-4d71-b48a-3edb8d88caf5
