### ISSUE TITLE
Improve sorting in creation script

### ISSUE THREAD

**Issue by mariec7** [pgmodeler/pgmodeler#1888]
**Feature description**
Allow move "up/down" of selected item(s) instead of switch.

Now it is only allow to switch two objects. It would be better if, instead of switching two objects, the selected object(s) could be moved one level up or down.

**Comment by rkhaotix** [comment]
Just hold control key and use the arrow keys to move the selected object up or down.

https://pgmodeler.io/support/docs/68-swap-objects-ids?v=1.1.0

**Comment by mariec7** [comment]
Thank you. I missed this improvement. There could be any buttons, but it's also OK.
