### ISSUE TITLE
[BUG]: 1.2.0 alpha, create function with `set` then save then edit to `table` then save, but the save is not working

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1899]
**Bug description**
Hi, it been long time, you are one of my favorite application. Today I'm working on function return as table, and click save not work, I hope the video is enough to describe. Hope you have a good day sir  @rkhaotix 

**How to reproduce**
1) create new function with `set` then save
2) open it again to edit then modify from `set` to `table`, add few example, then save
3) open it again and it jump back to `set` instead???

Note: this issue not happen if I create table directly, so it will work on create, I think it only happen while edit from `set` to `table`, maybe missing if else or switch case

**Expected behavior**
3) click save if `set should work`

**Screenshots**

https://github.com/user-attachments/assets/39619114-307b-4863-b9bb-f9f17e376f4b

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
_Add any other information that you may find useful to help in the problem solving._

**Comment by rkhaotix** [comment]
Thanks for reporting! I'll fix that. ;)
