### ISSUE TITLE
[BUG] 1.2.0 alpha: diff not update, export not add new column

### ISSUE THREAD

**Issue by hiepxanh** [pgmodeler/pgmodeler#1903]
@rkhaotix  I see new bug here

**Bug description**
in previous version, If I add column it should push into the table, If I change column, the diff should update table. But currently both is not work 
- the schema add NEW `wallet_level` and UPDATE `maximum_balance` to `reset_balance`

**How to reproduce**
- the 1.2.0 alpha version I'm using, If I add column it not work if I export
- the export command CTRL + E not add new column to database
- the diff CTRL + SHIFT + D not generate sql which update column

**Expected behavior**
- it should add on export
- it should update on diff

**Screenshots**

I guess something broken, since it still work in the previous vesion

https://github.com/user-attachments/assets/38401914-0b20-4999-8128-de1bd353c651

the git diff is very simple 

![image](https://github.com/user-attachments/assets/5b2dff93-5395-4602-b6c3-156bf3109699)

**Info about your desktop**
 - OS:
 - Version:
 - Window manager:
 - pgModeler version:
 - Qt version:

**Stacktrace / Debug info**
_If pgModeler crashed after the bug raised attach the stacktrace below_

```

 Put the stacktrace here!

```

**Additional info**
the previous version 1.1.3 work as expect:

![image](https://github.com/user-attachments/assets/a4e2c29b-cea6-4ffd-b61c-c12ad90ae11e)

**Comment by rkhaotix** [comment]
I can partially confirm the problem, but there are two things to consider here:

1) If you add a new column and want to reflect it in your database using the **export** feature then you have to check the option *Generate ALTER commands for columns/constraints* in the table where the column is added. The export process does not automatically recognize the addition of an object.

2) Always give preference to diff process when constructing your database incrementally, which means, adding new objects to the model and then applying the changes to a living database. 

Now, for the **update** via diff, note that the process **doesn't support objects renaming** so in your case you have to check the option *Recreate unmodifiable objects* so the column is correctly renamed in the database.

Finally, there's indeed a bug in the diff related to a new column addition when the option *Replace modified object* is checked. pgModeler is completely ignoring the new column. I'll provide a fix for that.

**Comment by hiepxanh** [comment]
thank you so much,  I understand the need to check `Generate ALTER commands for columns/constraints` when adding new columns via export. I also appreciate the recommendation to use the diff process for incremental changes and will ensure to check Recreate unmodifiable objects for renaming columns.

as an user, a really noob user I does not notice that feature `generate alter commands`. haha, now I found it useful now. Since the app is so big,  I just keep reading manual and try the important thing because it save me so much time on basic task. 

> Always give preference to diff process when constructing your database incrementally, which means, adding new objects to the model and then applying the changes to a living database.

about this, I not understand the word "preference", but I'm sure I understand the rest. Since the best practice come when I accident delete database and cannot recovery it. I understand that your recommend is: "add your changes first, then remove it later instead of update it". am I correct?

My current workflow is using `Diff Tool` first to update function and contraints or anything else, and using export later if it accident drop something else like role or user. 

> Now, for the update via diff, note that the process doesn't support objects renaming so in your case you have to check the option Recreate unmodifiable objects so the column is correctly renamed in the database.

this one `Recreate unmodifiable objects` is true, I'm hurry to record without to note you, 1.2.0 alpha remove my preset but come back seem recovery it. have no Idea but i think it not important since I have to manual create it again. But as I remember this option is very important. There is a time I'm update my production database and forgot to check `Recreate unmodifiable objects`, then lost a table :(  that issue is here: https://github.com/pgmodeler/pgmodeler/issues/1766


So lucky since I just not deploy it yet.  <3 <3 <3 thank you so much to notice me. I almost lost table again :(

**Comment by rkhaotix** [comment]
> about this, I not understand the word "preference", but I'm sure I understand the rest. Since the best practice come when I accident delete database and cannot recovery it. I understand that your recommend is: "add your changes first, then remove it later instead of update it". am I correct?

Actually what I tried to say is: "Always modify your model first and use the diff tool to generate the proper SQL code, and then apply that code to your database.". In that case, your model will always be the latest version of your database. That's the correct workflow when you intend to use the diff. :)

> this one Recreate unmodifiable objects is true, I'm hurry to record without to note you, 1.2.0 alpha remove my preset but come back to 1.1.3 version seem recovery it. have no Idea but i think it not important since I have to manual create it again. But as I remember this option is very important. There is a time I'm update my production database and forgot to check Recreate unmodifiable objects, then lost a table :( that issue is here: https://github.com/pgmodeler/pgmodeler/issues/1766

That's why I always recommend making a backup of the database before applying diff, and try to avoid applying it directly to your production server before being very sure that the code generated is what you want! :)

If there is no way to avoid run the diff code in the production DB, my advice for you is to instead of checking the option "Apply on server" use the "Store in SQL file" option and use that file in SQL tool by running manually each command generated by the diff.

**Comment by hiepxanh** [comment]
thank you so much, that a good suggestion, now I'm always to use 2 database, the dev one and the prod one. Working on the dev one first, and deploy once it ready. Since I know your application, I'm too lazy to edit a column and still use your application to export and willing to wait a minute to do a tiny job. That really amazing :)))))))))))))
