### ISSUE TITLE
[BUG] 1.2.0-alpha: Markdown export issue when table has a comment

### ISSUE THREAD

**Issue by mathieubossaert** [pgmodeler/pgmodeler#1904]
**Bug description**
When I set a comment on a table, the markdown export ommit a carriage return after the comment, so the table syntax is wrong

**How to reproduce**
Fill a comment on a table
Export the data dictionary in markdown

**Expected behavior**
The comment should be shown before the table, with a space between comment an table

**Screenshots**
Here is the generated md doc for the commented table

```md
<a name="suivi_gestion.projet"></a>
### _suivi_gestion_.**projet** `Table`
A alimenter à partir de LogeProj. garder l'historique des projest pour pouvoir garder l'historique des actions.| Name | Data type  | PK | FK | UQ  | Not null | Default value | Description |
| --- | --- | :---: | :---: | :---: | :---: | --- | --- |
| code_logeproj | text | &#10003; |  |  | &#10003; |  |  |
| intitule | text |  |  |  |  |  |  |
```

And thanks a lot for the tool ! I played with it today and really enjoy it !

**Comment by rkhaotix** [comment]
Hi @mathieubossaert 

Thanks for reporting, I'll provide the fix.

> And thanks a lot for the tool ! I played with it today and really enjoy it !

Thank you very much!
