### ISSUE TITLE
Import stuck at Destroying unused detached columns

### ISSUE THREAD

**Issue by grv87** [pgmodeler/pgmodeler#1922]
**Bug description**
The import freezes on `Destroying unused detached columns`. I've waited for 4 hours before killing it.

**How to reproduce**
The original database is pretty large. I was able to isolate the problem to this DDL:

```sql
CREATE TABLE lvl1 (
  id uuid NOT NULL,
  val int NULL,
  CONSTRAINT lvl1_pk PRIMARY KEY (id)
);


CREATE TABLE "object" (
  CONSTRAINT lvl2_pk PRIMARY KEY (id)
)
INHERITS (lvl1);


CREATE TABLE lvl3 (
  CONSTRAINT lvl3_pk PRIMARY KEY (id)
)
INHERITS ("object");
```

**Expected behavior**
Import succeeds.

**Info about your desktop**
 - OS: Windows
 - Version: 11
 - pgModeler version: 1.1.5, 1.2.0-alpha1

**Comment by rkhaotix** [comment]
Hi @grv87 

Thanks for reporting that! I confirm that pgModeler hangs as described. I'll provide the proper fix.

**Comment by grv87** [comment]
@rkhaotix, could we expect the fixed version released anywhere soon?

**Comment by rkhaotix** [comment]
@grv87 Hi! Sorry for the delay...

I'm planning to release 1.1.6 before Christmas.  :)
