### ISSUE TITLE
Support for PostGIS versions in Ubuntu

### ISSUE THREAD

**Issue by ninboy** [pgmodeler/pgmodeler#238]
Hi Raphael!

You added PostGIS support in a previous version (Issue #75), but you did for 2.0 version of PostGIS.

You can see Ubuntu (in its actual and LTS versions) only supports 1.7 versions. It would be possible to add support for this?

Basically when you create the table you don't have modifiers. If you run the SQL that pgModeler exports on a LTS server (lots and lots of those out there) you will get:

ERROR:  type modifier is not allowed for type "geometry"

Every geometry column must be added using the postgis function "AddGeometryColumn" (http://postgis.refractions.net/docs/AddGeometryColumn.html). Maybe you could put it to select the postGIS version too and output based on that...

**Comment by bunnyboy1** [comment]
Is it done ?
