### ISSUE TITLE
Mac OS X binary does not work

### ISSUE THREAD

**Issue by metajungle** [pgmodeler/pgmodeler#243]
When installing pgmodeler on Mac OS X and running: 

/Applications/pgmodeler.app/Contents/MacOS/pgmodeler 

I get the following error: 

dyld: Library not loaded: libutils.1.dylib
  Referenced from: /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found
Trace/BPT trap: 5

Then, I did the following: 

> export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Applications/pgmodeler.app/Contents/MacOS

This time I get the following error: 

dyld: Library not loaded: /Users/raphael/Qt5.0.2/5.0.2/clang_64/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport
  Referenced from: /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found
Trace/BPT trap: 5

Seems that "raphael" is hardcoded somewhere, which does not seem right. 

If I augment DYLD_LIBRARY_PATH with the path to my QT libs, the "raphael" path is still there, which cannot be found.

**Comment by jabclab** [comment]
Seeing this on OSX 10.10.2 also (having compiled from source). Here's the outcome of running `build/pgmodeler.app/Contents/MacOS/startapp pgmodeler` as @TimHoepfner suggested:

```
dyld: Library not loaded: libutils.1.dylib
  Referenced from: /Users/USER/*/pgmodeler/build/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found
pgmodeler.app/Contents/MacOS/startapp: line 29:  7042 Trace/BPT trap: 5       $EXE ${@:2:20}
```

I installed `qt` via `brew install qt5` followed by `brew link --overwrite --force qt5`.

**Comment by steakknife** [comment]
The issue is that the qmake rpath environment isn't setup correctly.

**Comment by steakknife** [comment]
@jabclab Don't link force qt5, it will break stuff.  Just follow my [gist here](https://gist.github.com/steakknife/c2a35c6eb74ef4a1c33a)

**Comment by rkhaotix** [comment]
Nice tip! I'll update the build process for OSX.
Em 23/04/2015 21:08, "Barry Allard" <notifications@github.com> escreveu:
