### ISSUE TITLE
Cannot add extension with dash character in name.

### ISSUE THREAD

**Issue by gswierczynski** [pgmodeler/pgmodeler#249]
Version 0.5.0.

It is not possible to add extension with dash character in extension name (eg. uuid-ossp).

**Comment by grgurev** [comment]
Version 0.9.1 

Somehow I'm experiencing this again (2018) with uuid-ossp in OSX.

Screenshot attached: 
<img width="793" alt="screen shot 2018-06-02 at 00 23 57" src="https://user-images.githubusercontent.com/7900918/40865929-52502eac-65fb-11e8-95bb-0f681725789a.png">

Any idea?

**Comment by rkhaotix** [comment]
Maybe a regression? I'll investigate.
