### ISSUE TITLE
*** Translators wanted!!! ***

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#27]
Hello!

This Issue is intended to reunite people interested on making translations to their language for pgModeler.

Necessary Tools: Qt Linguist (bundled with Qt Framework)

Translation steps:

1) Use the most recent pgModeler source code
2) Edit the file 'pgmodeler-intl.pro' and add the name of your language file:

```
   TRANSLATIONS =  lang/pgmodeler.pt_BR.ts \
                   lang/pgmodeler.[YOUR LANG HERE].ts
```

3) Generate the TS file:

```
    $ lupdate -no-obsolete pgmodeler-intl.pro
```

4) Edit the generated file `lang/pgmodeler.YOULANG.ts` on Qt Linguist and translate the phrases to your language. Do not forget to mark item as finished through the command `Crtl + ENTER` on every phrases you translate.

5) Generate the compiled version of translation:

```
   $ lrelease pgmodeler-intl.pro
```

After that, the file  `pgmodeler.YOURLANG.qm` will be generated. This is the file responsible to translate the pgModeler UI. Once created you can upload the file via "Pull request" here on Github.

NOTE: Make sure to update your pgModeler fork before start or resume your work on translation. After update run the  `lupdate`  command again (step 3).

**Comment by thiemo-taken** [comment]
Hi Raphael

I am working on translations to German and to the dialect spoken around Zürich in Switzerland.

When there is no translation, i. e. the same term is used, do I have to leave the translation empty or just duplicate the original term, e. g. "truncate"?

I cloned the git repository. Should I branch? I am new to git, so I might do it wrong.

Kind regards

Thiemo

**Comment by rkhaotix** [comment]
Hi Thiemo! First, thank you so much for your effort on translate pgmodeler! :)

About the duplicate terms, you have to translate it one time. For the others just leave the translation field empty so Qt will automatically translate that term in runtime.

The recommended approach is to clone the repository, create a branch and then submit a pull request when your work is done.

Thanks again

**Comment by cypa** [comment]
any russian translation available? or I should do it myself?

**Comment by rkhaotix** [comment]
@cypa Unfortunately, there's no Russian translation. You will have to do it yourself if that language is needed for your.

**Comment by cypa** [comment]
I've found this https://github.com/nikolay57/pgmodeler/blob/translation-ru/lang/ru_RU.ts

**Comment by cypa** [comment]
this is on the default branch
```
$ lupdate -no-obsolete pgmodeler-intl.pro
Info: creating stash file /hdd/data/builds/github/pgmodeler/.qmake.stash
Updating 'assets/lang/pt_BR.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
    Removed 2715 obsolete entries
Updating 'assets/lang/zh_CN.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
    Removed 2715 obsolete entries
Updating 'assets/lang/fr_FR.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
    Removed 3017 obsolete entries
Updating 'assets/lang/es_ES.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
    Removed 2715 obsolete entries
Updating 'assets/lang/nl_NL.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
    Removed 2715 obsolete entries
Updating 'assets/lang/ru_RU.ts'...
    Found 0 source text(s) (0 new and 0 already existing)
```
