### ISSUE TITLE
pgModeler is not starting in mac

### ISSUE THREAD

**Issue by ooriol** [pgmodeler/pgmodeler#295]
When I try to start pgModeler I have an error

---

Process:         pgmodeler [34308]
Path:            /Volumes/VOLUME/pgmodeler.app/Contents/MacOS/pgmodeler
Identifier:      br.com.pgmodeler.pgModeler
Version:         ??? (0.5.1_r1)
Code Type:       X86-64 (Native)
Parent Process:  launchd [141]

Date/Time:       2013-08-22 13:57:53.795 +0200
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Interval Since Last Report:          10776 sec
Crashes Since Last Report:           3
Per-App Crashes Since Last Report:   3
Anonymous UUID:                      C6BC90EF-2CCE-4A72-B8DC-EFFDEE794ABA

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/libpq.5.dylib
  Referenced from: /Volumes/VOLUME/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found

Binary Images:
       0x10b0e6000 -        0x10b0f5fff +br.com.pgmodeler.pgModeler (??? - 0.5.1_r1) <1078F625-9461-3B7F-80FC-171755AAAE01> /Volumes/VOLUME/pgmodeler.app/Contents/MacOS/pgmodeler
    0x7fff6ace6000 -     0x7fff6ad1abaf  dyld (195.6 - ???) <0CD1B35B-A28F-32DA-B72E-452EAD609613> /usr/lib/dyld
    0x7fff884f8000 -     0x7fff885fafff  libxml2.2.dylib (10.3.0 - compatibility 10.0.0) <AFBB22B7-07AE-3F2E-B88C-70BEEBFB8A86> /usr/lib/libxml2.2.dylib

Model: MacBookPro8,2, BootROM MBP81.0047.B27, 4 processors, Intel Core i7, 2 GHz, 16 GB, SMC 1.69f4
Graphics: AMD Radeon HD 6490M, AMD Radeon HD 6490M, PCIe, 256 MB
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 512 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1333 MHz, 0x029E, 0x434D5341384758334D314131333333433920
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 18 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: TOSHIBA MK5065GSXF, 500.11 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfa100000 / 3
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0246, 0xfa120000 / 5
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 4
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821a, 0xfa113000 / 7
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x8509, 0xfa200000 / 2
USB Device: hub_device, 0x0424  (SMSC), 0x2513, 0xfd100000 / 2
USB Device: hub_device, apple_vendor_id, 0x911f, 0xfd120000 / 4
USB Device: Keyboard Hub, apple_vendor_id, 0x1006, 0xfd121000 / 6
USB Device: Apple Keyboard, apple_vendor_id, 0x0221, 0xfd121200 / 7
USB Device: Apple Cinema HD Display, apple_vendor_id, 0x921f, 0xfd123000 / 5
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd110000 / 3

**Comment by skqr** [comment]
I had to manually create the local conf dir.

Other than that, it worked. I'm on a MacBook Pro on Yosemite.
