### ISSUE TITLE
Data type 'hstore' is not available

### ISSUE THREAD

**Issue by RoyalSens** [pgmodeler/pgmodeler#338]
When adding or editing a column definition in pgModeler, the data type 'hstore' is not available and therefore cannot be chosen. Is it possible to manually add datatypes? Or can that only be done in the sourcecode?

hstore is available as an extension to PostgreSQL and it can be installed as follows:
CREATE EXTENSION hstore;

And then used in a table definition as follows:
CREATE TABLE tablename (
  id serial PRIMARY KEY,
  attributes hstore
);

**Comment by maysam** [comment]
CREATE EXTENSION hstore WITH SCHEMA public;
