### ISSUE TITLE
Message returned: ERROR:  permission denied for relation pg_shadow

### ISSUE THREAD

**Issue by gcobr** [pgmodeler/pgmodeler#365]
When trying to use the reverse engineering feature, pgModeler gives me the following error message:

Message returned: ERROR:  permission denied for relation pg_shadow

Why is pgModeler trying to read pg_shadow? It shouldn't be required to reverse engineer database tables.

**Comment by mrlinton** [comment]
I believe I'm having the same or similar issue with running Postgres on RDS. I am able to successfully import but it is still pulling the roles and dependencies (even if de-select them). I tried updating the role.sch file but when doing so, I'm now getting a memory buffer error when selecting my DB in the import dialog:

Invalid syntax in file [memory buffer], line 5, column 5!

Have there been further updates to being able to import a schema from RDS Postgres and then export changes back?

Thank you in advance!

Mike

**Comment by rkhaotix** [comment]
@mrlinton  The problem is if a dependecy object is in a catalog view that your user is not allowed to read the import will fail.  Could you please provide the full error stacktrace generated by the import process? Thanks

**Comment by mrlinton** [comment]
I was able to get the above error resolved but I still have the fundamental problem with ultimately exporting my schema to the RDS-hosted DB. I can import successfully if I include the schema and at least the master user (not the superadmin) that is defined w/ RDS with my import. Then if I try to export back to the DB and select the 'Ignore Object Duplicity', I get the error: 

'ERROR:  permission denied to create role [masteruser]'

Is there a way around this? All I'm looking to do is export schema changes back to the DB.

Thanks again for your help!

**Comment by rkhaotix** [comment]
Yes. You can disable the SQL code of the role masteruser.
Just open the role's editing form and check the box 'Disable SQL' and run
the export again.

But let me inform you that the best way to export changes in the model to
an existing database is through the Diff tool.

--
Raphael Araújo e Silva
pgModeler Project Developer

raphael@pgmodeler.com.br
http://pgmodeler.com.br
https://github.com/pgmodeler

2017-02-07 18:57 GMT-03:00 mrlinton <notifications@github.com>:

**Comment by mrlinton** [comment]
Ah, I see the diff tool is really what I want, thank you for your help!
