### ISSUE TITLE
Custom compilation flags

### ISSUE THREAD

**Issue by hexum** [pgmodeler/pgmodeler#378]
I think it would be easier to add custom compiler flags if you append next strings to qt project files:

QMAKE_CXXFLAGS += $$(CXXFLAGS)
QMAKE_CFLAGS += $$(CFLAGS)
QMAKE_LFLAGS += $$(LDFLAGS)

**Comment by linux0uid** [comment]
I modified ebuild for 0.8.0 https://bugs.gentoo.org/show_bug.cgi?id=459918#c13
It is being built with plugins and lang files now.
https://github.com/linux0uid/gentoo-overlay/blob/master/dev-db/pgmodeler/pgmodeler-0.8.0.ebuild
