### ISSUE TITLE
Automatically layout model in different styles.

### ISSUE THREAD

**Issue by JustGitting** [pgmodeler/pgmodeler#423]
Hi,

I've looked through 0.7 and I cannot find an option for automatically changing the layout of the model. For example, DBVisualizer can layout the model using orthogonal, organic, etc style of linking and layout.

Will there be a future release that provides automatic layouts?

Thanks.

**Comment by diordonez** [comment]
This is definitely a must have feature in PGModeler. In general the application works very well, but setting the layout is a time consuming, let's say cumbersome operation.

Thanks

**Comment by diordonez** [comment]
Related to the item #588
