### ISSUE TITLE
tip: How to solve libpq dependency issue on Debian Wheezy to complie  pgmodeler

### ISSUE THREAD

**Issue by zekefast** [pgmodeler/pgmodeler#43]
It could be worth to add that tip somewhere to wiki page to help other.

So, the main problems is that `libpq` wasn't found and we would like to assist `pkg-config` tool with that.
What I found is the easiest way to solve this is to add `libpq.pc` file which contains information about library and let test in [COMPILING.md](https://github.com/pgmodeler/pgmodeler/blob/master/COMPILING.md#compiling) passed.
- Make sure you have installed `libpq-dev` and `libpq5` packages. This is at least what I have installed.

```
apt-get install libpq-dev libpq5
```

 or

```
aptitude install libpq-dev libpq5
```
- Create file `/usr/lib/x86_64-linux-gnu/pkgconfig/libpq.pc` with following content.

``` pc
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include

Name: LibPQ
Version: 5.0.0
Description: Library PQ
Requires:
Libs: -L${libdir} -lpq
Cflags: -I${includedir}/postgresql
```
- Run suggested in [COMPILING.md](https://github.com/pgmodeler/pgmodeler/blob/master/COMPILING.md#compiling) tests.

BTW, on some systems given path is absent. In that case you should make small investigation. 
What I did is to run `man pkg-config` and look for a paths where `pkg-config` utility usually stores *.pc files. There were few pathes mentioned there. All ended with `pkgconfig`. So, I just run (with `root` user credentials) search to find all directories with similar names.

```
find / -depth -type d -name pkgconfig
```

or

```
sudo find / -depth -type d -name pkgconfig
```

Here is what I saw on my system.

```
/usr/lib/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/share/pkgconfig
```

I selected `/usr/lib/x86_64-linux-gnu/pkgconfig` because there was `libxml-2.0.pc`, another dependency for pgmodeler.

**Comment by marcelojeff** [comment]
I'm on openSUSE and had same issue, this tip works with a little change in the last line, that should be: `Cflags: -I${includedir}/pgsql`.

**Comment by zekefast** [comment]
Thank you for writing here you fix!
