### ISSUE TITLE
Middle mouse panning

### ISSUE THREAD

**Issue by etosan** [pgmodeler/pgmodeler#430]
Please, add support for pannig with middle mouse button for users who have such mouse.

It is quite taxing to remember all those key+(left|right) mouse button combinations different programs tend to use. Middle mouse usually works in most software.

EDIT:
btw. very nice db modeler

**Comment by etosan** [comment]
Hello did you make any progress on this?

I tried to fix this myself, but as you said, this is surprisingly complex. 
Qt seems to be unfortunately and stupidly hardcoded to drag only on left mouse button.

I can get drag started with middle mouse button, but hand cursor doesn't grab unless I also press left button.

Seems like this guy found most reliable way to make it, by simply faking left mouse button press while dragging, and lets Qt reuse it's own drag state machine:
https://stackoverflow.com/questions/18551466/qt-proper-method-to-implement-panningdrag

Unfortunately my C++ skills are sucky at best. Also I am not very fond of OOP. When I tried to send fake event to view, like he does, it turns out methods he uses are not accessible in that context.

Maybe I am talking from my ass right now, but I guess it would require "subclass" the view object (I hope that is the right word) and replace methods there, so it sends left pressed while middle pressed?

Would you be so kind to look at this? After all you are much better at C++ than me and familiar with this codebase.

**Comment by rkhaotix** [comment]
Done here: 03a565f05861751a01e6ab44cfbe386a47eeb5dd

**Comment by etosan** [comment]
Thank you very much for this change!

It works great in my situation, I am immensely grateful for solving the issue.
