### ISSUE TITLE
Lack of option: Create relationship using existing fields

### ISSUE THREAD

**Issue by ezequielfalcon** [pgmodeler/pgmodeler#451]
Hi! This isn't really an issue, but I've would like to have that option (it can actually be created manually as a constraint). Thanks!

**Comment by hal-gh** [comment]
As a new user, it made it confusing by not having the suggestions made here. When will you be able to assign it to a milestone?

**Comment by rkhaotix** [comment]
Such feature is planned to version 0.9.0.
Em 08/05/2015 14:34, "hal-gh" <notifications@github.com> escreveu:

**Comment by hal-gh** [comment]
This isn't reflected in the milestone field of this ticket, tho.

**Comment by mgruel** [comment]
Is this feature included in the existing 0.9.0 release?
