### ISSUE TITLE
Is there anybody who give me a guide to compile pgModeler?

### ISSUE THREAD

**Issue by yangkwch** [pgmodeler/pgmodeler#464]
My compile environment is:
1. Windows 7 Ultimate
2. Qt 5.2.1 with Qt Creator 3.0.1
3. Postgre SQL 9.2
4. libxml2-2.7.8

Compilation whith Qt Creator  is finished but when I run pgmodeler, crashed.

I will thanks you if anyone can post a guideline for the pgModeler compilation in Windows 7 with Qt Creator 3.0.

Thanks

**Comment by AlexByNex** [comment]
Hi all! 
Help me please with trouble.
I have problem like this when try to run 'make' command after qmake:
 **************************************************************************************************
C:\Applications\pgmodeler-0.8.1-alpha1>qmake pgmodeler.pro

C:\Applications\pgmodeler-0.8.1-alpha1>make
MAKE Version 5.4  Copyright (c) 1987, 2010 Embarcadero Technologies, Inc.
Fatal: 'sub-libutils-make_first-ordered' does not exist - don't know how to make
 it
 **************************************************************************************************
Have some idea how to fix it?

**Comment by mlt** [comment]
@AlexByNex What compiler are you using? On windows, one usually downloads official QT binary for 32 bit along with mingw32 compiler used to build that QT, binary ZIP with PG 32 bit, and that is pretty much it from what I understand. So, it is mingw32-make.exe that you want.

**Comment by AlexByNex** [comment]
Sorry for not full information.
My compile environment is:
1. Windows XP SP2
2. Qt 5.2.1 with Qt Creator 3.0.1
3. Postgre SQL 9.2
4. libxml2-2.7.8

**Comment by mlt** [comment]
Uhm.. the question was about compiler and make tool. Also if you download PG 9.4 ZIP, it would have libxml 2.7.8 already included as a part of PG, so there is no need in separate copy.
You should see something like on the pic below while installing QT
![pic](https://musescore.org/sites/musescore.org/files/Qt-install.png)

**Comment by yangkwch** [comment]
At first, you have to set right path of PGSQL_LIB/PGSQL_INC/XML_INC/XML_LIB in pgmodeler.pri.
