### ISSUE TITLE
HSTORE Validation Problem

### ISSUE THREAD

**Issue by genebaker** [pgmodeler/pgmodeler#472]
I create the HSTORE extension, add an HSTORE datatype to a table and click to validate. I get the follow error:

![image](https://cloud.githubusercontent.com/assets/7683382/3070947/31e53432-e2b0-11e3-93d3-4702003209da.png)

What is the cause?

Thanks.

**Comment by pematt** [comment]
When I add the extension hstore in pgmodeler 0.9.0 then the data types are not created. Could have something to do with that but I don't really know. I do know that this is preventing me from using this product effectively and I am a paying customer.

**Comment by rkhaotix** [comment]
pgModeler can't understand that "hstore" extension creates datatypes. You SHOULD inform that the extension handles a datatype so pgModeler will create it internally so you can use it on your model.

To do that check the "Handles datatype" box in Extension's dialog prior the creation of this kind of object.

**Comment by pematt** [comment]
@rkhaotix thank you very much! I have done that now and the extension was added but no hstore datatype was added. How do I add the hstore datatype, please?
