### ISSUE TITLE
pgmodeler0.7.1 Failed to "make Install" Ubuntu 14.04

### ISSUE THREAD

**Issue by conyemaobi** [pgmodeler/pgmodeler#473]
Good day,

Please I have followed the Installation guide on 
http://www.pgmodeler.com.br/wiki/doku.php?id=installation&s[]=run&s[]=pgmodeler

I successfully installed all the dependencies
also
Successfully run "qmake pgmodeler.pro" and "make"
 but when i run  "make install" i get the following error:

strip:/opt/pgmodeler071/build/plugins/dummy/dummy.png: File format not recognized
make[1]: [install_dummy] Error 1 (ignored)
strip:/opt/pgmodeler071/build/plugins/dummy/dummy.json: File format not recognized
make[1]: [install_dummy] Error 1 (ignored)
strip:/opt/pgmodeler071/build/plugins/xml2object/xml2object.png: File format not recognized
make[1]: [install_xml2object] Error 1 (ignored)
strip:/opt/pgmodeler071/build/plugins/xml2object/xml2object.json: File format not recognized
make[1]: [install_xml2object] Error 1 (ignored)
strip:/opt/pgmodeler071/build/pgmodeler.vars: File format not recognized
make: [install_pgmodeler_data] Error 1 (ignored)
strip:/opt/pgmodeler071/build/README.md: File format not recognized
make: [install_pgmodeler_doc] Error 1 (ignored)
strip:/opt/pgmodeler071/build/CHANGELOG.md: File format not recognized
make: [install_pgmodeler_doc] Error 1 (ignored)
strip:/opt/pgmodeler071/build/LICENSE: File format not recognized
make: [install_pgmodeler_doc] Error 1 (ignored)

and it will exit without Intall

PLEASE ADVISE ME. 
THANKS

**Comment by GustaveCoste** [comment]
I just had the same problem on Ubuntu 14.04 trying to compile pgmodeler0.8.1.

Did you find any solution?
