### ISSUE TITLE
I can't compile on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by pierryangelo** [pgmodeler/pgmodeler#476]
I have followed what the oficial guide says, but after several hours trying to install I finally gave up, I got this message:

root@spck:/home/pierry/Downloads/pgmodeler-0.7.1# qmake pgmodeler.pro 
root@spck:/home/pierry/Downloads/pgmodeler-0.7.1# make
cd libutils/ && ( test -e Makefile || /opt/Qt5.3.0/5.3/gcc_64/bin/qmake /home/pierry/Downloads/pgmodeler-0.7.1/libutils/libutils.pro -o Makefile ) && make -f Makefile 
make[1]: Entrando no diretório `/home/pierry/Downloads/pgmodeler-0.7.1/libutils'
g++ -c -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/opt/Qt5.3.0/5.3/gcc_64/mkspecs/linux-g++ -I. -Isrc -I../libpgconnector/src -I../libparsers/src -I../libpgmodeler/src -I../libobjrenderer/src -I../libpgmodeler_ui/src -I../main/src -I/opt/Qt5.3.0/5.3/gcc_64/include -I/opt/Qt5.3.0/5.3/gcc_64/include/QtPrintSupport -I/opt/Qt5.3.0/5.3/gcc_64/include/QtWidgets -I/opt/Qt5.3.0/5.3/gcc_64/include/QtGui -I/opt/Qt5.3.0/5.3/gcc_64/include/QtCore -Imoc -I/usr/include/postgresql -I/usr/local/include/libxml2 -o obj/exception.o src/exception.cpp
rm -f libutils.so.1.0.0 libutils.so libutils.so.1 libutils.so.1.0
g++ -Wl,-O1 -Wl,-rpath,/opt/Qt5.3.0/5.3/gcc_64 -Wl,-rpath,/opt/Qt5.3.0/5.3/gcc_64/lib -shared -Wl,-soname,libutils.so.1 -o libutils.so.1.0.0 obj/exception.o  -L/opt/Qt5.3.0/5.3/gcc_64/lib -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread -L/usr/lib/postgresql/9.3/lib/libpq.so -lpq -L/usr/local/lib -lxml2 -lXext -lX11 -lm 
/usr/bin/ld: não foi possível encontrar -lGL
collect2: error: ld returned 1 exit status
make[1]: ** [../build/libutils.so.1.0.0] Erro 1
make[1]: Saindo do diretório`/home/pierry/Downloads/pgmodeler-0.7.1/libutils'
make: *\* [sub-libutils-make_first-ordered] Erro 2
root@spck:/home/pierry/Downloads/pgmodeler-0.7.1#

**Comment by maraya** [comment]
Man... you should leave this Debian/Ubuntu instructions on the installation guide...

Regards!
