### ISSUE TITLE
Failed to run qmake with arguments '-r-spec linux-g + + -64'

### ISSUE THREAD

**Issue by anderson-sousa** [pgmodeler/pgmodeler#495]
I use ubuntu 14.04 and I installed what was required and had the following error when running linuxdeploy.sh: 

Deploying version: 0.7.1 
Cleaning previous compilation ... 
Running qmake ... 

*\* Failed to run qmake with arguments '-r-spec linux-g + + -64' 

What can I do to fix this error?

**Comment by Daniel-Brosnan-Blazquez** [comment]
The script linuxdeploy.sh builds the command without including the project file and that is why the script is giving that error:
/usr/bin/qmake -r -spec linux-clang PREFIX=/opt/pgmodeler BINDIR=/opt/pgmodeler PRIVATEBINDIR=/opt/pgmodeler PRIVATELIBDIR=/opt/pgmodeler/lib LANGDIR=/opt/pgmodeler/lang SAMPLESDIR=/opt/pgmodeler/samples SCHEMASDIR=/opt/pgmodeler/schemas PLUGINSDIR=/opt/pgmodeler/plugins CONFDIR=/opt/pgmodeler/conf DOCDIR=/opt/pgmodeler SHAREDIR=/opt/pgmodeler TEMPDIR=/opt/pgmodeler/tmp

The argument pgmodeler.pro is missing:
QMAKE_ARGS="-r -spec linux-clang"
QMAKE_ARGS="$QMAKE_ARGS \
            PREFIX=$PREFIX \
            BINDIR=$BINDIR \
            PRIVATEBINDIR=$PRIVATEBINDIR \
            PRIVATELIBDIR=$PRIVATELIBDIR \
            LANGDIR=$LANGDIR \
            SAMPLESDIR=$SAMPLESDIR \
            SCHEMASDIR=$SCHEMASDIR \
            PLUGINSDIR=$PLUGINSDIR \
            CONFDIR=$CONFDIR \
            DOCDIR=$DOCDIR \
            SHAREDIR=$SHAREDIR \
            TEMPDIR=$TEMPDIR"
...
echo "Running qmake..."
$QMAKE_ROOT/$QMAKE_CMD $QMAKE_ARGS  >> $LOG 2>&1
