### ISSUE TITLE
 qt_xcb_createCursorXRender: query_pict_formats failed

### ISSUE THREAD

**Issue by pfoser** [pgmodeler/pgmodeler#496]
I am trying to run pgmodeler (tried with both binary and compiled version - same result) on a Ubuntu 12.04 VM.

The application starts (using the start-pgmodeler.sh script), but when trying to insert a new table it crashes and states "qt_xcb_createCursorXRender: query_pict_formats failed".

Has this happened to anyone else?

**Comment by Alphabaijinde** [comment]
> Seems some kind of incompatibility between Qt and Ubuntu. You're using such an old version of the latter. Please, try to run pgModeler at least on 13.x. If the error still persists we'll do a deep inspection on that..

Hello,I want to know how to solve this problem in the end.

**Comment by Alphabaijinde** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我已经收到您的邮件，会尽快回复的。
