### ISSUE TITLE
Locale errors when Validate/Export

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#498]
** This is a comment extracted from issue #467 since the context differs from the original issue! **

@rkhaotix Just to not create another issue, I want to post here because I'm getting an error similar to this one posted here. When I try to validate my model or export it to the server, I get this error:

**ERROR: new collation (en_AU.UTF8) is incompatible with the collation of the template database (en_AU.UTF-8) HINT: Use the same collation as in the template database, or use template0 as template. **

My locale is:
C.UTF-8
en_AU.utf8

I'm already using template0. I'm not sure but I think it's a silly mistake because pgModeler is trying to validate/export with the collation UTF8 and not with UTF-8 (Yeah, I think the problem is the hyphen).

Maybe they're facing the same problem in #468 and #306.

**Comment by erlonpinheiro** [comment]
I have the same sittuation, but with the collation pt_BR-UTF8
![pgmodeler1](https://cloud.githubusercontent.com/assets/5092413/5988239/87b566ba-a935-11e4-9191-cb83824c8a8f.png)

**Comment by rkhaotix** [comment]
@erlonpinheiro use a custom lc_collate and lc_ctype settings on db edit dialog. If you're running 0.8.0-alpha2 or above you can set a custom value for the mentioned fields just by typing a value on the combobox of each field.

**Comment by valq7711** [comment]
And I have  the same problem even after typing en_US.UTF-8. It was converted to abra-kadabra like en_US.UTF-8.UTF8, because  it's impossible to clear encoding field (supposedly).

**Comment by rkhaotix** [comment]
Thanks @valq7711 

Found a bug on the encoding field. I'll proceed with the proper fix!

**Comment by GAZ082** [comment]
Hi there. I'm running 0.8.1-alpha and cant change LC COLLATE nor LC CTYPE. O_O
