### ISSUE TITLE
Tables don't allow multiple foreign relationships from the same source table

### ISSUE THREAD

**Issue by robregonm** [pgmodeler/pgmodeler#513]
Replicate this way, using two tables:
Person
- id (pk)
- first_name (varchar)
- last_name (varchar)

Message
- id (pk)
- from_person_id (Foreign key from Person table)
- to_person_id (Another foreign key from Person table)
- message (text)

Pgmodeler doesn't allow to create two (or more) foreign keys from the same source table.

Thanks for the great work (and application).

Using v.0.8 alpha

**Comment by hendimarcos** [comment]
Using v0.8.2

![error_foreing](https://cloud.githubusercontent.com/assets/910965/17059324/fa80f976-4ffa-11e6-9787-a43f6f76072e.png)

How to add many relationships OneToMany between two tables from menu item New > Relationships?

I have always creates the field in the table and make foreingkey or can also be done by menu item New > Relationships > OneToMany?
