### ISSUE TITLE
Support to high resolution monitors

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#518]
Currently pgModeler isn't able to adpat its UI to high resolution monitors being impracticable its normal use. Some dialogs can't be resized what is causing some annoying issues. This issue requires  a complete UI redesign, including icons, images, input fields and many others. 

The dialogs must be able to "remeber" their previous sizes in order to avoid the user to do it again and again.

**Comment by aidanw** [comment]
This is still an issue in 2017!
![2017-04-21 10_21_31-pgmodeler - postgresql database modeler 0 9 0-beta](https://cloud.githubusercontent.com/assets/1986524/25271847/791096a8-267d-11e7-80f3-87047d5b2ff5.png)

**Comment by rkhaotix** [comment]
Yes. I'll add some improvements in order to diminish the problems still in 0.9.0-beta1 (already in development)

**Comment by archenroot** [comment]
rkhaotix needs first buy 4k monitor, so he can properly test :-)

**Comment by rkhaotix** [comment]
I got one already! Actually, a 2K monitor but it'll help in the same way! :D

**Comment by rkhaotix** [comment]
Here's the first result.. after have few lines of code tweaked! :)
This looks promising. The table editing dialog automatically resized to a 2K resolution with 162 dpi fonts. ;)

The only major problem now is to resize icons. Since the maximum size of icons is 32x32 I'll need to redesign all of them...

![table_dialog](https://cloud.githubusercontent.com/assets/2205476/25280360/1351f6f6-2680-11e7-8796-bfe7b3d7d662.png)

**Comment by archenroot** [comment]
Temporarily the icon size is not big deal, better have the visibility of values in tables.

But when you get to prepare new set, maybe it will be worth to get ready directly for 16K resolutions compatibility, as 8K is already here this year... :hammer:

**Comment by rkhaotix** [comment]
That's the idea ;)
