### ISSUE TITLE
src/exception.h:29:19: fatal error: QObject: No such file or directory

### ISSUE THREAD

**Issue by edouard-lopez** [pgmodeler/pgmodeler#524]
Hi,
I'm trying to build the the source on Linux Mint 17 (_i.e._ Ubuntu 14.04) and got the following error:

> WARNING: pgmodeler_data.path is not defined: install target not created
> 
> WARNING: pgmodeler_doc.path is not defined: install target not created
> 
> make[1]: Entering directory `/home/me/apps/pgmodeler-0.8.0-alpha1'
> cd libutils/ && make -f Makefile 
> make[2]: Entering directory`/home/me/apps/pgmodeler-0.8.0-alpha1/libutils'
> g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Isrc -I../libpgconnector/src -I../libparsers/src -I../libpgmodeler/src -I../libobjrenderer/src -I../libpgmodeler_ui/src -I../main/src -I/usr/X11R6/include -Imoc -I/usr/include/postgresql -I/usr/include/libxml2 -o obj/exception.o src/exception.cpp
> In file included from src/exception.cpp:18:0:
> src/exception.h:29:19: fatal error: QObject: No such file or directory
>  #include <QObject>
>                    ^
> compilation terminated.
> make[2]: **\* [obj/exception.o] Error 1
> make[2]: Leaving directory `/home/me/apps/pgmodeler-0.8.0-alpha1/libutils'
> make[1]: *** [sub-libutils-make_default-ordered] Error 2
> make[1]: Leaving directory`/home/me/apps/pgmodeler-0.8.0-alpha1'
> make: **\* [pgmodeler] Error 2
### Installation

Here is what I've installed and run:

``` bash
apt-get -y install libxml2{,-dev} libpq{5,-dev} qt{4,5}-qmake g++ libqt4-dev qt4-dev-tools libqt5serviceframework5 qtcreator{,-dev}  qtbase5-dev{,-tools}
pgmodelerVersion:=0.8.0-alpha1
wget --continue -O "${pgmodelerVersion}.tar.gz" https://github.com/pgmodeler/pgmodeler/archive/v${pgmodelerVersion}.tar.gz \
&& tar xvzf  "${pgmodelerVersion}.tar.gz" -C ./ ; \
cd pgmodeler-${pgmodelerVersion} \
&& qmake pgmodeler.pro &&  make && make install
```

Any idea what's missing?

**Comment by MATajik-mansoury** [comment]
for the same problem use cmake for compile  your program
Readme.howto.run:

% cd path_to_exampleXYZ     # go to directory which contains your example
       % mkdir exampleXYZ_build
       % cd exampleXYZ_build
       % cmake -DGeant4_DIR=path_to_Geant4_installation/lib[64]/Geant4-11.0.0/ ../exampleXYZ
       % make -j N exampleXYZ      # "N" is the number of processes
       % make install              # this step is optional
