### ISSUE TITLE
Wrong PostgreSQL function name

### ISSUE THREAD

**Issue by masimao** [pgmodeler/pgmodeler#536]
Hi,

When is defined a default sequence for a table column, pgModeler shows 'netval' instead of 'nextval'. Attached is an image with more details.

But the SQL code is generated normally.

Regards,

Marcio

![wrong_function_name](https://cloud.githubusercontent.com/assets/3603345/4142248/b9b96386-33b6-11e4-8051-7f8c5c43fa7e.png)

**Comment by ehsanvakili** [comment]
Hi,

This issue still exists in version 0.8.0 Win32.

Ehsan
