### ISSUE TITLE
erro após compilação

### ISSUE THREAD

**Issue by jrafaelg** [pgmodeler/pgmodeler#556]
Estou recebendo o seguinte erro após compilar o pgmodeler 0.7.2

---

pgmodeler.exe - Ponto de entrada não encontrado

---

Não foi possível localizar o ponto de entrada do procedimento _ZN7QString13toUtf8_helperERKS_ na biblioteca de vínculo dinâmico D:\Downloads\pgmodeler2\build\utils.dll. 

---

já compilei várias vezes e, durante a compilação, não ocorrem erros.

o que pode ser?

**Comment by nalomy** [comment]
Aconteceu comigo hoje também. porém com a versão 0.8.1. Eu tenho um exe dessa versão 0.7.2 caso precisar só informar que adiciono a um driver para você baixar.
