### ISSUE TITLE
Can't compile PGMODELER

### ISSUE THREAD

**Issue by stefannyza** [pgmodeler/pgmodeler#558]
szu@ste:/opt/pgmodeler-0.7.2$ qmake pgmodeler.pro
szu@ste:/opt/pgmodeler-0.7.2$ make 
cd libutils/ && ( test -e Makefile || /opt/Qt5.2.1/5.2.1/gcc_64/bin/qmake /opt/pgmodeler-0.7.2/libutils/libutils.pro -o Makefile ) && make -f Makefile 
make[1]: se ingresa al directorio «/opt/pgmodeler-0.7.2/libutils»
rm -f libutils.so.1.0.0 libutils.so libutils.so.1 libutils.so.1.0
g++ -Wl,-O1 -Wl,-rpath,/opt/Qt5.2.1/5.2.1/gcc_64 -Wl,-rpath,/opt/Qt5.2.1/5.2.1/gcc_64/lib -shared -Wl,-soname,libutils.so.1 -o libutils.so.1.0.0 obj/exception.o  -L/opt/Qt5.2.1/5.2.1/gcc_64/lib -lQt5PrintSupport -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread -L/usr/lib/postgresql/9.3/lib/libpq.so -lpq -L/usr/local/lib -lxml2 -lXext -lX11 -lm 
/usr/bin/ld: no se puede encontrar -lpq
collect2: error: ld returned 1 exit status
make[1]: **\* [../build/libutils.so.1.0.0] Error 1
make[1]: se sale del directorio «/opt/pgmodeler-0.7.2/libutils»
make: **\* [sub-libutils-make_first-ordered] Error 2

**Comment by nemtec** [comment]
Gracias smurav, esto me faltaba y ahora me funciona bien.  Estuve 3 días intentando instalar pgmodeler.

Saludos Cordiales.
