### ISSUE TITLE
Option 'if not exists' for extensions is not available.

### ISSUE THREAD

**Issue by RoyalSens** [pgmodeler/pgmodeler#560]
When you export a database to a server, which already has an extension that the schema also specifies, the export fails. Because the extension is simply added with CREATE EXTENSION <extension name> WITH SCHEMA public;

I would like to see an extra checkbox to add 'IF NOT EXISTS' to that statement.

Now I have to manually add a DROP statement to the prepend sql option, to mimic this behavior.

**Comment by posikifi** [comment]
Hi!

Is it possible add this "IF NOT EXISTS" -checkbox?

Now creation of PostGIS extension need superuser rights and we try to avoid using superuser-rights whenever it possible. Common way is to create template database with needed extension and then use template database as basis of your own database (need only CREATEDB rights).
