### ISSUE TITLE
Não é possível mudar o owner da tabela em relacionamentos N:N

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#579]
Não sei ao certo se é um problema, ou se não estou sabendo fazer, mas ao criar um relacionamento N:N onde ele cria uma tabela intermediária, se eu tentar editar esta tabela para mudar o owner, o pgmodeler não permite. Entendo que neste tipo de situação o pgmodeler proteja os objetos necessários, mas existem coisas que poderiam ser passíveis de mudança, tipo o owner e/ou "Esp. de Tabela".

![1](https://cloud.githubusercontent.com/assets/5092413/5631533/354246b6-95a6-11e4-9059-efdf549d90f1.png)

![2](https://cloud.githubusercontent.com/assets/5092413/5631536/394a9880-95a6-11e4-90fb-b0656299861a.png)

![3](https://cloud.githubusercontent.com/assets/5092413/5631538/3c302f88-95a6-11e4-879a-e027981150be.png)

![4](https://cloud.githubusercontent.com/assets/5092413/5631531/2cdae140-95a6-11e4-88b3-e2a26a6253f2.png)

**Comment by rkhaotix** [comment]
Devido à complexidade de implementação dos relacionamentos certas operações não são permitidas de uma forma direta. Alterar o dono ou tablespace da tabela intermediária é uma delas. Felizmente, existe uma solução para esta limitação: se você já efetuou toda configuração deseja no relacionamento basta clicar com o botão direito do mouse sobre o relacionamento n:n e acionar "Convert".

Assim o relacionamento é convertido explicitamente em uma tabela onde você poderá fazer alterações adicionais desejadas. Note que uma vez convertido o relacionamento não será mais possível desfazer a alteração caso você salve o modelo ou limpe o histórico de operações.

**Comment by erlonpinheiro** [comment]
Show de bola! 
Obrigado!

**Comment by rkhaotix** [comment]
Reabri o chamado pois é uma melhoria interessante.
