### ISSUE TITLE
Enable sql code drop and add if exists and cascade on statements

### ISSUE THREAD

**Issue by menwn** [pgmodeler/pgmodeler#581]
on 0.7.2 when I export the model to SQL I see that DROP statements are generates and are commented out. 

I was wondering if I could somehow make them to be enabled and add "IF EXISTS" table_name "CASCADE" to the statement.

**Comment by rkhaotix** [comment]
We can add this behavior as an option on export dialog. Once checked, pgModeler will execute any drop command attached to objects.

Thanks for the feedback
