### ISSUE TITLE
geometry handling doesn't work

### ISSUE THREAD

**Issue by hdus** [pgmodeler/pgmodeler#584]
I've added a geometry column into an existing model. The postgis extension is installed in the based database. But when I try to export the model or diff the model, in both cases I get the following error message:

"The object geometry_columns_insert (Rule) could not be imported due to one or more errors! Check the exception stack for more details."

What does it mean?

Here the exception report:

[8] src/schemaparser.cpp (1120)
  QString SchemaParser::getCodeDefinition(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `table' with an undefined value in file /usr/local/src/pgmodeler/schemas/xml/rule.sch, line 15, column 21!

[7] src/schemaparser.cpp (1408)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `table' with an undefined value in file /usr/local/src/pgmodeler/schemas/xml/rule.sch, line 15, column 21!

[6] src/schemaparser.cpp (887)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&, unsigned int)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `table' with an undefined value in file /usr/local/src/pgmodeler/schemas/xml/rule.sch, line 15, column 21!

[5] src/databaseimporthelper.cpp (766)
  void DatabaseImportHelper::loadObjectXML(ObjectType, attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `table' with an undefined value in file /usr/local/src/pgmodeler/schemas/xml/rule.sch, line 15, column 21!

[4] src/databaseimporthelper.cpp (1552)
  void DatabaseImportHelper::createRule(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `table' with an undefined value in file /usr/local/src/pgmodeler/schemas/xml/rule.sch, line 15, column 21!
       ** <extension name="postgis" cur-version="2.1.5">
	<schema name="public"/>
	<comment><![CDATA[PostGIS geometry, geography, and raster spatial types and functions]]></comment>
</extension>

[3] src/databaseimporthelper.cpp (638)
  void DatabaseImportHelper::createObject(attribs_map&)
    [ERR_OBJECT_NOT_IMPORTED] The object `geometry_columns_insert' (Rule) could not be imported due to one or more errors! Check the exception stack for more details.

[2] src/databaseimporthelper.cpp (315)
  void DatabaseImportHelper::createObjects()
    [ERR_OBJECT_NOT_IMPORTED] The object `geometry_columns_insert' (Rule) could not be imported due to one or more errors! Check the exception stack for more details.

[1] src/databaseimporthelper.cpp (551)
  void DatabaseImportHelper::importDatabase()
    [ERR_OBJECT_NOT_IMPORTED] The object `geometry_columns_insert' (Rule) could not be imported due to one or more errors! Check the exception stack for more details.

[0] src/modeldatabasediffform.cpp (528)
  void ModelDatabaseDiffForm::captureThreadError(Exception)
    [ERR_OBJECT_NOT_IMPORTED] The object `geometry_columns_insert' (Rule) could not be imported due to one or more errors! Check the exception stack for more details.

**Comment by rkhaotix** [comment]
This means that pgModeler somehow can't locate some object related to the
named object at the time when creating it. Try to check the option "Import
system objects " and "Import extension objects" before import or diff. This
can bloat the imported model but the chances to work are high.

Be in mind that import and diff processes, despite being in constantly
improvement, may fail depending on the configuration of the database.
Em 12/01/2015 16:26, "hdus" <notifications@github.com> escreveu:

**Comment by hdus** [comment]
I've tried your suggestions without success. You can download error log and model from here:

https://www.dropbox.com/s/6vc9ydm7fm7scxe/pgmodeler.zip?dl=0

**Comment by rkhaotix** [comment]
Thanks.
One mire question: what postgis version you're using?
Em 12/01/2015 16:59, "hdus" <notifications@github.com> escreveu:

**Comment by hdus** [comment]
PostgreSQL 9.3
PostGIS 2.1.5

**Comment by rkhaotix** [comment]
Ok. Later today I'll try to reproduce the error. Thanks
Em 12/01/2015 17:04, "hdus" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
@hdus I could identify the problem and create a first version of the fix. After apply the fix I could diff the model you've provided without errors. The problem was how pgModeler was retrieving the object during the diff process and wrongly selecting unnecessary extension objects leading to the errors you've repoted.

Could you please do some tests on your side? Use the code from the branch **export-changes**. This branch has incomplete code but you can use it just to validate the fix. Thanks.

**Comment by hdus** [comment]
I've tested the fix and it works fine for me. Thanks a lot for your fantastic work.
