### ISSUE TITLE
Inherited tables are not updated in all cases

### ISSUE THREAD

**Issue by hdus** [pgmodeler/pgmodeler#585]
I created some inherited tables and I made changes on the parent table. Add a column and delete a column. The added colum will appear in the child tables. But when I delete the column in the parent table it will not be removed from the child tables.

**Comment by rkhaotix** [comment]
Oh. This is not good. Seems we have a regression because this issue was
solved in older releases. How many levels is the inheritance you've created?
Em 13/01/2015 05:00, "hdus" <notifications@github.com> escreveu:

**Comment by hdus** [comment]
There is a further issue with inheritance. The child tables are created explicitly with all the inherited columns. Is that a feature?

**Comment by rkhaotix** [comment]
I suppose you're talking about diff / import process. This is a limitation
actually. The inheritance is a bit difficult to import from a existing
database. So pgModeler is forced to created the inherited columns on all
tables.
Em 13/01/2015 08:12, "hdus" <notifications@github.com> escreveu:

**Comment by hdus** [comment]
OK thank's for the clarification.

**Comment by rkhaotix** [comment]
You're welcome. I really sorry for this problem. I'll try to work on it
until the final release of 0.8.0
Em 13/01/2015 08:22, "hdus" <notifications@github.com> escreveu:
