### ISSUE TITLE
Thoughts on creating a cmake project for pgmodeler?

### ISSUE THREAD

**Issue by fire** [pgmodeler/pgmodeler#587]
What are your thoughts on creating  a cmake project for this project? 

I might be able to write a cmake for Windows.

**Comment by rkhaotix** [comment]
For now I'm not planning to move from qmake to cmake. But I evaluating tge
possibility to do that on a near future after release the 0.8.0
Em 26/01/2015 16:58, "K. S. Ernest (iFire) Lee" <notifications@github.com>
escreveu:
