### ISSUE TITLE
Diff doesn't detect new many to many relationships

### ISSUE THREAD

**Issue by marcelojeff** [pgmodeler/pgmodeler#589]
If I create a new `n:n` relationship and right after try to run a Diff, then the new relationships and the intermediate table aren't detected. I did some research but found nothing about.
If I create a new Table, for instance, then Diff works.

**Comment by rkhaotix** [comment]
Fixed  a6ad85dc04ce5433025da08b2d3b28140d55de67

**Comment by marcelojeff** [comment]
Works like a charm! Thanks

**Comment by rkhaotix** [comment]
You're welcome.
