### ISSUE TITLE
PK with more than one field

### ISSUE THREAD

**Issue by funtik1986** [pgmodeler/pgmodeler#591]
I created db on version 0.72. on this version all good. After that i compiled the last version from git. And i saw that if i load (nothing change) and save the project then for all fields with PK-constraint automatically filled the attribute "not null". It make sense if field only one. But if two or more fields than only the one value of fields should be not null. I propose remove this autofiled attribute "not null" for PK with many fields and stay for PK with one field.

**Comment by rkhaotix** [comment]
There is nothing wrong in automatically set columns as not null. Here the definition of pks extracted from PostgreSQL docs:


The primary key constraint specifies that a column or columns of a table can contain only unique (non-duplicate), nonnull values. Technically, PRIMARY KEY is merely a combination of UNIQUE and NOT NULL, but identifying a set of columns as primary key also provides metadata about the design of the schema, as a primary key implies that other tables can rely on this set of columns as a unique identifier for rows.

Only one primary key can be specified for a table, whether as a column constraint or a table constraint.

The primary key constraint should name a set of columns that is different from other sets of columns named by any unique constraint defined for the same table.
