### ISSUE TITLE
Field Rename

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#592]
When we rename a field, in the SQL commands, Pgmodeler drop the field and create another when the correct way would be use a rename structure.

**Comment by rkhaotix** [comment]
This is a limitation of diff process. Pgmodeler does not know if the object
was renamed and generate a drop for it. There's some additional operations
that must be implemented to see this feature fully functional. It will be
gradually improved as new releases come out
Em 01/02/2015 16:09, "erlonpinheiro" <notifications@github.com> escreveu:
