### ISSUE TITLE
Button close in "Generate diff from model" doesn't close. ;)

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#593]
When we click close button in "Generate diff from model" nothing happens. We need to press esc to close this window without process the diff sql commands.

![pgmodeler](https://cloud.githubusercontent.com/assets/5092413/5993213/4006381a-aa27-11e4-85f5-c8153f8e30fc.png)

**Comment by rkhaotix** [comment]
Get back to the "output " tab and see what is written in the last item ;)
Em 01/02/2015 16:30, "erlonpinheiro" <notifications@github.com> escreveu:

**Comment by erlonpinheiro** [comment]
But if i see the diff sql script and decide not run it ? :P The close button would be the logical choice, no?

**Comment by rkhaotix** [comment]
You need to cancel the process first. By pressing Esc or click cancel on
the output tab and then close the dialog
Em 01/02/2015 16:58, "erlonpinheiro" <notifications@github.com> escreveu:

**Comment by erlonpinheiro** [comment]
Ok. I understood now! 
Thanks.
