### ISSUE TITLE
UIC output in wrong folder?

### ISSUE THREAD

**Issue by DobiSoft** [pgmodeler/pgmodeler#594]
Hi,

I tried to build the latest beta in Win7 x64 with the latest QT Creator (qt 5.4) using boundled minGW 32bit.

The source tree was installed in pgmodeler folder. I fixup the libpg.dll and the xml lib variables in the pgmodeler.pro file and started to build.

1st thin. The build process make a new folder structure in the same level as pgmodeler folder for all build artifacts. 
so i have now a "build-pgmodeler-Desktop_Qt_5_4_0_MinGW_32bit-Release" folder and inside this folder i getting all the subprojects folders with moc obj src folders. 

in the pgmodeler/build folder only the binaries can be found.

But when a subproject is referencing a ui_*.h file (an uic output) it cannot found it and build is aborted.

First such  project in the build queue is the crashhandler and when it includes the messagebox.h from the pgmodeler_ui project and it is including the ui_messagebox.h it cannot be found.

I think there is some misconfiguration in  the pgmodeler.pro, in every  pro file the moc ui variables setup like this:

MOC_DIR = moc
OBJECTS_DIR = obj
UI_DIR = src

Can it be a problem? Maybe we must setup those relative to the basepath ?

**Comment by rkhaotix** [comment]
There is nothing wrong with pgmodeler.pro file or other pro's. Just disable
"Shadow build " on Qt creator and the process will run fine.
Em 01/02/2015 19:53, "DobiSoft" <notifications@github.com> escreveu:
