### ISSUE TITLE
V8b2 : import error

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#595]
Hi,

First : very nice tool ! I'm trying it since few weeks.
I'm trying to import an existing database (9.4).
There is a trigger on a table (entite), but it seems that the import function try to import the trigger before the table.
Here the error : 
> [6] src/databasemodel.cpp (5129)
>   Trigger* DatabaseModel::createTrigger()
>     [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_entite_requete' (Déclencheur) is referencing the object `public.entite' (Table) which was not found in the model!
> 
> [5] src/databasemodel.cpp (5253)
>   Trigger* DatabaseModel::createTrigger()
>     [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_entite_requete' (Déclencheur) is referencing the object `public.entite' (Table) which was not found in the model!
>        ** <trigger name="update_entite_requete" firing-type="BEFORE" per-line="true" constraint="false"
> 	 ins-event="false" del-event="false" upd-event="true" trunc-event="false"
> 	 table="public.entite">
> 	<condition><![CDATA[(new.requete <> old.requete)]]></condition>
> 		<function signature="public.update_entite_requete()"/>
> </trigger>
> 
> 
> 
> [4] src/databaseimporthelper.cpp (1562)
>   void DatabaseImportHelper::createTrigger(attribs_map&)
>     [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_entite_requete' (Déclencheur) is referencing the object `public.entite' (Table) which was not found in the model!
>        ** <trigger name="update_entite_requete" firing-type="BEFORE" per-line="true" constraint="false"
> 	 ins-event="false" del-event="false" upd-event="true" trunc-event="false"
> 	 table="public.entite">
> 	<condition><![CDATA[(new.requete <> old.requete)]]></condition>
> 		<function signature="public.update_entite_requete()"/>
> </trigger>
> 
> 
> 
> [3] src/databaseimporthelper.cpp (621)
>   void DatabaseImportHelper::createObject(attribs_map&)
>     [ERR_OBJECT_NOT_IMPORTED] The object `update_entite_requete' (Déclencheur) could not be imported due to one or more errors! Check the exception stack for more details.
> 
> [2] src/databaseimporthelper.cpp (316)
>   void DatabaseImportHelper::createObjects()
>     [ERR_OBJECT_NOT_IMPORTED] The object `update_entite_requete' (Déclencheur) could not be imported due to one or more errors! Check the exception stack for more details.
> 
> [1] src/databaseimporthelper.cpp (534)
>   void DatabaseImportHelper::importDatabase()
>     [ERR_OBJECT_NOT_IMPORTED] The object `update_entite_requete' (Déclencheur) could not be imported due to one or more errors! Check the exception stack for more details.
> 
> [0] src/databaseimportform.cpp (351)
>   void DatabaseImportForm::captureThreadError(Exception)
>     [ERR_OBJECT_NOT_IMPORTED] The object `update_entite_requete' (Déclencheur) could not be imported due to one or more errors! Check the exception stack for more details.
>

**Comment by rkhaotix** [comment]
Hi @rimbault 

It is possible to you to send me the dump of the database you're trying to import?
Thanks

**Comment by andersonlunz** [comment]
Hi,
I'm having the same problem here. I'm using pgmodeler 0.7.2 and when I try to import a schema with a table that has a trigger on it, I get an error. It seems that it tries to import the trigger before importing the table.

Here's the error reported by pgmodeler:

[6] src/databasemodel.cpp (4991)
  Trigger *DatabaseModel::createTrigger(BaseTable *)
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_available_imsi_range_update_ts' (Trigger) is referencing the object `sim_depot.available_imsi_range' (Table) which was not found in the model!

[5] src/databasemodel.cpp (5118)
  Trigger *DatabaseModel::createTrigger(BaseTable *)
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_available_imsi_range_update_ts' (Trigger) is referencing the object `sim_depot.available_imsi_range' (Table) which was not found in the model!
       ** <trigger name="update_available_imsi_range_update_ts" firing-type="BEFORE" per-line="true" constraint="false"
	 ins-event="false" del-event="false" upd-event="true" trunc-event="false"
	 table="sim_depot.available_imsi_range">
		<function signature="sim_depot.update_column_update_ts()"/>
</trigger>


[4] src/databaseimporthelper.cpp (1600)
  void DatabaseImportHelper::createTrigger(attribs_map &)
    [ERR_REF_OBJ_INEXISTS_MODEL] The object `update_available_imsi_range_update_ts' (Trigger) is referencing the object `sim_depot.available_imsi_range' (Table) which was not found in the model!
       ** <trigger name="update_available_imsi_range_update_ts" firing-type="BEFORE" per-line="true" constraint="false"
	 ins-event="false" del-event="false" upd-event="true" trunc-event="false"
	 table="sim_depot.available_imsi_range">
		<function signature="sim_depot.update_column_update_ts()"/>
</trigger>


[3] src/databaseimporthelper.cpp (611)
  void DatabaseImportHelper::createObject(attribs_map &)
    [ERR_OBJECT_NOT_IMPORTED] The object `update_available_imsi_range_update_ts' (Trigger) could not be imported due to one or more errors! Check the exception stack for more details.

[2] src/databaseimporthelper.cpp (318)
  void DatabaseImportHelper::createObjects()
    [ERR_OBJECT_NOT_IMPORTED] The object `update_available_imsi_range_update_ts' (Trigger) could not be imported due to one or more errors! Check the exception stack for more details.

[1] src/databaseimporthelper.cpp (524)
  void DatabaseImportHelper::importDatabase()
    [ERR_OBJECT_NOT_IMPORTED] The object `update_available_imsi_range_update_ts' (Trigger) could not be imported due to one or more errors! Check the exception stack for more details.

[0] src/databaseimportform.cpp (345)
  void DatabaseImportForm::captureThreadError(Exception)
    [ERR_OBJECT_NOT_IMPORTED] The object `update_available_imsi_range_update_ts' (Trigger) could not be imported due to one or more errors! Check the exception stack for more details.

**Comment by rimbault** [comment]
Hi Raphael,

The dump (without data) is attached to this mail.

Thanks !

Philippe


2015-02-04 20:39 GMT+01:00 Raphael Araújo e Silva <notifications@github.com>
:

**Comment by rimbault** [comment]
Raphael,

I've tried tio restore the dump on my local postgres and the import
function of pgmodeler work fine ...
The problème exists only on my production server (9.4) and on an other
database (9.2) with also a trigger.




2015-02-05 9:12 GMT+01:00 philippe rimbault <philippe@rimbault.org>:

**Comment by rkhaotix** [comment]
It could be an issue with 9.4. Please send the dump to my email raphael @
pgmodeler.com.br
Github extract any attachment from issues emails.
Em 05/02/2015 08:03, "rimbault" <notifications@github.com> escreveu:
