### ISSUE TITLE
pgmodeler-0.8.0-beta1/libpgmodeler_ui/src/messagebox.h:28:27: fatal error: ui_messagebox.h: No such file or directory

### ISSUE THREAD

**Issue by COLABORATI** [pgmodeler/pgmodeler#596]
Hi, I can not compile 0.8.0-beta1 on Ubuntu with QT Creator based on QT 5.4.0.

pgmodeler-0.8.0-beta1/libpgmodeler_ui/src/messagebox.h:28:27: fatal error: ui_messagebox.h: No such file or directory

I see there is a messagebox.ui file in "libpgmodeler_ui/ui/messagebox.h" but I do not know how to make QT include this file. Just doing this 

#include "../ui/messagebox.ui"

on top of libpgmodeler_ui/src/messagebox.h does not help. Even when I put the full path into the include statement it does not help. I assume somewhere needs to be defined a valid include path.

Sorry, I am new with QT so I do not understand where these path dependencies are defined.

**Comment by rkhaotix** [comment]
Hi. See here #594 

You are probably trying to build using "Shadow build" setting. Deactivate it and the process will work.
