### ISSUE TITLE
Is there some way to import a function from a database to a existent diagram ?

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#598]
Sometimes, write functions directly on database is more efficient than using pgmodeler (words from my DBA :P ). This, because, we need to change a lot of things during the test procedures. In the end, when the new function was sufficiently tested, would easier if pgmodeler could import this new function to a existent diagram. Is there this feature?

**Comment by rkhaotix** [comment]
No, there isn't. But I was planning to do a model merge feature that is similar to what you need. I'll create a ticket for it. Milestone 0.9.0 :)

**Comment by rkhaotix** [comment]
By the way, the copy/paste doesn't serves as a workaround for you? :)

**Comment by erlonpinheiro** [comment]
I will try. I need to see how will be the behavior with dependencies. ;) But thanks! ;) Something more, I put here.

**Comment by rkhaotix** [comment]
The copy process brings all dependencies of the object too... So, at a first glance, you'll not have any problem doing that... :)
