### ISSUE TITLE
All database listed although connection set up for one.

### ISSUE THREAD

**Issue by efedoso** [pgmodeler/pgmodeler#601]
In Settings > Connections, you can set up a connection for a specific database. However, when you connect to that database from Manage, you get listed that one and all the other ones in the server. I think connections should be useful to «isolate» one or several databases (according to the permissions for the user used in the connection) from the rest.

**Comment by rkhaotix** [comment]
You do not set up a connection for a specific database. The database required on the connection configuration is the INITIAL database, which means, the first database pgModeler will connect before handle other database or objects in the server.

The isolation is controlled by the permissions on PostgreSQL. If a database is listed it does not means that a specific user (which is configured on the connection) will access it. All database is listed for one to know how many db's are in the server.

**Comment by efedoso** [comment]
All right. But, if I've understood your explanation, I could expect the database configured in the connection to be the one automatically showed for browsing when I use it for connectiong to the server, such I'm used to in pgAdmin, for example. What I get is the same as when I use a global connection with user postgres: the select list with every database in the server, from which I have to select the database and then click «browse selected database» to finaly get to it.

**Comment by rkhaotix** [comment]
What you are expecting is that the db you set up on the connection could be automatically selected when using the "Manage" view? If so... this is quite possible.

**Comment by efedoso** [comment]
Yes, that's what I expected; also, what I'm used to in other database managers, and I think that makes sense when configuring a connection for a particular database.

**Comment by efedoso** [comment]
By the way: happens the same in the "Database import" dialog. Also, every role in the server is checked by default. Maybe would be more convenient that only the roles with permissions on the connected database are selected?

**Comment by rkhaotix** [comment]
I've done a little modification on the connection config dialog to set a connection to auto browse the database (optional) when using it on "Manage" view. 

By the way, I don't agree that the same behavior must be reproduced in Database import. I think that on that dialog the user must have the freedom to choose the database before start the import process.

**Comment by efedoso** [comment]
Yes, perhaps it is correct the database import as it is now. Didn't give much thought. Anyway: you rule ;)
