### ISSUE TITLE
Command history with old entries.

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#603]
This is a sugestion. (I dont know if this is a correct place to sugestions).

When we close the pgmodeler, all commands used in "manage module" are discarded. Would be interesting if this history can be saved automaticaly in a file, and loaded when we click on "manage module".

![pgmodeler](https://cloud.githubusercontent.com/assets/5092413/6146855/13a6b708-b1d0-11e4-945d-ef37a37a7c39.png)

Maybe will be needed a new parameter in config area which define a limit quantity of these commands that will be saved.

**Comment by rkhaotix** [comment]
Suggestions can be written here too. :)

It's a good idea... I'll think on the best way to store the command history.

Thanks.

**Comment by rkhaotix** [comment]
The command history is now saved and restored automatically. The history is separeted by database connection. So each connection will have a separeted set of commands saved. You can managed the history by right-clicking it to expose the available options. Also, the size of the history is controlled in the general settings
