### ISSUE TITLE
Error when we do diff procedure.

### ISSUE THREAD

**Issue by erlonpinheiro** [pgmodeler/pgmodeler#605]
After the last update (to version v0.8.0-beta2), pgmodeler presents an error on a diff procedure. 
I have a model that works fine with the prior version, but now, it show this screen:

![pgmodeler-2](https://cloud.githubusercontent.com/assets/5092413/6147674/c0e95cc4-b1d8-11e4-852a-edf81e1f6dc5.png)

Details:

I'm generating a diff from model to a server and  there is a object arc_archive_date (column) in model and in the database, and both are identical. I think that pgmodeler shouldn't make some actions in this case, right ?

Another thing is: The public.archiving_01_02 table is inherited from another table.

**Comment by rkhaotix** [comment]
It'll help me if you post the error stack too. The error message only is a bit generic... I need to know the exact point where the error occurred.

**Comment by erlonpinheiro** [comment]
How can I do this ? Look. Pgmodeler doesn't crash on this situation, but it shouldn't try to remove this field because already there is in database and how there is a index reference, pgmodeler reports that can't continue and doesn't make the diff procedure. Stops there.

**Comment by rkhaotix** [comment]
Click on the green arrow at message box, you will see the error stack (methods on the codes that raised exceptions). I need that information.

**Comment by rkhaotix** [comment]
If possible, please send me a copy of the model. I'll try to reproduce the error on my dev. environment.

**Comment by erlonpinheiro** [comment]
Living and learning! :P 

[4] src/table.cpp (636)
  virtual void Table::removeObject(unsigned int, ObjectType)
    [ERR_REM_INDIRECT_REFERENCE] The object `arc_archive_date' (Coluna) can not be removed because it is being referenced by object `idx_archiving_01_02_arc_archive_date' (Índice) that belongs to `public.archiving_01_02' (Tabela)!

[3] src/table.cpp (550)
  virtual void Table::removeObject(BaseObject *)
    [ERR_REM_INDIRECT_REFERENCE] The object `arc_archive_date' (Coluna) can not be removed because it is being referenced by object `idx_archiving_01_02_arc_archive_date' (Índice) that belongs to `public.archiving_01_02' (Tabela)!

[2] src/databaseimporthelper.cpp (1876)
  void DatabaseImportHelper::createTableInheritances()
    [ERR_REM_INDIRECT_REFERENCE] The object `arc_archive_date' (Coluna) can not be removed because it is being referenced by object `idx_archiving_01_02_arc_archive_date' (Índice) that belongs to `public.archiving_01_02' (Tabela)!

[1] src/databaseimporthelper.cpp (534)
  void DatabaseImportHelper::importDatabase()
    [ERR_REM_INDIRECT_REFERENCE] The object `arc_archive_date' (Coluna) can not be removed because it is being referenced by object `idx_archiving_01_02_arc_archive_date' (Índice) that belongs to `public.archiving_01_02' (Tabela)!

[0] src/modeldatabasediffform.cpp (513)
  void ModelDatabaseDiffForm::captureThreadError(Exception)
    [ERR_REM_INDIRECT_REFERENCE] The object `arc_archive_date' (Coluna) can not be removed because it is being referenced by object `idx_archiving_01_02_arc_archive_date' (Índice) that belongs to `public.archiving_01_02' (Tabela)!

I will send the model to your mail, ok ?

**Comment by rkhaotix** [comment]
Ok. Thanks.

For now I can investigate portions of the code...I'll be waiting the model.

**Comment by erlonpinheiro** [comment]
Sent!

**Comment by rkhaotix** [comment]
Thanks. I already have a suspect... :)
