### ISSUE TITLE
SQL validation failed...

### ISSUE THREAD

**Issue by jigdoc** [pgmodeler/pgmodeler#606]
I did run the script at PgAdminIII and it works (?) ! - this problem was sent to bug mail, too.

SQL validation failed due to error(s) below. NOTE: These errors does not invalidates the model but may affect operations like export and diff.

Could not connect to the database.
Message returned: `servidor fechou a conexão inesperadamente
    Isto provavelmente significa que o servidor terminou de forma anormal
    antes ou durante o processamento do pedido.

**Comment by rkhaotix** [comment]
This bug can be reproduced easily or it is sporadic?
In my development machine this does not occurs... Tested several times with the model you've sent me and with some I have here... All working fine.. :/

**Comment by jigdoc** [comment]
Thank you for your attention. It is sporadic ...
I think there was something wrong with updating the version of PostgreSQL
(9.3.x to 9.4)
Thank you again.

2015-02-19 9:52 GMT-02:00 Raphael Araújo e Silva <notifications@github.com>:
