### ISSUE TITLE
linuxdeploy.sh Qt core library copy - Wrong path on Fedora (21)

### ISSUE THREAD

**Issue by hassonofer** [pgmodeler/pgmodeler#607]
In line ~203 of linuxdeploy.sh:
qtpaths --install-prefix returns: /usr/lib64/qt5 on Fedora 21 (and i guess 20 as well)

then in the loop that copies the libraries it tries to copy from this path:
cp /usr/lib64/qt5/lib/$lib $BUILD_DIR/$INSTALL_ROOT/lib

instead of /usr/lib64/ $lib $BUILD_DIR/$INSTALL_ROOT/lib

the rest is fine, plugin copy and so on.

**Comment by rkhaotix** [comment]
the deployment scripts are tuned to my development environment (OpenSuse).
Note that paths may change from distro to distro. The user must change the
path according to his system.
Em 16/02/2015 13:04, "hassonofer" <notifications@github.com> escreveu:
