### ISSUE TITLE
Unable to compile Win 8.1

### ISSUE THREAD

**Issue by mytrix** [pgmodeler/pgmodeler#610]
Qt 5.4.1 for Windows 32-bit (VS 2013)
Mingw for Qt (i686-4.9.2-posix-dwarf-rt_v3-rev1)

After qmake i received this error:

<pre>
E:\Develope\pgmodeler-develop>mingw32-make
cd libutils\ && ( if not exist Makefile E:\Develope\Qt\Qt5.4.1\5.4\msvc2013\bin\
qmake.exe E:\Develope\pgmodeler-develop\libutils\libutils.pro -o Makefile ) && m
ingw32-make -f Makefile
mingw32-make[1]: Entering directory 'E:/Develope/pgmodeler-develop/libutils'
mingw32-make -f Makefile.Release
mingw32-make[2]: Entering directory 'E:/Develope/pgmodeler-develop/libutils'
<strong>Makefile.Release:64: *** missing separator.  Stop.</strong>
mingw32-make[2]: Leaving directory 'E:/Develope/pgmodeler-develop/libutils'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'E:/Develope/pgmodeler-develop/libutils'
makefile:48: recipe for target 'sub-libutils-make_first-ordered' failed
mingw32-make: *** [sub-libutils-make_first-ordered] Error 2</pre>

What`s wrong? Thx.

**Comment by rkhaotix** [comment]
Seems you're using a Qt bundled for MSVC. Pgmodeler works only with gcc,
clang and mingw (Windows)
Em 26/02/2015 16:28, "mytrix" <notifications@github.com> escreveu:

**Comment by mytrix** [comment]
Omg, I was absolutely blind when I have searched the download link for Qt..
Thank you!

I`ll send you some donation for coffe :) It`s a great app and to so much work.

**Comment by rkhaotix** [comment]
No problem! You're welcome and thanks for the donation! ;)
