### ISSUE TITLE
Some suggestions to facilitate the work

### ISSUE THREAD

**Issue by mytrix** [pgmodeler/pgmodeler#613]
Hi, I have some suggestions. I think, that these improvements could facilitate the work :-)

<b>Automatically create a sequence for PK of serial/bigserial data type</b>
I think that easiest way to do this, that if the user choose as default value "sequence" with no selection, the new sequence will be created automatically.

<b>Automatically expand a tree of choices eg. tags, schemas etc.</b>
By default is closed and I must click to expand it.

<b>Set schema of object by parent</b>
Eg:Available schemas: public, shared (public is set as default for model)
When I click in area of "shared" schema to create of a new object, it should by used this schema instead of the default. The default schema should be used only when I click somewhere else (outside of schema)

**Comment by rkhaotix** [comment]
**Automatically create a sequence for PK of serial/bigserial data type**
_Tried to right click a serial type and click "Convert to sequence"? :)_

**Automatically expand a tree of choices eg. tags, schemas etc.**
_Be more specific. If we expand the entire tree it will be quite annoying in my opinion. Furthermore there are buttons to expand / collapse the object's tree._

**Set schema of object by parent**
_Tried to right click the schema and select "New > [object]"? This will create a new object assigning the selected schema to it_ :)

**Comment by mytrix** [comment]
1) Thx. You saved my life :)

2) Left column = what's opened, right column = what I need
It does not seem, but If you work with a lot of tables, it's tiresome always exapnding the tree
![tree](https://cloud.githubusercontent.com/assets/3493273/6426665/76c2c706-bf67-11e4-9cf9-e79873b2ba82.png)

3) It does not work for me. I click inside the "shared" schema but the default schema is still "app" (which is default in my model)
![schema](https://cloud.githubusercontent.com/assets/3493273/6426686/2874c2e2-bf68-11e4-9adb-ae0b28ec4168.png)

**Comment by mytrix** [comment]
Ad 1) Bug: If the table doesn't have a primary key, program crashes during "Convert to sequence" command.
