### ISSUE TITLE
DLL entry point __gxx_personality_v0 not found.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#621]
I installed pgModeler 0.8.0 on Windows 81. and got the error that the DLL entry point __gxx_personality_v0 is not found in the DLL C:\Program Files (x86)\pgmodeler\lib\utils.dll. Looking at the DLL with a HEX editor I can see at least that string, but don't know any further. The former version 0.72.0 ran fine. I uninstalled the former version before installing the newer one as well.

This looks like some kind of linker error. Any ideas?

**Comment by rkhaotix** [comment]
It's seems you have another libstdc++6.dll on your system and the version of it is different from the one that comes with pgmodeler. Did you uninstalled 0.7.2 or kept this version and installed 0.8.0 in another location? If so, uninstall both, remove any reference to pgmodeler on PATh environment variable and install 0.8.0 again.

**Comment by tschoening** [comment]
I uninstalled both and removed the folders, no change. Do you really think another DLL is the problem? This problem didn't occure with the older version and the error dialog already mentions your DLL, not another. It even uses the "lib" folder, while your former DLLs where in the application root.

**Comment by tschoening** [comment]
I searched all my files and there's no file called libstdc++6.* anywhere.

**Comment by rkhaotix** [comment]
This is kinda strange. You are the first Windows 8.1 user that is facing
and reporting such error (and I have a lot of users running this OS). I
have my doubts if this is a linkage problem... :(
I'll investigate... The problem is, I don't have Windows 8.1... :/

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-03-03 13:24 GMT-03:00 tschoening <notifications@github.com>:

**Comment by rkhaotix** [comment]
I'll try to get an Windows 8.1 and run it on a VM!

**Comment by tschoening** [comment]
I was wrong, I made a mistake in my search, your were right, I had another libstdc++-6.dll in a GnuPG application folder which came first in PATH. I changed the order of both entries and now pgModeler works.

But this is a bad design, apps shouldn't just add such folders with DLLs to PATH because of exactly the problem I've had: You can't guarantee anymore which DLL gets loaded. Some even consider this as a security vulnerability, because any other app can get you to use their malicious DLL by just providing one with the same name. From that point of view, your former layout with DLLs in the app root were more maintainable...

https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

**Comment by rkhaotix** [comment]
Great.

Thanks for the hint about security breachs. I'm not the most experienced
Windows user/developer. I'll revert the former file structure in the first
patch release 0.8.1
Em 03/03/2015 13:49, "tschoening" <notifications@github.com> escreveu:

**Comment by tschoening** [comment]
You don't necessarily need to, but the only alternative I know of is to load the DLLs on your own using LoadLibrary or LoadLibraryEx, because that way you can add your lib folder to your application specific search path on runtime without using the PATH env var. But I know that this is a lot of work if you currently rely on automatically loaded DLLs by Windows. In that case, I would suggest as well to use your old dir structure. That's not as clean as your current one, and I would prefer your current one vbecause of that too ;-), but it will work better in cases like mine, where other apps use PATH as well do load DLLs.

http://support.microsoft.com/kb/2389418
https://msdn.microsoft.com/en-us/library/windows/desktop/ff919712(v=vs.85).aspx

**Comment by maniac787** [comment]
version 0.8.0
Inicien una terminal CMD como administrador e instalen desde ahi.
100% probado a mi me funciono y tenia el mismo problema.

**Comment by rkhaotix** [comment]
@maniac787 The problem was related to the new installation folder arrangement. I reverted back the the original one to solve the issue and reuploaded the installer. I'll think in a way (as @tschoening suggested) to use a clean folder structure and avoid this problem (DLL entry point).

**Comment by tschoening** [comment]
[Dynamic-Link Library Redirection](https://msdn.microsoft.com/de-de/library/windows/desktop/ms682600(v=vs.85).aspx) might be interesting for your last question:

    Alternatively, if a directory named c:\myapp\myapp.exe.local exists and contains mydll.dll,
    LoadLibrary loads c:\myapp\myapp.exe.local\mydll.dll.

I didn't tested it myself and such a dir name might not be as friendly as "lib", but if it works...

**Comment by tschoening** [comment]
I've found another two interesting sources on this topic, though I think the former approach is easier to implement:

https://msdn.microsoft.com/en-us/library/windows/desktop/ee872121?f=255&MSPPError=-2147217396#app_exe

> A secondary source of path pollution came from applications which added not only the application
> directory to the path, but also a helper directory where the application kept its DLLs. To address
> this, an additional Path value specified which directories your application wanted to be added to
> the path before it was executed.

https://blogs.msdn.microsoft.com/oldnewthing/20110725-00/?p=10073/

**Comment by tschoening** [comment]
Another interesting method to solve the problem and this looks nearly as easy to implement like my first suggestion with the `*.local` dir, but it seems you could keep your `lib` folder:

> Attribute	Description
privatePath	Specifies the relative paths of subdirectories of the application's base directory that might contain assemblies. A maximum of nine subdirectory paths can be specified. Delimit each subdirectory path with a semicolon.

https://msdn.microsoft.com/en-us/library/aa374182(VS.85).aspx

You would just need to create some manifest files for your existing DLLs, like is described in the following link in comment 1:

https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/3e82b658-e070-4b88-aaf2-0649ddb222d2/how-to-write-manifest-file-to-pick-up-dlls-via-dll-redirection

> Step 1 would be to take each of your dll's, and turn them into an assembly. Or assemblies.
> You do this - simply, by adding a .manifest file to the same folder as the dll.[...]
> Step 2 - make the applications use the assemblies to load the dlls.[...]
> Step 3 - test that the manifests are all correct.[...]
> Step 4. Add an application configuration file to do a probing path:[...]
