### ISSUE TITLE
Please add AppData

### ISSUE THREAD

**Issue by Hubbitus** [pgmodeler/pgmodeler#622]
Hello.
Firstly thank you for the great software.

Could you please add AppData to more sanee present it in Fedora Linux distribution?
http://people.freedesktop.org/~hughsient/appdata/
https://fedoraproject.org/wiki/Packaging:AppData

If you wish, I may help prepare it, but as it is meta information like desired description and presentable images it possibly much good idea got it from author.

**Comment by rkhaotix** [comment]
I think you can go on and create that files. Maybe we can create some kind of "contrib" folder in source code root and place all third party contributions there. What do you think?
