### ISSUE TITLE
Model fixing removes newlines from SQL functions.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#624]
I have some models pgModeler refused to load because of problems in the order of the created objects and such. On startup after double clicking such a model, pgModeler presents an error and provides me the chance to fix the model. If I do that, the model gets repaired, because afterwards pgModeler is showing it, but all my newlines I added to make my SQL better to read are gone. It looks like that more than one newline is reduced to only one, which is bad. On every fix I need to restore my newlines. If I just change things and save the file the newlines are preserved.

This is with version 0.8.0.

**Comment by rkhaotix** [comment]
Ok. I'll provide the proper fix to it. Thanks for reporting. Unfortunately
the fix will be kinda useless to you since it is doing undesirable chabges.
:(
Em 04/03/2015 14:08, "tschoening" <notifications@github.com> escreveu:

**Comment by tschoening** [comment]
Don't care, I versioned all my models and already repaired them useing TortoiseDiff if necessary, but I would like to not need to do that for the rest of my life. ;-)
