### ISSUE TITLE
Fixing the object order within an open model produces an endless loop.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#625]
Today I changed one of my models and added a function and a trigger to execute that function, but in the order that I first added the function and the trigger afterwards. On validation of the model pdModeler recognized a wrong order of those objects and allowed me to apply a fix like in older versions. But this time the fix doesn't seem to change anything, but instead it's always printing that the order is wrong and automatically reapplies the fix over and over again, until I finally hit the cancel button. This stops the endless loop, but the problem still persists. If I now save the file and try to open it again, pgModeler refuses to load it. If I open the model in a new instance of pgModeler it tells me about the error again, I can apply a fix and this time the order is corrected and the model opened. Looks like the problem only occures within the instance of pgModeler which I used to change the model.

This is with version 0.8.0.

**Comment by rkhaotix** [comment]
Oops. This is serious!
Could you send me a copy of the model and provide some steps to reproduce
the failure?
Em 04/03/2015 14:12, "tschoening" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
You may try a workaround for this issue until a fix is done.  Just open the
validation widget and hit button "Swap Ids". There you can manually change
the order of conflicting objects.
Em 04/03/2015 14:52, "Raphael Araújo e Silva" <rkhaotix@gmail.com> escreveu:

**Comment by tschoening** [comment]
Sorry, was not able to reproduce this problem with my original or a simplified model: I again created a function, afterwards a trigger, used validation and this time everything went well right from the start. I'll keep an eye open for this...
