### ISSUE TITLE
100% CPU load after validation

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#626]
After each validation of my models I have 100% CPU load on one core pgModeler uses until I close the model and reopen it. This happened in version 0.7.2 and still does in 0.8.0 and it happens all the time even with very basic models only containing one table.

http://www.xup.in/dl,11560593/test.dbm/

If it matters: The OS is Win 8.1 64 Bit with a Quad Core CPU and Hyperthreading enabled. It looks to me as if there's some kind of timing issue, because it looks like events to automatically save a model and such are fired too early as well on 100% CPU load after validation. If I e.g. validate first, then change somethign because I don't think of the high CPU load problem and open a table to edit it, after I close the dialog the model get automatically saved right away and that for every table I change etc. Without the high load and without validation this doesn't happen.

**Comment by rkhaotix** [comment]
I have a suspect. There must be some thread still living even after the
validation ends.
Em 05/03/2015 06:32, "tschoening" <notifications@github.com> escreveu:
