### ISSUE TITLE
Impossible to import correctly table or view with geometry

### ISSUE THREAD

**Issue by Barahir44** [pgmodeler/pgmodeler#627]
Hi

We have some postgis database. When we try to import one of these database, we have a table without geometry column and we have an error message like this:

[7] src/databasemodel.cpp (3733)
  PgSQLType DatabaseModel::createPgSQLType()
    [ERR_REF_INEXIST_USER_TYPE] Référence à un type de donné défini par l'utilisateur qui n'existe pas dans le modèle!

[6] src/databasemodel.cpp (3507)
  Function* DatabaseModel::createFunction()
    [ERR_REF_INEXIST_USER_TYPE] Référence à un type de donné défini par l'utilisateur qui n'existe pas dans le modèle!

[5] src/databasemodel.cpp (3566)
  Function* DatabaseModel::createFunction()
    [ERR_ASG_OBJ_INV_DEFINITION] The object `public.box2d' (Fonction) has inconsistent SQL or XML definition!
       ** <function name="box2d"
		window-func="false"
		leakproof="true"
		returns-setof="false"
		behavior-type="STRICT"
		function-type="IMMUTABLE"
		security-type="SECURITY INVOKER"
		execution-cost="1"
		row-amount="0">
	<schema name="public"/>
	<role name="postgres"/>
	<comment><![CDATA[args: geomA - Returns a BOX2D representing the maximum extents of the geometry.]]></comment>
	<language name="c"/>
	<return-type>
	<type name="public.box2d"/>
	</return-type>
	<parameter name="_param1">
		<type name="geometry"/>
	</parameter>
	<definition library="$libdir/postgis-1.5" symbol="LWGEOM_to_BOX2DFLOAT4"/>
</function>

When we try to import the public schema where these postgis type are, the import process stop on schema and pgmodeler blocks..

If you want, i can send you a backup of one database.

**Comment by rkhaotix** [comment]
The database dump will help to find the problem. But I'll be able to check
it in a week because I'm out on a vacation.

Thanks.
Em 06/03/2015 05:45, "Barahir44" <notifications@github.com> escreveu:

**Comment by Barahir44** [comment]
you can download it here:
http://dl.free.fr/gLmXqoLVV

**Comment by rkhaotix** [comment]
@Barahir44 

I'd take a look into your dump file and noted that you are using postgis 1.5. PgModeler supports only 2.x. Also, I tested the export and import processes with postgis datatypes (2.x) and all worked fine.

I can only conclude that the problem is with your postgis 1.5. If you upgrade it to 2 I think it may work.
