### ISSUE TITLE
Not able to add a new connection through the GUI. (windows 7 64)

### ISSUE THREAD

**Issue by diordonez** [pgmodeler/pgmodeler#628]
When I add a new DB connection using the GUI and then click apply, the application always becomes unresponsive and eventually crashes.

The only way I have to add a new DB connection is manually editing the file;

C:\Program Files (x86)\pgmodeler\conf\connections.conf

**Comment by rkhaotix** [comment]
Which version?
Em 06/03/2015 15:57, "diordonez" <notifications@github.com> escreveu:

**Comment by diordonez** [comment]
![pg_modeler](https://cloud.githubusercontent.com/assets/11354804/6535901/f066db0e-c405-11e4-9ce3-5e0cf2429292.png)

**Comment by rkhaotix** [comment]
Ok. I'll look at this issue as soon as possible
Em 06/03/2015 17:37, "diordonez" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
Can't reproduce the problem. Could you please add more details on how to raise the crash?

**Comment by diordonez** [comment]
Hi Raphael, thanks for your reply.

it seems that it was a permission problem when trying to edit the configuration file.

I did execute the application with "Run as Administrator" and now it is working properly, the issue has disappeared.

Regards.

Diego.
