### ISSUE TITLE
Syntax error trying to create index

### ISSUE THREAD

**Issue by masimao** [pgmodeler/pgmodeler#629]
Hi,

I am trying to create an index, it should use the expression `EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data)`.

pgModeler is generating this code:

```sql

CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
	USING btree
	(
	  (EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data)) ASC NULLS LAST
	);
```

When i use it, i receive this error:

>ERROR:  syntax error at or near ","
>LINE 4:       (EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data)) AS...
>                                       ^
>
>No bloco:
>
>CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
>    USING btree
>    (
>      (EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data)) ASC NULLS LAST
>    );

If i change manually the SQL to:

```sql

CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
	USING btree
	  (EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data));
```
Or:

```sql

CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
	  (EXTRACT(MONTH FROM data), EXTRACT(YEAR FROM data));

```
The index is created normally. Is there a way to force pgModeler to generate one of these syntaxes?

Thanks!

**Comment by rkhaotix** [comment]
No, there is no way to force the creation of the mentioned syntax. I need
to fix the index.sch file in order to generate the correct one.
Em 06/03/2015 17:47, "Márcio Simão" <notifications@github.com> escreveu:

**Comment by masimao** [comment]
Thanks for your attention! Please update this ticket when you do this change.

**Comment by rkhaotix** [comment]
No problem. As soon as possible I'll start to work on this issue.
Em 07/03/2015 18:27, "Márcio Simão" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
@masimao You are using both expression in the same element? If so, you must split them in two different elements. The resulting index SQL should be:

```sql
...
USING btree
(
  (EXTRACT(MONTH FROM data)),
  (EXTRACT(YEAR FROM data))
);
```

The comma is used to separate index elements this is why the error is happening, you are using the comma in a place not accepted. pgModeler automatically separates elements by comma so the user don't need to do this task.

**Comment by masimao** [comment]
@rkhaotix I updated the index creation, so i got:

```sql

CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
	USING btree
	(
	  ((EXTRACT(MONTH FROM data)),
  (EXTRACT(YEAR FROM data)))
	);

```

But i am getting this error:

> Erro de SQL:
> 
> ERROR:  syntax error at or near ","
> LINE 4:    ((EXTRACT(MONTH FROM data)),
>                                       ^
> 
> No bloco:
> 
> CREATE UNIQUE INDEX indice_igpm_data_idx_key_year_month ON public.indice_igpm
> 	USING btree
> 	(
> 	  ((EXTRACT(MONTH FROM data)),
>   (EXTRACT(YEAR FROM data)))
> 	);

**Comment by rkhaotix** [comment]
This does not makes sense... Which version you are using?

See the result I got with 0.8.1-alpha (in development  but the same codebase as 0.8.0)

```sql
CREATE INDEX idx_test ON public.table_b
	USING btree
	(
	  ((EXTRACT(MONTH FROM data))),
	  ((EXTRACT(YEAR FROM data)))
	);
```
The above code works like a charm. See the elements of the index I created.
![idx](https://cloud.githubusercontent.com/assets/2205476/6668118/5113f8b2-cbcf-11e4-878a-79c8da7f5d30.png)

**Comment by masimao** [comment]
I am using pgModeler 0.8.0. Maybe this behavior is because i am using PostgreSQL 8.4.20. Do you know if this version support this syntax?

**Comment by rkhaotix** [comment]
PostgreSQL 8.4 or below is not supported by pgModeler. I think this is the
problem :)
Em 16/03/2015 15:43, "Márcio Simão" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
The syntax generated is for 9.x
Em 16/03/2015 15:45, "Raphael Araújo e Silva" <rkhaotix@gmail.com> escreveu:

**Comment by masimao** [comment]
So we found the "problem". Thanks for your attention!
