### ISSUE TITLE
Disable automatic installation of .desktop file in runtime

### ISSUE THREAD

**Issue by Hubbitus** [pgmodeler/pgmodeler#633]
In comment https://github.com/pgmodeler/pgmodeler/issues/559#issuecomment-77743194 you suggest move it in separate issue:

>User report (https://github.com/Hubbitus/Fedora-packaging/issues/1) what two desktop files installed. First I install in RPM package (pgmodeler.desktop), second (pGmodeler.desktop) you install from https://github.com/pgmodeler/pgmodeler/blob/develop/libpgmodeler_ui/src/generalconfigwidget.cpp at first start. So, on my mind such code should belong to installation, not runtime. How you think? Indeed, you first need to install desktop file to allow user easy start it, but not force first time start for example from command line. I think for Debian it will be also preferred is not?

Honestly I did not properly understand how you check what that Mime is not yet installed. Call to updateFileAssociation from https://github.com/pgmodeler/pgmodeler/blob/c3e982b1aecf80676d52743ffac8f5e4fc909c3d/libpgmodeler_ui/src/mainwindow.cpp#L474, but just by timer, without any check.

I hope (test) I install all needed Mime from package, but on run pgmodeler ask me "It seems that .dbm files aren't associated with pgModeler. Do you want to do it now?"

If it unconditional, could you please add compilation key to disable such functionality?

**Comment by rkhaotix** [comment]
Check the GeneralConfigWidget::updateFileAssociation there some checkings
are made in order to properly configure the mime database.

I'm planning to move the whole code to CLI without automatic execution. So
I can run that command from my installer.
Em 09/03/2015 11:52, "Pavel Alexeev aka Pahan-Hubbitus" <
notifications@github.com> escreveu:

**Comment by Hubbitus** [comment]
Oh, yes. I missed it. Such checks failed for me because of different name "pgmodeler" and "pgModeler".

Run explicitly by some switch? Please note what such installation is not deleted with package, so leaved as garbage. If it common way for Windows we prefer to do not such thinks in distributions.

**Comment by rkhaotix** [comment]
The idea here is create an option in pgmodeler-cli that permits user to
install / remove file association in Linux and Windows (Mac OSX not
supported yet).

Let me clarify, I provide installers to both Windows and Linux and I will
optionally use the CLI to install or update association. For package
maintainers they will use their own way to associate dbm files, they'll not
be obligated to use the same command as I use.

So the option in CLI is the better less invasive approach, in my point of
view.
Em 09/03/2015 12:49, "Pavel Alexeev aka Pahan-Hubbitus" <
notifications@github.com> escreveu:

**Comment by Hubbitus** [comment]
I think option is the good choice. If it will also honor INSTALL_ROOT (introduced in https://github.com/pgmodeler/pgmodeler/issues/559) I also may use it in my package to do not repeat you work!

**Comment by rkhaotix** [comment]
Ok then. I'll include this issue in the set of the ones scheduled to 0.8.1
Em 09/03/2015 13:17, "Pavel Alexeev aka Pahan-Hubbitus" <
notifications@github.com> escreveu:

**Comment by Hubbitus** [comment]
Thank you very much.

**Comment by Hubbitus** [comment]
I do not see in commit 41f9fd312 remove runtime installation from main binary, only add into pgomodelercli.

**Comment by rkhaotix** [comment]
See this commit 4024c3f2eb51c08016d4f08d77f382478c031542

**Comment by Hubbitus** [comment]
Thank you.
