### ISSUE TITLE
demo problem [solved]

### ISSUE THREAD

**Issue by valq7711** [pgmodeler/pgmodeler#634]
Hi guys!
I try to view demo on win7/32, but it's something wrong:
"The procedure entry point PQfformat could not be located in the dynamic link library LIBPQ.dll"
8$ - not problem, but I want to be sure that i'll get pgmodeler, but not black hole

**Comment by rkhaotix** [comment]
Check this issue:

[pgmodeler] DLL entry point __gxx_personality_v0 not found. (#621)

The reason may be the same
Em 09/03/2015 15:15, "valq7711" <notifications@github.com> escreveu:

**Comment by valq7711** [comment]
I found some various versions of libpq.dll on my PC:
![libpq](https://cloud.githubusercontent.com/assets/11394363/6562172/d80792c0-c6a7-11e4-9925-989b5ef61f94.jpg)

I've replaced libpq.dll in System32 with one from pgmodeler... and it works now!

**Comment by rkhaotix** [comment]
I've fixed this issue by reverting to the old folder structure presenting on 0.8.0-beta and below.
