### ISSUE TITLE
error opening 0.7.2 model - fix will remove indexes

### ISSUE THREAD

**Issue by Grunge** [pgmodeler/pgmodeler#635]
I have a model created in 0.7.2 and try to update to pgmodeler 0.8.0.
When i import the model I have *Errors.
When i try to fix it, all Indexes on the tables getting removed.

*Errors

7] src/xmlparser.cpp (198)
  void XMLParser::readBuffer()
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Element table content does not follow the DTD, expecting (schema , role? , tablespace? , comment? , tag? , appended-sql? , prepended-sql? , position , column* , constraint* , customidxs*), got (schema appended-sql position column column constraint constraint index) . 

[6] src/xmlparser.cpp (122)
  void XMLParser::loadXMLBuffer(const QString&)
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Element table content does not follow the DTD, expecting (schema , role? , tablespace? , comment? , tag? , appended-sql? , prepended-sql? , position , column* , constraint* , customidxs*), got (schema appended-sql position column column constraint constraint index) . 

[5] src/xmlparser.cpp (91)
  void XMLParser::loadXMLFile(const QString&)
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Element table content does not follow the DTD, expecting (schema , role? , tablespace? , comment? , tag? , appended-sql? , prepended-sql? , position , column* , constraint* , customidxs*), got (schema appended-sql position column column constraint constraint index) . 

[4] src/databasemodel.cpp (2956)
  void DatabaseModel::loadModel(const QString&)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file D:/all_projects/all_non_web/eduDB/DatabaseModel/DB_Model_intern.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[3] src/modelwidget.cpp (1108)
  void ModelWidget::loadModel(const QString&)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file D:/all_projects/all_non_web/eduDB/DatabaseModel/DB_Model_intern.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[2] src/mainwindow.cpp (805)
  void MainWindow::addModel(const QString&)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file D:/all_projects/all_non_web/eduDB/DatabaseModel/DB_Model_intern.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[1] src/mainwindow.cpp (824)
  void MainWindow::addModel(const QString&)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file D:/all_projects/all_non_web/eduDB/DatabaseModel/DB_Model_intern.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[0] src/mainwindow.cpp (1473)
  void MainWindow::loadModels(const QStringList&)
    [ERR_MODEL_FILE_NOT_LOADED] Could not load the database model file `D:/all_projects/all_non_web/eduDB/DatabaseModel/DB_Model_intern.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

**Comment by rkhaotix** [comment]
There where some important changes on the structure of files created by
pgModeler. In 0.8.0 the indexes are created outside <table > tags and due
to a bug discovered after the release of 0.8.0 the fix process can't move
the indexes. The workaround is open the file on a text editor and move tags
<index> to outside the related tables.

A patch release is being prepared an soon these problems will be fixed.
Em 10/03/2015 10:34, "Grunge" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
This is fixed on the next release (0.8.1).
