### ISSUE TITLE
pgmodeler.exe - Ponto de entrada não encontrado(versao 0.8.0) 

### ISSUE THREAD

**Issue by tedeski** [pgmodeler/pgmodeler#638]
---------------------------
pgmodeler.exe - Ponto de entrada não encontrado
---------------------------
Não foi possível localizar o ponto de entrada do procedimento _ZN10Messagebox4showE9ExceptionRK7QStringjjS3_S3_S3_S3_S3_S3_ na biblioteca de vínculo dinâmico C:\Program Files (x86)\pgmodeler\pgmodeler.exe. 
---------------------------
OK   
---------------------------

**Comment by rkhaotix** [comment]
Dê uma olhada nessa discussão

[pgmodeler] DLL entry point __gxx_personality_v0 not found. (#621)
Em 13/03/2015 11:28, "tedeski" <notifications@github.com> escreveu:
