### ISSUE TITLE
Is it possible to generate SQL for a specific schema?

### ISSUE THREAD

**Issue by masimao** [pgmodeler/pgmodeler#639]
Hi,

I have some schemas in my model, is it possible to generate the SQL code for a specific schema?

Thanks!

**Comment by rkhaotix** [comment]
Do you mean the code of the entire schema including children objects? If so.. there is no way to do that. But I'll register this feature for future releases.

**Comment by masimao** [comment]
Yes, the entire schema code, including children objects.

Thanks to register this feature, it will be nice!
