### ISSUE TITLE
crash 0.8.0 on 10.10.2

### ISSUE THREAD

**Issue by prtome** [pgmodeler/pgmodeler#640]
continuous crashes, every 2 or 3 minutes, even when I am not doing anything. 
I see this in my logs very often 
18/03/2015 11:10:30,000 kernel[0]: Sandbox: pgmodeler(867) System Policy: deny file-write-unlink /Users/me/Library/Saved Application State/br.com.pgmodeler.pgModeler.savedState/restorecount.plist
18/03/2015 11:10:33,588 pgmodeler[867]: assertion failed: 14C1510: libxpc.dylib + 97940 [876216DC-D5D3-381E-8AF9-49AE464E5107]: 0x89

and when it crashes
18/03/2015 11:21:34,721 com.apple.xpc.launchd[1]: (br.com.pgmodeler.pgModeler.192584[867]) Service exited with abnormal code: 1

thanks

**Comment by prtome** [comment]
another point. Every time it crashes, I have an error in the console that say
spindump: Got xpc error message in libspindump client connection: Connection invalid

**Comment by rkhaotix** [comment]
It seems a permission issue... pgModeler is tested in 10.9 and runs quite well without minor crashes not related to the error you've mantioned.

I've found this link:
https://discussions.apple.com/thread/3210994

A lot of users are having this problem with different applications. The main reason is due to an system upgrade. But there are other causes... No solution found yet.

**Comment by prtome** [comment]
thanks, will check that. I moved to a newer Mac (with the  hope my old imac was full of garbage that was causing it) and I have a crash to. So I will investigate following that link.

**Comment by rkhaotix** [comment]
Ok. I'll try to run pgModeler on a Yosemite and see what happens.

**Comment by prtome** [comment]
thanks 
spindump crash is what prevents to have  a crash report. But has nothing to do with the crash itself.
If you can try with Yosemite and debugging it will be helpful.
The application crashes even when not doing anything, so it looks like some own background job is having problem.
Thanks.
