### ISSUE TITLE
[QUESTION] Validation error with "ERROR:  collations are not supported by type bigint".

### ISSUE THREAD

**Issue by shuLhan** [pgmodeler/pgmodeler#642]
When running validation, I get this message:

> Could not execute the SQL command.
> Message returned: `ERROR:  collations are not supported by type bigint
> '

Anyone know how to fix this? I've tried searching but did not found a solution.

Thank you in advance, and big thank you for the software. I really love it.

**Comment by shuLhan** [comment]
I found the problem. I have a table with field "id bigint" with collation is "default", while the index in the table is using btree on "id" with collation also set to "default".

To fix the problem I remove both collation in the field and in index.

Sorry for inconveniance.

**Comment by sylfree9999** [comment]
Hi @shuLhan 

I've bumped into the same situation.
But I do not know how to see the existed collation of a materialized view.
Can you please help?

**Comment by shuLhan** [comment]
@sylfree9999 ,

> But I do not know how to see the existed collation of a materialized view.

I forgot how to do that too, but quick search [1] point to this link [2]. AFAIK, collation only can be viewed through SQL not from GUI.

[1] https://www.google.com/search?q=postgresql+view+collation&ie=utf-8&oe=utf-8&client=firefox-b-ab
[2] https://dba.stackexchange.com/questions/29943/how-to-determine-the-collation-of-a-table-in-postgresql
