### ISSUE TITLE
User config file

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#643]
Claims that default conf deosnt exists as  ~/.config/pgmodeler/ui-style.conf but create them in /.config/pgmodeler/conf/ui-style.conf.
Once copied, software claims that config files are corrupted.

**Comment by rkhaotix** [comment]
Hi Damien! It is a long time! :)

If you're using master branch or 0.8.0 tag there's a bug on the build
process related to custom variables. Try to use 0.8.1-alpha, this bug was
fixed.
Em 21/03/2015 16:27, "Damien Degois" <notifications@github.com> escreveu:

**Comment by babs** [comment]
Hello Raphael,

Yes, a long time :) Hope you're doing well.

Same issue with 0.8.1-alpha :/

**Comment by babs** [comment]
seems to work with 0.8.1 packaged
