### ISSUE TITLE
dbmodel.dtd missing

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#644]
at startup, pgmodeler says: 
I/O error : failed to load external entity "<install dir>/share/pgmodeler/schemas/xml/dtd/dbmodel.dtd"

**Comment by rkhaotix** [comment]
Maybe this issue is related to #643?
Em 21/03/2015 16:28, "Damien Degois" <notifications@github.com> escreveu:

**Comment by babs** [comment]
unable to reproduce on later version
