### ISSUE TITLE
Configuration => new connoction

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#645]
When validating a  new connection, this leads to 100% CPU consumption and the only option is to kill the process

**Comment by rkhaotix** [comment]
By Validating a connection do you mean by test it?
Em 21/03/2015 16:31, "Damien Degois" <notifications@github.com> escreveu:

**Comment by babs** [comment]
yes

**Comment by rkhaotix** [comment]
Hmm... can't reproduce... It works to me. :/
You have additional details?

**Comment by babs** [comment]
Have you tried with a fresh ~/.config/pgmodeler ?

**Comment by babs** [comment]
I have no stack trace, it takes 100% CPU and that's all :/
