### ISSUE TITLE
Tab order in Settings / New connection 

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#646]
Tab make focus jump from Alias to Host instead of goign thru connection DB.
Connection DB is activeted only after cycling the entire fields

**Comment by rkhaotix** [comment]
Thanks,  I'll take a look on that.
Em 21/03/2015 16:33, "Damien Degois" <notifications@github.com> escreveu:

**Comment by babs** [comment]
works on 0.8.1
