### ISSUE TITLE
New connection vaidation

### ISSUE THREAD

**Issue by babs** [pgmodeler/pgmodeler#647]
When trying to add a new connection, it fails with the following error:

Unable to write the file ~/.config/pgmodeler/connections.conf' due to one or more errors in the definition generation process!

**Comment by rkhaotix** [comment]
Also related to #643?
Em 21/03/2015 16:35, "Damien Degois" <notifications@github.com> escreveu:

**Comment by babs** [comment]
Issue still here in 0.8.1-alpha

**Comment by rkhaotix** [comment]
Could you please post the full error stack?

**Comment by babs** [comment]
I'll when I'll have time. I think it's related to the default config files or something.

**Comment by babs** [comment]
works on 0.8.1
