### ISSUE TITLE
QSslSocket: cannot resolve SSLv2_server_method

### ISSUE THREAD

**Issue by matheusssilva** [pgmodeler/pgmodeler#648]
runing application I get this error:

QSslSocket: cannot resolve SSLv2_server_method

**Comment by rkhaotix** [comment]
This is not an error. Just a Qt warning. I'm investigating this already.

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-03-22 11:38 GMT-03:00 Matheus Saraiva da Silva <
notifications@github.com>:
