### ISSUE TITLE
Diff doesn't detect changes in rules

### ISSUE THREAD

**Issue by hdus** [pgmodeler/pgmodeler#650]
I changed a table rule but when I run diff the result says: 
-- No differences were detected between model and database. --

**Comment by rkhaotix** [comment]
@hdus Note that rules can't have their attributes changed via ALTER commands (except for name). For this situation you may force their recreation. In the diff dialog uncheck the "Recreate only unmodifiable objects" and leave "Force recreation of objects" checked.

If this does not solve, please, send me both model and database dump so I can debug the entire process. Thanks.

Reference:
http://www.postgresql.org/docs/9.3/static/sql-alterrule.html

**Comment by hdus** [comment]
Thank's for the hint. It works in priciple, but when I uncheck "Recreate only unmodifiable objects" than all tables will be dropped an recreated. As the result I will loose all my data. That's not what I expect.

**Comment by rkhaotix** [comment]
Since the feature is quite experimental I highly do not recommend to use
the diff in production databases or in development one where the data is
needed because table drops may occur easily. I'll provide a quick patch for
that enabling the diff of rules, indexes and triggers as expected.
Em 24/03/2015 04:20, "hdus" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
@hdus I've made a little change on diff process... Could you please test the code on branch "diff-changes"? See if it works for you.

https://github.com/pgmodeler/pgmodeler/tree/diff-changes

**Comment by hdus** [comment]
It seems to be working now, thank's a lot. But still all views are dropped and recreated. Even though the are not touched.

**Comment by rkhaotix** [comment]
The views are classified the same way as rules... They can be changed by ALTER commands so they must be recreated.

**Comment by hdus** [comment]
OK thank's for clarification.

**Comment by rkhaotix** [comment]
You're welcome. Little by little we'll refining the process... Thanks for test it!

**Comment by hdus** [comment]
Yes step by step. It's a great peace of software. I use it in my PostgreSQL training courses and the people are very happy to use it!

**Comment by rkhaotix** [comment]
Wow! This is GREAT!
I'm talking to a experienced PostgreSQL user / teacher! I'm kinda proud of it. :D
