### ISSUE TITLE
invalid shebang in shell scripts

### ISSUE THREAD

**Issue by pinhead84** [pgmodeler/pgmodeler#652]
The shell scripts `linuxdeploy.sh`, `macdeploy.sh`, `start-pgmodeler.sh` & `windeploy.sh` contain an invalid shebang at the first line. Instead of

```
#/bin/bash
```

you should use

```
#!/bin/bash
```

(note the exclamation mark)

I assume, that in case of an invalid shebang the system uses the users default shell - which is in my case **zsh** instead of **bash**. 

Calling `linuxdeploy.sh` with my default shell (**zsh**) produces errors like:

```
./linuxdeploy.sh: 111: ./linuxdeploy.sh: Bad substitution
./linuxdeploy.sh: 130: ./linuxdeploy.sh: cannot open 5.0.0: No such file
./linuxdeploy.sh: 130: ./linuxdeploy.sh: [[: not found
```

These errors do not occur, when

-  the script is explicitly excuted with **bash** - e.g. `bash linuxdeploy.sh` or
-  the first line of the script is changed to `#!/bin/bash`

**Comment by rkhaotix** [comment]
Thanks. I'll fix that!

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-03-23 19:36 GMT-03:00 Andreas Rudolph <notifications@github.com>:
