### ISSUE TITLE
corrupting model?

### ISSUE THREAD

**Issue by matheusssilva** [pgmodeler/pgmodeler#661]
Is very frequent the "corruption" of model.
When i open a model, I receive a dialog box "FIX". This window create a new file with "fixed" in end name file.

**Comment by rkhaotix** [comment]
Yes if you constantly ignore the validation process and keep working on the model saving it without validate. If that's not the case we have a bug.

**Comment by matheusssilva** [comment]
Because validate model?

**Comment by rkhaotix** [comment]
Are you asking why there is the need to validate the model? If so, please read this:
http://www.pgmodeler.com.br/wiki/doku.php?id=modelvalidation

It's a bit old but the mechanism remains the same.

**Comment by matheusssilva** [comment]
I understand, but this validation could happen just in exportation time.
I created a function and saved unfinished. It invalidated my model.

Can i not save a model with a unfinished object (tables, functions, types,...) ?

**Comment by rkhaotix** [comment]
You can save an incomplete set of objects BUT you have to organize their creation order through the validation in order to save them properly in .dbm file.

**Comment by matheusssilva** [comment]
hummm, ok, thanks
