### ISSUE TITLE
Support for foreign data tables 

### ISSUE THREAD

**Issue by shr3k** [pgmodeler/pgmodeler#664]
Hi, it would be nice to have support for foreign data tables from builtin postgres_fdw and file_fdw stored in pg_foreign_table and show them together in public schema in pgmodeler...

**Comment by rkhaotix** [comment]
Foreign data wrappers (tables and servers) are scheduled to implemented in 0.9.0 see #597

**Comment by shr3k** [comment]
Haven't noticed, thank you... :-)
