### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by uuela** [pgmodeler/pgmodeler#665]
I have installed pgModeler on the following system:
Window 7 64-bit, 8 gig RAM, 500 GB HDDR. 
I am connecting to my Ubuntu 14.0.4 server and postgres 9.4.1.

Issue:
When I open the app get the following notice:
![new issue pgmodeler_pgmodeler](https://cloud.githubusercontent.com/assets/11728501/6909503/bd0bde36-d714-11e4-8d3c-3aabd7679956.png)

The file does not appear to be corrupt however I have to use 'Quick Connect' option to connect to the database. When I try to save the connection for the database I get a notice that the conf file cannot be written to. 

![new issue pgmodeler configuration - connection](https://cloud.githubusercontent.com/assets/11728501/6909622/1a30495c-d716-11e4-87fc-a9807a2d4833.png)

The model displays as only outlines of the object, the data is present, when I click on an object I get a full display of all of the attributes. Just nothing in the map.

![2015-03-30 19_52_21-pgmodeler - model map example](https://cloud.githubusercontent.com/assets/11728501/6909637/64513e60-d716-11e4-9991-e1d9b775f57f.png)

Is this due to the postgres version being 9.4.1? I can live with the situation but it makes an otherwise simple task a bit tedious.
Regards

**Comment by rkhaotix** [comment]
No. This is not due to your PostgreSQL version.
It should be some issue related to permissions. Could you please post the entire error stack?

**Comment by uuela** [comment]
Here are the two error stack images in order of the dialogs in the original message:
![configuration files issue 665 opening error stack](https://cloud.githubusercontent.com/assets/11728501/6929886/81f10d2c-d7cc-11e4-8fcd-a1eaee8c0d77.png)
 Connection:
![configuration files - issue 665 - db connection save failure](https://cloud.githubusercontent.com/assets/11728501/6929895/8d44234e-d7cc-11e4-984b-e6dd7edface3.png)

**Comment by rkhaotix** [comment]
I mean the textual form of stack. Click in the button which icon is a text doc to convert the errors to text and post here.

Also, did you purchased a binary copy or compiled pgModeler?

**Comment by uuela** [comment]
Stack from first Dialog:
[5] src/xmlparser.cpp (198)
  void XMLParser::readBuffer()
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Value "" for attribute type of patterns is not among the enumerated set . 

[4] src/xmlparser.cpp (122)
  void XMLParser::loadXMLBuffer(const QString&)
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Value "" for attribute type of patterns is not among the enumerated set . 

[3] src/xmlparser.cpp (91)
  void XMLParser::loadXMLFile(const QString&)
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Value "" for attribute type of patterns is not among the enumerated set . 

[2] src/baseconfigwidget.cpp (181)
  void BaseConfigWidget::loadConfiguration(const QString&, std::map<QString, std::map<QString, QString> >&, const std::vector<QString>&)
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Value "" for attribute type of patterns is not among the enumerated set . 

[1] src/relationshipconfigwidget.cpp (116)
  virtual void RelationshipConfigWidget::loadConfiguration()
    [ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Value "" for attribute type of patterns is not among the enumerated set . 

[0] src/configurationform.cpp (109)
  void ConfigurationForm::loadConfiguration()
    [ERR_CONFIG_NOT_LOADED] Unable to load one or more configuration files! Please check if files exists in the configuration folder and if they are not corrupted to preventing this error to occur again on the next startup!

Stack from second:
[3] src/schemaparser.cpp (1083)
  QString SchemaParser::getCodeDefinition(attribs_map&)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `alias' in file C:/Program Files (x86)/pgmodeler/conf/schemas/connections.sch, line 17, column 34!

[2] src/schemaparser.cpp (1408)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `alias' in file C:/Program Files (x86)/pgmodeler/conf/schemas/connections.sch, line 17, column 34!

[1] src/baseconfigwidget.cpp (97)
  void BaseConfigWidget::saveConfiguration(const QString&, std::map<QString, std::map<QString, QString> >&)
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `C:/Program Files (x86)/pgmodeler/conf/connections.conf'' due to one or more errors in the definition generation process!

[0] src/connectionsconfigwidget.cpp (470)
  virtual void ConnectionsConfigWidget::saveConfiguration()
    [ERR_FILE_NOT_WRITTER_INV_DEF] Unable to write the file `C:/Program Files (x86)/pgmodeler/conf/connections.conf'' due to one or more errors in the definition generation process!

I purchased a compiled version

**Comment by rkhaotix** [comment]
I suspect that this is a permission issue. Hsve you tried to run as
administrator? Install in another location?
Em 02/04/2015 20:05, "uuela" <notifications@github.com> escreveu:

**Comment by KLITFE** [comment]
@rkhaotix 
Hi  i am facing the same  above  described issue. Is there any fix for it. I had  uninstalled v0.8.0-alpha1
and installed v08.2 full version and that is when the issue started happening. Tried installing and uninstalling multiple times. the download is working fine in every other system where they had no prior versions of pgmodeler.

@ uuela  Were you able to find a fix for it?
