### ISSUE TITLE
Change table color

### ISSUE THREAD

**Issue by masimao** [pgmodeler/pgmodeler#666]
Hi,

I would like to know if in version 0.8 is possible to define colors to table headers, like the image below, i got it from pgModeler options. As i have various schemas, the use of rectangles isn't good.

![coresschemas](https://cloud.githubusercontent.com/assets/3603345/6920061/8061e8a8-d792-11e4-9410-ea54d5f6a52f.png)

Regards,

Márcio Simão

**Comment by rkhaotix** [comment]
@masimao Use tag objects, they was implemented exactly for this purpose.
