### ISSUE TITLE
diff error

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#668]
[7] src/schemaparser.cpp (1120)
  QString SchemaParser::getCodeDefinition(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `operator' with an undefined value in file C:/Program Files/pgmodeler/schemas/xml/excelement.sch, line 29, column 23!

[6] src/schemaparser.cpp (1408)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `operator' with an undefined value in file C:/Program Files/pgmodeler/schemas/xml/excelement.sch, line 29, column 23!

[5] src/schemaparser.cpp (887)
  QString SchemaParser::getCodeDefinition(const QString&, attribs_map&, unsigned int)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `operator' with an undefined value in file C:/Program Files/pgmodeler/schemas/xml/excelement.sch, line 29, column 23!

[4] src/databaseimporthelper.cpp (1791)
  void DatabaseImportHelper::createConstraint(attribs_map&)
    [ERR_UNDEF_ATTRIB_VALUE] Attribute `operator' with an undefined value in file C:/Program Files/pgmodeler/schemas/xml/excelement.sch, line 29, column 23!
       *\* <constraint name="pk_t_telparams" type="pk-constr" table="main.t_telparams">
    <columns names="prm_id" ref-type="src-columns"/>
</constraint>

[3] src/databaseimporthelper.cpp (683)
  void DatabaseImportHelper::createObject(attribs_map&)
    [ERR_OBJECT_NOT_IMPORTED] The object `t_telparams_tel_id_tp_prm_range_excl' (Constraint) could not be imported due to one or more errors! Check the exception stack for more details.

[2] src/databaseimporthelper.cpp (412)
  void DatabaseImportHelper::createConstraints()
    [ERR_OBJECT_NOT_IMPORTED] The object `t_telparams_tel_id_tp_prm_range_excl' (Constraint) could not be imported due to one or more errors! Check the exception stack for more details.

[1] src/databaseimporthelper.cpp (596)
  void DatabaseImportHelper::importDatabase()
    [ERR_OBJECT_NOT_IMPORTED] The object `t_telparams_tel_id_tp_prm_range_excl' (Constraint) could not be imported due to one or more errors! Check the exception stack for more details.

[0] src/modeldatabasediffform.cpp (516)
  void ModelDatabaseDiffForm::captureThreadError(Exception)
    [ERR_OBJECT_NOT_IMPORTED] The object `t_telparams_tel_id_tp_prm_range_excl' (Constraint) could not be imported due to one or more errors! Check the exception stack for more details.

Source code of t_telparams_tel_id_tp_prm_range_excl in database:

CONSTRAINT t_telparams_tel_id_tp_prm_range_excl EXCLUDE
  USING gist (tel_id WITH =, tp WITH =, prm_range WITH &&);

**Comment by rkhaotix** [comment]
It's quite complicated to post only the stack of errors without a sample
model or database dump to analyze!

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-04-01 9:52 GMT-03:00 Takhir <notifications@github.com>:

**Comment by fte1965** [comment]
dump of my database has a size about 150 GB, and then I have exactly what sql statement pgmodeler  does not understand:
CONSTRAINT t_telparams_tel_id_tp_prm_range_excl EXCLUDE
USING gist (tel_id WITH =, tp WITH =, prm_range WITH &&);

You can use this simple test...

CREATE EXTENSION btree_gist
  SCHEMA public
  VERSION "1.0";

create table error_test (
     tel_id integer,tp integer,prm_range tsrange);
alter table error_test
add
CONSTRAINT t_telparams_tel_id_tp_prm_range_excl EXCLUDE
USING gist (tel_id WITH =, tp WITH =, prm_range WITH &&);

**Comment by rkhaotix** [comment]
The problem is that the operators used by the exclude constraint are system
objects so you need to check "Import system objects " option.

Also, found a bug on operator name validation and already fixed it. So, if
you're able to compile pgModeler use the branch "develop"
Em 03/04/2015 02:08, "Takhir" <notifications@github.com> escreveu:

**Comment by fte1965** [comment]
The problem not solved I send bug report with model to
bug@pgmodeler.com.br

**Comment by rkhaotix** [comment]
According to your small sample the error gone unless there are additional
errors...
Also, there is no model in the email.
Em 04/04/2015 06:04, "Takhir" <notifications@github.com> escreveu:

**Comment by fte1965** [comment]
I send my model to
bug@pgmodeler.com.br
