### ISSUE TITLE
[0.8.1-alpha] Problem with stability

### ISSUE THREAD

**Issue by replay111** [pgmodeler/pgmodeler#673]
Hi,

I Have compiled by myself version 0.8.1-aplha on osx.
I have enormous problems with stability. Especialy when I am trying to add some constraints (FK, PK) through table properties pgModeler just disapear... It stops without any message box - just like has been killed by kill command :/

Have You got any idea why? :-)

Is it possible to check some application logs?

**Comment by rkhaotix** [comment]
Well by definition alpha and beta releases are unstable. But I 'm having more issues in MacOSX...  There's no log generated by the app only a stack trace when the crash handler is triggered. 

Currently I build and test pgModeler in 10.9.2 without much problems. There's some crashes here and there but not related to add tables.

**Comment by replay111** [comment]
Hm.. I am aware that alpha and beta can crash... but so often... is really anoying ;).
I am not given any stack trace or window with information what went wrong.
I works on the newest Yosemite (propably from yesterday, or 2 days before), maybe this is a problem.
I have also unchekced debug "mode" in QT Creater because with this option enabled I was not able to compile application... maybe should I turned it on?

I will try to build pgModeler on windows today to check how it works on it.

And finally - this apps RULEZ ;-) I found it very usefull, so that's why I am asking about stability ;-)

Thanx for fast reply ;-)))

**Comment by rkhaotix** [comment]
It is known that pgModeler can crash on Yosemite when running on some kind of sandbox mode. Other user reported that. 

I am glad to see you are interested in pgModeler!  Thanks

**Comment by rkhaotix** [comment]
Check here
https://github.com/pgmodeler/pgmodeler/issues/640

**Comment by replay111** [comment]
Thanx,
It looks like Yosemite sucks... not the first time unfortunately...

No I am compiling on Windows if it will be more stable then on OSX, I will stay for a while with windows.

**Comment by rkhaotix** [comment]
My major problem is that I do not own a iMac or Macbook to do the proper
tests because these machines are very expensive here in my country :(
Em 12/04/2015 08:21, "replay111" <notifications@github.com> escreveu:

**Comment by replay111** [comment]
I dont onw eaither... because of price... I have one because I was given it from work to;-) So I really understand You;-))) But You did great work with that app!!!

**Comment by replay111** [comment]
OK so far for windows works without any problems :D

**Comment by rkhaotix** [comment]
The windows and Linux versions are the most stable. Special highlight for
performance on Linux, the best of all! :)
Em 12/04/2015 08:47, "replay111" <notifications@github.com> escreveu:

**Comment by replay111** [comment]
I will have to check it, but later. I am not keen on C language and I don't know C IDE including QT ;-) So I don't know how to install (QT) and compile (pgModeler)... yet ;-)))) But I will figure it out ;-)

**Comment by replay111** [comment]
I have to figure out how to include all required qt libs :D On other windows pc it says that lacks some dll's :-)
