### ISSUE TITLE
Sugestion for function editor

### ISSUE THREAD

**Issue by matheusssilva** [pgmodeler/pgmodeler#675]
Would be nice to have a syntax validation in function editor, as there is in pgAdmin.

**Comment by rkhaotix** [comment]
Currently the model validation covers the function syntax validation since
it creates all the objects in the database to check their SQL syntax.
Em 17/04/2015 18:39, "Matheus Saraiva da Silva" <notifications@github.com>
escreveu:

**Comment by matheusssilva** [comment]
When i try make the validation, I get the message:

new collation (pt_BR.UTF8) is incompatible with the collation of the template database (pt_BR.UTF-8)
HINT:  Use the same collation as in the template database, or use template0 as template.

May database is defined with the collation pt_BR.UTF-8. There isn't the 'pt_BR.UTF8' option. There's 'pt_BR.UTF-8', even with template0.
My system is postgresql 9.3 on ubuntu 14.04

**Comment by rkhaotix** [comment]
See this
https://github.com/pgmodeler/pgmodeler/issues/498
Em 18/04/2015 08:59, "Matheus Saraiva da Silva" <notifications@github.com>
escreveu:
