### ISSUE TITLE
Two 1-n relation to a single table

### ISSUE THREAD

**Issue by ChipsetX86** [pgmodeler/pgmodeler#676]
Error ERR_DUPLIC_RELATIONSHIP prohibits create two links with the same tables, but it is not very convenient. (You can use many to many, but it leads to unnecessary tables). For example a person may have two surnames (up to marry and after)

**Comment by rkhaotix** [comment]
You can solve that by manually creating the fks. The disadvantages of that
approach is that the column propagation will not work. Currently,  it is
too difficult to enable multiple relationships for the same table pair.
Em 20/04/2015 17:11, "ChipsetX86" <notifications@github.com> escreveu:

**Comment by ChipsetX86** [comment]
Ok! Thanks! 
I temporarily disabled the call throw Exception(msg,ERR_DUPLIC_RELATIONSHIP,__PRETTY_FUNCTION__,__FILE__,__LINE__);
I do not see any problems in the work program

**Comment by rkhaotix** [comment]
Disabling the exception throwing will lead to undefined behavior. You may
generate a corrupted model or even crash the application often. But if you
know what you're doing.. :)
Em 21/04/2015 10:06, "ChipsetX86" <notifications@github.com> escreveu:

**Comment by ChipsetX86** [comment]
Only works can not edit the previous relationship. 
But it would be a normal solution.
