### ISSUE TITLE
pgmodeler 0.8.1-alpha1 can not open model

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#678]
pgmodeler 0.8.1-alpha1 can not open model, but 0.8.1-alpha open it without problem

Below is a log and model:

[7] src/databasemodel.cpp (6025)
  Permission *DatabaseModel::createPermission()
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!

[6] src/databasemodel.cpp (6109)
  Permission *DatabaseModel::createPermission()
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!
       ** /Users/fte/Documents/ncsat/all/test.dbm (line: 68)

[5] src/databasemodel.cpp (2899)
  void DatabaseModel::loadModel(const QString &)
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!
       ** /Users/fte/Documents/ncsat/all/test.dbm (line: 68)

[4] src/databasemodel.cpp (2959)
  void DatabaseModel::loadModel(const QString &)
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!
       ** /Users/fte/Documents/ncsat/all/test.dbm (line: 68)

[3] src/modelwidget.cpp (1114)
  void ModelWidget::loadModel(const QString &)
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!

[2] src/mainwindow.cpp (811)
  void MainWindow::addModel(const QString &)
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!

[1] src/mainwindow.cpp (830)
  void MainWindow::addModel(const QString &)
    [ERR_PERM_REF_INEXIST_OBJECT] A permission is referencing the object `public.tle_alltodate(IN timestamp,OUT text)' (Function) which was not found in the model!

[0] src/mainwindow.cpp (1467)
  void MainWindow::loadModels(const QStringList &)
    [ERR_MODEL_FILE_NOT_LOADED] Could not load the database model file `/Users/fte/Documents/ncsat/all/test.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

I am create small test model 

<?xml version="1.0" encoding="UTF-8"?>

<dbmodel pgmodeler-ver="0.8.1-alpha" last-position="0,0" last-zoom="1"
	 default-owner="postgres">
<role name="__ncsat_users__"
      inherit="true"
      connlimit="0"
      sql-disabled="true">
	<comment><![CDATA[Роль по умолчанию для пользователей]]></comment>
</role>

<role name="__ncsat_internal__"
      inherit="true"
      sql-disabled="true">
	<comment><![CDATA[роль для внутренних процессов]]></comment>
</role>

<database name="ncsat-d" encoding="UTF8" lc-collate="ru_RU" lc-ctype="ru_RU">
</database>
<schema name="public" protected="true" rect-visible="true" fill-color="#e1e1e1" sql-disabled="true">
</schema>

<function name="tle_alltodate"
		window-func="false"
		returns-setof="true"
		behavior-type="RETURNS NULL ON NULL INPUT"
		function-type="STABLE"
		security-type="SECURITY INVOKER"
		execution-cost="1000"
		row-amount="60000">
	<schema name="public"/>
	<comment><![CDATA[Каталог TLE на дату в трехстрочном формате]]></comment>
	<language name="plpgsql" protected="true" sql-disabled="true"/>
	<return-type>
	<type name="text"/>
	</return-type>
	<parameter name="dt" in="true" default-value="current_timestamp">
		<type name="timestamp"/>
	</parameter>
	<parameter name="tle_str" out="true">
		<type name="text"/>
	</parameter>
	<definition><![CDATA[begin
    return query(
        select unnest(c1)::text -- разворачиваем из массива построчнно
        from (
            select array[coalesce(s.satname,'NOT DEFINED'),t.tline1,t.tline2] as c1 -- сворачиваем в массив
            from
            (   -- последние обновления за месяц до момента $1 в utc
                select distinct on(norad_cat_id) norad_cat_id,tline1,tline2
                from   v_tle
                where  ttm < to_ttm(dt) and ttm >= to_ttm(dt - interval '1 month')
                order by norad_cat_id,ttm desc,element_set_no desc
            ) as t left join v_satcat s on (s.norad_cat_id = t.norad_cat_id)
            where coalesce(s.decay,'infinity'::timestamp) > dt
            order by t.norad_cat_id
        ) t3
    );
end;
]]></definition>
</function>

<permission revoke="true">
	<object name="public.tle_alltodate(IN timestamp,OUT text)" type="function"/>
	<privileges execute="true"/>
</permission>
<permission>
	<object name="public.tle_alltodate(IN timestamp,OUT text)" type="function"/>
	<roles names="__ncsat_users__,__ncsat_internal__"/>
	<privileges execute="true"/>
</permission>

</dbmodel>

**Comment by fte1965** [comment]
I send test.dbm to yours mail

**Comment by rkhaotix** [comment]
Have you tried to fix the model?
Em 22/04/2015 03:38, "Takhir" <notifications@github.com> escreveu:

**Comment by fte1965** [comment]
![issue](https://cloud.githubusercontent.com/assets/3863428/7273187/c88149a8-e8f9-11e4-95b3-316cb3303a91.PNG)

**Comment by rkhaotix** [comment]
In that case I need the original model to see what is going on with the fix
steps.

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-04-22 8:14 GMT-03:00 Takhir <notifications@github.com>:

**Comment by fte1965** [comment]
I send letter with both (original and fixed) models to raphael@pgmodeler.com.br

**Comment by rkhaotix** [comment]
With that test.dbm you've sent it worked. The fix process corrected the
problem and the model loaded normally.

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-04-22 8:24 GMT-03:00 Takhir <notifications@github.com>:

**Comment by rkhaotix** [comment]
Well, I can confirm that this is working. Fixed the model using the
0.8.1-beta (new branch) but the same code as 0.8.1-alpha1.

If you pefer, you can open your model in a text editor and remove any OUT
parameter from functions signatures because in previous versions they were
included wrongly (according to docs).

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-04-22 8:25 GMT-03:00 Raphael Araújo e Silva <rkhaotix@gmail.com>:

**Comment by fte1965** [comment]
Ok
