### ISSUE TITLE
Wrong path to executable in Windows registry.

### ISSUE THREAD

**Issue by ams-tschoening** [pgmodeler/pgmodeler#679]
I just installed 0.8.1-alpha1 to test some bug fixes and directly after installation recognized that there's a wrong path in the registry for association of dbm files:

C:\Users\Raphael\Desktop\pgmodeler\build\pgmodeler.exe,1
and
"C:\Users\Raphael\Desktop\pgmodeler\build\pgmodeler.exe" "%1"

This is found in dbm_auto_file DefaultIcon and shell/open/command.

Additionally, you may consider using "%L" instead of "%1", because %L provides the full long path to the file always and is preferred in modern versions of Windows.

http://superuser.com/a/473602

**Comment by rkhaotix** [comment]
Thanks @tschoening . 
I'll check that again. Let me ask one thing? Did you uninstalled the previous version before install a new one? I suspect that the installer is messing around with the environment variables... :(

**Comment by tschoening** [comment]
Yes, I uninstalled before, but now that you mention it: I've forgotten to close a running instance and the uninstall didn't complete successfully, some files remained in the installation directory and I needed to delete those manually after closing the instance. But I don't think that explains the wrong path...
