### ISSUE TITLE
Problem creating a foreign key

### ISSUE THREAD

**Issue by slylord** [pgmodeler/pgmodeler#681]
I have to create a foreign key with multiple attributes (linked to another attribute of another table, of course).

the problem is about the attributes order: when I set the attributes order for a foreign key (a,b,c for example), every time I valid the foreign key it returns to another order (b,c,a for example, which is not the correct order). The attributes order may change for the mother table and/or for the child table. I've tried to close the foreign key declaration view, to delete/recreate the foreign key  and even to restart the computer.

It happens for a few foreign key of my model, not for all of them (in my model, approx 5 foreign keys / 50) but every problems appears on "heavy" foreign keys (approx 5 attributes concerned).

It's a bug which was present in the 0.7.2 version I previously bought.

I'm sorry I can't send yu the model.

**Comment by rkhaotix** [comment]
You can send a small model that can reproduce the problem ?
Em 23/04/2015 14:39, "slylord" <notifications@github.com> escreveu:
