### ISSUE TITLE
Compilation under cygwin in Windows (missing execinfo.h)

### ISSUE THREAD

**Issue by lourdas** [pgmodeler/pgmodeler#682]
I've installed the latest cygwin to compile pgmodeler. All seems to go fine, but at some point I get the error:

    g++ -c -pipe -fno-keep-inline-dllexport -O2 -std=gnu++11 -Wall -W -fexceptions -D_REENTRANT -DBUILDNUM=\"20150503\" -DBINDIR=\"\" -DPLUGINSDIR=\"\" -DPRIVATEBINDIR=\"\" -DCONFDIR=\"\" -DDOCDIR=\"\" -DLANGDIR=\"\" -DSAMPLESDIR=\"\" -DSCHEMASDIR=\"\" -DTEMPDIR=\"\" -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../libpgmodeler_ui -I../libpgmodeler_ui/src -I../libobjrenderer/src -I../libpgconnector/src -I../libpgmodeler/src -I../libparsers/src -I../libutils/src -I/usr/include/libxml2 -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -Imoc -I/usr/lib/qt5/mkspecs/cygwin-g++ -o obj/main.o src/main.cpp
    src/main.cpp:23:22: fatal error: execinfo.h: No such file or directory
    #include "execinfo.h"
                          ^
    compilation terminated.
    Makefile:590: recipe for target 'obj/main.o' failed
    make[1]: *** [obj/main.o] Error 1
    make[1]: Leaving directory '/home/Vasilis/pgmodeler-0.8.0/main'
    Makefile:394: recipe for target 'sub-main-make_first-ordered' failed
    make: *** [sub-main-make_first-ordered] Error 2

Any help? Windows is XP sp3 (32-bit).

**Comment by rkhaotix** [comment]
I've never tested the compilation with cygwin. Try to use mingw (msys or
msys2) or even compile the tool from within Qt creator
Em 03/05/2015 13:29, "Vasilis Lourdas" <notifications@github.com> escreveu:
