### ISSUE TITLE
Error while interpreting XML buffer at line 0 column 0. Message generated by the parser: Validation failed: no DTD found !. 

### ISSUE THREAD

**Issue by Rens70** [pgmodeler/pgmodeler#683]
I am getting this error executing pgmodeler from the applications directory (mac). The demo worked fine. OS X Yosemite

**Comment by rkhaotix** [comment]
Which version? O.s.?
Em 04/05/2015 08:44, "Rens70" <notifications@github.com> escreveu:

**Comment by Rens70** [comment]
OSX Yosemite

**Comment by rkhaotix** [comment]
Check if theres a folder called br.com.pgmodeler in ~/Library/Preferences.
If not the application failed to create default settings at first startup.

It the folder is missing,  please,  create it and copy the contents os
"conf" folder located in pgModeler's bundle to that new folder.
Em 04/05/2015 08:49, "Rens70" <notifications@github.com> escreveu:

**Comment by Rens70** [comment]
The folder is already there, including all the *.conf files.

**Comment by rkhaotix** [comment]
Did you ran the demo before purchase?  If so, remove the folder and run
pgModeler again
Em 04/05/2015 09:04, "Rens70" <notifications@github.com> escreveu:

**Comment by Rens70** [comment]
I think it's working now. Removing the (old) demo application and installing again seem to work. Thanks for your help!

**Comment by sidrock2309** [comment]
Hello,
im getting the following error while running pgmodeler
Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: No declaration for attribute capture-nearby of element word-separators . 
i have followed the instructions from this link 
https://github.com/miniwark/miniwark-howtos/blob/master/build_pgModeler0.9.0_for_Windows_64-bit.md|
please help
