### ISSUE TITLE
pgModeler crashes on startup on Mac OSX

### ISSUE THREAD

**Issue by InvalidCast** [pgmodeler/pgmodeler#684]
When launching pgModeler on OSX, get the error "Error while interpreting XML buffer at line 0 column 0.  Message generated by the parser: Validation failed: no DTD found!".  Is there a fix for this issue?  I just purchased the app today (version 0.8.0) and it won't even launch!

![screen shot 2015-05-05 at 4 56 07 pm](https://cloud.githubusercontent.com/assets/12140298/7481775/026892c6-f349-11e4-82d7-f31c45324d56.png)

[3] src/xmlparser.cpp (198)
void XMLParser::readBuffer()
[ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[2] src/xmlparser.cpp (122)
void XMLParser::loadXMLBuffer(const QString &)
[ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[1] src/xmlparser.cpp (91)
void XMLParser::loadXMLFile(const QString &)
[ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

[0] src/syntaxhighlighter.cpp (679)
void SyntaxHighlighter::loadConfiguration(const QString &)
[ERR_LIBXMLERR] Error while interpreting XML buffer at line 0 column 0.
Message generated by the parser: Validation failed: no DTD found !.

**Comment by chauvd** [comment]
Just ran into the same issue here.

**Comment by rkhaotix** [comment]
There's a small bug if you run the demo abd after the purchase version.
Please erase the folder ~/Library/Preferences/br.com.pgmodeler and run the
app again
Em 06/05/2015 09:34, "Daniel Chauvin" <notifications@github.com> escreveu:

**Comment by chauvd** [comment]
Perfect, confirmed. 

Thank you
