### ISSUE TITLE
Crash on osx 10.10.3

### ISSUE THREAD

**Issue by zxy198717** [pgmodeler/pgmodeler#685]
Process:               pgmodeler [77730]
Path:                  /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
Identifier:            br.com.pgmodeler.pgModeler
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           pgmodeler [77730]
User ID:               501

Date/Time:             2015-05-07 22:55:07.369 +0800
OS Version:            Mac OS X 10.10.3 (14D136)
Report Version:        11
Anonymous UUID:        04022DB5-AD7B-BF49-AE9F-126FA36BD2AB

Sleep/Wake UUID:       BC9A5644-7A08-4848-B8C7-9062F64DBB35

Time Awake Since Boot: 200000 seconds
Time Since Wake:       13000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: libpgmodeler_ui.1.dylib
  Referenced from: /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found

Binary Images:
    0x7fff64939000 -     0x7fff6496f837  dyld (353.2.1) <65DCCB06-339C-3E25-9702-600A28291D0E> /usr/lib/dyld

Who can help me?

**Comment by rkhaotix** [comment]
The Mac OSX bundle is being patched to permit user to call the main
application from within it. Currently, you've two options: 1) Execute the
application by opening the bundle or 2) use the command "startapp
pgmodeler" from /Applications/pgmodeler.app/Contents/MacOS/pgmodeler

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-05-07 11:55 GMT-03:00 Alvin <notifications@github.com>:

**Comment by zxy198717** [comment]
My step:
1. Checkout the latest code from https://github.com/pgmodeler/pgmodeler.
2. Do qmake pgmodeler.pro & make & make install.
3. Open pgmodeler APP from Applications.
4. pgmodeler crash.

Which step has mistake?

Thanks.

**Comment by rkhaotix** [comment]
Try to run the "pgmodeler" executable (not the bundle) using startapp
script. Or you can try this branch:
https://github.com/pgmodeler/pgmodeler/tree/0.8.1-beta the fix for this
crash is there!

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-05-07 12:10 GMT-03:00 Alvin <notifications@github.com>:

**Comment by zxy198717** [comment]
local$ sh start-pgmodeler.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
start-pgmodeler.sh: line 25: ./pgmodeler: No such file or directory
local:pgmodeler 

But I found the pgmodeler at "main/pgmodeler". 
After change that script:

local:pgmodeler$ sh start-pgmodeler.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
local:pgmodeler$ dyld: Library not loaded: libpgmodeler_ui.1.dylib
  Referenced from: /Users/AlvinZeng/Build/pgmodeler/./main/pgmodeler
  Reason: image not found

I will try branch https://github.com/pgmodeler/pgmodeler/tree/0.8.1-beta.

Thanks.

**Comment by zxy198717** [comment]
My mistake.
./startapp pgmodeler works.

Thanks

**Comment by calvinwillman** [comment]
The patch at the bottom of this issue mentioned by steakknife works to get it to run via a double click on the icon, normal Mac fashion. https://github.com/pgmodeler/pgmodeler/issues/243

However, the plugins are not available. I had to compile them separately in any case as they weren't included in the main app compilation. Then added to the directory within the app bundle, they are still not being registered at runtime, so not sure what's gone on there.
