### ISSUE TITLE
CREATE SERVER

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#687]
Please tell me how I can define in pgmodeler

SQL Statement 
CREATE SERVER
http://www.postgresql.org/docs/9.4/interactive/sql-createserver.html
CREATE USER MAPPING
http://www.postgresql.org/docs/9.4/interactive/sql-createusermapping.html
CREATE FOREIGN TABLE
http://www.postgresql.org/docs/9.4/interactive/sql-createforeigntable.html
CREATE FOREIGN DATA WRAPPER
http://www.postgresql.org/docs/9.4/interactive/sql-createforeigndatawrapper.html

**Comment by rkhaotix** [comment]
These objects are not supported by pgModeler. They are planning to be
included only in 0.9.x

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-05-15 10:00 GMT-03:00 Takhir <notifications@github.com>:

**Comment by fte1965** [comment]
Ok
