### ISSUE TITLE
pgmodeler-cli doesn't assume pwd for file locations

### ISSUE THREAD

**Issue by GeertJohan** [pgmodeler/pgmodeler#690]
I got a Segmentation Fault when executing pgmodeler-cli to export to png and found that pgmodeler-cli assumes /usr/local/bin as prefix for input/output files, even when specifying as `./filename.dbm`.

Example fail case:
```
$ pgmodeler-cli -i=nlgnet-schema.dbm -p -o=nlgnet-schema.png

pgModeler 0.8.1-alpha1 command line interface.
Starting model export...
Loading input file: /usr/local/bin/nlgnet-schema.dbm
[1]    6237 segmentation fault  pgmodeler-cli -i=nlgnet-schema.dbm -p -o=nlgnet-schema.png
```

Working usage: 
```pgmodeler-cli -i=`pwd`/nlgnet-schema.dbm -p -o=`pwd`/nlgnet-schema.png```

I think the cli tool should locate input/output files in the current working directory by default, and not use a built-in path prefix.

**Comment by rkhaotix** [comment]
Thanks for reporting! This is really a bug. I'll take a look on that as
soon as possible!
Em 23/05/2015 14:03, "Geert-Johan Riemer" <notifications@github.com>
escreveu:

**Comment by GeertJohan** [comment]
Thanks :smile: :+1:
