### ISSUE TITLE
Crashed at create index

### ISSUE THREAD

**Issue by obelich** [pgmodeler/pgmodeler#691]
Hiyas i recent download the app to test and i want to buy it i get this error in the demo at try to add a index
 i send the file create for email here knot attach

Sorry me english bad i speak spanish

**Comment by rkhaotix** [comment]
This issue was fixed in 0.8.1-beta. The workaround for now is to create
first the table. After that, reopen the table's dialog and create the index.

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-05-27 14:57 GMT-03:00 Oscar Miguel Amezcua Estrella <
notifications@github.com>:

**Comment by obelich** [comment]
ok thanks
