### ISSUE TITLE
pgModeler error on startup on Win 8.1 ( pgmodeler 0.8.1-beta)

### ISSUE THREAD

**Issue by tifmepo** [pgmodeler/pgmodeler#693]
When launching pgModeler on Win 8.1, get the error "Unable to write the file or directory `C:/Program Files (x86)/pgmodeler/plugins'! Make sure the output directory exists, or if the user has write permissions over it!".

![erro1](https://cloud.githubusercontent.com/assets/12697195/7915278/deb4e5d6-0852-11e5-962b-d0d6d51cb647.png)

If I click in OK, I get the error "Unable to write the file or directory `C:/Program Files (x86)/pgmodeler/tmp'! Make sure the output directory exists, or if the user has write permissions over it!.

But the PgModeler continues to boot .

From time to time during use of pgModeler appear the error:
" [ 0 ] src / databasemodel.cpp ( 6918 )
  void DatabaseModel :: saveModel (const QString & , unsigned int)
    [ ERR_FILE_DIR_NOT_WRITTEN ] Unable to write the file or directory ` ' ! Make sure the output directory exists , or if the user has write permissions over it !

I believe the error is generated by the presence of activated UAC .

![erro2](https://cloud.githubusercontent.com/assets/12697195/7915382/8f2fcaf2-0853-11e5-8469-e9a9debb9954.png)

**Comment by mytrix** [comment]
I have the same issue. There is probably used absolute path during compilation.

<code>[ERR_FILE_DIR_NOT_WRITTEN] Unable to write the file or directory `D:/Develope/pgmodeler-0.8.1/build/plugins'! Make sure the output directory exists, or if the user has write permissions over it!
</code>

v 0.8.1

**Comment by cvvergara** [comment]
For what is worth
same issue in 0.9 alpha

after
```
sudo make install
```
does not install `/usr/local/lib/pgmodeler/plugins`

after doing:

```
sudo cp -r plugins/ /usr/local/lib/pgmodeler/plugins
```

```
$ pgmodeler
element connection: validity error : No declaration for attribute connect-timeout of element connection
        sslmode="disable" auto-browse-db="false" />
                                                 ^
element connection: validity error : No declaration for attribute connect-timeout of element connection
        sslmode="disable" auto-browse-db="false" />
```
&
I get the error mentioned in #665 

contents of connection.conf
```
$ more .config/pgmodeler/connections.conf 
<?xml version="1.0" encoding="UTF-8" ?>
<!--
  CAUTION: Do not modify this file directly on it's code unless you know what you are doing.
           Unexpected results may occur if the code is changed deliberately.
-->
<connections>
        <connection alias="local-db" host="localhost" port="5432" dbname="postgres"
                user="postgres" password="postgres" connect-timeout="2"
        sslmode="disable" auto-browse-db="false" />
```

```
diff -u /usr/local/share/pgmodeler/conf/defaults/connections.conf /usr/local/share/pgmodeler/conf/connections.conf
--- /usr/local/share/pgmodeler/conf/defaults/connections.conf   2016-10-19 23:59:22.631244652 -0500
+++ /usr/local/share/pgmodeler/conf/connections.conf    2016-10-18 06:21:11.000000000 -0500
@@ -4,7 +4,7 @@
            Unexpected results may occur if the code is changed deliberately.
 -->
 <connections>
-        <connection alias="local-db" host="localhost" port="5432" dbname="postgres"
-                user="postgres" password="postgres" connection-timeout="2"
+       <connection alias="local-db" host="localhost" port="5432" dbname="postgres"
+               user="postgres" password="postgres" connect-timeout="2"
                 sslmode="disable" auto-browse-db="false"/>
 </connections>
```

after changing the files so they both have `connect-timeout` I still get:
```
$ element connection: validity error : No declaration for attribute connect-timeout of element connection
        sslmode="disable" auto-browse-db="false" />
```
