### ISSUE TITLE
HELP ME !!  libpq.dll: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by richqez** [pgmodeler/pgmodeler#695]
Windows 8.1 x86
Postgres 9.4
qt-opensource-windows-x86-mingw491_opengl-5.4.1_2

C:\PostgreSQL\9.4\lib\libpq.dll: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
Makefile.Release:85: recipe for target 'pgconnector.dll' failed
mingw32-make[2]: **\* [pgconnector.dll] Error 1
mingw32-make[2]: Leaving directory 'c:/Users/User/Desktop/pgmodeler/libpgconnector'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: **\* [release] Error 2
mingw32-make[1]: Leaving directory 'c:/Users/User/Desktop/pgmodeler/libpgconnector'
makefile:175: recipe for target 'sub-libpgconnector-make_first-ordered' failed
mingw32-make: **\* [sub-libpgconnector-make_first-ordered] Error 2

**Comment by cmelgarejo** [comment]
I'm having the same issue right now, no one can hint something? thanks.

**Comment by richqez** [comment]
Try to use 32 bit version

**Comment by cmelgarejo** [comment]
Figured out already. I was about to post this hehe

-----Mensaje original-----
De: "richqez" <notifications@github.com>
Enviado el: ‎30/‎12/‎2015 12:45
Para: "pgmodeler/pgmodeler" <pgmodeler@noreply.github.com>
CC: "Christian Melgarejo Bresanovich" <christian.melgarejo.bresanovich@gmail.com>
Asunto: Re: [pgmodeler] HELP ME !!  libpq.dll: file not recognized: Fileformat not recognized (#695)

Try to use 32 bit version

**Comment by richqez** [comment]
Great !!!

**Comment by abincai** [comment]
try 32 bit libxml2?

**Comment by abincai** [comment]
Figuring out.Try 32bit postgres
