### ISSUE TITLE
Enable object rename in Database Explorer

### ISSUE THREAD

**Issue by rkhaotix** [pgmodeler/pgmodeler#698]
Enable the user to rename objects in Database Explorer widget. By typing F2 the item can have its name changed and then an Alter command is triggered to the database. Once renamed an object the tree must be updated.

**Comment by yogesch** [comment]
After renaming an object in pgmodeler, nothing changes in the database automatically. But on exporting the new model with the renamed objects, the existing database model still gets overwritten instead of being altered to get the new name.
