### ISSUE TITLE
output show error truncated

### ISSUE THREAD

**Issue by Grunge** [pgmodeler/pgmodeler#700]
When Exporting with Version 0.8.1-beta, the Output truncates the Error in the View.
See screenshot. Would be nice if the text could be expanded/shown as Tooltip.
Greetings & thanks

![pgmodeler_081_beta_output](https://cloud.githubusercontent.com/assets/4060331/8409809/bcc06214-1e7a-11e5-9ee4-b523d6d5078d.png)

**Comment by rkhaotix** [comment]
By double-clicking the selected item you are able to read/copy the entire
text and see the complete error message.

[image: http://pgmodeler.com.br] <http://pgmodeler.com.br>

2015-06-29 11:21 GMT-03:00 Grunge <notifications@github.com>:

**Comment by Grunge** [comment]
okay, thanks i just would like to have it better looking.
But thats just a nice to have feature.

**Comment by rkhaotix** [comment]
I know it looks like weird. This is because I must handle the output in three different systems (Windows, Linux and OS X)... The Linux is the one with the best looking, in the other two I'm struggling to improve the UI. I hope in a near future the UI could be the same for all O.S. :)
