### ISSUE TITLE
QFileDialogs don't have parents: causes complete unresponsiveness under KDE 5

### ISSUE THREAD

**Issue by nickguletskii** [pgmodeler/pgmodeler#702]
When using pgmodeler under KDE 5, all QFileDialogs cause the whole pgmodeler UI to stop responding (not really a freeze, just lock up), meaning that pgmodeler is completely unusable under KDE 5. This happens because QFileDialog instances need parents.

**Comment by rkhaotix** [comment]
According to Qt 5.4.x docs QFileDialog, the parent attribute is optional. See the second ctor in this link:
http://doc.qt.io/qt-5/qfiledialog.html

I don't have KDE5 to test but in KDE4 it works perfectly.

**Comment by rkhaotix** [comment]
Any way there is some error message that I can check? Also, I'll open a new branch setting parent for the dialogs and let you test it. What do you think?

**Comment by nickguletskii** [comment]
Thanks for the quick response. I am preparing a pull request with the fixes right now.

**Comment by rkhaotix** [comment]
Oh. Sorry and thank you for the pull request! :)

**Comment by nickguletskii** [comment]
For anyone having the same issue as me, this seems to be directly caused by this: https://git.reviewboard.kde.org/r/123335/
