### ISSUE TITLE
Validation with uuid-ossp extension.  (with UTF8 encoding)

### ISSUE THREAD

**Issue by donnorman** [pgmodeler/pgmodeler#708]
Hello,

I'm running pgModeler 0.7.2 and PostgreSQL 9.4.1.3.

When trying to use the SQL Validation feature, I keep getting the following error after it processes all of the tables against the server.

`ERROR:  function uuid_generate_v4() does not exist`

I am using `UUID` as a column type and a default value of `uuid_generate_v4()`.
I have the `uuid-ossp` extension installed on the `postgres` database as well as the one I am using.

The extension is working fine because I can `SELECT uuid_generate_v4();` and get a UUID response at the console.

Now, I don't know if it matters or not that the `Template DB` is set to `template0` and not `postgres`.

I'm using `template0` due to another issue with validation.  The database Encoding option in pgModeler is `UTF8`, but when I run validation I get the following error.

`ERROR:  new collation (en_US.UTF8) is incompatible with the collation of the template database (en_US.utf8)`

And it suggests that I use a different template database.

In the end the SQL all works fine, but I just figured you would like to know about the validation issues.

Thanks for the great program!

**Comment by rkhaotix** [comment]
Hi @donnorman,
Thanks for your feedback!

About your issues...

1) Have you created the extension object "uuid-ossp" in your model? Because pgModeler need to create a temporary database in the server in order to validate objects. At the validation process  occurs all objects in the model will be created and if somehow you are using a function created by extension and the extension itself is not installed the error you've report will be raised. In short, create the extension "uuid-ossp" in your model and try to validate it. I'm 99% sure that this will solve the problem.

2) The collation errors is occurs because pgModeler generates a list of collations that may differ from Linux distro to distro or even from OS to OS. In 0.7.2 the workaround is the one you've used: set the template database to template0. In newer versions, a fix was introduced and the user can specify a custom enconding/locale in order to avoid those errors.

**Comment by donnorman** [comment]
@rkhaotix Thanks for the quick response.

I tried adding the extension, but I receive the same error during validation.

I have multiple schemas  in this database, and put the extension in the public schema and then also tried putting it in a schema where one of the tables uses the extension.

Does it matter that I am using the `Use unique temporary names for database, role and tablespace objects` option?  I didn't want to interfere with the tables that may have already been created.

**Comment by donnorman** [comment]
@rkhaotix I was able to fix that issue.

On a hunch I opened the dbm file in a text editor and looked for the XML generated for the extension.
It was attempting to be used before it was declared in the XML.

I cut and pasted it directly after the schema definition and it gets past that part now.

**Comment by rkhaotix** [comment]
Hi @donnorman 

There some situations where pgModeler can't solve by validating the model. And the situation you mentioned is one of them. Let me explain, say that you are using a function that is created by an extension "extension_test". This function is called inside a view named "view_test", for instance. 

Knowing that the function is created by the "extension_test" you immediately create this last object after the "view_test". In pgModeler, all objects have an unique ID. To put simple "view_test" has an id=1 and the "extension_test" an id=2. In the moment of the validation, pgModeler will create first the view and then the extension which will produce the error.

Finally, I gave you a bit explanation of internal details of the software that can help you to solve some issues with the tools that it offers. You don't need to open the model in a text editor and move the object, just go to the validation tool and click "Swap ids" (see image)
![validate_img](https://cloud.githubusercontent.com/assets/2205476/8702325/99b19822-2aed-11e5-91af-5a0fd1b0c883.png)

With this dialog you are able to change the creation order between two objects and avoid the most common reference errors. In case of our example, put in the "Create" selector the object "extension_test" and in the "Before" selector the object "view_test" and apply! Now when validation the model you will see the extension being created before the view! :)

**Comment by donnorman** [comment]
Oh ok, very nice, thanks!

**Comment by m-thirumal** [comment]
This works with `DIFF`?

**Comment by rkhaotix** [comment]
> This works with `DIFF`?

Could you elaborate, please?
