### ISSUE TITLE
Array of Citext is not supported

### ISSUE THREAD

**Issue by seuros** [pgmodeler/pgmodeler#709]
I'm using using the latest stable version 0.8.0
In one of my tables i have `citext[]` in one column. I get the following error.

```
[4] src/databaseimporthelper.cpp (1440)
  void DatabaseImportHelper::createType(attribs_map &)
    [ERR_ASG_INV_NAME_OBJECT] Assignment of a name which contains invalid characters!
       ** <usertype name="citext[]" configuration="base"
 internal-length="-1" by-value="false"
 alignment="integer" storage="extended"
 element="citext" delimiter=","
 category="A" collatable="true">
        <schema name="public"/>
        <role name="abdelkader"/>
        <!--[ unknown object OID=750 ]-->
        <!--[ unknown object OID=751 ]-->
        <!--[ unknown object OID=2400 ]-->
        <!--[ unknown object OID=2401 ]-->
        <!--[ unknown object OID=3816 ]-->
</usertype>

```

**Comment by rkhaotix** [comment]
citext is an type related to an extension?

**Comment by seuros** [comment]
Correct : http://www.postgresql.org/docs/9.1/static/citext.html

**Comment by rkhaotix** [comment]
Sorry... forget my previous question. It seems pgModeler is putting the type of the column on the wrong place. Do you have a small sample database in which is possible to reprodutce the error?

**Comment by seuros** [comment]
No , but i will provide you one asap. I can dump provide the failing table.
