### ISSUE TITLE
Escape on comment

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#710]
Hi,

After generating a diff file from my database, I see a problem on COMMENT : 
> COMMENT ON COLUMN public.depot.url IS 'Chemin d'accès.';

The simple quote in the comment text is not escaped.

Great work anyway !

**Comment by rkhaotix** [comment]
Hi @rimbault 

I'll provide a quick fix for that! Thanks for reporting!

**Comment by rimbault** [comment]
Thanks for this quick fix !

**Comment by rkhaotix** [comment]
You're welcome! :+1:
