### ISSUE TITLE
Broken Windows installer because of debug build?

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#716]
I just installed version 0.8.1 and it dosn't work, it requests Qt5Cored.dll, which is not available in the installation directory. Running depends.exe with pgmodeler.exe, it looks like you provided a debug build for Windows without providing the debug DLLs.

![screenshot pgmodeler](https://cloud.githubusercontent.com/assets/6223655/9009396/2d9ec73e-37a1-11e5-807b-17106aecb5c3.jpg)

**Comment by rkhaotix** [comment]
Oh. That's not good. I'll fix it right now! Thanks
Em 31/07/2015 11:29, "Thorsten Schöning" <notifications@github.com>
escreveu:

**Comment by rkhaotix** [comment]
It sould be ok now! Double checked dependency walker and know the executable points to the release version of Qt dlls. Thank you again for reporting this!

**Comment by tschoening** [comment]
Confirmed, just downloaded, installed, works. Thanks!
