### ISSUE TITLE
Checking `deferrable` for a trigger has no effect on the generated SQL

### ISSUE THREAD

**Issue by ziadloo** [pgmodeler/pgmodeler#719]
First let me congratulate you for your awesome software, it's really helpful.

It seems this is a missing feature, I'm not sure if it's intentional or not so I thought I should report it. When I tried to create a trigger for a table, checking the `deferrable` checkbox had no effect on generated SQL statement. Using the `export` button also didn't create a deferrable trigger.

I'm using pgModeler v0.8.1-beta 1 (build: 20150730) on a 64bit Ubuntu 14.04.

**Comment by rkhaotix** [comment]
Thank you for reporting this fail @ziadloo !
Found the bug and already fixed it!

If you are able to compile pgModeler you can try the last commit d1a4ab9250674ba417cb40ed55db9c8ec50f7b77

If you purchased pgModeler I kindly ask you to wait for the next release 0.8.2-alpha that will happen in 20-30 days.
