### ISSUE TITLE
integration pgmodeler with doxygen

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#724]
It's possible?
for example if you add to all objects of model property "description"
and I can fill it with my own comment with doxygen style
I need to transfer to the customer a complete set of documentation for my program with a detailed description of all the tables, functions, etc., in government standards, as well doxygen greatly simplifies my job
it would be great to be able to export model in sql-script with comments in the style of doxygen

www.doxygen.org
http://www.chrisoldwood.com/wip/sql2doxygen/manual/sql2doxygen.html

**Comment by rkhaotix** [comment]
There is no such support in pgModeler. What you can do is used the "Custom SQL" form to append/prepend Doxygen styled comments. I think it should work almost in the way you need.

**Comment by fte1965** [comment]
agree it will solve my issues by 95%, I think this will be enough
