### ISSUE TITLE
Drop trigger generating invalid SQL, double "on table"

### ISSUE THREAD

**Issue by darkdiablo** [pgmodeler/pgmodeler#728]
Hi,

basically SQL drop code is generated with double "on table" that makes it unusable for export with drop objects.

Please fix it

Example
`DROP TRIGGER IF EXISTS user_dt_upd ON system."user"  ON system."user" CASCADE;`

Code for creating trigger:
-- object: "TR_system_user_dt_upd" | type: TRIGGER --
-- DROP TRIGGER IF EXISTS "TR_system_user_dt_upd" ON system."user"  ON system."user" CASCADE;
CREATE TRIGGER "user_dt_upd"
	BEFORE UPDATE
	ON system."user"
	FOR EACH ROW
	EXECUTE PROCEDURE system.update_dt_upd();

**Comment by darkdiablo** [comment]
pretty please, 

i have to disable triggers and use custom sql

**Comment by rkhaotix** [comment]
Hi, sorry the delay to fix it!

The patch will be officially released when the final 0.8.2 ir ready! But you can try it right now... Just download this file:
https://github.com/pgmodeler/pgmodeler/blob/0.8.2-alpha/schemas/sql/drop.sch

And replace the original ```drop.sch```  in ```the schema/sql/```

It should work.

**Comment by darkdiablo** [comment]
sweet, thanx

btw great job on application, keep it up
