### ISSUE TITLE
Suggestion: allow individual objects to be exported to the database

### ISSUE THREAD

**Issue by nickguletskii** [pgmodeler/pgmodeler#731]
Preferably from the context menu. For example, I've modified a function, and I want to test how it works. As it stands right now, I have to shut down all connections to the database and run "Export", or run the function creation source manually. This gets quite annoying when you are writing a lot of functions.

**Comment by rkhaotix** [comment]
Did you tried the diff process?

**Comment by nickguletskii** [comment]
Yes, and it's not really what I am talking about. The diff process does a full diff of the database. That is slow and is completely overkill for small changes.

**Comment by rkhaotix** [comment]
Right. I'm just confirming! :)
I'll analyze your suggestion and try to put it in the next major release 0.9.0. It's not that complicated.

Thanks.

**Comment by nickguletskii** [comment]
Thank you very much for this amazing software!

**Comment by rkhaotix** [comment]
You're welcome! Thanks for helping to improve pgModeler with new feature requests! ;)
