### ISSUE TITLE
Suggestion: add SSH tunnel to connection

### ISSUE THREAD

**Issue by SvatoplukHus** [pgmodeler/pgmodeler#733]
Thank you.

**Comment by cbednarski** [comment]
While you're waiting for this you can achieve the same via `ssh`:

    ssh -L 5432:127.0.0.1:5432 -N -f <remote-ip>

See `man ssh` for details and use `ps x | grep ssh` to find and `kill` the tunnel when you're done.

**Comment by hiepxanh** [comment]
I like this feature too :D
