### ISSUE TITLE
pgsql : ELSE clause seems unrecognized

### ISSUE THREAD

**Issue by CaptainBloodz** [pgmodeler/pgmodeler#734]
When ELSE clause is inserted in the following definition, it remains in blue color instead of black as for IF, THEN or END IF.
function execution in psql returns error at END; at character;

-- object: public.login_email_duplicate | type: FUNCTION --
-- DROP FUNCTION IF EXISTS public.login_email_duplicate(IN varchar(20),IN varchar(254)) CASCADE;
CREATE FUNCTION public.login_email_duplicate (IN login varchar(20) DEFAULT NULL, IN email varchar(254) DEFAULT NULL)
	RETURNS boolean
	LANGUAGE plpgsql
	VOLATILE 
	STRICT
	SECURITY INVOKER
	COST 1
	AS $$
DECLARE
mybigint bigint :=1;
myboolean boolean :='t';
BEGIN
SELECT COUNT(*) INTO mybigint FROM login WHERE login.login=$1 or login.email=$2;
IF 0 = mybigint THEN myboolean :='f';
END IF;
RETURN myboolean;
END;
$$;
-- ddl-end --
ALTER FUNCTION public.login_email_duplicate(IN varchar(20),IN varchar(254)) OWNER TO postgres;
-- ddl-end --
COMMENT ON FUNCTION public.login_email_duplicate(IN varchar(20),IN varchar(254)) IS 'returns returns f if neither login or email already exist, t otherwise';
-- ddl-end --

I strongly guess it is more of a pgsql error than a pgmodeler error.
Still requesting for help.

Thanks for your attention

**Comment by rkhaotix** [comment]
There is no error when executing the code either in pgModeler's SQL tool or in psql.

About the ELSE keyword not being highlighted correctly, it's just a missing configuration in sql-highlight.conf. I'll add it. Thanks.

**Comment by CaptainBloodz** [comment]
Well ... Guess I have lots to learn still ...
BTW is pgModeler's SQL tool an extension as I can't find it in my interface?

**Comment by rkhaotix** [comment]
Click the "Manage" button at left bar. :)
The Sql tool is still being improved but you can run commands and manage
data. It still lacks dialog to create database objects
Em 26/08/2015 11:16 AM, "CaptainBloodz" <notifications@github.com> escreveu:

**Comment by CaptainBloodz** [comment]
Thks, besides ELSE works just fine, my apologize ...
