### ISSUE TITLE
QUERY keyword not bolded

### ISSUE THREAD

**Issue by CaptainBloodz** [pgmodeler/pgmodeler#739]
Same as ELSE clause, which works just fine though

**Comment by Ox0000** [comment]
CaptainBloodz, thanks for reporting this!
Can you provide us with repro steps (executed steps, expected outcome, actual outcome)? Where did you encounter this?

**Comment by rkhaotix** [comment]
The problem is simple to solve. The keyword is missing from
sql-highlight.conf file. Later today I'll provide the fix for this issue.
Em 28/08/2015 1:00 PM, "Ox0000" <notifications@github.com> escreveu:
