### ISSUE TITLE
Error running pgmodeler on Mac OS X 10.10.5

### ISSUE THREAD

**Issue by miller15** [pgmodeler/pgmodeler#750]
When I try to run the pgmodeler 0.8.1 application, a dialog box pops up:
(Note: using Qt 5.5.0)
![image](https://cloud.githubusercontent.com/assets/8574097/9798839/a7399326-57d1-11e5-901f-42bb8f810685.png)

**Comment by rkhaotix** [comment]
This dialog is not enough to know what is happening. I don't know what Qt version you are using but pgModeler is not ready for Qt 5.5 is Mac OS X and some crashes may occur.

Also, take a look in this issue: https://github.com/pgmodeler/pgmodeler/issues/721
Try to run ```macdeployqt``` to fix some lib paths in the executables (details in the issue)

**Comment by miller15** [comment]
Thank you for your quick response.
Here are the report details if you would like to take a look at them while I try your suggestions:

Process:               pgmodeler [31412]
Path:                  /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
Identifier:            br.com.pgmodeler.pgModeler
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           pgmodeler [31412]
User ID:               1766347467

Date/Time:             2015-09-10 16:06:43.112 -0400
OS Version:            Mac OS X 10.10.5 (14F27)
Report Version:        11
Anonymous UUID:        EDF76349-D36A-B494-F3DF-DB7D042C2CDB


Time Awake Since Boot: 3000 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: libpgmodeler_ui.1.dylib
  Referenced from: /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
  Reason: image not found

Binary Images:
    0x7fff6e197000 -     0x7fff6e1cd887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld

Model: MacBookPro11,5, BootROM MBP114.0172.B04, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2048 MB
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: Thunderbolt Ethernet, Ethernet, en3
PCI Card: Apple 57762-A0, Ethernet Controller, Thunderbolt@195,0,0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1
Thunderbolt Device: Thunderbolt to Gigabit Ethernet Adapter, Apple Inc., 1, 5.5

**Comment by rkhaotix** [comment]
Thanks. Based on the log I think that what I have suggested will work! :)

**Comment by miller15** [comment]
When I run the command: "macdeployqt pgmodeler.app -executable=pgmodeler.app/Contents/MacOS/pgmodeler-ch -executable=pgmodeler.app/Contents/MacOS/pgmodeler-cli"
I get the Error: 
Could not find app bundle "pgmodeler.app"

**Comment by rkhaotix** [comment]
You need to pass the full path to pgmodeler.app

**Comment by miller15** [comment]
Ok now I have these errors:
ERROR: no file at "/usr/lib/libpgmodeler_ui.1.dylib"
ERROR: no file at "/usr/lib/libobjrenderer.1.dylib"
ERROR: no file at "/usr/lib/libpgconnector.1.dylib"
ERROR: no file at "/usr/lib/libpgmodeler.1.dylib"
ERROR: no file at "/usr/lib/libparsers.1.dylib"
ERROR: no file at "/usr/lib/libutils.1.dylib"

For the last one in the list, I have a libutils.1.0.0.dylib file. Still checking the others to see if they are somewhere else. Any recommendations in the mean time?

**Comment by rkhaotix** [comment]
It's ok... These errors don't affect the final result. If no error except for these ones were raised you are able to run pgModeler

**Comment by miller15** [comment]
hmm unfortunately same as initial error when I try to run pgModeler app
