### ISSUE TITLE
Object ID sequencing mess

### ISSUE THREAD

**Issue by RomanHargrave** [pgmodeler/pgmodeler#751]
I am currently making some changes to a database schema I created in PGModeler. One of these changes led to creating a custom type which was referenced by a table created at an earlier time. Obviously, ID is going to be an issue, and a simple swap should fix the problem -- but it does not. 

When trying to swap object ID's, nothing happens. The table that is dependent on the type keeps its original ID (4082), as does the type (4190). It is apparent that this is some manner of underlying bug, as when the validator attempts the same solution, it contentiously fails and retries, and will be stuck in that loop until it is cancelled.

At the moment, it is likely that I will need to edit the `dbm` file by hand, which can be mildly infuriating.

I am experiencing this issue at commit 9271d9d452434151c278e1c1b324ce721ba2deea. Due to confidentiality issues, I can not post the `dbm` file here.

**Comment by RomanHargrave** [comment]
I just looked at the DBM file and I am absolutely confused now. 

The composite type is indeed specified _before_ the dependent object.

**Comment by RomanHargrave** [comment]
After re-opening the _un-modified_ project, the issue is no longer present.

That being said, I am leaving this bug open as the behaviour is obviously wrong.

**Comment by rkhaotix** [comment]
We can reproduce this bug in a small model?

Another question, is not clear to me but the composite type references a table and that same table references the composite type? If this is the situation we have a redundant reference and unfortunatelly can't be solve by pgModeler! This is one of the limitations of the tool. :(

**Comment by RomanHargrave** [comment]
No, the composite type is insular from everything else, e.g. it depends on nothing. So it's not a cyclic reference. The issue (if you read all my posts) is that while the order is updated in the DBM file, PGModeler does not acknowledge it's own change until the file is reloaded.

**Comment by rkhaotix** [comment]
Yes,  I read all your posts. I'm trying to clarify things in order to try a
workaround or a fix. But it's ok I'll try to reproduce the error.
Em 11/09/2015 8:00 PM, "Roman Hargrave" <notifications@github.com> escreveu:
