### ISSUE TITLE
Import SQL

### ISSUE THREAD

**Issue by bebr42** [pgmodeler/pgmodeler#752]
Importing SQL would be very helpful.
From older projects I have various pg_dump SQL files, without databases running any more.
Now to get a model in pgmodeler, one has to set up a database, execute the SQL, build a connection in pgmodeler - tedious. 
As the demo is capable to export SQL I expected the full version to be able to import it.

**Comment by rkhaotix** [comment]
No. It is not possible to import database from Sql as described in
project's site. This is a quite difficult feature to implement and in a
near future I don't plan to add it to pgmodeler.
Em 13/09/2015 12:39 PM, "Bebr" <notifications@github.com> escreveu:

**Comment by bebr42** [comment]
Given there is a connection, It would need not more than an Upload feature, then execute the script, show the output. Correct me if I'm wrong.

**Comment by rkhaotix** [comment]
The SQL import I plan is quite different. It'll parse a Sql script and create the model without the need to run a server. Let's say is a offline import.

What do you want now, as I can understand,  is to upload the script to the server and proceed with the reverse engineering. Right?

**Comment by bebr42** [comment]
Offline would be the best solution, of course.
A compromise is setting up a dummy database and connecting to that. Uploading and executing the script could be done with another tool (like pgadmin), but it'd be cooler to have one interface in pgModeler.

**Comment by rkhaotix** [comment]
I'm planning to add an interface to pg_* commands and integrate them to
pgmodeler soon. This way the user will be able to do basic operations on
the server without use another tool.
Em 13/09/2015 2:01 PM, "Bebr" <notifications@github.com> escreveu:

**Comment by bebr42** [comment]
Fine.
