### ISSUE TITLE
Invalid PostgreSQL version '9.3' assigned to parser! Valid versions are: 9.0, 9.1, 9.2

### ISSUE THREAD

**Issue by glennSutton** [pgmodeler/pgmodeler#757]
When trying to import a database schema I get the attached error message complaining that the postgreSQL version 9.3 is invalid.  The webpage indicates that 9.x is supported.  Is there some further configuration required on the client i.e. config file settings etc.

The database connection is successful.  It's when importing it complains. I have attached the error message including limited trace, an image showing my database connection is successful, the about splashpage for the pgModeler version I'm using and my server details for postgreSQL
![postgres_error](https://cloud.githubusercontent.com/assets/14832097/10093633/4ba317a6-63a9-11e5-83eb-2f6337fa577b.png)

![postgres_connx_success](https://cloud.githubusercontent.com/assets/14832097/10093639/599b37bc-63a9-11e5-8668-b1d71152b5f8.png)

![aboout_pgmodeler](https://cloud.githubusercontent.com/assets/14832097/10093644/653373a0-63a9-11e5-96d7-783dbee5d112.png)

![postgres_svr](https://cloud.githubusercontent.com/assets/14832097/10093647/6c0d423c-63a9-11e5-8140-3c2ec113b17b.png)

Any assistance greatly appreciated.  I am keen to use the modeler to reverse engineer a schema diagram for a legacy database.

Cheers

**Comment by rkhaotix** [comment]
The release you're using doesn't supports the database version 9.3 or
above. In the moment 0.6.0-beta was released PostgreSQL 9.3 was released
just three days before.

The support to 9.3 was included in 0.6.1 released in November 2013.

So, the only thing I can do is ask you to upgrade your current release to
at least 0.6.1.
Em 25/09/2015 2:18 AM, "glennSutton" <notifications@github.com> escreveu:
