### ISSUE TITLE
Change payment gateway on website

### ISSUE THREAD

**Issue by AndresGuerraMax** [pgmodeler/pgmodeler#760]
This maybe off topic, but I don't know a better place to suggest this; I was going to buy platinum edition and I didn't notice the payment was with Paypal, here in my country is really tedious to use Paypal, only one bank supports it, it takes a long delay to transfer funds and an exaggerated fee.

I really liked the software and I think is the best gui for postgres and I need to use it full featured right now, so my suggestion is to use a payment gateway that charges directly to a credit or debit card, like Stripe or Braintree, I hope this can be worked out somehow.

**Comment by rkhaotix** [comment]
Hello Andres!

You did well in open this issue! I really need to add more options of purchase. I'll do that in the new project's site that I'm planning to release between December and February. I'm a bit busy updating the user's guide and creating a patch release (0.8.2-alpha) to be released in the Octuber 05 but when finishing these tasks I'll work in the web site.

The problem with Stripe and Baintree is that they can't support brazilian banks right now. But I am already evaluating some other options.

Anyway thanks for suggest!
