### ISSUE TITLE
Allowing uppercase without quoting object name

### ISSUE THREAD

**Issue by okamy** [pgmodeler/pgmodeler#761]
Hi,

I'd like to use CamelCase naming convention in my database model, but PgModeler has a quite Strange way of handling these in my opinion. In postgres, Table is equivalent to table, RoleID is equivalent to roleid. But PgModeler quotes object name even if the only difference is the case.
I don't care if objects names are in lower case in postgres, but i really want them to be in CamelCase in my model.
I looked at the source code of PgModeler and tried some stuff. It was quite easy to allow the uppercase without quoting, but the diffs from database keeps droping and recreating everything because the name are in lower case in the database and in uppercase in the model. I can't figure out how exactly the diff is done.
Can you tell me where i've to look in order to do that ?

I join the diff between the original source code (v0.8.1) and what i tried.

Best regards.

```
Parent: 9f7a171101272e82a14fece4786ef1f9e25048dd (commit initial)
Branch: master
Follows: 
Precedes: 

    diff

----------------------- libpgmodeler/src/baseobject.cpp -----------------------
index cd6467a..5546620 100644
@@ -205,9 +205,8 @@ QString BaseObject::formatName(const QString &name, bool is_operator)
                 //3 bytes UTF-8 character
                 (chr  >= 0xE0 && chr <= 0xEF &&
                    chr1 >= 0x80 && chr1 <= 0xBF &&
-                   chr2 >= 0x80 && chr2 <= 0xBF) ||
-
-                QChar(chr).isUpper())
+                   chr2 >= 0x80 && chr2 <= 0xBF)
+                )
            {
         needs_fmt=true;
            }
@@ -567,6 +566,27 @@ QString BaseObject::getName(bool format, bool prepend_schema)
     return(this->obj_name);
 }

+QString BaseObject::getLowerName(bool format, bool prepend_schema)
+{
+    QString name = this->obj_name;
+    QString nameLower = name.toLower();
+   if(format)
+   {
+       QString aux_name;
+       aux_name=formatName(nameLower, (obj_type==OBJ_OPERATOR));
+
+       if(this->schema && prepend_schema)
+      aux_name=formatName(this->schema->getName(format)) + QString(".") + aux_name;
+
+       if(!aux_name.isEmpty())
+           return(aux_name);
+       else
+           return(nameLower);
+   }
+   else
+    return(nameLower);
+}
+
 QString BaseObject::getSignature(bool format)
 {
   return(this->getName(format, true));
@@ -856,7 +876,7 @@ QString BaseObject::getCodeDefinition(unsigned def_type, bool reduced_form)
        }
    }

-  return(code_def);
+  return(code_def.toLower());
 }

 void BaseObject::setAttribute(const QString &attrib, const QString &value)

------------------------ libpgmodeler/src/baseobject.h ------------------------
index 0b29670..c9801f9 100644
@@ -313,6 +313,7 @@ class BaseObject {
         the name properly formated (using quotes when there is uppercase char or extended utf-8),
         the parameter 'prepend_schema' includes the schema name on the objects name (defult) */
     virtual QString getName(bool format=false, bool prepend_schema=true);
+    virtual QString getLowerName(bool format=false, bool prepend_schema=true);

     //! brief Returns the name of the object with schema name (when available) prepended by default
     virtual QString getSignature(bool format=true);

----------------------- libpgmodeler/src/tableobject.cpp -----------------------
index eecf84a..ebaaee7 100644
@@ -126,5 +126,5 @@ QString TableObject::getSignature(bool format)
   if(!parent_table)
     return(BaseObject::getSignature(format));

-  return(QString("%1.%2").arg(parent_table->getSignature(format)).arg(this->getName(format)));
+  return(QString("%1.%2").arg(parent_table->getSignature(format)).arg(this->getLowerName(format)));
 }

------------------- libpgmodeler_ui/src/modelsdiffhelper.cpp -------------------
index 370de98..f043571 100644
@@ -158,7 +158,7 @@ void ModelsDiffHelper::diffTables(Table *src_table, Table *imp_table, unsigned d
     for(auto &tab_obj : *tab_objs)
     {
       //Get the object from the compared table
-      aux_obj=comp_tab->getObject(tab_obj->getName(), tab_obj->getObjectType());
+      aux_obj=comp_tab->getObject(tab_obj->getLowerName(), tab_obj->getObjectType());
       constr=dynamic_cast<Constraint *>(tab_obj);

       //Ignoring check constraints added by generalizations
@@ -264,8 +264,8 @@ void ModelsDiffHelper::diffModels(unsigned diff_type)
           {
             Table *ref_tab=nullptr, *rec_tab=nullptr;

-            ref_tab=aux_model->getTable(rel->getReferenceTable()->getName(true));
-            rec_tab=aux_model->getTable(rel->getReceiverTable()->getName(true));
+            ref_tab=aux_model->getTable(rel->getReferenceTable()->getLowerName(true));
+            rec_tab=aux_model->getTable(rel->getReceiverTable()->getLowerName(true));

             /* If the receiver table exists on the model generates a info for the relationship,
                otherwise, the generalization will be created automatically when the table is
@@ -355,7 +355,7 @@ void ModelsDiffHelper::diffTableObject(TableObject *tab_obj, unsigned diff_type)
 {
    BaseTable *base_tab=nullptr, *aux_base_tab=nullptr;
    ObjectType obj_type=tab_obj->getObjectType();
-  QString tab_name, obj_name=tab_obj->getName(true);
+  QString tab_name, obj_name=tab_obj->getLowerName(true);
    BaseObject *aux_tab_obj=nullptr;

   //Get the parent table of the object
@@ -453,7 +453,7 @@ void ModelsDiffHelper::generateDiffInfo(unsigned diff_type, BaseObject *object,
         BaseTable *tab=col->getParentTable();

         //Configures the sequence
-        seq->setName(QString("%1_%2_seq").arg(tab->getName()).arg(col->getName()));
+        seq->setName(QString("%1_%2_seq").arg(tab->getLowerName()).arg(col->getLowerName()));
         seq->setOwner(tab->getOwner());
         seq->setSchema(tab->getSchema());

@@ -581,7 +581,7 @@ void ModelsDiffHelper::processDiffInfos(void)

     //Reuniting the schema names to inject a SET search_path command
     for(auto &schema : *imported_model->getObjectList(OBJ_SCHEMA))
-      sch_names.push_back(schema->getName(true));
+      sch_names.push_back(schema->getLowerName(true));

     //Separating the base types
     for(ObjectsDiffInfo diff : diff_infos)
@@ -619,7 +619,7 @@ void ModelsDiffHelper::processDiffInfos(void)
         skip_obj=constr->isAddedByGeneralization();

         for(unsigned i=0; i < parent_tab->getAncestorTableCount() && !skip_obj; i++)
-          skip_obj=(parent_tab->getAncestorTable(i)->getConstraint(constr->getName())!=nullptr);
+          skip_obj=(parent_tab->getAncestorTable(i)->getConstraint(constr->getLowerName())!=nullptr);

         if(skip_obj) continue;
       }
@@ -631,7 +631,7 @@ void ModelsDiffHelper::processDiffInfos(void)

         for(unsigned i=0; i < parent_tab->getAncestorTableCount() && !skip_obj; i++)
         {
-          aux_col=parent_tab->getAncestorTable(i)->getColumn(col->getName());
+          aux_col=parent_tab->getAncestorTable(i)->getColumn(col->getLowerName());
           skip_obj=(aux_col && aux_col->getType().getAliasType()==col->getType());
         }

@@ -682,7 +682,7 @@ void ModelsDiffHelper::processDiffInfos(void)
             create_objs[object->getObjectId()]=getCodeDefinition(object, false);

             if(obj_type==OBJ_SCHEMA)
-              sch_names.push_back(object->getName(true));
+              sch_names.push_back(object->getLowerName(true));
           }
         }
       }
@@ -904,7 +904,7 @@ void ModelsDiffHelper::recreateObject(BaseObject *object, vector<BaseObject *> &
            name is the same as the 'object' parent table's name. Sencond, we try to get a child
            object from that table using the same name as the 'object' */
         BaseTable *tab=dynamic_cast<BaseTable *>(imported_model->getObject(tab_obj->getParentTable()->getSignature(), tab_obj->getParentTable()->getObjectType()));
-        aux_obj=tab->getObject(tab_obj->getName(true), tab_obj->getObjectType());
+        aux_obj=tab->getObject(tab_obj->getLowerName(true), tab_obj->getObjectType());
       }
     }

```

**Comment by rkhaotix** [comment]
If you don't mind if Table is the same as table and so on why not use lower
names in your model? In my humble opinion it is your desired behavior is a
bit strange.

The tool reproduces the PostgreSQL feature of quoting object names to
differ them. So if you want camel case in model you'll have camel case in
the database. There is no easy way to change this behavior because the
naming rules are strongly tied to reverse and forward engineering,
validation and diff. A lot of code need to be changed.
Em 02/10/2015 5:24 AM, "okamy" <notifications@github.com> escreveu:

**Comment by okamy** [comment]
Well the best would be that Postgres display Bob if the query is CREATE TABLE Bob, but this is probably harder than tweaking PgModeler.
I don't mind too much how Postgres displays it because most of the time i'll edit the schema trough PgModeler and i'll query it trough an application. But it's important for me in PgModeler because it'd be my main tool for editing the model and rolegroupid is much less pretty (and readable imho) thant RoleGroupID.
I could also change and use a naming convention which would use underscore instead of CamelCase, but i don't like this either.

I'm not asking you to do it, just some advices.

My reading of the code of PgModeler gave me the idea that for the diff, you diff two PgModeler model. The database is inspected at start so you can build the equivalent PgModeler model.
So i'd the feeling that with some tweaking in the model comparison i could remove the case constraint. But i can't figure out exactly where the real comparison is done. I saw that you use the xml, but also the sql generated.

**Comment by rkhaotix** [comment]
>
> Well the best would be that Postgres display Bob if the query is CREATE
> TABLE Bob, but this is probably harder than tweaking PgModeler.
> I don't mind too much how Postgres displays it because most of the time
> i'll edit the schema trough PgModeler and i'll query it trough an
> application. But it's important for me in PgModeler because it'd be my main
> tool for editing the model and rolegroupid is much less pretty (and
> readable imho) thant RoleGroupID.
> I could also change and use a naming convention which would use underscore
> instead of CamelCase, but i don't like this either.
>

I understand your desire! But what I'm trying to explain is that tweaking
pgModeler is hard as well... No so difficult as PostgreSQL but will demand
a considerable effort! :)

> I'm not asking you to do it, just some advices.
>
And I'm not denying some future patch to enable it! :)

> My reading of the code of PgModeler gave me the idea that for the diff,
> you diff two PgModeler model. The database is inspected at start so you can
> build the equivalent PgModeler model.
> So i'd the feeling that with some tweaking in the model comparison i could
> remove the case constraint. But i can't figure out exactly where the real
> comparison is done. I saw that you use the xml, but also the sql generated.
>

This is why I'm telling you that if we change a single portion of the
naming rules may affect a good part of the software, including the diff.
So, at a first glance, in order to ignore the case we need to do two
things.. First remove the quoting from the SQL that is exported to the
database. And second, when diff'ing the model and database, remove the
quotes from names and ignore the case too.. But this step demands a deep
inspection because there are few nuances on how we compare two objects and
it involves compare the xml too.. which demands remove the &quot; entity
from the code .

>

**Comment by okamy** [comment]
I'll give it another on monday. This afternoon was not successfull :-(
If i succeed, i'll let you know.
If i don't, i guess i'll just save the model on a second database and with a command line diff tool and pg_dump i'll be able to generate the diff quite easily.

Anyway, thanks for your answer and for PgModeler. So far it's the best Tools for Postgres modeling, a lot of options and a very nice UI! :-)

**Comment by rkhaotix** [comment]
Thank you for the feedback. May I suggest you one thing? If you succeed in use the CLI tool and pg_dump together why not create a plugin for pgModeler? This way you can help other users too :)

Anyways, I'm glad to see that you enjoyed pgModeler's UI. A lot has to come in future versions! ;)
Best regards!

**Comment by okamy** [comment]
I'll look at the plugin creation. My experience with Qt and c++ is quite old, but i can give it a try
