### ISSUE TITLE
pgmodeler 0.8.2-alpha can not open model

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#762]
mac os x 10.11 el Capitan
I can open only usda.dbm ( it does not have views!)

Other sample models I can not open

when I try open demo.dbm:

12] src/schemaparser.cpp (1083)
  QString SchemaParser::getCodeDefinition(attribs_map &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[11] src/schemaparser.cpp (1408)
  QString SchemaParser::getCodeDefinition(const QString &, attribs_map &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[10] src/schemaparser.cpp (887)
  QString SchemaParser::getCodeDefinition(const QString &, attribs_map &, unsigned int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[9] src/baseobject.cpp (847)
  virtual QString BaseObject::getCodeDefinition(unsigned int, bool)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[8] src/databasemodel.cpp (421)
  void DatabaseModel::__addObject(BaseObject *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[7] src/databasemodel.cpp (1006)
  void DatabaseModel::addView(View *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[6] src/databasemodel.cpp (212)
  void DatabaseModel::addObject(BaseObject *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[5] src/databasemodel.cpp (2959)
  void DatabaseModel::loadModel(const QString &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!
       ** /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm (line: 244)

[4] src/databasemodel.cpp (3016)
  void DatabaseModel::loadModel(const QString &)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!
       ** /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm (line: 244)

[3] src/modelwidget.cpp (1114)
  void ModelWidget::loadModel(const QString &)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[2] src/mainwindow.cpp (815)
  void MainWindow::addModel(const QString &)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[1] src/mainwindow.cpp (834)
  void MainWindow::addModel(const QString &)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[0] src/mainwindow.cpp (1479)
  void MainWindow::showFixMessage(Exception &, const QString &)
    [ERR_MODEL_FILE_NOT_LOADED] Could not load the database model file `/Applications/pgmodeler.app/Contents/MacOS/samples/demo.dbm'. Check the error stack to see details. Try to run `pgmodeler-cli --fix-model' in order to correct the structure of the file if that is the case.

**Comment by rkhaotix** [comment]
Are you building it from source? If so, please, remove all contents from "build" directory and repeat the process. In my Mac OSX installation all is running fine. See screenshot below

![082-alpha-mac](https://cloud.githubusercontent.com/assets/2205476/10291377/d3266218-6b7f-11e5-8ae7-115f146052a7.png)

**Comment by fte1965** [comment]
I am building from source and using macdeploy.sh, it cleaning all?

**Comment by rkhaotix** [comment]
It should. Also, if you have a previous version in /Applications you have
to uninstall it to avoid conflicts
Em 05/10/2015 5:20 PM, "Takhir" <notifications@github.com> escreveu:

**Comment by fte1965** [comment]
Rebuild pgmodeler....
and try start from application folder...
![2015-10-05 23 34 52](https://cloud.githubusercontent.com/assets/3863428/10292840/12ffd7f4-6bba-11e5-8fbc-483f88869707.png)

**Comment by fte1965** [comment]
[11] src/schemaparser.cpp (1083)
  QString SchemaParser::getCodeDefinition(attribs_map &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[10] src/schemaparser.cpp (1408)
  QString SchemaParser::getCodeDefinition(const QString &, attribs_map &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[9] src/schemaparser.cpp (887)
  QString SchemaParser::getCodeDefinition(const QString &, attribs_map &, unsigned int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[8] src/baseobject.cpp (847)
  virtual QString BaseObject::getCodeDefinition(unsigned int, bool)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[7] src/databasemodel.cpp (421)
  void DatabaseModel::__addObject(BaseObject *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[6] src/databasemodel.cpp (1006)
  void DatabaseModel::addView(View *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[5] src/databasemodel.cpp (212)
  void DatabaseModel::addObject(BaseObject *, int)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!

[4] src/databasemodel.cpp (2959)
  void DatabaseModel::loadModel(const QString &)
    [ERR_UNK_ATTRIBUTE] Unknown attribute `declaration' in file /Applications/pgmodeler.app/Contents/MacOS/schemas/sql/view.sch, line 50, column 18!
       ** /Applications/pgmodeler.app/Contents/MacOS/conf/example.dbm (line: 136)

[3] src/databasemodel.cpp (3016)
  void DatabaseModel::loadModel(const QString &)
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/conf/example.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!
       ** /Applications/pgmodeler.app/Contents/MacOS/conf/example.dbm (line: 136)

[2] src/appearanceconfigwidget.cpp (164)
  void AppearanceConfigWidget::loadExampleModel()
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/conf/example.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[1] src/appearanceconfigwidget.cpp (195)
  virtual void AppearanceConfigWidget::loadConfiguration()
    [ERR_LOAD_INV_MODEL_FILE] Could not load file /Applications/pgmodeler.app/Contents/MacOS/conf/example.dbm. The same appears to be inconsistent or one of its dependencies (DTD files) has errors or is missing!

[0] src/configurationform.cpp (114)
  void ConfigurationForm::loadConfiguration()
    [ERR_CONFIG_NOT_LOADED] Unable to load one or more configuration files! Please check if files exists in the configuration folder and if they are not corrupted to preventing this error to occur again on the next startup!

**Comment by fte1965** [comment]
After uninstall previous version in /Applications, everything OK
