### ISSUE TITLE
Diff : Using more than 63 characters in the name

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#763]
Hi,

I'm using 8.2-alpha compiled on Linux from sources.
I try to use the diff tools between the pg_modeler schema and a database, but it stop on this error :

Sorry, the error is in french : 
>[2] src/baseobject.cpp (354)
>  virtual void BaseObject::setName(const QString&)
>    [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le nom!
>
>[1] src/modelsdiffhelper.cpp (107)
>  void ModelsDiffHelper::diffModels()
>    [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le nom!
>
>[0] src/modeldatabasediffform.cpp (550)
>  void ModelDatabaseDiffForm::captureThreadError(Exception)
>    [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le nom!

2 questions : 
1- why this limitations an where ?
2- is it possible to have the name (and object) that is the problem ?

Thank you

**Comment by rkhaotix** [comment]
This limitation is in conformance to PostgreSQL naming rules which deny
names longer than 63 bytes. In order to know exactly where the error is
triggered I need the dump of your database and the model so I can debug it.
Em 06/10/2015 5:26 AM, "rimbault" <notifications@github.com> escreveu:

**Comment by rimbault** [comment]
Raphael,



You will find pgmodeler model and database model atteched.

Thanks





 ---- On mar., 06 oct. 2015 12:17:53 +0200 Raphael Araújo e Silva &lt;notifications@github.com&gt; wrote ----




This limitation is in conformance to PostgreSQL naming rules which deny

 names longer than 63 bytes. In order to know exactly where the error is

 triggered I need the dump of your database and the model so I can debug it.

 Em 06/10/2015 5:26 AM, "rimbault" &lt;notifications@github.com&gt; escreveu:

 

 &gt; Hi,

 &gt;

 &gt; I'm using 8.2-alpha compiled on Linux from sources.

 &gt; I try to use the diff tools between the pg_modeler schema and a database,

 &gt; but it stop on this error :

 &gt;

 &gt; Sorry, the error is in french :

 &gt;

 &gt; [2] src/baseobject.cpp (354)

 &gt; virtual void BaseObject::setName(const QString&amp;)

 &gt; [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le

 &gt; nom!

 &gt;

 &gt; [1] src/modelsdiffhelper.cpp (107)

 &gt; void ModelsDiffHelper::diffModels()

 &gt; [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le

 &gt; nom!

 &gt;

 &gt; [0] src/modeldatabasediffform.cpp (550)

 &gt; void ModelDatabaseDiffForm::captureThreadError(Exception)

 &gt; [ERR_ASG_LONG_NAME_OBJECT] Utilisation de plus de 63 caractères dans le

 &gt; nom!

 &gt;

 &gt; 2 questions :

 &gt; 1- why this limitations an where ?

 &gt; 2- is it possible to have the name (and object) that is the problem ?

 &gt;

 &gt; Thank you

 &gt;

 &gt; —

 &gt; Reply to this email directly or view it on GitHub

 &gt; &lt;https://github.com/pgmodeler/pgmodeler/issues/763&gt;.

 &gt;

**Comment by rkhaotix** [comment]
@rimbault Please, send me a direct e-mail. Do not use github because it will remove any attachment. Thanks.

**Comment by rkhaotix** [comment]
@rimbault you can test the patch using the "develop" branch. I've tested the model you've sent and all worked fine. The problem was a sequence that was being generated with a extensive name ( > 63 bytes) and the name wasn't truncated.

**Comment by rimbault** [comment]
Great !!!
I will test it as soon as possible.
