### ISSUE TITLE
SUPERUSER role does not allow for LOGIN option

### ISSUE THREAD

**Issue by selimt** [pgmodeler/pgmodeler#764]
If a role is created and set as SUPERUSER, the generated SQL users the "CREATE ROLE" syntax but there is no way to specify the login option when the "Superuser" checkbox is checked (Can login checkbox is disabled).

This results in a role that doesn't have the login privileges.

**Comment by rkhaotix** [comment]
According to PostgreSQL docs:

SUPERUSER
NOSUPERUSER

These clauses determine whether the new role is a"superuser", who can
override all access restrictions within the database. Superuser status is
dangerous and should be used only when really needed. You must yourself be
a superuser to create a new superuser. If not specified,NOSUPERUSER is the
default

So, in my understanding it is sufficient to specify a password and the
option SUPERUSER if you intend to create an fully privileged role that is
able to login into a server.
Em 07/10/2015 6:16 PM, "selimt" <notifications@github.com> escreveu:

**Comment by selimt** [comment]
Hi, are you using Postgres 9 or later? According to the docs:

CREATE USER is now an alias for CREATE ROLE. The only difference is that when the command is spelled CREATE USER, LOGIN is assumed by default, whereas NOLOGIN is assumed when the command is spelled CREATE ROLE.

Since pgmodeler creates the "CREATE ROLE" SQL and doesn't specify the LOGIN option explicitly, I am not able to login with this user.

**Comment by rkhaotix** [comment]
I'm using 9x. You're right. I'll fix that!
Thanks
Em 07/10/2015 6:52 PM, "selimt" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
Done! You can test the patch in "develop" branch.

**Comment by selimt** [comment]
Thanks for the quick fix!

**Comment by rkhaotix** [comment]
You're welcome. Actually I have changed the wrong behavior that was
unchecking other options when Superuser was checked. It should work now.
Em 07/10/2015 8:10 PM, "selimt" <notifications@github.com> escreveu:
