### ISSUE TITLE
How to drop role before creating it?

### ISSUE THREAD

**Issue by oliversalzburg** [pgmodeler/pgmodeler#765]
I see a commented `DROP ROLE` comment in the exported SQL. How can I have it as an actual command?

**Comment by rkhaotix** [comment]
Use the "Drop objects " in export dialog
Em 12/10/2015 10:08 AM, "Oliver Salzburg" <notifications@github.com>
escreveu:

**Comment by oliversalzburg** [comment]
That option is disabled for SQL file export (which is what we use).

**Comment by rkhaotix** [comment]
This option is available only in export do dbms only. You can prepend a
drop command to the desired object. See "custom sql " in role editing form
Em 12/10/2015 10:10 AM, "Oliver Salzburg" <notifications@github.com>
escreveu:

**Comment by oliversalzburg** [comment]
Ah, alright. Thanks for the quick support :)

**Comment by rkhaotix** [comment]
You're welcome!   :)
Em 12/10/2015 10:14 AM, "Oliver Salzburg" <notifications@github.com>
escreveu:
