### ISSUE TITLE
Freeze/hard shutdown filled file with null characters [NUL]

### ISSUE THREAD

**Issue by donnorman** [pgmodeler/pgmodeler#766]
Hello,

I had a model open in version 0.7.2 build 20140628 when my computer decided to freeze and I had to perform a hard shutdown in order to resolve it.

After restarting the system, the program wouldn't open the model- stating that it was corrupted and to use the fix model feature.  I tried to use the fix model button, but then it said that the file was not recognized.  So I opened the file up in a normal text editor and it was filled with [NUL][NUL][NUL][NUL], etc for the entire 211KB contents of the file.

Luckily I had a relatively fresh backup and I didn't lose anything that wasn't quickly replaced.

I just figured that I would report what happened in case you would like to dig deeper.  I did have the file saved before the freeze/hard shutdown.

Thanks!

-Don

**Comment by rkhaotix** [comment]
Wow! That's kinda strange! Why the hack the file was filled with [NUL]? :/ 
Anyway thanks for reporting this issue! Despite all mechanisms available to avoid data loss none of them are perfect so a old and good backup is always welcome! :)

**Comment by donnorman** [comment]
Oh I only just wrote it as [NUL], that's how it appeared in my text editor.  They're actual NULL characters, or 00s if looking in a hex editor.

![nulls](https://cloud.githubusercontent.com/assets/4530709/10465230/b9aac512-71bb-11e5-9cbb-c84d1f6c67eb.PNG)

![null hex](https://cloud.githubusercontent.com/assets/4530709/10465266/f343fbcc-71bb-11e5-98ca-932ff8baf21a.PNG)

Yeah, totally bizarre that happened, and very happy I had a backup, haha.
