### ISSUE TITLE
permissions on new table

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#768]
Hi,

When I create a new table, I can't set permissions because the table does not exist yet :
>The object grant_8dab15e5b1 (Table) is referencing the object new_table (Table) which was not found in the model!

We need to create the table (apply) and then edit it to create permissions.
Perhaps, you could hide or disable the permission button unless the table exists ?

**Comment by rkhaotix** [comment]
Actually we have a regression here. The behavior was keep the permission
button disabled until user click apply. I'll fix that! Thanks
Em 20/10/2015 7:32 AM, "rimbault" <notifications@github.com> escreveu:
