### ISSUE TITLE
Unable to import all PostGIS operator classes

### ISSUE THREAD

**Issue by FxKu** [pgmodeler/pgmodeler#770]
Hey,

I got problems when importing the PostGIS extension to a pgModeler project with version 8.0. I need the operator class gist_geometry_ops_2d and gist_geometry_ops_nd for gist index, but especially these once can not be imported. At first the import process runs very fast until it gets very slow ends after several minutes.

Any idea what could be the reason? A corrupted installation maybe? For import I choose the options "Import extension objects" and "Ignore import errors". Do I have to import system objects as well? Am I not allowed to uncheck anything before starting the process?

I wish I could send you the log file, but my pgModeler is missing a tmp directory. I've created the folder myself but nothing is written to it.

Next, I would merge the file manually with this one: https://github.com/3dcitydb/3dcitydb/tree/master/PostgreSQL/pgModeler. Fortunately this works easily.

Best wishes and keep up the good work.
Felix

**Comment by rkhaotix** [comment]
Hi Felix.

I suspect that the slowdowns are due to the amount of objects being
imported. What I can suggest is to create fake objects with the name of the
ones you need. Or you can try to import extension and system objects to see
the results.

The reverse engineering is constantly improved but sometimes can fail. But
I'll investigate this issue. Thanks
Em 22/10/2015 10:14 AM, "Felix Kunde" <notifications@github.com> escreveu:

**Comment by FxKu** [comment]
Faking the objects was my first plan ;) 
Because in the end I only wanted to have the correct string for the index in the SQL output.

CREATE INDEX some_spatial_index_spx ON public.table
	USING gist
	(
	  some_spatial_column *gist_geometry_ops_nd*
	);

For setting the operator class for an index in pgModeler I need a defined operator class. For that I need operators. For operators I need functions. Too much too fake ;) 

I'll continue trying with different setting and will let you know if one worked out for me.

**Comment by FxKu** [comment]
Ok, I tried to work with the objects that passed the import. Turned out that I could use all the operators which would make faking the missing operator classes more easy. Unfortunately, I'm not allowed to add operators for index classes other than btree :,-(

Sooo close.

![pgmodeler_error_opclass](https://cloud.githubusercontent.com/assets/5940260/10668180/5e0f27d0-78db-11e5-8bb6-7dc6acd8365e.png)

![pgmodeler_error_btree](https://cloud.githubusercontent.com/assets/5940260/10668184/62901288-78db-11e5-9853-d080e75a9f41.png)

**Comment by rkhaotix** [comment]
Hmmmm. That was close!  :(
I strictly follow the PostgreSQL docs. So the error is raised because some
rules were broken. It was a long time ago when I created these forms but if
there are some bug I can fix. I'm not a PostgreSQL specialist so any help
related to rules is welcome!  :)
Em 22/10/2015 12:39 PM, "Felix Kunde" <notifications@github.com> escreveu:

**Comment by FxKu** [comment]
Probably long ago, but where have you found this rule? Here? http://www.postgresql.org/docs/8.0/static/xindex.html (says something about "B-tree operator classes only", but its only till pg8.2)

I also looked up this page: http://www.postgresql.org/docs/9.4/static/sql-createopclass.html

**Comment by rkhaotix** [comment]
It may be that. PgModeler supported PostgreSQL 8.X until release 0.5.x (if
my memory serves). The support was dropped after that version and probably
some features or restrictions of 8.x are still there. I'll take a look!
Em 22/10/2015 12:55 PM, "Felix Kunde" <notifications@github.com> escreveu:

**Comment by FxKu** [comment]
Maybe the rule was also the reason the operator classes were not imported during reverse engeneering.

Thanks for having a look!

**Comment by rkhaotix** [comment]
Exactly! You're able to compile pgModeler?
I'll try to fix this later today.
Em 22/10/2015 1:13 PM, "Felix Kunde" <notifications@github.com> escreveu:

**Comment by FxKu** [comment]
No, I have always used the packed installer. I can also wait for the next release. It's not urgent.

**Comment by rkhaotix** [comment]
@FxKu Actually, taking a deep look into pgModeler's code and PostgreSQL docs (specially the ones related to 9.x) the operator family in question (associated to the operator class element) needs to have a "btree" op. family if you intend to use the "FOR ORDER BY" option. 

See **sort_family_name** in the last link you've sent! In your case I think you can let that field empty so you can create the operator class.

**Comment by FxKu** [comment]
Thanks for the hint. I was able to create operator classes. Yay! But for some reason pgModeler still doesn't like them. When I want to reopen my DBM file pgModeler crashes when he gets to my customized operator classes. I can send you my DBM file for debugging, if that would be ok for you?

**Comment by rkhaotix** [comment]
Yes. Send the file, please . I can easily debug the software to find where
it crashes.
Em 23/10/2015 1:29 PM, "Felix Kunde" <notifications@github.com> escreveu:

**Comment by rkhaotix** [comment]
Hi!

Received your file. The strange thing is that it can be perfectly loaded in Linux version when it comes to Windows it crashes almost in the end of loading. I'm debugging it in Windows to see what is happening! Thanks!
