### ISSUE TITLE
Crash after 100% Creating table inheritances....

### ISSUE THREAD

**Issue by narguedasn** [pgmodeler/pgmodeler#771]
I have tried loading the db several times. I have selected only an independent section of the db.

 It crashes when achieving 100% of 'Creating table inheritances...' 
![crash report1](https://cloud.githubusercontent.com/assets/7024739/10703721/fc24a67e-799f-11e5-89ff-e2cba5b9e3eb.jpg)

**Comment by rkhaotix** [comment]
I need a dump of your database in order to debug the reverse engineering
process.
Em 23/10/2015 6:06 PM, "narguedasn" <notifications@github.com> escreveu:

**Comment by narguedasn** [comment]
Hi Raphael. Thanks for your quick answer. I'm out of the office until Monday, I'll work on the dump then.

Nidia

[http://sig.cmparks.net/cmp-ms-90x122.png] Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com<http://www.clemetparks.com>



________________________________

**Comment by narguedasn** [comment]
Hello again

Dump is attached

N

[http://sig.cmparks.net/cmp-ms-90x122.png] Nidia Arguedas, PhD
Conservation Planner
Phone: 216-635-3292
Fax: 216-635-3286
na@clevelandmetroparks.com<http://www.clemetparks.com>



________________________________

**Comment by rkhaotix** [comment]
Please, send the dump directly to my email. GitHub removes any attachments
from emails.
Em 26/10/2015 11:35, "narguedasn" <notifications@github.com> escreveu:
