### ISSUE TITLE
Unable to edit many to many relation's table

### ISSUE THREAD

**Issue by ziadloo** [pgmodeler/pgmodeler#774]
Consider a "many to many" relationship, double click on it so the `Create / Edit: Relationship` form is open. Now go to the `Advanced` tab and double click on the table's name. Now you should be seeing `Create / Edit: Table` form for the association table of the n-n relation.

The problem is that the `Apply` button is never enabled in the last form and changes I make are not applied. I wanted to change the schema for the association table but I couldn't.

I'm using pgModeler 0.8.2-alpha, build 20151102.

Thanks.

**Comment by rkhaotix** [comment]
Try right click the "many-to-many" relationship  and click "Convert". This will transform the relationship into an intermediate table in which is possible to edit properties.

**Comment by ziadloo** [comment]
That will sure do for now, but perhaps you would like to put this in your future road map!? I mean the reason why I choose to use a `many to many` relationship to begin with, is to have a cleaner diagram. Otherwise having such a relationship is not a must and I could implement it with an association table manually.

Thanks for your reply and your magnificent software.

**Comment by rkhaotix** [comment]
The steps I provided is only a workaround to that limitation but also serves as an advanced tool to modify other attributes of the generated table. But I agree! I'll add the ability to set schema, tablespace, and owner for many-to-many relationships, I mean, the intermediate table.

**Comment by rkhaotix** [comment]
Oh, I forgot to mention one more thing... I don't know if it was your intention but the intermediate table will use the same schema as the first clicked table during the relationship creation. For instance: if you have ```schemaA.tableA``` and ```schemaB.tableB``` and click ```tableB``` the schema of the generated table will be ```schemaB``` not ```schemaA``` nor ```public``` (the default schema).

**Comment by ziadloo** [comment]
That's good to know, thanks. But unfortunately my intermediate table should belong to a `schemaC` :)

Yet I'm really grateful for your effort to help me :+1:

**Comment by christiaanwesterbeek** [comment]
I suppose no way yet to define the owner of the many-to-many table?

**Comment by rokkie** [comment]
I'm running onto the same issue, I can't set the permissions for the n:n table.
