### ISSUE TITLE
Cannot export partial model

### ISSUE THREAD

**Issue by antoine-pous** [pgmodeler/pgmodeler#775]
Currently i work on big project and i don't find any way in pgmodeler to export only what i want.

It would be cool to select only Schema, Tables, Roles we want export.

**Comment by rkhaotix** [comment]
pgModeler does not supports partial exports. I'll tag this issue as feature request and try to implement it in the development of release 0.9.0

**Comment by rkhaotix** [comment]
One more thing, which kind of export you're talking about: directly to dbms, as png image or sql script?

**Comment by Antoine-Pous** [comment]
Directly to DBMS.

**Comment by rkhaotix** [comment]
Ok. I'll study a way to enable that. Thanks for suggesting.
