### ISSUE TITLE
pgmodeler not starting on OSx 10.11.7

### ISSUE THREAD

**Issue by Pulsar2011** [pgmodeler/pgmodeler#779]
I just build and install successfully pgmodeler v.0.8.2.alpha1 with success. Unfortunately, the application wan't start and it give me the following error :

> Process:               pgmodeler [25041]
> Path:                  /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
> Identifier:            br.com.pgmodeler.pgModeler
> Version:               ???
> Code Type:             X86-64 (Native)
> Parent Process:        ??? [1]
> Responsible:           pgmodeler [25041]
> User ID:               501
> 
> Date/Time:             2015-12-14 10:43:26.429 +0100
> OS Version:            Mac OS X 10.11.2 (15C50)
> Report Version:        11
> Anonymous UUID:        F764DBE3-5815-7B08-3AB5-B2DC33B0C5B8
> 
> Sleep/Wake UUID:       7AE5BBE6-C499-4E66-AA92-E54FBCD145FB
> 
> Time Awake Since Boot: 34000 seconds
> Time Since Wake:       7800 seconds
> 
> System Integrity Protection: enabled
> 
> Crashed Thread:        0
> 
> Exception Type:        EXC_BREAKPOINT (SIGTRAP)
> Exception Codes:       0x0000000000000002, 0x0000000000000000
> Exception Note:        EXC_CORPSE_NOTIFY
> 
> Application Specific Information:
> dyld: launch, loading dependent libraries
> 
> Dyld Error Message:
>  Library not loaded: libpgmodeler_ui.1.dylib
>  Referenced from: /Applications/pgmodeler.app/Contents/MacOS/pgmodeler
>  Reason: image not found
> [...]

The application isn't able to locate the `*.dylib` files which are properly copied into the directory `/Applications/pgmodeler/Contents/Frameworks` at installation times.

If I properly set the `DYLD_LIBRARY_PATH` and `PATH` environment variables in my `.cshrc` files, the application is running if I start it from shell, but not if I double-click on its icon (as double-click on the icon does not load the environment variable I set in my `.cshrc`).

**Comment by rkhaotix** [comment]
Take a look here
https://github.com/pgmodeler/pgmodeler/issues/750
Em 14/12/2015 07:51, "Pulsar2011" <notifications@github.com> escreveu:

**Comment by Pulsar2011** [comment]
Yes, I also follow this instruction but, with the command `macdeployqt`, nothing happen : The application did not start and no error messages are displayed.

**Comment by rob-miller** [comment]
I have this problem on OS X 10.11.6 (15G31).  I found that Homebrew's current Qt5 is 5.6.1-1.  By changing the symlink back to the previous version (/usr/local/opt/qt5 -> ../Cellar/qt5/5.6.0) and running `brew linkapps qt5` I find that I can build an executable that runs.

**Comment by lumieru** [comment]
Uncomment the following line in pgmodeler.pri:
`  # Specifies where to find the libraries at runtime`
`  #QMAKE_RPATHDIR += @executable_path/../Frameworks`

And also add the following line to pgmodeler.pri:
`QMAKE_LFLAGS_SONAME = -Wl,-install_name,@rpath/`
