### ISSUE TITLE
Redshift support

### ISSUE THREAD

**Issue by dbecar** [pgmodeler/pgmodeler#780]
Would it be possible to add support for modelling Amazon Redshift database schemas in pgmodeler? Could this be implemented as a new plugin?

Features that need to be implemented:
Ability to generate Redshift models, export them to a SQL file and to reverse engineer from a Redshift database connection.
Ability to assign compression types to columns.
Ability to assign data distribution style (EVEN, KEY, or ALL) to a table.
Ability to set sort key (INTERLEAVED or COMPOUND) for each table.

More info: http://docs.aws.amazon.com/redshift/latest/dg/t_Creating_tables.html

**Comment by jprando** [comment]
I'm interested, too
