### ISSUE TITLE
Plugin directory requires write permission

### ISSUE THREAD

**Issue by Hubbitus** [pgmodeler/pgmodeler#783]
8d1e180 build just on start I got warning:
```
Unable to write the file or directory /usr/lib64/pgmodeler/plugins! Make sure the output directory exists, or if the user has write permissions over it!
```

Is it really needed and why? Or how I can disable such check and message?

**Comment by rkhaotix** [comment]
pgmodeler will create the plug-ins folder in the first startup. To avoid
this message in case of pre compiled packages just create it during the
packaging process.
Em 02/01/2016 17:25, "Pavel Alexeev aka Pahan-Hubbitus" <
notifications@github.com> escreveu:

**Comment by Hubbitus** [comment]
Thank you very much. It solve problem.
