### ISSUE TITLE
Automatic primary key/foreign key names

### ISSUE THREAD

**Issue by pinaraf** [pgmodeler/pgmodeler#785]
Hello

When adding a primary key, it would be nice if pgModeler could automatically name it <column>_pkey for single-column pkey… or even better, follow the postgresql automatic naming convention for every optional name.
Thanks for this great tool :+1:

**Comment by rkhaotix** [comment]
Hi @pinaraf 

I'm already studying to add this feature into the next major release 0.9.0! :)

You're welcome!
