### ISSUE TITLE
Model objects search dialog should be keyboard usable

### ISSUE THREAD

**Issue by pinaraf** [pgmodeler/pgmodeler#787]
Hi

When for instance adding a foreign key, the model objects dialog appears to select the target table. It is possible to filter, but even when there is only one item left in the list, pressing enter does not select it and close the dialog, giving the user two choices : pressing tab several times to focus the object list, select the found item and press enter, or select the item with the mouse.
Since filtering will often lead to one result in a few keystrokes, it would be a huge usability improvement to complete that step with no mouse interaction.

**Comment by rkhaotix** [comment]
If you are able to compile the software.. please check if the change done is what you need! :)
Anyway thanks for reporting this issue!

**Comment by pinaraf** [comment]
Indeed, far better that way, thanks a lot
