### ISSUE TITLE
compile error develop branch

### ISSUE THREAD

**Issue by hdus** [pgmodeler/pgmodeler#796]
I try to compile the develop branch but I get the following error:

usr/bin/ld: obj/crashhandlerform.o: undefined reference to symbol '__cxa_free_exception@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by hdus** [comment]
My system: Ubuntu 14.04

**Comment by israelins85** [comment]
According with: https://codeyarns.com/2014/05/02/undefined-reference-error-with-__cxa_free_exceptioncxxabi_1-3/

You can solve this doing:
Edit the file pgmodeler.pri and add look for:

# Linux custom variables settings
linux {

Add inside de linux {...}

  LIBS += -lstdc++

And then try compile again.
