### ISSUE TITLE
error: cannot find -lutils

### ISSUE THREAD

**Issue by Blacktoviche** [pgmodeler/pgmodeler#797]
I'm trying to build pgmodeler (pgmodeler-0.8.1) on 
(Windows 7 64) using (QT 5.0.2 with mingw47_32-x86)

$mingw32-make produced error

c:/qt/qt5.0.2/tools/mingw/bin/../lib/gcc/i686-w64-mingw32/4.7.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lutils
collect2.exe: error: ld returned 1 exit status
Makefile.Debug:81: recipe for target '....\pgmodeler-0.8.1\libparsers\parsers.dll' failed
mingw32-make[2]: **\* [....\pgmodeler-0.8.1\libparsers\parsers.dll] Error 1
17:19:47: The process "C:\Qt\Qt5.0.2\Tools\MinGW\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project pgmodeler (kit: Desktop Qt 5.0.2 MinGW 32bit)
When executing step 'Make'
17:19:47: Elapsed time: 00:30.

**Comment by Chocanto** [comment]
Exactly same error here under Windows 7.

Maybe a problem with .pri files, linking utils under source directory and parser searching utils library under build directory ?

**Comment by Renatov** [comment]
Exactly same error here under Windows 10 

Makefile.Release:70: recipe for target 'parsers.dll' failed
mingw32-make[2]: *** [parsers.dll] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/H-P/pgmodeler/libparsers'
Makefile:34: recipe for target 'release' failed
mingw32-make[1]: *** [release] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/H-P/pgmodeler/libparsers'
Makefile:89: recipe for target 'sub-libparsers-make_first-ordered' failed
mingw32-make: *** [sub-libparsers-make_first-ordered] Error 2

please help

**Comment by atlight** [comment]
The solution seems to be to  `cd` into the root directory of pgModeler.

**Comment by ramonhoyo** [comment]
I'm trying of compile from Qt IDE for debug, but I'm facing the same problem. 
C:/Qt/Qt5.9.1/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lutils

Any one has solve this problem ?

**Comment by Maxzor** [comment]
> The solution seems to be to `cd` into the root directory of pgModeler.

I don't think this is an answer?
I have the same problem when trying to compile on windows with qtcreator and msys2/mingw64 packages. However I had no problem compiling with bare mingw64...
Maybe @Chocanto is on the right track, with -lutils alias referring to the out_pwd qt variables?
