### ISSUE TITLE
How to define a column with datatype citext

### ISSUE THREAD

**Issue by cedricdo** [pgmodeler/pgmodeler#799]
Hi,

Is there any way to use citext as a datatype for column ? 
http://www.postgresql.org/docs/9.5/static/citext.html
I've added the extension citext in pgmodeler, but i can't find the type anywhere when i setup a table.

Thanks

**Comment by shilch** [comment]
+1

**Comment by MikaAK** [comment]
I still can't figure this out. Was there a solution @cedricdo @rkhaotix

**Comment by landedexperts** [comment]
Reopening this issue.
Using `v0.9.2-alpha1` on Windows10, have added `citext` as an extension, but can't use the type `citext`.

The type `citext` does not show in the dropdown, if typed by hand the type is rejected.
Tried saving, reopening the dbm file, also tried added `citext` in schema `public`, tried added `citext` in the same schema as the table which uses `citext`, problem still shows.

Is there a certain manip to make?

**Comment by rkhaotix** [comment]
First, create an extension named ```citext``` checking the option ```Handles data type```
https://pgmodeler.io/support/docs/317-extensions

After creating that object a new data type named ```citext``` will be available in the data type configuration widget.

**Comment by landedexperts** [comment]
Thanks for your fast response.
`Handles data type` is grayed out and cannot be checked.

**Comment by landedexperts** [comment]
Took a screen capture:
![bug_pgmodeler_citext](https://user-images.githubusercontent.com/32337870/54851252-89b2f680-4ca6-11e9-938b-7ddc7cc8d10f.jpg)

**Comment by landedexperts** [comment]
Is there anything to do in order to make possible to check the checkbox `Handle data type`?

**Comment by landedexperts** [comment]
OK. Now the checkbox is enabled, and `citext` works. I have no idea why the checkbox suddenly is enabled, but it works, and the original problem is solved.
