### ISSUE TITLE
Add support for dark themes

### ISSUE THREAD

**Issue by txtsd** [pgmodeler/pgmodeler#801]
Various elements are hardcoded to be light themed at the moment.

**Comment by linux0uid** [comment]
I have the same problem with dark theme in v0.8.2-beta
![pgmodeler_dark](https://cloud.githubusercontent.com/assets/4116796/13201602/7c7a3984-d881-11e5-9032-c99459f3d762.png)

**Comment by rkhaotix** [comment]
There's a work in progress... Until the final release of 0.8.2 this issue is fixed.

![pgmodeler_dark_theme](https://cloud.githubusercontent.com/assets/2205476/13206936/924d61c2-d8e6-11e5-8ab4-ad623153c1ef.png)

**Comment by rkhaotix** [comment]
@IsaakGroepT You can change the files xml-highlight.conf and sql-highlight.conf files on pgModeler's installation or on ~/.config/pgmodeler and change the colors of the text to temporarily solve the issue you're having.

Currently, this is a limitation of the tool and I'm still need to think on the best solution for it.
