### ISSUE TITLE
Design Editor: Boxes and captions covering each other

### ISSUE THREAD

**Issue by bebr42** [pgmodeler/pgmodeler#804]
The design editor seems to apply some automatic algorithm to avoid the covering of DB objects, relations and captions. In some cases this effects just the opposite of its purpose. 
For example, moving a table object left, in order to make the caption of a right-hand relation readable > Pgmodeler moves the anchor to the left, where the caption is now again covered by the table.
A simple solution might be a switch to turn off the automatic movement of relation anchors.

**Comment by kb3ien** [comment]
BUMP. 

Agreed, either end of the relationship should have 'force left' 'force right' or 'auto'  with auto being the current behaviour.
