### ISSUE TITLE
Feature request: Diff for tables in model only

### ISSUE THREAD

**Issue by manuel-ch** [pgmodeler/pgmodeler#806]
To extend an existing application, i only want to import and model certain tables from the database. 

After editing these tables in pgModeler, i'd like to generate the SQL statements with the diff function. Now lots of drop statements are generated to make the database be equal to the model. I have to delete these drop Statements manually which takes time and is dangerous.

Solution propositions:
a) remember the objects not imported during import and ignore these when it comes to diff against the database
b) a switch in the diff dialog to turn off dropping objects not existing in the model

**Comment by rkhaotix** [comment]
Hi @manuel-ch 

This is a good idea!
I have some thoughts on how to solve this issue and I'll try to make it available in 0.8.2!

Thanks!

**Comment by rkhaotix** [comment]
I made a small tweak in the code. Made some local tests with a small database and it worked as expected. Are you able to compile pgModeler? If so, try the code in branch ```diff-partial-model``` commit d152d1b2c4a8d12f7499fc131c0b5a835cfc9bd6
