### ISSUE TITLE
create operator family

### ISSUE THREAD

**Issue by fte1965** [pgmodeler/pgmodeler#807]
I can not create two operator family

CREATE OPERATOR FAMILY pg_catalog.text_pattern_ops USING btree;
CREATE OPERATOR FAMILY pg_catalog.text_pattern_ops USING hash;

pgmodeler say "text_pattern_ops already exists", but however, in pg_catalog on server there are two families of operators

**Comment by fte1965** [comment]
actually my goal to use the standard class of operators for example:
CREATE INDEX ix2_t_fits ON area_no USING btree (lower(area_no) **varchar_pattern_ops**);
and for that I need to define all operator functions, create all operators,create operator class,create operator family, in addition disable all sql-code, it is very difficult, of course, I can use custom sql, but on the picture of the table no notation that is used, thus hides very important information

**Comment by rkhaotix** [comment]
Confirmed the bug.
I started to construct a patch and the last  commit is https://github.com/pgmodeler/pgmodeler/commit/10197024db3737bbca46c4f75759ab9f7c13dc1b

There were some important changes, so it is quite sure that your model file will be broken. So, until I create automatic fixes in the CLI you'll have to do the following in your file:

1) Replace the attribute ```name``` by ```signature``` in any reference to operator family inside ```<opclass>``` tag. 

2) Now operator families are referenced by signature. Signature for operator families are the union of their names the keyword ```USING``` and the index access mode ```btree```, ```hash``` etc. Thus, for the operator family ```schema.op_family``` that uses ```btree``` its signature will be: ```schema.op_family USING btree```. Be sure to put only one space between the elements.

Assuming that we have the following operator class:

```
<opclass name="opclass" index-type="btree" default="false">
	<schema name="public"/>
	<role name="postgres"/>
	<opfamily signature="public.opfamily"/>
	<type name="smallint"/>
	<element type="storage">
		<type name="smallint"/>
	</element>
	<element type="operator" stg-number="1">
		<operator  signature="public.+-+*(smallint,smallint)"/>
	        <opfamily signature="public.opfamily"/>
	</element>
</opclass>
```

After done all the mentioned changes the resulting XML should be:

```
<opclass name="opclass" index-type="btree" default="false">
	<schema name="public"/>
	<role name="postgres"/>
	<opfamily signature="public.opfamily USING btree"/>
	<type name="smallint"/>
	<element type="storage">
		<type name="smallint"/>
	</element>
	<element type="operator" stg-number="1">
		<operator  signature="public.+-+*(smallint,smallint)"/>
	<opfamily signature="public.opfamily USING btree"/>
	</element>
</opclass>
```

**Comment by fte1965** [comment]
For Operator class you need to do the same

CREATE OPERATOR CLASS text_pattern_ops
   FOR TYPE text USING **btree** AS
   OPERATOR 1  ~<~,
   OPERATOR 2  ~<=~,
   OPERATOR 3  =,
   OPERATOR 4  ~>=~,
   OPERATOR 5  ~>~,
   FUNCTION 1  bttext_pattern_cmp(text, text);

CREATE OPERATOR CLASS text_pattern_ops
   FOR TYPE text USING **hash** AS
   OPERATOR 1  =,
   FUNCTION 1  hashtext(text);

**Comment by rkhaotix** [comment]
Done that too! Try this commit https://github.com/pgmodeler/pgmodeler/commit/e9f14520b40d6eff9c460f60f3ea817ca873c617
