### ISSUE TITLE
Option for bezier curves in the future?

### ISSUE THREAD

**Issue by shanemgrey** [pgmodeler/pgmodeler#810]
I just bought the compiled binary for OSX and am very impressed by the level of detail, quality of presentation, and quantity of features.  For a FOSS project, this is pretty incredible! 

One feature request I have immediately is for offering the option of bezier curves for the relationship connections.  Curves offer better visual separation of the lines between objects because the shapes are distinct compared to lines which can blend together visually when many run parallel.

Related to offering curves for connectors, it would be convenient if there were an "Auto Arrange" button that would attempt to find the best presentation of the objects, still allowing manual adjustment after.  yEd has good examples of various methods.

I've been looking for a great open source project for modeling my schemas for a while, and was thrilled when I found this.

**Comment by rkhaotix** [comment]
@shanemgrey ,

First, thank you so much in supporting the project by purchasing a binary package as well giving your feedback here in GitHub.

Your idea about bezier curves sounds  very well! I'll do some tests and see if I can implement them in future releases ok? About the "Auto arrange" feature, it is already scheduled to the release 0.9.0. I think that in March or April I'll open the development line of that version. :)

I hope you keep enjoying pgModeler!
You can count on me for additional support!

Thanks again!

**Comment by shanemgrey** [comment]
Great to hear about the Auto Arrange.  I imagine that's a hard problem to solve.  

Glad you like the idea of adding curves to the relationship lines.  

Thanks for the fast response.  :-)
