### ISSUE TITLE
hstore precision in the saved model (XML)

### ISSUE THREAD

**Issue by RoyalSens** [pgmodeler/pgmodeler#814]
When a database model is saved with hstore column, it automatically adds a precision property to the XML output:
&lt;column name="column1"&gt;
		&lt;type name="public.hstore" **precision="2684804"**/&gt;
&lt;/column&gt;

This is not something PostgreSQL needs, so I think this should be skipped. It also seems that this is some kind of random number, as it will change that value when I re-open the model, change something else and want to save it again. This leads to my 'problem' that the diff between the two files has lots of changes, that are not really changes. 

It could maybe be fixed by changing basetype.sch. However, I don't know the syntax.

**Comment by rkhaotix** [comment]
It can't just be fixed by changing basetype.sch. The problem was in the initialization of PgSQLType class. I've fixed it and it is available for tests in this commit: 9fb606becf9c66c543deafe2f4ebae06e286df5b

**Comment by RoyalSens** [comment]
I have tested the fix by compiling the commit you specified. And it works perfectly! Thanks.
