### ISSUE TITLE
could not create geometry column

### ISSUE THREAD

**Issue by felixfkrull** [pgmodeler/pgmodeler#815]
Hi,
i tried to validate a simple table design created with a pgmodeler-0.8.1-demo.
the connection to a 9.4 versioned database with postgis enabled succeded.
I can also create the table via pgadmin without any errors.

The last message in the validation process looks like this: 

Could not execute the SQL command.
 Message returned: 'FEHLER:  Typ „geometry“ existiert nicht
LINE 2:  mycolumn geometry(POINT)'

In the Manage-View (with Extension checkbox enabled) in the tree-view the geometry type is listed under _dbname _-> schema -> public -> type

What am I doing wrong?

![issue](https://cloud.githubusercontent.com/assets/11665806/13469087/164da70e-e0a6-11e5-8b05-23be4191d068.jpg)

![issue2](https://cloud.githubusercontent.com/assets/11665806/13469154/4e46ac28-e0a6-11e5-8290-bb39e2560f87.jpg)

**Comment by rkhaotix** [comment]
You have to create an extension object in your model called "postgis". 
Despite the postgis types being available, pgModeler can't create automatically the extension.

**Comment by felixfkrull** [comment]
SURE!
The validation creates a new DB on the server und this new DB does not know anything about my wishes to use postgis. so i have to enable the extension first.
Am i right that the Handles data type checkbox must be enabled for the postgis extension creation?

Thanks for the quick reply!
