### ISSUE TITLE
Cannot export to PNG when the dst PNG file size over 6.3Mb

### ISSUE THREAD

**Issue by aceBeta** [pgmodeler/pgmodeler#816]
v0.8.2-beta

Cannot export to PNG when the dst file size over 6.3Mb.
Can set export png filesize at setting window?

normally exported when the file size less then 6.29Mb

**Comment by aceBeta** [comment]
Exporting PNG Image to the same folder.
OP1:  export --> PNG image --> Zoom 125%  --> successed (OK)
OP2:  export --> PNG image --> Zoom 175%  --> failed  (NG)

the error detail from version 0.8.2-beta1 is below

[3] src\modelexporthelper.cpp (184)
  void ModelExportHelper::exportToPNG(ObjectsScene*, const QString&, double, bool, bool, bool, QGraphicsView*)
    [ERR_FILE_DIR_NOT_WRITTEN] Unable to write the file or directory `/Subversion/Link-Talent/trunk/42_DBDesign/Link-Talent.png'! Make sure the output directory exists, or if the user has write permissions over it!

[2] src\modelexporthelper.cpp (205)
  void ModelExportHelper::exportToPNG(ObjectsScene*, const QString&, double, bool, bool, bool, QGraphicsView*)
    [ERR_FILE_DIR_NOT_WRITTEN] Unable to write the file or directory `/Subversion/Link-Talent/trunk/42_DBDesign/Link-Talent.png'! Make sure the output directory exists, or if the user has write permissions over it!

[1] src\modelexporthelper.cpp (987)
  void ModelExportHelper::exportToPNG()
    [ERR_FILE_DIR_NOT_WRITTEN] Unable to write the file or directory `/Subversion/Link-Talent/trunk/42_DBDesign/Link-Talent.png'! Make sure the output directory exists, or if the user has write permissions over it!

[0] src\modelexportform.cpp (271)
  void ModelExportForm::captureThreadError(Exception)
    [ERR_FILE_DIR_NOT_WRITTEN] Unable to write the file or directory `/Subversion/Link-Talent/trunk/42_DBDesign/Link-Talent.png'! Make sure the output directory exists, or if the user has write permissions over it!

**Comment by rkhaotix** [comment]
Can you provide the model being used in this process?
Em 11/04/2016 21:06, "aceBeta" <notifications@github.com> escreveu:

**Comment by aceBeta** [comment]
I recompiled pgModeler at CentOS 64bit.
Also successfully generated a PNG file with 200% and 27.2Mb of size.
So I think, the error is not the pgModeler, but is to about compiled at Windows 32bit.

@rkhaotix Thanks.
