### ISSUE TITLE
How do you create an inherited table inside of pgmodeler?

### ISSUE THREAD

**Issue by cumminsjp** [pgmodeler/pgmodeler#817]
When I import inherited tables, they come across perfectly.

But I can't figure out a way to create my inherited table in pgmodeler (currently, I create in postgres and then import into pgmodeler) Is it possible? Or am I missing something?

**Comment by rkhaotix** [comment]
@cumminsjp 

You have two ways to create relationships in pgModeler. The first one is to right-click the canvas are and select Relationship > Generalization. The second choice is to select the desired tables, hit N to popup the overlay menu and choose Inheritance. 

The names for the action are no the same (my bad!) but I will fix that and use only "Inheritance". ;)

**Comment by cumminsjp** [comment]
Perfect.  Tried it both ways and both worked.  I saw the **Relationship > Generalization** option before asking the question, but couldn't figure how to get back to it (right-click on canvas). _I was right-clicking on tables directly._

Appreciate the quick reply!

**Comment by rkhaotix** [comment]
You're welcome! ;)
