### ISSUE TITLE
Missing PostGIS geometry types

### ISSUE THREAD

**Issue by posikifi** [pgmodeler/pgmodeler#818]
Hi!

Some PostGIS geometry types are missing, ref: http://postgis.refractions.net/documentation/manual-2.0/using_postgis_dbmanagement.html

If you can add following ones: CIRCULARSTRING, COMPOUNDCURVE, CURVEPOLYGON, MULTICURVE. At least for me ;-)

P

**Comment by rkhaotix** [comment]
Ok! Thanks for reporting this issue. I'll include these missing types
before release the 0.8.1-beta1 :)
Em 22/03/2016 09:28, "posikifi" <notifications@github.com> escreveu:

**Comment by posikifi** [comment]
Great, thank you.

Please add all those missing data types. I might need them in the future.

How about supporting PointClouds: https://github.com/pgpointcloud/pointcloud?

P
