### ISSUE TITLE
Multiple inheritance exports to sql source in wrong order

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [pgmodeler/pgmodeler#820]
The create sql of parent tables needs to be in top of script. Else the create of the child tables fails not knowing their parents. It seems that the order of create table statements of the exported script is the same as the order they where made in the model.

**Comment by rkhaotix** [comment]
Have you tried the model validation?

**Comment by michalkvacek** [comment]
I think it is not only multiple inheritance. I have created table A, which inherits from table B. Columns were added at the end of list of all columns, validation run fine, however I was not able to import the exported SQL file. Once I have moved columns to the begining of the list, everything was fine. Problem is with comma after last column name. Export produced code similar to this:

```
CREATE TABLE public.A(
	id serial NOT NULL,
-- 	name varchar(126) NOT NULL,
-- 	description text,
) INHERITS(public.B)
```

However, there may be another bug related to this issue. After reopening the model, the order of colums is again wrong (inherited columns are specified in the end of column list) and export produces invalid SQL again.

**Comment by rkhaotix** [comment]
@michalkvacek ,

I've confirmed the missplaced comma and already fixed it!
About the columns positioning... Inherited columns can't have their position changed. If you need to change the column's position do it in the parent not in the children. Also, if you add new columns to the children you can move them freely but the inherited column's position are completely ignored.

In PostgreSQL the inherited columns appear first and in pgModeler they will appear always at the end of the table just for practical reasons. Nothing that can't be changed.

**Comment by Jakob-Lanstorp** [comment]
Hello,

I've recently  came accross that amazing  stuff, it looks nice I  think, ytake  a look <http://esteem.electronicdealoftheday.com/e4lsoioe>


In haste, jakob@lanstorp.com

**Comment by Jakob-Lanstorp** [comment]
Hello, 

I'm planning some  house renovation in the near future, so  I wanted  to show you some pictures  of walls  I  really like,  what  do you think? Here is the  link <http://diquoslapru.cindymkim.com/e4jaiq>


All best, jakob

**Comment by Jakob-Lanstorp** [comment]
Hey! 

I've recently watched a musical performance you might  really  like, so I decided to share it with  you  <http://bidaquypy.mishakahn.com/e4ulbeq>

Regards, jakob
