### ISSUE TITLE
Feature request: Export to SVG

### ISSUE THREAD

**Issue by frankgard** [pgmodeler/pgmodeler#822]
It would be nice to be able to export to vector graphics, such as SVG.
Similar to #805, but possibly less effort…

**Comment by rkhaotix** [comment]
Take a look on the last commit in the branch 0.8.2: a51ab9922c9b72f671aa438810ee4473560fce50! ;)
The SVG export is available in the export dialog as well in the CLI. In the moment, it has some issues like not being reproducing the same object sizes and fonts but little by little we'll improve it.

**Comment by frankgard** [comment]
Thanks a lot for such a quick implementation of my feature request. This really helps, and I'll try out as soon as possible. Great work!
