### ISSUE TITLE
Editing a column, no longer able to tab through all the fields.  (Stops at Expression)

### ISSUE THREAD

**Issue by donnorman** [pgmodeler/pgmodeler#826]
Hi,

I just recently upgraded from 0.7.2 to the 0.8.2-beta1, build 20160401.
Love the new design and improvements!

I'm not sure if it's a bug or intended, but you can no longer `<TAB>` out of the Expression field when editing a column.  It just inserts a tab character.  Even `<SHIFT><TAB>` inserts a tab character instead of heading back to the previous field.

If this is going to be a new thing, would it be possible to get a keyboard shortcut for the NOT NULL field?  (`<ALT><N>` perhaps?)

I can still hit `<ALT><Q>` to get to the Sequence field and then `<TAB>` to NOT NULL, but a single step would be ideal if possible.

Thanks and keep up the great work!

**Comment by rkhaotix** [comment]
Actually, we have a regression here. I'll provide the fix ASAP.
About the shortcut for NOT NULL, it'll be included too. 

Thanks for reporting.
