### ISSUE TITLE
diff : escape single quote in comment

### ISSUE THREAD

**Issue by rimbault** [pgmodeler/pgmodeler#827]
Hi,

Using 8.2-beta1, i'm doing a diff between 2 databases.
And pgmodeler don't escape single quote of this comment :
`COMMENT ON COLUMN trela.sequence_vav.broadcast_name IS 'Nom de l'émission';`

Nice job anyway ! :)

**Comment by jmunson** [comment]
You get a similar error if a comment has a ' in it and you try to export it to a database.  I'm a little too far behind schedule to see if that last commit fixes this as well, but it looks like it should.
