### ISSUE TITLE
Issue in v0.8.2-beta1 connect_timeout vs connection-timeout

### ISSUE THREAD

**Issue by Tormen** [pgmodeler/pgmodeler#830]
Hi,

In v0.8.1 things are fine with connect_timeout, but in v0.8.2-beta1 there are some parts where you use connection-timeout and some where you still use connect_timeout and this causes error messages on startup of pgmodeler :(

On the commandline you see (when starting v0.8.2-beta1):
element connection: validity error : No declaration for attribute connect_timeout of element connection

I am using openSuse linux self-compiled version of v0.8.2-beta1. But the issue is really in the provided .conf files and .dtd and .sch files, that are not changed during compile!

Tormen

**Comment by ziben** [comment]
You can modify your connect conf dtd file 'conf/dtd/connections.dtd'，change the connection-timeout to connet_timeout.

Or you can change your config file, the location is 'AppData\Local\pgmodeler'. Change the connect_timeout to connection-timeout.
