### ISSUE TITLE
Add support for PostgreSQL 9.5 and future releases.

### ISSUE THREAD

**Issue by ieugen** [pgmodeler/pgmodeler#831]
Hello, 

I've purchased pgmodeler a couple of days ago and I used it to generate a diagram. It was quite useull for it. In the meantime I've migrated the database to PostgreSQL 9.5 and now I can't use the software. 

I know PostgreSQL 9.5 is only a few months old but I imagine that not much has changed interface wise.  From what I know, most of the changes are additions and or back-end stuff that shouldn ot affect the way pgmodeler uses them. 

Please consider allowing pgmodeler to work regardless of the version used or issue a warning if the version is not supported. Most of the features might just work and people will be able to just use the softwware.  

p.s. I can build software but I chose to purchase the diamond package to support your development efforts. I too work with open source software and I believe quality should be rewarded.

**Comment by rkhaotix** [comment]
The 0.8.2-beta has a basic support PostgreSQL 9.5. 
Try to update your release! I'm sure that it'll work.

**Comment by ieugen** [comment]
Thank you,  0.8.2-beta has 9.5 support. However I got an error when the app started the first time. Now it seems to have gone away. It was related to some XML parsing.
