### ISSUE TITLE
Unable to alter objects after renaming instead of simply dropping and creating 

### ISSUE THREAD

**Issue by yogesch** [pgmodeler/pgmodeler#834]
After renaming an object in pgmodeler, nothing changes in the database automatically. But on exporting the new model with the renamed objects, the existing database model still gets overwritten (by dropping the old objects and creating new ones) instead of the correct objects being altered to get the new name.

**Comment by rkhaotix** [comment]
The object renaming in diff is not supported.

**Comment by yogesch** [comment]
Is there any plan to include this? 
It would make the software very attractive for production use if it were possible to "sync" the model with the database without overwriting everything..

**Comment by rkhaotix** [comment]
There is no plan for it for now. It demands some deep changes on the way pgModeler import objects which affect the whole diff process. I'm sure that before the release 1.0 this will not happen.

**Comment by yogesch** [comment]
Hope it happens in the future..combined with all the other existing features, this would make pgmodeler the most complete software for Postgres. Cheers
