### ISSUE TITLE
The object schema.gender is being referenced before its creation

### ISSUE THREAD

**Issue by rictorres** [pgmodeler/pgmodeler#837]
First of all, thanks for this awesome project!

I created an `ENUM` type and then referenced it in some tables. The problem is that the SQL code for this type is actually after the SQL code for the tables.

![image](https://cloud.githubusercontent.com/assets/351568/14981457/a218220a-112f-11e6-8e4f-b16d80c15ec8.png)

Is this a bug or have I done something wrong?

Thanks!

**Comment by rictorres** [comment]
Okaaay! I just found the **Apply fix** button :)

**Comment by kkursor** [comment]
I experience this issue on 0.9.2-beta2.
How to reproduce:
I had a table with boolean field. After a while I realized that it should be tri-state.
I created enum and changed type and default value of field. After that model validation fails, apply fix mode works infinitely (I stopped it after 30 min), I swapped ID to ensure that type is created before table, but this does not work. It seems that the only way to fix model is to drop field and re-create it with new type and same name.

**Comment by rkhaotix** [comment]
I tested these steps and pgModeler worked as expected. Do you have a sample model where I can detect the problem?

**Comment by kkursor** [comment]
Sorry, our primary model contains sensitive data. :(
I'll try to reproduce it from scratch tomorrow

**Comment by vladsol** [comment]
pgModeler 0.9.3-beta
PostgreSQL 12.0

Same issue. Trying to validate the model:
_The object datadb.client_id_seq (Sequence) [id: 4321] is being referenced by 1 object(s) before its creation._

The "datadb.client_id_seq" is present in model (in Objects list)
