### ISSUE TITLE
Unable to run CLI headless

### ISSUE THREAD

**Issue by polyfloyd** [pgmodeler/pgmodeler#842]
It is currently not possible to run pgmodeler-cli without a DISPLAY variable set.
This makes it very hard to script on servers which do not have Xorg installed.

Steps to reproduce:

```
DISPLAY= pgmodeler-cli
```

Expected output:

```
<The help message of the CLI>
```

Actual output:

```
QXcbConnection: Could not connect to display 
Aborted
```

**Comment by rkhaotix** [comment]
This is the limitation of CLI. The export feature embedded to the application uses graphical libraries that need to X to be running. There is no plans, for now, to change that since it'll demand a deep change in the pgModeler's core.
