### ISSUE TITLE
0.8.2 SQL code generation issue with tables without a constraint.

### ISSUE THREAD

**Issue by donnorman** [pgmodeler/pgmodeler#845]
Hi,

Using the 0.8.2 final release, when SQL code is generated for a table with a single column and nothing else, there's a trailing comma left which causes the validation to fail.

e.g.
![image](https://cloud.githubusercontent.com/assets/4530709/16589485/60521ea4-42a1-11e6-8eb8-1069336a560c.png)

SQL generated:

```
CREATE TABLE sales.contract(
    id uuid NOT NULL DEFAULT uuid_generate_v1(),

);
```

This does not happen if the table is empty, or if there is a constraint (PK) on the column.

I was not experiencing this with the 0.8.2-beta1, as I have a few tables in development that might not have all their columns or constraints when I validate the schema.

Thanks,

Don

**Update after more testing:**

It appears that any table missing a constraint is left with a trailing comma.

Without:
![image](https://cloud.githubusercontent.com/assets/4530709/16589926/65c6b3b6-42a3-11e6-91c3-47138861dc1c.png)

```
CREATE TABLE sales.invoice(
    id uuid NOT NULL DEFAULT uuid_generate_v1(),
    amount money NOT NULL DEFAULT 0.00,

);
```

With:
![image](https://cloud.githubusercontent.com/assets/4530709/16589971/9300864a-42a3-11e6-96d6-f44f0bcc8beb.png)

```
CREATE TABLE sales.invoice(
    id uuid NOT NULL DEFAULT uuid_generate_v1(),
    amount money NOT NULL DEFAULT 0.00,
    CONSTRAINT pk_sales_invoice_id PRIMARY KEY (id)
     WITH (FILLFACTOR = 90)

);
```

If you have tables in development you'll just have to give them a constraint of some kind so the SQL code generated doesn't leave a trailing slash in the table definition.

**Comment by rkhaotix** [comment]
Hi Don,

Unfortunately this bug was introduced in 0.8.2 but the solution is quite
simple. Just replace the file [install root]/schemas/sql/table.sch by the
one in this commit
https://github.com/pgmodeler/pgmodeler/commit/46b64c9e6e1f5503c0e78b190e25655a567bd5bb
Em 5 de jul de 2016 12:17, "Don Norman" <notifications@github.com> escreveu:

**Comment by donnorman** [comment]
Thanks for the quick response!

I just applied the fix and it works as expected.
