### ISSUE TITLE
Columns with type character varying(1) or character(1) not saved properly

### ISSUE THREAD

**Issue by manuelnunez** [pgmodeler/pgmodeler#847]
When I create a column with type **character varying(1)** or **character(1)**, pgModeler save just **character varying** or **character** without length information. This generate an incorrect  column type that allows more than 1 character. Am I missing something?

**Comment by rkhaotix** [comment]
No, you aren't missing anything. It's a bug. 
I missundestood the docs. I'll fix that ASAP!

**Comment by manuelnunez** [comment]
Great!
