### ISSUE TITLE
SQL syntax errors on simple table

### ISSUE THREAD

**Issue by laurensversluis** [pgmodeler/pgmodeler#851]
Hi,

I am trying out this software but got stuck at the creation of a table with 2 columns. The source SQL being generated is this;

-- object: public.new_table | type: TABLE --
-- DROP TABLE IF EXISTS public.new_table CASCADE;
CREATE TABLE public.new_table(
	id serial,
	geom geometry(LINESTRING, 27700),

);
-- ddl-end --
ALTER TABLE public.new_table OWNER TO postgres;
-- ddl-end --

As you can see the program generates an unnecessary comma. 

Please help because I would like to use this software very much.

**Comment by rkhaotix** [comment]
Hi!

Take a look in this issue #845

**Comment by laurensversluis** [comment]
thanks!
