### ISSUE TITLE
Trigger 

### ISSUE THREAD

**Issue by laurensversluis** [pgmodeler/pgmodeler#853]
Hello!

More of a question than an issue. Where can I set the parameters of my trigger function in the table properties. Arguments does not seem to work. See below.  Or am I doing something completely wrong?

Thanks!

![image](https://cloud.githubusercontent.com/assets/11682704/17442342/395ebf38-5b2d-11e6-97e0-2371573db5c6.png)

![image](https://cloud.githubusercontent.com/assets/11682704/17442350/4689119a-5b2d-11e6-852b-fbc0a4ac8e42.png)

**Comment by rkhaotix** [comment]
I think it is because the function you're associating with the trigger.
According to PostgreSQL docs the trigger function can't have arguments and need to return ```trigger``` type: https://www.postgresql.org/docs/9.5/static/sql-createtrigger.html
