### ISSUE TITLE
notation styles, i.e. crows feet

### ISSUE THREAD

**Issue by metapsj** [pgmodeler/pgmodeler#855]
any chance of supporting other notation styles like information engineering for it's use of crow's feet based cardinality symbols?   

here are a couple links describing cardinality using crows feet style... 

  crow's feet are best
  http://tdan.com/crows-feet-are-best/7474

  cardinality notion symbols
  http://ben.hamilton.id.au/how-to/cardinality-notation-symbols

**Comment by rkhaotix** [comment]
Hi.

There are no plans to add new notation styles in a near future.  But I will
mark this as feature request so I can decide to do it in the future

Em 13 de ago de 2016 19:10, "metapsj" <notifications@github.com> escreveu:

**Comment by kb3ien** [comment]
Bump! 

«Crow's feet» are a very popular standard, and for very good reason. Support for this feature would push pgmodeler to the front of the pack for me!
