### ISSUE TITLE
invalid locale name on mac 

### ISSUE THREAD

**Issue by netwobble** [pgmodeler/pgmodeler#856]
Receive error trying to export ... Invalid Locale en_US.UTF8 

Currently on OSx  10.11.6

Current DB has 
LC_COLLATE = en_US.UTF-8
LC_CTYPE = en_US.UTF-8

In prior bug #484 - - work around was posted as ...
For now, the only way to solve this issue is using the "Default" option for
lc_collate as well for lc_ctype.

Any idea where/how to set this?  is this in PGMODELER or Postgres?  currently running PG 9.5 

thanks,
Art

**Comment by donnorman** [comment]
@netwobble 

Try this:

Show your Objects, then double click on the database in the top of the list.  You should be able to change those settings there.  If you still can't export, try changing the "Template DB" to "template0".

![pgmodeler-db-prop-locale](https://cloud.githubusercontent.com/assets/4530709/17776414/72866944-652a-11e6-82d3-ee8d58c65bc7.png)
