### ISSUE TITLE
Field is primary key no more if it is set as primary key + foreign key, after the model is saved and reopened

### ISSUE THREAD

**Issue by ziadloo** [pgmodeler/pgmodeler#858]
Having a compound primary key which is also a foreign key in part, once I set create it, everything is fine. Even the export process generates the correct SQL statements.

But once saved and reopened, the part of the primary key that is also a foreign key, is lost and I have to tell the pgModeler again that it's also a primary key.

Here's the generated SQL for when I've just created / modify the model (everything's alright in this case):

```
-- NOTE: the code below contains the SQL for the selected object
-- as well for its dependencies and children (if applicable).
-- 
-- This feature is only a convinience in order to permit you to test
-- the whole object's SQL definition at once.
-- 
-- When exporting or generating the SQL for the whole database model
-- all objects will be placed at their original positions.


-- object: "Authorization".role_resource | type: TABLE --
-- DROP TABLE IF EXISTS "Authorization".role_resource CASCADE;
CREATE TABLE "Authorization".role_resource(
    role_id bigint NOT NULL,
    resource_code varchar(255) NOT NULL,
    CONSTRAINT role_resource_pk PRIMARY KEY (role_id,resource_code)

);
-- ddl-end --
ALTER TABLE "Authorization".role_resource OWNER TO postgres;
-- ddl-end --

-- object: role_fk | type: CONSTRAINT --
-- ALTER TABLE "Authorization".role_resource DROP CONSTRAINT IF EXISTS role_fk CASCADE;
ALTER TABLE "Authorization".role_resource ADD CONSTRAINT role_fk FOREIGN KEY (role_id)
REFERENCES "Authorization".role (role_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --

```

Once saved and reopened, here's the SQL statements generated for the same exact model:

```
-- NOTE: the code below contains the SQL for the selected object
-- as well for its dependencies and children (if applicable).
-- 
-- This feature is only a convinience in order to permit you to test
-- the whole object's SQL definition at once.
-- 
-- When exporting or generating the SQL for the whole database model
-- all objects will be placed at their original positions.


-- object: "Authorization".role_resource | type: TABLE --
-- DROP TABLE IF EXISTS "Authorization".role_resource CASCADE;
CREATE TABLE "Authorization".role_resource(
    role_id bigint NOT NULL,
    resource_code varchar(255) NOT NULL,
    CONSTRAINT role_resource_pk PRIMARY KEY (role_id)

);
-- ddl-end --
ALTER TABLE "Authorization".role_resource OWNER TO postgres;
-- ddl-end --

-- object: role_fk | type: CONSTRAINT --
-- ALTER TABLE "Authorization".role_resource DROP CONSTRAINT IF EXISTS role_fk CASCADE;
ALTER TABLE "Authorization".role_resource ADD CONSTRAINT role_fk FOREIGN KEY (role_id)
REFERENCES "Authorization".role (role_id) MATCH FULL
ON DELETE CASCADE ON UPDATE CASCADE;
-- ddl-end --
```

**Comment by rkhaotix** [comment]
How the table's xml looks like?

Em 20 de ago de 2016 13:03, "Mehran Ziadloo" <notifications@github.com>
escreveu:

**Comment by ziadloo** [comment]
I've reset the primary key and saved. Then opened the XML file in an editor. Later I reopened the model in pgModeler and of course, the modeler showed that the field is primary key no more. Then I moved some object around just so I can save the file. Then opened it in the editor for the second time.

In the both cases the XML tags were the same and like this:

```
<table name="role_resource">
    <schema name="&quot;Authorization&quot;"/>
    <role name="postgres"/>
    <position x="506.62" y="756.548"/>

    <customidxs object-type="column">
        <object name="resource_code" index="1"/>
        <object name="role_id" index="0"/>
    </customidxs>

    <customidxs object-type="constraint">
        <object name="role_fk" index="0"/>
    </customidxs>
</table>

<relationship name="role_has_many_resources" type="rel1n"
     src-col-pattern="{sc}"
     pk-pattern="{dt}_pk" uq-pattern="{dt}_uq"
     src-fk-pattern="{st}_fk"
     custom-color="#44c1fe"
     src-table="&quot;Authorization&quot;.role"
     dst-table="&quot;Authorization&quot;.role_resource"
     src-required="true" dst-required="false"
    upd-action="CASCADE"
    del-action="CASCADE">
    <column name="resource_code" not-null="true">
        <type name="varchar" length="255"/>
    </column>
    <special-pk-cols indexes="0,"/>
</relationship>
```

**Comment by rkhaotix** [comment]
Ok. I'm not able to create a fix for it right now (recently suffered a
surgery in my shoulder).  As soon as I am recovered I will take care of
this bug. Thanks for reporting.

Em 20 de ago de 2016 13:24, "Mehran Ziadloo" <notifications@github.com>
escreveu:

I've reset the primary key and saved. Then opened the XML file in an
editor. Later I reopened the model in pgModeler and of course, the modeler
showed that the field is primary key no more. Then I moved some object
around just so I can save the file. Then opened it in the editor for the
second time.

In the both cases the XML tags were the same and like this:

<table name="role_resource">
    <schema name="&quot;Authorization&quot;"/>
    <role name="postgres"/>
    <position x="506.62" y="756.548"/>

    <customidxs object-type="column">
        <object name="resource_code" index="1"/>
        <object name="role_id" index="0"/>
    </customidxs>

    <customidxs object-type="constraint">
        <object name="role_fk" index="0"/>
    </customidxs>
</table>

<relationship name="role_has_many_resources" type="rel1n"
     src-col-pattern="{sc}"
     pk-pattern="{dt}_pk" uq-pattern="{dt}_uq"
     src-fk-pattern="{st}_fk"
     custom-color="#44c1fe"
     src-table="&quot;Authorization&quot;.role"
     dst-table="&quot;Authorization&quot;.role_resource"
     src-required="true" dst-required="false"
    upd-action="CASCADE"
    del-action="CASCADE">
    <column name="resource_code" not-null="true">
        <type name="varchar" length="255"/>
    </column>
    <special-pk-cols indexes="0,"/>
</relationship>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pgmodeler/pgmodeler/issues/858#issuecomment-241209277>,
or mute the thread

**Comment by ziadloo** [comment]
Sure, definitely. I hope you'll get better soon.
