### ISSUE TITLE
SQL Source: VIEW gets created before TABLE it depends on

### ISSUE THREAD

**Issue by pboos** [pgmodeler/pgmodeler#867]
There seems to be a problem with the order that tables/views get created. I have a VIEW that depends on several other TABLES. But one table seems to be created after the VIEW. So running the validator returns a problem.

If I remove the JOIN to the given TABLE in the VIEW, it works again. But as soon as I add it back in, it does not work.

Reason probably is that I just use "EXPRESSION" in the View. Because I seem to not be able to create my view with the "normal?" way. So because of that pgmodeler does not know on which tables it depends.

I would suggest to just create the views always at the end. Or allow to somehow change the creation order.

UPDATE:
I see in the "Deps & Referrers" that it is not noticing the other table. But there is no way (or I don't find it) to add a own dependency.

For now I solved it by just manually rearranging the view to the bottom in the .dbm.

**Comment by rkhaotix** [comment]
If you use expression that somehow references a table pgModeler will not be
able to detect that dependency between the view and table.

You can anytime create the whole view from a single expression just check
"View definition". The only drawback is that pgmodeler will not keep track
of table name changes updating the view definition.

Finally, you can change the creation order of many objects by clicking
"Swap Ids" button in the validation widget.

Em 12 de out de 2016 07:13, "Patrick Boos" <notifications@github.com>
escreveu:

**Comment by pboos** [comment]
Didn't notice the "Swap Ids". But sounds like that would help as well :). Thank you for the quick answer!

**Comment by bob-wiegand** [comment]
There are several issues involving dependencies and I have experienced them myself. Would it be feasible for pgmodeler to use pg_depend+pg_class+pg_rewrite to address the difficulty of finding dependencies of views/functions/other on other objects?
