### ISSUE TITLE
Cannot show schema's rectangle

### ISSUE THREAD

**Issue by marialcarria** [pgmodeler/pgmodeler#869]
I have two schemas in my DB model. In one of them I've chosen hiding the background rectangle, but now I cannot change it back, because there's not any way to access the "Schema Properties" besides clicking the rectangle.

I attached an image to show my two schemas and by that show what I want to do. The window property belongs to the schema "apps". I wanna see "schema properties" referent to the other schema, the one without the background rectangle.

![pgmodeler](https://cloud.githubusercontent.com/assets/16889741/19396701/b747da32-921a-11e6-8806-1569913059ae.png)

**Comment by rkhaotix** [comment]
You should use the "Model objects view" (see the image below). Any object in the model can be handled from there.

![model_objects](https://cloud.githubusercontent.com/assets/2205476/22509925/cab8d4fe-e86e-11e6-8f01-2118c4d027d4.png)

**Comment by namrata007** [comment]
I have recently started using pgmodeler so my question may sound silly. How to get Model Objects pane on the view window?
