### ISSUE TITLE
Table data in source for array types

### ISSUE THREAD

**Issue by Tigrov** [pgmodeler/pgmodeler#870]
When I specify table data for array types
![pg-data](https://cloud.githubusercontent.com/assets/8563175/19420207/32f05d82-93ef-11e6-95c1-d0047da62e8f.PNG)

and then when pgmodeler generates a source code it makes an invalid SQL code.
![pd-source](https://cloud.githubusercontent.com/assets/8563175/19420208/38934718-93ef-11e6-9a81-9b8be6f7dfe9.PNG)

It generates "US","CA","MX", but should be '{"US","CA","MX"}'

**Comment by rkhaotix** [comment]
Please, pay attention to the to the info box right below the data grid. As you can see you need to escape  the { } in order to achieve the desired result, so for your case, the array value should be written as: 
*\\{"US","CA","MX"\\}* , note the \ before the curly braces.

**Comment by Tigrov** [comment]
It works with escaping. Thanks.
