### ISSUE TITLE
Schema autocompletion in Sql editor

### ISSUE THREAD

**Issue by rornor** [pgmodeler/pgmodeler#872]
Hi,

I checked the wiki, googled this and looked for it in the issues, but it seems nowhere mentioned.

Is it correct that there is no autocompletion for db schema in sql editor view?
Like for example I type `select * from ...` and get table suggestion at least?

TIA

**Comment by rkhaotix** [comment]
Yes. Pgmodeler does not supports this feature yet. I'm planning to add it
during the development of 0.9.0.

Em 17 de out de 2016 12:54, "rornor" <notifications@github.com> escreveu:

**Comment by rornor** [comment]
Great! 
Thanks for your quick reply :)
