### ISSUE TITLE
Cannot import, change, and export

### ISSUE THREAD

**Issue by eengnerd** [pgmodeler/pgmodeler#878]
Even though pgmodeler uses collation "en_US.UTF-8" to create a database with name of "new_database", when importing any existing database, making one simple change and then trying to export it, results in the following complaint:

Could not execute the SQL command. Message returned: ERROR: new collation (en_US.UTF8) is incompatible with the collation of the template database (en_US.UTF-8)
HINT: Use the same collation as in the template database, or use template0 as template.

**Comment by eengnerd** [comment]
I should add that this problem shows up on pgmodeler version 0.9.0 alpha.  And obviously the generated SQL statement is trying to use a collation of "en_US.UTF8" which does not exist in PostGreSQL 9.5

**Comment by eengnerd** [comment]
I've successfully modified both files to match the changes you made, but the behavior remains the same.

**Comment by eengnerd** [comment]
After the changes rkhaotix added are compiled again, even after a clean and rebuild all, still getting the same error message on export:

Could not execute the SQL command.
Message returned: ERROR: new collation (en_US.UTF8) is incompatible with the collation of the template database (en_US.UTF-8)
HINT: Use the same collation as in the template database, or use template0 as template.

**Comment by eengnerd** [comment]
I should also note that when exporting I check the checkbox for "Ignore duplicate objects" if that helps.

**Comment by eengnerd** [comment]
I've experimented for quite a while now.  There seem to be many calls to a function that is built into QObject, namely trUtf8(), but in looking at the documentation for QObject, it says that this function is "obsolete".  And that it is included only to make sure old code still runs.  In any case, this seems like it may be involved in this problem because the end result is that when all is said and done, the collation string defined by pgmodeler is always missing the "dash character" when indeed the dash should be included.
Again:  pgmodeler generates "en_US.UTF8" when it should be generating "en_US.UTF-8" as the content of LC_COLLATE.  Try as I might, I have not found where to fix this yet.

**Comment by eengnerd** [comment]
OK, I think I understand this problem better now, but still don't know how to fix it.  The problem is that pgmodeler is "getting the locale" information at some point, but the string it is finding is limited to "en_US.utf8" which of course is why it is using the string "en_US.UTF8" for the value of LC_COLLATE.
Evidently there are two commands involved in a terminal window to manipulate the string values in locale: locale -a (used to display the current values) and locale-gen (a script to generate the locale strings).  I'm not familiar with how to edit the content of the script file for locale-gen, if someone can help me out here...I would greatly appreciate it.

**Comment by eengnerd** [comment]
By the way, IMHO pgmodeler should check itself to make sure that if the obvious "system flaw" of en_US.utf8 still exists, then pgmodeler should automatically add the expected dash character in between the f and the 8, at least for now, until the system flaw is found and fixed.

**Comment by rkhaotix** [comment]
As I told a month ago, the fix was included in this commit b63869a. You're supposing things that aren't even close to the original problem. The call to QObject::trUtf8 (actually, not directly to this method because it is really obsolete) has not to do with the locale incompatibilities... The method is used to translate sentences in the UI!

You don't need to use the command ```locale -a``` or ```locale-gen``` to solve the issue. You may break your system if you try to change locale related files.

Explaining again the problem: pgModeler was generating the locale string correctly but the format required by the PostgreSQL server may vary from system to system where it is installed so I decided to drop the automatic locale code generation. This fix solved all the problems.

Now, if you've compiled the code from the commit that I mentioned (or even the head of the branch 0.9.0-alpha1) and the problem persists (at least for me it was solved!) we can continue to discuss the errors.

**Comment by eengnerd** [comment]
OK, I'm tired of not being able to get a modified version of the code running.  I tried deleting the local git repository and doing a fresh git clone of the main pgmodeler directory, then compiled with the same result I previously reported.  Then I tried the following command with the result shown as well:

git clone https://github.com/pgmodeler/pgmodeler/tree/0.9.0-alpha1 pgmodeler2
Cloning into 'pgmodeler2'...
fatal: repository 'https://github.com/pgmodeler/pgmodeler/tree/0.9.0-alpha1/' not found

I'm assuming that is what you meant by the "head of alpha" in your previous comment.

**Comment by rkhaotix** [comment]
Ok. It seems you're not familiar to git. So here's a little help: https://git-scm.com/documentation

You have to clone and checkout the branch:

git clone [url]
git checkout 0.9.0-alpha1

**Comment by eengnerd** [comment]
OK, I have tried Checking Out all 3 branches that were listed in the list on the remote side and making a local copy of each, one by one, and compiling after each checkout to see if there was any change in the behavior of the software.  I used the gui tools on the QT Creator 4.2 Tools menu to perform the checkout.  Unfortunately there was no change in the behavior of the software on any of the 3 branches.  See original problem above.

**Comment by eengnerd** [comment]
The branches listed were:
0.9.0-alpha1
HEAD
develop

in that order.

**Comment by eengnerd** [comment]
Let me specify the behavior of the software more clearly:
I have a very simple database called pgMedical with one table called Patients.  There is one field in Patients called PatientID with the correct properties for behavior that is similar to MS Access' AutoNumber data type.  In PostGreSQL that is "big serial".  The procedure is to "Import" this database and table into pgmodeler, then add one field called FirstName of type "Character Varying" with a length of 15.  Then I try to Export the model back to PostGreSQL, validating the model first (works), and checking the box that's labeled "Ignore Object Duplicity".  When clicking "Export" I get a message as described above saying that it cannot use collation "en_US.UTF8" because the template database is using "en_US.UTF-8".  Notice the added "dash".

**Comment by eengnerd** [comment]
After re reading your comments here, I decided to try the HEAD branch once more, but this time do a "clean all" and "rebuild all" after making sure that the code snippets actually look the same as those in the bug fix where you have a link to the changes in the code.  Although the code looks the same, after doing clean all and rebuild all, the same behavior is seen.

**Comment by eengnerd** [comment]
I used pgadmin3 to look at the actual collation of both pgMedical and pgdefault and they are both listed as "en_US.UTF-8".  So this bug makes sense.

**Comment by eengnerd** [comment]
How difficult would it be just to add the dash?

**Comment by rkhaotix** [comment]
I don't see any need to add another patch because the problem was solved. You are failing to compile the branch 0.9.0-alpha1... I don't know if it is because a problem in your environment or due to the lack of experience with the language and/or  the ecosystem involved like git, qt framework, etc.

The truth is... We are walking in circle because I have said that the problem is solved in a certain commit and you're still pointing things that you consider "bugs".

 which system you are compiling pgmodeler?

**Comment by eengnerd** [comment]
I'm using Linux Mint Cinnamon 18.1 as the OS and using the build-essential package with QT Creator version 4.2.  I also installed the latest git package.
