### ISSUE TITLE
Diff of modeled table with serial data type results in an alter column to integer?

### ISSUE THREAD

**Issue by knizami** [pgmodeler/pgmodeler#881]
Hello, for a table modeled with a serial primary key and then exported to a database, a subsequent diff results in pgmodeler picking up that the serial column needs to be altered to type integer?  and that the sequence needs to be reapplied?  see modeled table:

![image](https://cloud.githubusercontent.com/assets/9139171/20852971/99cff574-b8ae-11e6-94c5-d400254c955d.png)

And after that, doing a diff results in the following:

ALTER TABLE public.test1 ALTER COLUMN _id TYPE integer;
-- ddl-end --
ALTER TABLE public.test1 ALTER COLUMN _id SET DEFAULT nextval('public.test1__id_seq'::regclass);
-- ddl-end --
ALTER TABLE public.test2 ALTER COLUMN _id TYPE integer;
-- ddl-end --
ALTER TABLE public.test2 ALTER COLUMN _id SET DEFAULT nextval('public.test2__id_seq'::regclass);
-- ddl-end --

why is it trying to alter the column type?  Looking at the column in pgadmin, the column is already a type integer, not null.

**Comment by knizami** [comment]
FYI - 
If I instead model each tables pk with type integer, not null set and a pk constraint on each and then export to the db and then try and do a diff, I get the expected behavior, which is no changes detected...

**Comment by CSLTech** [comment]
Serial is only a shorthand for integer with a sequence. Internally postgres looses the serial type.

**Comment by jadbox** [comment]
@CSLTech I think the solution here is that the diff tool should understand this equivalence between the serial type and integer+incrementer. This would help reduce the unnecessary 'noise' that gets generated in the diffs when the user wants to use Serial types instead of defining the raw behavior with an integer field.

**Comment by sachnk** [comment]
+1

The diff noise makes it hard to tease out exactly the migrations necessary between the sources that are being compared, particularly if there are a lot of changes.

**Comment by rkhaotix** [comment]
Ok, guys. I'll look into it as soon as I finish the declarative table partitioning on pgModeler. Since I will need to patch the diff process I can include a fix for this too.
