### ISSUE TITLE
applying a diff after a many to many generated table in db with no changes results in a DROP NOT NULL on the keys in the generated table resulting in error

### ISSUE THREAD

**Issue by knizami** [pgmodeler/pgmodeler#882]
Given the following many - many relationship in pgmodeler:

![image](https://cloud.githubusercontent.com/assets/9139171/20853082/451b8768-b8af-11e6-814a-2d64b6464b78.png)

When you immediately do a diff after exporting this to a pg 9.6 database, you get the following diff statements generated:
-- [ Changed objects ] --
ALTER TABLE public."user" ALTER COLUMN join_date TYPE timestamp;
-- ddl-end --
ALTER TABLE public."user" ALTER COLUMN join_date SET DEFAULT CURRENT_TIMESTAMP;
-- ddl-end --
ALTER TABLE public."user" ALTER COLUMN resetcode_exp TYPE timestamp;
-- ddl-end --
ALTER TABLE public.component_permissions ALTER COLUMN _id_user DROP NOT NULL;
-- ddl-end --
ALTER TABLE public.component_permissions ALTER COLUMN _id_component DROP NOT NULL;
-- ddl-end --
ALTER TABLE public."user" ALTER COLUMN _id TYPE integer;
-- ddl-end --
ALTER TABLE public."user" ALTER COLUMN _id SET DEFAULT nextval('public.user__id_seq'::regclass);
-- ddl-end --

When you try and apply this it fails because pg doesn't let you drop a not null constraint on a primary key, the many to many table is composed of the two foreign keys its trying to alter.  

Also, it tries to alter the types to integer, not sure why.  It also doesn't pick up that the join_date column is already of type TIMESTAMP, looking in pgadmin, you see join_date is of type:
'timestamp without timezone' with a default value of now()

**Comment by rkhaotix** [comment]
The diff process is quite new and sometimes can present the user some
false-positive results. The drop not null problem also happened to me few
days ago and I already provided a patch which is available in the
0.9.0-alpha1 branch.

The other issues I will investigate them as soon as possible. anyways
thanks for reporting them.

Em 2 de dez de 2016 20:53, "knizami" <notifications@github.com> escreveu:
