### ISSUE TITLE
Kerberos connection results in error

### ISSUE THREAD

**Issue by pamvdam** [pgmodeler/pgmodeler#885]
Good afternoon,

First, let me compliment you on this great software. I really enjoy it. Hopefully I can attribute a little bit to your effort.

I have a Kerberos infrastructure based upon FreeIPA on Centos-7. All the principals are set up correctly and from the client host I can access the database on the remote server using psql over kerberos.

My kerberos REALM is KLEEFDRAAKJES.NEST
the remote Postgresql database is on server pgsqlcn05, my username is pascal.

The tickets I have are:

Ticket cache: KEYRING:persistent:243200001:krb_ccache_4spm0Fs
Default principal: pascal@KLEEFDRAAKJES.NEST

Valid starting       Expires              Service principal
12/11/2016 13:17:47  12/12/2016 13:17:37  postgres/pgsqlcn05.kleefdraakjes.nest@KLEEFDRAAKJES.NEST
12/11/2016 13:17:39  12/12/2016 13:17:37  krbtgt/KLEEFDRAAKJES.NEST@KLEEFDRAAKJES.NEST

To show that the pgsql connection works:

Ticket cache: KEYRING:persistent:243200001:krb_ccache_4spm0Fs
Default principal: pascal@KLEEFDRAAKJES.NEST

Valid starting       Expires              Service principal
12/11/2016 13:17:47  12/12/2016 13:17:37  postgres/pgsqlcn05.kleefdraakjes.nest@KLEEFDRAAKJES.NEST
12/11/2016 13:17:39  12/12/2016 13:17:37  krbtgt/KLEEFDRAAKJES.NEST@KLEEFDRAAKJES.NEST

I' ve configured a connection pgsqlcn05_krb with no passwd, no ssl and kerberos server
ipan03.kleefdraakjes.nest. GSSAPI is not selected

(If I do select GSSAPI, a connection will result in another error:
(Could not connect to the database.
Message returned: invalid connection option "gsslib)

When I make a connection I will get the following error:

Could not connect to the database.
Message returned: `GSSAPI continuation error: Unspecified GSS failure.  Minor code may provide more information
GSSAPI continuation error: Server ipan03.kleefdraakjes.nest/pgsqlcn05.kleefdraakjes.nest@KLEEFDRAAKJES.NEST not found in Kerberos database

Did I mis a configuration step or is this a bug?

Thanks for any input you can give me. Glad to help you in debugging.

BTW: I do have a subscription on the pgmodeler application also. :)

Kind regards,

   Pascal van Dam

**Comment by rkhaotix** [comment]
Hi @pamvdam 

First, thank you so much for the compliment! I'm glad to see that pgModeler is being useful to you somehow! Oh, and thanks for the subscription too... This kind of support is quite important to keep the hard work on this project! :)

About your problem... It seems that pgModeler is messing with the connectins parameters. Could you provide some more details about the error? Maybe some log files, your connections.conf file or even a screenshot of the connections dilag with the connection attributes exposed (these details you can provide via e-mail for privacy reasons if you pefer).

Just to inform, the gsslib (in pgModeler "Force GSSAPI") is used only in Windows environment so if you are running pgModeler on Linux and your server is on this system too use "Force GSSAPI" is useless.

I'll be waiting your response!

Kind regards,
Raphael
