### ISSUE TITLE
DIFF generates changes that are not needed

### ISSUE THREAD

**Issue by JedrzejczykRobert** [pgmodeler/pgmodeler#886]
Reproduce steps:

1. Create table like:

CREATE TABLE test1
(
  rsign character varying(1),
  currency char(3) NOT NULL DEFAULT 'PLN',
  add_date timestamp NOT NULL DEFAULT statement_timestamp(),
  mod_date timestamp
);

2. After run DIFF, we have:

ALTER TABLE test1 ALTER COLUMN rsign TYPE character varying(1);
ALTER TABLE test1 ALTER COLUMN currency SET DEFAULT 'PLN';
ALTER TABLE test1 ALTER COLUMN add_date TYPE timestamp;
ALTER TABLE test1 ALTER COLUMN mod_date TYPE timestamp;

3. Apply DIFF and run DIFF again, we have again:

ALTER TABLE test1 ALTER COLUMN rsign TYPE character varying(1);
ALTER TABLE test1 ALTER COLUMN currency SET DEFAULT 'PLN';
ALTER TABLE test1 ALTER COLUMN add_date TYPE timestamp;
ALTER TABLE test1 ALTER COLUMN mod_date TYPE timestamp;

pgModeller 0.9.0-alpha (build 20161017),
pgsql93 (windows)
pgsql94 (linux)

when use pgdump then I have:

CREATE TABLE test1
(
  rsign character varying,
  currency character(3) NOT NULL DEFAULT 'PLN'::bpchar,
  add_date timestamp without time zone NOT NULL DEFAULT statement_timestamp(),  
  mod_date timestamp without time zone
);

**Comment by rkhaotix** [comment]
This issue is already known!
Even considering it a minor one I did some tweaks and it may reduce the chance of unnecessary diff entries.
