### ISSUE TITLE
Table Creation interface is not ideal

### ISSUE THREAD

**Issue by Tahaan** [pgmodeler/pgmodeler#892]
Allow to set PKey at the time a column is created.

Allow to set the referenced FKey column at the time a column is created.

Allow to set a default value when creating a column.

When adding an FKey afterwards, put the referenced table and column side-by-side in the same TAB so that they are visible at the same time.

Fill in an Auto-generated constraint name if I don't fill one in.

New column as a copy from the current column, allow changes to be made.

For example I sometimes want to add 6 varchar(30s) and all of them are NOT NULL and all have default value of "XYZ", only the column name is different.  I want to create one, then click "copy", change the column name, and Apply.

When I change a type to varchar and press TAB, it doesn't go to the Len (Max).  That is almost always where I want to go next.  The interface only enables this field AFTER leaving the varchar column, so I always end up having to go back, which is frustrating.

**Comment by rkhaotix** [comment]
Almost all of your suggestions are scheduled to be implement in next releases.
