### ISSUE TITLE
Setting PRIMARY KEY constraint before adding the column

### ISSUE THREAD

**Issue by caiohamamura** [pgmodeler/pgmodeler#899]
I had a table which I needed to change its primary key by creating a new serial one, but when I ran Diff the script tried to created the `ADD CONSTRAINT PRIMARY KEY` before the `ADD COLUMN`.

**Comment by rkhaotix** [comment]
Have you tried to validate the model before run the diff?

**Comment by caiohamamura** [comment]
Actually I didn't. Validate will reorder things under the hood?

**Comment by rkhaotix** [comment]
No, but the validation points out what objects are broken due to reference problems. Just use the 'Fix' button that pgModeler will reorder them to you, in the majority of cases.

**Comment by caiohamamura** [comment]
Validate didn't complain about broken references.

**Comment by rkhaotix** [comment]
Found the problem. I'll provide the fix ASAP.
