### ISSUE TITLE
Many-to-many intermediate table: provide the option to display in the diagram.

### ISSUE THREAD

**Issue by caiohamamura** [pgmodeler/pgmodeler#900]
Sometimes displaying the intermediate table from many-to-many relationship is nice to provide a visual aid for `JOIN ON` table and column names, so it would be nice to be able to visualize it.

**Comment by rkhaotix** [comment]
Right click the many-to-many relationship and select "Convert".

**Comment by caiohamamura** [comment]
Thanks! It won't "unconvert" without undoing, will it?

**Comment by rkhaotix** [comment]
No, the relationship between the tables is preserved. The only drawback is that the intermediate table can't be reverted back to a many-to-many relationship.

**Comment by caiohamamura** [comment]
Ok, thanks again. Great job BTW.

**Comment by rkhaotix** [comment]
Thanks :)
