### ISSUE TITLE
Disable AltGr+space shortcut

### ISSUE THREAD

**Issue by v-melot** [pgmodeler/pgmodeler#908]
Hi,

I noticed that in the View creation window, when editing an expression, AltGr+space is a shortcut for selecting an existing column. Though, in some keyboard layouts, AltGr+space is used for typing characters: 0 for German Neo2, underscore for French BÉPO and no-breaking space for some others. As AltGr (alternating graph) is a key designed for input (contrary to Ctrl or Alt, which are designed for interaction with softwares and Super for windows manager), I suggest you to disable this shortcut or, at least, to add a setting “disable AltGr shortcuts”.

Thanks !

**Comment by rkhaotix** [comment]
Hi!
There is no such shortcut in view editing dialog or in any other dialog / control in pgModeler.
This could be an issue with the Qt framework.

**Comment by v-melot** [comment]
Oh, that’s strange. Thanks!
