### ISSUE TITLE
Duplicated Index is not validated

### ISSUE THREAD

**Issue by rmaugusto** [pgmodeler/pgmodeler#910]
The application does not validate if the index already exists in model such is done with table.
This is only noticed when the database is exported with error.

pgModeler v0.9.0-alpha1

**Comment by rkhaotix** [comment]
Did you try to validate the model?
Because, here in my environment with the current codebase (0.9.0-beta) pgModeler detects the duplication.

![index](https://cloud.githubusercontent.com/assets/2205476/23141481/c9361f20-f795-11e6-96d3-ffbec3568fd6.png)

**Comment by rmaugusto** [comment]
The validate feature detected duplication !
I was expecting a message like table "The object schema."ReserveAmount" (Table) already exists on db (Database)!

Thanks
