### ISSUE TITLE
Hard-time compiling from source in Debian Jessie

### ISSUE THREAD

**Issue by Manumie** [pgmodeler/pgmodeler#911]
Hi,
I've had a hard time compiling pgmodeler from sources in Debian Jessie.
At first I was gonna ask for help, but I solved my issue while writing this note, so I thought it might be helpful. I still have two minor issues exposed below.

#### Short story
```
$ sudo apt install pkg-config libxml2-dev libpq-dev qt5-qmake qt5-default libqt5svg5-dev
$ sudo ./linuxdeploy.sh
$ sudo qmake pgmodeler.pro
$ sudo make
$ sudo make install
$ pgmodeler &
```

#### Longer story
Check the requirements : 
`pkg-config`is not installed by default : `sudo apt install pkg-config`.

* gcc > 4.8 : `gcc/stable,now 4:4.9.2-2 amd64  [installé, automatique]`
  > default in Jessie
* libxml : `-I/usr/include/libxml2 -lxml2`
  > I had to install the headers : `sudo apt install libxml2-dev` 
* libpq : `-I/usr/include/postgresql -lpq`
  > I had to install the headers `sudo apt install libpq-dev`
  > the output in not exactly like on the instructions page (`I/usr/include ­L/usr/lib64/libpq.so`), but it doesn't seem to be a problem

Qt5 in not installed by default (unless I messed with it 😛) and the headers for `libqt5-svg5` are also needed : `sudo apt install qt5-qmake qt5-default libqt5svg5-dev`

Trying to compile directly with `qmake` (as per the instructions page) will fail :
```
$ sudo qmake pgmodeler.pro
```
It issues WARNINGS about various paths not being set (samples.path, lang.path, etc.)

But there is a script called `linuxdeploy.sh` which I hadn't noticed at first...
It seems to set the missing paths but it fails when trying to run qmake : 
```
$ sudo ./linuxdeploy.sh
(...)
Failed to execute qmake with arguments '-r -spec linux-clang`
```
I tried to change the `-r`option (not documented in the man page for `qmake`) to `-recursive`, but I got the same error.

However, you can now run :
```
$ sudo qmake pgmodeler.pro
(very fast, seems like nothing happened...)
$ make
( you can go have a cup of coffee... maybe several... )
$ make install
```
The app is now installed. To run it, type `pgmodeler`in a terminal or with Alt+F2 in the window manager.
It looks really beautiful at first sight, and after just a few minutes hands on, it seems very powerful and efficient.

Hope this helps !

### Remaining issues

I have a warning when I run `pgmodeler` from the command line :
```
$ pgmodeler
element connection: validity error : No declaration for attribute connect_timeout of element connection
                sslmode="disable" auto-browse-db="false"/>
```
Is that bad ?

And I get a warning in a Qt dialog about `/usr/local/lib/pgmodeler/plugins` not being writeable by my user.
The directory doesn't exist, so I created it, chowned it to group staff (other objects in /usr/local/share belong to group staff), made it writeable by the group, and added my user to the group.
(I have to log out and back in for the shell to know about my user's new group)
```
$ sudo mkdir /usr/local/share/pgmodeler/plugins
$ sudo chown :staff /usr/local/share/pgmodeler/plugins
$ sudo chmod g+w /usr/local/share/pgmodeler/plugins
$ sudo adduser <user> staff
```
Is this correct ?

Thanks,
Emmanuel

**Comment by antoine-pous** [comment]
Are you sure about `qt5-make` and `qt5-defaults`? I've found `qt5-qmake` and `qt5-default` packages instead of yours.

**Comment by Manumie** [comment]
You're absolutely right. I've edited my post accordingly.

**Comment by antoine-pous** [comment]
You've missed the short story ;)

**Comment by Manumie** [comment]
Done, thanks

**Comment by Summer88** [comment]
Hi,
I'm on a Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux with:
- gcc version 6.3.0 20170516 (Debian 6.3.0-18)
- clang version 3.8.1-24 (tags/RELEASE_381/final)
- qmake -v QMake version 3.0 Using Qt version 5.7.1 in /usr/lib/x86_64-linux-gnu

Tried to follow your step but stuck here:

```
pgModeler Linux deployment script
PostgreSQL Database Modeler Project - pgmodeler.com.br
Copyright 2006-2016 Raphael A. Silva <raphael@pgmodeler.com.br>

Deploying version: 0.9.0-beta1
Cleaning previous compilation...
Running qmake...
Compiling code...

** Compilation failed!

```

`* Proceed with build process by running:
  >  make && make install

cd libutils/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/gigi/Scaricati/pgmodeler/libutils/libutils.pro -spec linux-g++ PREFIX=/opt/pgmodeler$
make[1]: ingresso nella directory "/home/gigi/Scaricati/pgmodeler/libutils"
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILDNUM=\"20170621\" -DBINDIR=\"/opt/pgmodeler\" -DPLUGINSDIR=\"/opt/pgmodeler/plugins\" -DPRIVATEBINDIR=\"$
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILDNUM=\"20170621\" -DBINDIR=\"/opt/pgmodeler\" -DPLUGINSDIR=\"/opt/pgmodeler/plugins\" -DPRIVATEBINDIR=\"$
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBUILDNUM=\"20170621\" -DBINDIR=\"/opt/pgmodeler\" -DPLUGINSDIR=\"/opt/pgmodeler/plugins\" -DPRIVATEBINDIR=\"$
rm -f libutils.so.1.0.0 libutils.so libutils.so.1 libutils.so.1.0
g++ -Wl,-O1 -Wl,-rpath,/opt/pgmodeler/lib -shared -Wl,-soname,libutils.so.1 -o libutils.so.1.0.0 obj/exception.o obj/globalattributes.o obj/pgsqlversions.o  -lpq -lxml2$
/usr/bin/ld: impossibile trovare -lGL
collect2: error: ld returned 1 exit status
Makefile:143: set di istruzioni per l'obiettivo "libutils.so.1.0.0" non riuscito
make[1]: *** [libutils.so.1.0.0] Errore 1
make[1]: uscita dalla directory "/home/gigi/Scaricati/pgmodeler/libutils"
Makefile:50: set di istruzioni per l'obiettivo "sub-libutils-make_first-ordered" non riuscito
make: *** [sub-libutils-make_first-ordered] Errore 2

`

**Comment by Manumie** [comment]
I don't remember bumping into this problem...

Do you get the same message as I did when you run `linuxdeploy.sh` ?
That is : `Failed to execute qmake with arguments '-r -spec linux-clang`

Have you run `sudo qmake pgmodeler.pro` before `make && make install` ?

I was using pgModeler 0.8.2, are you using the same version ?

**Comment by Summer88** [comment]
Thanks for reply,  I've tried today with the new beta release 0.9.0-beta2, but stuck.

> Do you get the same message as I did when you run linuxdeploy.sh ?
That is : Failed to execute qmake with arguments '-r -spec linux-clang

Yes, I get the message then make the edit to -recursive, 

sudo ./linuxdeploy.sh    

```
pgModeler Linux deployment script
PostgreSQL Database Modeler Project - pgmodeler.com.br
Copyright 2006-2017 Raphael A. Silva <raphael@pgmodeler.com.br>

Deploying version: 0.9.0-beta2
Cleaning previous compilation...
Running qmake...
Compiling code...

** Compilation failed!

```

Note for the author: I'd like to pay to get the deb package even if it's still in beta, as I've tried under windows and it allow to connect to postgresql-9.6, instead with stable I cannot use this.

**Comment by Manumie** [comment]
@Summer88 Ok, I tried to compile on Debian 9 with the last master from the repository here on GitHub.

I bumped into the compilation fail, and checked in `linuxdeploy.sh` :
if you don't have LLVM and clang installed (they're not installed in a fresh Debian 9), you need to change QMAKE_ARGS, as indicated in the comment, so your file looks like this :
```
(...snip...)
# Uncomment this line if your system doesn't have LLVM (clang) compiler tools
QMAKE_ARGS="-r -spec linux-g++"
#QMAKE_ARGS="-r -spec linux-clang"
(...snip...)
```

Now, the compile step goes smoothly, but I get an error wen copying lib files :
```
Copying Qt core libraries...
** Library copy failed!
```
That is because `qtpaths` doesn't know what version it should use. I couldn't find a way to make `qtpaths` aware of the correct paths, so I went on and changed `linuxdeploy.sh` (from line 247) :
```
# QT_ROOT=`$QMAKE_ROOT/qtpaths --install-prefix`  >> $LOG 2>&1
 QT_ROOT=/usr/lib/x86_64-linux-gnu

 for lib in $QT_LIBS; do
#  cp -v $QT_ROOT/lib/$lib $BUILD_DIR/$INSTALL_ROOT/lib >> $LOG 2>&1
 cp -v $QT_ROOT/$lib $BUILD_DIR/$INSTALL_ROOT/lib >> $LOG 2>&1
 done
```
In order to figure out where te libs are on your system, you can try `find /usr/lib/ -name libQt5* -ls`

I ran the script again and got a similar path problem with the plugins, so I changed `linuxdeploy.sh` again (line 276) :
```
#   cp -v $QT_ROOT/plugins/$plug $DEP_PLUGINS_DIR/$pdir >> $LOG 2>&1
   cp -v $QT_ROOT/qt5/plugins/$plug $DEP_PLUGINS_DIR/$pdir >> $LOG 2>&1
```
and I also had to install `qt5-image-formats-plugins` 

Now `linuxdeploy.sh` goes all the way smoothly :
```
pgModeler Linux deployment script
PostgreSQL Database Modeler Project - pgmodeler.com.br
Copyright 2006-2016 Raphael A. Silva <raphael@pgmodeler.com.br>

Deploying version: 0.8.2
Cleaning previous compilation...
Running qmake...
Compiling code...
Installing dependencies...
Copying Qt core libraries...
Copying Qt plugins...
Copying scripts...
Generating tarball...
File created: dist/pgmodeler-0.8.2-linux64.tar.gz
pgModeler successfully deployed!
```
Not sure if this actually installs pgModeler, so I ran
```
make && sudo make install
```
pgModeler is now installed in `/opt/pgmodeler`

**Comment by tz4678** [comment]
Thanx
