### ISSUE TITLE
Settings of geometry column are not kept

### ISSUE THREAD

**Issue by yjacolin** [pgmodeler/pgmodeler#912]
* Open table property
* Open column property with a geometry column
* Geometry settings (Spatial and srid) are empty, see screenshot:

![spectacle m18094](https://cloud.githubusercontent.com/assets/660191/23401181/105b88d8-fda7-11e6-89f1-3126c4a97edc.png)

If we valid, the settings are lost.

Version: 0.9.0alpha1

**Comment by yjacolin** [comment]
I don't know if it is valuable to confirm that this issue is still valid for next version. If this is not the case, sorry, it so it is still valid in Version 0.9.1-beta. :)

**Comment by rbrdevs** [comment]
Same problem here with version 0.9.2-beta-1
Whenever I setup a geometry column and re-open the edit form, values SRID, Variation Z, M disappear.
![vcxsrv_EkTvEeZBUQ](https://user-images.githubusercontent.com/4678959/67098758-08303200-f1bd-11e9-9be9-03c2ae06d6a1.png)
![lv8D24ElcB](https://user-images.githubusercontent.com/4678959/67098767-0cf4e600-f1bd-11e9-9514-5412495553ba.png)

If you open SQL source code visualization (Alt+S) everything seems correct.

![vcxsrv_WdAfeh2jD8](https://user-images.githubusercontent.com/4678959/67098807-21d17980-f1bd-11e9-9b24-fa3760cd1201.png)

But if option "Generate ALTER for columns/constraints" is checked, comma separator is omited in SQL source.

![iY6jBAVOyK](https://user-images.githubusercontent.com/4678959/67098818-24cc6a00-f1bd-11e9-9204-610a82918337.png)

Additionaly, when using "Export" tool to db server connection, geometry type fields with SRID specified fails becouse of comma separator ausence. Need to append SQL code in table definition using "UpdateGeometrySRID" to solve it.

Using pgModeler 0.9.2-beta1 and PostgreSQL 11.2
