### ISSUE TITLE
Wrong syntax for DROP CAST?

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#920]
It seems to me that the generated syntax for `DROP CAST` is wrong, as it uses `,` as delimiter instead of `AS`. Compare your syntax to the documentation and in my case your syntax simply fails with an error message about wrong syntax:

`DROP CAST IF EXISTS (varchar,inet) CASCADE;`

> DROP CAST (sourcetype AS targettype) [ CASCADE | RESTRICT ]

https://www.postgresql.org/docs/8.0/static/sql-dropcast.html

**Comment by rkhaotix** [comment]
Yes, you're right.
We have a bug here! Thanks for reporting!
