### ISSUE TITLE
Object creation after table bug

### ISSUE THREAD

**Issue by denkomanceski** [pgmodeler/pgmodeler#922]
Okay, so the problem is that the order of the queries executed is wrong, and to make it work we need to manually (by hand) move the statements to the expored .sql, which means we cannot use the diff feature nor export directly to a server. Here is short explanation:
There is an object (called userGroupTypes) which is used as enumeration to userGroups -> lets say (admin, guest, user, etc..), and object is used as a type on a column on the userGroups table, so the problem is that CREATE userGroups table statement is BEFORE creating type userGroupTypes and because of that this error is thrown when exporting: (userGroupTypes does not exist)
http://prntscr.com/elnzf0

How should we fix this ?
Here is the table screenshot: http://prntscr.com/elnzu7
Here is the enum object: http://prntscr.com/elo03e

I assume the best way to be to create all the object after creating the schema that they live in, and than create all the tables?

**Comment by rkhaotix** [comment]
Validade your model.

**Comment by denkomanceski** [comment]
@rkhaotix I did validate it, to be able to save the file as .dbm I have to validate it
