### ISSUE TITLE
Fading out state for connectors lost 

### ISSUE THREAD

**Issue by haubourg** [pgmodeler/pgmodeler#925]
Hi, using 64 bits 9.0 alpha1 yesterday, I faded out a lot of relation connectors and this morning, they are all displayed again. I was warned to validate the model yesterday, which I did, and then saved normally. 
Since I couldn't find a way to select connectors by clic and drag, only CTRL + clic, it is quite long to reset.

**Comment by rkhaotix** [comment]
Hi @haubourg 

You can restore the original opacity of all object by right click the canvas area (blank portions) and access the Fade in/out action.

The fade in/out feature is new and still needs adjustments. The opacity is not persisted but if you think this could be good , I'll try to change it.

**Comment by haubourg** [comment]
Hi, thanks, yes, this is truely usefull to make it persistent to keep a model more readable. 
Batch selecting by clic and drag would also be a very nice productivity booster.

**Comment by rkhaotix** [comment]
The batch selecting is already present. Hold SHIFT and click a blank area to avoid select a single object & drag the mouse. A blue rectangle will be displayed as you move the mouse. Release the SHIFT and mouse button to select all object inside the rectangle! :)

**Comment by haubourg** [comment]
Oh nice! I was tricked by the fact that I had the schema rectangle object under my "clic" tests! Thanks!
