### ISSUE TITLE
Running on 4k resolution screen with high font DPI (160) doesn't scale GUI

### ISSUE THREAD

**Issue by archenroot** [pgmodeler/pgmodeler#926]
When working with larger fonts on 4k display I experience hidden parts of text. 

Steps:
- add table
- add single column

Result:
In table view there is tab Columns with table of Name,Type,Default Value and Attribute columns. The height of each line in this table doesn't scale with the font and has less height then the column, so top/bottom part of text is hidden and is badly visible.

Still unbeatable tool, I have as well license and being happy to pay for this kind of software.

**Comment by rkhaotix** [comment]
Hi @archenroot !

Thanks for reporting. 
This is a known issue. Currently, I don't have the opportunity to test/fix the problem due to the lack of a hi-res monitor. As soon as I get one, this will be the first issue I'll work on! :)

**Comment by archenroot** [comment]
:-)))) ok buddy
