### ISSUE TITLE
Data manipulation

### ISSUE THREAD

**Issue by GitStorageOne** [pgmodeler/pgmodeler#927]
Hello!

In data manipulation window, json value editing not handy.
Each time, when i want send changes, each "{" and "}" character must be escaped, as stated at bottom of form. Once value saved, if i need correct value one more time, each "{" and "}" character must be escaped again. For big json objects it's not good behavior. 

Suppose, that since PostgreSQL support JSON type, "{" and "}" should not be used internally.
Suggest to use "{{" and "}}" for internal purposes, like in angular :)

And how to disable italic font in SQL execution pane?

(using pre-compilled 0.9.0.alpha1)

**Comment by rkhaotix** [comment]
Hi!

That's really annoying. I have forgot about json data :/
I'll change the character used to enclose special data .

About italic in SQL pane, you should edit by hand the file sql-highlight.conf stored in your user's config storage. The manipulation of syntax highlight is not open to the user for now.

Which OS pgModeler is running on your machine?

**Comment by GitStorageOne** [comment]
Thanks for response!
I use windows x64 version.

**Comment by rkhaotix** [comment]
No problem! :)

Well, look for the mentioned file in C:\Users\[your user]\AppData\Local\pgmodeler

The sql-highlight.conf file is xml based so there is no difficult in change it.
