### ISSUE TITLE
Error compiling on Windows 7, QT 5.6.2

### ISSUE THREAD

**Issue by fernandoc1** [pgmodeler/pgmodeler#929]
I'm trying to compile version 0.9.0 alpha 1, by I'm facing  the following error:

c:/Qt/Qt5.6.2/Tools/mingw492_32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lutils

**Comment by ramonhoyo** [comment]
I'm facing the same problem, did you solved this?
Regards.

**Comment by losbaltica** [comment]
Same error here on:
Windows 10 Pro
Qt 5.9.6
MinGW 5.3.0 32bit

C:/Qt/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lutils
collect2.exe: error: ld returned 1 exit status

**Comment by ramonhoyo** [comment]
@losbaltica , you're trying to compile from console or using IDE?

**Comment by ramonhoyo** [comment]
You may try copy manually the utils.dll in the compilation directory, I'm not 100% secure because it was some time ago. But if you try from IDE you need disable "shadow built" in project configuration. Regards.

**Comment by losbaltica** [comment]
In compilation directory, I got utils.dll already, not sure from where. Is it better to run it through IDE? Did you manage to compile it if so on which software?

**Comment by losbaltica** [comment]
Ok, I manage to compile it 🥇  When I downgrade Qt from 5.9.6 to 5.9.3 it works fine
