### ISSUE TITLE
Generate SQL without setting owner in pgmodeler-0.9.0-alpha1

### ISSUE THREAD

**Issue by static-max** [pgmodeler/pgmodeler#933]
Hi,

I made a small model without setting the owner on my tables. When I export the model as SQL file, it contains "ALTER TABLE ... OWNER TO postgres".
I don't want these set owner statements, however it seems that every table, relation etc. must have an owner set as I cannot set the Owner to "empty".
Is there a way to omit the "ALTER TABLE ... OWNER TO postgres" statements?

Thanks a lot

**Comment by rkhaotix** [comment]
Nope. Owner is optional.
Just open the object's dialog and clear the onwer field. You can also setup default owner as empty in Database editing dialog, this way, any object you create will have no owner.

**Comment by static-max** [comment]
You're right, my bad.
