### ISSUE TITLE
GRANT permission for column error

### ISSUE THREAD

**Issue by TakhirFakhrutdinov** [pgmodeler/pgmodeler#936]
when I grant permission SELECT,UPDATE for one column of table, pgmodeler generate next command:
-- object: grant_f2ee8e43dc | type: PERMISSION --
GRANT SELECT,INSERT
  (recid) ON TABLE mn.t_instrattr
   TO __public__;
-- ddl-end --

but postgresql mean two separate command:
1. GRANT SELECT ON TABLE mn.t_instrattr TO __public__;
2. GRANT INSERT (recid) ON TABLE mn.t_instrattr TO __public__;

**Comment by TakhirFakhrutdinov** [comment]
It would be nice to be able to generate one GRANT command^ for example
GRANT SELECT(col1,col2,col3),INSERT(col1,col2),UPDATE(col3),DELETE
on table table1 to public;

**Comment by rkhaotix** [comment]
Thanks for reporting!
I'll fix that as soon as possible!

**Comment by rkhaotix** [comment]
Actually, reviewing the issue again and testing the software I don't see any problem in the current generated syntax.

**Comment by TakhirFakhrutdinov** [comment]
Now pgmodeler generates two commands at once. Why? 

-- object: grant_314f6c96f7 | type: PERMISSION --
GRANT SELECT(attr),INSERT(attr)
   ON TABLE mn.t_docattr
   TO __public__;

GRANT SELECT(attr),INSERT(attr)
   ON TABLE mn.t_docattr
   TO __public__ WITH GRANT OPTION;
-- ddl-end --

**Comment by rkhaotix** [comment]
Oops. Found the problem. Fix on the way!

**Comment by rkhaotix** [comment]
Try this commit 13f9342aa4861e44ae6549d6ccdb5b39c8f89d38

**Comment by TakhirFakhrutdinov** [comment]
Thanks, all worked well
