### ISSUE TITLE
Error Create Table SQL

### ISSUE THREAD

**Issue by vcantidio** [pgmodeler/pgmodeler#939]
All SQL Create Table comes with an extra comma after the last field.

CREATE TABLE public.t_org(
	zk_org serial,
	zk_org_mas integer,
	cd_org varchar(3),
	nm_org text,

);

This causes the error:

Could not execute the SQL command.
 Message returned: `ERROR:  syntax error at or near ")"
LINE 6: );
        ^
Can you help me?

Valder Cantidio

**Comment by d3xter** [comment]
Simple workaround is to add a Primary Key to the table.

But this is obviously a bug
