### ISSUE TITLE
Can't disable ALTER ROLE

### ISSUE THREAD

**Issue by antoine-pous** [pgmodeler/pgmodeler#945]
Hi!

If the role doesn't have the privileges to alter itself pgmodeler can't export to pgsql...

Currently the remote role is absolutely the same as the one on pgmodeler and I still have this alteration in diff
```sql
-- [ Changed objects ] --
ALTER ROLE user;
```

I'm on pgmodeler 0.9.0-beta1

**Comment by rkhaotix** [comment]
You workaround this problem by forcing pgModeler to ignore the error by its code. Just inform the error code in the highlighted box and rerun the diff.

If my memory serves the error code is 42501 (insufficient_privilege) but you can confirm it here: https://www.postgresql.org/docs/current/static/errcodes-appendix.html

![diff_advanced_tab](https://cloud.githubusercontent.com/assets/2205476/25131156/1c05b650-241b-11e7-9907-f64e3ad9a06b.png)

**Comment by antoine-pous** [comment]
I've found this workaround but the error is `42501	insufficient_privilege` i can't ignore it globally just for this issue :/
