### ISSUE TITLE
building 0.8.2

### ISSUE THREAD

**Issue by humanitiesNerd** [pgmodeler/pgmodeler#947]
Building pgmodeler 0.8.2, I get this

Project ERROR: libpq development package not found

But both postgresql and libpg are available

In fact, these 2 lines are copied from the .qmake.stash file

```
QMAKE_DEFAULT_INCDIRS = \
...
    /gnu/store/wg123wvq0s4zj5dclfkybgir9a4kw86z-postgresql-9.6.2/include \
...
QMAKE_DEFAULT_LIBDIRS = \
...
    /gnu/store/wg123wvq0s4zj5dclfkybgir9a4kw86z-postgresql-9.6.2/lib \
```

What is Qmake exactly looking for ?

Thanks

**Comment by antoine-pous** [comment]
> Project ERROR: libp**q** development package not found
> But both postgresql and libp**g** are available

Are you sure about that?

**Comment by mbrumbelow** [comment]
1. Did you build PostgreSQL from the command line?
2. What output do you get with this command: 'pkg-config libpq --cflags --libs' ?

**Comment by humanitiesNerd** [comment]
2017-05-01 16:20 GMT+02:00 Michael Brumbelow <notifications@github.com>:

>
>    1. Did you build PostgreSQL from the command line?
>    2. What output do you get with this command: 'pkg-config libpq
>    --cflags --libs' ?
>
>
Ok, I apologize

pkg-config was not reachable in the build environment

Thanks for your help

**Comment by nboisteault** [comment]
Can you close issue? Thanks

**Comment by humanitiesNerd** [comment]
Sure, sorry
