### ISSUE TITLE
hidden hyphen in installation page

### ISSUE THREAD

**Issue by nboisteault** [pgmodeler/pgmodeler#951]
Hi and thank you for your great tool,

I've been surprised to discover an hidden hyphen in mingw32**-**make.exe in installation page. As you see in the capture it is not visible in chrome nor firefox so if you don't copy/paste you miss it.
And even if you copy/paste in git client the hyphen pasted is not correct.
I think many users can have a headache with this kind of behavior.
What the purpose of soft hyphen here?

![image](https://cloud.githubusercontent.com/assets/2145040/26047766/c580d072-3954-11e7-8e45-9a9dc478e696.png)

**Comment by rkhaotix** [comment]
Whoa! That's not good!

There's no purpose to "hide" that hyphen there... is just a bug in the HTML! 
I'll fix it right now!

Thanks for reporting.

**Comment by rkhaotix** [comment]
Done! :)

![installation](https://cloud.githubusercontent.com/assets/2205476/26103765/5d1c68f8-3a11-11e7-86c3-625f6b169d08.png)

**Comment by nboisteault** [comment]
Good! ;-)
