### ISSUE TITLE
accept (do not fail on) future versions

### ISSUE THREAD

**Issue by rob-miller** [pgmodeler/pgmodeler#954]
There is a previous, closed bug report referencing this for postgresql 9.5; the solution there was upgrading to the current release with support for 9.5, but that is not the complete fix.

My sequence of events: 
load schema, make change, really for documentation only so I know I added a table in database.
save -> not validated -> save anyway or validate
-> validate
validation failed due to unsupported postgres version (9.6, this is pgmodeler 0.82)
save -> can't save due to validation error
quit without save

restart
load last session / open -> ERR_ASG_EMPTY_XML_BUFFER (155) ; ERR_LOAD_INV_MODEL_FILE (161)

The preferred outcome is:
- not corrupt the model file
- be able to 'save anyway' even after model is invalidated

Please remember that it is not always possible to update to a newer version.

**Comment by rkhaotix** [comment]
The problem with allowing not support versions is that it may cause critical failures in export, import and diff process. But I'll make pgModeler assume the most recent supported PostgreSQL version when connecting to a server with an unsupported version. For instance, connecting to a PostgreSQL 10.0-beta will cause pgModeler to use 9.6 and rely on the server's backward compatibility.

**Comment by rob-miller** [comment]
Thanks!
