### ISSUE TITLE
Add trigger as function from extension

### ISSUE THREAD

**Issue by dldamilola** [pgmodeler/pgmodeler#960]
I'm using temporal_tables extension and I have it in my model. I need to add trigger from extension function versioning() but pgModeler refuses to accept this function name. 
Is there a way to create such trigger? Or I should use append SQL?

**Comment by rkhaotix** [comment]
Could you please elaborate?
Are you trying to name the funciton "versioning" or "versioning()" [note the parentheses]?

**Comment by dldamilola** [comment]
The problem is not with trigger name or function name.
Then I try to fill in "function" field in "trigger properties" I get "select function" window with functions only from db/schema.

**Comment by dldamilola** [comment]
I try to fix it by adding my function with the same name and exclude it from generation. So I successfully validate my model. But on diff with DB I get error
`[6] src/databasemodel.cpp (5352)
  Trigger *DatabaseModel::createTrigger()
    [ERR_ASG_OBJ_INV_DEFINITION] The object versioning_trigger (Trigger) has inconsistent SQL or XML definition!
       ** <trigger name="versioning_trigger" firing-type="BEFORE" per-line="true" constraint="false"
	 ins-event="true" del-event="true" upd-event="true" trunc-event="false" arguments="sys_period,history,true"
	 table="table">
		
</trigger>`
