### ISSUE TITLE
Successfully built source of 0.9.0 beta 1  on Windows 7, But cannot start it on Windows 10

### ISSUE THREAD

**Issue by Robban1980** [pgmodeler/pgmodeler#967]
So i managed to finally build the 0.9.0 beta 1  on Windows 7 virtual machine. 
pgModeler starts fine on windows 7. However when i copy the full build to Windows 10 it throws the below error on start 
Any ideas on what i might be missing in the Windows 10 environment?

![image](https://cloud.githubusercontent.com/assets/5434244/26822100/de067c96-4ae3-11e7-9361-c7d796ebc917.png)

**Comment by rkhaotix** [comment]
It seems that you're missing some dlls... 

Don't forget to run ```$QTBIN/windeployqt pgmodeler.exe``` where ```$QTBIN```is the path to main executables of Qt framework. And make sure to copy the following dlls to the executable's root directory:

```
Assuming that:
$QMAKE_ROOT = path where qmake command is found
$MINGW_ROOT = path where mingw32-make is found
$PGSQL_ROOT = path where PostgreSQL main dlls are found

Copy the dlls:
$QMAKE_ROOT/icudt55.dll
$QMAKE_ROOT/icuin55.dll
$QMAKE_ROOT/icuuc55.dll
$MINGW_ROOT/libgcc_s_seh-1.dll
$MINGW_ROOT/libstdc++-6.dll
$MINGW_ROOT/libwinpthread-1.dll
$PGSQL_ROOT/libiconv-2.dll
$PGSQL_ROOT/libintl-8.dll
$PGSQL_ROOT/libpq.dll
$PGSQL_ROOT/libxml2.dll
```
Note that filenames may change a bit depending on the framework version or database server you're running.

**Comment by Robban1980** [comment]
@rkhaotix thank yo so much. Copying the DLL's was the missing step, now it is running just fine on Windows 10.

**Comment by rkhaotix** [comment]
No problem! :)
