### ISSUE TITLE
Version 0.9.0 Beta1 on Windows 10, minimizing then maximizing the window shows the "Model restoration" window

### ISSUE THREAD

**Issue by Robban1980** [pgmodeler/pgmodeler#968]
I just started testing version 0.9.0 Beta1 and realized that every time pgModeler is minimized with a model open, and the window i opened again the Model Restoration dialog will show up like below.

![image](https://cloud.githubusercontent.com/assets/5434244/26833857/9787f4e0-4b0e-11e7-8e6f-e3870a435baa.png)

**Comment by rkhaotix** [comment]
Ohh... that's not good! :(
I've changed the behavior of model restoration dialog but did not expect that! I'll fix it right now and see if I  can release an emergency patch. This issue can be really annoying!

Thanks for reporting!
