### ISSUE TITLE
sslmode value "require" invalid when SSL support is not compiled in

### ISSUE THREAD

**Issue by alexander-zakharov** [pgmodeler/pgmodeler#973]
the compiled module I've downloaded for Mac doesn't work
(latest beta - didn't try current)

**Comment by alexander-zakharov** [comment]
I downloaded linux version of the modeler and run it in virtual box machine - that version works fine.
can you please rebuild Mac release with included libraries

**Comment by jstnlvns** [comment]
Assuming since this is still open it hasn't been addressed.
I'm receiving `Could not connect to the database.
Message returned: sslmode value "verify-ca" invalid when SSL support is not compiled in`

**Comment by chrispytoes** [comment]
I also have the same error on Windows, version 1.0.6. `sslmode value "require" invalid when SSL support is not compiled in`

I am using a DigitalOcean managed database, and it sslmode is required to connect. I am providing my certificate. I am able to connect with pgAdmin just fine.
