### ISSUE TITLE
Error trying to import postgres tables in pgModeler

### ISSUE THREAD

**Issue by santoshtalks** [pgmodeler/pgmodeler#974]
Hi,

I am getting below errors while trying to import some tables from postgres into pgModeler for reverse engineering. Any help on resolving this would be appreciated.

[3] src/databaseimporthelper.cpp (2042)
  void DatabaseImportHelper::createPermission(attribs_map&)
    [ERR_CUSTOM] The object `permission_readonly=r/tm_pmpml' (Permission) is referencing the object `readonly' (Role) which was not found in the model!

[2] src/databaseimporthelper.cpp (503)
  void DatabaseImportHelper::createPermissions()
    [ERR_CUSTOM] The object `permission_readonly=r/tm_pmpml' (Permission) is referencing the object `readonly' (Role) which was not found in the model!

[1] src/databaseimporthelper.cpp (642)
  void DatabaseImportHelper::importDatabase()
    [ERR_CUSTOM] The object `permission_readonly=r/tm_pmpml' (Permission) is referencing the object `readonly' (Role) which was not found in the model!

[0] src/databaseimportform.cpp (413)
  void DatabaseImportForm::captureThreadError(Exception)
    [ERR_CUSTOM] The object `permission_readonly=r/tm_pmpml' (Permission) is referencing the object `readonly' (Role) which was not found in the model!

**Comment by rkhaotix** [comment]
Hi! Sorry the delay , I'm on a vacation and I'm trying to respond any email as fast as I can.

What is the release you're running? Could you please send me a dump of your database without data?

**Comment by santoshtalks** [comment]
Sorry, didn't understand your question. Release of postgresql or pgmodeler?
It won't be possible to send the database dump as we only have read-only
access on it.
