### ISSUE TITLE
Support language "internal" in CREATE FUNCTION.

### ISSUE THREAD

**Issue by tschoening** [pgmodeler/pgmodeler#978]
pgModeler supports various languages for `CREATE FUNCTION`, but the documented one `internal` isn't among those:

> lang_name
> The name of the language that the function is implemented in. Can be SQL, C, internal, or the name of a user-defined procedural language.

https://www.postgresql.org/docs/9.0/static/sql-createfunction.html

I have a use-case in which I need a function using that language and without that I cannot create the function and everything else that relies on that, in my example a custom type. While one is able to workaround this with Custom SQL, it makes maintenance of the schema pretty hard, because nothing within pgModeler can use those function, types, CASTs etc.

https://stackoverflow.com/questions/45188301/how-to-use-original-postgres-input-output-function-in-create-type

So please consider adding that language as well. Thanks!

**Comment by rkhaotix** [comment]
Hi!

In that case you could use a fake language object for a temporary solution. Just create a language named "internal" and deactivate its SQL code generation. 

I'll add the mentioned lang in the next patch!

Thanks for reporting!
