### ISSUE TITLE
gist index not imported correctly

### ISSUE THREAD

**Issue by bob-wiegand** [pgmodeler/pgmodeler#979]
This is a minor/rare issue but thought I'd report it for tracking purposes.
Exporting .sql for a gist index (or looking at the .dbm file) indicates that import is not working.

Here are sample commands for creating a database:

CREATE EXTENSION btree_gist;

CREATE TABLE public.pdata(
    t1 int NOT NULL,
    t2 int NOT NULL
);

CREATE INDEX pt_idx ON public.pdata
    USING gist
    (
        pid,
        int4range(t1, t2)
    );

Exporting to sql after importing this database includes
-- object: pt_idx | type: INDEX --
-- DROP INDEX IF EXISTS public.pt_idx CASCADE;
CREATE INDEX pt_idx ON public.pdata
    USING gist
    (
      (int4range(t1)
    )   WITH (FILLFACTOR = 90);
-- ddl-end --

**Comment by rkhaotix** [comment]
Could confirm that.
I'll check what's wrong and apply the fix to the next release. thanks!
