### ISSUE TITLE
Pgmodeler don't delete constraints

### ISSUE THREAD

**Issue by antoine-pous** [pgmodeler/pgmodeler#987]
Hi !

When i create a new constraint PgModeler create it on export, but if i delete an existing constraint without deleting the column PgModeler don't delete it on the live DB.

To reproduce it follow these steps:

- Create a column and add unique constraint on it
- Export on pgsql
- Delete the unique constraint
- Export on pgsql 

The constraint is not deleted

**Comment by rkhaotix** [comment]
Hi!

You should use the diff operation not the export.
The diff was designed for that purpose, on the other hand the export process is not smart enough to detect that you've removed the constraint or any other object in the model so this scenario can be replicated to the live DB.

**Comment by antoine-pous** [comment]
Oh, i see.

Thank you! :+1:
