### ISSUE TITLE
Unable to run compiled version on x64 Windows

### ISSUE THREAD

**Issue by amather** [pgmodeler/pgmodeler#988]
Thanks for this great project!

I'm unable to run pgmodeler.exe after building it:

Versions:
OS: Win7 x64
QT: 5.6.2 32bit mingw 4.9.2
PostgreSQL: 9.6 (32bit, zip download)

Build Steps:
* qmake
* mingw32-make
* mingw32-make install
* cd build
* windeployqt pgmodeler.exe

Build runs fine, running pgmodeler.exe first results with missing libxml2.dll. Copied manually from postgres folder.

Running pgmodeler.exe then finally results in 'The application was unable to start correctly (0xc000007b). Click OK to close the application' message.

Any ideas on how to fix this?

**Comment by ziben** [comment]
You should copy the three dll  file from pgsql's bin folder to the build folder.

libiconv-2.dll
libintl-8.dll
ssleay32.dll

**Comment by ThalysonRA** [comment]
Fiz isso, mas não funciona. Continua dando o mesmo erro.
