### ISSUE TITLE
I noticed some compilation issues with latest beta version on Gentoo linux

### ISSUE THREAD

**Issue by archenroot** [pgmodeler/pgmodeler#990]
Gentoo uses its own build system, where you define ebuild images. When I run against PG 9.6 database, I am failing on:
```
>>> Configuring source in /tmp/portage/dev-db/pgmodeler-0.9.0_beta2/work/pgmodeler-0.9.0-beta2 ...
 * Running qmake ...
Info: creating stash file /tmp/portage/dev-db/pgmodeler-0.9.0_beta2/work/pgmodeler-0.9.0-beta2/.qmake.stash
Project ERROR: libpq development package not found                                                                                                    [ !! ]

 * Running qmake has failed! (see above for details)
 * This shouldn't happen - please send a bug report to https://bugs.gentoo.org/

 * ERROR: dev-db/pgmodeler-0.9.0_beta2::archenroot failed (configure phase):
 *   eqmake5 failed
```
The previous version 0.8.* worked fine, I used actually completely same buidling file (same dependencies) to build and the libpq file is of course available on my system.

I am now not sure if it is issue with my system(due to some changes I did) or you do something now in different way than before?

**Comment by rkhaotix** [comment]
Hi @archenroot 

No. The build process hasn't changed!
Maybe you need to install the development packages... postgresql-devel or libpq-devel or something like that, no?

**Comment by archenroot** [comment]
I found I have some corrupted installation of postgresql where this dependency is auto provided. I upgraded from 9.5 to 9.6 recently, all ok, but I see now some links under /usr/lib64 points to 9.5 which doesn't exists... will check

**Comment by archenroot** [comment]
Ok, it was problem with my upgrade, lots of missing links, I cleared the system out of nonworking links:
`find . -xtype l |xargs -0 rm`

Now I am able to compile, so not an issue with pgmodeller :-)

@rkhaotix thx for quick response.

**Comment by rkhaotix** [comment]
No problem! :)
I'm here to help. :D
