### ISSUE TITLE
db import fails

### ISSUE THREAD

**Issue by kneeke** [pgmodeler/pgmodeler#991]
upon import of a db which uses extension btree_gist
    Could not execute the SQL command.
    Message returned: ERROR: invalid attnum 6 for relation "client_user_id_tsrange_excl"

The index this is referring to is:
"client_user_id_tsrange_excl" EXCLUDE USING gist (user_id WITH =, tsrange(valid_from, valid_until) WITH &&)

**Comment by rkhaotix** [comment]
There's a chance to you to send me a dump of your database? I'll debug the
import process.

Em 4 de set de 2017 4:11 AM, "kneeke" <notifications@github.com> escreveu:

**Comment by kneeke** [comment]
no db dump needed. to reproduce, create a new db and issue:


create extension btree_gist;
create table test (id int, valid_from timestamp, valid_until timestamp);
alter table test add constraint testc1 exclude USING gist (id WITH =, tsrange(valid_from, valid_until) WITH &&);

the resulting db will not import into pg_modeler

**Comment by rkhaotix** [comment]
Ok! I'll test it later.


--
Raphael Araújo e Silva
pgModeler Project Developer

raphael@pgmodeler.com.br
http://pgmodeler.com.br
https://github.com/pgmodeler

2017-09-04 7:55 GMT-03:00 kneeke <notifications@github.com>:

**Comment by rkhaotix** [comment]
I've made a fix and pushed to a new branch '0.9.1-alpha'. Importing is now working (based upon on your test case). If you're able to compile pgModeler from source you can try the patch.
